/**
 * Idwws_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package idw.idwws;

public interface Idwws_PortType extends java.rmi.Remote {
    public double getCicloPadrao(idw.idwws.DwFolha arg0, idw.idwws.OmPt arg1) throws java.rmi.RemoteException;
    public double getPcsPorCicloAtivas(idw.idwws.DwFolha arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpClienteDTO[] getPpClientesDTO(idw.idwws.PpClienteDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpClienteDTO setPpClienteDTO(idw.idwws.PpClienteDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpClienteDTO[] removePpClientesDTO(idw.idwws.PpClienteDTO[] arg0) throws java.rmi.RemoteException;
    public void salvarNovaPpCp(idw.idwws.PpCp arg0) throws java.rmi.RemoteException;
    public idw.idwws.MsicupDTO[] getListaMsicup() throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmpt(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaArea(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmpa(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmgt(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmcc(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtDTO[] getGTsDTO(idw.idwws.GtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtDTO setGTDTO(idw.idwws.GtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtDTO[] removeGTsDTO(idw.idwws.GtDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtDTO ativaGTDTO(idw.idwws.GtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO[] getPTsDTO(idw.idwws.PtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO setPtDTO(idw.idwws.PtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO[] removePTsDTO(idw.idwws.PtDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO ativaPtDTO(idw.idwws.PtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PaDTO validarPaDTO(idw.idwws.PaDTO arg0) throws java.rmi.RemoteException;
    public boolean isMapaValido(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public idw.idwws.LeiturasCODTO setCorrente(idw.idwws.LeiturasCODTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.LeiturasCODTO getCorrente(long arg0) throws java.rmi.RemoteException;
    public idw.idwws.TurnoDTO[] getTurnosDTO(idw.idwws.TurnoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TurnoDTO setTurnoDTO(idw.idwws.TurnoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TAcaoDTO[] getTAcoesDTO(idw.idwws.TAcaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TAcaoDTO setTAcaoDTO(idw.idwws.TAcaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.SessoesDTO heartBeat(java.lang.String arg0, java.util.Calendar arg1) throws java.rmi.RemoteException;
    public idw.idwws.LoginDTO setLoginDTO(idw.idwws.LoginDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.LogoutDTO setLogoutDTO(idw.idwws.LogoutDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EtapaDTO[] getEtapasDTO(idw.idwws.EtapaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EtapaDTO setEtapaDTO(idw.idwws.EtapaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FolhasDTO getFolhasDTO(idw.idwws.FolhaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FolhaDTO setFolhaDTO(idw.idwws.FolhaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ChangeLogBDDTO[] getChangeLogsBDNaoExecutados() throws java.rmi.RemoteException;
    public idw.idwws.ChangeLogBDDTO[] getChangeLogsBDExecutados() throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmprodutoComponente(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmprodutoAgrupador(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwprocedimento(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GrupoUsuarioDTO[] removeGrupoUsuariosDTO(idw.idwws.GrupoUsuarioDTO[] arg0) throws java.rmi.RemoteException;
    public java.lang.Object soma(int n1, int n2) throws java.rmi.RemoteException;
    public boolean ping() throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmprodutoExcessaoProdutoFinal(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmprodutoComponenteComAgrupador(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ConfiguracaoNecessidadeDTO[] pesquisaListaConfiguracaoNecessidadeDTO(idw.idwws.ConfiguracaoNecessidadeDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ConfiguracaoNecessidadeDTO setExclusaoConfiguracoesNecessidadesDTO(idw.idwws.ConfiguracaoNecessidadeDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtGtDTO pesquisarCentrosComCPsDeProdutosIguais(idw.idwws.OmProduto arg0) throws java.rmi.RemoteException;
    public idw.idwws.GraficoDetalhePtDTO getGraficoDetalhePtandroidUltimosCiclosDTO(long idpt, long idturno, java.lang.String dtreferencia) throws java.rmi.RemoteException;
    public idw.idwws.GraficoDetalhePtDTO getGraficoDetalhePtandroidUltimosCiclosBIDTO(long idgt, long idturno, java.lang.String dtreferencia) throws java.rmi.RemoteException;
    public idw.idwws.MsMs pesquisarMsMsPorURLConexaoComParametro(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.UsuarioDTO[] getUsuariosDTO(idw.idwws.UsuarioDTO arg0) throws java.rmi.RemoteException;
    public boolean executarChangeLogBD(idw.idwws.ChangeLogBDDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.UsuarioDTO setUsuarioDTO(idw.idwws.UsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.UsuarioDTO[] removeUsuariosDTO(idw.idwws.UsuarioDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.UsuarioDTO ativaUsuarioDTO(idw.idwws.UsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.UsuarioDTO isUsuarioAutenticado(idw.idwws.UsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.UsuarioDTO getUsuarioDTO(idw.idwws.UsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaTurno(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwFolha(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwEst(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwCal(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwPepro(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwFtParam(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaGrupoProduto(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmgrpusr(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmusr(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmresgui(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmimg(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.OmImg pesquisaOmimgLikeUrl(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmCargo(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwGrpativ(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmEstoque(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmgtFabrica(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmtpgt(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwTParada(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmtppt(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmproduto(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwRap(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmfornecedor(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmprg(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmmapa(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaOmcfgscrpimp(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GrupoUsuarioDTO[] getGrupoUsuariosDTO(idw.idwws.GrupoUsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GrupoUsuarioDTO setGrupoUsuarioDTO(idw.idwws.GrupoUsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GrupoUsuarioDTO ativaGrupoUsuarioDTO(idw.idwws.GrupoUsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DireitoAcessoDTO validarRecursoGUI(idw.idwws.DireitoAcessoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.MonitorizacaoHierarquicaDTO getGtsHierarquico(idw.idwws.OmGt arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtDTO[] getGTsComLayoutDTO(idw.idwws.GtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutosDTO getProdutosDTO(idw.idwws.ProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutoDTO setProdutoDTO(idw.idwws.ProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutosDTO removeProdutosDTO(idw.idwws.ProdutosDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutoDTO ativaProdutoDTO(idw.idwws.ProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FornecedorDTO[] getFornecedoresDTO(idw.idwws.FornecedorDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FornecedorDTO setFornecedorDTO(idw.idwws.FornecedorDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FornecedorDTO ativaFornecedorDTO(idw.idwws.FornecedorDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO[] getAndroidPTsDTO() throws java.rmi.RemoteException;
    public idw.idwws.PtDTO[] getPTsDeGtDTO(idw.idwws.PtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PaDTO[] geracaoAutomaticaPA(idw.idwws.PtDTO arg0, idw.idwws.WizPaDTO arg1, int arg2) throws java.rmi.RemoteException;
    public idw.idwws.MapaPaDTO validarMapaPaDTO(idw.idwws.MapaPaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.AlimentacaoDTO[] getAlimentacoesDTO(idw.idwws.AlimentacaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EtiquetaDTO[] getEtiquetasProduto(idw.idwws.ProdutosDTO arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public idw.idwws.EtiquetaDTO[] getEtiquetasMapas(idw.idwws.MapaAlimentacaoDTO[] arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public idw.idwws.EtiquetaDTO[] getEtiquetasPTs(idw.idwws.PtDTO[] arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public idw.idwws.EtiquetaDTO[] getEtiquetasPAs(idw.idwws.PaDTO[] arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public void importarPrograma(java.lang.String arg0, java.lang.String arg1, boolean arg2) throws java.rmi.RemoteException;
    public idw.idwws.UsuarioCODTO getUsuarioCODTO(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.MapasCODTO getMapasCODTO(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.PosicaoCODTO[] getPosicoesCODTO(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public boolean setConferenciaOuPre(idw.idwws.LeiturasCODTO arg0) throws java.rmi.RemoteException;
    public boolean setRealimentacao(idw.idwws.LeiturasCODTO arg0) throws java.rmi.RemoteException;
    public void assumePreConferencia(java.lang.String arg0) throws java.rmi.RemoteException;
    public boolean isRecursoAcessivel(int arg0, long arg1) throws java.rmi.RemoteException;
    public idw.idwws.ParametroDTO[] getParametrosDTO(idw.idwws.ParametroDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ConfiguracoesDTO getConfiguracoesDTO(idw.idwws.ConfiguracaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ParametroDTO setParametroDTO(idw.idwws.ParametroDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ConfiguracaoDTO setConfiguracaoDTO(idw.idwws.ConfiguracaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ParametroDTO[] removeParametrosDTO(idw.idwws.ParametroDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.TurnoDTO[] removeTurnosDTO(idw.idwws.TurnoDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.TurnoDTO ativaTurnoDTO(idw.idwws.TurnoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TDefeitoDTO[] getTDefeitosDTO(idw.idwws.TDefeitoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TDefeitoDTO setTDefeitoDTO(idw.idwws.TDefeitoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TDefeitoDTO[] removeTDefeitosDTO(idw.idwws.TDefeitoDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.TDefeitoDTO ativaTDefeitoDTO(idw.idwws.TDefeitoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TAcaoDTO[] removeTAcoesDTO(idw.idwws.TAcaoDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.TAcaoDTO ativaTAcaoDTO(idw.idwws.TAcaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GrupoProdutoDTO[] getGruposProdutoDTO(idw.idwws.GrupoProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GrupoProdutoDTO setGrupoProdutoDTO(idw.idwws.GrupoProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GrupoProdutoDTO ativaGrupoProdutoDTO(idw.idwws.GrupoProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.CalendarioDTO[] getCalendariosDTO(idw.idwws.CalendarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.CalendarioDTO setCalendarioDTO(idw.idwws.CalendarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.CalendarioDTO[] removeCalendariosDTO(idw.idwws.CalendarioDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.CalendariosSemanaisDTO wizardCalendario(idw.idwws.CalendarioWizardDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.SessoesDTO inicializacao(java.lang.String arg0, java.util.Calendar arg1) throws java.rmi.RemoteException;
    public idw.idwws.PassagemDTO postoPassagem(idw.idwws.PassagemDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PassagemDTO postoTesteVisual(idw.idwws.PassagemDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PassagemDTO postoReprocesso(idw.idwws.PassagemDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PassagemDTO postoMontagem(idw.idwws.PassagemDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PassagemDTO verificaPassagem(idw.idwws.PassagemDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EtapaDTO[] removeEtapasDTO(idw.idwws.EtapaDTO[] arg0) throws java.rmi.RemoteException;
    public void updateFolhaDTO(idw.idwws.FolhaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FolhasDTO removeFolhasDTO(idw.idwws.FolhasDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.AcoplamentoDTO verificaAcoplamento(idw.idwws.AcoplamentoDTO arg0, idw.idwws.MontagensDTO arg1) throws java.rmi.RemoteException;
    public idw.idwws.DefeitoDTO verificaDefeito(idw.idwws.DefeitoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ComponenteDTO verificaComponente(idw.idwws.ComponenteDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.RoteiroDTO[] getRoteirosDTO(idw.idwws.RoteiroDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.RoteiroDTO setRoteiroDTO(idw.idwws.RoteiroDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.RoteiroDTO[] removeRoteirosDTO(idw.idwws.RoteiroDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.ImgDTO[] getImgsRoteiroDTO(idw.idwws.ImgDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ObjsDTO getArvoreObjsGt(idw.idwws.GtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ObjDTO getOmObjInicializado() throws java.rmi.RemoteException;
    public idw.idwws.ObjsDTO getObjsRoteiroDTO(idw.idwws.ObjDTO arg0) throws java.rmi.RemoteException;
    public void setObjsRoteiro(idw.idwws.DwRota arg0) throws java.rmi.RemoteException;
    public idw.idwws.PassagemDTO postoTesteFuncional(idw.idwws.PassagemDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DetalheColetaDTO[] detalheColeta(long arg0) throws java.rmi.RemoteException;
    public idw.idwws.RelIndTesteFinalDTO getRelIndTesteFinal(idw.idwws.FiltroRelDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FolhasDTO getFolhasporProduto(idw.idwws.ProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EstoquesDTO getEstoquesDTO(idw.idwws.EstoqueDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EstoqueDTO setEstoqueDTO(idw.idwws.EstoqueDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EstoquesDTO removeEstoqueDTO(idw.idwws.EstoquesDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EstoqueDTO ativaEstoqueDTO(idw.idwws.EstoqueDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwRota(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DetalhePTSerieDTO detalheEtapasTeste(long arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaCliente(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpNecListDTO importarPlanilhas(idw.idwws.PpNecListDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwRapDTO[] pesquisaListaRAPDTO(idw.idwws.DwRapDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwRapDTO setExclusaoRAPDTO(idw.idwws.DwRapDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoListDTO pesquisarPlanos(idw.idwws.PlanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisarPlanosBusca(idw.idwws.PlanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpTpplanoListDTO pesquisarTpPlanos(idw.idwws.PpTpplanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpNecListDTO pesquisarPpNecs(java.util.Calendar arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoDTO excluirRegistro(idw.idwws.PlanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwFolhaRap() throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaProgramaIAC(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaProdutoIAC(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwRotapasso getOmPtDwRotapasso(idw.idwws.DwRotapasso arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoListDTO pesquisarPlanoECPs(idw.idwws.PlanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisarPpCliente(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.SapEstoqueDTO[] getSapEstoquesDTO(idw.idwws.SapEstoqueDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTurnosDTO pesquisarTurnos() throws java.rmi.RemoteException;
    public java.lang.String[] getEspecializaApon() throws java.rmi.RemoteException;
    public idw.idwws.MsTpevt[] pesquisarMsTpEvts() throws java.rmi.RemoteException;
    public idw.idwws.OmTppt[] pesquisarOmTppts() throws java.rmi.RemoteException;
    public idw.idwws.MsDetectorDTO[] pesquisarMsDetector(idw.idwws.MsDetectorDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.MsDetectorDTO excluirMsDetectors(idw.idwws.MsDetectorDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpCmDTO salvarCmEstrutura(idw.idwws.PpCmDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FolhasDTO importarCiclos(idw.idwws.FolhasDTO arg0, idw.idwws.UsuarioDTO arg1) throws java.rmi.RemoteException;
    public idw.idwws.DwConsolidDTOs importarProducao(idw.idwws.DwConsolidDTOs arg0, idw.idwws.UsuarioDTO arg1) throws java.rmi.RemoteException;
    public idw.idwws.PpCmDTO[] pesquisarPpCm(idw.idwws.PpCmDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ResultadoImportacaoSapDTO importarPlanilhaSAP(idw.idwws.SapEstoqueDTO[] arg0, idw.idwws.UsuarioDTO arg1) throws java.rmi.RemoteException;
    public idw.idwws.ListaCPDTO pesquisarCpComPedido(idw.idwws.PpCp arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtImgMonitorizacaoDTO getImgsPTsDTO() throws java.rmi.RemoteException;
    public idw.idwws.GtImgMonitorizacaoDTO getImgsGTsDTO() throws java.rmi.RemoteException;
    public idw.idwws.DwFolhaDTO[] getDwFolhasPorCod(idw.idwws.FolhaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaIcDTO getListaIcDTO(idw.idwws.IcDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaIhmDTO getListaIhmDTO(idw.idwws.IhmDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaMSDTO getListaMSDTO(idw.idwws.MsDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaUPDTO getTodosUPDTO() throws java.rmi.RemoteException;
    public idw.idwws.ListaIcDTO getTodosIcDTO() throws java.rmi.RemoteException;
    public idw.idwws.ListaIhmDTO getTodosIhmDTO() throws java.rmi.RemoteException;
    public idw.idwws.ListaUPDTO getListaupDTO(idw.idwws.UpDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaEvtDTO pesquisaListaEvtDTO(java.lang.String arg0, int arg1) throws java.rmi.RemoteException;
    public boolean configuraWebXml(idw.idwws.WebXMLDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.WebXMLDTO pesquisarWebXml() throws java.rmi.RemoteException;
    public idw.idwws.BcDTO[] pesquisarListaBcs(idw.idwws.BcDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaMSDTO importacaoManual(long arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public java.lang.String salvarIcSimplificado(idw.idwws.IcDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TempoRealDTO getUltimoTempoRealPt(idw.idwws.FiltroProducaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwEstlocalDTO[] getDwEstlocal(idw.idwws.DwEstlocalDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwEstlocalDTO setDwEstlocal(idw.idwws.DwEstlocalDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwEstlocalDTO removeDwEstlocal(idw.idwws.DwEstlocalDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwEstlocalproDTO[] getDwEstlocalpros(idw.idwws.DwEstlocalproDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TurnoDTO[] getTodosOsTurnos() throws java.rmi.RemoteException;
    public idw.idwws.ProdutosDTO getTodosProdutosDTO() throws java.rmi.RemoteException;
    public idw.idwws.MonitorizacaoAlimDTO[] getMonitorizacaoAlim() throws java.rmi.RemoteException;
    public idw.idwws.DwRapDTO[] getTodosDwRap() throws java.rmi.RemoteException;
    public idw.idwws.CiclosDTO getUltimosCiclos(idw.idwws.FiltroCiclosDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TurnoAtualDTO getTurnoAtual(idw.idwws.OmPt arg0, java.util.Calendar arg1) throws java.rmi.RemoteException;
    public idw.idwws.TurnoAtualDTO getPeriodoTurno(idw.idwws.FiltroTurnoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.TurnoAtualDTO getTurnoAtualGt(idw.idwws.OmGt arg0, java.util.Calendar arg1) throws java.rmi.RemoteException;
    public idw.idwws.TurnoAtualDTO getTurnoAtual1PTDTO(java.util.Calendar arg0) throws java.rmi.RemoteException;
    public idw.idwws.TurnoAtualDTO getTurnoAtualDTO(idw.idwws.OmPt arg0, java.util.Calendar arg1) throws java.rmi.RemoteException;
    public idw.idwws.CpsDTO setAdiantamentoDTO(idw.idwws.AdiantamentoDTO arg0, idw.idwws.PlanoDTO arg1) throws java.rmi.RemoteException;
    public idw.idwws.DetalheAnaliseGargaloDTO getDetalheCelulas(idw.idwws.FiltroProducaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwParadaDTO[] getParadasDTO(idw.idwws.FiltroRelatorioParadaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTRefugoDTO[] getRefugosDTO(idw.idwws.FiltroRelatorioRefugoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.UsuarioDTO[] getOMUsuariosDTO(idw.idwws.FiltroRelatorioUsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.AlertaDTO[] getAlertasDTO(idw.idwws.FiltroRelatorioAlertaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.AlertaDTO[] getTAlertasDTO(idw.idwws.AlertaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.AlertaDTO setTAlertaDTO(idw.idwws.AlertaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.AlertaDTO[] removeTAlertasDTO(idw.idwws.AlertaDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTJustDTO[] getTJustificativa(idw.idwws.DwTJustDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTJustDTO setTJustificativa(idw.idwws.DwTJustDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTJustDTO[] removeTJustificativa(idw.idwws.DwTJustDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTRefugoDTO[] removeTRefugo(idw.idwws.DwTRefugoDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwProcedimentoDTO[] getDwProcedimento(idw.idwws.DwProcedimentoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwProcedimentoDTO setDwProcedimento(idw.idwws.DwProcedimentoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwProcedimentoDTO[] removeDwProcedimento(idw.idwws.DwProcedimentoDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwGrpativDTO[] removeDwGrpativ(idw.idwws.DwGrpativDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.OmCargoDTO[] removeOmCargo(idw.idwws.OmCargoDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwParadaDTO[] removeTParada(idw.idwws.DwParadaDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtDTO[] getGTsDtoAtivos() throws java.rmi.RemoteException;
    public idw.idwws.ConsolpaDTO[] getConsolpasDTO(idw.idwws.FiltroRelatorioIndiceParadasDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwParadaDTO[] getListaParadas() throws java.rmi.RemoteException;
    public idw.idwws.ProdutoDTO integracaoEstProduto(idw.idwws.ProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutosDTO integracaoEstoque(java.util.Calendar arg0, idw.idwws.UsuarioDTO arg1) throws java.rmi.RemoteException;
    public idw.idwws.RoteiroDTO sugestaoRoteiro(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.DadosRelatorioDTO relatorioTurnoHora(java.util.Calendar arg0) throws java.rmi.RemoteException;
    public idw.idwws.ArquivoTrilhaDTO[] getArquivoTrilha(idw.idwws.FiltroExportacaoTrilhaDTO arg0) throws java.rmi.RemoteException;
    public void setEventoInsert(idw.idwws.EventoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.CpDTO pesquisarMpFaltante(long arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaDwFolhaTesteFuncional(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutosDTO pesquisarProdutosFinaisNoTurno(java.util.Calendar arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public idw.idwws.AcoplamentoDTO verificaComponenteAcoplamento(idw.idwws.AcoplamentoDTO arg0, idw.idwws.MontagensDTO arg1) throws java.rmi.RemoteException;
    public idw.idwws.ConfiguracaoNecessidadeDTO setConfiguracoesNecessidadesDTO(idw.idwws.ConfiguracaoNecessidadeDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpNecListDTO pesquisaListaNecessidadesClientesDTO(idw.idwws.PpNecDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpNecDTO setExclusaoNecessidadesClientesDTO(idw.idwws.PpNecDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EstoqueDTO salvarPrevChegadaMateriaPrima(idw.idwws.EstoquesDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutoDTO importarPlanilhaEstruturaProduto(idw.idwws.ProdutoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanosIndisponibilidadesDTO pesquisarPlanoIndisponibilidade(idw.idwws.PlanoIndisponibilidadeDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoIndisponibilidadeDTO excluirPlanoIndisponibilidade(idw.idwws.PlanoIndisponibilidadeDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoListDTO pesquisarPlanosPlanejamentoProducao(idw.idwws.PlanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoAcompanhamentoDTOList pesquisarAcompanhamentosDoPlano(idw.idwws.PlanoAcompanhamentoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpNecListDTO pesquisarTodosCpComPedidoAtivo() throws java.rmi.RemoteException;
    public idw.idwws.DetalheMonitorizacaoPTInjetDTO getDetalheMonitorizacaoPtInjetDTO(idw.idwws.FiltroDetalhePTInjetDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutosDTO pesquisarProdutosPaiDisponiveis(long arg0) throws java.rmi.RemoteException;
    public idw.idwws.ConfiguraHibernateDTO pesquisaConfiguracaoHibernate(int arg0) throws java.rmi.RemoteException;
    public idw.idwws.MonitorizacaoAlimDTO[] getMonitorizacaoAlimComFiltro(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.GraficoDetalhePtFornoDTO getGraficoDetalhePtFornoDTOAndroid(long idpt, long idturno, java.lang.String dtreferencia, long idCp) throws java.rmi.RemoteException;
    public idw.idwws.ListaPerdasmpDTO getGraficoPerdasMateriaPrimaDTO(idw.idwws.FiltroGraficoDetalhePtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtRtMonitorizacaoDTO getGtRtMonitorizacaoTmAndroidDTO(long idturno, long idgt, java.lang.String dtreferencia) throws java.rmi.RemoteException;
    public idw.idwws.PpNecListDTO integracaoPlanoProducaoPeriodo(java.util.Calendar arg0, java.util.Calendar arg1, idw.idwws.UsuarioDTO arg2, boolean arg3) throws java.rmi.RemoteException;
    public idw.idwws.DetalheMonitorizacaoPTInjetDTO getDetalheMonitorizacaoPTAndroid(java.lang.String dtreferencia, long iddwconsolid, java.lang.String dtreferenciainicial, java.lang.String dtreferenciafinal, long idturno, long iddwrap, long idpt, long idgt, long idproduto, java.lang.String cdCp) throws java.rmi.RemoteException;
    public idw.idwws.GraficoDetalhePtDTO getGraficoDetalhePTandroidDTO(long idpt, long idturno, long idfolha, java.lang.String dtReferencia, java.lang.String dtReferenciainicial, java.lang.String dtReferenciafinal, long idCp, java.lang.String tpId, int limiteMaxresult) throws java.rmi.RemoteException;
    public idw.idwws.GraficoDetalhePtDTO getGraficoDetalhePTandroidDTOPorHora(long idpt, java.lang.String dtReferenciainicial, java.lang.String dtReferenciafinal) throws java.rmi.RemoteException;
    public idw.idwws.GraficoDetalhePtDTO getGraficoDetalhePTandroidBIDTO(long idgt, long idturno, long idfolha, java.lang.String dtReferencia, java.lang.String dtReferenciainicial, java.lang.String dtReferenciafinal) throws java.rmi.RemoteException;
    public idw.idwws.DetalhamentoProducaoDTO getDetalhamentoProducaoDTOAndroid(long iddwconsolid, java.lang.String dtreferenciainicial, java.lang.String dtreferenciafinal, long idpt) throws java.rmi.RemoteException;
    public idw.idwws.DwFolhaDTO[] getGraficoDetalhePadraoandroidDTO(long idpt, long idfolha, java.lang.String dtreferencia) throws java.rmi.RemoteException;
    public idw.idwws.DwFolhaDTO[] getGraficoDetalhePadraoandroidBIDTO(long idgt, long idfolha, java.lang.String dtreferencia) throws java.rmi.RemoteException;
    public idw.idwws.MonitorizacaoHierarquicaDTO getMonitorizacaoHierarquicaDTO(idw.idwws.FiltroProducaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DetalhamentoParadaDTO getOcorrenciaParettoParadaDTO(java.util.Calendar arg0, java.math.BigDecimal arg1, java.math.BigDecimal arg2, boolean arg3, boolean arg4, java.math.BigDecimal arg5, java.lang.String arg6) throws java.rmi.RemoteException;
    public idw.idwws.DetalhamentoParadaDTO getOcorrenciaBIParettoParadaDTO(java.util.Calendar arg0, java.util.Calendar arg1, java.math.BigDecimal arg2, java.math.BigDecimal arg3, java.math.BigDecimal arg4, boolean arg5, boolean arg6, java.math.BigDecimal arg7, java.lang.String arg8) throws java.rmi.RemoteException;
    public idw.idwws.OmObjDTO[] obterMonitorizacaoVisaoRoteiro(java.util.Calendar arg0, java.lang.String arg1, java.lang.String arg2) throws java.rmi.RemoteException;
    public idw.idwws.GtDTO[] getAndroidGTsComLayoutDTO() throws java.rmi.RemoteException;
    public idw.idwws.FornecedorDTO[] removeFornecedoresDTO(idw.idwws.FornecedorDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.MapaAlimentacaoDTO[] getMapasAlimentacaoDTO(idw.idwws.MapaAlimentacaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.MapaAlimentacaoDTO setMapaAlimentacaoDTO(idw.idwws.MapaAlimentacaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.MapaAlimentacaoDTO[] removeMapasAlimentacaoDTO(idw.idwws.MapaAlimentacaoDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.MapaAlimentacaoDTO ativaMapaAlimentacaoDTO(idw.idwws.MapaAlimentacaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ComponenteDeParaDTO[] importarComponentesDePara(idw.idwws.ComponenteDeParaDTO[] arg0) throws java.rmi.RemoteException;
    public boolean isProdutoEAlternativo(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException;
    public idw.idwws.HomologacoesDTO validarHomologacoesUsrPt(idw.idwws.HomologacoesDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.HomologacoesDTO validarHomologacoesUsrGt(idw.idwws.HomologacoesDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.HomologacoesDTO validarHomologacoesGt(idw.idwws.HomologacoesDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.HomologacoesDTO validarHomologacoesPt(idw.idwws.HomologacoesDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ConfiguracoesDTO removeConfiguracoesDTO(idw.idwws.ConfiguracoesDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GrupoProdutoDTO[] removeGruposProdutoDTO(idw.idwws.GrupoProdutoDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.CalendarioPtsDTO validarCalendarioPtsDTO(idw.idwws.CalendarioPtsDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.CalendariosSemanaisDTO getCalendariosSemanaisDTO(idw.idwws.CalendarioSemanalFiltroDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PassagemDTO obtemNaoConformidadesAtuais(idw.idwws.PassagemDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtRtMonitorizacaoDTO getGtRtMonitorizacaoDTO(idw.idwws.GtRtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtRtMonitorizacaoDTO getGtRtMonitorizacaoAcum(idw.idwws.GtRtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DetalhePTGraficoTesteFuncionalDTO getGraficoTesteFuncional(idw.idwws.FiltroDetalhePTDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaUnidadeMedida(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpNecimpurllogListDTO pesquisarAbasByUrlLog(idw.idwws.PpNecimpurllogListDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpNecDTO setNecessidadesClientesDTO(idw.idwws.PpNecDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.IndicadorMinMetaMaxDTO[] buscarIndicadoresMinMetaMax(idw.idwws.FiltroIndCfg arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtGtDTO pesquisarCentrosTrabalho() throws java.rmi.RemoteException;
    public idw.idwws.PlanoDTO salvarPlanoManipulacao(idw.idwws.PlanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.EstoquesDTO pesquisarEstoqueMateriaPrima(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2) throws java.rmi.RemoteException;
    public idw.idwws.SapConhecimentoDTO[] getSapConhecimentosDTO(idw.idwws.SapConhecimentoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO[] pesquisarOmPtsAtivosComGt() throws java.rmi.RemoteException;
    public idw.idwws.DwConsolidDTOs pesquisarApontamentoProducao(idw.idwws.DwConsolidDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwFolhaDTO[] pesquisaProdutoNaFolha(java.lang.String arg0, long arg1) throws java.rmi.RemoteException;
    public idw.idwws.DwConsolidDTO salvarApontamentoProducao(idw.idwws.DwConsolidDTOs arg0) throws java.rmi.RemoteException;
    public idw.idwws.TmgConhecimentoDTO[] getTmgConhecimentosDTO(idw.idwws.TmgConhecimentoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.MsDetectorDTO salvarAlertaPlanejamento(idw.idwws.MsDetectorDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoIndisponibilidadeDTO salvarPlanoIndisponibilidade(idw.idwws.PlanoIndisponibilidadeDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaCPDTO pesquisaListaPredecessoraCP(long arg0) throws java.rmi.RemoteException;
    public idw.idwws.CpsDTO pesquisarCpByProdutoFinal(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.ObjsLayoutRoteiroDTO getObjsLayoutRoteiroDTO() throws java.rmi.RemoteException;
    public idw.idwws.IcDTO pesquisarMsIcPorUrlConexao(java.lang.String arg0) throws java.rmi.RemoteException;
    public boolean salvarConfiguracoesHibernate(idw.idwws.ConfiguraHibernateDTO arg0, int arg1) throws java.rmi.RemoteException;
    public boolean salvarConfiguracaoLog4J(idw.idwws.Log4JDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.Log4JDTO carregarPropriedadesLog4JDTO() throws java.rmi.RemoteException;
    public boolean isUsuarioOperadorAutenticado(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2) throws java.rmi.RemoteException;
    public void carregaTabelasBasicas() throws java.rmi.RemoteException;
    public idw.idwws.CiclosDTO getUltimosCiclosAndroid(long idpt, long idCp) throws java.rmi.RemoteException;
    public idw.idwws.GraficoDetalhePtDTO getGraficoDetalhePtDTO(idw.idwws.FiltroGraficoDetalhePtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GraficoDetalhePtFornoDTO getGraficoDetalhePtFornoDTO(idw.idwws.FiltroGraficoDetalhePtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwFolhaDTO[] getGraficoDetalhePadraoDTO(idw.idwws.FiltroGraficoDetalhePtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DetalhamentoProducaoDTO getDetalhamentoProducao(idw.idwws.FiltroDetalheProducaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaDetalheAnaliseTurnoDTO getDetalheAnaliseTurno(idw.idwws.FiltroProducaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DetalhamentoParadaDTO getDetalhamentoParada(idw.idwws.FiltroDetalhePTInjetDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwGrpativDTO[] getTodosDwGrpativAtivos() throws java.rmi.RemoteException;
    public idw.idwws.OmCargoDTO[] getTodosOmCargosAtivos() throws java.rmi.RemoteException;
    public idw.idwws.DwFolhaDTO[] getTodasDwFolhasAtivas() throws java.rmi.RemoteException;
    public idw.idwws.DwFolhaDTO[] getDwFolhaDoProcedimento(idw.idwws.DwProcedimento arg0) throws java.rmi.RemoteException;
    public void integrarEstoqueFuturo(idw.idwws.PeriodoDTO arg0, idw.idwws.UsuarioDTO arg1) throws java.rmi.RemoteException;
    public void integracaoApontamentoDiario(idw.idwws.UsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DadosRelatorioDTO relatorioPlanejadoRealizado(java.util.Calendar arg0, java.util.Calendar arg1) throws java.rmi.RemoteException;
    public idw.idwws.DadosRelatorioDTO relatorioMapaEscadinha(idw.idwws.DadosRelatorioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ProdutosDTO getListaProdutosFiltrosBIDTO(idw.idwws.FiltroDetalhePTInjetDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GraficoBIParetoDTO getGrafBIParetoPerdas(idw.idwws.FiltroDetalhePTInjetDTO arg0, idw.idwws.DetalheMonitorizacaoPTInjetDTO arg1) throws java.rmi.RemoteException;
    public idw.idwws.GraficoBIItemRecorrenciaDTO[] getGraficoBIRecorrencia(idw.idwws.FiltroDetalhePTInjetDTO arg0, byte arg1, java.lang.String arg2) throws java.rmi.RemoteException;
    public idw.idwws.GtDTO pesquisarOmGtPorIdOuCd(idw.idwws.OmGt arg0) throws java.rmi.RemoteException;
    public idw.idwws.GraficosParettoParadaDTO getGraficoParettoParadaDTO(java.util.Calendar arg0, java.math.BigDecimal arg1, java.math.BigDecimal arg2, boolean arg3, boolean arg4, java.math.BigDecimal arg5) throws java.rmi.RemoteException;
    public idw.idwws.GraficosParettoParadaDTO getGraficoParettoParadaBIDTO(java.util.Calendar arg0, java.util.Calendar arg1, java.math.BigDecimal arg2, java.math.BigDecimal arg3, java.math.BigDecimal arg4, boolean arg5, boolean arg6, java.math.BigDecimal arg7) throws java.rmi.RemoteException;
    public idw.idwws.PlanoDTO importarArquivoTrilha(idw.idwws.FiltroImportacaoTrilhaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ImgDTO[] getImgsDTO(idw.idwws.ImgDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ObjsDTO getObjsDTO(idw.idwws.ObjDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.GtRtDTO getGtRtDTO(idw.idwws.GtRtDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DetalhePTDTO detalhePT(idw.idwws.FiltroDetalhePTDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpNecimplogListDTO buscarLogs(long arg0, int arg1) throws java.rmi.RemoteException;
    public idw.idwws.DwRapDTO setRAPDTO(idw.idwws.DwRapDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoDTO salvarPlano(idw.idwws.PlanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoDTO firmarPlano(idw.idwws.PlanoDTO arg0, boolean arg1) throws java.rmi.RemoteException;
    public idw.idwws.PesquisaDTO[] pesquisaRAPs(idw.idwws.PesquisaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO[] getPtsAtivos() throws java.rmi.RemoteException;
    public idw.idwws.MsInd[] pesquisaInds() throws java.rmi.RemoteException;
    public idw.idwws.ResultadoImportacaoSapDTO importarSap(idw.idwws.UsuarioDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PlanoDTO simularPlano(idw.idwws.PlanoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PpCmDTO removePpCm(idw.idwws.PpCmDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaIcDTO removeIcDTO(idw.idwws.IcDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaIhmDTO setihmDTO(idw.idwws.IhmDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaIhmDTO removeIhmDTO(idw.idwws.IhmDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaMSDTO setMSDTO(idw.idwws.MsDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaMSDTO removeMSDTO(idw.idwws.MsDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaUPDTO setupDTO(idw.idwws.UpDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaUPDTO removeUpDTO(idw.idwws.UpDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaUPDTO getTodosPrUp() throws java.rmi.RemoteException;
    public java.lang.String pesquisarLog(java.math.BigDecimal arg0, java.math.BigDecimal arg1) throws java.rmi.RemoteException;
    public idw.idwws.IwsConsultaDTO consulta(idw.idwws.EventoColetado arg0) throws java.rmi.RemoteException;
    public idw.idwws.ListaIcDTO getListaMsIC() throws java.rmi.RemoteException;
    public idw.idwws.ListaIcDTO salvarIcDTO(idw.idwws.IcDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.BcDTO[] getListBcDTO() throws java.rmi.RemoteException;
    public idw.idwws.ListaUPDTO getListaMsUP() throws java.rmi.RemoteException;
    public idw.idwws.OmTppt[] getOmTpptDTO() throws java.rmi.RemoteException;
    public idw.idwws.DwTCausaDTO[] getTCausa(idw.idwws.DwTCausaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTCausaDTO setTCausa(idw.idwws.DwTCausaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTCausaDTO[] removeTCausa(idw.idwws.DwTCausaDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTRefugoDTO[] getTRefugo(idw.idwws.DwTRefugoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTRefugoDTO setTRefugo(idw.idwws.DwTRefugoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTAreaDTO[] getTArea(idw.idwws.DwTAreaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTAreaDTO setTArea(idw.idwws.DwTAreaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwTAreaDTO[] removeTArea(idw.idwws.DwTAreaDTO[] arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwGrpativDTO[] getDwGrpativ(idw.idwws.DwGrpativDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwGrpativDTO setDwGrpativ(idw.idwws.DwGrpativDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.OmCargoDTO[] getOmCargo(idw.idwws.OmCargoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.OmCargoDTO setOmCargo(idw.idwws.OmCargoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwParadaDTO[] getTParada(idw.idwws.DwParadaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.DwParadaDTO setTParada(idw.idwws.DwParadaDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.FirmwareDTO[] getFirmwares() throws java.rmi.RemoteException;
    public void integracaoCM() throws java.rmi.RemoteException;
    public idw.idwws.DwRota getDwRota(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.OmProduto getOmProduto(java.lang.String arg0) throws java.rmi.RemoteException;
    public idw.idwws.IndicadoresDTO[] getProducaoBrutaPt(idw.idwws.FiltroProducaoDTO arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO getOmPtOuIdOuCd(idw.idwws.OmPt arg0) throws java.rmi.RemoteException;
    public idw.idwws.PtDTO[] getPtsDoTtptDaFolha(idw.idwws.DwFolha arg0) throws java.rmi.RemoteException;
    public idw.idwws.MaquinasInjetDTO getIndicadoresInjet(idw.idwws.FiltroMaquinaInjetDTO arg0) throws java.rmi.RemoteException;
}
