package idw.webservices.dto;

import java.io.Serializable;

import idw.model.pojos.DwCal;

@SuppressWarnings("serial")
public class CalendarioDTO implements Serializable {
	private int EVENTO_BEM_SUCEDIDO = 0;
	private int ERRO_CALENDARIO_JA_EXISTE = 1;
	private int ERRO_DESCONHECIDO = 3;
	private int ERRO_USUARIO_REVISAO_DESCONHECIDO = 4;
	private int ERRO_USUARIO_STATUS_DESCONHECIDO = 5;
	private int ERRO_CDCALENDARIO_INVALIDO = 6;
	private int ERRO_REATIVACAO_INDISPONIVEL = 7;
	private int ERRO_DATAFINAL_INFERIOR = 8;
	private int ERRO_INICIOTURNO_SEM_FIM_ANTERIOR = 9;
	private int ERRO_FIMTURNO_SEM_INICIO_ANTERIOR = 10;
	private int ERRO_FIMTURNO_DIFERENTE_TURNOAVALIADO = 11;
	private int ERRO_DIADASEMANA_DESCONHECIDO = 12;
	private int ERRO_HORAFINAL_MENOR_HORAINICIAL = 13;
	private int ERRO_TEMPOCALENDARIO_INVALIDO = 14;
	private int ERRO_TEMPOSEMPESO_MAIOR_TEMPOCALENDARIO = 15;
	private int ERRO_TIPODATAREFERENCIA_INVALIDO = 16;
	private int ERRO_TURNO_DESCONHECIDO = 17;
	private int ERRO_DATAINICIAL_INVALIDA = 18;
	private int ERRO_EXISTE_CALENDARIO_EM_ABERTO = 19;
	private int ERRO_PERIODO_CALENDARIO_CONFLITA = 20;
	private int ERRO_TURNO_REPETIDO_MESMO_DIA = 21;
	
    private DwCal calendario;
    private CalendarioPtsDTO calendarioPts;
    private CalendariosSemanaisDTO calendariosSemanais;    
    private int resultadoEvento;
    private String complementoResultado;
	
    public int getEVENTO_BEM_SUCEDIDO() {
		return EVENTO_BEM_SUCEDIDO;
	}
	public void setEVENTO_BEM_SUCEDIDO(int eVENTOBEMSUCEDIDO) {
		EVENTO_BEM_SUCEDIDO = eVENTOBEMSUCEDIDO;
	}
	public int getERRO_DESCONHECIDO() {
		return ERRO_DESCONHECIDO;
	}
	public void setERRO_DESCONHECIDO(int eRRODESCONHECIDO) {
		ERRO_DESCONHECIDO = eRRODESCONHECIDO;
	}
	public int getERRO_USUARIO_REVISAO_DESCONHECIDO() {
		return ERRO_USUARIO_REVISAO_DESCONHECIDO;
	}
	public void setERRO_USUARIO_REVISAO_DESCONHECIDO(
			int eRROUSUARIOREVISAODESCONHECIDO) {
		ERRO_USUARIO_REVISAO_DESCONHECIDO = eRROUSUARIOREVISAODESCONHECIDO;
	}
	public int getERRO_USUARIO_STATUS_DESCONHECIDO() {
		return ERRO_USUARIO_STATUS_DESCONHECIDO;
	}
	public void setERRO_USUARIO_STATUS_DESCONHECIDO(
			int eRROUSUARIOSTATUSDESCONHECIDO) {
		ERRO_USUARIO_STATUS_DESCONHECIDO = eRROUSUARIOSTATUSDESCONHECIDO;
	}
	public int getERRO_REATIVACAO_INDISPONIVEL() {
		return ERRO_REATIVACAO_INDISPONIVEL;
	}
	public void setERRO_REATIVACAO_INDISPONIVEL(int eRROREATIVACAOINDISPONIVEL) {
		ERRO_REATIVACAO_INDISPONIVEL = eRROREATIVACAOINDISPONIVEL;
	}
	public int getResultadoEvento() {
		return resultadoEvento;
	}
	public void setResultadoEvento(int resultadoEvento) {
		this.resultadoEvento = resultadoEvento;
	}
	public int getERRO_CALENDARIO_JA_EXISTE() {
		return ERRO_CALENDARIO_JA_EXISTE;
	}
	public void setERRO_CALENDARIO_JA_EXISTE(int eRROCALENDARIOJAEXISTE) {
		ERRO_CALENDARIO_JA_EXISTE = eRROCALENDARIOJAEXISTE;
	}
	public int getERRO_CDCALENDARIO_INVALIDO() {
		return ERRO_CDCALENDARIO_INVALIDO;
	}
	public void setERRO_CDCALENDARIO_INVALIDO(int eRROCDCALENDARIOINVALIDO) {
		ERRO_CDCALENDARIO_INVALIDO = eRROCDCALENDARIOINVALIDO;
	}
	public DwCal getCalendario() {
		return calendario;
	}
	public void setCalendario(DwCal calendario) {
		this.calendario = calendario;
	}
	public CalendarioPtsDTO getCalendarioPts() {
		return calendarioPts;
	}
	public void setCalendarioPts(CalendarioPtsDTO calendarioPts) {
		this.calendarioPts = calendarioPts;
	}
	public CalendariosSemanaisDTO getCalendariosSemanais() {
		return calendariosSemanais;
	}
	public void setCalendariosSemanais(CalendariosSemanaisDTO calendariosSemanais) {
		this.calendariosSemanais = calendariosSemanais;
	}
	public int getERRO_DATAFINAL_INFERIOR() {
		return ERRO_DATAFINAL_INFERIOR;
	}
	public void setERRO_DATAFINAL_INFERIOR(int eRRODATAFINALINFERIOR) {
		ERRO_DATAFINAL_INFERIOR = eRRODATAFINALINFERIOR;
	}
	public int getERRO_INICIOTURNO_SEM_FIM_ANTERIOR() {
		return ERRO_INICIOTURNO_SEM_FIM_ANTERIOR;
	}
	public void setERRO_INICIOTURNO_SEM_FIM_ANTERIOR(
			int eRROINICIOTURNOSEMFIMANTERIOR) {
		ERRO_INICIOTURNO_SEM_FIM_ANTERIOR = eRROINICIOTURNOSEMFIMANTERIOR;
	}
	public int getERRO_FIMTURNO_SEM_INICIO_ANTERIOR() {
		return ERRO_FIMTURNO_SEM_INICIO_ANTERIOR;
	}
	public void setERRO_FIMTURNO_SEM_INICIO_ANTERIOR(
			int eRROFIMTURNOSEMINICIOANTERIOR) {
		ERRO_FIMTURNO_SEM_INICIO_ANTERIOR = eRROFIMTURNOSEMINICIOANTERIOR;
	}
	public int getERRO_FIMTURNO_DIFERENTE_TURNOAVALIADO() {
		return ERRO_FIMTURNO_DIFERENTE_TURNOAVALIADO;
	}
	public void setERRO_FIMTURNO_DIFERENTE_TURNOAVALIADO(
			int eRROFIMTURNODIFERENTETURNOAVALIADO) {
		ERRO_FIMTURNO_DIFERENTE_TURNOAVALIADO = eRROFIMTURNODIFERENTETURNOAVALIADO;
	}
	public int getERRO_DIADASEMANA_DESCONHECIDO() {
		return ERRO_DIADASEMANA_DESCONHECIDO;
	}
	public void setERRO_DIADASEMANA_DESCONHECIDO(int eRRODIADASEMANADESCONHECIDO) {
		ERRO_DIADASEMANA_DESCONHECIDO = eRRODIADASEMANADESCONHECIDO;
	}
	public int getERRO_HORAFINAL_MENOR_HORAINICIAL() {
		return ERRO_HORAFINAL_MENOR_HORAINICIAL;
	}
	public void setERRO_HORAFINAL_MENOR_HORAINICIAL(
			int eRROHORAFINALMENORHORAINICIAL) {
		ERRO_HORAFINAL_MENOR_HORAINICIAL = eRROHORAFINALMENORHORAINICIAL;
	}
	public int getERRO_TEMPOCALENDARIO_INVALIDO() {
		return ERRO_TEMPOCALENDARIO_INVALIDO;
	}
	public void setERRO_TEMPOCALENDARIO_INVALIDO(int eRROTEMPOCALENDARIOINVALIDO) {
		ERRO_TEMPOCALENDARIO_INVALIDO = eRROTEMPOCALENDARIOINVALIDO;
	}
	public int getERRO_TEMPOSEMPESO_MAIOR_TEMPOCALENDARIO() {
		return ERRO_TEMPOSEMPESO_MAIOR_TEMPOCALENDARIO;
	}
	public void setERRO_TEMPOSEMPESO_MAIOR_TEMPOCALENDARIO(
			int eRROTEMPOSEMPESOMAIORTEMPOCALENDARIO) {
		ERRO_TEMPOSEMPESO_MAIOR_TEMPOCALENDARIO = eRROTEMPOSEMPESOMAIORTEMPOCALENDARIO;
	}
	public int getERRO_TIPODATAREFERENCIA_INVALIDO() {
		return ERRO_TIPODATAREFERENCIA_INVALIDO;
	}
	public void setERRO_TIPODATAREFERENCIA_INVALIDO(
			int eRROTIPODATAREFERENCIAINVALIDO) {
		ERRO_TIPODATAREFERENCIA_INVALIDO = eRROTIPODATAREFERENCIAINVALIDO;
	}
	public int getERRO_TURNO_DESCONHECIDO() {
		return ERRO_TURNO_DESCONHECIDO;
	}
	public void setERRO_TURNO_DESCONHECIDO(int eRROTURNODESCONHECIDO) {
		ERRO_TURNO_DESCONHECIDO = eRROTURNODESCONHECIDO;
	}
	public int getERRO_DATAINICIAL_INVALIDA() {
		return ERRO_DATAINICIAL_INVALIDA;
	}
	public void setERRO_DATAINICIAL_INVALIDA(int eRRO_DATAINICIAL_INVALIDA) {
		ERRO_DATAINICIAL_INVALIDA = eRRO_DATAINICIAL_INVALIDA;
	}
	public int getERRO_EXISTE_CALENDARIO_EM_ABERTO() {
		return ERRO_EXISTE_CALENDARIO_EM_ABERTO;
	}
	public void setERRO_EXISTE_CALENDARIO_EM_ABERTO(
			int eRRO_EXISTE_CALENDARIO_EM_ABERTO) {
		ERRO_EXISTE_CALENDARIO_EM_ABERTO = eRRO_EXISTE_CALENDARIO_EM_ABERTO;
	}
	public int getERRO_PERIODO_CALENDARIO_CONFLITA() {
		return ERRO_PERIODO_CALENDARIO_CONFLITA;
	}
	public void setERRO_PERIODO_CALENDARIO_CONFLITA(
			int eRRO_PERIODO_CALENDARIO_CONFLITA) {
		ERRO_PERIODO_CALENDARIO_CONFLITA = eRRO_PERIODO_CALENDARIO_CONFLITA;
	}
	public String getComplementoResultado() {
		return complementoResultado;
	}
	public void setComplementoResultado(String complementoResultado) {
		this.complementoResultado = complementoResultado;
	}
	public int getERRO_TURNO_REPETIDO_MESMO_DIA() {
		return ERRO_TURNO_REPETIDO_MESMO_DIA;
	}
	public void setERRO_TURNO_REPETIDO_MESMO_DIA(
			int eRRO_TURNO_REPETIDO_MESMO_DIA) {
		ERRO_TURNO_REPETIDO_MESMO_DIA = eRRO_TURNO_REPETIDO_MESMO_DIA;
	}
}