/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package idw.webservices.dto;

import java.io.Serializable;

import idw.model.pojos.DwFtEtapa;


/**
 *
 * @author lineker
 */
@SuppressWarnings("serial")
public class EtapaDTO implements Serializable {
	private int EVENTO_BEM_SUCEDIDO = 0;
	private int ERRO_ETAPA_JA_EXISTE = 1;
	private int ERRO_DESCONHECIDO = 3;
	private int ERRO_USUARIO_REVISAO_DESCONHECIDO = 4;
	private int ERRO_USUARIO_STATUS_DESCONHECIDO = 5;
	private int ERRO_CDETAPA_INVALIDO = 6;	
	private int ERRO_MSGOK_INVALIDA = 7;
	private int ERRO_MSGNOK_INVALIDA = 8;
	private int ERRO_TIPO_SUBETAPA_DESCONHECIDO = 9;
	private int ERRO_CATEGORIA_SUBETAPA_DESCONHECIDA = 10;
	private int ERRO_PARAMETROS_9998_DESCONHECIDOS = 11;
	private int ERRO_PARAMETRO_EVENTO_DESCONHECIDO = 12;
	private int ERRO_VALOR_EVENTO_INVALIDO = 13;
	private int ERRO_CONSIDACAO_DESCONHECIDO = 14;
	private int ERRO_COMPONENTE_DESCONHECIDO = 15;
	private int ERRO_PARAMETRO_MEDICAO_DESCONHECIDO = 16;
	private int ERRO_COMPARADOR_INVALIDO = 17;
	
    private DwFtEtapa etapa;
    private EtapaSubsDTO subs;
    private EtapaSubsDTO subsParaExclusao;
    private int resultadoEvento;
	
    public int getEVENTO_BEM_SUCEDIDO() {
		return EVENTO_BEM_SUCEDIDO;
	}
	public void setEVENTO_BEM_SUCEDIDO(int eVENTOBEMSUCEDIDO) {
		EVENTO_BEM_SUCEDIDO = eVENTOBEMSUCEDIDO;
	}
	public int getERRO_DESCONHECIDO() {
		return ERRO_DESCONHECIDO;
	}
	public void setERRO_DESCONHECIDO(int eRRODESCONHECIDO) {
		ERRO_DESCONHECIDO = eRRODESCONHECIDO;
	}
	public int getERRO_USUARIO_REVISAO_DESCONHECIDO() {
		return ERRO_USUARIO_REVISAO_DESCONHECIDO;
	}
	public void setERRO_USUARIO_REVISAO_DESCONHECIDO(
			int eRROUSUARIOREVISAODESCONHECIDO) {
		ERRO_USUARIO_REVISAO_DESCONHECIDO = eRROUSUARIOREVISAODESCONHECIDO;
	}
	public int getERRO_USUARIO_STATUS_DESCONHECIDO() {
		return ERRO_USUARIO_STATUS_DESCONHECIDO;
	}
	public void setERRO_USUARIO_STATUS_DESCONHECIDO(
			int eRROUSUARIOSTATUSDESCONHECIDO) {
		ERRO_USUARIO_STATUS_DESCONHECIDO = eRROUSUARIOSTATUSDESCONHECIDO;
	}
	public int getResultadoEvento() {
		return resultadoEvento;
	}
	public void setResultadoEvento(int resultadoEvento) {
		this.resultadoEvento = resultadoEvento;
	}
	public int getERRO_ETAPA_JA_EXISTE() {
		return ERRO_ETAPA_JA_EXISTE;
	}
	public void setERRO_ETAPA_JA_EXISTE(int eRROETAPAJAEXISTE) {
		ERRO_ETAPA_JA_EXISTE = eRROETAPAJAEXISTE;
	}
	public int getERRO_CDETAPA_INVALIDO() {
		return ERRO_CDETAPA_INVALIDO;
	}
	public void setERRO_CDETAPA_INVALIDO(int eRROCDETAPAINVALIDO) {
		ERRO_CDETAPA_INVALIDO = eRROCDETAPAINVALIDO;
	}
	public DwFtEtapa getEtapa() {
		return etapa;
	}
	public void setEtapa(DwFtEtapa etapa) {
		this.etapa = etapa;
	}
	public int getERRO_MSGOK_INVALIDA() {
		return ERRO_MSGOK_INVALIDA;
	}
	public void setERRO_MSGOK_INVALIDA(int eRROMSGOKINVALIDA) {
		ERRO_MSGOK_INVALIDA = eRROMSGOKINVALIDA;
	}
	public int getERRO_MSGNOK_INVALIDA() {
		return ERRO_MSGNOK_INVALIDA;
	}
	public void setERRO_MSGNOK_INVALIDA(int eRROMSGNOKINVALIDA) {
		ERRO_MSGNOK_INVALIDA = eRROMSGNOKINVALIDA;
	}
	public int getERRO_TIPO_SUBETAPA_DESCONHECIDO() {
		return ERRO_TIPO_SUBETAPA_DESCONHECIDO;
	}
	public void setERRO_TIPO_SUBETAPA_DESCONHECIDO(int eRROTIPOSUBETAPADESCONHECIDO) {
		ERRO_TIPO_SUBETAPA_DESCONHECIDO = eRROTIPOSUBETAPADESCONHECIDO;
	}
	public int getERRO_CATEGORIA_SUBETAPA_DESCONHECIDA() {
		return ERRO_CATEGORIA_SUBETAPA_DESCONHECIDA;
	}
	public void setERRO_CATEGORIA_SUBETAPA_DESCONHECIDA(
			int eRROCATEGORIASUBETAPADESCONHECIDA) {
		ERRO_CATEGORIA_SUBETAPA_DESCONHECIDA = eRROCATEGORIASUBETAPADESCONHECIDA;
	}
	public int getERRO_PARAMETROS_9998_DESCONHECIDOS() {
		return ERRO_PARAMETROS_9998_DESCONHECIDOS;
	}
	public void setERRO_PARAMETROS_9998_DESCONHECIDOS(
			int eRROPARAMETROS_9998DESCONHECIDOS) {
		ERRO_PARAMETROS_9998_DESCONHECIDOS = eRROPARAMETROS_9998DESCONHECIDOS;
	}
	public int getERRO_PARAMETRO_EVENTO_DESCONHECIDO() {
		return ERRO_PARAMETRO_EVENTO_DESCONHECIDO;
	}
	public void setERRO_PARAMETRO_EVENTO_DESCONHECIDO(
			int eRROPARAMETROEVENTODESCONHECIDO) {
		ERRO_PARAMETRO_EVENTO_DESCONHECIDO = eRROPARAMETROEVENTODESCONHECIDO;
	}
	public int getERRO_CONSIDACAO_DESCONHECIDO() {
		return ERRO_CONSIDACAO_DESCONHECIDO;
	}
	public void setERRO_CONSIDACAO_DESCONHECIDO(int eRROCONSIDACAODESCONHECIDO) {
		ERRO_CONSIDACAO_DESCONHECIDO = eRROCONSIDACAODESCONHECIDO;
	}
	public int getERRO_COMPONENTE_DESCONHECIDO() {
		return ERRO_COMPONENTE_DESCONHECIDO;
	}
	public void setERRO_COMPONENTE_DESCONHECIDO(int eRROCOMPONENTEDESCONHECIDO) {
		ERRO_COMPONENTE_DESCONHECIDO = eRROCOMPONENTEDESCONHECIDO;
	}
	public int getERRO_PARAMETRO_MEDICAO_DESCONHECIDO() {
		return ERRO_PARAMETRO_MEDICAO_DESCONHECIDO;
	}
	public void setERRO_PARAMETRO_MEDICAO_DESCONHECIDO(
			int eRROPARAMETROMEDICAODESCONHECIDO) {
		ERRO_PARAMETRO_MEDICAO_DESCONHECIDO = eRROPARAMETROMEDICAODESCONHECIDO;
	}
	public int getERRO_COMPARADOR_INVALIDO() {
		return ERRO_COMPARADOR_INVALIDO;
	}
	public void setERRO_COMPARADOR_INVALIDO(int eRROCOMPARADORINVALIDO) {
		ERRO_COMPARADOR_INVALIDO = eRROCOMPARADORINVALIDO;
	}
	public int getERRO_VALOR_EVENTO_INVALIDO() {
		return ERRO_VALOR_EVENTO_INVALIDO;
	}
	public void setERRO_VALOR_EVENTO_INVALIDO(int eRROVALOREVENTOINVALIDO) {
		ERRO_VALOR_EVENTO_INVALIDO = eRROVALOREVENTOINVALIDO;
	}
	public EtapaSubsDTO getSubs() {
		return subs;
	}
	public void setSubs(EtapaSubsDTO subs) {
		this.subs = subs;
	}
	public EtapaSubsDTO getSubsParaExclusao() {
		return subsParaExclusao;
	}
	public void setSubsParaExclusao(EtapaSubsDTO subsParaExclusao) {
		this.subsParaExclusao = subsParaExclusao;
	}
	
}