package idw.webservices.dto;

import java.io.Serializable;

import idw.model.pojos.DwRota;

@SuppressWarnings("serial")
public class RoteiroDTO implements Serializable {
	
	private int EVENTO_BEM_SUCEDIDO = 0;
	private int ERRO_ROTA_JA_EXISTE = 1;
	private int ERRO_DESCONHECIDO = 3;
	private int ERRO_USUARIO_REVISAO_DESCONHECIDO = 4;
	private int ERRO_USUARIO_STATUS_DESCONHECIDO = 5;
	private int ERRO_CDROTA_INVALIDO = 6;
	private int ERRO_GT_DESCONHECIDO = 7;
	private int ERRO_PRODUTO_DESCONHECIDO = 8;
	private int ERRO_ESTOQUE_DESCONHECIDO = 9;
	private int ERRO_PT_DESCONHECIDO = 10;
	private int ERRO_FOLHA_NAO_PERTENCE_GT = 11;
	private int ERRO_FOLHA_DUPLICADA = 12;
	private int ERRO_FOLHA_NAO_PERTENCE_ROTEIRO = 13;
	private int ERRO_PRODUTO_JA_VINCULADO_A_OUTRA_ROTA = 14;
	private int ERRO_CADASTRO_NAO_PODE_SER_REATIVADO = 15;
	private int ERRO_FOLHA_DESCONHECIDA = 16;
	private int ERRO_ROTEIRO_INCONSISTENTE = 17;
	
    private DwRota roteiro;
    private int resultadoEvento;
    
    private String complemento;
    
	public int getEVENTO_BEM_SUCEDIDO() {
		return EVENTO_BEM_SUCEDIDO;
	}
	public void setEVENTO_BEM_SUCEDIDO(int eVENTOBEMSUCEDIDO) {
		EVENTO_BEM_SUCEDIDO = eVENTOBEMSUCEDIDO;
	}
	public int getERRO_ROTA_JA_EXISTE() {
		return ERRO_ROTA_JA_EXISTE;
	}
	public void setERRO_ROTA_JA_EXISTE(int eRROROTAJAEXISTE) {
		ERRO_ROTA_JA_EXISTE = eRROROTAJAEXISTE;
	}
	public int getERRO_DESCONHECIDO() {
		return ERRO_DESCONHECIDO;
	}
	public void setERRO_DESCONHECIDO(int eRRODESCONHECIDO) {
		ERRO_DESCONHECIDO = eRRODESCONHECIDO;
	}
	public int getERRO_USUARIO_REVISAO_DESCONHECIDO() {
		return ERRO_USUARIO_REVISAO_DESCONHECIDO;
	}
	public void setERRO_USUARIO_REVISAO_DESCONHECIDO(
			int eRROUSUARIOREVISAODESCONHECIDO) {
		ERRO_USUARIO_REVISAO_DESCONHECIDO = eRROUSUARIOREVISAODESCONHECIDO;
	}
	public int getERRO_USUARIO_STATUS_DESCONHECIDO() {
		return ERRO_USUARIO_STATUS_DESCONHECIDO;
	}
	public void setERRO_USUARIO_STATUS_DESCONHECIDO(
			int eRROUSUARIOSTATUSDESCONHECIDO) {
		ERRO_USUARIO_STATUS_DESCONHECIDO = eRROUSUARIOSTATUSDESCONHECIDO;
	}
	public int getERRO_CDROTA_INVALIDO() {
		return ERRO_CDROTA_INVALIDO;
	}
	public void setERRO_CDROTA_INVALIDO(int eRROCDROTAINVALIDO) {
		ERRO_CDROTA_INVALIDO = eRROCDROTAINVALIDO;
	}
	public int getResultadoEvento() {
		return resultadoEvento;
	}
	public void setResultadoEvento(int resultadoEvento) {
		this.resultadoEvento = resultadoEvento;
	}
	public DwRota getRoteiro() {
		return roteiro;
	}
	public void setRoteiro(DwRota roteiro) {
		this.roteiro = roteiro;
	}
	public int getERRO_GT_DESCONHECIDO() {
		return ERRO_GT_DESCONHECIDO;
	}
	public void setERRO_GT_DESCONHECIDO(int eRROGTDESCONHECIDO) {
		ERRO_GT_DESCONHECIDO = eRROGTDESCONHECIDO;
	}
	public int getERRO_PRODUTO_DESCONHECIDO() {
		return ERRO_PRODUTO_DESCONHECIDO;
	}
	public void setERRO_PRODUTO_DESCONHECIDO(int eRROPRODUTODESCONHECIDO) {
		ERRO_PRODUTO_DESCONHECIDO = eRROPRODUTODESCONHECIDO;
	}
	public int getERRO_ESTOQUE_DESCONHECIDO() {
		return ERRO_ESTOQUE_DESCONHECIDO;
	}
	public void setERRO_ESTOQUE_DESCONHECIDO(int eRROESTOQUEDESCONHECIDO) {
		ERRO_ESTOQUE_DESCONHECIDO = eRROESTOQUEDESCONHECIDO;
	}
	public int getERRO_PT_DESCONHECIDO() {
		return ERRO_PT_DESCONHECIDO;
	}
	public void setERRO_PT_DESCONHECIDO(int eRROPTDESCONHECIDO) {
		ERRO_PT_DESCONHECIDO = eRROPTDESCONHECIDO;
	}
	public int getERRO_FOLHA_NAO_PERTENCE_GT() {
		return ERRO_FOLHA_NAO_PERTENCE_GT;
	}
	public void setERRO_FOLHA_NAO_PERTENCE_GT(int eRROFOLHANAOPERTENCEGT) {
		ERRO_FOLHA_NAO_PERTENCE_GT = eRROFOLHANAOPERTENCEGT;
	}
	public int getERRO_FOLHA_DUPLICADA() {
		return ERRO_FOLHA_DUPLICADA;
	}
	public void setERRO_FOLHA_DUPLICADA(int eRROFOLHADUPLICADA) {
		ERRO_FOLHA_DUPLICADA = eRROFOLHADUPLICADA;
	}
	public int getERRO_FOLHA_NAO_PERTENCE_ROTEIRO() {
		return ERRO_FOLHA_NAO_PERTENCE_ROTEIRO;
	}
	public void setERRO_FOLHA_NAO_PERTENCE_ROTEIRO(int eRROFOLHANAOPERTENCEROTEIRO) {
		ERRO_FOLHA_NAO_PERTENCE_ROTEIRO = eRROFOLHANAOPERTENCEROTEIRO;
	}
	public int getERRO_PRODUTO_JA_VINCULADO_A_OUTRA_ROTA() {
		return ERRO_PRODUTO_JA_VINCULADO_A_OUTRA_ROTA;
	}
	public void setERRO_PRODUTO_JA_VINCULADO_A_OUTRA_ROTA(int eRRO_PRODUTO_JA_VINCULADO_A_OUTRA_ROTA) {
		ERRO_PRODUTO_JA_VINCULADO_A_OUTRA_ROTA = eRRO_PRODUTO_JA_VINCULADO_A_OUTRA_ROTA;
	}
	public int getERRO_CADASTRO_NAO_PODE_SER_REATIVADO() {
		return ERRO_CADASTRO_NAO_PODE_SER_REATIVADO;
	}
	public void setERRO_CADASTRO_NAO_PODE_SER_REATIVADO(
			int eRRO_CADASTRO_NAO_PODE_SER_REATIVADO) {
		ERRO_CADASTRO_NAO_PODE_SER_REATIVADO = eRRO_CADASTRO_NAO_PODE_SER_REATIVADO;
	}
	public int getERRO_FOLHA_DESCONHECIDA() {
		return ERRO_FOLHA_DESCONHECIDA;
	}
	public void setERRO_FOLHA_DESCONHECIDA(int eRRO_FOLHA_DESCONHECIDA) {
		ERRO_FOLHA_DESCONHECIDA = eRRO_FOLHA_DESCONHECIDA;
	}
	public int getERRO_ROTEIRO_INCONSISTENTE() {
		return ERRO_ROTEIRO_INCONSISTENTE;
	}
	public void setERRO_ROTEIRO_INCONSISTENTE(int eRRO_ROTEIRO_INCONSISTENTE) {
		ERRO_ROTEIRO_INCONSISTENTE = eRRO_ROTEIRO_INCONSISTENTE;
	}
	public String getComplemento() {
		return complemento;
	}
	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}    
	
}