package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cavidades2 generated by hbm2java
 */
@Entity
@Table(name = "CAVIDADES2")
public class Cavidades2 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -632229267918541239L;
	private Cavidades2Id id;

	public Cavidades2() {
	}

	public Cavidades2(Cavidades2Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "dthrival", column = @Column(name = "DTHRIVAL", nullable = false, length = 7)),
			@AttributeOverride(name = "qtcavidades", column = @Column(name = "QTCAVIDADES", precision = 22, scale = 0)),
			@AttributeOverride(name = "qtcavativas", column = @Column(name = "QTCAVATIVAS", precision = 22, scale = 0)),
			@AttributeOverride(name = "pliquidomedio", column = @Column(name = "PLIQUIDOMEDIO", precision = 22, scale = 0)),
			@AttributeOverride(name = "pbrutomedio", column = @Column(name = "PBRUTOMEDIO", precision = 22, scale = 0)) })
	public Cavidades2Id getId() {
		return this.id;
	}

	public void setId(Cavidades2Id id) {
		this.id = id;
	}

}
