package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exp017Aux generated by hbm2java
 */
@Entity
@Table(name = "EXP_017_AUX")
public class Exp017Aux implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4196409283397653521L;
	private Exp017AuxId id;

	public Exp017Aux() {
	}

	public Exp017Aux(Exp017AuxId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrrefugo", column = @Column(name = "DTHRREFUGO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdrefugo", column = @Column(name = "CDREFUGO", nullable = false, length = 6)),
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", length = 20)),
			@AttributeOverride(name = "qtref", column = @Column(name = "QTREF", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "cancelado", column = @Column(name = "CANCELADO", nullable = false, length = 1)) })
	public Exp017AuxId getId() {
		return this.id;
	}

	public void setId(Exp017AuxId id) {
		this.id = id;
	}

}
