package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exp028RefAux generated by hbm2java
 */
@Entity
@Table(name = "EXP_028_REF_AUX")
public class Exp028RefAux implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5120713800386835789L;
	private Exp028RefAuxId id;

	public Exp028RefAux() {
	}

	public Exp028RefAux(Exp028RefAuxId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthrirefugo", column = @Column(name = "DTHRIREFUGO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public Exp028RefAuxId getId() {
		return this.id;
	}

	public void setId(Exp028RefAuxId id) {
		this.id = id;
	}

}
