package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exportacao020 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_020")
public class Exportacao020 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8018253437873068569L;
	private Exportacao020Id id;
	private String dtrefturno;
	private char cdturno;
	private String cdoperador;
	private String cdmaquina;
	private Date dthriparada;
	private String cdparada;
	private String dtinidia;
	private String hrinidia;
	private String dtfimdia;
	private String hrfimdia;
	private String dtiniparada;
	private String hriniparada;
	private String dtfimparada;
	private String hrfimparada;
	private char tpoperacao;
	private char stregistro;
	private Date dthrstregistro;

	public Exportacao020() {
	}

	public Exportacao020(Exportacao020Id id, String dtrefturno, char cdturno,
			String cdoperador, String cdmaquina, Date dthriparada,
			String cdparada, String dtinidia, String hrinidia, String dtfimdia,
			String hrfimdia, String dtiniparada, String hriniparada,
			String dtfimparada, String hrfimparada, char tpoperacao,
			char stregistro, Date dthrstregistro) {
		this.id = id;
		this.dtrefturno = dtrefturno;
		this.cdturno = cdturno;
		this.cdoperador = cdoperador;
		this.cdmaquina = cdmaquina;
		this.dthriparada = dthriparada;
		this.cdparada = cdparada;
		this.dtinidia = dtinidia;
		this.hrinidia = hrinidia;
		this.dtfimdia = dtfimdia;
		this.hrfimdia = hrfimdia;
		this.dtiniparada = dtiniparada;
		this.hriniparada = hriniparada;
		this.dtfimparada = dtfimparada;
		this.hrfimparada = hrfimparada;
		this.tpoperacao = tpoperacao;
		this.stregistro = stregistro;
		this.dthrstregistro = dthrstregistro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idregistro", column = @Column(name = "IDREGISTRO", nullable = false, length = 13)),
			@AttributeOverride(name = "idplanta", column = @Column(name = "IDPLANTA", nullable = false, length = 4)),
			@AttributeOverride(name = "idarea", column = @Column(name = "IDAREA", nullable = false, length = 10)) })
	public Exportacao020Id getId() {
		return this.id;
	}

	public void setId(Exportacao020Id id) {
		this.id = id;
	}

	@Column(name = "DTREFTURNO", nullable = false, length = 8)
	public String getDtrefturno() {
		return this.dtrefturno;
	}

	public void setDtrefturno(String dtrefturno) {
		this.dtrefturno = dtrefturno;
	}

	@Column(name = "CDTURNO", nullable = false, length = 1)
	public char getCdturno() {
		return this.cdturno;
	}

	public void setCdturno(char cdturno) {
		this.cdturno = cdturno;
	}

	@Column(name = "CDOPERADOR", nullable = false, length = 6)
	public String getCdoperador() {
		return this.cdoperador;
	}

	public void setCdoperador(String cdoperador) {
		this.cdoperador = cdoperador;
	}

	@Column(name = "CDMAQUINA", nullable = false, length = 6)
	public String getCdmaquina() {
		return this.cdmaquina;
	}

	public void setCdmaquina(String cdmaquina) {
		this.cdmaquina = cdmaquina;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIPARADA", nullable = false, length = 7)
	public Date getDthriparada() {
		return this.dthriparada;
	}

	public void setDthriparada(Date dthriparada) {
		this.dthriparada = dthriparada;
	}

	@Column(name = "CDPARADA", nullable = false, length = 6)
	public String getCdparada() {
		return this.cdparada;
	}

	public void setCdparada(String cdparada) {
		this.cdparada = cdparada;
	}

	@Column(name = "DTINIDIA", nullable = false, length = 8)
	public String getDtinidia() {
		return this.dtinidia;
	}

	public void setDtinidia(String dtinidia) {
		this.dtinidia = dtinidia;
	}

	@Column(name = "HRINIDIA", nullable = false, length = 8)
	public String getHrinidia() {
		return this.hrinidia;
	}

	public void setHrinidia(String hrinidia) {
		this.hrinidia = hrinidia;
	}

	@Column(name = "DTFIMDIA", nullable = false, length = 8)
	public String getDtfimdia() {
		return this.dtfimdia;
	}

	public void setDtfimdia(String dtfimdia) {
		this.dtfimdia = dtfimdia;
	}

	@Column(name = "HRFIMDIA", nullable = false, length = 8)
	public String getHrfimdia() {
		return this.hrfimdia;
	}

	public void setHrfimdia(String hrfimdia) {
		this.hrfimdia = hrfimdia;
	}

	@Column(name = "DTINIPARADA", nullable = false, length = 8)
	public String getDtiniparada() {
		return this.dtiniparada;
	}

	public void setDtiniparada(String dtiniparada) {
		this.dtiniparada = dtiniparada;
	}

	@Column(name = "HRINIPARADA", nullable = false, length = 8)
	public String getHriniparada() {
		return this.hriniparada;
	}

	public void setHriniparada(String hriniparada) {
		this.hriniparada = hriniparada;
	}

	@Column(name = "DTFIMPARADA", nullable = false, length = 8)
	public String getDtfimparada() {
		return this.dtfimparada;
	}

	public void setDtfimparada(String dtfimparada) {
		this.dtfimparada = dtfimparada;
	}

	@Column(name = "HRFIMPARADA", nullable = false, length = 8)
	public String getHrfimparada() {
		return this.hrfimparada;
	}

	public void setHrfimparada(String hrfimparada) {
		this.hrfimparada = hrfimparada;
	}

	@Column(name = "TPOPERACAO", nullable = false, length = 1)
	public char getTpoperacao() {
		return this.tpoperacao;
	}

	public void setTpoperacao(char tpoperacao) {
		this.tpoperacao = tpoperacao;
	}

	@Column(name = "STREGISTRO", nullable = false, length = 1)
	public char getStregistro() {
		return this.stregistro;
	}

	public void setStregistro(char stregistro) {
		this.stregistro = stregistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRSTREGISTRO", nullable = false, length = 7)
	public Date getDthrstregistro() {
		return this.dthrstregistro;
	}

	public void setDthrstregistro(Date dthrstregistro) {
		this.dthrstregistro = dthrstregistro;
	}

}
