package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exportacao025 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_025")
public class Exportacao025 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7438505778862066718L;
	private Exportacao025Id id;
	private String cdmaquina;
	private String cdmolde;
	private String cdestrutura;
	private double tmpciclo;
	private String stregistro;
	private String obs;

	public Exportacao025() {
	}

	public Exportacao025(Exportacao025Id id, String cdmaquina, String cdmolde,
			String cdestrutura, double tmpciclo, String stregistro) {
		this.id = id;
		this.cdmaquina = cdmaquina;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.tmpciclo = tmpciclo;
		this.stregistro = stregistro;
	}

	public Exportacao025(Exportacao025Id id, String cdmaquina, String cdmolde,
			String cdestrutura, double tmpciclo, String stregistro, String obs) {
		this.id = id;
		this.cdmaquina = cdmaquina;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.tmpciclo = tmpciclo;
		this.stregistro = stregistro;
		this.obs = obs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idregistro", column = @Column(name = "IDREGISTRO", nullable = false, length = 14)),
			@AttributeOverride(name = "idempresa", column = @Column(name = "IDEMPRESA", nullable = false, length = 2)) })
	public Exportacao025Id getId() {
		return this.id;
	}

	public void setId(Exportacao025Id id) {
		this.id = id;
	}

	@Column(name = "CDMAQUINA", nullable = false, length = 8)
	public String getCdmaquina() {
		return this.cdmaquina;
	}

	public void setCdmaquina(String cdmaquina) {
		this.cdmaquina = cdmaquina;
	}

	@Column(name = "CDMOLDE", nullable = false, length = 18)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "CDESTRUTURA", nullable = false, length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Column(name = "TMPCICLO", nullable = false, precision = 126, scale = 0)
	public double getTmpciclo() {
		return this.tmpciclo;
	}

	public void setTmpciclo(double tmpciclo) {
		this.tmpciclo = tmpciclo;
	}

	@Column(name = "STREGISTRO", nullable = false, length = 1)
	public String getStregistro() {
		return this.stregistro;
	}

	public void setStregistro(String stregistro) {
		this.stregistro = stregistro;
	}

	@Column(name = "OBS", length = 2)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
