package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exportacao010 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_010")
public class Exportacao010 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4788416388011213572L;
	private Exportacao010Id id;

	public Exportacao010() {
	}

	public Exportacao010(Exportacao010Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "dtturno", column = @Column(name = "DTTURNO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdturno", column = @Column(name = "CDTURNO", nullable = false, length = 6)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "cdoperador", column = @Column(name = "CDOPERADOR", length = 6)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "qtbruta", column = @Column(name = "QTBRUTA", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtrefugada", column = @Column(name = "QTREFUGADA", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtrefabater", column = @Column(name = "QTREFABATER", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "dthrcriacao", column = @Column(name = "DTHRCRIACAO", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrleitura", column = @Column(name = "DTHRLEITURA", length = 7)),
			@AttributeOverride(name = "stexportacao", column = @Column(name = "STEXPORTACAO", nullable = false, length = 1)) })
	public Exportacao010Id getId() {
		return this.id;
	}

	public void setId(Exportacao010Id id) {
		this.id = id;
	}

}
