package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Exportacao004 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_004")
public class Exportacao004 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 328551060084598568L;
	private Exportacao004Id id;
	private Ijestmol ijestmol;
	private Ijop ijop;
	private Ijtbinj ijtbinj;
	private Ijtbpro ijtbpro;

	public Exportacao004() {
	}

	public Exportacao004(Exportacao004Id id, Ijestmol ijestmol, Ijop ijop,
			Ijtbinj ijtbinj, Ijtbpro ijtbpro) {
		this.id = id;
		this.ijestmol = ijestmol;
		this.ijop = ijop;
		this.ijtbinj = ijtbinj;
		this.ijtbpro = ijtbpro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "dthrcriacaoevento", column = @Column(name = "DTHRCRIACAOEVENTO", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrprevent", column = @Column(name = "DTHRPREVENT", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrprevsaida", column = @Column(name = "DTHRPREVSAIDA", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrrealent", column = @Column(name = "DTHRREALENT", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrrealsaida", column = @Column(name = "DTHRREALSAIDA", length = 7)),
			@AttributeOverride(name = "qtdplanejada", column = @Column(name = "QTDPLANEJADA", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtdbruta", column = @Column(name = "QTDBRUTA", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtdrefugos", column = @Column(name = "QTDREFUGOS", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtdrefugosabater", column = @Column(name = "QTDREFUGOSABATER", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "stexportacao", column = @Column(name = "STEXPORTACAO", nullable = false, length = 1)),
			@AttributeOverride(name = "dthrsitexportacao", column = @Column(name = "DTHRSITEXPORTACAO", nullable = false, length = 7)) })
	public Exportacao004Id getId() {
		return this.id;
	}

	public void setId(Exportacao004Id id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false, insertable = false, updatable = false) })
	public Ijestmol getIjestmol() {
		return this.ijestmol;
	}

	public void setIjestmol(Ijestmol ijestmol) {
		this.ijestmol = ijestmol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

}
