package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exportacao030 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_030")
public class Exportacao030 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2923371740127654845L;
	private double idregistro;
	private Ijocorvarritmo ijocorvarritmo;
	private Date dthrinicio;
	private Date dthrfim;
	private char tpevt;
	private Character tpevtprod;
	private char correcao;
	private String cdproduto;
	private String cdturno;
	private String cdusuario;
	private Double qtdinj;
	private Double qtdprod;
	private Double qtdhrprod;
	private Double qtdref;
	private String cdparada;
	private String cdlocalparada;
	private String txtanotacao;
	private String nrop;
	private String nropexibicao;
	private String cdinjetora;
	private String stregistro;

	public Exportacao030() {
	}

	public Exportacao030(double idregistro, Date dthrinicio, char tpevt,
			char correcao, String cdproduto, String nrop, String nropexibicao,
			String cdinjetora, String stregistro) {
		this.idregistro = idregistro;
		this.dthrinicio = dthrinicio;
		this.tpevt = tpevt;
		this.correcao = correcao;
		this.cdproduto = cdproduto;
		this.nrop = nrop;
		this.nropexibicao = nropexibicao;
		this.cdinjetora = cdinjetora;
		this.stregistro = stregistro;
	}

	public Exportacao030(double idregistro, Ijocorvarritmo ijocorvarritmo,
			Date dthrinicio, Date dthrfim, char tpevt, Character tpevtprod,
			char correcao, String cdproduto, String cdturno, String cdusuario,
			Double qtdinj, Double qtdprod, Double qtdhrprod, Double qtdref,
			String cdparada, String cdlocalparada, String txtanotacao,
			String nrop, String nropexibicao, String cdinjetora,
			String stregistro) {
		this.idregistro = idregistro;
		this.ijocorvarritmo = ijocorvarritmo;
		this.dthrinicio = dthrinicio;
		this.dthrfim = dthrfim;
		this.tpevt = tpevt;
		this.tpevtprod = tpevtprod;
		this.correcao = correcao;
		this.cdproduto = cdproduto;
		this.cdturno = cdturno;
		this.cdusuario = cdusuario;
		this.qtdinj = qtdinj;
		this.qtdprod = qtdprod;
		this.qtdhrprod = qtdhrprod;
		this.qtdref = qtdref;
		this.cdparada = cdparada;
		this.cdlocalparada = cdlocalparada;
		this.txtanotacao = txtanotacao;
		this.nrop = nrop;
		this.nropexibicao = nropexibicao;
		this.cdinjetora = cdinjetora;
		this.stregistro = stregistro;
	}

	@Id
	@Column(name = "IDREGISTRO", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(double idregistro) {
		this.idregistro = idregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGVARRITMO")
	public Ijocorvarritmo getIjocorvarritmo() {
		return this.ijocorvarritmo;
	}

	public void setIjocorvarritmo(Ijocorvarritmo ijocorvarritmo) {
		this.ijocorvarritmo = ijocorvarritmo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRINICIO", nullable = false, length = 7)
	public Date getDthrinicio() {
		return this.dthrinicio;
	}

	public void setDthrinicio(Date dthrinicio) {
		this.dthrinicio = dthrinicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFIM", length = 7)
	public Date getDthrfim() {
		return this.dthrfim;
	}

	public void setDthrfim(Date dthrfim) {
		this.dthrfim = dthrfim;
	}

	@Column(name = "TPEVT", nullable = false, length = 1)
	public char getTpevt() {
		return this.tpevt;
	}

	public void setTpevt(char tpevt) {
		this.tpevt = tpevt;
	}

	@Column(name = "TPEVTPROD", length = 1)
	public Character getTpevtprod() {
		return this.tpevtprod;
	}

	public void setTpevtprod(Character tpevtprod) {
		this.tpevtprod = tpevtprod;
	}

	@Column(name = "CORRECAO", nullable = false, length = 1)
	public char getCorrecao() {
		return this.correcao;
	}

	public void setCorrecao(char correcao) {
		this.correcao = correcao;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "CDTURNO", length = 6)
	public String getCdturno() {
		return this.cdturno;
	}

	public void setCdturno(String cdturno) {
		this.cdturno = cdturno;
	}

	@Column(name = "CDUSUARIO", length = 6)
	public String getCdusuario() {
		return this.cdusuario;
	}

	public void setCdusuario(String cdusuario) {
		this.cdusuario = cdusuario;
	}

	@Column(name = "QTDINJ", precision = 126, scale = 0)
	public Double getQtdinj() {
		return this.qtdinj;
	}

	public void setQtdinj(Double qtdinj) {
		this.qtdinj = qtdinj;
	}

	@Column(name = "QTDPROD", precision = 126, scale = 0)
	public Double getQtdprod() {
		return this.qtdprod;
	}

	public void setQtdprod(Double qtdprod) {
		this.qtdprod = qtdprod;
	}

	@Column(name = "QTDHRPROD", precision = 126, scale = 0)
	public Double getQtdhrprod() {
		return this.qtdhrprod;
	}

	public void setQtdhrprod(Double qtdhrprod) {
		this.qtdhrprod = qtdhrprod;
	}

	@Column(name = "QTDREF", precision = 126, scale = 0)
	public Double getQtdref() {
		return this.qtdref;
	}

	public void setQtdref(Double qtdref) {
		this.qtdref = qtdref;
	}

	@Column(name = "CDPARADA", length = 6)
	public String getCdparada() {
		return this.cdparada;
	}

	public void setCdparada(String cdparada) {
		this.cdparada = cdparada;
	}

	@Column(name = "CDLOCALPARADA", length = 6)
	public String getCdlocalparada() {
		return this.cdlocalparada;
	}

	public void setCdlocalparada(String cdlocalparada) {
		this.cdlocalparada = cdlocalparada;
	}

	@Column(name = "TXTANOTACAO", length = 500)
	public String getTxtanotacao() {
		return this.txtanotacao;
	}

	public void setTxtanotacao(String txtanotacao) {
		this.txtanotacao = txtanotacao;
	}

	@Column(name = "NROP", nullable = false, length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "NROPEXIBICAO", nullable = false, length = 25)
	public String getNropexibicao() {
		return this.nropexibicao;
	}

	public void setNropexibicao(String nropexibicao) {
		this.nropexibicao = nropexibicao;
	}

	@Column(name = "CDINJETORA", nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Column(name = "STREGISTRO", nullable = false, length = 1)
	public String getStregistro() {
		return this.stregistro;
	}

	public void setStregistro(String stregistro) {
		this.stregistro = stregistro;
	}

}
