package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exportacao018Aux generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_018_AUX")
public class Exportacao018Aux implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2935397267277218549L;
	private Exportacao018AuxId id;
	private String cdparada;
	private char mdo;

	public Exportacao018Aux() {
	}

	public Exportacao018Aux(Exportacao018AuxId id, String cdparada, char mdo) {
		this.id = id;
		this.cdparada = cdparada;
		this.mdo = mdo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dtrefturno", column = @Column(name = "DTREFTURNO", nullable = false, length = 8)),
			@AttributeOverride(name = "cdturno", column = @Column(name = "CDTURNO", nullable = false, length = 1)),
			@AttributeOverride(name = "cdoperador", column = @Column(name = "CDOPERADOR", nullable = false, length = 6)),
			@AttributeOverride(name = "cdmaquina", column = @Column(name = "CDMAQUINA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "dthriparada", column = @Column(name = "DTHRIPARADA", nullable = false, length = 7)) })
	public Exportacao018AuxId getId() {
		return this.id;
	}

	public void setId(Exportacao018AuxId id) {
		this.id = id;
	}

	@Column(name = "CDPARADA", nullable = false, length = 6)
	public String getCdparada() {
		return this.cdparada;
	}

	public void setCdparada(String cdparada) {
		this.cdparada = cdparada;
	}

	@Column(name = "MDO", nullable = false, length = 1)
	public char getMdo() {
		return this.mdo;
	}

	public void setMdo(char mdo) {
		this.mdo = mdo;
	}

}
