package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exportacao017 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_017")
public class Exportacao017 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3547118988505264467L;
	private Exportacao017Id id;

	public Exportacao017() {
	}

	public Exportacao017(Exportacao017Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "qtprodbrutaacum", column = @Column(name = "QTPRODBRUTAACUM", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtrefacum", column = @Column(name = "QTREFACUM", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtrefcancelacum", column = @Column(name = "QTREFCANCELACUM", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtprodbruta", column = @Column(name = "QTPRODBRUTA", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtref", column = @Column(name = "QTREF", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtrefcancel", column = @Column(name = "QTREFCANCEL", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "dthrcriacao", column = @Column(name = "DTHRCRIACAO", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrleitura", column = @Column(name = "DTHRLEITURA", length = 7)),
			@AttributeOverride(name = "stexportacao", column = @Column(name = "STEXPORTACAO", nullable = false, length = 1)),
			@AttributeOverride(name = "idregistro", column = @Column(name = "IDREGISTRO", nullable = false, length = 12)) })
	public Exportacao017Id getId() {
		return this.id;
	}

	public void setId(Exportacao017Id id) {
		this.id = id;
	}

}
