package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exportacao014 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_014")
public class Exportacao014 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2477174456105637873L;
	private Exportacao014Id id;

	public Exportacao014() {
	}

	public Exportacao014(Exportacao014Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "hrstrab", column = @Column(name = "HRSTRAB", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "dthrcriacao", column = @Column(name = "DTHRCRIACAO", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrleitura", column = @Column(name = "DTHRLEITURA", length = 7)),
			@AttributeOverride(name = "stexportacao", column = @Column(name = "STEXPORTACAO", nullable = false, length = 1)) })
	public Exportacao014Id getId() {
		return this.id;
	}

	public void setId(Exportacao014Id id) {
		this.id = id;
	}

}
