package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exportacao026Aux generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_026_AUX")
public class Exportacao026Aux implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -32959942772625638L;
	private String cdmaquina;
	private Date dthrultintervexp;

	public Exportacao026Aux() {
	}

	public Exportacao026Aux(String cdmaquina, Date dthrultintervexp) {
		this.cdmaquina = cdmaquina;
		this.dthrultintervexp = dthrultintervexp;
	}

	@Id
	@Column(name = "CDMAQUINA", unique = true, nullable = false, length = 8)
	public String getCdmaquina() {
		return this.cdmaquina;
	}

	public void setCdmaquina(String cdmaquina) {
		this.cdmaquina = cdmaquina;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRULTINTERVEXP", nullable = false, length = 7)
	public Date getDthrultintervexp() {
		return this.dthrultintervexp;
	}

	public void setDthrultintervexp(Date dthrultintervexp) {
		this.dthrultintervexp = dthrultintervexp;
	}

}
