package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exportacao016 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_016")
public class Exportacao016 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3076341393344160161L;
	private Exportacao016Id id;

	public Exportacao016() {
	}

	public Exportacao016(Exportacao016Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdbarrasproduto", column = @Column(name = "CDBARRASPRODUTO", nullable = false, length = 50)),
			@AttributeOverride(name = "cdbarrascaixa", column = @Column(name = "CDBARRASCAIXA", nullable = false, length = 50)),
			@AttributeOverride(name = "stapontamento", column = @Column(name = "STAPONTAMENTO", nullable = false, length = 1)),
			@AttributeOverride(name = "stregistro", column = @Column(name = "STREGISTRO", nullable = false, length = 1)),
			@AttributeOverride(name = "dthrcriacao", column = @Column(name = "DTHRCRIACAO", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrleitura", column = @Column(name = "DTHRLEITURA", length = 7)) })
	public Exportacao016Id getId() {
		return this.id;
	}

	public void setId(Exportacao016Id id) {
		this.id = id;
	}

}
