package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Exportacao007 generated by hbm2java
 */
@Entity
@Table(name = "EXPORTACAO_007")
public class Exportacao007 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5367942135269633178L;
	private Exportacao007Id id;

	public Exportacao007() {
	}

	public Exportacao007(Exportacao007Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "qtdplanejada", column = @Column(name = "QTDPLANEJADA", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "dthrplaninicio", column = @Column(name = "DTHRPLANINICIO", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrplanfim", column = @Column(name = "DTHRPLANFIM", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrentrada", column = @Column(name = "DTHRENTRADA", length = 7)),
			@AttributeOverride(name = "dthrsaida", column = @Column(name = "DTHRSAIDA", length = 7)),
			@AttributeOverride(name = "statusop", column = @Column(name = "STATUSOP", nullable = false, length = 1)),
			@AttributeOverride(name = "dthrstatusop", column = @Column(name = "DTHRSTATUSOP", nullable = false, length = 7)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", nullable = false, length = 1)),
			@AttributeOverride(name = "dthrcriacao", column = @Column(name = "DTHRCRIACAO", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrleitura", column = @Column(name = "DTHRLEITURA", length = 7)),
			@AttributeOverride(name = "origem", column = @Column(name = "ORIGEM", nullable = false, length = 1)) })
	public Exportacao007Id getId() {
		return this.id;
	}

	public void setId(Exportacao007Id id) {
		this.id = id;
	}

}
