package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijacumprod generated by hbm2java
 */
@Entity
@Table(name = "IJACUMPROD")
public class Ijacumprod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3005953222300133513L;
	private IjacumprodId id;
	private Ijestmol ijestmol;
	private Ijop ijop;
	private Ijtbinj ijtbinj;

	public Ijacumprod() {
	}

	public Ijacumprod(IjacumprodId id) {
		this.id = id;
	}

	public Ijacumprod(IjacumprodId id, Ijestmol ijestmol, Ijop ijop,
			Ijtbinj ijtbinj) {
		this.id = id;
		this.ijestmol = ijestmol;
		this.ijop = ijop;
		this.ijtbinj = ijtbinj;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", length = 6)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", length = 4)),
			@AttributeOverride(name = "dthrivalestru", column = @Column(name = "DTHRIVALESTRU", length = 7)),
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", length = 10)),
			@AttributeOverride(name = "dthriacumprod", column = @Column(name = "DTHRIACUMPROD", length = 7)),
			@AttributeOverride(name = "dthrfacumprod", column = @Column(name = "DTHRFACUMPROD", length = 7)),
			@AttributeOverride(name = "qtinjnormal", column = @Column(name = "QTINJNORMAL", precision = 126, scale = 0)),
			@AttributeOverride(name = "qtinjparada", column = @Column(name = "QTINJPARADA", precision = 126, scale = 0)),
			@AttributeOverride(name = "qtinjnaparada", column = @Column(name = "QTINJNAPARADA", precision = 126, scale = 0)),
			@AttributeOverride(name = "somatmpcicnormal", column = @Column(name = "SOMATMPCICNORMAL", precision = 126, scale = 0)),
			@AttributeOverride(name = "somatmpcicparada", column = @Column(name = "SOMATMPCICPARADA", precision = 126, scale = 0)),
			@AttributeOverride(name = "somatmpcicnaparada", column = @Column(name = "SOMATMPCICNAPARADA", precision = 126, scale = 0)),
			@AttributeOverride(name = "somatmpsininjalto", column = @Column(name = "SOMATMPSININJALTO", precision = 126, scale = 0)),
			@AttributeOverride(name = "somatmpmolabe", column = @Column(name = "SOMATMPMOLABE", precision = 126, scale = 0)) })
	public IjacumprodId getId() {
		return this.id;
	}

	public void setId(IjacumprodId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", insertable = false, updatable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", insertable = false, updatable = false) })
	public Ijestmol getIjestmol() {
		return this.ijestmol;
	}

	public void setIjestmol(Ijestmol ijestmol) {
		this.ijestmol = ijestmol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

}
