package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijaledbqldinsp generated by hbm2java
 */
@Entity
@Table(name = "IJALEDBQLDINSP", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDREGDBQLD", "IDINSPECAO" }))
public class Ijaledbqldinsp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 540406713425591068L;
	private double idregistro;
	private Ijinspecao ijinspecao;
	private Ijaledbqld ijaledbqld;
	private BigDecimal origemmoduloqld;

	public Ijaledbqldinsp() {
	}

	public Ijaledbqldinsp(double idregistro, Ijinspecao ijinspecao,
			Ijaledbqld ijaledbqld, BigDecimal origemmoduloqld) {
		this.idregistro = idregistro;
		this.ijinspecao = ijinspecao;
		this.ijaledbqld = ijaledbqld;
		this.origemmoduloqld = origemmoduloqld;
	}

	@Id
	@Column(name = "IDREGISTRO", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(double idregistro) {
		this.idregistro = idregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINSPECAO", nullable = false)
	public Ijinspecao getIjinspecao() {
		return this.ijinspecao;
	}

	public void setIjinspecao(Ijinspecao ijinspecao) {
		this.ijinspecao = ijinspecao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGDBQLD", nullable = false)
	public Ijaledbqld getIjaledbqld() {
		return this.ijaledbqld;
	}

	public void setIjaledbqld(Ijaledbqld ijaledbqld) {
		this.ijaledbqld = ijaledbqld;
	}

	@Column(name = "ORIGEMMODULOQLD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOrigemmoduloqld() {
		return this.origemmoduloqld;
	}

	public void setOrigemmoduloqld(BigDecimal origemmoduloqld) {
		this.origemmoduloqld = origemmoduloqld;
	}

}
