package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ijaledbqld generated by hbm2java
 */
@Entity
@Table(name = "IJALEDBQLD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DTHRIALERTA", "CDALERTA", "CDINJETORA" }))
public class Ijaledbqld implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4432203553761769442L;
	private double idregistro;
	private Ijgrpparaminsp ijgrpparaminsp;
	private Ijtbpro ijtbpro;
	private Ijalertas ijalertas;
	private double tempolimite;
	private Date dthrlimite;
	private BigDecimal anotado;
	private Set<Ijqldultinsp> ijqldultinsps = new HashSet<Ijqldultinsp>(0);
	private Set<Ijaledbqldanot> ijaledbqldanots = new HashSet<Ijaledbqldanot>(0);
	private Set<Ijaledbqldinsp> ijaledbqldinsps = new HashSet<Ijaledbqldinsp>(0);

	public Ijaledbqld() {
	}

	public Ijaledbqld(double idregistro, Ijtbpro ijtbpro, Ijalertas ijalertas,
			double tempolimite, Date dthrlimite, BigDecimal anotado) {
		this.idregistro = idregistro;
		this.ijtbpro = ijtbpro;
		this.ijalertas = ijalertas;
		this.tempolimite = tempolimite;
		this.dthrlimite = dthrlimite;
		this.anotado = anotado;
	}

	public Ijaledbqld(double idregistro, Ijgrpparaminsp ijgrpparaminsp,
			Ijtbpro ijtbpro, Ijalertas ijalertas, double tempolimite,
			Date dthrlimite, BigDecimal anotado,
			Set<Ijqldultinsp> ijqldultinsps,
			Set<Ijaledbqldanot> ijaledbqldanots,
			Set<Ijaledbqldinsp> ijaledbqldinsps) {
		this.idregistro = idregistro;
		this.ijgrpparaminsp = ijgrpparaminsp;
		this.ijtbpro = ijtbpro;
		this.ijalertas = ijalertas;
		this.tempolimite = tempolimite;
		this.dthrlimite = dthrlimite;
		this.anotado = anotado;
		this.ijqldultinsps = ijqldultinsps;
		this.ijaledbqldanots = ijaledbqldanots;
		this.ijaledbqldinsps = ijaledbqldinsps;
	}

	@Id
	@Column(name = "IDREGISTRO", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(double idregistro) {
		this.idregistro = idregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRPPARAM")
	public Ijgrpparaminsp getIjgrpparaminsp() {
		return this.ijgrpparaminsp;
	}

	public void setIjgrpparaminsp(Ijgrpparaminsp ijgrpparaminsp) {
		this.ijgrpparaminsp = ijgrpparaminsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "DTHRIALERTA", referencedColumnName = "DTHRIALERTA", nullable = false),
			@JoinColumn(name = "CDALERTA", referencedColumnName = "CDALERTA", nullable = false),
			@JoinColumn(name = "CDINJETORA", referencedColumnName = "CDINJETORA", nullable = false) })
	public Ijalertas getIjalertas() {
		return this.ijalertas;
	}

	public void setIjalertas(Ijalertas ijalertas) {
		this.ijalertas = ijalertas;
	}

	@Column(name = "TEMPOLIMITE", nullable = false, precision = 126, scale = 0)
	public double getTempolimite() {
		return this.tempolimite;
	}

	public void setTempolimite(double tempolimite) {
		this.tempolimite = tempolimite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRLIMITE", nullable = false, length = 7)
	public Date getDthrlimite() {
		return this.dthrlimite;
	}

	public void setDthrlimite(Date dthrlimite) {
		this.dthrlimite = dthrlimite;
	}

	@Column(name = "ANOTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAnotado() {
		return this.anotado;
	}

	public void setAnotado(BigDecimal anotado) {
		this.anotado = anotado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijaledbqld")
	public Set<Ijqldultinsp> getIjqldultinsps() {
		return this.ijqldultinsps;
	}

	public void setIjqldultinsps(Set<Ijqldultinsp> ijqldultinsps) {
		this.ijqldultinsps = ijqldultinsps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijaledbqld")
	public Set<Ijaledbqldanot> getIjaledbqldanots() {
		return this.ijaledbqldanots;
	}

	public void setIjaledbqldanots(Set<Ijaledbqldanot> ijaledbqldanots) {
		this.ijaledbqldanots = ijaledbqldanots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijaledbqld")
	public Set<Ijaledbqldinsp> getIjaledbqldinsps() {
		return this.ijaledbqldinsps;
	}

	public void setIjaledbqldinsps(Set<Ijaledbqldinsp> ijaledbqldinsps) {
		this.ijaledbqldinsps = ijaledbqldinsps;
	}

}
