package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijalertas generated by hbm2java
 */
@Entity
@Table(name = "IJALERTAS")
public class Ijalertas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3302767471661156561L;
	private IjalertasId id;
	private Ijestmol ijestmol;
	private Ijtbale ijtbale;
	private Ijtbusu ijtbusu;
	private Date dthrfalerta;
	private BigDecimal lgeradoautomatico;
	private BigDecimal quedaescravo;
	private Date dthrivalestru;
	private String nrop;
	private Character tpfechamento;
	private String observacao;
	private Set<Ijaledbqld> ijaledbqlds = new HashSet<Ijaledbqld>(0);

	public Ijalertas() {
	}

	public Ijalertas(IjalertasId id, Ijtbale ijtbale) {
		this.id = id;
		this.ijtbale = ijtbale;
	}

	public Ijalertas(IjalertasId id, Ijestmol ijestmol, Ijtbale ijtbale,
			Ijtbusu ijtbusu, Date dthrfalerta, BigDecimal lgeradoautomatico,
			BigDecimal quedaescravo, Date dthrivalestru, String nrop,
			Character tpfechamento, String observacao,
			Set<Ijaledbqld> ijaledbqlds) {
		this.id = id;
		this.ijestmol = ijestmol;
		this.ijtbale = ijtbale;
		this.ijtbusu = ijtbusu;
		this.dthrfalerta = dthrfalerta;
		this.lgeradoautomatico = lgeradoautomatico;
		this.quedaescravo = quedaescravo;
		this.dthrivalestru = dthrivalestru;
		this.nrop = nrop;
		this.tpfechamento = tpfechamento;
		this.observacao = observacao;
		this.ijaledbqlds = ijaledbqlds;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthrialerta", column = @Column(name = "DTHRIALERTA", nullable = false, length = 7)),
			@AttributeOverride(name = "cdalerta", column = @Column(name = "CDALERTA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public IjalertasId getId() {
		return this.id;
	}

	public void setId(IjalertasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE"),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA") })
	public Ijestmol getIjestmol() {
		return this.ijestmol;
	}

	public void setIjestmol(Ijestmol ijestmol) {
		this.ijestmol = ijestmol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDALERTA", nullable = false, insertable = false, updatable = false)
	public Ijtbale getIjtbale() {
		return this.ijtbale;
	}

	public void setIjtbale(Ijtbale ijtbale) {
		this.ijtbale = ijtbale;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIO")
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFALERTA", length = 7)
	public Date getDthrfalerta() {
		return this.dthrfalerta;
	}

	public void setDthrfalerta(Date dthrfalerta) {
		this.dthrfalerta = dthrfalerta;
	}

	@Column(name = "LGERADOAUTOMATICO", precision = 22, scale = 0)
	public BigDecimal getLgeradoautomatico() {
		return this.lgeradoautomatico;
	}

	public void setLgeradoautomatico(BigDecimal lgeradoautomatico) {
		this.lgeradoautomatico = lgeradoautomatico;
	}

	@Column(name = "QUEDAESCRAVO", precision = 22, scale = 0)
	public BigDecimal getQuedaescravo() {
		return this.quedaescravo;
	}

	public void setQuedaescravo(BigDecimal quedaescravo) {
		this.quedaescravo = quedaescravo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIVALESTRU", length = 7)
	public Date getDthrivalestru() {
		return this.dthrivalestru;
	}

	public void setDthrivalestru(Date dthrivalestru) {
		this.dthrivalestru = dthrivalestru;
	}

	@Column(name = "NROP", length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "TPFECHAMENTO", length = 1)
	public Character getTpfechamento() {
		return this.tpfechamento;
	}

	public void setTpfechamento(Character tpfechamento) {
		this.tpfechamento = tpfechamento;
	}

	@Column(name = "OBSERVACAO", length = 250)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijalertas")
	public Set<Ijaledbqld> getIjaledbqlds() {
		return this.ijaledbqlds;
	}

	public void setIjaledbqlds(Set<Ijaledbqld> ijaledbqlds) {
		this.ijaledbqlds = ijaledbqlds;
	}

}
