package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijamstrmedias generated by hbm2java
 */
@Entity
@Table(name = "IJAMSTRMEDIAS")
public class Ijamstrmedias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7854214516696114207L;
	private IjamstrmediasId id;
	private Ijamostragem ijamostragemByIdamostragem;
	private Ijamostragem ijamostragemByIdamstrmedia;

	public Ijamstrmedias() {
	}

	public Ijamstrmedias(IjamstrmediasId id,
			Ijamostragem ijamostragemByIdamostragem,
			Ijamostragem ijamostragemByIdamstrmedia) {
		this.id = id;
		this.ijamostragemByIdamostragem = ijamostragemByIdamostragem;
		this.ijamostragemByIdamstrmedia = ijamostragemByIdamstrmedia;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idamstrmedia", column = @Column(name = "IDAMSTRMEDIA", nullable = false, length = 12)),
			@AttributeOverride(name = "idamostragem", column = @Column(name = "IDAMOSTRAGEM", nullable = false, length = 12)) })
	public IjamstrmediasId getId() {
		return this.id;
	}

	public void setId(IjamstrmediasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDAMOSTRAGEM", nullable = false, insertable = false, updatable = false)
	public Ijamostragem getIjamostragemByIdamostragem() {
		return this.ijamostragemByIdamostragem;
	}

	public void setIjamostragemByIdamostragem(
			Ijamostragem ijamostragemByIdamostragem) {
		this.ijamostragemByIdamostragem = ijamostragemByIdamostragem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDAMSTRMEDIA", nullable = false, insertable = false, updatable = false)
	public Ijamostragem getIjamostragemByIdamstrmedia() {
		return this.ijamostragemByIdamstrmedia;
	}

	public void setIjamostragemByIdamstrmedia(
			Ijamostragem ijamostragemByIdamstrmedia) {
		this.ijamostragemByIdamstrmedia = ijamostragemByIdamstrmedia;
	}

}
