package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijamstraltcgq generated by hbm2java
 */
@Entity
@Table(name = "IJAMSTRALTCGQ")
public class Ijamstraltcgq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 468248293678317387L;
	private double idctrlaltcgqamstr;
	private Ijamostragem ijamostragem;
	private Ijctrlcgqalt ijctrlcgqalt;
	private double mediavllidos;
	private double amplitudevllidos;
	private char compoemedia;
	private char resultado;
	private Set<Ijamstrdetaltcgq> ijamstrdetaltcgqs = new HashSet<Ijamstrdetaltcgq>(
			0);
	private Set<Ijamstrdetaltmedia> ijamstrdetaltmediasForIdctrlaltcgammedia = new HashSet<Ijamstrdetaltmedia>(
			0);
	private Set<Ijamstrdetaltmedia> ijamstrdetaltmediasForIdctrlaltcgqamstr = new HashSet<Ijamstrdetaltmedia>(
			0);

	public Ijamstraltcgq() {
	}

	public Ijamstraltcgq(double idctrlaltcgqamstr, Ijamostragem ijamostragem,
			Ijctrlcgqalt ijctrlcgqalt, double mediavllidos,
			double amplitudevllidos, char compoemedia, char resultado) {
		this.idctrlaltcgqamstr = idctrlaltcgqamstr;
		this.ijamostragem = ijamostragem;
		this.ijctrlcgqalt = ijctrlcgqalt;
		this.mediavllidos = mediavllidos;
		this.amplitudevllidos = amplitudevllidos;
		this.compoemedia = compoemedia;
		this.resultado = resultado;
	}

	public Ijamstraltcgq(double idctrlaltcgqamstr, Ijamostragem ijamostragem,
			Ijctrlcgqalt ijctrlcgqalt, double mediavllidos,
			double amplitudevllidos, char compoemedia, char resultado,
			Set<Ijamstrdetaltcgq> ijamstrdetaltcgqs,
			Set<Ijamstrdetaltmedia> ijamstrdetaltmediasForIdctrlaltcgammedia,
			Set<Ijamstrdetaltmedia> ijamstrdetaltmediasForIdctrlaltcgqamstr) {
		this.idctrlaltcgqamstr = idctrlaltcgqamstr;
		this.ijamostragem = ijamostragem;
		this.ijctrlcgqalt = ijctrlcgqalt;
		this.mediavllidos = mediavllidos;
		this.amplitudevllidos = amplitudevllidos;
		this.compoemedia = compoemedia;
		this.resultado = resultado;
		this.ijamstrdetaltcgqs = ijamstrdetaltcgqs;
		this.ijamstrdetaltmediasForIdctrlaltcgammedia = ijamstrdetaltmediasForIdctrlaltcgammedia;
		this.ijamstrdetaltmediasForIdctrlaltcgqamstr = ijamstrdetaltmediasForIdctrlaltcgqamstr;
	}

	@Id
	@Column(name = "IDCTRLALTCGQAMSTR", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdctrlaltcgqamstr() {
		return this.idctrlaltcgqamstr;
	}

	public void setIdctrlaltcgqamstr(double idctrlaltcgqamstr) {
		this.idctrlaltcgqamstr = idctrlaltcgqamstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDAMOSTRAGEM", nullable = false)
	public Ijamostragem getIjamostragem() {
		return this.ijamostragem;
	}

	public void setIjamostragem(Ijamostragem ijamostragem) {
		this.ijamostragem = ijamostragem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCTRLALTCGQ", nullable = false)
	public Ijctrlcgqalt getIjctrlcgqalt() {
		return this.ijctrlcgqalt;
	}

	public void setIjctrlcgqalt(Ijctrlcgqalt ijctrlcgqalt) {
		this.ijctrlcgqalt = ijctrlcgqalt;
	}

	@Column(name = "MEDIAVLLIDOS", nullable = false, precision = 126, scale = 0)
	public double getMediavllidos() {
		return this.mediavllidos;
	}

	public void setMediavllidos(double mediavllidos) {
		this.mediavllidos = mediavllidos;
	}

	@Column(name = "AMPLITUDEVLLIDOS", nullable = false, precision = 126, scale = 0)
	public double getAmplitudevllidos() {
		return this.amplitudevllidos;
	}

	public void setAmplitudevllidos(double amplitudevllidos) {
		this.amplitudevllidos = amplitudevllidos;
	}

	@Column(name = "COMPOEMEDIA", nullable = false, length = 1)
	public char getCompoemedia() {
		return this.compoemedia;
	}

	public void setCompoemedia(char compoemedia) {
		this.compoemedia = compoemedia;
	}

	@Column(name = "RESULTADO", nullable = false, length = 1)
	public char getResultado() {
		return this.resultado;
	}

	public void setResultado(char resultado) {
		this.resultado = resultado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijamstraltcgq")
	public Set<Ijamstrdetaltcgq> getIjamstrdetaltcgqs() {
		return this.ijamstrdetaltcgqs;
	}

	public void setIjamstrdetaltcgqs(Set<Ijamstrdetaltcgq> ijamstrdetaltcgqs) {
		this.ijamstrdetaltcgqs = ijamstrdetaltcgqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijamstraltcgqByIdctrlaltcgammedia")
	public Set<Ijamstrdetaltmedia> getIjamstrdetaltmediasForIdctrlaltcgammedia() {
		return this.ijamstrdetaltmediasForIdctrlaltcgammedia;
	}

	public void setIjamstrdetaltmediasForIdctrlaltcgammedia(
			Set<Ijamstrdetaltmedia> ijamstrdetaltmediasForIdctrlaltcgammedia) {
		this.ijamstrdetaltmediasForIdctrlaltcgammedia = ijamstrdetaltmediasForIdctrlaltcgammedia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijamstraltcgqByIdctrlaltcgqamstr")
	public Set<Ijamstrdetaltmedia> getIjamstrdetaltmediasForIdctrlaltcgqamstr() {
		return this.ijamstrdetaltmediasForIdctrlaltcgqamstr;
	}

	public void setIjamstrdetaltmediasForIdctrlaltcgqamstr(
			Set<Ijamstrdetaltmedia> ijamstrdetaltmediasForIdctrlaltcgqamstr) {
		this.ijamstrdetaltmediasForIdctrlaltcgqamstr = ijamstrdetaltmediasForIdctrlaltcgqamstr;
	}

}
