package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijamstrdetaltcgq generated by hbm2java
 */
@Entity
@Table(name = "IJAMSTRDETALTCGQ", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDCTRLALTCGQAMSTR", "AMOSTRA" }))
public class Ijamstrdetaltcgq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6670868883340406613L;
	private double idctrlaltcgqamstvl;
	private Ijamstraltcgq ijamstraltcgq;
	private BigDecimal amostra;
	private double vllido;
	private char resultado;

	public Ijamstrdetaltcgq() {
	}

	public Ijamstrdetaltcgq(double idctrlaltcgqamstvl,
			Ijamstraltcgq ijamstraltcgq, BigDecimal amostra, double vllido,
			char resultado) {
		this.idctrlaltcgqamstvl = idctrlaltcgqamstvl;
		this.ijamstraltcgq = ijamstraltcgq;
		this.amostra = amostra;
		this.vllido = vllido;
		this.resultado = resultado;
	}

	@Id
	@Column(name = "IDCTRLALTCGQAMSTVL", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdctrlaltcgqamstvl() {
		return this.idctrlaltcgqamstvl;
	}

	public void setIdctrlaltcgqamstvl(double idctrlaltcgqamstvl) {
		this.idctrlaltcgqamstvl = idctrlaltcgqamstvl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCTRLALTCGQAMSTR", nullable = false)
	public Ijamstraltcgq getIjamstraltcgq() {
		return this.ijamstraltcgq;
	}

	public void setIjamstraltcgq(Ijamstraltcgq ijamstraltcgq) {
		this.ijamstraltcgq = ijamstraltcgq;
	}

	@Column(name = "AMOSTRA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAmostra() {
		return this.amostra;
	}

	public void setAmostra(BigDecimal amostra) {
		this.amostra = amostra;
	}

	@Column(name = "VLLIDO", nullable = false, precision = 126, scale = 0)
	public double getVllido() {
		return this.vllido;
	}

	public void setVllido(double vllido) {
		this.vllido = vllido;
	}

	@Column(name = "RESULTADO", nullable = false, length = 1)
	public char getResultado() {
		return this.resultado;
	}

	public void setResultado(char resultado) {
		this.resultado = resultado;
	}

}
