package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijamstrdetaltmedia generated by hbm2java
 */
@Entity
@Table(name = "IJAMSTRDETALTMEDIA")
public class Ijamstrdetaltmedia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7759435072413666749L;
	private IjamstrdetaltmediaId id;
	private Ijamstraltcgq ijamstraltcgqByIdctrlaltcgammedia;
	private Ijamstraltcgq ijamstraltcgqByIdctrlaltcgqamstr;

	public Ijamstrdetaltmedia() {
	}

	public Ijamstrdetaltmedia(IjamstrdetaltmediaId id,
			Ijamstraltcgq ijamstraltcgqByIdctrlaltcgammedia,
			Ijamstraltcgq ijamstraltcgqByIdctrlaltcgqamstr) {
		this.id = id;
		this.ijamstraltcgqByIdctrlaltcgammedia = ijamstraltcgqByIdctrlaltcgammedia;
		this.ijamstraltcgqByIdctrlaltcgqamstr = ijamstraltcgqByIdctrlaltcgqamstr;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idctrlaltcgammedia", column = @Column(name = "IDCTRLALTCGAMMEDIA", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "idctrlaltcgqamstr", column = @Column(name = "IDCTRLALTCGQAMSTR", nullable = false, precision = 126, scale = 0)) })
	public IjamstrdetaltmediaId getId() {
		return this.id;
	}

	public void setId(IjamstrdetaltmediaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCTRLALTCGAMMEDIA", nullable = false, insertable = false, updatable = false)
	public Ijamstraltcgq getIjamstraltcgqByIdctrlaltcgammedia() {
		return this.ijamstraltcgqByIdctrlaltcgammedia;
	}

	public void setIjamstraltcgqByIdctrlaltcgammedia(
			Ijamstraltcgq ijamstraltcgqByIdctrlaltcgammedia) {
		this.ijamstraltcgqByIdctrlaltcgammedia = ijamstraltcgqByIdctrlaltcgammedia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCTRLALTCGQAMSTR", nullable = false, insertable = false, updatable = false)
	public Ijamstraltcgq getIjamstraltcgqByIdctrlaltcgqamstr() {
		return this.ijamstraltcgqByIdctrlaltcgqamstr;
	}

	public void setIjamstraltcgqByIdctrlaltcgqamstr(
			Ijamstraltcgq ijamstraltcgqByIdctrlaltcgqamstr) {
		this.ijamstraltcgqByIdctrlaltcgqamstr = ijamstraltcgqByIdctrlaltcgqamstr;
	}

}
