package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijarereslog generated by hbm2java
 */
@Entity
@Table(name = "IJARERESLOG")
public class Ijarereslog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1428506081558958889L;
	private IjarereslogId id;

	public Ijarereslog() {
	}

	public Ijarereslog(IjarereslogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdarea", column = @Column(name = "CDAREA", nullable = false, length = 6)),
			@AttributeOverride(name = "dsarea", column = @Column(name = "DSAREA", length = 40)),
			@AttributeOverride(name = "tipoarearesp", column = @Column(name = "TIPOAREARESP", length = 1)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", nullable = false, length = 6)) })
	public IjarereslogId getId() {
		return this.id;
	}

	public void setId(IjarereslogId id) {
		this.id = id;
	}

}
