package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijbroneopprocomp generated by hbm2java
 */
@Entity
@Table(name = "IJBRONEOPPROCOMP")
public class Ijbroneopprocomp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -224770396103973075L;
	private IjbroneopprocompId id;
	private Ijbroneopsecao ijbroneopsecao;
	private Date dthrinicomp;

	public Ijbroneopprocomp() {
	}

	public Ijbroneopprocomp(IjbroneopprocompId id,
			Ijbroneopsecao ijbroneopsecao, Date dthrinicomp) {
		this.id = id;
		this.ijbroneopsecao = ijbroneopsecao;
		this.dthrinicomp = dthrinicomp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nropsecao", column = @Column(name = "NROPSECAO", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)) })
	public IjbroneopprocompId getId() {
		return this.id;
	}

	public void setId(IjbroneopprocompId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "NROPSECAO", referencedColumnName = "NROPSECAO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false) })
	public Ijbroneopsecao getIjbroneopsecao() {
		return this.ijbroneopsecao;
	}

	public void setIjbroneopsecao(Ijbroneopsecao ijbroneopsecao) {
		this.ijbroneopsecao = ijbroneopsecao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRINICOMP", nullable = false, length = 7)
	public Date getDthrinicomp() {
		return this.dthrinicomp;
	}

	public void setDthrinicomp(Date dthrinicomp) {
		this.dthrinicomp = dthrinicomp;
	}

}
