package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijbroneinjapt generated by hbm2java
 */
@Entity
@Table(name = "IJBRONEINJAPT")
public class Ijbroneinjapt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3312382280264165938L;
	private String cdinjetora;
	private Ijtbinj ijtbinj;
	private char aponta;

	public Ijbroneinjapt() {
	}

	public Ijbroneinjapt(String cdinjetora, Ijtbinj ijtbinj, char aponta) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.aponta = aponta;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "APONTA", nullable = false, length = 1)
	public char getAponta() {
		return this.aponta;
	}

	public void setAponta(char aponta) {
		this.aponta = aponta;
	}

}
