package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjbroneprosecaoId generated by hbm2java
 */
@Embeddable
public class IjbroneprosecaoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4861520460760020269L;
	private String cdproduto;
	private String cdprodutocomp;
	private Date dthrinicomp;

	public IjbroneprosecaoId() {
	}

	public IjbroneprosecaoId(String cdproduto, String cdprodutocomp,
			Date dthrinicomp) {
		this.cdproduto = cdproduto;
		this.cdprodutocomp = cdprodutocomp;
		this.dthrinicomp = dthrinicomp;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "CDPRODUTOCOMP", nullable = false, length = 20)
	public String getCdprodutocomp() {
		return this.cdprodutocomp;
	}

	public void setCdprodutocomp(String cdprodutocomp) {
		this.cdprodutocomp = cdprodutocomp;
	}

	@Column(name = "DTHRINICOMP", nullable = false, length = 7)
	public Date getDthrinicomp() {
		return this.dthrinicomp;
	}

	public void setDthrinicomp(Date dthrinicomp) {
		this.dthrinicomp = dthrinicomp;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjbroneprosecaoId))
			return false;
		IjbroneprosecaoId castOther = (IjbroneprosecaoId) other;

		return ((this.getCdproduto() == castOther.getCdproduto()) || (this
				.getCdproduto() != null && castOther.getCdproduto() != null && this
				.getCdproduto().equals(castOther.getCdproduto())))
				&& ((this.getCdprodutocomp() == castOther.getCdprodutocomp()) || (this
						.getCdprodutocomp() != null
						&& castOther.getCdprodutocomp() != null && this
						.getCdprodutocomp()
						.equals(castOther.getCdprodutocomp())))
				&& ((this.getDthrinicomp() == castOther.getDthrinicomp()) || (this
						.getDthrinicomp() != null
						&& castOther.getDthrinicomp() != null && this
						.getDthrinicomp().equals(castOther.getDthrinicomp())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCdproduto() == null ? 0 : this.getCdproduto().hashCode());
		result = 37
				* result
				+ (getCdprodutocomp() == null ? 0 : this.getCdprodutocomp()
						.hashCode());
		result = 37
				* result
				+ (getDthrinicomp() == null ? 0 : this.getDthrinicomp()
						.hashCode());
		return result;
	}

}
