package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijbroneopsecaoops generated by hbm2java
 */
@Entity
@Table(name = "IJBRONEOPSECAOOPS")
public class Ijbroneopsecaoops implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4609904488122124490L;
	private IjbroneopsecaoopsId id;
	private Ijbroneopsecao ijbroneopsecao;
	private String cdprodutocomp;
	private double qtdplanejada;

	public Ijbroneopsecaoops() {
	}

	public Ijbroneopsecaoops(IjbroneopsecaoopsId id,
			Ijbroneopsecao ijbroneopsecao, String cdprodutocomp,
			double qtdplanejada) {
		this.id = id;
		this.ijbroneopsecao = ijbroneopsecao;
		this.cdprodutocomp = cdprodutocomp;
		this.qtdplanejada = qtdplanejada;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nropsecao", column = @Column(name = "NROPSECAO", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "nropbrone", column = @Column(name = "NROPBRONE", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)) })
	public IjbroneopsecaoopsId getId() {
		return this.id;
	}

	public void setId(IjbroneopsecaoopsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "NROPSECAO", referencedColumnName = "NROPSECAO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false) })
	public Ijbroneopsecao getIjbroneopsecao() {
		return this.ijbroneopsecao;
	}

	public void setIjbroneopsecao(Ijbroneopsecao ijbroneopsecao) {
		this.ijbroneopsecao = ijbroneopsecao;
	}

	@Column(name = "CDPRODUTOCOMP", nullable = false, length = 20)
	public String getCdprodutocomp() {
		return this.cdprodutocomp;
	}

	public void setCdprodutocomp(String cdprodutocomp) {
		this.cdprodutocomp = cdprodutocomp;
	}

	@Column(name = "QTDPLANEJADA", nullable = false, precision = 126, scale = 0)
	public double getQtdplanejada() {
		return this.qtdplanejada;
	}

	public void setQtdplanejada(double qtdplanejada) {
		this.qtdplanejada = qtdplanejada;
	}

}
