package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijcarteira generated by hbm2java
 */
@Entity
@Table(name = "IJCARTEIRA")
public class Ijcarteira implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5939491321991492717L;
	private String nrcarteira;
	private Ijtbcli ijtbcli;
	private Date dthrpedido;
	private String solicitante;
	private String doc;
	private String obs;
	private BigDecimal stpedido;
	private Set<Ijprocarteira> ijprocarteiras = new HashSet<Ijprocarteira>(0);
	private Set<Ijplano> ijplanos = new HashSet<Ijplano>(0);

	public Ijcarteira() {
	}

	public Ijcarteira(String nrcarteira, Ijtbcli ijtbcli) {
		this.nrcarteira = nrcarteira;
		this.ijtbcli = ijtbcli;
	}

	public Ijcarteira(String nrcarteira, Ijtbcli ijtbcli, Date dthrpedido,
			String solicitante, String doc, String obs, BigDecimal stpedido,
			Set<Ijprocarteira> ijprocarteiras, Set<Ijplano> ijplanos) {
		this.nrcarteira = nrcarteira;
		this.ijtbcli = ijtbcli;
		this.dthrpedido = dthrpedido;
		this.solicitante = solicitante;
		this.doc = doc;
		this.obs = obs;
		this.stpedido = stpedido;
		this.ijprocarteiras = ijprocarteiras;
		this.ijplanos = ijplanos;
	}

	@Id
	@Column(name = "NRCARTEIRA", unique = true, nullable = false, length = 10)
	public String getNrcarteira() {
		return this.nrcarteira;
	}

	public void setNrcarteira(String nrcarteira) {
		this.nrcarteira = nrcarteira;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCLIENTE", nullable = false)
	public Ijtbcli getIjtbcli() {
		return this.ijtbcli;
	}

	public void setIjtbcli(Ijtbcli ijtbcli) {
		this.ijtbcli = ijtbcli;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRPEDIDO", length = 7)
	public Date getDthrpedido() {
		return this.dthrpedido;
	}

	public void setDthrpedido(Date dthrpedido) {
		this.dthrpedido = dthrpedido;
	}

	@Column(name = "SOLICITANTE", length = 30)
	public String getSolicitante() {
		return this.solicitante;
	}

	public void setSolicitante(String solicitante) {
		this.solicitante = solicitante;
	}

	@Column(name = "DOC", length = 10)
	public String getDoc() {
		return this.doc;
	}

	public void setDoc(String doc) {
		this.doc = doc;
	}

	@Column(name = "OBS", length = 60)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Column(name = "STPEDIDO", precision = 22, scale = 0)
	public BigDecimal getStpedido() {
		return this.stpedido;
	}

	public void setStpedido(BigDecimal stpedido) {
		this.stpedido = stpedido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijcarteira")
	public Set<Ijprocarteira> getIjprocarteiras() {
		return this.ijprocarteiras;
	}

	public void setIjprocarteiras(Set<Ijprocarteira> ijprocarteiras) {
		this.ijprocarteiras = ijprocarteiras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijcarteira")
	public Set<Ijplano> getIjplanos() {
		return this.ijplanos;
	}

	public void setIjplanos(Set<Ijplano> ijplanos) {
		this.ijplanos = ijplanos;
	}

}
