package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjcelxestagiosId generated by hbm2java
 */
@Embeddable
public class IjcelxestagiosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7025734152069797784L;
	private String cdcelula;
	private BigDecimal estagio;

	public IjcelxestagiosId() {
	}

	public IjcelxestagiosId(String cdcelula, BigDecimal estagio) {
		this.cdcelula = cdcelula;
		this.estagio = estagio;
	}

	@Column(name = "CDCELULA", nullable = false, length = 6)
	public String getCdcelula() {
		return this.cdcelula;
	}

	public void setCdcelula(String cdcelula) {
		this.cdcelula = cdcelula;
	}

	@Column(name = "ESTAGIO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstagio() {
		return this.estagio;
	}

	public void setEstagio(BigDecimal estagio) {
		this.estagio = estagio;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjcelxestagiosId))
			return false;
		IjcelxestagiosId castOther = (IjcelxestagiosId) other;

		return ((this.getCdcelula() == castOther.getCdcelula()) || (this
				.getCdcelula() != null && castOther.getCdcelula() != null && this
				.getCdcelula().equals(castOther.getCdcelula())))
				&& ((this.getEstagio() == castOther.getEstagio()) || (this
						.getEstagio() != null && castOther.getEstagio() != null && this
						.getEstagio().equals(castOther.getEstagio())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCdcelula() == null ? 0 : this.getCdcelula().hashCode());
		result = 37 * result
				+ (getEstagio() == null ? 0 : this.getEstagio().hashCode());
		return result;
	}

}
