package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijcfgandonarg generated by hbm2java
 */
@Entity
@Table(name = "IJCFGANDONARG")
public class Ijcfgandonarg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4525664598254171933L;
	private IjcfgandonargId id;
	private Ijcfgandon ijcfgandon;
	private String operadorcalculo;
	private String operadorlogico;
	private BigDecimal tpvlreferencia;
	private String vlreferenciastr;
	private Double vlreferencianum;

	public Ijcfgandonarg() {
	}

	public Ijcfgandonarg(IjcfgandonargId id, Ijcfgandon ijcfgandon,
			BigDecimal tpvlreferencia) {
		this.id = id;
		this.ijcfgandon = ijcfgandon;
		this.tpvlreferencia = tpvlreferencia;
	}

	public Ijcfgandonarg(IjcfgandonargId id, Ijcfgandon ijcfgandon,
			String operadorcalculo, String operadorlogico,
			BigDecimal tpvlreferencia, String vlreferenciastr,
			Double vlreferencianum) {
		this.id = id;
		this.ijcfgandon = ijcfgandon;
		this.operadorcalculo = operadorcalculo;
		this.operadorlogico = operadorlogico;
		this.tpvlreferencia = tpvlreferencia;
		this.vlreferenciastr = vlreferenciastr;
		this.vlreferencianum = vlreferencianum;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ideventoandon", column = @Column(name = "IDEVENTOANDON", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "ordemcondicao", column = @Column(name = "ORDEMCONDICAO", nullable = false, precision = 22, scale = 0)) })
	public IjcfgandonargId getId() {
		return this.id;
	}

	public void setId(IjcfgandonargId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDEVENTOANDON", nullable = false, insertable = false, updatable = false)
	public Ijcfgandon getIjcfgandon() {
		return this.ijcfgandon;
	}

	public void setIjcfgandon(Ijcfgandon ijcfgandon) {
		this.ijcfgandon = ijcfgandon;
	}

	@Column(name = "OPERADORCALCULO", length = 20)
	public String getOperadorcalculo() {
		return this.operadorcalculo;
	}

	public void setOperadorcalculo(String operadorcalculo) {
		this.operadorcalculo = operadorcalculo;
	}

	@Column(name = "OPERADORLOGICO", length = 20)
	public String getOperadorlogico() {
		return this.operadorlogico;
	}

	public void setOperadorlogico(String operadorlogico) {
		this.operadorlogico = operadorlogico;
	}

	@Column(name = "TPVLREFERENCIA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpvlreferencia() {
		return this.tpvlreferencia;
	}

	public void setTpvlreferencia(BigDecimal tpvlreferencia) {
		this.tpvlreferencia = tpvlreferencia;
	}

	@Column(name = "VLREFERENCIASTR", length = 20)
	public String getVlreferenciastr() {
		return this.vlreferenciastr;
	}

	public void setVlreferenciastr(String vlreferenciastr) {
		this.vlreferenciastr = vlreferenciastr;
	}

	@Column(name = "VLREFERENCIANUM", precision = 126, scale = 0)
	public Double getVlreferencianum() {
		return this.vlreferencianum;
	}

	public void setVlreferencianum(Double vlreferencianum) {
		this.vlreferencianum = vlreferencianum;
	}

}
