package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijcfgandmaqevtarg generated by hbm2java
 */
@Entity
@Table(name = "IJCFGANDMAQEVTARG")
public class Ijcfgandmaqevtarg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5018062676046618826L;
	private IjcfgandmaqevtargId id;
	private Ijcfgandmaqevt ijcfgandmaqevt;
	private String operadorcalculo;
	private String operadorlogico;
	private BigDecimal tpvlreferencia;
	private String vlreferenciastr;
	private Double vlreferencianum;

	public Ijcfgandmaqevtarg() {
	}

	public Ijcfgandmaqevtarg(IjcfgandmaqevtargId id,
			Ijcfgandmaqevt ijcfgandmaqevt, BigDecimal tpvlreferencia) {
		this.id = id;
		this.ijcfgandmaqevt = ijcfgandmaqevt;
		this.tpvlreferencia = tpvlreferencia;
	}

	public Ijcfgandmaqevtarg(IjcfgandmaqevtargId id,
			Ijcfgandmaqevt ijcfgandmaqevt, String operadorcalculo,
			String operadorlogico, BigDecimal tpvlreferencia,
			String vlreferenciastr, Double vlreferencianum) {
		this.id = id;
		this.ijcfgandmaqevt = ijcfgandmaqevt;
		this.operadorcalculo = operadorcalculo;
		this.operadorlogico = operadorlogico;
		this.tpvlreferencia = tpvlreferencia;
		this.vlreferenciastr = vlreferenciastr;
		this.vlreferencianum = vlreferencianum;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ideventoandon", column = @Column(name = "IDEVENTOANDON", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "ordemcondicao", column = @Column(name = "ORDEMCONDICAO", nullable = false, precision = 22, scale = 0)) })
	public IjcfgandmaqevtargId getId() {
		return this.id;
	}

	public void setId(IjcfgandmaqevtargId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDEVENTOANDON", nullable = false, insertable = false, updatable = false)
	public Ijcfgandmaqevt getIjcfgandmaqevt() {
		return this.ijcfgandmaqevt;
	}

	public void setIjcfgandmaqevt(Ijcfgandmaqevt ijcfgandmaqevt) {
		this.ijcfgandmaqevt = ijcfgandmaqevt;
	}

	@Column(name = "OPERADORCALCULO", length = 20)
	public String getOperadorcalculo() {
		return this.operadorcalculo;
	}

	public void setOperadorcalculo(String operadorcalculo) {
		this.operadorcalculo = operadorcalculo;
	}

	@Column(name = "OPERADORLOGICO", length = 20)
	public String getOperadorlogico() {
		return this.operadorlogico;
	}

	public void setOperadorlogico(String operadorlogico) {
		this.operadorlogico = operadorlogico;
	}

	@Column(name = "TPVLREFERENCIA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpvlreferencia() {
		return this.tpvlreferencia;
	}

	public void setTpvlreferencia(BigDecimal tpvlreferencia) {
		this.tpvlreferencia = tpvlreferencia;
	}

	@Column(name = "VLREFERENCIASTR", length = 20)
	public String getVlreferenciastr() {
		return this.vlreferenciastr;
	}

	public void setVlreferenciastr(String vlreferenciastr) {
		this.vlreferenciastr = vlreferenciastr;
	}

	@Column(name = "VLREFERENCIANUM", precision = 126, scale = 0)
	public Double getVlreferencianum() {
		return this.vlreferencianum;
	}

	public void setVlreferencianum(Double vlreferencianum) {
		this.vlreferencianum = vlreferencianum;
	}

}
