package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijcfgdiariobrdqld generated by hbm2java
 */
@Entity
@Table(name = "IJCFGDIARIOBRDQLD")
public class Ijcfgdiariobrdqld implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4127340424870709245L;
	private IjcfgdiariobrdqldId id;

	public Ijcfgdiariobrdqld() {
	}

	public Ijcfgdiariobrdqld(IjcfgdiariobrdqldId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cfgdiariobrdqld", column = @Column(name = "CFGDIARIOBRDQLD", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tempolimaptdbqld", column = @Column(name = "TEMPOLIMAPTDBQLD", nullable = false, precision = 22, scale = 0)) })
	public IjcfgdiariobrdqldId getId() {
		return this.id;
	}

	public void setId(IjcfgdiariobrdqldId id) {
		this.id = id;
	}

}
