package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijcgfandonsinc generated by hbm2java
 */
@Entity
@Table(name = "IJCGFANDONSINC")
public class Ijcgfandonsinc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6123173548751897615L;
	private IjcgfandonsincId id;
	private Ijcfgandon ijcfgandon;
	private Ijtbmestres ijtbmestres;
	private char stsincronismo;

	public Ijcgfandonsinc() {
	}

	public Ijcgfandonsinc(IjcgfandonsincId id, Ijcfgandon ijcfgandon,
			Ijtbmestres ijtbmestres, char stsincronismo) {
		this.id = id;
		this.ijcfgandon = ijcfgandon;
		this.ijtbmestres = ijtbmestres;
		this.stsincronismo = stsincronismo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ideventoandon", column = @Column(name = "IDEVENTOANDON", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "cdmestre", column = @Column(name = "CDMESTRE", nullable = false, length = 6)) })
	public IjcgfandonsincId getId() {
		return this.id;
	}

	public void setId(IjcgfandonsincId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDEVENTOANDON", nullable = false, insertable = false, updatable = false)
	public Ijcfgandon getIjcfgandon() {
		return this.ijcfgandon;
	}

	public void setIjcfgandon(Ijcfgandon ijcfgandon) {
		this.ijcfgandon = ijcfgandon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMESTRE", nullable = false, insertable = false, updatable = false)
	public Ijtbmestres getIjtbmestres() {
		return this.ijtbmestres;
	}

	public void setIjtbmestres(Ijtbmestres ijtbmestres) {
		this.ijtbmestres = ijtbmestres;
	}

	@Column(name = "STSINCRONISMO", nullable = false, length = 1)
	public char getStsincronismo() {
		return this.stsincronismo;
	}

	public void setStsincronismo(char stsincronismo) {
		this.stsincronismo = stsincronismo;
	}

}
