package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijclassrecmanut generated by hbm2java
 */
@Entity
@Table(name = "IJCLASSRECMANUT")
public class Ijclassrecmanut implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8475497386240780549L;
	private String cdclassrecurso;
	private String dsclassrecurso;
	private Set<Ijtbrecmanut> ijtbrecmanuts = new HashSet<Ijtbrecmanut>(0);

	public Ijclassrecmanut() {
	}

	public Ijclassrecmanut(String cdclassrecurso, String dsclassrecurso) {
		this.cdclassrecurso = cdclassrecurso;
		this.dsclassrecurso = dsclassrecurso;
	}

	public Ijclassrecmanut(String cdclassrecurso, String dsclassrecurso,
			Set<Ijtbrecmanut> ijtbrecmanuts) {
		this.cdclassrecurso = cdclassrecurso;
		this.dsclassrecurso = dsclassrecurso;
		this.ijtbrecmanuts = ijtbrecmanuts;
	}

	@Id
	@Column(name = "CDCLASSRECURSO", unique = true, nullable = false, length = 6)
	public String getCdclassrecurso() {
		return this.cdclassrecurso;
	}

	public void setCdclassrecurso(String cdclassrecurso) {
		this.cdclassrecurso = cdclassrecurso;
	}

	@Column(name = "DSCLASSRECURSO", nullable = false, length = 40)
	public String getDsclassrecurso() {
		return this.dsclassrecurso;
	}

	public void setDsclassrecurso(String dsclassrecurso) {
		this.dsclassrecurso = dsclassrecurso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijclassrecmanut")
	public Set<Ijtbrecmanut> getIjtbrecmanuts() {
		return this.ijtbrecmanuts;
	}

	public void setIjtbrecmanuts(Set<Ijtbrecmanut> ijtbrecmanuts) {
		this.ijtbrecmanuts = ijtbrecmanuts;
	}

}
