package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijclassificcont generated by hbm2java
 */
@Entity
@Table(name = "IJCLASSIFICCONT")
public class Ijclassificcont implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8931310978427776558L;
	private IjclassificcontId id;
	private Ijtbtipoinf ijtbtipoinf;
	private Ijtbcont ijtbcont;
	private Set<Ijselitensmen> ijselitensmens = new HashSet<Ijselitensmen>(0);

	public Ijclassificcont() {
	}

	public Ijclassificcont(IjclassificcontId id, Ijtbtipoinf ijtbtipoinf,
			Ijtbcont ijtbcont) {
		this.id = id;
		this.ijtbtipoinf = ijtbtipoinf;
		this.ijtbcont = ijtbcont;
	}

	public Ijclassificcont(IjclassificcontId id, Ijtbtipoinf ijtbtipoinf,
			Ijtbcont ijtbcont, Set<Ijselitensmen> ijselitensmens) {
		this.id = id;
		this.ijtbtipoinf = ijtbtipoinf;
		this.ijtbcont = ijtbcont;
		this.ijselitensmens = ijselitensmens;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdtipoinf", column = @Column(name = "CDTIPOINF", nullable = false, length = 6)),
			@AttributeOverride(name = "cdcont", column = @Column(name = "CDCONT", nullable = false, length = 6)) })
	public IjclassificcontId getId() {
		return this.id;
	}

	public void setId(IjclassificcontId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTIPOINF", nullable = false, insertable = false, updatable = false)
	public Ijtbtipoinf getIjtbtipoinf() {
		return this.ijtbtipoinf;
	}

	public void setIjtbtipoinf(Ijtbtipoinf ijtbtipoinf) {
		this.ijtbtipoinf = ijtbtipoinf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCONT", nullable = false, insertable = false, updatable = false)
	public Ijtbcont getIjtbcont() {
		return this.ijtbcont;
	}

	public void setIjtbcont(Ijtbcont ijtbcont) {
		this.ijtbcont = ijtbcont;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijclassificcont")
	public Set<Ijselitensmen> getIjselitensmens() {
		return this.ijselitensmens;
	}

	public void setIjselitensmens(Set<Ijselitensmen> ijselitensmens) {
		this.ijselitensmens = ijselitensmens;
	}

}
