package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijcnsoprdut generated by hbm2java
 */
@Entity
@Table(name = "IJCNSOPRDUT")
public class Ijcnsoprdut implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6336199754467754067L;
	private IjcnsoprdutId id;
	private Date dthrfimintervalo;
	private Date dthrpriocor;
	private Date dthrultocor;
	private Double qtinjnormal;
	private Double qtinjfinparada;
	private Double qtinjnaparada;
	private Double tmpcicnormal;
	private Double tmpcicfinparada;
	private Double tmpcicnaparada;
	private Double tmpparadas;
	private Double qtinjrefugadas;
	private Double tmpparadassempeso;
	private Double tmpparadaprep;
	private Double qtparadaprep;
	private Double tmpparprev;
	private Double tmpparnaoprev;
	private Double tmppcta;
	private Double tmppao;
	private Double tmppa;
	private Double tmpptp;
	private Double cta;
	private Date dthriref;
	private Date dthrfref;
	private Character pf;
	private Double ctcp;
	private Double ctci;
	private Double ctt;
	private Character stagrup;
	private Double tmpcicespera;
	private Double tmpcicpkgcic;
	private Double qtinjpkgcic;
	private Double qtprodpkgcic;

	public Ijcnsoprdut() {
	}

	public Ijcnsoprdut(IjcnsoprdutId id) {
		this.id = id;
	}

	public Ijcnsoprdut(IjcnsoprdutId id, Date dthrfimintervalo,
			Date dthrpriocor, Date dthrultocor, Double qtinjnormal,
			Double qtinjfinparada, Double qtinjnaparada, Double tmpcicnormal,
			Double tmpcicfinparada, Double tmpcicnaparada, Double tmpparadas,
			Double qtinjrefugadas, Double tmpparadassempeso,
			Double tmpparadaprep, Double qtparadaprep, Double tmpparprev,
			Double tmpparnaoprev, Double tmppcta, Double tmppao, Double tmppa,
			Double tmpptp, Double cta, Date dthriref, Date dthrfref,
			Character pf, Double ctcp, Double ctci, Double ctt,
			Character stagrup, Double tmpcicespera) {
		this.id = id;
		this.dthrfimintervalo = dthrfimintervalo;
		this.dthrpriocor = dthrpriocor;
		this.dthrultocor = dthrultocor;
		this.qtinjnormal = qtinjnormal;
		this.qtinjfinparada = qtinjfinparada;
		this.qtinjnaparada = qtinjnaparada;
		this.tmpcicnormal = tmpcicnormal;
		this.tmpcicfinparada = tmpcicfinparada;
		this.tmpcicnaparada = tmpcicnaparada;
		this.tmpparadas = tmpparadas;
		this.qtinjrefugadas = qtinjrefugadas;
		this.tmpparadassempeso = tmpparadassempeso;
		this.tmpparadaprep = tmpparadaprep;
		this.qtparadaprep = qtparadaprep;
		this.tmpparprev = tmpparprev;
		this.tmpparnaoprev = tmpparnaoprev;
		this.tmppcta = tmppcta;
		this.tmppao = tmppao;
		this.tmppa = tmppa;
		this.tmpptp = tmpptp;
		this.cta = cta;
		this.dthriref = dthriref;
		this.dthrfref = dthrfref;
		this.pf = pf;
		this.ctcp = ctcp;
		this.ctci = ctci;
		this.ctt = ctt;
		this.stagrup = stagrup;
		this.tmpcicespera = tmpcicespera;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthriniintervalo", column = @Column(name = "DTHRINIINTERVALO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "cdoperador", column = @Column(name = "CDOPERADOR", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrivalestru", column = @Column(name = "DTHRIVALESTRU", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrivalcic", column = @Column(name = "DTHRIVALCIC", nullable = false, length = 7)) })
	public IjcnsoprdutId getId() {
		return this.id;
	}

	public void setId(IjcnsoprdutId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFIMINTERVALO", length = 7)
	public Date getDthrfimintervalo() {
		return this.dthrfimintervalo;
	}

	public void setDthrfimintervalo(Date dthrfimintervalo) {
		this.dthrfimintervalo = dthrfimintervalo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRPRIOCOR", length = 7)
	public Date getDthrpriocor() {
		return this.dthrpriocor;
	}

	public void setDthrpriocor(Date dthrpriocor) {
		this.dthrpriocor = dthrpriocor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRULTOCOR", length = 7)
	public Date getDthrultocor() {
		return this.dthrultocor;
	}

	public void setDthrultocor(Date dthrultocor) {
		this.dthrultocor = dthrultocor;
	}

	@Column(name = "QTINJNORMAL", precision = 126, scale = 0)
	public Double getQtinjnormal() {
		return this.qtinjnormal;
	}

	public void setQtinjnormal(Double qtinjnormal) {
		this.qtinjnormal = qtinjnormal;
	}

	@Column(name = "QTINJFINPARADA", precision = 126, scale = 0)
	public Double getQtinjfinparada() {
		return this.qtinjfinparada;
	}

	public void setQtinjfinparada(Double qtinjfinparada) {
		this.qtinjfinparada = qtinjfinparada;
	}

	@Column(name = "QTINJNAPARADA", precision = 126, scale = 0)
	public Double getQtinjnaparada() {
		return this.qtinjnaparada;
	}

	public void setQtinjnaparada(Double qtinjnaparada) {
		this.qtinjnaparada = qtinjnaparada;
	}

	@Column(name = "TMPCICNORMAL", precision = 126, scale = 0)
	public Double getTmpcicnormal() {
		return this.tmpcicnormal;
	}

	public void setTmpcicnormal(Double tmpcicnormal) {
		this.tmpcicnormal = tmpcicnormal;
	}

	@Column(name = "TMPCICFINPARADA", precision = 126, scale = 0)
	public Double getTmpcicfinparada() {
		return this.tmpcicfinparada;
	}

	public void setTmpcicfinparada(Double tmpcicfinparada) {
		this.tmpcicfinparada = tmpcicfinparada;
	}

	@Column(name = "TMPCICNAPARADA", precision = 126, scale = 0)
	public Double getTmpcicnaparada() {
		return this.tmpcicnaparada;
	}

	public void setTmpcicnaparada(Double tmpcicnaparada) {
		this.tmpcicnaparada = tmpcicnaparada;
	}

	@Column(name = "TMPPARADAS", precision = 126, scale = 0)
	public Double getTmpparadas() {
		return this.tmpparadas;
	}

	public void setTmpparadas(Double tmpparadas) {
		this.tmpparadas = tmpparadas;
	}

	@Column(name = "QTINJREFUGADAS", precision = 126, scale = 0)
	public Double getQtinjrefugadas() {
		return this.qtinjrefugadas;
	}

	public void setQtinjrefugadas(Double qtinjrefugadas) {
		this.qtinjrefugadas = qtinjrefugadas;
	}

	@Column(name = "TMPPARADASSEMPESO", precision = 126, scale = 0)
	public Double getTmpparadassempeso() {
		return this.tmpparadassempeso;
	}

	public void setTmpparadassempeso(Double tmpparadassempeso) {
		this.tmpparadassempeso = tmpparadassempeso;
	}

	@Column(name = "TMPPARADAPREP", precision = 126, scale = 0)
	public Double getTmpparadaprep() {
		return this.tmpparadaprep;
	}

	public void setTmpparadaprep(Double tmpparadaprep) {
		this.tmpparadaprep = tmpparadaprep;
	}

	@Column(name = "QTPARADAPREP", precision = 126, scale = 0)
	public Double getQtparadaprep() {
		return this.qtparadaprep;
	}

	public void setQtparadaprep(Double qtparadaprep) {
		this.qtparadaprep = qtparadaprep;
	}

	@Column(name = "TMPPARPREV", precision = 126, scale = 0)
	public Double getTmpparprev() {
		return this.tmpparprev;
	}

	public void setTmpparprev(Double tmpparprev) {
		this.tmpparprev = tmpparprev;
	}

	@Column(name = "TMPPARNAOPREV", precision = 126, scale = 0)
	public Double getTmpparnaoprev() {
		return this.tmpparnaoprev;
	}

	public void setTmpparnaoprev(Double tmpparnaoprev) {
		this.tmpparnaoprev = tmpparnaoprev;
	}

	@Column(name = "TMPPCTA", precision = 126, scale = 0)
	public Double getTmppcta() {
		return this.tmppcta;
	}

	public void setTmppcta(Double tmppcta) {
		this.tmppcta = tmppcta;
	}

	@Column(name = "TMPPAO", precision = 126, scale = 0)
	public Double getTmppao() {
		return this.tmppao;
	}

	public void setTmppao(Double tmppao) {
		this.tmppao = tmppao;
	}

	@Column(name = "TMPPA", precision = 126, scale = 0)
	public Double getTmppa() {
		return this.tmppa;
	}

	public void setTmppa(Double tmppa) {
		this.tmppa = tmppa;
	}

	@Column(name = "TMPPTP", precision = 126, scale = 0)
	public Double getTmpptp() {
		return this.tmpptp;
	}

	public void setTmpptp(Double tmpptp) {
		this.tmpptp = tmpptp;
	}

	@Column(name = "CTA", precision = 126, scale = 0)
	public Double getCta() {
		return this.cta;
	}

	public void setCta(Double cta) {
		this.cta = cta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIREF", length = 7)
	public Date getDthriref() {
		return this.dthriref;
	}

	public void setDthriref(Date dthriref) {
		this.dthriref = dthriref;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFREF", length = 7)
	public Date getDthrfref() {
		return this.dthrfref;
	}

	public void setDthrfref(Date dthrfref) {
		this.dthrfref = dthrfref;
	}

	@Column(name = "PF", length = 1)
	public Character getPf() {
		return this.pf;
	}

	public void setPf(Character pf) {
		this.pf = pf;
	}

	@Column(name = "CTCP", precision = 126, scale = 0)
	public Double getCtcp() {
		return this.ctcp;
	}

	public void setCtcp(Double ctcp) {
		this.ctcp = ctcp;
	}

	@Column(name = "CTCI", precision = 126, scale = 0)
	public Double getCtci() {
		return this.ctci;
	}

	public void setCtci(Double ctci) {
		this.ctci = ctci;
	}

	@Column(name = "CTT", precision = 126, scale = 0)
	public Double getCtt() {
		return this.ctt;
	}

	public void setCtt(Double ctt) {
		this.ctt = ctt;
	}

	@Column(name = "STAGRUP", length = 1)
	public Character getStagrup() {
		return this.stagrup;
	}

	public void setStagrup(Character stagrup) {
		this.stagrup = stagrup;
	}

	@Column(name = "TMPCICESPERA", precision = 126, scale = 0)
	public Double getTmpcicespera() {
		return this.tmpcicespera;
	}

	public void setTmpcicespera(Double tmpcicespera) {
		this.tmpcicespera = tmpcicespera;
	}
	
	@Column(name = "TMPCICPKGCIC", precision = 126, scale = 0)
	public Double getTmpcicpkgcic() {
		return tmpcicpkgcic;
	}

	public void setTmpcicpkgcic(Double tmpcicpkgcic) {
		this.tmpcicpkgcic = tmpcicpkgcic;
	}

	@Column(name = "QTINJPKGCIC", precision = 126, scale = 0)
	public Double getQtinjpkgcic() {
		return qtinjpkgcic;
	}

	public void setQtinjpkgcic(Double qtinjpkgcic) {
		this.qtinjpkgcic = qtinjpkgcic;
	}

	@Column(name = "QTPRODPKGCIC", precision = 126, scale = 0)
	public Double getQtprodpkgcic() {
		return qtprodpkgcic;
	}

	public void setQtprodpkgcic(Double qtprodpkgcic) {
		this.qtprodpkgcic = qtprodpkgcic;
	}

}
