package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijcnsdivergencia generated by hbm2java
 */
@Entity
@Table(name = "IJCNSDIVERGENCIA")
public class Ijcnsdivergencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8557882363205143504L;
	private String idapontamento;
	private Date dtturno;
	private String cdturno;
	private String cdinjetora;
	private String nrop;
	private String cdmolde;
	private String cdestrutura;
	private Date dthrivalestru;
	private String cdoperador;
	private String cdproduto;
	private double pesoteorico;
	private double pesomediolido;
	private double qtapontada;
	private Date dthrsolicapont;
	private double divacum;

	public Ijcnsdivergencia() {
	}

	public Ijcnsdivergencia(String idapontamento, Date dtturno, String cdturno,
			String cdinjetora, String nrop, String cdmolde, String cdestrutura,
			Date dthrivalestru, String cdproduto, double pesoteorico,
			double pesomediolido, double qtapontada, Date dthrsolicapont,
			double divacum) {
		this.idapontamento = idapontamento;
		this.dtturno = dtturno;
		this.cdturno = cdturno;
		this.cdinjetora = cdinjetora;
		this.nrop = nrop;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.dthrivalestru = dthrivalestru;
		this.cdproduto = cdproduto;
		this.pesoteorico = pesoteorico;
		this.pesomediolido = pesomediolido;
		this.qtapontada = qtapontada;
		this.dthrsolicapont = dthrsolicapont;
		this.divacum = divacum;
	}

	public Ijcnsdivergencia(String idapontamento, Date dtturno, String cdturno,
			String cdinjetora, String nrop, String cdmolde, String cdestrutura,
			Date dthrivalestru, String cdoperador, String cdproduto,
			double pesoteorico, double pesomediolido, double qtapontada,
			Date dthrsolicapont, double divacum) {
		this.idapontamento = idapontamento;
		this.dtturno = dtturno;
		this.cdturno = cdturno;
		this.cdinjetora = cdinjetora;
		this.nrop = nrop;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.dthrivalestru = dthrivalestru;
		this.cdoperador = cdoperador;
		this.cdproduto = cdproduto;
		this.pesoteorico = pesoteorico;
		this.pesomediolido = pesomediolido;
		this.qtapontada = qtapontada;
		this.dthrsolicapont = dthrsolicapont;
		this.divacum = divacum;
	}

	@Id
	@Column(name = "IDAPONTAMENTO", unique = true, nullable = false, length = 15)
	public String getIdapontamento() {
		return this.idapontamento;
	}

	public void setIdapontamento(String idapontamento) {
		this.idapontamento = idapontamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTTURNO", nullable = false, length = 7)
	public Date getDtturno() {
		return this.dtturno;
	}

	public void setDtturno(Date dtturno) {
		this.dtturno = dtturno;
	}

	@Column(name = "CDTURNO", nullable = false, length = 6)
	public String getCdturno() {
		return this.cdturno;
	}

	public void setCdturno(String cdturno) {
		this.cdturno = cdturno;
	}

	@Column(name = "CDINJETORA", nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Column(name = "NROP", nullable = false, length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "CDMOLDE", nullable = false, length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "CDESTRUTURA", nullable = false, length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIVALESTRU", nullable = false, length = 7)
	public Date getDthrivalestru() {
		return this.dthrivalestru;
	}

	public void setDthrivalestru(Date dthrivalestru) {
		this.dthrivalestru = dthrivalestru;
	}

	@Column(name = "CDOPERADOR", length = 6)
	public String getCdoperador() {
		return this.cdoperador;
	}

	public void setCdoperador(String cdoperador) {
		this.cdoperador = cdoperador;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "PESOTEORICO", nullable = false, precision = 126, scale = 0)
	public double getPesoteorico() {
		return this.pesoteorico;
	}

	public void setPesoteorico(double pesoteorico) {
		this.pesoteorico = pesoteorico;
	}

	@Column(name = "PESOMEDIOLIDO", nullable = false, precision = 126, scale = 0)
	public double getPesomediolido() {
		return this.pesomediolido;
	}

	public void setPesomediolido(double pesomediolido) {
		this.pesomediolido = pesomediolido;
	}

	@Column(name = "QTAPONTADA", nullable = false, precision = 126, scale = 0)
	public double getQtapontada() {
		return this.qtapontada;
	}

	public void setQtapontada(double qtapontada) {
		this.qtapontada = qtapontada;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRSOLICAPONT", nullable = false, length = 7)
	public Date getDthrsolicapont() {
		return this.dthrsolicapont;
	}

	public void setDthrsolicapont(Date dthrsolicapont) {
		this.dthrsolicapont = dthrsolicapont;
	}

	@Column(name = "DIVACUM", nullable = false, precision = 126, scale = 0)
	public double getDivacum() {
		return this.divacum;
	}

	public void setDivacum(double divacum) {
		this.divacum = divacum;
	}

}
