package idw.model.pojos.injet;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import idw.model.pojos.injet.template.IjcnsmaqopTemplate;

/**
 * Ijcnsmaqop generated by hbm2java
 */
@Entity
@Table(name = "IJCNSMAQOP")
public class Ijcnsmaqop extends IjcnsmaqopTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8328933699190175122L;
	private IjcnsmaqopId id;
	private Double qtinjnormal;
	private Double qtinjfinparada;
	private Double qtinjnaparada;
	private BigDecimal tmpcicnormal;
	private BigDecimal tmpcicfinparada;
	private Double tmpcicnaparada;
	private BigDecimal tmpparadas;
	private Double qtinjrefugadas;
	private Double tmpparadassempeso;
	private Double tmpparadaprep;
	private Double qtparadaprep;
	private Double tmpparprev;
	private Double tmpparnaoprev;
	private Double tmppcta;
	private Double tmppao;
	private Double tmppa;
	private Double tmpptp;
	private Double cta;
	private Date dthriref;
	private Date dthrfref;
	private BigDecimal ctcp;
	private BigDecimal ctci;
	private BigDecimal ctt;
	private Character stagrup;
	private Double tmpcicespera;
	private Double tmpcicpkgcic;
	private Double qtinjpkgcic;
	private Double qtprodpkgcic;

	public Ijcnsmaqop() {
	}

	public Ijcnsmaqop(IjcnsmaqopId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "dthrivalestru", column = @Column(name = "DTHRIVALESTRU", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrivalcic", column = @Column(name = "DTHRIVALCIC", nullable = false, length = 7)) })
	public IjcnsmaqopId getId() {
		return this.id;
	}

	public void setId(IjcnsmaqopId id) {
		this.id = id;
	}

	@Column(name = "QTINJNORMAL", precision = 126, scale = 0)
	public Double getQtinjnormal() {
		return this.qtinjnormal;
	}

	public void setQtinjnormal(Double qtinjnormal) {
		this.qtinjnormal = qtinjnormal;
	}

	@Column(name = "QTINJFINPARADA", precision = 126, scale = 0)
	public Double getQtinjfinparada() {
		return this.qtinjfinparada;
	}

	public void setQtinjfinparada(Double qtinjfinparada) {
		this.qtinjfinparada = qtinjfinparada;
	}

	@Column(name = "QTINJNAPARADA", precision = 126, scale = 0)
	public Double getQtinjnaparada() {
		return this.qtinjnaparada;
	}

	public void setQtinjnaparada(Double qtinjnaparada) {
		this.qtinjnaparada = qtinjnaparada;
	}

	@Column(name = "TMPCICNORMAL", precision = 126, scale = 0)
	public BigDecimal getTmpcicnormal() {
		return this.tmpcicnormal;
	}

	public void setTmpcicnormal(BigDecimal tmpcicnormal) {
		this.tmpcicnormal = tmpcicnormal;
	}

	@Column(name = "TMPCICFINPARADA", precision = 126, scale = 0)
	public BigDecimal getTmpcicfinparada() {
		return this.tmpcicfinparada;
	}

	public void setTmpcicfinparada(BigDecimal tmpcicfinparada) {
		this.tmpcicfinparada = tmpcicfinparada;
	}

	@Column(name = "TMPCICNAPARADA", precision = 126, scale = 0)
	public Double getTmpcicnaparada() {
		return this.tmpcicnaparada;
	}

	public void setTmpcicnaparada(Double tmpcicnaparada) {
		this.tmpcicnaparada = tmpcicnaparada;
	}

	@Column(name = "TMPPARADAS", precision = 126, scale = 0)
	public BigDecimal getTmpparadas() {
		return this.tmpparadas;
	}

	public void setTmpparadas(BigDecimal tmpparadas) {
		this.tmpparadas = tmpparadas;
	}

	@Column(name = "QTINJREFUGADAS", precision = 126, scale = 0)
	public Double getQtinjrefugadas() {
		return this.qtinjrefugadas;
	}

	public void setQtinjrefugadas(Double qtinjrefugadas) {
		this.qtinjrefugadas = qtinjrefugadas;
	}

	@Column(name = "TMPPARADASSEMPESO", precision = 126, scale = 0)
	public Double getTmpparadassempeso() {
		return this.tmpparadassempeso;
	}

	public void setTmpparadassempeso(Double tmpparadassempeso) {
		this.tmpparadassempeso = tmpparadassempeso;
	}

	@Column(name = "TMPPARADAPREP", precision = 126, scale = 0)
	public Double getTmpparadaprep() {
		return this.tmpparadaprep;
	}

	public void setTmpparadaprep(Double tmpparadaprep) {
		this.tmpparadaprep = tmpparadaprep;
	}

	@Column(name = "QTPARADAPREP", precision = 126, scale = 0)
	public Double getQtparadaprep() {
		return this.qtparadaprep;
	}

	public void setQtparadaprep(Double qtparadaprep) {
		this.qtparadaprep = qtparadaprep;
	}

	@Column(name = "TMPPARPREV", precision = 126, scale = 0)
	public Double getTmpparprev() {
		return this.tmpparprev;
	}

	public void setTmpparprev(Double tmpparprev) {
		this.tmpparprev = tmpparprev;
	}

	@Column(name = "TMPPARNAOPREV", precision = 126, scale = 0)
	public Double getTmpparnaoprev() {
		return this.tmpparnaoprev;
	}

	public void setTmpparnaoprev(Double tmpparnaoprev) {
		this.tmpparnaoprev = tmpparnaoprev;
	}

	@Column(name = "TMPPCTA", precision = 126, scale = 0)
	public Double getTmppcta() {
		return this.tmppcta;
	}

	public void setTmppcta(Double tmppcta) {
		this.tmppcta = tmppcta;
	}

	@Column(name = "TMPPAO", precision = 126, scale = 0)
	public Double getTmppao() {
		return this.tmppao;
	}

	public void setTmppao(Double tmppao) {
		this.tmppao = tmppao;
	}

	@Column(name = "TMPPA", precision = 126, scale = 0)
	public Double getTmppa() {
		return this.tmppa;
	}

	public void setTmppa(Double tmppa) {
		this.tmppa = tmppa;
	}

	@Column(name = "TMPPTP", precision = 126, scale = 0)
	public Double getTmpptp() {
		return this.tmpptp;
	}

	public void setTmpptp(Double tmpptp) {
		this.tmpptp = tmpptp;
	}

	@Column(name = "CTA", precision = 126, scale = 0)
	public Double getCta() {
		return this.cta;
	}

	public void setCta(Double cta) {
		this.cta = cta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIREF", length = 7)
	public Date getDthriref() {
		return this.dthriref;
	}

	public void setDthriref(Date dthriref) {
		this.dthriref = dthriref;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFREF", length = 7)
	public Date getDthrfref() {
		return this.dthrfref;
	}

	public void setDthrfref(Date dthrfref) {
		this.dthrfref = dthrfref;
	}

	@Column(name = "CTCP", precision = 126, scale = 0)
	public BigDecimal getCtcp() {
		return this.ctcp;
	}

	public void setCtcp(BigDecimal ctcp) {
		this.ctcp = ctcp;
	}

	@Column(name = "CTCI", precision = 126, scale = 0)
	public BigDecimal getCtci() {
		return this.ctci;
	}

	public void setCtci(BigDecimal ctci) {
		this.ctci = ctci;
	}

	@Column(name = "CTT", precision = 126, scale = 0)
	public BigDecimal getCtt() {
		return this.ctt;
	}

	public void setCtt(BigDecimal ctt) {
		this.ctt = ctt;
	}

	@Column(name = "STAGRUP", length = 1)
	public Character getStagrup() {
		return this.stagrup;
	}

	public void setStagrup(Character stagrup) {
		this.stagrup = stagrup;
	}

	@Column(name = "TMPCICESPERA", precision = 126, scale = 0)
	public Double getTmpcicespera() {
		return this.tmpcicespera;
	}

	public void setTmpcicespera(Double tmpcicespera) {
		this.tmpcicespera = tmpcicespera;
	}

	@Column(name = "TMPCICPKGCIC", precision = 126, scale = 0)
	public Double getTmpcicpkgcic() {
		return tmpcicpkgcic;
	}

	public void setTmpcicpkgcic(Double tmpcicpkgcic) {
		this.tmpcicpkgcic = tmpcicpkgcic;
	}

	@Column(name = "QTINJPKGCIC", precision = 126, scale = 0)
	public Double getQtinjpkgcic() {
		return qtinjpkgcic;
	}

	public void setQtinjpkgcic(Double qtinjpkgcic) {
		this.qtinjpkgcic = qtinjpkgcic;
	}

	@Column(name = "QTPRODPKGCIC", precision = 126, scale = 0)
	public Double getQtprodpkgcic() {
		return qtprodpkgcic;
	}

	public void setQtprodpkgcic(Double qtprodpkgcic) {
		this.qtprodpkgcic = qtprodpkgcic;
	}
}
