package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijconsumoenergia generated by hbm2java
 */
@Entity
@Table(name = "IJCONSUMOENERGIA")
public class Ijconsumoenergia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7445245951646232817L;
	private IjconsumoenergiaId id;
	private double consumo;

	public Ijconsumoenergia() {
	}

	public Ijconsumoenergia(IjconsumoenergiaId id, double consumo) {
		this.id = id;
		this.consumo = consumo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ano", column = @Column(name = "ANO", nullable = false, length = 4)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", nullable = false, length = 2)) })
	public IjconsumoenergiaId getId() {
		return this.id;
	}

	public void setId(IjconsumoenergiaId id) {
		this.id = id;
	}

	@Column(name = "CONSUMO", nullable = false, precision = 126, scale = 0)
	public double getConsumo() {
		return this.consumo;
	}

	public void setConsumo(double consumo) {
		this.consumo = consumo;
	}

}
