package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijconger generated by hbm2java
 */
@Entity
@Table(name = "IJCONGER")
public class Ijconger implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 844366087853567458L;
	private IjcongerId id;

	public Ijconger() {
	}

	public Ijconger(IjcongerId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "qtcicmon", column = @Column(name = "QTCICMON", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "qtcicarm", column = @Column(name = "QTCICARM", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "tecontagememuso", column = @Column(name = "TECONTAGEMEMUSO", nullable = false, length = 18)),
			@AttributeOverride(name = "lrefugartodaspecas", column = @Column(name = "LREFUGARTODASPECAS", nullable = false, length = 18)),
			@AttributeOverride(name = "hrreferencia", column = @Column(name = "HRREFERENCIA", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "tempotimeoutescr", column = @Column(name = "TEMPOTIMEOUTESCR", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "indrefmaiorque", column = @Column(name = "INDREFMAIORQUE", precision = 126, scale = 0)),
			@AttributeOverride(name = "padraomediosetup", column = @Column(name = "PADRAOMEDIOSETUP", precision = 22, scale = 0)),
			@AttributeOverride(name = "metaefisetup", column = @Column(name = "METAEFISETUP", precision = 126, scale = 0)),
			@AttributeOverride(name = "metaatendimento", column = @Column(name = "METAATENDIMENTO", precision = 126, scale = 0)),
			@AttributeOverride(name = "metautilizacao", column = @Column(name = "METAUTILIZACAO", precision = 126, scale = 0)),
			@AttributeOverride(name = "metaeficiencia", column = @Column(name = "METAEFICIENCIA", precision = 126, scale = 0)),
			@AttributeOverride(name = "metaprodutividade", column = @Column(name = "METAPRODUTIVIDADE", precision = 126, scale = 0)),
			@AttributeOverride(name = "metappmil", column = @Column(name = "METAPPMIL", precision = 126, scale = 0)),
			@AttributeOverride(name = "univamostraqld", column = @Column(name = "UNIVAMOSTRAQLD", precision = 126, scale = 0)),
			@AttributeOverride(name = "tmpsetuppadrao", column = @Column(name = "TMPSETUPPADRAO", precision = 126, scale = 0)),
			@AttributeOverride(name = "efireapadrao", column = @Column(name = "EFIREAPADRAO", precision = 126, scale = 0)),
			@AttributeOverride(name = "relctrlprodefirea", column = @Column(name = "RELCTRLPRODEFIREA", precision = 126, scale = 0)),
			@AttributeOverride(name = "relctrlprodindref", column = @Column(name = "RELCTRLPRODINDREF", precision = 126, scale = 0)),
			@AttributeOverride(name = "maxtmpmicroparada", column = @Column(name = "MAXTMPMICROPARADA", precision = 22, scale = 0)),
			@AttributeOverride(name = "tpverifconcop", column = @Column(name = "TPVERIFCONCOP", length = 1)),
			@AttributeOverride(name = "vlverifconcop", column = @Column(name = "VLVERIFCONCOP", precision = 126, scale = 0)),
			@AttributeOverride(name = "idplanta", column = @Column(name = "IDPLANTA", length = 10)),
			@AttributeOverride(name = "idareaproducao", column = @Column(name = "IDAREAPRODUCAO", length = 10)),
			@AttributeOverride(name = "libaramreqsup", column = @Column(name = "LIBARAMREQSUP", length = 1)),
			@AttributeOverride(name = "tampulmaopadrao", column = @Column(name = "TAMPULMAOPADRAO", precision = 126, scale = 0)),
			@AttributeOverride(name = "tampulmaomax", column = @Column(name = "TAMPULMAOMAX", precision = 126, scale = 0)),
			@AttributeOverride(name = "tampulmaomin", column = @Column(name = "TAMPULMAOMIN", precision = 126, scale = 0)),
			@AttributeOverride(name = "tmptimeoutcolet", column = @Column(name = "TMPTIMEOUTCOLET", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "tamamostra", column = @Column(name = "TAMAMOSTRA", precision = 22, scale = 0)),
			@AttributeOverride(name = "coletaamstrporcav", column = @Column(name = "COLETAAMSTRPORCAV", length = 1)),
			@AttributeOverride(name = "tpespeclimites", column = @Column(name = "TPESPECLIMITES", length = 1)),
			@AttributeOverride(name = "tpmedinspqld", column = @Column(name = "TPMEDINSPQLD", nullable = false, length = 1)),
			@AttributeOverride(name = "exclistedicaostd", column = @Column(name = "EXCLISTEDICAOSTD", nullable = false, length = 1)),
			@AttributeOverride(name = "exibebkgclraleinsp", column = @Column(name = "EXIBEBKGCLRALEINSP", nullable = false, length = 1)),
			@AttributeOverride(name = "obsdefrelcgq", column = @Column(name = "OBSDEFRELCGQ", length = 250)),
			@AttributeOverride(name = "refamostfespec", column = @Column(name = "REFAMOSTFESPEC", length = 1)),
			@AttributeOverride(name = "cdrfgamostabxespcf", column = @Column(name = "CDRFGAMOSTABXESPCF", length = 20)),
			@AttributeOverride(name = "cdrfgamostacmespcf", column = @Column(name = "CDRFGAMOSTACMESPCF", length = 20)),
			@AttributeOverride(name = "ctrlaleprobqld", column = @Column(name = "CTRLALEPROBQLD", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "bloqcgqitemforaesp", column = @Column(name = "BLOQCGQITEMFORAESP", nullable = false, precision = 22, scale = 0)) })
	public IjcongerId getId() {
		return this.id;
	}

	public void setId(IjcongerId id) {
		this.id = id;
	}

}
