package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjcomppromprimaId generated by hbm2java
 */
@Embeddable
public class IjcomppromprimaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4081466896418667165L;
	private String cdproduto;
	private String cdmprima;

	public IjcomppromprimaId() {
	}

	public IjcomppromprimaId(String cdproduto, String cdmprima) {
		this.cdproduto = cdproduto;
		this.cdmprima = cdmprima;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "CDMPRIMA", nullable = false, length = 20)
	public String getCdmprima() {
		return this.cdmprima;
	}

	public void setCdmprima(String cdmprima) {
		this.cdmprima = cdmprima;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjcomppromprimaId))
			return false;
		IjcomppromprimaId castOther = (IjcomppromprimaId) other;

		return ((this.getCdproduto() == castOther.getCdproduto()) || (this
				.getCdproduto() != null && castOther.getCdproduto() != null && this
				.getCdproduto().equals(castOther.getCdproduto())))
				&& ((this.getCdmprima() == castOther.getCdmprima()) || (this
						.getCdmprima() != null
						&& castOther.getCdmprima() != null && this
						.getCdmprima().equals(castOther.getCdmprima())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCdproduto() == null ? 0 : this.getCdproduto().hashCode());
		result = 37 * result
				+ (getCdmprima() == null ? 0 : this.getCdmprima().hashCode());
		return result;
	}

}
