package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijcomequipamento generated by hbm2java
 */
@Entity
@Table(name = "IJCOMEQUIPAMENTO")
public class Ijcomequipamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2588037709486610947L;
	private IjcomequipamentoId id;
	private Ijtbequipamentos ijtbequipamentos;
	private Ijtbinj ijtbinj;
	private BigDecimal stequipamento;

	public Ijcomequipamento() {
	}

	public Ijcomequipamento(IjcomequipamentoId id,
			Ijtbequipamentos ijtbequipamentos, Ijtbinj ijtbinj,
			BigDecimal stequipamento) {
		this.id = id;
		this.ijtbequipamentos = ijtbequipamentos;
		this.ijtbinj = ijtbinj;
		this.stequipamento = stequipamento;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "idequipamento", column = @Column(name = "IDEQUIPAMENTO", nullable = false, length = 20)) })
	public IjcomequipamentoId getId() {
		return this.id;
	}

	public void setId(IjcomequipamentoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDEQUIPAMENTO", nullable = false, insertable = false, updatable = false)
	public Ijtbequipamentos getIjtbequipamentos() {
		return this.ijtbequipamentos;
	}

	public void setIjtbequipamentos(Ijtbequipamentos ijtbequipamentos) {
		this.ijtbequipamentos = ijtbequipamentos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "STEQUIPAMENTO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStequipamento() {
		return this.stequipamento;
	}

	public void setStequipamento(BigDecimal stequipamento) {
		this.stequipamento = stequipamento;
	}

}
