package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijcontenvio generated by hbm2java
 */
@Entity
@Table(name = "IJCONTENVIO")
public class Ijcontenvio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4926464856576453678L;
	private String cdcontenvio;
	private String cdsolicitacao;
	private String nomearqger;
	private String cdselecao;
	private String cdinf;
	private String cdtipoinf;
	private Date dthrenvio;
	private BigDecimal qtdetent;
	private String indresultenvio;
	private String resultenvio;

	public Ijcontenvio() {
	}

	public Ijcontenvio(String cdcontenvio) {
		this.cdcontenvio = cdcontenvio;
	}

	public Ijcontenvio(String cdcontenvio, String cdsolicitacao,
			String nomearqger, String cdselecao, String cdinf,
			String cdtipoinf, Date dthrenvio, BigDecimal qtdetent,
			String indresultenvio, String resultenvio) {
		this.cdcontenvio = cdcontenvio;
		this.cdsolicitacao = cdsolicitacao;
		this.nomearqger = nomearqger;
		this.cdselecao = cdselecao;
		this.cdinf = cdinf;
		this.cdtipoinf = cdtipoinf;
		this.dthrenvio = dthrenvio;
		this.qtdetent = qtdetent;
		this.indresultenvio = indresultenvio;
		this.resultenvio = resultenvio;
	}

	@Id
	@Column(name = "CDCONTENVIO", unique = true, nullable = false, length = 10)
	public String getCdcontenvio() {
		return this.cdcontenvio;
	}

	public void setCdcontenvio(String cdcontenvio) {
		this.cdcontenvio = cdcontenvio;
	}

	@Column(name = "CDSOLICITACAO", length = 20)
	public String getCdsolicitacao() {
		return this.cdsolicitacao;
	}

	public void setCdsolicitacao(String cdsolicitacao) {
		this.cdsolicitacao = cdsolicitacao;
	}

	@Column(name = "NOMEARQGER", length = 30)
	public String getNomearqger() {
		return this.nomearqger;
	}

	public void setNomearqger(String nomearqger) {
		this.nomearqger = nomearqger;
	}

	@Column(name = "CDSELECAO", length = 6)
	public String getCdselecao() {
		return this.cdselecao;
	}

	public void setCdselecao(String cdselecao) {
		this.cdselecao = cdselecao;
	}

	@Column(name = "CDINF", length = 6)
	public String getCdinf() {
		return this.cdinf;
	}

	public void setCdinf(String cdinf) {
		this.cdinf = cdinf;
	}

	@Column(name = "CDTIPOINF", length = 6)
	public String getCdtipoinf() {
		return this.cdtipoinf;
	}

	public void setCdtipoinf(String cdtipoinf) {
		this.cdtipoinf = cdtipoinf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRENVIO", length = 7)
	public Date getDthrenvio() {
		return this.dthrenvio;
	}

	public void setDthrenvio(Date dthrenvio) {
		this.dthrenvio = dthrenvio;
	}

	@Column(name = "QTDETENT", precision = 22, scale = 0)
	public BigDecimal getQtdetent() {
		return this.qtdetent;
	}

	public void setQtdetent(BigDecimal qtdetent) {
		this.qtdetent = qtdetent;
	}

	@Column(name = "INDRESULTENVIO", length = 1)
	public String getIndresultenvio() {
		return this.indresultenvio;
	}

	public void setIndresultenvio(String indresultenvio) {
		this.indresultenvio = indresultenvio;
	}

	@Column(name = "RESULTENVIO")
	public String getResultenvio() {
		return this.resultenvio;
	}

	public void setResultenvio(String resultenvio) {
		this.resultenvio = resultenvio;
	}

}
