package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijctrlcgqxctts generated by hbm2java
 */
@Entity
@Table(name = "IJCTRLCGQXCTTS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDCTRLALTCGQ", "CDCLIENTE", "PLANTA", "EMAILCTT" }))
public class Ijctrlcgqxctts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -998391926860540559L;
	private double idregistro;
	private Ijctrlcgqalt ijctrlcgqalt;
	private Ijtbclixcttcgq ijtbclixcttcgq;

	public Ijctrlcgqxctts() {
	}

	public Ijctrlcgqxctts(double idregistro, Ijctrlcgqalt ijctrlcgqalt,
			Ijtbclixcttcgq ijtbclixcttcgq) {
		this.idregistro = idregistro;
		this.ijctrlcgqalt = ijctrlcgqalt;
		this.ijtbclixcttcgq = ijtbclixcttcgq;
	}

	@Id
	@Column(name = "IDREGISTRO", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(double idregistro) {
		this.idregistro = idregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCTRLALTCGQ", nullable = false)
	public Ijctrlcgqalt getIjctrlcgqalt() {
		return this.ijctrlcgqalt;
	}

	public void setIjctrlcgqalt(Ijctrlcgqalt ijctrlcgqalt) {
		this.ijctrlcgqalt = ijctrlcgqalt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDCLIENTE", referencedColumnName = "CDCLIENTE", nullable = false),
			@JoinColumn(name = "PLANTA", referencedColumnName = "PLANTA", nullable = false),
			@JoinColumn(name = "EMAILCTT", referencedColumnName = "EMAILCTT", nullable = false) })
	public Ijtbclixcttcgq getIjtbclixcttcgq() {
		return this.ijtbclixcttcgq;
	}

	public void setIjtbclixcttcgq(Ijtbclixcttcgq ijtbclixcttcgq) {
		this.ijtbclixcttcgq = ijtbclixcttcgq;
	}

}
