package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijctrlalertaandon generated by hbm2java
 */
@Entity
@Table(name = "IJCTRLALERTAANDON")
public class Ijctrlalertaandon implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3175273230443798760L;
	private String cdinjetora;
	private Ijtbinj ijtbinj;
	private String nrop;
	private String cdmolde;
	private String cdestrutura;
	private String cdproduto;
	private Date dthralerta;
	private BigDecimal tmpliminspqld;
	private String idinspecao;

	public Ijctrlalertaandon() {
	}

	public Ijctrlalertaandon(String cdinjetora, Ijtbinj ijtbinj) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
	}

	public Ijctrlalertaandon(String cdinjetora, Ijtbinj ijtbinj, String nrop,
			String cdmolde, String cdestrutura, String cdproduto,
			Date dthralerta, BigDecimal tmpliminspqld, String idinspecao) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.nrop = nrop;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.cdproduto = cdproduto;
		this.dthralerta = dthralerta;
		this.tmpliminspqld = tmpliminspqld;
		this.idinspecao = idinspecao;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "NROP", length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "CDMOLDE", length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "CDESTRUTURA", length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Column(name = "CDPRODUTO", length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRALERTA", length = 7)
	public Date getDthralerta() {
		return this.dthralerta;
	}

	public void setDthralerta(Date dthralerta) {
		this.dthralerta = dthralerta;
	}

	@Column(name = "TMPLIMINSPQLD", precision = 22, scale = 0)
	public BigDecimal getTmpliminspqld() {
		return this.tmpliminspqld;
	}

	public void setTmpliminspqld(BigDecimal tmpliminspqld) {
		this.tmpliminspqld = tmpliminspqld;
	}

	@Column(name = "IDINSPECAO", length = 12)
	public String getIdinspecao() {
		return this.idinspecao;
	}

	public void setIdinspecao(String idinspecao) {
		this.idinspecao = idinspecao;
	}

}
