package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijdeparamaq generated by hbm2java
 */
@Entity
@Table(name = "IJDEPARAMAQ", uniqueConstraints = @UniqueConstraint(columnNames = "CDINJETORA"))
public class Ijdeparamaq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9206003259960799585L;
	private String cdmaqauxiliar;
	private Ijtbinj ijtbinj;

	public Ijdeparamaq() {
	}

	public Ijdeparamaq(String cdmaqauxiliar) {
		this.cdmaqauxiliar = cdmaqauxiliar;
	}

	public Ijdeparamaq(String cdmaqauxiliar, Ijtbinj ijtbinj) {
		this.cdmaqauxiliar = cdmaqauxiliar;
		this.ijtbinj = ijtbinj;
	}

	@Id
	@Column(name = "CDMAQAUXILIAR", unique = true, nullable = false, length = 30)
	public String getCdmaqauxiliar() {
		return this.cdmaqauxiliar;
	}

	public void setCdmaqauxiliar(String cdmaqauxiliar) {
		this.cdmaqauxiliar = cdmaqauxiliar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

}
