package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijdeparamol generated by hbm2java
 */
@Entity
@Table(name = "IJDEPARAMOL", uniqueConstraints = @UniqueConstraint(columnNames = "CDMOLDE"))
public class Ijdeparamol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1600112242573575910L;
	private String cdmoldeauxiliar;
	private Ijtbmol ijtbmol;

	public Ijdeparamol() {
	}

	public Ijdeparamol(String cdmoldeauxiliar) {
		this.cdmoldeauxiliar = cdmoldeauxiliar;
	}

	public Ijdeparamol(String cdmoldeauxiliar, Ijtbmol ijtbmol) {
		this.cdmoldeauxiliar = cdmoldeauxiliar;
		this.ijtbmol = ijtbmol;
	}

	@Id
	@Column(name = "CDMOLDEAUXILIAR", unique = true, nullable = false, length = 30)
	public String getCdmoldeauxiliar() {
		return this.cdmoldeauxiliar;
	}

	public void setCdmoldeauxiliar(String cdmoldeauxiliar) {
		this.cdmoldeauxiliar = cdmoldeauxiliar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMOLDE", unique = true)
	public Ijtbmol getIjtbmol() {
		return this.ijtbmol;
	}

	public void setIjtbmol(Ijtbmol ijtbmol) {
		this.ijtbmol = ijtbmol;
	}

}
