package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijdiremp generated by hbm2java
 */
@Entity
@Table(name = "IJDIREMP")
public class Ijdiremp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4067662641669034002L;
	private IjdirempId id;
	private Ijtbopcmenu ijtbopcmenu;

	public Ijdiremp() {
	}

	public Ijdiremp(IjdirempId id, Ijtbopcmenu ijtbopcmenu) {
		this.id = id;
		this.ijtbopcmenu = ijtbopcmenu;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idempresa", column = @Column(name = "IDEMPRESA", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdopcao", column = @Column(name = "CDOPCAO", nullable = false, length = 6)) })
	public IjdirempId getId() {
		return this.id;
	}

	public void setId(IjdirempId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDOPCAO", nullable = false, insertable = false, updatable = false)
	public Ijtbopcmenu getIjtbopcmenu() {
		return this.ijtbopcmenu;
	}

	public void setIjtbopcmenu(Ijtbopcmenu ijtbopcmenu) {
		this.ijtbopcmenu = ijtbopcmenu;
	}

}
