package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijdrvcntexecprtdef generated by hbm2java
 */
@Entity
@Table(name = "IJDRVCNTEXECPRTDEF")
public class Ijdrvcntexecprtdef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5913501548389045550L;
	private IjdrvcntexecprtdefId id;
	private Ijtbcentinsp ijtbcentinsp;
	private Ijtbdrivers ijtbdrivers;
	private Ijprodxgrpparam ijprodxgrpparam;
	private Ijparaminspec ijparaminspec;
	private String idportacomdef;

	public Ijdrvcntexecprtdef() {
	}

	public Ijdrvcntexecprtdef(IjdrvcntexecprtdefId id,
			Ijtbcentinsp ijtbcentinsp, Ijtbdrivers ijtbdrivers,
			Ijprodxgrpparam ijprodxgrpparam, Ijparaminspec ijparaminspec,
			String idportacomdef) {
		this.id = id;
		this.ijtbcentinsp = ijtbcentinsp;
		this.ijtbdrivers = ijtbdrivers;
		this.ijprodxgrpparam = ijprodxgrpparam;
		this.ijparaminspec = ijparaminspec;
		this.idportacomdef = idportacomdef;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdcentinsp", column = @Column(name = "CDCENTINSP", nullable = false, length = 6)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "cdgrpparam", column = @Column(name = "CDGRPPARAM", nullable = false, length = 6)),
			@AttributeOverride(name = "idespecific", column = @Column(name = "IDESPECIFIC", nullable = false, length = 20)) })
	public IjdrvcntexecprtdefId getId() {
		return this.id;
	}

	public void setId(IjdrvcntexecprtdefId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCENTINSP", nullable = false, insertable = false, updatable = false)
	public Ijtbcentinsp getIjtbcentinsp() {
		return this.ijtbcentinsp;
	}

	public void setIjtbcentinsp(Ijtbcentinsp ijtbcentinsp) {
		this.ijtbcentinsp = ijtbcentinsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDRIVER", nullable = false)
	public Ijtbdrivers getIjtbdrivers() {
		return this.ijtbdrivers;
	}

	public void setIjtbdrivers(Ijtbdrivers ijtbdrivers) {
		this.ijtbdrivers = ijtbdrivers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDGRPPARAM", referencedColumnName = "CDGRPPARAM", nullable = false, insertable = false, updatable = false) })
	public Ijprodxgrpparam getIjprodxgrpparam() {
		return this.ijprodxgrpparam;
	}

	public void setIjprodxgrpparam(Ijprodxgrpparam ijprodxgrpparam) {
		this.ijprodxgrpparam = ijprodxgrpparam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDESPECIFIC", nullable = false, insertable = false, updatable = false)
	public Ijparaminspec getIjparaminspec() {
		return this.ijparaminspec;
	}

	public void setIjparaminspec(Ijparaminspec ijparaminspec) {
		this.ijparaminspec = ijparaminspec;
	}

	@Column(name = "IDPORTACOMDEF", nullable = false, length = 20)
	public String getIdportacomdef() {
		return this.idportacomdef;
	}

	public void setIdportacomdef(String idportacomdef) {
		this.idportacomdef = idportacomdef;
	}

}
