package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjdrivercentparamId generated by hbm2java
 */
@Embeddable
public class IjdrivercentparamId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8672307689786776841L;
	private double iddrivercentral;
	private BigDecimal ordemparametro;

	public IjdrivercentparamId() {
	}

	public IjdrivercentparamId(double iddrivercentral, BigDecimal ordemparametro) {
		this.iddrivercentral = iddrivercentral;
		this.ordemparametro = ordemparametro;
	}

	@Column(name = "IDDRIVERCENTRAL", nullable = false, precision = 126, scale = 0)
	public double getIddrivercentral() {
		return this.iddrivercentral;
	}

	public void setIddrivercentral(double iddrivercentral) {
		this.iddrivercentral = iddrivercentral;
	}

	@Column(name = "ORDEMPARAMETRO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOrdemparametro() {
		return this.ordemparametro;
	}

	public void setOrdemparametro(BigDecimal ordemparametro) {
		this.ordemparametro = ordemparametro;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjdrivercentparamId))
			return false;
		IjdrivercentparamId castOther = (IjdrivercentparamId) other;

		return (this.getIddrivercentral() == castOther.getIddrivercentral())
				&& ((this.getOrdemparametro() == castOther.getOrdemparametro()) || (this
						.getOrdemparametro() != null
						&& castOther.getOrdemparametro() != null && this
						.getOrdemparametro().equals(
								castOther.getOrdemparametro())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIddrivercentral();
		result = 37
				* result
				+ (getOrdemparametro() == null ? 0 : this.getOrdemparametro()
						.hashCode());
		return result;
	}

}
