package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijdriverparam generated by hbm2java
 */
@Entity
@Table(name = "IJDRIVERPARAM")
public class Ijdriverparam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -296893401452238593L;
	private IjdriverparamId id;
	private Ijtbdrivers ijtbdrivers;
	private String dsparametro;
	private String parametro;

	public Ijdriverparam() {
	}

	public Ijdriverparam(IjdriverparamId id, Ijtbdrivers ijtbdrivers,
			String dsparametro, String parametro) {
		this.id = id;
		this.ijtbdrivers = ijtbdrivers;
		this.dsparametro = dsparametro;
		this.parametro = parametro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "iddriver", column = @Column(name = "IDDRIVER", nullable = false, length = 20)),
			@AttributeOverride(name = "ordemparametro", column = @Column(name = "ORDEMPARAMETRO", nullable = false, precision = 22, scale = 0)) })
	public IjdriverparamId getId() {
		return this.id;
	}

	public void setId(IjdriverparamId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDRIVER", nullable = false, insertable = false, updatable = false)
	public Ijtbdrivers getIjtbdrivers() {
		return this.ijtbdrivers;
	}

	public void setIjtbdrivers(Ijtbdrivers ijtbdrivers) {
		this.ijtbdrivers = ijtbdrivers;
	}

	@Column(name = "DSPARAMETRO", nullable = false, length = 60)
	public String getDsparametro() {
		return this.dsparametro;
	}

	public void setDsparametro(String dsparametro) {
		this.dsparametro = dsparametro;
	}

	@Column(name = "PARAMETRO", nullable = false)
	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

}
