package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijdrivercentprtdef generated by hbm2java
 */
@Entity
@Table(name = "IJDRIVERCENTPRTDEF")
public class Ijdrivercentprtdef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8884847878542831984L;
	private IjdrivercentprtdefId id;
	private Ijtbcentinsp ijtbcentinsp;
	private Ijtbdrivers ijtbdrivers;
	private String idportacomdef;

	public Ijdrivercentprtdef() {
	}

	public Ijdrivercentprtdef(IjdrivercentprtdefId id,
			Ijtbcentinsp ijtbcentinsp, Ijtbdrivers ijtbdrivers,
			String idportacomdef) {
		this.id = id;
		this.ijtbcentinsp = ijtbcentinsp;
		this.ijtbdrivers = ijtbdrivers;
		this.idportacomdef = idportacomdef;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdcentinsp", column = @Column(name = "CDCENTINSP", nullable = false, length = 6)),
			@AttributeOverride(name = "iddriver", column = @Column(name = "IDDRIVER", nullable = false, length = 20)) })
	public IjdrivercentprtdefId getId() {
		return this.id;
	}

	public void setId(IjdrivercentprtdefId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCENTINSP", nullable = false, insertable = false, updatable = false)
	public Ijtbcentinsp getIjtbcentinsp() {
		return this.ijtbcentinsp;
	}

	public void setIjtbcentinsp(Ijtbcentinsp ijtbcentinsp) {
		this.ijtbcentinsp = ijtbcentinsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDRIVER", nullable = false, insertable = false, updatable = false)
	public Ijtbdrivers getIjtbdrivers() {
		return this.ijtbdrivers;
	}

	public void setIjtbdrivers(Ijtbdrivers ijtbdrivers) {
		this.ijtbdrivers = ijtbdrivers;
	}

	@Column(name = "IDPORTACOMDEF", nullable = false, length = 20)
	public String getIdportacomdef() {
		return this.idportacomdef;
	}

	public void setIdportacomdef(String idportacomdef) {
		this.idportacomdef = idportacomdef;
	}

}
