package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijdunumeracao generated by hbm2java
 */
@Entity
@Table(name = "IJDUNUMERACAO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NROP", "CDPRODUTO" }))
public class Ijdunumeracao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1359518426636963289L;
	private double du;
	private BigDecimal revisao;
	private String nrop;
	private String cdproduto;

	public Ijdunumeracao() {
	}

	public Ijdunumeracao(double du, String nrop, String cdproduto) {
		this.du = du;
		this.nrop = nrop;
		this.cdproduto = cdproduto;
	}

	public Ijdunumeracao(double du, BigDecimal revisao, String nrop,
			String cdproduto) {
		this.du = du;
		this.revisao = revisao;
		this.nrop = nrop;
		this.cdproduto = cdproduto;
	}

	@Id
	@Column(name = "DU", unique = true, nullable = false, precision = 126, scale = 0)
	public double getDu() {
		return this.du;
	}

	public void setDu(double du) {
		this.du = du;
	}

	@Column(name = "REVISAO", precision = 22, scale = 0)
	public BigDecimal getRevisao() {
		return this.revisao;
	}

	public void setRevisao(BigDecimal revisao) {
		this.revisao = revisao;
	}

	@Column(name = "NROP", nullable = false, length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

}
