package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijduimpxplantas generated by hbm2java
 */
@Entity
@Table(name = "IJDUIMPXPLANTAS")
public class Ijduimpxplantas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6158987234010079614L;
	private IjduimpxplantasId id;
	private Ijduimpressaocgq ijduimpressaocgq;

	public Ijduimpxplantas() {
	}

	public Ijduimpxplantas(IjduimpxplantasId id,
			Ijduimpressaocgq ijduimpressaocgq) {
		this.id = id;
		this.ijduimpressaocgq = ijduimpressaocgq;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idregistro", column = @Column(name = "IDREGISTRO", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "planta", column = @Column(name = "PLANTA", nullable = false, length = 50)) })
	public IjduimpxplantasId getId() {
		return this.id;
	}

	public void setId(IjduimpxplantasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGISTRO", nullable = false, insertable = false, updatable = false)
	public Ijduimpressaocgq getIjduimpressaocgq() {
		return this.ijduimpressaocgq;
	}

	public void setIjduimpressaocgq(Ijduimpressaocgq ijduimpressaocgq) {
		this.ijduimpressaocgq = ijduimpressaocgq;
	}

}
