package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijespecinspromedia generated by hbm2java
 */
@Entity
@Table(name = "IJESPECINSPROMEDIA")
public class Ijespecinspromedia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3670957371696631721L;
	private IjespecinspromediaId id;
	private Ijespecinsppro ijespecinsppro;
	private Ijparaminspec ijparaminspec;

	public Ijespecinspromedia() {
	}

	public Ijespecinspromedia(IjespecinspromediaId id,
			Ijespecinsppro ijespecinsppro, Ijparaminspec ijparaminspec) {
		this.id = id;
		this.ijespecinsppro = ijespecinsppro;
		this.ijparaminspec = ijparaminspec;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "idespecific", column = @Column(name = "IDESPECIFIC", nullable = false, length = 20)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrivalespecific", column = @Column(name = "DTHRIVALESPECIFIC", nullable = false, length = 7)),
			@AttributeOverride(name = "idespecificmedia", column = @Column(name = "IDESPECIFICMEDIA", nullable = false, length = 20)) })
	public IjespecinspromediaId getId() {
		return this.id;
	}

	public void setId(IjespecinspromediaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "IDESPECIFIC", referencedColumnName = "IDESPECIFIC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "DTHRIVALESPECIFIC", referencedColumnName = "DTHRIVALESPECIFIC", nullable = false, insertable = false, updatable = false) })
	public Ijespecinsppro getIjespecinsppro() {
		return this.ijespecinsppro;
	}

	public void setIjespecinsppro(Ijespecinsppro ijespecinsppro) {
		this.ijespecinsppro = ijespecinsppro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDESPECIFICMEDIA", nullable = false, insertable = false, updatable = false)
	public Ijparaminspec getIjparaminspec() {
		return this.ijparaminspec;
	}

	public void setIjparaminspec(Ijparaminspec ijparaminspec) {
		this.ijparaminspec = ijparaminspec;
	}

}
