package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijestruprod generated by hbm2java
 */
@Entity
@Table(name = "IJESTRUPROD")
public class Ijestruprod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4350138686198108592L;
	private IjestruprodId id;
	private Ijtbpro ijtbproByCdproduto;
	private Ijtbpro ijtbproByCdprodutoseq;
	private double qtitens;

	public Ijestruprod() {
	}

	public Ijestruprod(IjestruprodId id, Ijtbpro ijtbproByCdproduto,
			Ijtbpro ijtbproByCdprodutoseq, double qtitens) {
		this.id = id;
		this.ijtbproByCdproduto = ijtbproByCdproduto;
		this.ijtbproByCdprodutoseq = ijtbproByCdprodutoseq;
		this.qtitens = qtitens;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "sequencia", column = @Column(name = "SEQUENCIA", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdprodutoseq", column = @Column(name = "CDPRODUTOSEQ", nullable = false, length = 20)) })
	public IjestruprodId getId() {
		return this.id;
	}

	public void setId(IjestruprodId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbproByCdproduto() {
		return this.ijtbproByCdproduto;
	}

	public void setIjtbproByCdproduto(Ijtbpro ijtbproByCdproduto) {
		this.ijtbproByCdproduto = ijtbproByCdproduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTOSEQ", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbproByCdprodutoseq() {
		return this.ijtbproByCdprodutoseq;
	}

	public void setIjtbproByCdprodutoseq(Ijtbpro ijtbproByCdprodutoseq) {
		this.ijtbproByCdprodutoseq = ijtbproByCdprodutoseq;
	}

	@Column(name = "QTITENS", nullable = false, precision = 126, scale = 0)
	public double getQtitens() {
		return this.qtitens;
	}

	public void setQtitens(double qtitens) {
		this.qtitens = qtitens;
	}

}
