package idw.model.pojos.injet;

// Generated 05/08/2013 13:30:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijespecinspproxinj generated by hbm2java
 */
@Entity
@Table(name = "IJESPECINSPPROXINJ")
public class Ijespecinspproxinj implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3317802456333783115L;
	private IjespecinspproxinjId id;
	private Ijespecinsppro ijespecinsppro;
	private Ijtbinj ijtbinj;

	public Ijespecinspproxinj() {
	}

	public Ijespecinspproxinj(IjespecinspproxinjId id,
			Ijespecinsppro ijespecinsppro, Ijtbinj ijtbinj) {
		this.id = id;
		this.ijespecinsppro = ijespecinsppro;
		this.ijtbinj = ijtbinj;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "idespecific", column = @Column(name = "IDESPECIFIC", nullable = false, length = 20)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrivalespecific", column = @Column(name = "DTHRIVALESPECIFIC", nullable = false, length = 7)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public IjespecinspproxinjId getId() {
		return this.id;
	}

	public void setId(IjespecinspproxinjId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "IDESPECIFIC", referencedColumnName = "IDESPECIFIC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "DTHRIVALESPECIFIC", referencedColumnName = "DTHRIVALESPECIFIC", nullable = false, insertable = false, updatable = false) })
	public Ijespecinsppro getIjespecinsppro() {
		return this.ijespecinsppro;
	}

	public void setIjespecinsppro(Ijespecinsppro ijespecinsppro) {
		this.ijespecinsppro = ijespecinsppro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

}
