package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijespecinsproatrib generated by hbm2java
 */
@Entity
@Table(name = "IJESPECINSPROATRIB")
public class Ijespecinsproatrib implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7315578069753785719L;
	private IjespecinsproatribId id;
	private Ijtbmetodocgq ijtbmetodocgq;
	private Ijtbpro ijtbpro;
	private Date dthrfvalespecific;
	private char especificativa;
	private BigDecimal selecnocgq;
	private BigDecimal tamamostra;
	private char coletaamstrporcav;
	private double qtdreprsevero;
	private double qtdreprnormal;
	private double qtdactvsevero;
	private double qtdactvnormal;
	private String obsaprovado;
	private String obsaprvrestricao;
	private String obsreprovado;
	private BigDecimal tpavaliacao;
	private BigDecimal habilitaact;

	public Ijespecinsproatrib() {
	}

	public Ijespecinsproatrib(IjespecinsproatribId id, Ijtbpro ijtbpro,
			char especificativa, BigDecimal selecnocgq, BigDecimal tamamostra,
			char coletaamstrporcav, double qtdreprsevero, double qtdreprnormal,
			double qtdactvsevero, double qtdactvnormal, BigDecimal tpavaliacao,
			BigDecimal habilitaact) {
		this.id = id;
		this.ijtbpro = ijtbpro;
		this.especificativa = especificativa;
		this.selecnocgq = selecnocgq;
		this.tamamostra = tamamostra;
		this.coletaamstrporcav = coletaamstrporcav;
		this.qtdreprsevero = qtdreprsevero;
		this.qtdreprnormal = qtdreprnormal;
		this.qtdactvsevero = qtdactvsevero;
		this.qtdactvnormal = qtdactvnormal;
		this.tpavaliacao = tpavaliacao;
		this.habilitaact = habilitaact;
	}

	public Ijespecinsproatrib(IjespecinsproatribId id,
			Ijtbmetodocgq ijtbmetodocgq, Ijtbpro ijtbpro,
			Date dthrfvalespecific, char especificativa,
			BigDecimal selecnocgq, BigDecimal tamamostra,
			char coletaamstrporcav, double qtdreprsevero, double qtdreprnormal,
			double qtdactvsevero, double qtdactvnormal, String obsaprovado,
			String obsaprvrestricao, String obsreprovado,
			BigDecimal tpavaliacao, BigDecimal habilitaact) {
		this.id = id;
		this.ijtbmetodocgq = ijtbmetodocgq;
		this.ijtbpro = ijtbpro;
		this.dthrfvalespecific = dthrfvalespecific;
		this.especificativa = especificativa;
		this.selecnocgq = selecnocgq;
		this.tamamostra = tamamostra;
		this.coletaamstrporcav = coletaamstrporcav;
		this.qtdreprsevero = qtdreprsevero;
		this.qtdreprnormal = qtdreprnormal;
		this.qtdactvsevero = qtdactvsevero;
		this.qtdactvnormal = qtdactvnormal;
		this.obsaprovado = obsaprovado;
		this.obsaprvrestricao = obsaprvrestricao;
		this.obsreprovado = obsreprovado;
		this.tpavaliacao = tpavaliacao;
		this.habilitaact = habilitaact;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "idespecific", column = @Column(name = "IDESPECIFIC", nullable = false, length = 20)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrivalespecific", column = @Column(name = "DTHRIVALESPECIFIC", nullable = false)) })
	public IjespecinsproatribId getId() {
		return this.id;
	}

	public void setId(IjespecinsproatribId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDMETODO")
	public Ijtbmetodocgq getIjtbmetodocgq() {
		return this.ijtbmetodocgq;
	}

	public void setIjtbmetodocgq(Ijtbmetodocgq ijtbmetodocgq) {
		this.ijtbmetodocgq = ijtbmetodocgq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "DTHRFVALESPECIFIC")
	public Date getDthrfvalespecific() {
		return this.dthrfvalespecific;
	}

	public void setDthrfvalespecific(Date dthrfvalespecific) {
		this.dthrfvalespecific = dthrfvalespecific;
	}

	@Column(name = "ESPECIFICATIVA", nullable = false, length = 1)
	public char getEspecificativa() {
		return this.especificativa;
	}

	public void setEspecificativa(char especificativa) {
		this.especificativa = especificativa;
	}

	@Column(name = "SELECNOCGQ", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSelecnocgq() {
		return this.selecnocgq;
	}

	public void setSelecnocgq(BigDecimal selecnocgq) {
		this.selecnocgq = selecnocgq;
	}

	@Column(name = "TAMAMOSTRA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTamamostra() {
		return this.tamamostra;
	}

	public void setTamamostra(BigDecimal tamamostra) {
		this.tamamostra = tamamostra;
	}

	@Column(name = "COLETAAMSTRPORCAV", nullable = false, length = 1)
	public char getColetaamstrporcav() {
		return this.coletaamstrporcav;
	}

	public void setColetaamstrporcav(char coletaamstrporcav) {
		this.coletaamstrporcav = coletaamstrporcav;
	}

	@Column(name = "QTDREPRSEVERO", nullable = false, precision = 126, scale = 0)
	public double getQtdreprsevero() {
		return this.qtdreprsevero;
	}

	public void setQtdreprsevero(double qtdreprsevero) {
		this.qtdreprsevero = qtdreprsevero;
	}

	@Column(name = "QTDREPRNORMAL", nullable = false, precision = 126, scale = 0)
	public double getQtdreprnormal() {
		return this.qtdreprnormal;
	}

	public void setQtdreprnormal(double qtdreprnormal) {
		this.qtdreprnormal = qtdreprnormal;
	}

	@Column(name = "QTDACTVSEVERO", nullable = false, precision = 126, scale = 0)
	public double getQtdactvsevero() {
		return this.qtdactvsevero;
	}

	public void setQtdactvsevero(double qtdactvsevero) {
		this.qtdactvsevero = qtdactvsevero;
	}

	@Column(name = "QTDACTVNORMAL", nullable = false, precision = 126, scale = 0)
	public double getQtdactvnormal() {
		return this.qtdactvnormal;
	}

	public void setQtdactvnormal(double qtdactvnormal) {
		this.qtdactvnormal = qtdactvnormal;
	}

	@Column(name = "OBSAPROVADO", length = 50)
	public String getObsaprovado() {
		return this.obsaprovado;
	}

	public void setObsaprovado(String obsaprovado) {
		this.obsaprovado = obsaprovado;
	}

	@Column(name = "OBSAPRVRESTRICAO", length = 50)
	public String getObsaprvrestricao() {
		return this.obsaprvrestricao;
	}

	public void setObsaprvrestricao(String obsaprvrestricao) {
		this.obsaprvrestricao = obsaprvrestricao;
	}

	@Column(name = "OBSREPROVADO", length = 50)
	public String getObsreprovado() {
		return this.obsreprovado;
	}

	public void setObsreprovado(String obsreprovado) {
		this.obsreprovado = obsreprovado;
	}

	@Column(name = "TPAVALIACAO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpavaliacao() {
		return this.tpavaliacao;
	}

	public void setTpavaliacao(BigDecimal tpavaliacao) {
		this.tpavaliacao = tpavaliacao;
	}

	@Column(name = "HABILITAACT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getHabilitaact() {
		return this.habilitaact;
	}

	public void setHabilitaact(BigDecimal habilitaact) {
		this.habilitaact = habilitaact;
	}

}
