package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijetqproduto generated by hbm2java
 */
@Entity
@Table(name = "IJETQPRODUTO")
public class Ijetqproduto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4632263563569796117L;
	private String cdbarrasproduto;
	private Ijop ijop;
	private Ijtbpro ijtbpro;
	private double nrseq;
	private double qtitensemb;

	public Ijetqproduto() {
	}

	public Ijetqproduto(String cdbarrasproduto, Ijop ijop, Ijtbpro ijtbpro,
			double nrseq, double qtitensemb) {
		this.cdbarrasproduto = cdbarrasproduto;
		this.ijop = ijop;
		this.ijtbpro = ijtbpro;
		this.nrseq = nrseq;
		this.qtitensemb = qtitensemb;
	}

	@Id
	@Column(name = "CDBARRASPRODUTO", unique = true, nullable = false, length = 50)
	public String getCdbarrasproduto() {
		return this.cdbarrasproduto;
	}

	public void setCdbarrasproduto(String cdbarrasproduto) {
		this.cdbarrasproduto = cdbarrasproduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "NRSEQ", nullable = false, precision = 126, scale = 0)
	public double getNrseq() {
		return this.nrseq;
	}

	public void setNrseq(double nrseq) {
		this.nrseq = nrseq;
	}

	@Column(name = "QTITENSEMB", nullable = false, precision = 126, scale = 0)
	public double getQtitensemb() {
		return this.qtitensemb;
	}

	public void setQtitensemb(double qtitensemb) {
		this.qtitensemb = qtitensemb;
	}

}
