package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijetqfaixa generated by hbm2java
 */
@Entity
@Table(name = "IJETQFAIXA")
public class Ijetqfaixa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8521400871466908389L;
	private IjetqfaixaId id;
	private Ijop ijop;
	private Ijtbpro ijtbpro;
	private double nrseqinicial;
	private double nrseqfinal;
	private Double nrultseqlida;

	public Ijetqfaixa() {
	}

	public Ijetqfaixa(IjetqfaixaId id, Ijop ijop, Ijtbpro ijtbpro,
			double nrseqinicial, double nrseqfinal) {
		this.id = id;
		this.ijop = ijop;
		this.ijtbpro = ijtbpro;
		this.nrseqinicial = nrseqinicial;
		this.nrseqfinal = nrseqfinal;
	}

	public Ijetqfaixa(IjetqfaixaId id, Ijop ijop, Ijtbpro ijtbpro,
			double nrseqinicial, double nrseqfinal, Double nrultseqlida) {
		this.id = id;
		this.ijop = ijop;
		this.ijtbpro = ijtbpro;
		this.nrseqinicial = nrseqinicial;
		this.nrseqfinal = nrseqfinal;
		this.nrultseqlida = nrultseqlida;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)) })
	public IjetqfaixaId getId() {
		return this.id;
	}

	public void setId(IjetqfaixaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "NRSEQINICIAL", nullable = false, precision = 126, scale = 0)
	public double getNrseqinicial() {
		return this.nrseqinicial;
	}

	public void setNrseqinicial(double nrseqinicial) {
		this.nrseqinicial = nrseqinicial;
	}

	@Column(name = "NRSEQFINAL", nullable = false, precision = 126, scale = 0)
	public double getNrseqfinal() {
		return this.nrseqfinal;
	}

	public void setNrseqfinal(double nrseqfinal) {
		this.nrseqfinal = nrseqfinal;
	}

	@Column(name = "NRULTSEQLIDA", precision = 126, scale = 0)
	public Double getNrultseqlida() {
		return this.nrultseqlida;
	}

	public void setNrultseqlida(Double nrultseqlida) {
		this.nrultseqlida = nrultseqlida;
	}

}
