package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijfamiliaxmaq generated by hbm2java
 */
@Entity
@Table(name = "IJFAMILIAXMAQ")
public class Ijfamiliaxmaq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8847550698968880833L;
	private IjfamiliaxmaqId id;
	private Ijtbinj ijtbinj;
	private Ijtbfamiliamaq ijtbfamiliamaq;

	public Ijfamiliaxmaq() {
	}

	public Ijfamiliaxmaq(IjfamiliaxmaqId id, Ijtbinj ijtbinj,
			Ijtbfamiliamaq ijtbfamiliamaq) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijtbfamiliamaq = ijtbfamiliamaq;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdfamilia", column = @Column(name = "CDFAMILIA", nullable = false, length = 8)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public IjfamiliaxmaqId getId() {
		return this.id;
	}

	public void setId(IjfamiliaxmaqId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDFAMILIA", nullable = false, insertable = false, updatable = false)
	public Ijtbfamiliamaq getIjtbfamiliamaq() {
		return this.ijtbfamiliamaq;
	}

	public void setIjtbfamiliamaq(Ijtbfamiliamaq ijtbfamiliamaq) {
		this.ijtbfamiliamaq = ijtbfamiliamaq;
	}

}
