package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijfiltrocont generated by hbm2java
 */
@Entity
@Table(name = "IJFILTROCONT")
public class Ijfiltrocont implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6252769218515390677L;
	private IjfiltrocontId id;
	private Ijtbtipofiltro ijtbtipofiltro;
	private Ijtbcont ijtbcont;
	private String indseq;
	private String indnumopcao;
	private String indobrigatorio;
	private String indtipoicone;
	private Set<Ijgrpfiltro> ijgrpfiltrosForSysC0013021 = new HashSet<Ijgrpfiltro>(
			0);
	private Set<Ijgrpfiltro> ijgrpfiltrosForSysC0013022 = new HashSet<Ijgrpfiltro>(
			0);

	public Ijfiltrocont() {
	}

	public Ijfiltrocont(IjfiltrocontId id, Ijtbtipofiltro ijtbtipofiltro,
			Ijtbcont ijtbcont, String indseq, String indnumopcao,
			String indobrigatorio, String indtipoicone) {
		this.id = id;
		this.ijtbtipofiltro = ijtbtipofiltro;
		this.ijtbcont = ijtbcont;
		this.indseq = indseq;
		this.indnumopcao = indnumopcao;
		this.indobrigatorio = indobrigatorio;
		this.indtipoicone = indtipoicone;
	}

	public Ijfiltrocont(IjfiltrocontId id, Ijtbtipofiltro ijtbtipofiltro,
			Ijtbcont ijtbcont, String indseq, String indnumopcao,
			String indobrigatorio, String indtipoicone,
			Set<Ijgrpfiltro> ijgrpfiltrosForSysC0013021,
			Set<Ijgrpfiltro> ijgrpfiltrosForSysC0013022) {
		this.id = id;
		this.ijtbtipofiltro = ijtbtipofiltro;
		this.ijtbcont = ijtbcont;
		this.indseq = indseq;
		this.indnumopcao = indnumopcao;
		this.indobrigatorio = indobrigatorio;
		this.indtipoicone = indtipoicone;
		this.ijgrpfiltrosForSysC0013021 = ijgrpfiltrosForSysC0013021;
		this.ijgrpfiltrosForSysC0013022 = ijgrpfiltrosForSysC0013022;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdcont", column = @Column(name = "CDCONT", nullable = false, length = 6)),
			@AttributeOverride(name = "cdtipofiltro", column = @Column(name = "CDTIPOFILTRO", nullable = false, length = 6)) })
	public IjfiltrocontId getId() {
		return this.id;
	}

	public void setId(IjfiltrocontId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTIPOFILTRO", nullable = false, insertable = false, updatable = false)
	public Ijtbtipofiltro getIjtbtipofiltro() {
		return this.ijtbtipofiltro;
	}

	public void setIjtbtipofiltro(Ijtbtipofiltro ijtbtipofiltro) {
		this.ijtbtipofiltro = ijtbtipofiltro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCONT", nullable = false, insertable = false, updatable = false)
	public Ijtbcont getIjtbcont() {
		return this.ijtbcont;
	}

	public void setIjtbcont(Ijtbcont ijtbcont) {
		this.ijtbcont = ijtbcont;
	}

	@Column(name = "INDSEQ", nullable = false, length = 4)
	public String getIndseq() {
		return this.indseq;
	}

	public void setIndseq(String indseq) {
		this.indseq = indseq;
	}

	@Column(name = "INDNUMOPCAO", nullable = false, length = 1)
	public String getIndnumopcao() {
		return this.indnumopcao;
	}

	public void setIndnumopcao(String indnumopcao) {
		this.indnumopcao = indnumopcao;
	}

	@Column(name = "INDOBRIGATORIO", nullable = false, length = 1)
	public String getIndobrigatorio() {
		return this.indobrigatorio;
	}

	public void setIndobrigatorio(String indobrigatorio) {
		this.indobrigatorio = indobrigatorio;
	}

	@Column(name = "INDTIPOICONE", nullable = false, length = 1)
	public String getIndtipoicone() {
		return this.indtipoicone;
	}

	public void setIndtipoicone(String indtipoicone) {
		this.indtipoicone = indtipoicone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijfiltrocontBySysC0013021")
	public Set<Ijgrpfiltro> getIjgrpfiltrosForSysC0013021() {
		return this.ijgrpfiltrosForSysC0013021;
	}

	public void setIjgrpfiltrosForSysC0013021(
			Set<Ijgrpfiltro> ijgrpfiltrosForSysC0013021) {
		this.ijgrpfiltrosForSysC0013021 = ijgrpfiltrosForSysC0013021;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijfiltrocontBySysC0013022")
	public Set<Ijgrpfiltro> getIjgrpfiltrosForSysC0013022() {
		return this.ijgrpfiltrosForSysC0013022;
	}

	public void setIjgrpfiltrosForSysC0013022(
			Set<Ijgrpfiltro> ijgrpfiltrosForSysC0013022) {
		this.ijgrpfiltrosForSysC0013022 = ijgrpfiltrosForSysC0013022;
	}

}
