package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijfictecautorizusu generated by hbm2java
 */
@Entity
@Table(name = "IJFICTECAUTORIZUSU")
public class Ijfictecautorizusu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5735713632764893074L;
	private IjfictecautorizusuId id;
	private Ijfictecautorizmod ijfictecautorizmod;
	private Ijtbusu ijtbusuByCdususubstituto;
	private Ijtbusu ijtbusuByCdusuarioaut;
	private char stautoriz;
	private Date dthrautoriz;

	public Ijfictecautorizusu() {
	}

	public Ijfictecautorizusu(IjfictecautorizusuId id,
			Ijfictecautorizmod ijfictecautorizmod,
			Ijtbusu ijtbusuByCdusuarioaut, char stautoriz, Date dthrautoriz) {
		this.id = id;
		this.ijfictecautorizmod = ijfictecautorizmod;
		this.ijtbusuByCdusuarioaut = ijtbusuByCdusuarioaut;
		this.stautoriz = stautoriz;
		this.dthrautoriz = dthrautoriz;
	}

	public Ijfictecautorizusu(IjfictecautorizusuId id,
			Ijfictecautorizmod ijfictecautorizmod,
			Ijtbusu ijtbusuByCdususubstituto, Ijtbusu ijtbusuByCdusuarioaut,
			char stautoriz, Date dthrautoriz) {
		this.id = id;
		this.ijfictecautorizmod = ijfictecautorizmod;
		this.ijtbusuByCdususubstituto = ijtbusuByCdususubstituto;
		this.ijtbusuByCdusuarioaut = ijtbusuByCdusuarioaut;
		this.stautoriz = stautoriz;
		this.dthrautoriz = dthrautoriz;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrsolicmodificcic", column = @Column(name = "NRSOLICMODIFICCIC", nullable = false, length = 12)),
			@AttributeOverride(name = "cdusuarioaut", column = @Column(name = "CDUSUARIOAUT", nullable = false, length = 6)) })
	public IjfictecautorizusuId getId() {
		return this.id;
	}

	public void setId(IjfictecautorizusuId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NRSOLICMODIFICCIC", nullable = false, insertable = false, updatable = false)
	public Ijfictecautorizmod getIjfictecautorizmod() {
		return this.ijfictecautorizmod;
	}

	public void setIjfictecautorizmod(Ijfictecautorizmod ijfictecautorizmod) {
		this.ijfictecautorizmod = ijfictecautorizmod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUSUBSTITUTO")
	public Ijtbusu getIjtbusuByCdususubstituto() {
		return this.ijtbusuByCdususubstituto;
	}

	public void setIjtbusuByCdususubstituto(Ijtbusu ijtbusuByCdususubstituto) {
		this.ijtbusuByCdususubstituto = ijtbusuByCdususubstituto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIOAUT", nullable = false, insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuarioaut() {
		return this.ijtbusuByCdusuarioaut;
	}

	public void setIjtbusuByCdusuarioaut(Ijtbusu ijtbusuByCdusuarioaut) {
		this.ijtbusuByCdusuarioaut = ijtbusuByCdusuarioaut;
	}

	@Column(name = "STAUTORIZ", nullable = false, length = 1)
	public char getStautoriz() {
		return this.stautoriz;
	}

	public void setStautoriz(char stautoriz) {
		this.stautoriz = stautoriz;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRAUTORIZ", nullable = false, length = 7)
	public Date getDthrautoriz() {
		return this.dthrautoriz;
	}

	public void setDthrautoriz(Date dthrautoriz) {
		this.dthrautoriz = dthrautoriz;
	}

}
