package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijfiltrosoeegrp generated by hbm2java
 */
@Entity
@Table(name = "IJFILTROSOEEGRP")
public class Ijfiltrosoeegrp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1073304261197050663L;
	private IjfiltrosoeegrpId id;
	private Ijfiltrosoee ijfiltrosoee;

	public Ijfiltrosoeegrp() {
	}

	public Ijfiltrosoeegrp(IjfiltrosoeegrpId id, Ijfiltrosoee ijfiltrosoee) {
		this.id = id;
		this.ijfiltrosoee = ijfiltrosoee;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idfiltrooee", column = @Column(name = "IDFILTROOEE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tpmaqmolgrp", column = @Column(name = "TPMAQMOLGRP", nullable = false, length = 1)),
			@AttributeOverride(name = "cdmaqmolgrp", column = @Column(name = "CDMAQMOLGRP", nullable = false, length = 6)) })
	public IjfiltrosoeegrpId getId() {
		return this.id;
	}

	public void setId(IjfiltrosoeegrpId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDFILTROOEE", nullable = false, insertable = false, updatable = false)
	public Ijfiltrosoee getIjfiltrosoee() {
		return this.ijfiltrosoee;
	}

	public void setIjfiltrosoee(Ijfiltrosoee ijfiltrosoee) {
		this.ijfiltrosoee = ijfiltrosoee;
	}

}
