package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijfreqmanutprev generated by hbm2java
 */
@Entity
@Table(name = "IJFREQMANUTPREV")
public class Ijfreqmanutprev implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 416513580760714016L;
	private IjfreqmanutprevId id;
	private Ijmanut ijmanut;
	private BigDecimal tpfreqmanut;
	private double vlrfreq;
	private double qtdcicexec;
	private double qtdhstrab;
	private Date dthrultalemanprev;
	private BigDecimal podegeraralerta;
	private BigDecimal ativo;

	public Ijfreqmanutprev() {
	}

	public Ijfreqmanutprev(IjfreqmanutprevId id, BigDecimal tpfreqmanut,
			double vlrfreq, double qtdcicexec, double qtdhstrab,
			BigDecimal podegeraralerta, BigDecimal ativo) {
		this.id = id;
		this.tpfreqmanut = tpfreqmanut;
		this.vlrfreq = vlrfreq;
		this.qtdcicexec = qtdcicexec;
		this.qtdhstrab = qtdhstrab;
		this.podegeraralerta = podegeraralerta;
		this.ativo = ativo;
	}

	public Ijfreqmanutprev(IjfreqmanutprevId id, Ijmanut ijmanut,
			BigDecimal tpfreqmanut, double vlrfreq, double qtdcicexec,
			double qtdhstrab, Date dthrultalemanprev,
			BigDecimal podegeraralerta, BigDecimal ativo) {
		this.id = id;
		this.ijmanut = ijmanut;
		this.tpfreqmanut = tpfreqmanut;
		this.vlrfreq = vlrfreq;
		this.qtdcicexec = qtdcicexec;
		this.qtdhstrab = qtdhstrab;
		this.dthrultalemanprev = dthrultalemanprev;
		this.podegeraralerta = podegeraralerta;
		this.ativo = ativo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idrecurso", column = @Column(name = "IDRECURSO", nullable = false, length = 6)),
			@AttributeOverride(name = "tprecurso", column = @Column(name = "TPRECURSO", nullable = false, length = 2)),
			@AttributeOverride(name = "cdchklst", column = @Column(name = "CDCHKLST", nullable = false, length = 6)) })
	public IjfreqmanutprevId getId() {
		return this.id;
	}

	public void setId(IjfreqmanutprevId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROS")
	public Ijmanut getIjmanut() {
		return this.ijmanut;
	}

	public void setIjmanut(Ijmanut ijmanut) {
		this.ijmanut = ijmanut;
	}

	@Column(name = "TPFREQMANUT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpfreqmanut() {
		return this.tpfreqmanut;
	}

	public void setTpfreqmanut(BigDecimal tpfreqmanut) {
		this.tpfreqmanut = tpfreqmanut;
	}

	@Column(name = "VLRFREQ", nullable = false, precision = 126, scale = 0)
	public double getVlrfreq() {
		return this.vlrfreq;
	}

	public void setVlrfreq(double vlrfreq) {
		this.vlrfreq = vlrfreq;
	}

	@Column(name = "QTDCICEXEC", nullable = false, precision = 126, scale = 0)
	public double getQtdcicexec() {
		return this.qtdcicexec;
	}

	public void setQtdcicexec(double qtdcicexec) {
		this.qtdcicexec = qtdcicexec;
	}

	@Column(name = "QTDHSTRAB", nullable = false, precision = 126, scale = 0)
	public double getQtdhstrab() {
		return this.qtdhstrab;
	}

	public void setQtdhstrab(double qtdhstrab) {
		this.qtdhstrab = qtdhstrab;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRULTALEMANPREV", length = 7)
	public Date getDthrultalemanprev() {
		return this.dthrultalemanprev;
	}

	public void setDthrultalemanprev(Date dthrultalemanprev) {
		this.dthrultalemanprev = dthrultalemanprev;
	}

	@Column(name = "PODEGERARALERTA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPodegeraralerta() {
		return this.podegeraralerta;
	}

	public void setPodegeraralerta(BigDecimal podegeraralerta) {
		this.podegeraralerta = podegeraralerta;
	}

	@Column(name = "ATIVO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAtivo() {
		return this.ativo;
	}

	public void setAtivo(BigDecimal ativo) {
		this.ativo = ativo;
	}

}
