package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijgalobj generated by hbm2java
 */
@Entity
@Table(name = "IJGALOBJ")
public class Ijgalobj implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8405759004288572880L;
	private IjgalobjId id;
	private Ijtbpostos ijtbpostos;
	private Ijtbgal ijtbgal;
	private Ijtbinj ijtbinj;

	public Ijgalobj() {
	}

	public Ijgalobj(IjgalobjId id, Ijtbgal ijtbgal) {
		this.id = id;
		this.ijtbgal = ijtbgal;
	}

	public Ijgalobj(IjgalobjId id, Ijtbpostos ijtbpostos, Ijtbgal ijtbgal,
			Ijtbinj ijtbinj) {
		this.id = id;
		this.ijtbpostos = ijtbpostos;
		this.ijtbgal = ijtbgal;
		this.ijtbinj = ijtbinj;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdgalpao", column = @Column(name = "CDGALPAO", nullable = false, length = 6)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", length = 6)),
			@AttributeOverride(name = "cdposto", column = @Column(name = "CDPOSTO", length = 6)),
			@AttributeOverride(name = "coorelobjx", column = @Column(name = "COORELOBJX", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "coorelobjy", column = @Column(name = "COORELOBJY", nullable = false, precision = 126, scale = 0)) })
	public IjgalobjId getId() {
		return this.id;
	}

	public void setId(IjgalobjId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPOSTO", insertable = false, updatable = false)
	public Ijtbpostos getIjtbpostos() {
		return this.ijtbpostos;
	}

	public void setIjtbpostos(Ijtbpostos ijtbpostos) {
		this.ijtbpostos = ijtbpostos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGALPAO", nullable = false, insertable = false, updatable = false)
	public Ijtbgal getIjtbgal() {
		return this.ijtbgal;
	}

	public void setIjtbgal(Ijtbgal ijtbgal) {
		this.ijtbgal = ijtbgal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

}
