package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijgrpinjref generated by hbm2java
 */
@Entity
@Table(name = "IJGRPINJREF")
public class Ijgrpinjref implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8978134248640442185L;
	private IjgrpinjrefId id;
	private Ijtbinj ijtbinj;
	private Ijgrpref ijgrpref;

	public Ijgrpinjref() {
	}

	public Ijgrpinjref(IjgrpinjrefId id, Ijtbinj ijtbinj, Ijgrpref ijgrpref) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijgrpref = ijgrpref;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdgruporef", column = @Column(name = "CDGRUPOREF", nullable = false, length = 6)) })
	public IjgrpinjrefId getId() {
		return this.id;
	}

	public void setId(IjgrpinjrefId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRUPOREF", nullable = false, insertable = false, updatable = false)
	public Ijgrpref getIjgrpref() {
		return this.ijgrpref;
	}

	public void setIjgrpref(Ijgrpref ijgrpref) {
		this.ijgrpref = ijgrpref;
	}

}
