package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijgrprecxrec generated by hbm2java
 */
@Entity
@Table(name = "IJGRPRECXREC")
public class Ijgrprecxrec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2238607433869414475L;
	private IjgrprecxrecId id;
	private Ijtbgrprecursos ijtbgrprecursos;

	public Ijgrprecxrec() {
	}

	public Ijgrprecxrec(IjgrprecxrecId id, Ijtbgrprecursos ijtbgrprecursos) {
		this.id = id;
		this.ijtbgrprecursos = ijtbgrprecursos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdgrprecurso", column = @Column(name = "CDGRPRECURSO", nullable = false, length = 6)),
			@AttributeOverride(name = "idrecurso", column = @Column(name = "IDRECURSO", nullable = false, length = 6)),
			@AttributeOverride(name = "tprecurso", column = @Column(name = "TPRECURSO", nullable = false, length = 2)) })
	public IjgrprecxrecId getId() {
		return this.id;
	}

	public void setId(IjgrprecxrecId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRPRECURSO", nullable = false, insertable = false, updatable = false)
	public Ijtbgrprecursos getIjtbgrprecursos() {
		return this.ijtbgrprecursos;
	}

	public void setIjtbgrprecursos(Ijtbgrprecursos ijtbgrprecursos) {
		this.ijtbgrprecursos = ijtbgrprecursos;
	}

}
