package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijgrppro generated by hbm2java
 */
@Entity
@Table(name = "IJGRPPRO")
public class Ijgrppro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4635538306530733845L;
	private String cdgrppro;
	private String dsgrppro;
	private BigDecimal tmpsetup;
	private Set<Ijgrpdetpro> ijgrpdetpros = new HashSet<Ijgrpdetpro>(0);
	private Set<Ijgrpdetprocgq> ijgrpdetprocgqs = new HashSet<Ijgrpdetprocgq>(0);

	public Ijgrppro() {
	}

	public Ijgrppro(String cdgrppro, String dsgrppro, BigDecimal tmpsetup) {
		this.cdgrppro = cdgrppro;
		this.dsgrppro = dsgrppro;
		this.tmpsetup = tmpsetup;
	}

	public Ijgrppro(String cdgrppro, String dsgrppro, BigDecimal tmpsetup,
			Set<Ijgrpdetpro> ijgrpdetpros, Set<Ijgrpdetprocgq> ijgrpdetprocgqs) {
		this.cdgrppro = cdgrppro;
		this.dsgrppro = dsgrppro;
		this.tmpsetup = tmpsetup;
		this.ijgrpdetpros = ijgrpdetpros;
		this.ijgrpdetprocgqs = ijgrpdetprocgqs;
	}

	@Id
	@Column(name = "CDGRPPRO", unique = true, nullable = false, length = 6)
	public String getCdgrppro() {
		return this.cdgrppro;
	}

	public void setCdgrppro(String cdgrppro) {
		this.cdgrppro = cdgrppro;
	}

	@Column(name = "DSGRPPRO", nullable = false, length = 40)
	public String getDsgrppro() {
		return this.dsgrppro;
	}

	public void setDsgrppro(String dsgrppro) {
		this.dsgrppro = dsgrppro;
	}

	@Column(name = "TMPSETUP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmpsetup() {
		return this.tmpsetup;
	}

	public void setTmpsetup(BigDecimal tmpsetup) {
		this.tmpsetup = tmpsetup;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijgrppro")
	public Set<Ijgrpdetpro> getIjgrpdetpros() {
		return this.ijgrpdetpros;
	}

	public void setIjgrpdetpros(Set<Ijgrpdetpro> ijgrpdetpros) {
		this.ijgrpdetpros = ijgrpdetpros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijgrppro")
	public Set<Ijgrpdetprocgq> getIjgrpdetprocgqs() {
		return this.ijgrpdetprocgqs;
	}

	public void setIjgrpdetprocgqs(Set<Ijgrpdetprocgq> ijgrpdetprocgqs) {
		this.ijgrpdetprocgqs = ijgrpdetprocgqs;
	}

}
