package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijgrpparaminsp generated by hbm2java
 */
@Entity
@Table(name = "IJGRPPARAMINSP")
public class Ijgrpparaminsp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7961719288558919880L;
	private String cdgrpparam;
	private String dsgrpparam;
	private BigDecimal tpgrpparaminsp;
	private Set<Ijctrlresnegqld2> ijctrlresnegqld2s = new HashSet<Ijctrlresnegqld2>(0);
	private Set<Ijaledbqld> ijaledbqlds = new HashSet<Ijaledbqld>(0);
	private Set<Ijprodxgrpparam> ijprodxgrpparams = new HashSet<Ijprodxgrpparam>(0);
	private Set<Ijgrpparaminspxord> ijgrpparaminspxords = new HashSet<Ijgrpparaminspxord>(0);
	private Set<Ijinspecao> ijinspecaos = new HashSet<Ijinspecao>(0);

	public Ijgrpparaminsp() {
	}

	public Ijgrpparaminsp(String cdgrpparam, String dsgrpparam,
			BigDecimal tpgrpparaminsp) {
		this.cdgrpparam = cdgrpparam;
		this.dsgrpparam = dsgrpparam;
		this.tpgrpparaminsp = tpgrpparaminsp;
	}

	public Ijgrpparaminsp(String cdgrpparam, String dsgrpparam,
			BigDecimal tpgrpparaminsp,Set<Ijctrlresnegqld2> ijctrlresnegqld2s,
			Set<Ijaledbqld> ijaledbqlds,
			Set<Ijprodxgrpparam> ijprodxgrpparams,		
			Set<Ijgrpparaminspxord> ijgrpparaminspxords,
			Set<Ijinspecao> ijinspecaos) {
		this.cdgrpparam = cdgrpparam;
		this.dsgrpparam = dsgrpparam;
		this.tpgrpparaminsp = tpgrpparaminsp;
		this.ijctrlresnegqld2s = ijctrlresnegqld2s;
		this.ijaledbqlds = ijaledbqlds;
		this.ijprodxgrpparams = ijprodxgrpparams;
		this.ijgrpparaminspxords = ijgrpparaminspxords;
		this.ijinspecaos = ijinspecaos;
	}

	@Id
	@Column(name = "CDGRPPARAM", unique = true, nullable = false, length = 6)
	public String getCdgrpparam() {
		return this.cdgrpparam;
	}

	public void setCdgrpparam(String cdgrpparam) {
		this.cdgrpparam = cdgrpparam;
	}

	@Column(name = "DSGRPPARAM", nullable = false, length = 30)
	public String getDsgrpparam() {
		return this.dsgrpparam;
	}

	public void setDsgrpparam(String dsgrpparam) {
		this.dsgrpparam = dsgrpparam;
	}

	@Column(name = "TPGRPPARAMINSP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpgrpparaminsp() {
		return this.tpgrpparaminsp;
	}

	public void setTpgrpparaminsp(BigDecimal tpgrpparaminsp) {
		this.tpgrpparaminsp = tpgrpparaminsp;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijgrpparaminsp")
	public Set<Ijctrlresnegqld2> getIjctrlresnegqld2s() {
		return this.ijctrlresnegqld2s;
	}

	public void setIjctrlresnegqld2s(Set<Ijctrlresnegqld2> ijctrlresnegqld2s) {
		this.ijctrlresnegqld2s = ijctrlresnegqld2s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijgrpparaminsp")
	public Set<Ijaledbqld> getIjaledbqlds() {
		return this.ijaledbqlds;
	}

	public void setIjaledbqlds(Set<Ijaledbqld> ijaledbqlds) {
		this.ijaledbqlds = ijaledbqlds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijgrpparaminsp")
	public Set<Ijprodxgrpparam> getIjprodxgrpparams() {
		return this.ijprodxgrpparams;
	}

	public void setIjprodxgrpparams(Set<Ijprodxgrpparam> ijprodxgrpparams) {
		this.ijprodxgrpparams = ijprodxgrpparams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijgrpparaminsp")
	public Set<Ijgrpparaminspxord> getIjgrpparaminspxords() {
		return this.ijgrpparaminspxords;
	}

	public void setIjgrpparaminspxords(
			Set<Ijgrpparaminspxord> ijgrpparaminspxords) {
		this.ijgrpparaminspxords = ijgrpparaminspxords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijgrpparaminsp")
	public Set<Ijinspecao> getIjinspecaos() {
		return this.ijinspecaos;
	}

	public void setIjinspecaos(Set<Ijinspecao> ijinspecaos) {
		this.ijinspecaos = ijinspecaos;
	}

}
