package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijgrpusuemail generated by hbm2java
 */
@Entity
@Table(name = "IJGRPUSUEMAIL")
public class Ijgrpusuemail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2120271440115242114L;
	private IjgrpusuemailId id;
	private Ijtbusumail ijtbusumail;
	private Ijgrpemail ijgrpemail;

	public Ijgrpusuemail() {
	}

	public Ijgrpusuemail(IjgrpusuemailId id, Ijtbusumail ijtbusumail,
			Ijgrpemail ijgrpemail) {
		this.id = id;
		this.ijtbusumail = ijtbusumail;
		this.ijgrpemail = ijgrpemail;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdgrpemail", column = @Column(name = "CDGRPEMAIL", nullable = false, length = 6)),
			@AttributeOverride(name = "cdusumail", column = @Column(name = "CDUSUMAIL", nullable = false, length = 6)) })
	public IjgrpusuemailId getId() {
		return this.id;
	}

	public void setId(IjgrpusuemailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUMAIL", nullable = false, insertable = false, updatable = false)
	public Ijtbusumail getIjtbusumail() {
		return this.ijtbusumail;
	}

	public void setIjtbusumail(Ijtbusumail ijtbusumail) {
		this.ijtbusumail = ijtbusumail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRPEMAIL", nullable = false, insertable = false, updatable = false)
	public Ijgrpemail getIjgrpemail() {
		return this.ijgrpemail;
	}

	public void setIjgrpemail(Ijgrpemail ijgrpemail) {
		this.ijgrpemail = ijgrpemail;
	}

}
