package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijgrpdetinj generated by hbm2java
 */
@Entity
@Table(name = "IJGRPDETINJ")
public class Ijgrpdetinj implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7390191580326857930L;
	private IjgrpdetinjId id;
	private Ijgrpinj ijgrpinj;
	private Ijtbinj ijtbinj;

	public Ijgrpdetinj() {
	}

	public Ijgrpdetinj(IjgrpdetinjId id, Ijgrpinj ijgrpinj, Ijtbinj ijtbinj) {
		this.id = id;
		this.ijgrpinj = ijgrpinj;
		this.ijtbinj = ijtbinj;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdgrpinj", column = @Column(name = "CDGRPINJ", nullable = false, length = 6)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public IjgrpdetinjId getId() {
		return this.id;
	}

	public void setId(IjgrpdetinjId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRPINJ", nullable = false, insertable = false, updatable = false)
	public Ijgrpinj getIjgrpinj() {
		return this.ijgrpinj;
	}

	public void setIjgrpinj(Ijgrpinj ijgrpinj) {
		this.ijgrpinj = ijgrpinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

}
