package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjgrprecxrecId generated by hbm2java
 */
@Embeddable
public class IjgrprecxrecId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3366327057750049579L;
	private String cdgrprecurso;
	private String idrecurso;
	private String tprecurso;

	public IjgrprecxrecId() {
	}

	public IjgrprecxrecId(String cdgrprecurso, String idrecurso,
			String tprecurso) {
		this.cdgrprecurso = cdgrprecurso;
		this.idrecurso = idrecurso;
		this.tprecurso = tprecurso;
	}

	@Column(name = "CDGRPRECURSO", nullable = false, length = 6)
	public String getCdgrprecurso() {
		return this.cdgrprecurso;
	}

	public void setCdgrprecurso(String cdgrprecurso) {
		this.cdgrprecurso = cdgrprecurso;
	}

	@Column(name = "IDRECURSO", nullable = false, length = 6)
	public String getIdrecurso() {
		return this.idrecurso;
	}

	public void setIdrecurso(String idrecurso) {
		this.idrecurso = idrecurso;
	}

	@Column(name = "TPRECURSO", nullable = false, length = 2)
	public String getTprecurso() {
		return this.tprecurso;
	}

	public void setTprecurso(String tprecurso) {
		this.tprecurso = tprecurso;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjgrprecxrecId))
			return false;
		IjgrprecxrecId castOther = (IjgrprecxrecId) other;

		return ((this.getCdgrprecurso() == castOther.getCdgrprecurso()) || (this
				.getCdgrprecurso() != null
				&& castOther.getCdgrprecurso() != null && this
				.getCdgrprecurso().equals(castOther.getCdgrprecurso())))
				&& ((this.getIdrecurso() == castOther.getIdrecurso()) || (this
						.getIdrecurso() != null
						&& castOther.getIdrecurso() != null && this
						.getIdrecurso().equals(castOther.getIdrecurso())))
				&& ((this.getTprecurso() == castOther.getTprecurso()) || (this
						.getTprecurso() != null
						&& castOther.getTprecurso() != null && this
						.getTprecurso().equals(castOther.getTprecurso())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdgrprecurso() == null ? 0 : this.getCdgrprecurso()
						.hashCode());
		result = 37 * result
				+ (getIdrecurso() == null ? 0 : this.getIdrecurso().hashCode());
		result = 37 * result
				+ (getTprecurso() == null ? 0 : this.getTprecurso().hashCode());
		return result;
	}

}
