package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijgrpdetestproc generated by hbm2java
 */
@Entity
@Table(name = "IJGRPDETESTPROC")
public class Ijgrpdetestproc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3307465102339861019L;
	private IjgrpdetestprocId id;
	private Ijtbinj ijtbinj;
	private Ijtboperacoes ijtboperacoes;
	private Ijgrpestproc ijgrpestproc;

	public Ijgrpdetestproc() {
	}

	public Ijgrpdetestproc(IjgrpdetestprocId id, Ijtbinj ijtbinj,
			Ijgrpestproc ijgrpestproc) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijgrpestproc = ijgrpestproc;
	}

	public Ijgrpdetestproc(IjgrpdetestprocId id, Ijtbinj ijtbinj,
			Ijtboperacoes ijtboperacoes, Ijgrpestproc ijgrpestproc) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijtboperacoes = ijtboperacoes;
		this.ijgrpestproc = ijgrpestproc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdgrupoestproc", column = @Column(name = "CDGRUPOESTPROC", nullable = false, length = 6)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public IjgrpdetestprocId getId() {
		return this.id;
	}

	public void setId(IjgrpdetestprocId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPARADAPENDENTE")
	public Ijtboperacoes getIjtboperacoes() {
		return this.ijtboperacoes;
	}

	public void setIjtboperacoes(Ijtboperacoes ijtboperacoes) {
		this.ijtboperacoes = ijtboperacoes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRUPOESTPROC", nullable = false, insertable = false, updatable = false)
	public Ijgrpestproc getIjgrpestproc() {
		return this.ijgrpestproc;
	}

	public void setIjgrpestproc(Ijgrpestproc ijgrpestproc) {
		this.ijgrpestproc = ijgrpestproc;
	}

}
