package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijhortur generated by hbm2java
 */
@Entity
@Table(name = "IJHORTUR")
public class Ijhortur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 116955572954969329L;
	private IjhorturId id;
	private Ijtbtur ijtbtur;
	private Ijhorage ijhorage;
	private Ijtbdse ijtbdse;
	private Date hriturno;
	private Date hrfturno;

	public Ijhortur() {
	}

	public Ijhortur(IjhorturId id, Ijtbtur ijtbtur, Ijhorage ijhorage,
			Ijtbdse ijtbdse, Date hriturno, Date hrfturno) {
		this.id = id;
		this.ijtbtur = ijtbtur;
		this.ijhorage = ijhorage;
		this.ijtbdse = ijtbdse;
		this.hriturno = hriturno;
		this.hrfturno = hrfturno;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cddiasem", column = @Column(name = "CDDIASEM", nullable = false, length = 6)),
			@AttributeOverride(name = "cdturno", column = @Column(name = "CDTURNO", nullable = false, length = 6)),
			@AttributeOverride(name = "cdagenda", column = @Column(name = "CDAGENDA", nullable = false, length = 6)) })
	public IjhorturId getId() {
		return this.id;
	}

	public void setId(IjhorturId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTURNO", nullable = false, insertable = false, updatable = false)
	public Ijtbtur getIjtbtur() {
		return this.ijtbtur;
	}

	public void setIjtbtur(Ijtbtur ijtbtur) {
		this.ijtbtur = ijtbtur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDAGENDA", nullable = false, insertable = false, updatable = false)
	public Ijhorage getIjhorage() {
		return this.ijhorage;
	}

	public void setIjhorage(Ijhorage ijhorage) {
		this.ijhorage = ijhorage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDDIASEM", nullable = false, insertable = false, updatable = false)
	public Ijtbdse getIjtbdse() {
		return this.ijtbdse;
	}

	public void setIjtbdse(Ijtbdse ijtbdse) {
		this.ijtbdse = ijtbdse;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HRITURNO", nullable = false, length = 7)
	public Date getHriturno() {
		return this.hriturno;
	}

	public void setHriturno(Date hriturno) {
		this.hriturno = hriturno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HRFTURNO", nullable = false, length = 7)
	public Date getHrfturno() {
		return this.hrfturno;
	}

	public void setHrfturno(Date hrfturno) {
		this.hrfturno = hrfturno;
	}

}
