package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijhorexc generated by hbm2java
 */
@Entity
@Table(name = "IJHOREXC")
public class Ijhorexc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7938310087280521360L;
	private IjhorexcId id;
	private Ijtbinj ijtbinj;
	private Ijtbtphor ijtbtphor;
	private Date dthrfexchor;
	private BigDecimal conscalefi;

	public Ijhorexc() {
	}

	public Ijhorexc(IjhorexcId id, Ijtbinj ijtbinj, Ijtbtphor ijtbtphor,
			Date dthrfexchor, BigDecimal conscalefi) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijtbtphor = ijtbtphor;
		this.dthrfexchor = dthrfexchor;
		this.conscalefi = conscalefi;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdtphor", column = @Column(name = "CDTPHOR", nullable = false, length = 6)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "dthriexchor", column = @Column(name = "DTHRIEXCHOR", nullable = false, length = 7)) })
	public IjhorexcId getId() {
		return this.id;
	}

	public void setId(IjhorexcId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTPHOR", nullable = false, insertable = false, updatable = false)
	public Ijtbtphor getIjtbtphor() {
		return this.ijtbtphor;
	}

	public void setIjtbtphor(Ijtbtphor ijtbtphor) {
		this.ijtbtphor = ijtbtphor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFEXCHOR", nullable = false, length = 7)
	public Date getDthrfexchor() {
		return this.dthrfexchor;
	}

	public void setDthrfexchor(Date dthrfexchor) {
		this.dthrfexchor = dthrfexchor;
	}

	@Column(name = "CONSCALEFI", nullable = false, precision = 22, scale = 0)
	public BigDecimal getConscalefi() {
		return this.conscalefi;
	}

	public void setConscalefi(BigDecimal conscalefi) {
		this.conscalefi = conscalefi;
	}

}
