package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ijinjctrlultparmon generated by hbm2java
 */
@Entity
@Table(name = "IJINJCTRLULTPARMON", uniqueConstraints = @UniqueConstraint(columnNames = "CDINJETORA"))
public class Ijinjctrlultparmon implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6409041776446438926L;
	private double idregistro;
	private Ijtbinj ijtbinj;
	private Date dthriparrefmonit;
	private Date dthrfparrefmonit;

	public Ijinjctrlultparmon() {
	}

	public Ijinjctrlultparmon(double idregistro, Ijtbinj ijtbinj) {
		this.idregistro = idregistro;
		this.ijtbinj = ijtbinj;
	}

	public Ijinjctrlultparmon(double idregistro, Ijtbinj ijtbinj,
			Date dthriparrefmonit, Date dthrfparrefmonit) {
		this.idregistro = idregistro;
		this.ijtbinj = ijtbinj;
		this.dthriparrefmonit = dthriparrefmonit;
		this.dthrfparrefmonit = dthrfparrefmonit;
	}

	@Id
	@Column(name = "IDREGISTRO", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(double idregistro) {
		this.idregistro = idregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIPARREFMONIT", length = 7)
	public Date getDthriparrefmonit() {
		return this.dthriparrefmonit;
	}

	public void setDthriparrefmonit(Date dthriparrefmonit) {
		this.dthriparrefmonit = dthriparrefmonit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFPARREFMONIT", length = 7)
	public Date getDthrfparrefmonit() {
		return this.dthrfparrefmonit;
	}

	public void setDthrfparrefmonit(Date dthrfparrefmonit) {
		this.dthrfparrefmonit = dthrfparrefmonit;
	}

}
