package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijinspecao generated by hbm2java
 */
@Entity
@Table(name = "IJINSPECAO")
public class Ijinspecao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3028375437142845303L;
	private String idinspecao;
	private Ijtbcentinsp ijtbcentinsp;
	private Ijop ijop;
	private Ijgrpparaminsp ijgrpparaminsp;
	private Ijtbusu ijtbusuByCdsupervisor;
	private Ijtbinj ijtbinj;
	private Ijtbusu ijtbusuByCdusucancelalerta;
	private Ijtbusu ijtbusuByCdoperador;
	private Ijmolpro ijmolpro;
	private Date dthralerta;
	private Date dtrefturnoalerta;
	private String cdturnoalerta;
	private Date dthrinspecao;
	private char resultadoinspecao;
	private String nretiquetainsp;
	private Date dthrcancelalerta;
	private Set<Ijamostragemctrl> ijamostragemctrls = new HashSet<Ijamostragemctrl>(
			0);
	private Set<Ijaledbqldinsp> ijaledbqldinsps = new HashSet<Ijaledbqldinsp>(0);
	private Set<Ijinspecaoctrl> ijinspecaoctrls = new HashSet<Ijinspecaoctrl>(0);
	private Set<Ijamostragem> ijamostragems = new HashSet<Ijamostragem>(0);

	public Ijinspecao() {
	}

	public Ijinspecao(String idinspecao, Ijop ijop,
			Ijgrpparaminsp ijgrpparaminsp, Ijtbinj ijtbinj, Ijmolpro ijmolpro,
			Date dthralerta, Date dtrefturnoalerta, String cdturnoalerta,
			char resultadoinspecao) {
		this.idinspecao = idinspecao;
		this.ijop = ijop;
		this.ijgrpparaminsp = ijgrpparaminsp;
		this.ijtbinj = ijtbinj;
		this.ijmolpro = ijmolpro;
		this.dthralerta = dthralerta;
		this.dtrefturnoalerta = dtrefturnoalerta;
		this.cdturnoalerta = cdturnoalerta;
		this.resultadoinspecao = resultadoinspecao;
	}

	public Ijinspecao(String idinspecao, Ijtbcentinsp ijtbcentinsp, Ijop ijop,
			Ijgrpparaminsp ijgrpparaminsp, Ijtbusu ijtbusuByCdsupervisor,
			Ijtbinj ijtbinj, Ijtbusu ijtbusuByCdusucancelalerta,
			Ijtbusu ijtbusuByCdoperador, Ijmolpro ijmolpro, Date dthralerta,
			Date dtrefturnoalerta, String cdturnoalerta, Date dthrinspecao,
			char resultadoinspecao, String nretiquetainsp,
			Date dthrcancelalerta, Set<Ijamostragemctrl> ijamostragemctrls,
			Set<Ijaledbqldinsp> ijaledbqldinsps,
			Set<Ijinspecaoctrl> ijinspecaoctrls, Set<Ijamostragem> ijamostragems) {
		this.idinspecao = idinspecao;
		this.ijtbcentinsp = ijtbcentinsp;
		this.ijop = ijop;
		this.ijgrpparaminsp = ijgrpparaminsp;
		this.ijtbusuByCdsupervisor = ijtbusuByCdsupervisor;
		this.ijtbinj = ijtbinj;
		this.ijtbusuByCdusucancelalerta = ijtbusuByCdusucancelalerta;
		this.ijtbusuByCdoperador = ijtbusuByCdoperador;
		this.ijmolpro = ijmolpro;
		this.dthralerta = dthralerta;
		this.dtrefturnoalerta = dtrefturnoalerta;
		this.cdturnoalerta = cdturnoalerta;
		this.dthrinspecao = dthrinspecao;
		this.resultadoinspecao = resultadoinspecao;
		this.nretiquetainsp = nretiquetainsp;
		this.dthrcancelalerta = dthrcancelalerta;
		this.ijamostragemctrls = ijamostragemctrls;
		this.ijaledbqldinsps = ijaledbqldinsps;
		this.ijinspecaoctrls = ijinspecaoctrls;
		this.ijamostragems = ijamostragems;
	}

	@Id
	@Column(name = "IDINSPECAO", unique = true, nullable = false, length = 12)
	public String getIdinspecao() {
		return this.idinspecao;
	}

	public void setIdinspecao(String idinspecao) {
		this.idinspecao = idinspecao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCENTINSP")
	public Ijtbcentinsp getIjtbcentinsp() {
		return this.ijtbcentinsp;
	}

	public void setIjtbcentinsp(Ijtbcentinsp ijtbcentinsp) {
		this.ijtbcentinsp = ijtbcentinsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRPPARAM", nullable = false)
	public Ijgrpparaminsp getIjgrpparaminsp() {
		return this.ijgrpparaminsp;
	}

	public void setIjgrpparaminsp(Ijgrpparaminsp ijgrpparaminsp) {
		this.ijgrpparaminsp = ijgrpparaminsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDSUPERVISOR")
	public Ijtbusu getIjtbusuByCdsupervisor() {
		return this.ijtbusuByCdsupervisor;
	}

	public void setIjtbusuByCdsupervisor(Ijtbusu ijtbusuByCdsupervisor) {
		this.ijtbusuByCdsupervisor = ijtbusuByCdsupervisor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUCANCELALERTA")
	public Ijtbusu getIjtbusuByCdusucancelalerta() {
		return this.ijtbusuByCdusucancelalerta;
	}

	public void setIjtbusuByCdusucancelalerta(Ijtbusu ijtbusuByCdusucancelalerta) {
		this.ijtbusuByCdusucancelalerta = ijtbusuByCdusucancelalerta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDOPERADOR")
	public Ijtbusu getIjtbusuByCdoperador() {
		return this.ijtbusuByCdoperador;
	}

	public void setIjtbusuByCdoperador(Ijtbusu ijtbusuByCdoperador) {
		this.ijtbusuByCdoperador = ijtbusuByCdoperador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false),
			@JoinColumn(name = "DTHRIVALESTRU", referencedColumnName = "DTHRIVAL", nullable = false) })
	public Ijmolpro getIjmolpro() {
		return this.ijmolpro;
	}

	public void setIjmolpro(Ijmolpro ijmolpro) {
		this.ijmolpro = ijmolpro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRALERTA", nullable = false, length = 7)
	public Date getDthralerta() {
		return this.dthralerta;
	}

	public void setDthralerta(Date dthralerta) {
		this.dthralerta = dthralerta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTREFTURNOALERTA", nullable = false, length = 7)
	public Date getDtrefturnoalerta() {
		return this.dtrefturnoalerta;
	}

	public void setDtrefturnoalerta(Date dtrefturnoalerta) {
		this.dtrefturnoalerta = dtrefturnoalerta;
	}

	@Column(name = "CDTURNOALERTA", nullable = false, length = 6)
	public String getCdturnoalerta() {
		return this.cdturnoalerta;
	}

	public void setCdturnoalerta(String cdturnoalerta) {
		this.cdturnoalerta = cdturnoalerta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRINSPECAO", length = 7)
	public Date getDthrinspecao() {
		return this.dthrinspecao;
	}

	public void setDthrinspecao(Date dthrinspecao) {
		this.dthrinspecao = dthrinspecao;
	}

	@Column(name = "RESULTADOINSPECAO", nullable = false, length = 1)
	public char getResultadoinspecao() {
		return this.resultadoinspecao;
	}

	public void setResultadoinspecao(char resultadoinspecao) {
		this.resultadoinspecao = resultadoinspecao;
	}

	@Column(name = "NRETIQUETAINSP", length = 20)
	public String getNretiquetainsp() {
		return this.nretiquetainsp;
	}

	public void setNretiquetainsp(String nretiquetainsp) {
		this.nretiquetainsp = nretiquetainsp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRCANCELALERTA", length = 7)
	public Date getDthrcancelalerta() {
		return this.dthrcancelalerta;
	}

	public void setDthrcancelalerta(Date dthrcancelalerta) {
		this.dthrcancelalerta = dthrcancelalerta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijinspecao")
	public Set<Ijamostragemctrl> getIjamostragemctrls() {
		return this.ijamostragemctrls;
	}

	public void setIjamostragemctrls(Set<Ijamostragemctrl> ijamostragemctrls) {
		this.ijamostragemctrls = ijamostragemctrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijinspecao")
	public Set<Ijaledbqldinsp> getIjaledbqldinsps() {
		return this.ijaledbqldinsps;
	}

	public void setIjaledbqldinsps(Set<Ijaledbqldinsp> ijaledbqldinsps) {
		this.ijaledbqldinsps = ijaledbqldinsps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijinspecao")
	public Set<Ijinspecaoctrl> getIjinspecaoctrls() {
		return this.ijinspecaoctrls;
	}

	public void setIjinspecaoctrls(Set<Ijinspecaoctrl> ijinspecaoctrls) {
		this.ijinspecaoctrls = ijinspecaoctrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijinspecao")
	public Set<Ijamostragem> getIjamostragems() {
		return this.ijamostragems;
	}

	public void setIjamostragems(Set<Ijamostragem> ijamostragems) {
		this.ijamostragems = ijamostragems;
	}

}
