package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijinspecaoctrl generated by hbm2java
 */
@Entity
@Table(name = "IJINSPECAOCTRL")
public class Ijinspecaoctrl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4451123922523040596L;
	private String idinspecao;
	private Ijinspecao ijinspecao;
	private BigDecimal qtdamostras;
	private BigDecimal qtdamostraslidas;

	public Ijinspecaoctrl() {
	}

	public Ijinspecaoctrl(String idinspecao, Ijinspecao ijinspecao,
			BigDecimal qtdamostras, BigDecimal qtdamostraslidas) {
		this.idinspecao = idinspecao;
		this.ijinspecao = ijinspecao;
		this.qtdamostras = qtdamostras;
		this.qtdamostraslidas = qtdamostraslidas;
	}

	@Id
	@Column(name = "IDINSPECAO", unique = true, nullable = false, length = 12)
	public String getIdinspecao() {
		return this.idinspecao;
	}

	public void setIdinspecao(String idinspecao) {
		this.idinspecao = idinspecao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINSPECAO", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijinspecao getIjinspecao() {
		return this.ijinspecao;
	}

	public void setIjinspecao(Ijinspecao ijinspecao) {
		this.ijinspecao = ijinspecao;
	}

	@Column(name = "QTDAMOSTRAS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getQtdamostras() {
		return this.qtdamostras;
	}

	public void setQtdamostras(BigDecimal qtdamostras) {
		this.qtdamostras = qtdamostras;
	}

	@Column(name = "QTDAMOSTRASLIDAS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getQtdamostraslidas() {
		return this.qtdamostraslidas;
	}

	public void setQtdamostraslidas(BigDecimal qtdamostraslidas) {
		this.qtdamostraslidas = qtdamostraslidas;
	}

}
