package idw.model.pojos.injet;
// Generated 02/02/2016 08:16:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IjIntFitesaOp generated by hbm2java
 */
@Entity
@Table(name = "ijIntFitesaOP")
public class IjIntFitesaOp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idregistro;
	private String nropErp;
	private String cdmolde;
	private String cdestrutura;
	private String cdproduto;
	private BigDecimal qtdplan;
	private Date dthriniplan;
	private Date dthrfimplan;
	private BigDecimal qtdplanutil;
	private int stregistro;
	private Date dthrregistro;
	private Set<IjIntFitesaOplog> ijIntFitesaOplogs = new HashSet<IjIntFitesaOplog>(0);

	public IjIntFitesaOp() {
	}

	public IjIntFitesaOp(BigDecimal idregistro, String nropErp, String cdmolde, String cdestrutura, String cdproduto,
			BigDecimal qtdplan, Date dthriniplan, Date dthrfimplan, int stregistro, Date dthrregistro) {
		this.idregistro = idregistro;
		this.nropErp = nropErp;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.cdproduto = cdproduto;
		this.qtdplan = qtdplan;
		this.dthriniplan = dthriniplan;
		this.dthrfimplan = dthrfimplan;
		this.stregistro = stregistro;
		this.dthrregistro = dthrregistro;
	}

	public IjIntFitesaOp(BigDecimal idregistro, String nropErp, String cdmolde, String cdestrutura, String cdproduto,
			BigDecimal qtdplan, Date dthriniplan, Date dthrfimplan, BigDecimal qtdplanutil, int stregistro,
			Date dthrregistro, Set<IjIntFitesaOplog> ijIntFitesaOplogs) {
		this.idregistro = idregistro;
		this.nropErp = nropErp;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.cdproduto = cdproduto;
		this.qtdplan = qtdplan;
		this.dthriniplan = dthriniplan;
		this.dthrfimplan = dthrfimplan;
		this.qtdplanutil = qtdplanutil;
		this.stregistro = stregistro;
		this.dthrregistro = dthrregistro;
		this.ijIntFitesaOplogs = ijIntFitesaOplogs;
	}

	@Id

	@Column(name = "idregistro", unique = true, nullable = false, precision = 30, scale = 0)
	public BigDecimal getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(BigDecimal idregistro) {
		this.idregistro = idregistro;
	}

	@Column(name = "nropERP", nullable = false, length = 25)
	public String getNropErp() {
		return this.nropErp;
	}

	public void setNropErp(String nropErp) {
		this.nropErp = nropErp;
	}

	@Column(name = "cdmolde", nullable = false, length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "cdestrutura", nullable = false, length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Column(name = "cdproduto", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "qtdplan", nullable = false, precision = 30, scale = 15)
	public BigDecimal getQtdplan() {
		return this.qtdplan;
	}

	public void setQtdplan(BigDecimal qtdplan) {
		this.qtdplan = qtdplan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthriniplan", nullable = false, length = 23)
	public Date getDthriniplan() {
		return this.dthriniplan;
	}

	public void setDthriniplan(Date dthriniplan) {
		this.dthriniplan = dthriniplan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthrfimplan", nullable = false, length = 23)
	public Date getDthrfimplan() {
		return this.dthrfimplan;
	}

	public void setDthrfimplan(Date dthrfimplan) {
		this.dthrfimplan = dthrfimplan;
	}

	@Column(name = "qtdplanutil", precision = 30, scale = 15)
	public BigDecimal getQtdplanutil() {
		return this.qtdplanutil;
	}

	public void setQtdplanutil(BigDecimal qtdplanutil) {
		this.qtdplanutil = qtdplanutil;
	}

	@Column(name = "stregistro", nullable = false)
	public int getStregistro() {
		return this.stregistro;
	}

	public void setStregistro(int stregistro) {
		this.stregistro = stregistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthrregistro", nullable = false, length = 23)
	public Date getDthrregistro() {
		return this.dthrregistro;
	}

	public void setDthrregistro(Date dthrregistro) {
		this.dthrregistro = dthrregistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijIntFitesaOp")
	public Set<IjIntFitesaOplog> getIjIntFitesaOplogs() {
		return this.ijIntFitesaOplogs;
	}

	public void setIjIntFitesaOplogs(Set<IjIntFitesaOplog> ijIntFitesaOplogs) {
		this.ijIntFitesaOplogs = ijIntFitesaOplogs;
	}

}
