package idw.model.pojos.injet;

// Generated 02/02/2016 08:16:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IjIntFitesaOplog generated by hbm2java
 */
@Entity
@Table(name = "ijIntFitesaOPLog")
public class IjIntFitesaOplog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idregistro;
	private IjIntFitesaOp ijIntFitesaOp;
	private Date dthrlog;
	private String nropInjet;
	private String cdinjetora;
	private BigDecimal qtdincremento;
	private String cdusuario;

	public IjIntFitesaOplog() {
	}

	public IjIntFitesaOplog(BigDecimal idregistro, IjIntFitesaOp ijIntFitesaOp, Date dthrlog, String nropInjet,
			String cdinjetora, BigDecimal qtdincremento, String cdusuario) {
		this.idregistro = idregistro;
		this.ijIntFitesaOp = ijIntFitesaOp;
		this.dthrlog = dthrlog;
		this.nropInjet = nropInjet;
		this.cdinjetora = cdinjetora;
		this.qtdincremento = qtdincremento;
		this.cdusuario = cdusuario;
	}

	@Id

	@Column(name = "idregistro", unique = true, nullable = false, precision = 30, scale = 0)
	public BigDecimal getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(BigDecimal idregistro) {
		this.idregistro = idregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idregistropai", nullable = false)
	public IjIntFitesaOp getIjIntFitesaOp() {
		return this.ijIntFitesaOp;
	}

	public void setIjIntFitesaOp(IjIntFitesaOp ijIntFitesaOp) {
		this.ijIntFitesaOp = ijIntFitesaOp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthrlog", nullable = false, length = 23)
	public Date getDthrlog() {
		return this.dthrlog;
	}

	public void setDthrlog(Date dthrlog) {
		this.dthrlog = dthrlog;
	}

	@Column(name = "nropInjet", nullable = false, length = 10)
	public String getNropInjet() {
		return this.nropInjet;
	}

	public void setNropInjet(String nropInjet) {
		this.nropInjet = nropInjet;
	}

	@Column(name = "cdinjetora", nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Column(name = "qtdincremento", nullable = false, precision = 30, scale = 15)
	public BigDecimal getQtdincremento() {
		return this.qtdincremento;
	}

	public void setQtdincremento(BigDecimal qtdincremento) {
		this.qtdincremento = qtdincremento;
	}

	@Column(name = "cdusuario", nullable = false, length = 6)
	public String getCdusuario() {
		return this.cdusuario;
	}

	public void setCdusuario(String cdusuario) {
		this.cdusuario = cdusuario;
	}

}
