package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijindiceselabels generated by hbm2java
 */
@Entity
@Table(name = "IJINDICESELABELS")
public class Ijindiceselabels implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4059941801388371006L;
	private String cdlingua;
	private Ijlinguas ijlinguas;
	private BigDecimal eficrealizacao;
	private BigDecimal eficciclo;
	private String captionoutros;
	private String captioninicio;
	private String captionfim;
	private String captiondodia;
	private String captionciclo;
	private String captionperdaciclo;
	private String captionperdarefugo;
	private String captionperdaparada;
	private String capperdacavinat;

	public Ijindiceselabels() {
	}

	public Ijindiceselabels(String cdlingua, Ijlinguas ijlinguas) {
		this.cdlingua = cdlingua;
		this.ijlinguas = ijlinguas;
	}

	public Ijindiceselabels(String cdlingua, Ijlinguas ijlinguas,
			BigDecimal eficrealizacao, BigDecimal eficciclo,
			String captionoutros, String captioninicio, String captionfim,
			String captiondodia, String captionciclo, String captionperdaciclo,
			String captionperdarefugo, String captionperdaparada,
			String capperdacavinat) {
		this.cdlingua = cdlingua;
		this.ijlinguas = ijlinguas;
		this.eficrealizacao = eficrealizacao;
		this.eficciclo = eficciclo;
		this.captionoutros = captionoutros;
		this.captioninicio = captioninicio;
		this.captionfim = captionfim;
		this.captiondodia = captiondodia;
		this.captionciclo = captionciclo;
		this.captionperdaciclo = captionperdaciclo;
		this.captionperdarefugo = captionperdarefugo;
		this.captionperdaparada = captionperdaparada;
		this.capperdacavinat = capperdacavinat;
	}

	@Id
	@Column(name = "CDLINGUA", unique = true, nullable = false, length = 6)
	public String getCdlingua() {
		return this.cdlingua;
	}

	public void setCdlingua(String cdlingua) {
		this.cdlingua = cdlingua;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLINGUA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijlinguas getIjlinguas() {
		return this.ijlinguas;
	}

	public void setIjlinguas(Ijlinguas ijlinguas) {
		this.ijlinguas = ijlinguas;
	}

	@Column(name = "EFICREALIZACAO", precision = 5)
	public BigDecimal getEficrealizacao() {
		return this.eficrealizacao;
	}

	public void setEficrealizacao(BigDecimal eficrealizacao) {
		this.eficrealizacao = eficrealizacao;
	}

	@Column(name = "EFICCICLO", precision = 5)
	public BigDecimal getEficciclo() {
		return this.eficciclo;
	}

	public void setEficciclo(BigDecimal eficciclo) {
		this.eficciclo = eficciclo;
	}

	@Column(name = "CAPTIONOUTROS", length = 15)
	public String getCaptionoutros() {
		return this.captionoutros;
	}

	public void setCaptionoutros(String captionoutros) {
		this.captionoutros = captionoutros;
	}

	@Column(name = "CAPTIONINICIO", length = 15)
	public String getCaptioninicio() {
		return this.captioninicio;
	}

	public void setCaptioninicio(String captioninicio) {
		this.captioninicio = captioninicio;
	}

	@Column(name = "CAPTIONFIM", length = 15)
	public String getCaptionfim() {
		return this.captionfim;
	}

	public void setCaptionfim(String captionfim) {
		this.captionfim = captionfim;
	}

	@Column(name = "CAPTIONDODIA", length = 15)
	public String getCaptiondodia() {
		return this.captiondodia;
	}

	public void setCaptiondodia(String captiondodia) {
		this.captiondodia = captiondodia;
	}

	@Column(name = "CAPTIONCICLO", length = 15)
	public String getCaptionciclo() {
		return this.captionciclo;
	}

	public void setCaptionciclo(String captionciclo) {
		this.captionciclo = captionciclo;
	}

	@Column(name = "CAPTIONPERDACICLO", length = 15)
	public String getCaptionperdaciclo() {
		return this.captionperdaciclo;
	}

	public void setCaptionperdaciclo(String captionperdaciclo) {
		this.captionperdaciclo = captionperdaciclo;
	}

	@Column(name = "CAPTIONPERDAREFUGO", length = 15)
	public String getCaptionperdarefugo() {
		return this.captionperdarefugo;
	}

	public void setCaptionperdarefugo(String captionperdarefugo) {
		this.captionperdarefugo = captionperdarefugo;
	}

	@Column(name = "CAPTIONPERDAPARADA", length = 15)
	public String getCaptionperdaparada() {
		return this.captionperdaparada;
	}

	public void setCaptionperdaparada(String captionperdaparada) {
		this.captionperdaparada = captionperdaparada;
	}

	@Column(name = "CAPPERDACAVINAT", length = 20)
	public String getCapperdacavinat() {
		return this.capperdacavinat;
	}

	public void setCapperdacavinat(String capperdacavinat) {
		this.capperdacavinat = capperdacavinat;
	}

}
