package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjitensfiltroId generated by hbm2java
 */
@Embeddable
public class IjitensfiltroId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2622104290017508671L;
	private String cdfiltroitensmen;
	private String cdtipofiltro;
	private String itemsel;

	public IjitensfiltroId() {
	}

	public IjitensfiltroId(String cdfiltroitensmen, String cdtipofiltro,
			String itemsel) {
		this.cdfiltroitensmen = cdfiltroitensmen;
		this.cdtipofiltro = cdtipofiltro;
		this.itemsel = itemsel;
	}

	@Column(name = "CDFILTROITENSMEN", nullable = false, length = 6)
	public String getCdfiltroitensmen() {
		return this.cdfiltroitensmen;
	}

	public void setCdfiltroitensmen(String cdfiltroitensmen) {
		this.cdfiltroitensmen = cdfiltroitensmen;
	}

	@Column(name = "CDTIPOFILTRO", nullable = false, length = 6)
	public String getCdtipofiltro() {
		return this.cdtipofiltro;
	}

	public void setCdtipofiltro(String cdtipofiltro) {
		this.cdtipofiltro = cdtipofiltro;
	}

	@Column(name = "ITEMSEL", nullable = false, length = 6)
	public String getItemsel() {
		return this.itemsel;
	}

	public void setItemsel(String itemsel) {
		this.itemsel = itemsel;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjitensfiltroId))
			return false;
		IjitensfiltroId castOther = (IjitensfiltroId) other;

		return ((this.getCdfiltroitensmen() == castOther.getCdfiltroitensmen()) || (this
				.getCdfiltroitensmen() != null
				&& castOther.getCdfiltroitensmen() != null && this
				.getCdfiltroitensmen().equals(castOther.getCdfiltroitensmen())))
				&& ((this.getCdtipofiltro() == castOther.getCdtipofiltro()) || (this
						.getCdtipofiltro() != null
						&& castOther.getCdtipofiltro() != null && this
						.getCdtipofiltro().equals(castOther.getCdtipofiltro())))
				&& ((this.getItemsel() == castOther.getItemsel()) || (this
						.getItemsel() != null && castOther.getItemsel() != null && this
						.getItemsel().equals(castOther.getItemsel())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdfiltroitensmen() == null ? 0 : this
						.getCdfiltroitensmen().hashCode());
		result = 37
				* result
				+ (getCdtipofiltro() == null ? 0 : this.getCdtipofiltro()
						.hashCode());
		result = 37 * result
				+ (getItemsel() == null ? 0 : this.getItemsel().hashCode());
		return result;
	}

}
