package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijkanbanmov generated by hbm2java
 */
@Entity
@Table(name = "IJKANBANMOV")
public class Ijkanbanmov implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6071950200889362285L;
	private IjkanbanmovId id;
	private Ijkanbanlocal ijkanbanlocalByCdlocaldestino;
	private Ijkanbanlocal ijkanbanlocalByCdlocalorigem;
	private Ijkanbanidcartao ijkanbanidcartao;
	private Ijtbusu ijtbusu;

	public Ijkanbanmov() {
	}

	public Ijkanbanmov(IjkanbanmovId id,
			Ijkanbanlocal ijkanbanlocalByCdlocaldestino,
			Ijkanbanlocal ijkanbanlocalByCdlocalorigem,
			Ijkanbanidcartao ijkanbanidcartao, Ijtbusu ijtbusu) {
		this.id = id;
		this.ijkanbanlocalByCdlocaldestino = ijkanbanlocalByCdlocaldestino;
		this.ijkanbanlocalByCdlocalorigem = ijkanbanlocalByCdlocalorigem;
		this.ijkanbanidcartao = ijkanbanidcartao;
		this.ijtbusu = ijtbusu;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idcartaokanban", column = @Column(name = "IDCARTAOKANBAN", nullable = false, length = 50)),
			@AttributeOverride(name = "dthrmovimentacao", column = @Column(name = "DTHRMOVIMENTACAO", nullable = false, length = 7)) })
	public IjkanbanmovId getId() {
		return this.id;
	}

	public void setId(IjkanbanmovId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLOCALDESTINO", nullable = false)
	public Ijkanbanlocal getIjkanbanlocalByCdlocaldestino() {
		return this.ijkanbanlocalByCdlocaldestino;
	}

	public void setIjkanbanlocalByCdlocaldestino(
			Ijkanbanlocal ijkanbanlocalByCdlocaldestino) {
		this.ijkanbanlocalByCdlocaldestino = ijkanbanlocalByCdlocaldestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLOCALORIGEM", nullable = false)
	public Ijkanbanlocal getIjkanbanlocalByCdlocalorigem() {
		return this.ijkanbanlocalByCdlocalorigem;
	}

	public void setIjkanbanlocalByCdlocalorigem(
			Ijkanbanlocal ijkanbanlocalByCdlocalorigem) {
		this.ijkanbanlocalByCdlocalorigem = ijkanbanlocalByCdlocalorigem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCARTAOKANBAN", nullable = false, insertable = false, updatable = false)
	public Ijkanbanidcartao getIjkanbanidcartao() {
		return this.ijkanbanidcartao;
	}

	public void setIjkanbanidcartao(Ijkanbanidcartao ijkanbanidcartao) {
		this.ijkanbanidcartao = ijkanbanidcartao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIO", nullable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

}
