package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijkanbanfluxo generated by hbm2java
 */
@Entity
@Table(name = "IJKANBANFLUXO")
public class Ijkanbanfluxo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7571903073046420001L;
	private String cdlocalorigem;
	private Ijkanbanlocal ijkanbanlocalByCdlocaldestino;
	private Ijkanbanlocal ijkanbanlocalByCdlocalorigem;

	public Ijkanbanfluxo() {
	}

	public Ijkanbanfluxo(String cdlocalorigem,
			Ijkanbanlocal ijkanbanlocalByCdlocaldestino,
			Ijkanbanlocal ijkanbanlocalByCdlocalorigem) {
		this.cdlocalorigem = cdlocalorigem;
		this.ijkanbanlocalByCdlocaldestino = ijkanbanlocalByCdlocaldestino;
		this.ijkanbanlocalByCdlocalorigem = ijkanbanlocalByCdlocalorigem;
	}

	@Id
	@Column(name = "CDLOCALORIGEM", unique = true, nullable = false, length = 6)
	public String getCdlocalorigem() {
		return this.cdlocalorigem;
	}

	public void setCdlocalorigem(String cdlocalorigem) {
		this.cdlocalorigem = cdlocalorigem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLOCALDESTINO", nullable = false)
	public Ijkanbanlocal getIjkanbanlocalByCdlocaldestino() {
		return this.ijkanbanlocalByCdlocaldestino;
	}

	public void setIjkanbanlocalByCdlocaldestino(
			Ijkanbanlocal ijkanbanlocalByCdlocaldestino) {
		this.ijkanbanlocalByCdlocaldestino = ijkanbanlocalByCdlocaldestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLOCALORIGEM", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijkanbanlocal getIjkanbanlocalByCdlocalorigem() {
		return this.ijkanbanlocalByCdlocalorigem;
	}

	public void setIjkanbanlocalByCdlocalorigem(
			Ijkanbanlocal ijkanbanlocalByCdlocalorigem) {
		this.ijkanbanlocalByCdlocalorigem = ijkanbanlocalByCdlocalorigem;
	}

}
