package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijlinguas generated by hbm2java
 */
@Entity
@Table(name = "IJLINGUAS")
public class Ijlinguas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9126514023771156339L;
	private String cdlingua;
	private String dslingua;
	private Set<Ijtbesttab> ijtbesttabs = new HashSet<Ijtbesttab>(0);
	private Set<Ijtbcont> ijtbconts = new HashSet<Ijtbcont>(0);
	private Set<Ijtbconttempo> ijtbconttempos = new HashSet<Ijtbconttempo>(0);
	private Set<Ijoplogicos> ijoplogicoses = new HashSet<Ijoplogicos>(0);
	private Set<Ijtbparam> ijtbparams = new HashSet<Ijtbparam>(0);
	private Set<Ijtbsitmaq> ijtbsitmaqs = new HashSet<Ijtbsitmaq>(0);
	private Set<Ijrptreports> ijrptreportses = new HashSet<Ijrptreports>(0);
	private Set<Ijtbtipofiltro> ijtbtipofiltros = new HashSet<Ijtbtipofiltro>(0);
	private Set<Ijindiceselabels> ijindiceselabelses = new HashSet<Ijindiceselabels>(
			0);
	private Set<Ijtbtpocorea> ijtbtpocoreas = new HashSet<Ijtbtpocorea>(0);
	private Set<Ijcaptionlinguas> ijcaptionlinguases = new HashSet<Ijcaptionlinguas>(
			0);
	private Set<Ijtbgrids> ijtbgridses = new HashSet<Ijtbgrids>(0);
	private Set<Ijgrafico> ijgraficos = new HashSet<Ijgrafico>(0);
	private Set<Ijtbinf> ijtbinfs = new HashSet<Ijtbinf>(0);
	private Set<Ijtbmen> ijtbmens = new HashSet<Ijtbmen>(0);
	private Set<Ijtbmes> ijtbmeses = new HashSet<Ijtbmes>(0);

	public Ijlinguas() {
	}

	public Ijlinguas(String cdlingua) {
		this.cdlingua = cdlingua;
	}

	public Ijlinguas(String cdlingua, String dslingua,
			Set<Ijtbesttab> ijtbesttabs, Set<Ijtbcont> ijtbconts,
			Set<Ijtbconttempo> ijtbconttempos, Set<Ijoplogicos> ijoplogicoses,
			Set<Ijtbparam> ijtbparams, Set<Ijtbsitmaq> ijtbsitmaqs,
			Set<Ijrptreports> ijrptreportses,
			Set<Ijtbtipofiltro> ijtbtipofiltros,
			Set<Ijindiceselabels> ijindiceselabelses,
			Set<Ijtbtpocorea> ijtbtpocoreas,
			Set<Ijcaptionlinguas> ijcaptionlinguases,
			Set<Ijtbgrids> ijtbgridses, Set<Ijgrafico> ijgraficos,
			Set<Ijtbinf> ijtbinfs, Set<Ijtbmen> ijtbmens, Set<Ijtbmes> ijtbmeses) {
		this.cdlingua = cdlingua;
		this.dslingua = dslingua;
		this.ijtbesttabs = ijtbesttabs;
		this.ijtbconts = ijtbconts;
		this.ijtbconttempos = ijtbconttempos;
		this.ijoplogicoses = ijoplogicoses;
		this.ijtbparams = ijtbparams;
		this.ijtbsitmaqs = ijtbsitmaqs;
		this.ijrptreportses = ijrptreportses;
		this.ijtbtipofiltros = ijtbtipofiltros;
		this.ijindiceselabelses = ijindiceselabelses;
		this.ijtbtpocoreas = ijtbtpocoreas;
		this.ijcaptionlinguases = ijcaptionlinguases;
		this.ijtbgridses = ijtbgridses;
		this.ijgraficos = ijgraficos;
		this.ijtbinfs = ijtbinfs;
		this.ijtbmens = ijtbmens;
		this.ijtbmeses = ijtbmeses;
	}

	@Id
	@Column(name = "CDLINGUA", unique = true, nullable = false, length = 6)
	public String getCdlingua() {
		return this.cdlingua;
	}

	public void setCdlingua(String cdlingua) {
		this.cdlingua = cdlingua;
	}

	@Column(name = "DSLINGUA", length = 20)
	public String getDslingua() {
		return this.dslingua;
	}

	public void setDslingua(String dslingua) {
		this.dslingua = dslingua;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbesttab> getIjtbesttabs() {
		return this.ijtbesttabs;
	}

	public void setIjtbesttabs(Set<Ijtbesttab> ijtbesttabs) {
		this.ijtbesttabs = ijtbesttabs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbcont> getIjtbconts() {
		return this.ijtbconts;
	}

	public void setIjtbconts(Set<Ijtbcont> ijtbconts) {
		this.ijtbconts = ijtbconts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbconttempo> getIjtbconttempos() {
		return this.ijtbconttempos;
	}

	public void setIjtbconttempos(Set<Ijtbconttempo> ijtbconttempos) {
		this.ijtbconttempos = ijtbconttempos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijoplogicos> getIjoplogicoses() {
		return this.ijoplogicoses;
	}

	public void setIjoplogicoses(Set<Ijoplogicos> ijoplogicoses) {
		this.ijoplogicoses = ijoplogicoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbparam> getIjtbparams() {
		return this.ijtbparams;
	}

	public void setIjtbparams(Set<Ijtbparam> ijtbparams) {
		this.ijtbparams = ijtbparams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbsitmaq> getIjtbsitmaqs() {
		return this.ijtbsitmaqs;
	}

	public void setIjtbsitmaqs(Set<Ijtbsitmaq> ijtbsitmaqs) {
		this.ijtbsitmaqs = ijtbsitmaqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijrptreports> getIjrptreportses() {
		return this.ijrptreportses;
	}

	public void setIjrptreportses(Set<Ijrptreports> ijrptreportses) {
		this.ijrptreportses = ijrptreportses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbtipofiltro> getIjtbtipofiltros() {
		return this.ijtbtipofiltros;
	}

	public void setIjtbtipofiltros(Set<Ijtbtipofiltro> ijtbtipofiltros) {
		this.ijtbtipofiltros = ijtbtipofiltros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijindiceselabels> getIjindiceselabelses() {
		return this.ijindiceselabelses;
	}

	public void setIjindiceselabelses(Set<Ijindiceselabels> ijindiceselabelses) {
		this.ijindiceselabelses = ijindiceselabelses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbtpocorea> getIjtbtpocoreas() {
		return this.ijtbtpocoreas;
	}

	public void setIjtbtpocoreas(Set<Ijtbtpocorea> ijtbtpocoreas) {
		this.ijtbtpocoreas = ijtbtpocoreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijcaptionlinguas> getIjcaptionlinguases() {
		return this.ijcaptionlinguases;
	}

	public void setIjcaptionlinguases(Set<Ijcaptionlinguas> ijcaptionlinguases) {
		this.ijcaptionlinguases = ijcaptionlinguases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbgrids> getIjtbgridses() {
		return this.ijtbgridses;
	}

	public void setIjtbgridses(Set<Ijtbgrids> ijtbgridses) {
		this.ijtbgridses = ijtbgridses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijgrafico> getIjgraficos() {
		return this.ijgraficos;
	}

	public void setIjgraficos(Set<Ijgrafico> ijgraficos) {
		this.ijgraficos = ijgraficos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbinf> getIjtbinfs() {
		return this.ijtbinfs;
	}

	public void setIjtbinfs(Set<Ijtbinf> ijtbinfs) {
		this.ijtbinfs = ijtbinfs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbmen> getIjtbmens() {
		return this.ijtbmens;
	}

	public void setIjtbmens(Set<Ijtbmen> ijtbmens) {
		this.ijtbmens = ijtbmens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlinguas")
	public Set<Ijtbmes> getIjtbmeses() {
		return this.ijtbmeses;
	}

	public void setIjtbmeses(Set<Ijtbmes> ijtbmeses) {
		this.ijtbmeses = ijtbmeses;
	}

}
