package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijlotenipponins generated by hbm2java
 */
@Entity
@Table(name = "IJLOTENIPPONINS")
public class Ijlotenipponins implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8656454010990183141L;
	private String nrlote;
	private Ijtbmprima ijtbmprima;
	private double qtdinsumo;
	private BigDecimal ativo;
	private Set<Ijocorreploteins> ijocorreploteinses = new HashSet<Ijocorreploteins>(
			0);

	public Ijlotenipponins() {
	}

	public Ijlotenipponins(String nrlote, Ijtbmprima ijtbmprima,
			double qtdinsumo, BigDecimal ativo) {
		this.nrlote = nrlote;
		this.ijtbmprima = ijtbmprima;
		this.qtdinsumo = qtdinsumo;
		this.ativo = ativo;
	}

	public Ijlotenipponins(String nrlote, Ijtbmprima ijtbmprima,
			double qtdinsumo, BigDecimal ativo,
			Set<Ijocorreploteins> ijocorreploteinses) {
		this.nrlote = nrlote;
		this.ijtbmprima = ijtbmprima;
		this.qtdinsumo = qtdinsumo;
		this.ativo = ativo;
		this.ijocorreploteinses = ijocorreploteinses;
	}

	@Id
	@Column(name = "NRLOTE", unique = true, nullable = false, length = 20)
	public String getNrlote() {
		return this.nrlote;
	}

	public void setNrlote(String nrlote) {
		this.nrlote = nrlote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMPRIMA", nullable = false)
	public Ijtbmprima getIjtbmprima() {
		return this.ijtbmprima;
	}

	public void setIjtbmprima(Ijtbmprima ijtbmprima) {
		this.ijtbmprima = ijtbmprima;
	}

	@Column(name = "QTDINSUMO", nullable = false, precision = 126, scale = 0)
	public double getQtdinsumo() {
		return this.qtdinsumo;
	}

	public void setQtdinsumo(double qtdinsumo) {
		this.qtdinsumo = qtdinsumo;
	}

	@Column(name = "ATIVO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAtivo() {
		return this.ativo;
	}

	public void setAtivo(BigDecimal ativo) {
		this.ativo = ativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijlotenipponins")
	public Set<Ijocorreploteins> getIjocorreploteinses() {
		return this.ijocorreploteinses;
	}

	public void setIjocorreploteinses(Set<Ijocorreploteins> ijocorreploteinses) {
		this.ijocorreploteinses = ijocorreploteinses;
	}

}
