package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijloginj generated by hbm2java
 */
@Entity
@Table(name = "IJLOGINJ")
public class Ijloginj implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1230879045422360401L;
	private IjloginjId id;
	private Ijtbinj ijtbinj;
	private Date dthrlogout;

	public Ijloginj() {
	}

	public Ijloginj(IjloginjId id, Ijtbinj ijtbinj) {
		this.id = id;
		this.ijtbinj = ijtbinj;
	}

	public Ijloginj(IjloginjId id, Ijtbinj ijtbinj, Date dthrlogout) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.dthrlogout = dthrlogout;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthrlogin", column = @Column(name = "DTHRLOGIN", nullable = false, length = 7)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public IjloginjId getId() {
		return this.id;
	}

	public void setId(IjloginjId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRLOGOUT", length = 7)
	public Date getDthrlogout() {
		return this.dthrlogout;
	}

	public void setDthrlogout(Date dthrlogout) {
		this.dthrlogout = dthrlogout;
	}

}
