package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijlogtrocamaqmol generated by hbm2java
 */
@Entity
@Table(name = "IJLOGTROCAMAQMOL")
public class Ijlogtrocamaqmol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3707112869330119902L;
	private IjlogtrocamaqmolId id;
	private String cdusuario;
	private String cdmaqprefant;
	private String cdmaqprefnova;

	public Ijlogtrocamaqmol() {
	}

	public Ijlogtrocamaqmol(IjlogtrocamaqmolId id, String cdusuario,
			String cdmaqprefnova) {
		this.id = id;
		this.cdusuario = cdusuario;
		this.cdmaqprefnova = cdmaqprefnova;
	}

	public Ijlogtrocamaqmol(IjlogtrocamaqmolId id, String cdusuario,
			String cdmaqprefant, String cdmaqprefnova) {
		this.id = id;
		this.cdusuario = cdusuario;
		this.cdmaqprefant = cdmaqprefant;
		this.cdmaqprefnova = cdmaqprefnova;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrtroca", column = @Column(name = "DTHRTROCA", nullable = false, length = 7)) })
	public IjlogtrocamaqmolId getId() {
		return this.id;
	}

	public void setId(IjlogtrocamaqmolId id) {
		this.id = id;
	}

	@Column(name = "CDUSUARIO", nullable = false, length = 6)
	public String getCdusuario() {
		return this.cdusuario;
	}

	public void setCdusuario(String cdusuario) {
		this.cdusuario = cdusuario;
	}

	@Column(name = "CDMAQPREFANT", length = 6)
	public String getCdmaqprefant() {
		return this.cdmaqprefant;
	}

	public void setCdmaqprefant(String cdmaqprefant) {
		this.cdmaqprefant = cdmaqprefant;
	}

	@Column(name = "CDMAQPREFNOVA", nullable = false, length = 6)
	public String getCdmaqprefnova() {
		return this.cdmaqprefnova;
	}

	public void setCdmaqprefnova(String cdmaqprefnova) {
		this.cdmaqprefnova = cdmaqprefnova;
	}

}
