package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjlogcorrreqId generated by hbm2java
 */
@Embeddable
public class IjlogcorrreqId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3766119620856936907L;
	private String cdusuario;
	private String cdinjetora;
	private String cdparada;
	private Date dthriparada;
	private String drttecnico1;
	private String drttecnico2;
	private String drtresponsa;
	private String cdacoes;
	private String cdcausas;
	private String cdjustparada;

	public IjlogcorrreqId() {
	}

	public IjlogcorrreqId(String cdusuario, String cdinjetora, String cdparada,
			Date dthriparada, String drttecnico1, String drttecnico2,
			String drtresponsa, String cdacoes, String cdcausas,
			String cdjustparada) {
		this.cdusuario = cdusuario;
		this.cdinjetora = cdinjetora;
		this.cdparada = cdparada;
		this.dthriparada = dthriparada;
		this.drttecnico1 = drttecnico1;
		this.drttecnico2 = drttecnico2;
		this.drtresponsa = drtresponsa;
		this.cdacoes = cdacoes;
		this.cdcausas = cdcausas;
		this.cdjustparada = cdjustparada;
	}

	@Column(name = "CDUSUARIO", length = 6)
	public String getCdusuario() {
		return this.cdusuario;
	}

	public void setCdusuario(String cdusuario) {
		this.cdusuario = cdusuario;
	}

	@Column(name = "CDINJETORA", length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Column(name = "CDPARADA", length = 6)
	public String getCdparada() {
		return this.cdparada;
	}

	public void setCdparada(String cdparada) {
		this.cdparada = cdparada;
	}

	@Column(name = "DTHRIPARADA", length = 7)
	public Date getDthriparada() {
		return this.dthriparada;
	}

	public void setDthriparada(Date dthriparada) {
		this.dthriparada = dthriparada;
	}

	@Column(name = "DRTTECNICO1", length = 6)
	public String getDrttecnico1() {
		return this.drttecnico1;
	}

	public void setDrttecnico1(String drttecnico1) {
		this.drttecnico1 = drttecnico1;
	}

	@Column(name = "DRTTECNICO2", length = 6)
	public String getDrttecnico2() {
		return this.drttecnico2;
	}

	public void setDrttecnico2(String drttecnico2) {
		this.drttecnico2 = drttecnico2;
	}

	@Column(name = "DRTRESPONSA", length = 6)
	public String getDrtresponsa() {
		return this.drtresponsa;
	}

	public void setDrtresponsa(String drtresponsa) {
		this.drtresponsa = drtresponsa;
	}

	@Column(name = "CDACOES", length = 6)
	public String getCdacoes() {
		return this.cdacoes;
	}

	public void setCdacoes(String cdacoes) {
		this.cdacoes = cdacoes;
	}

	@Column(name = "CDCAUSAS", length = 6)
	public String getCdcausas() {
		return this.cdcausas;
	}

	public void setCdcausas(String cdcausas) {
		this.cdcausas = cdcausas;
	}

	@Column(name = "CDJUSTPARADA", length = 6)
	public String getCdjustparada() {
		return this.cdjustparada;
	}

	public void setCdjustparada(String cdjustparada) {
		this.cdjustparada = cdjustparada;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjlogcorrreqId))
			return false;
		IjlogcorrreqId castOther = (IjlogcorrreqId) other;

		return ((this.getCdusuario() == castOther.getCdusuario()) || (this
				.getCdusuario() != null && castOther.getCdusuario() != null && this
				.getCdusuario().equals(castOther.getCdusuario())))
				&& ((this.getCdinjetora() == castOther.getCdinjetora()) || (this
						.getCdinjetora() != null
						&& castOther.getCdinjetora() != null && this
						.getCdinjetora().equals(castOther.getCdinjetora())))
				&& ((this.getCdparada() == castOther.getCdparada()) || (this
						.getCdparada() != null
						&& castOther.getCdparada() != null && this
						.getCdparada().equals(castOther.getCdparada())))
				&& ((this.getDthriparada() == castOther.getDthriparada()) || (this
						.getDthriparada() != null
						&& castOther.getDthriparada() != null && this
						.getDthriparada().equals(castOther.getDthriparada())))
				&& ((this.getDrttecnico1() == castOther.getDrttecnico1()) || (this
						.getDrttecnico1() != null
						&& castOther.getDrttecnico1() != null && this
						.getDrttecnico1().equals(castOther.getDrttecnico1())))
				&& ((this.getDrttecnico2() == castOther.getDrttecnico2()) || (this
						.getDrttecnico2() != null
						&& castOther.getDrttecnico2() != null && this
						.getDrttecnico2().equals(castOther.getDrttecnico2())))
				&& ((this.getDrtresponsa() == castOther.getDrtresponsa()) || (this
						.getDrtresponsa() != null
						&& castOther.getDrtresponsa() != null && this
						.getDrtresponsa().equals(castOther.getDrtresponsa())))
				&& ((this.getCdacoes() == castOther.getCdacoes()) || (this
						.getCdacoes() != null && castOther.getCdacoes() != null && this
						.getCdacoes().equals(castOther.getCdacoes())))
				&& ((this.getCdcausas() == castOther.getCdcausas()) || (this
						.getCdcausas() != null
						&& castOther.getCdcausas() != null && this
						.getCdcausas().equals(castOther.getCdcausas())))
				&& ((this.getCdjustparada() == castOther.getCdjustparada()) || (this
						.getCdjustparada() != null
						&& castOther.getCdjustparada() != null && this
						.getCdjustparada().equals(castOther.getCdjustparada())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCdusuario() == null ? 0 : this.getCdusuario().hashCode());
		result = 37
				* result
				+ (getCdinjetora() == null ? 0 : this.getCdinjetora()
						.hashCode());
		result = 37 * result
				+ (getCdparada() == null ? 0 : this.getCdparada().hashCode());
		result = 37
				* result
				+ (getDthriparada() == null ? 0 : this.getDthriparada()
						.hashCode());
		result = 37
				* result
				+ (getDrttecnico1() == null ? 0 : this.getDrttecnico1()
						.hashCode());
		result = 37
				* result
				+ (getDrttecnico2() == null ? 0 : this.getDrttecnico2()
						.hashCode());
		result = 37
				* result
				+ (getDrtresponsa() == null ? 0 : this.getDrtresponsa()
						.hashCode());
		result = 37 * result
				+ (getCdacoes() == null ? 0 : this.getCdacoes().hashCode());
		result = 37 * result
				+ (getCdcausas() == null ? 0 : this.getCdcausas().hashCode());
		result = 37
				* result
				+ (getCdjustparada() == null ? 0 : this.getCdjustparada()
						.hashCode());
		return result;
	}

}
