package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijloggalabc generated by hbm2java
 */
@Entity
@Table(name = "IJLOGGALABC")
public class Ijloggalabc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5056711401428487142L;
	private Date dthrocorrabc;
	private Ijcfggalabc ijcfggalabc;
	private Ijtbusu ijtbusu;
	private double limclassea;
	private double limclassec;
	private double metaoeemina;
	private double metaoeemaxa;
	private double metaoeeminb;
	private double metaoeemaxb;
	private double metaoeeminc;
	private double metaoeemaxc;
	private String observacao;

	public Ijloggalabc() {
	}

	public Ijloggalabc(Date dthrocorrabc, Ijcfggalabc ijcfggalabc,
			Ijtbusu ijtbusu, double limclassea, double limclassec,
			double metaoeemina, double metaoeemaxa, double metaoeeminb,
			double metaoeemaxb, double metaoeeminc, double metaoeemaxc) {
		this.dthrocorrabc = dthrocorrabc;
		this.ijcfggalabc = ijcfggalabc;
		this.ijtbusu = ijtbusu;
		this.limclassea = limclassea;
		this.limclassec = limclassec;
		this.metaoeemina = metaoeemina;
		this.metaoeemaxa = metaoeemaxa;
		this.metaoeeminb = metaoeeminb;
		this.metaoeemaxb = metaoeemaxb;
		this.metaoeeminc = metaoeeminc;
		this.metaoeemaxc = metaoeemaxc;
	}

	public Ijloggalabc(Date dthrocorrabc, Ijcfggalabc ijcfggalabc,
			Ijtbusu ijtbusu, double limclassea, double limclassec,
			double metaoeemina, double metaoeemaxa, double metaoeeminb,
			double metaoeemaxb, double metaoeeminc, double metaoeemaxc,
			String observacao) {
		this.dthrocorrabc = dthrocorrabc;
		this.ijcfggalabc = ijcfggalabc;
		this.ijtbusu = ijtbusu;
		this.limclassea = limclassea;
		this.limclassec = limclassec;
		this.metaoeemina = metaoeemina;
		this.metaoeemaxa = metaoeemaxa;
		this.metaoeeminb = metaoeeminb;
		this.metaoeemaxb = metaoeemaxb;
		this.metaoeeminc = metaoeeminc;
		this.metaoeemaxc = metaoeemaxc;
		this.observacao = observacao;
	}

	@Id
	@Temporal(TemporalType.DATE)
	@Column(name = "DTHROCORRABC", unique = true, nullable = false, length = 7)
	public Date getDthrocorrabc() {
		return this.dthrocorrabc;
	}

	public void setDthrocorrabc(Date dthrocorrabc) {
		this.dthrocorrabc = dthrocorrabc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPCFG", nullable = false)
	public Ijcfggalabc getIjcfggalabc() {
		return this.ijcfggalabc;
	}

	public void setIjcfggalabc(Ijcfggalabc ijcfggalabc) {
		this.ijcfggalabc = ijcfggalabc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIO", nullable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@Column(name = "LIMCLASSEA", nullable = false, precision = 126, scale = 0)
	public double getLimclassea() {
		return this.limclassea;
	}

	public void setLimclassea(double limclassea) {
		this.limclassea = limclassea;
	}

	@Column(name = "LIMCLASSEC", nullable = false, precision = 126, scale = 0)
	public double getLimclassec() {
		return this.limclassec;
	}

	public void setLimclassec(double limclassec) {
		this.limclassec = limclassec;
	}

	@Column(name = "METAOEEMINA", nullable = false, precision = 126, scale = 0)
	public double getMetaoeemina() {
		return this.metaoeemina;
	}

	public void setMetaoeemina(double metaoeemina) {
		this.metaoeemina = metaoeemina;
	}

	@Column(name = "METAOEEMAXA", nullable = false, precision = 126, scale = 0)
	public double getMetaoeemaxa() {
		return this.metaoeemaxa;
	}

	public void setMetaoeemaxa(double metaoeemaxa) {
		this.metaoeemaxa = metaoeemaxa;
	}

	@Column(name = "METAOEEMINB", nullable = false, precision = 126, scale = 0)
	public double getMetaoeeminb() {
		return this.metaoeeminb;
	}

	public void setMetaoeeminb(double metaoeeminb) {
		this.metaoeeminb = metaoeeminb;
	}

	@Column(name = "METAOEEMAXB", nullable = false, precision = 126, scale = 0)
	public double getMetaoeemaxb() {
		return this.metaoeemaxb;
	}

	public void setMetaoeemaxb(double metaoeemaxb) {
		this.metaoeemaxb = metaoeemaxb;
	}

	@Column(name = "METAOEEMINC", nullable = false, precision = 126, scale = 0)
	public double getMetaoeeminc() {
		return this.metaoeeminc;
	}

	public void setMetaoeeminc(double metaoeeminc) {
		this.metaoeeminc = metaoeeminc;
	}

	@Column(name = "METAOEEMAXC", nullable = false, precision = 126, scale = 0)
	public double getMetaoeemaxc() {
		return this.metaoeemaxc;
	}

	public void setMetaoeemaxc(double metaoeemaxc) {
		this.metaoeemaxc = metaoeemaxc;
	}

	@Column(name = "OBSERVACAO")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

}
