package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjlogsenhatmId generated by hbm2java
 */
@Embeddable
public class IjlogsenhatmId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4297425451370686963L;
	private String cdadmin;
	private Date dthrtroca;
	private String cdusuario;

	public IjlogsenhatmId() {
	}

	public IjlogsenhatmId(String cdadmin, Date dthrtroca, String cdusuario) {
		this.cdadmin = cdadmin;
		this.dthrtroca = dthrtroca;
		this.cdusuario = cdusuario;
	}

	@Column(name = "CDADMIN", length = 6)
	public String getCdadmin() {
		return this.cdadmin;
	}

	public void setCdadmin(String cdadmin) {
		this.cdadmin = cdadmin;
	}

	@Column(name = "DTHRTROCA", length = 7)
	public Date getDthrtroca() {
		return this.dthrtroca;
	}

	public void setDthrtroca(Date dthrtroca) {
		this.dthrtroca = dthrtroca;
	}

	@Column(name = "CDUSUARIO", length = 6)
	public String getCdusuario() {
		return this.cdusuario;
	}

	public void setCdusuario(String cdusuario) {
		this.cdusuario = cdusuario;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjlogsenhatmId))
			return false;
		IjlogsenhatmId castOther = (IjlogsenhatmId) other;

		return ((this.getCdadmin() == castOther.getCdadmin()) || (this
				.getCdadmin() != null && castOther.getCdadmin() != null && this
				.getCdadmin().equals(castOther.getCdadmin())))
				&& ((this.getDthrtroca() == castOther.getDthrtroca()) || (this
						.getDthrtroca() != null
						&& castOther.getDthrtroca() != null && this
						.getDthrtroca().equals(castOther.getDthrtroca())))
				&& ((this.getCdusuario() == castOther.getCdusuario()) || (this
						.getCdusuario() != null
						&& castOther.getCdusuario() != null && this
						.getCdusuario().equals(castOther.getCdusuario())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCdadmin() == null ? 0 : this.getCdadmin().hashCode());
		result = 37 * result
				+ (getDthrtroca() == null ? 0 : this.getDthrtroca().hashCode());
		result = 37 * result
				+ (getCdusuario() == null ? 0 : this.getCdusuario().hashCode());
		return result;
	}

}
