package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijlogcorrreq generated by hbm2java
 */
@Entity
@Table(name = "IJLOGCORRREQ")
public class Ijlogcorrreq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7024015822202038857L;
	private IjlogcorrreqId id;
	private Ijtbusu ijtbusuByDrtresponsa;
	private Ijtbusu ijtbusuByDrttecnico2;
	private Ijtbusu ijtbusuByDrttecnico1;
	private Ijtbinj ijtbinj;
	private Ijtbpar ijtbpar;
	private Ijtbcau ijtbcau;
	private Ijtbjup ijtbjup;
	private Ijtbaco ijtbaco;
	private Ijtbusu ijtbusuByCdusuario;

	public Ijlogcorrreq() {
	}

	public Ijlogcorrreq(IjlogcorrreqId id) {
		this.id = id;
	}

	public Ijlogcorrreq(IjlogcorrreqId id, Ijtbusu ijtbusuByDrtresponsa,
			Ijtbusu ijtbusuByDrttecnico2, Ijtbusu ijtbusuByDrttecnico1,
			Ijtbinj ijtbinj, Ijtbpar ijtbpar, Ijtbcau ijtbcau, Ijtbjup ijtbjup,
			Ijtbaco ijtbaco, Ijtbusu ijtbusuByCdusuario) {
		this.id = id;
		this.ijtbusuByDrtresponsa = ijtbusuByDrtresponsa;
		this.ijtbusuByDrttecnico2 = ijtbusuByDrttecnico2;
		this.ijtbusuByDrttecnico1 = ijtbusuByDrttecnico1;
		this.ijtbinj = ijtbinj;
		this.ijtbpar = ijtbpar;
		this.ijtbcau = ijtbcau;
		this.ijtbjup = ijtbjup;
		this.ijtbaco = ijtbaco;
		this.ijtbusuByCdusuario = ijtbusuByCdusuario;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdusuario", column = @Column(name = "CDUSUARIO", length = 6)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", length = 6)),
			@AttributeOverride(name = "cdparada", column = @Column(name = "CDPARADA", length = 6)),
			@AttributeOverride(name = "dthriparada", column = @Column(name = "DTHRIPARADA", length = 7)),
			@AttributeOverride(name = "drttecnico1", column = @Column(name = "DRTTECNICO1", length = 6)),
			@AttributeOverride(name = "drttecnico2", column = @Column(name = "DRTTECNICO2", length = 6)),
			@AttributeOverride(name = "drtresponsa", column = @Column(name = "DRTRESPONSA", length = 6)),
			@AttributeOverride(name = "cdacoes", column = @Column(name = "CDACOES", length = 6)),
			@AttributeOverride(name = "cdcausas", column = @Column(name = "CDCAUSAS", length = 6)),
			@AttributeOverride(name = "cdjustparada", column = @Column(name = "CDJUSTPARADA", length = 6)) })
	public IjlogcorrreqId getId() {
		return this.id;
	}

	public void setId(IjlogcorrreqId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DRTRESPONSA", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByDrtresponsa() {
		return this.ijtbusuByDrtresponsa;
	}

	public void setIjtbusuByDrtresponsa(Ijtbusu ijtbusuByDrtresponsa) {
		this.ijtbusuByDrtresponsa = ijtbusuByDrtresponsa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DRTTECNICO2", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByDrttecnico2() {
		return this.ijtbusuByDrttecnico2;
	}

	public void setIjtbusuByDrttecnico2(Ijtbusu ijtbusuByDrttecnico2) {
		this.ijtbusuByDrttecnico2 = ijtbusuByDrttecnico2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DRTTECNICO1", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByDrttecnico1() {
		return this.ijtbusuByDrttecnico1;
	}

	public void setIjtbusuByDrttecnico1(Ijtbusu ijtbusuByDrttecnico1) {
		this.ijtbusuByDrttecnico1 = ijtbusuByDrttecnico1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPARADA", insertable = false, updatable = false)
	public Ijtbpar getIjtbpar() {
		return this.ijtbpar;
	}

	public void setIjtbpar(Ijtbpar ijtbpar) {
		this.ijtbpar = ijtbpar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCAUSAS", insertable = false, updatable = false)
	public Ijtbcau getIjtbcau() {
		return this.ijtbcau;
	}

	public void setIjtbcau(Ijtbcau ijtbcau) {
		this.ijtbcau = ijtbcau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDJUSTPARADA", insertable = false, updatable = false)
	public Ijtbjup getIjtbjup() {
		return this.ijtbjup;
	}

	public void setIjtbjup(Ijtbjup ijtbjup) {
		this.ijtbjup = ijtbjup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDACOES", insertable = false, updatable = false)
	public Ijtbaco getIjtbaco() {
		return this.ijtbaco;
	}

	public void setIjtbaco(Ijtbaco ijtbaco) {
		this.ijtbaco = ijtbaco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIO", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuario() {
		return this.ijtbusuByCdusuario;
	}

	public void setIjtbusuByCdusuario(Ijtbusu ijtbusuByCdusuario) {
		this.ijtbusuByCdusuario = ijtbusuByCdusuario;
	}

}
