package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijlogavulsos generated by hbm2java
 */
@Entity
@Table(name = "IJLOGAVULSOS")
public class Ijlogavulsos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7627336057224227417L;
	private IjlogavulsosId id;

	public Ijlogavulsos() {
	}

	public Ijlogavulsos(IjlogavulsosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthrocorrencia", column = @Column(name = "DTHROCORRENCIA", nullable = false, length = 7)),
			@AttributeOverride(name = "cdusuario", column = @Column(name = "CDUSUARIO", nullable = false, length = 6)),
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", length = 4)),
			@AttributeOverride(name = "dtreferenciaturno", column = @Column(name = "DTREFERENCIATURNO", length = 7)),
			@AttributeOverride(name = "cdturno", column = @Column(name = "CDTURNO", length = 6)),
			@AttributeOverride(name = "iniciorealop", column = @Column(name = "INICIOREALOP", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "injecoes", column = @Column(name = "INJECOES", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "paradas", column = @Column(name = "PARADAS", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "refugos", column = @Column(name = "REFUGOS", nullable = false, precision = 22, scale = 0)) })
	public IjlogavulsosId getId() {
		return this.id;
	}

	public void setId(IjlogavulsosId id) {
		this.id = id;
	}

}
