package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijmanutexec generated by hbm2java
 */
@Entity
@Table(name = "IJMANUTEXEC")
public class Ijmanutexec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3489217032751542206L;
	private IjmanutexecId id;
	private Ijtbusu ijtbusuByCdusuiniexec;
	private Ijmanuttarefa ijmanuttarefaByIdtarefachklstpai;
	private Ijtbusu ijtbusuByCdusufimexec;
	private Ijmanutchklst ijmanutchklst;
	private Ijmanut ijmanut;
	private Ijmanuttarefa ijmanuttarefaByIdtarefachklst;
	private Ijmanuttarefa ijmanuttarefaByIdtarefaavulsa;
	private Character stchklstfilhos;
	private Character stchklstobrig;
	private String dstarefa;
	private BigDecimal nivel;
	private Date dtiniexec;
	private Date dtfimexec;
	private BigDecimal tpexec;
	private Double qtdhrs;
	private Double vlrhrs;
	private Double custototal;
	private BigDecimal situacao;
	private String observacao;
	private String idrecurso;
	private String tprecurso;
	private Set<Ijmanutexectec> ijmanutexectecs = new HashSet<Ijmanutexectec>(0);

	public Ijmanutexec() {
	}

	public Ijmanutexec(IjmanutexecId id, Ijmanut ijmanut, BigDecimal nivel,
			String idrecurso, String tprecurso) {
		this.id = id;
		this.ijmanut = ijmanut;
		this.nivel = nivel;
		this.idrecurso = idrecurso;
		this.tprecurso = tprecurso;
	}

	public Ijmanutexec(IjmanutexecId id, Ijtbusu ijtbusuByCdusuiniexec,
			Ijmanuttarefa ijmanuttarefaByIdtarefachklstpai,
			Ijtbusu ijtbusuByCdusufimexec, Ijmanutchklst ijmanutchklst,
			Ijmanut ijmanut, Ijmanuttarefa ijmanuttarefaByIdtarefachklst,
			Ijmanuttarefa ijmanuttarefaByIdtarefaavulsa,
			Character stchklstfilhos, Character stchklstobrig, String dstarefa,
			BigDecimal nivel, Date dtiniexec, Date dtfimexec,
			BigDecimal tpexec, Double qtdhrs, Double vlrhrs, Double custototal,
			BigDecimal situacao, String observacao, String idrecurso,
			String tprecurso, Set<Ijmanutexectec> ijmanutexectecs) {
		this.id = id;
		this.ijtbusuByCdusuiniexec = ijtbusuByCdusuiniexec;
		this.ijmanuttarefaByIdtarefachklstpai = ijmanuttarefaByIdtarefachklstpai;
		this.ijtbusuByCdusufimexec = ijtbusuByCdusufimexec;
		this.ijmanutchklst = ijmanutchklst;
		this.ijmanut = ijmanut;
		this.ijmanuttarefaByIdtarefachklst = ijmanuttarefaByIdtarefachklst;
		this.ijmanuttarefaByIdtarefaavulsa = ijmanuttarefaByIdtarefaavulsa;
		this.stchklstfilhos = stchklstfilhos;
		this.stchklstobrig = stchklstobrig;
		this.dstarefa = dstarefa;
		this.nivel = nivel;
		this.dtiniexec = dtiniexec;
		this.dtfimexec = dtfimexec;
		this.tpexec = tpexec;
		this.qtdhrs = qtdhrs;
		this.vlrhrs = vlrhrs;
		this.custototal = custototal;
		this.situacao = situacao;
		this.observacao = observacao;
		this.idrecurso = idrecurso;
		this.tprecurso = tprecurso;
		this.ijmanutexectecs = ijmanutexectecs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nros", column = @Column(name = "NROS", nullable = false, length = 12)),
			@AttributeOverride(name = "seqitem", column = @Column(name = "SEQITEM", nullable = false, precision = 126, scale = 0)) })
	public IjmanutexecId getId() {
		return this.id;
	}

	public void setId(IjmanutexecId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUINIEXEC")
	public Ijtbusu getIjtbusuByCdusuiniexec() {
		return this.ijtbusuByCdusuiniexec;
	}

	public void setIjtbusuByCdusuiniexec(Ijtbusu ijtbusuByCdusuiniexec) {
		this.ijtbusuByCdusuiniexec = ijtbusuByCdusuiniexec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTAREFACHKLSTPAI")
	public Ijmanuttarefa getIjmanuttarefaByIdtarefachklstpai() {
		return this.ijmanuttarefaByIdtarefachklstpai;
	}

	public void setIjmanuttarefaByIdtarefachklstpai(
			Ijmanuttarefa ijmanuttarefaByIdtarefachklstpai) {
		this.ijmanuttarefaByIdtarefachklstpai = ijmanuttarefaByIdtarefachklstpai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUFIMEXEC")
	public Ijtbusu getIjtbusuByCdusufimexec() {
		return this.ijtbusuByCdusufimexec;
	}

	public void setIjtbusuByCdusufimexec(Ijtbusu ijtbusuByCdusufimexec) {
		this.ijtbusuByCdusufimexec = ijtbusuByCdusufimexec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCHKLST")
	public Ijmanutchklst getIjmanutchklst() {
		return this.ijmanutchklst;
	}

	public void setIjmanutchklst(Ijmanutchklst ijmanutchklst) {
		this.ijmanutchklst = ijmanutchklst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROS", nullable = false, insertable = false, updatable = false)
	public Ijmanut getIjmanut() {
		return this.ijmanut;
	}

	public void setIjmanut(Ijmanut ijmanut) {
		this.ijmanut = ijmanut;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTAREFACHKLST")
	public Ijmanuttarefa getIjmanuttarefaByIdtarefachklst() {
		return this.ijmanuttarefaByIdtarefachklst;
	}

	public void setIjmanuttarefaByIdtarefachklst(
			Ijmanuttarefa ijmanuttarefaByIdtarefachklst) {
		this.ijmanuttarefaByIdtarefachklst = ijmanuttarefaByIdtarefachklst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTAREFAAVULSA")
	public Ijmanuttarefa getIjmanuttarefaByIdtarefaavulsa() {
		return this.ijmanuttarefaByIdtarefaavulsa;
	}

	public void setIjmanuttarefaByIdtarefaavulsa(
			Ijmanuttarefa ijmanuttarefaByIdtarefaavulsa) {
		this.ijmanuttarefaByIdtarefaavulsa = ijmanuttarefaByIdtarefaavulsa;
	}

	@Column(name = "STCHKLSTFILHOS", length = 1)
	public Character getStchklstfilhos() {
		return this.stchklstfilhos;
	}

	public void setStchklstfilhos(Character stchklstfilhos) {
		this.stchklstfilhos = stchklstfilhos;
	}

	@Column(name = "STCHKLSTOBRIG", length = 1)
	public Character getStchklstobrig() {
		return this.stchklstobrig;
	}

	public void setStchklstobrig(Character stchklstobrig) {
		this.stchklstobrig = stchklstobrig;
	}

	@Column(name = "DSTAREFA")
	public String getDstarefa() {
		return this.dstarefa;
	}

	public void setDstarefa(String dstarefa) {
		this.dstarefa = dstarefa;
	}

	@Column(name = "NIVEL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNivel() {
		return this.nivel;
	}

	public void setNivel(BigDecimal nivel) {
		this.nivel = nivel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINIEXEC", length = 7)
	public Date getDtiniexec() {
		return this.dtiniexec;
	}

	public void setDtiniexec(Date dtiniexec) {
		this.dtiniexec = dtiniexec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTFIMEXEC", length = 7)
	public Date getDtfimexec() {
		return this.dtfimexec;
	}

	public void setDtfimexec(Date dtfimexec) {
		this.dtfimexec = dtfimexec;
	}

	@Column(name = "TPEXEC", precision = 22, scale = 0)
	public BigDecimal getTpexec() {
		return this.tpexec;
	}

	public void setTpexec(BigDecimal tpexec) {
		this.tpexec = tpexec;
	}

	@Column(name = "QTDHRS", precision = 126, scale = 0)
	public Double getQtdhrs() {
		return this.qtdhrs;
	}

	public void setQtdhrs(Double qtdhrs) {
		this.qtdhrs = qtdhrs;
	}

	@Column(name = "VLRHRS", precision = 126, scale = 0)
	public Double getVlrhrs() {
		return this.vlrhrs;
	}

	public void setVlrhrs(Double vlrhrs) {
		this.vlrhrs = vlrhrs;
	}

	@Column(name = "CUSTOTOTAL", precision = 126, scale = 0)
	public Double getCustototal() {
		return this.custototal;
	}

	public void setCustototal(Double custototal) {
		this.custototal = custototal;
	}

	@Column(name = "SITUACAO", precision = 22, scale = 0)
	public BigDecimal getSituacao() {
		return this.situacao;
	}

	public void setSituacao(BigDecimal situacao) {
		this.situacao = situacao;
	}

	@Column(name = "OBSERVACAO")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "IDRECURSO", nullable = false, length = 6)
	public String getIdrecurso() {
		return this.idrecurso;
	}

	public void setIdrecurso(String idrecurso) {
		this.idrecurso = idrecurso;
	}

	@Column(name = "TPRECURSO", nullable = false, length = 2)
	public String getTprecurso() {
		return this.tprecurso;
	}

	public void setTprecurso(String tprecurso) {
		this.tprecurso = tprecurso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmanutexec")
	public Set<Ijmanutexectec> getIjmanutexectecs() {
		return this.ijmanutexectecs;
	}

	public void setIjmanutexectecs(Set<Ijmanutexectec> ijmanutexectecs) {
		this.ijmanutexectecs = ijmanutexectecs;
	}

}
