package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijmatrizsetuplog generated by hbm2java
 */
@Entity
@Table(name = "IJMATRIZSETUPLOG")
public class Ijmatrizsetuplog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7716203353681588100L;
	private IjmatrizsetuplogId id;

	public Ijmatrizsetuplog() {
	}

	public Ijmatrizsetuplog(IjmatrizsetuplogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdmoldesai", column = @Column(name = "CDMOLDESAI", nullable = false, length = 6)),
			@AttributeOverride(name = "cdmoldeentra", column = @Column(name = "CDMOLDEENTRA", nullable = false, length = 6)),
			@AttributeOverride(name = "temposetup", column = @Column(name = "TEMPOSETUP", precision = 126, scale = 0)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", nullable = false, length = 6)) })
	public IjmatrizsetuplogId getId() {
		return this.id;
	}

	public void setId(IjmatrizsetuplogId id) {
		this.id = id;
	}

}
