package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijmanuttarefa generated by hbm2java
 */
@Entity
@Table(name = "IJMANUTTAREFA", uniqueConstraints = @UniqueConstraint(columnNames = "CDTAREFA"))
public class Ijmanuttarefa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 944537815581206384L;
	private String idtarefa;
	private Ijclasstarefamanut ijclasstarefamanut;
	private String cdtarefa;
	private String dstarefa;
	private Character sttarefa;
	private Set<Ijmanutchklstdet> ijmanutchklstdetsForIdtarefapai = new HashSet<Ijmanutchklstdet>(
			0);
	private Set<Ijmanutexec> ijmanutexecsForIdtarefaavulsa = new HashSet<Ijmanutexec>(
			0);
	private Set<Ijmanutchklstdet> ijmanutchklstdetsForIdtarefa = new HashSet<Ijmanutchklstdet>(
			0);
	private Set<Ijmanutexec> ijmanutexecsForIdtarefachklstpai = new HashSet<Ijmanutexec>(
			0);
	private Set<Ijmanutexec> ijmanutexecsForIdtarefachklst = new HashSet<Ijmanutexec>(
			0);

	public Ijmanuttarefa() {
	}

	public Ijmanuttarefa(String idtarefa,
			Ijclasstarefamanut ijclasstarefamanut, String cdtarefa,
			String dstarefa) {
		this.idtarefa = idtarefa;
		this.ijclasstarefamanut = ijclasstarefamanut;
		this.cdtarefa = cdtarefa;
		this.dstarefa = dstarefa;
	}

	public Ijmanuttarefa(String idtarefa,
			Ijclasstarefamanut ijclasstarefamanut, String cdtarefa,
			String dstarefa, Character sttarefa,
			Set<Ijmanutchklstdet> ijmanutchklstdetsForIdtarefapai,
			Set<Ijmanutexec> ijmanutexecsForIdtarefaavulsa,
			Set<Ijmanutchklstdet> ijmanutchklstdetsForIdtarefa,
			Set<Ijmanutexec> ijmanutexecsForIdtarefachklstpai,
			Set<Ijmanutexec> ijmanutexecsForIdtarefachklst) {
		this.idtarefa = idtarefa;
		this.ijclasstarefamanut = ijclasstarefamanut;
		this.cdtarefa = cdtarefa;
		this.dstarefa = dstarefa;
		this.sttarefa = sttarefa;
		this.ijmanutchklstdetsForIdtarefapai = ijmanutchklstdetsForIdtarefapai;
		this.ijmanutexecsForIdtarefaavulsa = ijmanutexecsForIdtarefaavulsa;
		this.ijmanutchklstdetsForIdtarefa = ijmanutchklstdetsForIdtarefa;
		this.ijmanutexecsForIdtarefachklstpai = ijmanutexecsForIdtarefachklstpai;
		this.ijmanutexecsForIdtarefachklst = ijmanutexecsForIdtarefachklst;
	}

	@Id
	@Column(name = "IDTAREFA", unique = true, nullable = false, length = 15)
	public String getIdtarefa() {
		return this.idtarefa;
	}

	public void setIdtarefa(String idtarefa) {
		this.idtarefa = idtarefa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCLASSTAREFA", nullable = false)
	public Ijclasstarefamanut getIjclasstarefamanut() {
		return this.ijclasstarefamanut;
	}

	public void setIjclasstarefamanut(Ijclasstarefamanut ijclasstarefamanut) {
		this.ijclasstarefamanut = ijclasstarefamanut;
	}

	@Column(name = "CDTAREFA", unique = true, nullable = false, length = 10)
	public String getCdtarefa() {
		return this.cdtarefa;
	}

	public void setCdtarefa(String cdtarefa) {
		this.cdtarefa = cdtarefa;
	}

	@Column(name = "DSTAREFA", nullable = false)
	public String getDstarefa() {
		return this.dstarefa;
	}

	public void setDstarefa(String dstarefa) {
		this.dstarefa = dstarefa;
	}

	@Column(name = "STTAREFA", length = 1)
	public Character getSttarefa() {
		return this.sttarefa;
	}

	public void setSttarefa(Character sttarefa) {
		this.sttarefa = sttarefa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmanuttarefaByIdtarefapai")
	public Set<Ijmanutchklstdet> getIjmanutchklstdetsForIdtarefapai() {
		return this.ijmanutchklstdetsForIdtarefapai;
	}

	public void setIjmanutchklstdetsForIdtarefapai(
			Set<Ijmanutchklstdet> ijmanutchklstdetsForIdtarefapai) {
		this.ijmanutchklstdetsForIdtarefapai = ijmanutchklstdetsForIdtarefapai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmanuttarefaByIdtarefaavulsa")
	public Set<Ijmanutexec> getIjmanutexecsForIdtarefaavulsa() {
		return this.ijmanutexecsForIdtarefaavulsa;
	}

	public void setIjmanutexecsForIdtarefaavulsa(
			Set<Ijmanutexec> ijmanutexecsForIdtarefaavulsa) {
		this.ijmanutexecsForIdtarefaavulsa = ijmanutexecsForIdtarefaavulsa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmanuttarefaByIdtarefa")
	public Set<Ijmanutchklstdet> getIjmanutchklstdetsForIdtarefa() {
		return this.ijmanutchklstdetsForIdtarefa;
	}

	public void setIjmanutchklstdetsForIdtarefa(
			Set<Ijmanutchklstdet> ijmanutchklstdetsForIdtarefa) {
		this.ijmanutchklstdetsForIdtarefa = ijmanutchklstdetsForIdtarefa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmanuttarefaByIdtarefachklstpai")
	public Set<Ijmanutexec> getIjmanutexecsForIdtarefachklstpai() {
		return this.ijmanutexecsForIdtarefachklstpai;
	}

	public void setIjmanutexecsForIdtarefachklstpai(
			Set<Ijmanutexec> ijmanutexecsForIdtarefachklstpai) {
		this.ijmanutexecsForIdtarefachklstpai = ijmanutexecsForIdtarefachklstpai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmanuttarefaByIdtarefachklst")
	public Set<Ijmanutexec> getIjmanutexecsForIdtarefachklst() {
		return this.ijmanutexecsForIdtarefachklst;
	}

	public void setIjmanutexecsForIdtarefachklst(
			Set<Ijmanutexec> ijmanutexecsForIdtarefachklst) {
		this.ijmanutexecsForIdtarefachklst = ijmanutexecsForIdtarefachklst;
	}

}
