package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjmatrizsetupId generated by hbm2java
 */
@Embeddable
public class IjmatrizsetupId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4758600538907465059L;
	private String cdinjetora;
	private String cdmoldesai;
	private String cdmoldeentra;

	public IjmatrizsetupId() {
	}

	public IjmatrizsetupId(String cdinjetora, String cdmoldesai,
			String cdmoldeentra) {
		this.cdinjetora = cdinjetora;
		this.cdmoldesai = cdmoldesai;
		this.cdmoldeentra = cdmoldeentra;
	}

	@Column(name = "CDINJETORA", nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Column(name = "CDMOLDESAI", nullable = false, length = 6)
	public String getCdmoldesai() {
		return this.cdmoldesai;
	}

	public void setCdmoldesai(String cdmoldesai) {
		this.cdmoldesai = cdmoldesai;
	}

	@Column(name = "CDMOLDEENTRA", nullable = false, length = 6)
	public String getCdmoldeentra() {
		return this.cdmoldeentra;
	}

	public void setCdmoldeentra(String cdmoldeentra) {
		this.cdmoldeentra = cdmoldeentra;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjmatrizsetupId))
			return false;
		IjmatrizsetupId castOther = (IjmatrizsetupId) other;

		return ((this.getCdinjetora() == castOther.getCdinjetora()) || (this
				.getCdinjetora() != null && castOther.getCdinjetora() != null && this
				.getCdinjetora().equals(castOther.getCdinjetora())))
				&& ((this.getCdmoldesai() == castOther.getCdmoldesai()) || (this
						.getCdmoldesai() != null
						&& castOther.getCdmoldesai() != null && this
						.getCdmoldesai().equals(castOther.getCdmoldesai())))
				&& ((this.getCdmoldeentra() == castOther.getCdmoldeentra()) || (this
						.getCdmoldeentra() != null
						&& castOther.getCdmoldeentra() != null && this
						.getCdmoldeentra().equals(castOther.getCdmoldeentra())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdinjetora() == null ? 0 : this.getCdinjetora()
						.hashCode());
		result = 37
				* result
				+ (getCdmoldesai() == null ? 0 : this.getCdmoldesai()
						.hashCode());
		result = 37
				* result
				+ (getCdmoldeentra() == null ? 0 : this.getCdmoldeentra()
						.hashCode());
		return result;
	}

}
