package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijmaqevt generated by hbm2java
 */
@Entity
@Table(name = "IJMAQEVT")
public class Ijmaqevt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4835949949699899327L;
	private IjmaqevtId id;

	public Ijmaqevt() {
	}

	public Ijmaqevt(IjmaqevtId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrinievento", column = @Column(name = "DTHRINIEVENTO", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrfimevento", column = @Column(name = "DTHRFIMEVENTO", nullable = false, length = 7)),
			@AttributeOverride(name = "evento", column = @Column(name = "EVENTO", nullable = false, length = 1)),
			@AttributeOverride(name = "origem", column = @Column(name = "ORIGEM", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuario", column = @Column(name = "CDUSUARIO", length = 6)) })
	public IjmaqevtId getId() {
		return this.id;
	}

	public void setId(IjmaqevtId id) {
		this.id = id;
	}

}
