package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijmaqinievt generated by hbm2java
 */
@Entity
@Table(name = "IJMAQINIEVT")
public class Ijmaqinievt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1768528828929752753L;
	private String cdinjetora;
	private Date dthrini;
	private Date dthrfim;

	public Ijmaqinievt() {
	}

	public Ijmaqinievt(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	public Ijmaqinievt(String cdinjetora, Date dthrini, Date dthrfim) {
		this.cdinjetora = cdinjetora;
		this.dthrini = dthrini;
		this.dthrfim = dthrfim;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRINI", length = 7)
	public Date getDthrini() {
		return this.dthrini;
	}

	public void setDthrini(Date dthrini) {
		this.dthrini = dthrini;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFIM", length = 7)
	public Date getDthrfim() {
		return this.dthrfim;
	}

	public void setDthrfim(Date dthrfim) {
		this.dthrfim = dthrfim;
	}

}
