package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijmanutmateriais generated by hbm2java
 */
@Entity
@Table(name = "IJMANUTMATERIAIS")
public class Ijmanutmateriais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5064026300724449826L;
	private IjmanutmateriaisId id;
	private Ijmanut ijmanut;
	private String dsmaterial;
	private String unidmedida;
	private double precounit;
	private double qtde;
	private double precototal;
	private String nrnota;
	private String nmfornecec;
	private String observacao;

	public Ijmanutmateriais() {
	}

	public Ijmanutmateriais(IjmanutmateriaisId id, Ijmanut ijmanut,
			String dsmaterial, String unidmedida, double precounit,
			double qtde, double precototal, String nrnota, String nmfornecec,
			String observacao) {
		this.id = id;
		this.ijmanut = ijmanut;
		this.dsmaterial = dsmaterial;
		this.unidmedida = unidmedida;
		this.precounit = precounit;
		this.qtde = qtde;
		this.precototal = precototal;
		this.nrnota = nrnota;
		this.nmfornecec = nmfornecec;
		this.observacao = observacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nros", column = @Column(name = "NROS", nullable = false, length = 12)),
			@AttributeOverride(name = "idregistro", column = @Column(name = "IDREGISTRO", nullable = false, precision = 126, scale = 0)) })
	public IjmanutmateriaisId getId() {
		return this.id;
	}

	public void setId(IjmanutmateriaisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROS", nullable = false, insertable = false, updatable = false)
	public Ijmanut getIjmanut() {
		return this.ijmanut;
	}

	public void setIjmanut(Ijmanut ijmanut) {
		this.ijmanut = ijmanut;
	}

	@Column(name = "DSMATERIAL", nullable = false, length = 20)
	public String getDsmaterial() {
		return this.dsmaterial;
	}

	public void setDsmaterial(String dsmaterial) {
		this.dsmaterial = dsmaterial;
	}

	@Column(name = "UNIDMEDIDA", nullable = false, length = 10)
	public String getUnidmedida() {
		return this.unidmedida;
	}

	public void setUnidmedida(String unidmedida) {
		this.unidmedida = unidmedida;
	}

	@Column(name = "PRECOUNIT", nullable = false, precision = 126, scale = 0)
	public double getPrecounit() {
		return this.precounit;
	}

	public void setPrecounit(double precounit) {
		this.precounit = precounit;
	}

	@Column(name = "QTDE", nullable = false, precision = 126, scale = 0)
	public double getQtde() {
		return this.qtde;
	}

	public void setQtde(double qtde) {
		this.qtde = qtde;
	}

	@Column(name = "PRECOTOTAL", nullable = false, precision = 126, scale = 0)
	public double getPrecototal() {
		return this.precototal;
	}

	public void setPrecototal(double precototal) {
		this.precototal = precototal;
	}

	@Column(name = "NRNOTA", nullable = false, length = 10)
	public String getNrnota() {
		return this.nrnota;
	}

	public void setNrnota(String nrnota) {
		this.nrnota = nrnota;
	}

	@Column(name = "NMFORNECEC", nullable = false, length = 40)
	public String getNmfornecec() {
		return this.nmfornecec;
	}

	public void setNmfornecec(String nmfornecec) {
		this.nmfornecec = nmfornecec;
	}

	@Column(name = "OBSERVACAO", nullable = false)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

}
