package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijmdoalocmaq generated by hbm2java
 */
@Entity
@Table(name = "IJMDOALOCMAQ")
public class Ijmdoalocmaq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9044894423205174772L;
	private String cdproduto;
	private Ijtbpro ijtbpro;
	private char sttodasmaquinas;

	public Ijmdoalocmaq() {
	}

	public Ijmdoalocmaq(String cdproduto, Ijtbpro ijtbpro, char sttodasmaquinas) {
		this.cdproduto = cdproduto;
		this.ijtbpro = ijtbpro;
		this.sttodasmaquinas = sttodasmaquinas;
	}

	@Id
	@Column(name = "CDPRODUTO", unique = true, nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "STTODASMAQUINAS", nullable = false, length = 1)
	public char getSttodasmaquinas() {
		return this.sttodasmaquinas;
	}

	public void setSttodasmaquinas(char sttodasmaquinas) {
		this.sttodasmaquinas = sttodasmaquinas;
	}

}
