package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ijmdoaloc generated by hbm2java
 */
@Entity
@Table(name = "IJMDOALOC", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CDPRODUTO", "CDINJETORA", "DTHRINIVAL" }))
public class Ijmdoaloc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 233174607852444562L;
	private String idmdoaloc;
	private Ijtbinj ijtbinj;
	private Ijtbpro ijtbpro;
	private Ijtbusu ijtbusu;
	private Date dthrinival;
	private Date dthrfval;
	private Set<Ijmdoalocop> ijmdoalocops = new HashSet<Ijmdoalocop>(0);
	private Set<Ijmdoalocdet> ijmdoalocdets = new HashSet<Ijmdoalocdet>(0);

	public Ijmdoaloc() {
	}

	public Ijmdoaloc(String idmdoaloc, Ijtbinj ijtbinj, Ijtbpro ijtbpro,
			Ijtbusu ijtbusu, Date dthrinival) {
		this.idmdoaloc = idmdoaloc;
		this.ijtbinj = ijtbinj;
		this.ijtbpro = ijtbpro;
		this.ijtbusu = ijtbusu;
		this.dthrinival = dthrinival;
	}

	public Ijmdoaloc(String idmdoaloc, Ijtbinj ijtbinj, Ijtbpro ijtbpro,
			Ijtbusu ijtbusu, Date dthrinival, Date dthrfval,
			Set<Ijmdoalocop> ijmdoalocops, Set<Ijmdoalocdet> ijmdoalocdets) {
		this.idmdoaloc = idmdoaloc;
		this.ijtbinj = ijtbinj;
		this.ijtbpro = ijtbpro;
		this.ijtbusu = ijtbusu;
		this.dthrinival = dthrinival;
		this.dthrfval = dthrfval;
		this.ijmdoalocops = ijmdoalocops;
		this.ijmdoalocdets = ijmdoalocdets;
	}

	@Id
	@Column(name = "IDMDOALOC", unique = true, nullable = false, length = 12)
	public String getIdmdoaloc() {
		return this.idmdoaloc;
	}

	public void setIdmdoaloc(String idmdoaloc) {
		this.idmdoaloc = idmdoaloc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIO", nullable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRINIVAL", nullable = false, length = 7)
	public Date getDthrinival() {
		return this.dthrinival;
	}

	public void setDthrinival(Date dthrinival) {
		this.dthrinival = dthrinival;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFVAL", length = 7)
	public Date getDthrfval() {
		return this.dthrfval;
	}

	public void setDthrfval(Date dthrfval) {
		this.dthrfval = dthrfval;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmdoaloc")
	public Set<Ijmdoalocop> getIjmdoalocops() {
		return this.ijmdoalocops;
	}

	public void setIjmdoalocops(Set<Ijmdoalocop> ijmdoalocops) {
		this.ijmdoalocops = ijmdoalocops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmdoaloc")
	public Set<Ijmdoalocdet> getIjmdoalocdets() {
		return this.ijmdoalocdets;
	}

	public void setIjmdoalocdets(Set<Ijmdoalocdet> ijmdoalocdets) {
		this.ijmdoalocdets = ijmdoalocdets;
	}

}
