package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijmolproautorizpro generated by hbm2java
 */
@Entity
@Table(name = "IJMOLPROAUTORIZPRO")
public class Ijmolproautorizpro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8154565496325047889L;
	private IjmolproautorizproId id;
	private Ijtbpro ijtbpro;
	private Ijmolproautorizmod ijmolproautorizmod;
	private char cdidentificacao;
	private double qtcavidades;
	private double qtcavativas;
	private double pliquidomedio;
	private double pbrutomedio;

	public Ijmolproautorizpro() {
	}

	public Ijmolproautorizpro(IjmolproautorizproId id, Ijtbpro ijtbpro,
			Ijmolproautorizmod ijmolproautorizmod, char cdidentificacao,
			double qtcavidades, double qtcavativas, double pliquidomedio,
			double pbrutomedio) {
		this.id = id;
		this.ijtbpro = ijtbpro;
		this.ijmolproautorizmod = ijmolproautorizmod;
		this.cdidentificacao = cdidentificacao;
		this.qtcavidades = qtcavidades;
		this.qtcavativas = qtcavativas;
		this.pliquidomedio = pliquidomedio;
		this.pbrutomedio = pbrutomedio;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrsolicmodificest", column = @Column(name = "NRSOLICMODIFICEST", nullable = false, length = 12)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)) })
	public IjmolproautorizproId getId() {
		return this.id;
	}

	public void setId(IjmolproautorizproId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NRSOLICMODIFICEST", nullable = false, insertable = false, updatable = false)
	public Ijmolproautorizmod getIjmolproautorizmod() {
		return this.ijmolproautorizmod;
	}

	public void setIjmolproautorizmod(Ijmolproautorizmod ijmolproautorizmod) {
		this.ijmolproautorizmod = ijmolproautorizmod;
	}

	@Column(name = "CDIDENTIFICACAO", nullable = false, length = 1)
	public char getCdidentificacao() {
		return this.cdidentificacao;
	}

	public void setCdidentificacao(char cdidentificacao) {
		this.cdidentificacao = cdidentificacao;
	}

	@Column(name = "QTCAVIDADES", nullable = false, precision = 126, scale = 0)
	public double getQtcavidades() {
		return this.qtcavidades;
	}

	public void setQtcavidades(double qtcavidades) {
		this.qtcavidades = qtcavidades;
	}

	@Column(name = "QTCAVATIVAS", nullable = false, precision = 126, scale = 0)
	public double getQtcavativas() {
		return this.qtcavativas;
	}

	public void setQtcavativas(double qtcavativas) {
		this.qtcavativas = qtcavativas;
	}

	@Column(name = "PLIQUIDOMEDIO", nullable = false, precision = 126, scale = 0)
	public double getPliquidomedio() {
		return this.pliquidomedio;
	}

	public void setPliquidomedio(double pliquidomedio) {
		this.pliquidomedio = pliquidomedio;
	}

	@Column(name = "PBRUTOMEDIO", nullable = false, precision = 126, scale = 0)
	public double getPbrutomedio() {
		return this.pbrutomedio;
	}

	public void setPbrutomedio(double pbrutomedio) {
		this.pbrutomedio = pbrutomedio;
	}

}
