package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijmolproautorizmod generated by hbm2java
 */
@Entity
@Table(name = "IJMOLPROAUTORIZMOD")
public class Ijmolproautorizmod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8523753611130909079L;
	private String nrsolicmodificest;
	private Ijestmol ijestmol;
	private Ijtbusu ijtbusu;
	private Ijtbjuscav ijtbjuscav;
	private Date dthrsolicmodific;
	private char stsolicmodific;
	private Date dthrstsolic;
	private Set<Ijmolproautorizpro> ijmolproautorizpros = new HashSet<Ijmolproautorizpro>(
			0);
	private Set<Ijmolproautorizusu> ijmolproautorizusus = new HashSet<Ijmolproautorizusu>(
			0);

	public Ijmolproautorizmod() {
	}

	public Ijmolproautorizmod(String nrsolicmodificest, Ijestmol ijestmol,
			Ijtbusu ijtbusu, Date dthrsolicmodific, char stsolicmodific,
			Date dthrstsolic) {
		this.nrsolicmodificest = nrsolicmodificest;
		this.ijestmol = ijestmol;
		this.ijtbusu = ijtbusu;
		this.dthrsolicmodific = dthrsolicmodific;
		this.stsolicmodific = stsolicmodific;
		this.dthrstsolic = dthrstsolic;
	}

	public Ijmolproautorizmod(String nrsolicmodificest, Ijestmol ijestmol,
			Ijtbusu ijtbusu, Ijtbjuscav ijtbjuscav, Date dthrsolicmodific,
			char stsolicmodific, Date dthrstsolic,
			Set<Ijmolproautorizpro> ijmolproautorizpros,
			Set<Ijmolproautorizusu> ijmolproautorizusus) {
		this.nrsolicmodificest = nrsolicmodificest;
		this.ijestmol = ijestmol;
		this.ijtbusu = ijtbusu;
		this.ijtbjuscav = ijtbjuscav;
		this.dthrsolicmodific = dthrsolicmodific;
		this.stsolicmodific = stsolicmodific;
		this.dthrstsolic = dthrstsolic;
		this.ijmolproautorizpros = ijmolproautorizpros;
		this.ijmolproautorizusus = ijmolproautorizusus;
	}

	@Id
	@Column(name = "NRSOLICMODIFICEST", unique = true, nullable = false, length = 12)
	public String getNrsolicmodificest() {
		return this.nrsolicmodificest;
	}

	public void setNrsolicmodificest(String nrsolicmodificest) {
		this.nrsolicmodificest = nrsolicmodificest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false) })
	public Ijestmol getIjestmol() {
		return this.ijestmol;
	}

	public void setIjestmol(Ijestmol ijestmol) {
		this.ijestmol = ijestmol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUSOLIC", nullable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDJUSCAV")
	public Ijtbjuscav getIjtbjuscav() {
		return this.ijtbjuscav;
	}

	public void setIjtbjuscav(Ijtbjuscav ijtbjuscav) {
		this.ijtbjuscav = ijtbjuscav;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRSOLICMODIFIC", nullable = false, length = 7)
	public Date getDthrsolicmodific() {
		return this.dthrsolicmodific;
	}

	public void setDthrsolicmodific(Date dthrsolicmodific) {
		this.dthrsolicmodific = dthrsolicmodific;
	}

	@Column(name = "STSOLICMODIFIC", nullable = false, length = 1)
	public char getStsolicmodific() {
		return this.stsolicmodific;
	}

	public void setStsolicmodific(char stsolicmodific) {
		this.stsolicmodific = stsolicmodific;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRSTSOLIC", nullable = false, length = 7)
	public Date getDthrstsolic() {
		return this.dthrstsolic;
	}

	public void setDthrstsolic(Date dthrstsolic) {
		this.dthrstsolic = dthrstsolic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmolproautorizmod")
	public Set<Ijmolproautorizpro> getIjmolproautorizpros() {
		return this.ijmolproautorizpros;
	}

	public void setIjmolproautorizpros(
			Set<Ijmolproautorizpro> ijmolproautorizpros) {
		this.ijmolproautorizpros = ijmolproautorizpros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijmolproautorizmod")
	public Set<Ijmolproautorizusu> getIjmolproautorizusus() {
		return this.ijmolproautorizusus;
	}

	public void setIjmolproautorizusus(
			Set<Ijmolproautorizusu> ijmolproautorizusus) {
		this.ijmolproautorizusus = ijmolproautorizusus;
	}

}
