package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijmolproidcav generated by hbm2java
 */
@Entity
@Table(name = "IJMOLPROIDCAV", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CDMOLDE", "CDESTRUTURA", "DTHRIVAL", "IDCAVIDADE" }))
public class Ijmolproidcav implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9099209750736116186L;
	private IjmolproidcavId id;
	private Ijtbmolidcav ijtbmolidcav;
	private Ijmolpro ijmolpro;

	public Ijmolproidcav() {
	}

	public Ijmolproidcav(IjmolproidcavId id, Ijtbmolidcav ijtbmolidcav,
			Ijmolpro ijmolpro) {
		this.id = id;
		this.ijtbmolidcav = ijtbmolidcav;
		this.ijmolpro = ijmolpro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "dthrival", column = @Column(name = "DTHRIVAL", nullable = false, length = 7)),
			@AttributeOverride(name = "idcavidade", column = @Column(name = "IDCAVIDADE", nullable = false, precision = 126, scale = 0)) })
	public IjmolproidcavId getId() {
		return this.id;
	}

	public void setId(IjmolproidcavId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCAVIDADE", nullable = false, insertable = false, updatable = false)
	public Ijtbmolidcav getIjtbmolidcav() {
		return this.ijtbmolidcav;
	}

	public void setIjtbmolidcav(Ijtbmolidcav ijtbmolidcav) {
		this.ijtbmolidcav = ijtbmolidcav;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "DTHRIVAL", referencedColumnName = "DTHRIVAL", nullable = false, insertable = false, updatable = false) })
	public Ijmolpro getIjmolpro() {
		return this.ijmolpro;
	}

	public void setIjmolpro(Ijmolpro ijmolpro) {
		this.ijmolpro = ijmolpro;
	}

}
