package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjocorreploteinsId generated by hbm2java
 */
@Embeddable
public class IjocorreploteinsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6118111203796160732L;
	private String cdinjetora;
	private String nrlote;
	private Date dthrreploteinsumo;

	public IjocorreploteinsId() {
	}

	public IjocorreploteinsId(String cdinjetora, String nrlote,
			Date dthrreploteinsumo) {
		this.cdinjetora = cdinjetora;
		this.nrlote = nrlote;
		this.dthrreploteinsumo = dthrreploteinsumo;
	}

	@Column(name = "CDINJETORA", nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Column(name = "NRLOTE", nullable = false, length = 20)
	public String getNrlote() {
		return this.nrlote;
	}

	public void setNrlote(String nrlote) {
		this.nrlote = nrlote;
	}

	@Column(name = "DTHRREPLOTEINSUMO", nullable = false, length = 7)
	public Date getDthrreploteinsumo() {
		return this.dthrreploteinsumo;
	}

	public void setDthrreploteinsumo(Date dthrreploteinsumo) {
		this.dthrreploteinsumo = dthrreploteinsumo;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjocorreploteinsId))
			return false;
		IjocorreploteinsId castOther = (IjocorreploteinsId) other;

		return ((this.getCdinjetora() == castOther.getCdinjetora()) || (this
				.getCdinjetora() != null && castOther.getCdinjetora() != null && this
				.getCdinjetora().equals(castOther.getCdinjetora())))
				&& ((this.getNrlote() == castOther.getNrlote()) || (this
						.getNrlote() != null && castOther.getNrlote() != null && this
						.getNrlote().equals(castOther.getNrlote())))
				&& ((this.getDthrreploteinsumo() == castOther
						.getDthrreploteinsumo()) || (this
						.getDthrreploteinsumo() != null
						&& castOther.getDthrreploteinsumo() != null && this
						.getDthrreploteinsumo().equals(
								castOther.getDthrreploteinsumo())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdinjetora() == null ? 0 : this.getCdinjetora()
						.hashCode());
		result = 37 * result
				+ (getNrlote() == null ? 0 : this.getNrlote().hashCode());
		result = 37
				* result
				+ (getDthrreploteinsumo() == null ? 0 : this
						.getDthrreploteinsumo().hashCode());
		return result;
	}

}
