package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijoplog generated by hbm2java
 */
@Entity
@Table(name = "IJOPLOG")
public class Ijoplog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8982745165423694941L;
	private IjoplogId id;

	public Ijoplog() {
	}

	public Ijoplog(IjoplogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "nrplano", column = @Column(name = "NRPLANO", nullable = false, length = 10)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "nrseq", column = @Column(name = "NRSEQ", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "dthriprevista", column = @Column(name = "DTHRIPREVISTA", nullable = false, length = 7)),
			@AttributeOverride(name = "dthrireal", column = @Column(name = "DTHRIREAL", length = 7)),
			@AttributeOverride(name = "stop", column = @Column(name = "STOP", length = 1)),
			@AttributeOverride(name = "dthrfprevista", column = @Column(name = "DTHRFPREVISTA", length = 7)),
			@AttributeOverride(name = "dthrsaida", column = @Column(name = "DTHRSAIDA", length = 7)),
			@AttributeOverride(name = "dthrpriciclo", column = @Column(name = "DTHRPRICICLO", length = 7)),
			@AttributeOverride(name = "tpordemproducao", column = @Column(name = "TPORDEMPRODUCAO", length = 1)),
			@AttributeOverride(name = "dtentrega", column = @Column(name = "DTENTREGA", length = 7)),
			@AttributeOverride(name = "numsmnentrega", column = @Column(name = "NUMSMNENTREGA", precision = 22, scale = 0)),
			@AttributeOverride(name = "nropcoorp", column = @Column(name = "NROPCOORP", length = 10)),
			@AttributeOverride(name = "tpacabamento", column = @Column(name = "TPACABAMENTO", length = 1)),
			@AttributeOverride(name = "opcritica", column = @Column(name = "OPCRITICA", length = 1)),
			@AttributeOverride(name = "nropestendido", column = @Column(name = "NROPESTENDIDO", nullable = false, length = 25)),
			@AttributeOverride(name = "toleranciaplano", column = @Column(name = "TOLERANCIAPLANO", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", nullable = false, length = 6)) })
	public IjoplogId getId() {
		return this.id;
	}

	public void setId(IjoplogId id) {
		this.id = id;
	}

}
