package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijopagrupada generated by hbm2java
 */
@Entity
@Table(name = "IJOPAGRUPADA")
public class Ijopagrupada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1379729808757020660L;
	private IjopagrupadaId id;
	private Ijop ijop;
	private Ijtbpro ijtbpro;

	public Ijopagrupada() {
	}

	public Ijopagrupada(IjopagrupadaId id, Ijop ijop) {
		this.id = id;
		this.ijop = ijop;
	}

	public Ijopagrupada(IjopagrupadaId id, Ijop ijop, Ijtbpro ijtbpro) {
		this.id = id;
		this.ijop = ijop;
		this.ijtbpro = ijtbpro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "nropagrupada", column = @Column(name = "NROPAGRUPADA", nullable = false, length = 25)) })
	public IjopagrupadaId getId() {
		return this.id;
	}

	public void setId(IjopagrupadaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO")
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

}
