package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijopagrup generated by hbm2java
 */
@Entity
@Table(name = "IJOPAGRUP")
public class Ijopagrup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 826076926521487658L;
	private IjopagrupId id;
	private Ijop ijop;

	public Ijopagrup() {
	}

	public Ijopagrup(IjopagrupId id, Ijop ijop) {
		this.id = id;
		this.ijop = ijop;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "nropagrup", column = @Column(name = "NROPAGRUP", nullable = false, length = 10)) })
	public IjopagrupId getId() {
		return this.id;
	}

	public void setId(IjopagrupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

}
