package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijopcgq generated by hbm2java
 */
@Entity
@Table(name = "IJOPCGQ")
public class Ijopcgq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7561545336881328928L;
	private String nrop;
	private Ijop ijop;
	private Date dtfabricacao;

	public Ijopcgq() {
	}

	public Ijopcgq(String nrop, Ijop ijop, Date dtfabricacao) {
		this.nrop = nrop;
		this.ijop = ijop;
		this.dtfabricacao = dtfabricacao;
	}

	@Id
	@Column(name = "NROP", unique = true, nullable = false, length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTFABRICACAO", nullable = false, length = 7)
	public Date getDtfabricacao() {
		return this.dtfabricacao;
	}

	public void setDtfabricacao(Date dtfabricacao) {
		this.dtfabricacao = dtfabricacao;
	}

}
