package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjoplotefabId generated by hbm2java
 */
@Embeddable
public class IjoplotefabId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1540634474274396443L;
	private String nrop;
	private String nrlotefabricacao;

	public IjoplotefabId() {
	}

	public IjoplotefabId(String nrop, String nrlotefabricacao) {
		this.nrop = nrop;
		this.nrlotefabricacao = nrlotefabricacao;
	}

	@Column(name = "NROP", nullable = false, length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "NRLOTEFABRICACAO", nullable = false, length = 20)
	public String getNrlotefabricacao() {
		return this.nrlotefabricacao;
	}

	public void setNrlotefabricacao(String nrlotefabricacao) {
		this.nrlotefabricacao = nrlotefabricacao;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjoplotefabId))
			return false;
		IjoplotefabId castOther = (IjoplotefabId) other;

		return ((this.getNrop() == castOther.getNrop()) || (this.getNrop() != null
				&& castOther.getNrop() != null && this.getNrop().equals(
				castOther.getNrop())))
				&& ((this.getNrlotefabricacao() == castOther
						.getNrlotefabricacao()) || (this.getNrlotefabricacao() != null
						&& castOther.getNrlotefabricacao() != null && this
						.getNrlotefabricacao().equals(
								castOther.getNrlotefabricacao())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNrop() == null ? 0 : this.getNrop().hashCode());
		result = 37
				* result
				+ (getNrlotefabricacao() == null ? 0 : this
						.getNrlotefabricacao().hashCode());
		return result;
	}

}
