package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijoplotes generated by hbm2java
 */
@Entity
@Table(name = "IJOPLOTES")
public class Ijoplotes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6986045415983130015L;
	private String nrloteop;
	private Ijop ijop;
	private Ijtbinj ijtbinj;
	private Ijtbpro ijtbpro;
	private Ijtbmol ijtbmol;
	private Date dthraberturalote;
	private Date dthrfechamentolote;
	private double qtdunidades;
	private String cdestrutura;
	private BigDecimal tamlotepadrao;
	private Double percfirmlote;
	private char sitlote;
	private Date dthrsitlote;
	private Set<Ijoplotesdet> ijoplotesdets = new HashSet<Ijoplotesdet>(0);

	public Ijoplotes() {
	}

	public Ijoplotes(String nrloteop, Ijtbinj ijtbinj, Ijtbpro ijtbpro,
			Ijtbmol ijtbmol, Date dthraberturalote, double qtdunidades,
			String cdestrutura, char sitlote, Date dthrsitlote) {
		this.nrloteop = nrloteop;
		this.ijtbinj = ijtbinj;
		this.ijtbpro = ijtbpro;
		this.ijtbmol = ijtbmol;
		this.dthraberturalote = dthraberturalote;
		this.qtdunidades = qtdunidades;
		this.cdestrutura = cdestrutura;
		this.sitlote = sitlote;
		this.dthrsitlote = dthrsitlote;
	}

	public Ijoplotes(String nrloteop, Ijop ijop, Ijtbinj ijtbinj,
			Ijtbpro ijtbpro, Ijtbmol ijtbmol, Date dthraberturalote,
			Date dthrfechamentolote, double qtdunidades, String cdestrutura,
			BigDecimal tamlotepadrao, Double percfirmlote, char sitlote,
			Date dthrsitlote, Set<Ijoplotesdet> ijoplotesdets) {
		this.nrloteop = nrloteop;
		this.ijop = ijop;
		this.ijtbinj = ijtbinj;
		this.ijtbpro = ijtbpro;
		this.ijtbmol = ijtbmol;
		this.dthraberturalote = dthraberturalote;
		this.dthrfechamentolote = dthrfechamentolote;
		this.qtdunidades = qtdunidades;
		this.cdestrutura = cdestrutura;
		this.tamlotepadrao = tamlotepadrao;
		this.percfirmlote = percfirmlote;
		this.sitlote = sitlote;
		this.dthrsitlote = dthrsitlote;
		this.ijoplotesdets = ijoplotesdets;
	}

	@Id
	@Column(name = "NRLOTEOP", unique = true, nullable = false, length = 12)
	public String getNrloteop() {
		return this.nrloteop;
	}

	public void setNrloteop(String nrloteop) {
		this.nrloteop = nrloteop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP")
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMOLDE", nullable = false)
	public Ijtbmol getIjtbmol() {
		return this.ijtbmol;
	}

	public void setIjtbmol(Ijtbmol ijtbmol) {
		this.ijtbmol = ijtbmol;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRABERTURALOTE", nullable = false, length = 7)
	public Date getDthraberturalote() {
		return this.dthraberturalote;
	}

	public void setDthraberturalote(Date dthraberturalote) {
		this.dthraberturalote = dthraberturalote;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFECHAMENTOLOTE", length = 7)
	public Date getDthrfechamentolote() {
		return this.dthrfechamentolote;
	}

	public void setDthrfechamentolote(Date dthrfechamentolote) {
		this.dthrfechamentolote = dthrfechamentolote;
	}

	@Column(name = "QTDUNIDADES", nullable = false, precision = 126, scale = 0)
	public double getQtdunidades() {
		return this.qtdunidades;
	}

	public void setQtdunidades(double qtdunidades) {
		this.qtdunidades = qtdunidades;
	}

	@Column(name = "CDESTRUTURA", nullable = false, length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Column(name = "TAMLOTEPADRAO", precision = 22, scale = 0)
	public BigDecimal getTamlotepadrao() {
		return this.tamlotepadrao;
	}

	public void setTamlotepadrao(BigDecimal tamlotepadrao) {
		this.tamlotepadrao = tamlotepadrao;
	}

	@Column(name = "PERCFIRMLOTE", precision = 126, scale = 0)
	public Double getPercfirmlote() {
		return this.percfirmlote;
	}

	public void setPercfirmlote(Double percfirmlote) {
		this.percfirmlote = percfirmlote;
	}

	@Column(name = "SITLOTE", nullable = false, length = 1)
	public char getSitlote() {
		return this.sitlote;
	}

	public void setSitlote(char sitlote) {
		this.sitlote = sitlote;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRSITLOTE", nullable = false, length = 7)
	public Date getDthrsitlote() {
		return this.dthrsitlote;
	}

	public void setDthrsitlote(Date dthrsitlote) {
		this.dthrsitlote = dthrsitlote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijoplotes")
	public Set<Ijoplotesdet> getIjoplotesdets() {
		return this.ijoplotesdets;
	}

	public void setIjoplotesdets(Set<Ijoplotesdet> ijoplotesdets) {
		this.ijoplotesdets = ijoplotesdets;
	}

}
