package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ijopmprima generated by hbm2java
 */
@Entity
@Table(name = "IJOPMPRIMA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NROP", "CDPRODUTO", "CDMPRIMA", "DTHRIVALCOMPMPRIMA", "NRLOTEMPRIMA" }))
public class Ijopmprima implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7154258470200154566L;
	private double idreg;
	private Ijtbmprima ijtbmprima;
	private Ijop ijop;
	private String nrlotemprima;
	private String cdproduto;
	private Date dthrivalcompmprima;

	public Ijopmprima() {
	}

	public Ijopmprima(double idreg, Ijtbmprima ijtbmprima, Ijop ijop,
			String cdproduto, Date dthrivalcompmprima) {
		this.idreg = idreg;
		this.ijtbmprima = ijtbmprima;
		this.ijop = ijop;
		this.cdproduto = cdproduto;
		this.dthrivalcompmprima = dthrivalcompmprima;
	}

	public Ijopmprima(double idreg, Ijtbmprima ijtbmprima, Ijop ijop,
			String nrlotemprima, String cdproduto, Date dthrivalcompmprima) {
		this.idreg = idreg;
		this.ijtbmprima = ijtbmprima;
		this.ijop = ijop;
		this.nrlotemprima = nrlotemprima;
		this.cdproduto = cdproduto;
		this.dthrivalcompmprima = dthrivalcompmprima;
	}

	@Id
	@Column(name = "IDREG", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdreg() {
		return this.idreg;
	}

	public void setIdreg(double idreg) {
		this.idreg = idreg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMPRIMA", nullable = false)
	public Ijtbmprima getIjtbmprima() {
		return this.ijtbmprima;
	}

	public void setIjtbmprima(Ijtbmprima ijtbmprima) {
		this.ijtbmprima = ijtbmprima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@Column(name = "NRLOTEMPRIMA", length = 30)
	public String getNrlotemprima() {
		return this.nrlotemprima;
	}

	public void setNrlotemprima(String nrlotemprima) {
		this.nrlotemprima = nrlotemprima;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIVALCOMPMPRIMA", nullable = false, length = 7)
	public Date getDthrivalcompmprima() {
		return this.dthrivalcompmprima;
	}

	public void setDthrivalcompmprima(Date dthrivalcompmprima) {
		this.dthrivalcompmprima = dthrivalcompmprima;
	}

}
