package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijopprodutos generated by hbm2java
 */
@Entity
@Table(name = "IJOPPRODUTOS")
public class Ijopprodutos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5995274245192524194L;
	private IjopprodutosId id;
	private Ijestmol ijestmol;
	private Ijop ijop;
	private Ijtbpro ijtbpro;
	private double qtpecasproduzir;
	private Double qtpecasestoque;
	private Set<Ijopnipponinsumo> ijopnipponinsumos = new HashSet<Ijopnipponinsumo>(
			0);

	public Ijopprodutos() {
	}

	public Ijopprodutos(IjopprodutosId id, Ijestmol ijestmol, Ijop ijop,
			Ijtbpro ijtbpro, double qtpecasproduzir) {
		this.id = id;
		this.ijestmol = ijestmol;
		this.ijop = ijop;
		this.ijtbpro = ijtbpro;
		this.qtpecasproduzir = qtpecasproduzir;
	}

	public Ijopprodutos(IjopprodutosId id, Ijestmol ijestmol, Ijop ijop,
			Ijtbpro ijtbpro, double qtpecasproduzir, Double qtpecasestoque,
			Set<Ijopnipponinsumo> ijopnipponinsumos) {
		this.id = id;
		this.ijestmol = ijestmol;
		this.ijop = ijop;
		this.ijtbpro = ijtbpro;
		this.qtpecasproduzir = qtpecasproduzir;
		this.qtpecasestoque = qtpecasestoque;
		this.ijopnipponinsumos = ijopnipponinsumos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)) })
	public IjopprodutosId getId() {
		return this.id;
	}

	public void setId(IjopprodutosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false, insertable = false, updatable = false) })
	public Ijestmol getIjestmol() {
		return this.ijestmol;
	}

	public void setIjestmol(Ijestmol ijestmol) {
		this.ijestmol = ijestmol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "QTPECASPRODUZIR", nullable = false, precision = 126, scale = 0)
	public double getQtpecasproduzir() {
		return this.qtpecasproduzir;
	}

	public void setQtpecasproduzir(double qtpecasproduzir) {
		this.qtpecasproduzir = qtpecasproduzir;
	}

	@Column(name = "QTPECASESTOQUE", precision = 126, scale = 0)
	public Double getQtpecasestoque() {
		return this.qtpecasestoque;
	}

	public void setQtpecasestoque(Double qtpecasestoque) {
		this.qtpecasestoque = qtpecasestoque;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijopprodutos")
	public Set<Ijopnipponinsumo> getIjopnipponinsumos() {
		return this.ijopnipponinsumos;
	}

	public void setIjopnipponinsumos(Set<Ijopnipponinsumo> ijopnipponinsumos) {
		this.ijopnipponinsumos = ijopnipponinsumos;
	}

}
