package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijparaminspec generated by hbm2java
 */
@Entity
@Table(name = "IJPARAMINSPEC", uniqueConstraints = @UniqueConstraint(columnNames = "IDAUXDRIVERCELCAR"))
public class Ijparaminspec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3509316160414853665L;
	private String idespecific;
	private String dsespecific;
	private BigDecimal tpespecific;
	private String unidmedida;
	private String idauxdrivercelcar;
	private Set<Ijespecinspromedia> ijespecinspromedias = new HashSet<Ijespecinspromedia>(
			0);
	private Set<Ijgrpparaminspxord> ijgrpparaminspxords = new HashSet<Ijgrpparaminspxord>(
			0);
	private Set<Ijgrcarcrtctrlxesp> ijgrcarcrtctrlxesps = new HashSet<Ijgrcarcrtctrlxesp>(
			0);
	private Set<Ijdrvcntexecprtdef> ijdrvcntexecprtdefs = new HashSet<Ijdrvcntexecprtdef>(
			0);

	public Ijparaminspec() {
	}

	public Ijparaminspec(String idespecific, String dsespecific,
			BigDecimal tpespecific, String unidmedida, String idauxdrivercelcar) {
		this.idespecific = idespecific;
		this.dsespecific = dsespecific;
		this.tpespecific = tpespecific;
		this.unidmedida = unidmedida;
		this.idauxdrivercelcar = idauxdrivercelcar;
	}

	public Ijparaminspec(String idespecific, String dsespecific,
			BigDecimal tpespecific, String unidmedida,
			String idauxdrivercelcar,
			Set<Ijespecinspromedia> ijespecinspromedias,
			Set<Ijgrpparaminspxord> ijgrpparaminspxords,
			Set<Ijgrcarcrtctrlxesp> ijgrcarcrtctrlxesps,
			Set<Ijdrvcntexecprtdef> ijdrvcntexecprtdefs) {
		this.idespecific = idespecific;
		this.dsespecific = dsespecific;
		this.tpespecific = tpespecific;
		this.unidmedida = unidmedida;
		this.idauxdrivercelcar = idauxdrivercelcar;
		this.ijespecinspromedias = ijespecinspromedias;
		this.ijgrpparaminspxords = ijgrpparaminspxords;
		this.ijgrcarcrtctrlxesps = ijgrcarcrtctrlxesps;
		this.ijdrvcntexecprtdefs = ijdrvcntexecprtdefs;
	}

	@Id
	@Column(name = "IDESPECIFIC", unique = true, nullable = false, length = 20)
	public String getIdespecific() {
		return this.idespecific;
	}

	public void setIdespecific(String idespecific) {
		this.idespecific = idespecific;
	}

	@Column(name = "DSESPECIFIC", nullable = false, length = 60)
	public String getDsespecific() {
		return this.dsespecific;
	}

	public void setDsespecific(String dsespecific) {
		this.dsespecific = dsespecific;
	}

	@Column(name = "TPESPECIFIC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpespecific() {
		return this.tpespecific;
	}

	public void setTpespecific(BigDecimal tpespecific) {
		this.tpespecific = tpespecific;
	}

	@Column(name = "UNIDMEDIDA", nullable = false, length = 10)
	public String getUnidmedida() {
		return this.unidmedida;
	}

	public void setUnidmedida(String unidmedida) {
		this.unidmedida = unidmedida;
	}

	@Column(name = "IDAUXDRIVERCELCAR", unique = true, nullable = false, length = 50)
	public String getIdauxdrivercelcar() {
		return this.idauxdrivercelcar;
	}

	public void setIdauxdrivercelcar(String idauxdrivercelcar) {
		this.idauxdrivercelcar = idauxdrivercelcar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijparaminspec")
	public Set<Ijespecinspromedia> getIjespecinspromedias() {
		return this.ijespecinspromedias;
	}

	public void setIjespecinspromedias(
			Set<Ijespecinspromedia> ijespecinspromedias) {
		this.ijespecinspromedias = ijespecinspromedias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijparaminspec")
	public Set<Ijgrpparaminspxord> getIjgrpparaminspxords() {
		return this.ijgrpparaminspxords;
	}

	public void setIjgrpparaminspxords(
			Set<Ijgrpparaminspxord> ijgrpparaminspxords) {
		this.ijgrpparaminspxords = ijgrpparaminspxords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijparaminspec")
	public Set<Ijgrcarcrtctrlxesp> getIjgrcarcrtctrlxesps() {
		return this.ijgrcarcrtctrlxesps;
	}

	public void setIjgrcarcrtctrlxesps(
			Set<Ijgrcarcrtctrlxesp> ijgrcarcrtctrlxesps) {
		this.ijgrcarcrtctrlxesps = ijgrcarcrtctrlxesps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijparaminspec")
	public Set<Ijdrvcntexecprtdef> getIjdrvcntexecprtdefs() {
		return this.ijdrvcntexecprtdefs;
	}

	public void setIjdrvcntexecprtdefs(
			Set<Ijdrvcntexecprtdef> ijdrvcntexecprtdefs) {
		this.ijdrvcntexecprtdefs = ijdrvcntexecprtdefs;
	}

}
