package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijparamitensarq generated by hbm2java
 */
@Entity
@Table(name = "IJPARAMITENSARQ")
public class Ijparamitensarq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4286853081075290729L;
	private IjparamitensarqId id;
	private Ijtbparam ijtbparam;
	private Ijselitensarq ijselitensarq;

	public Ijparamitensarq() {
	}

	public Ijparamitensarq(IjparamitensarqId id, Ijtbparam ijtbparam,
			Ijselitensarq ijselitensarq) {
		this.id = id;
		this.ijtbparam = ijtbparam;
		this.ijselitensarq = ijselitensarq;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdselecao", column = @Column(name = "CDSELECAO", nullable = false, length = 6)),
			@AttributeOverride(name = "cdtipoinf", column = @Column(name = "CDTIPOINF", nullable = false, length = 6)),
			@AttributeOverride(name = "cdinf", column = @Column(name = "CDINF", nullable = false, length = 6)),
			@AttributeOverride(name = "cdparam", column = @Column(name = "CDPARAM", nullable = false, length = 6)),
			@AttributeOverride(name = "itemsel", column = @Column(name = "ITEMSEL", nullable = false, length = 20)) })
	public IjparamitensarqId getId() {
		return this.id;
	}

	public void setId(IjparamitensarqId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPARAM", nullable = false, insertable = false, updatable = false)
	public Ijtbparam getIjtbparam() {
		return this.ijtbparam;
	}

	public void setIjtbparam(Ijtbparam ijtbparam) {
		this.ijtbparam = ijtbparam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDSELECAO", referencedColumnName = "CDSELECAO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDTIPOINF", referencedColumnName = "CDTIPOINF", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDINF", referencedColumnName = "CDINF", nullable = false, insertable = false, updatable = false) })
	public Ijselitensarq getIjselitensarq() {
		return this.ijselitensarq;
	}

	public void setIjselitensarq(Ijselitensarq ijselitensarq) {
		this.ijselitensarq = ijselitensarq;
	}

}
