package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijparprogoslog generated by hbm2java
 */
@Entity
@Table(name = "IJPARPROGOSLOG")
public class Ijparprogoslog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7342850737173955257L;
	private IjparprogoslogId id;

	public Ijparprogoslog() {
	}

	public Ijparprogoslog(IjparprogoslogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrinicio", column = @Column(name = "DTHRINICIO", nullable = false, length = 7)),
			@AttributeOverride(name = "nros", column = @Column(name = "NROS", nullable = false, length = 12)),
			@AttributeOverride(name = "dtprevinimanut", column = @Column(name = "DTPREVINIMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "dtprevfimmanut", column = @Column(name = "DTPREVFIMMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "dthralteracao", column = @Column(name = "DTHRALTERACAO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdusuario", column = @Column(name = "CDUSUARIO", nullable = false, length = 6)),
			@AttributeOverride(name = "tipolog", column = @Column(name = "TIPOLOG", nullable = false, precision = 22, scale = 0)) })
	public IjparprogoslogId getId() {
		return this.id;
	}

	public void setId(IjparprogoslogId id) {
		this.id = id;
	}

}
