package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijpdcaagndacmp generated by hbm2java
 */
@Entity
@Table(name = "IJPDCAAGNDACMP")
public class Ijpdcaagndacmp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5354762178248983974L;
	private IjpdcaagndacmpId id;
	private Ijpdcaparticipproj ijpdcaparticipproj;
	private Date dtenviorelatorio;

	public Ijpdcaagndacmp() {
	}

	public Ijpdcaagndacmp(IjpdcaagndacmpId id,
			Ijpdcaparticipproj ijpdcaparticipproj) {
		this.id = id;
		this.ijpdcaparticipproj = ijpdcaparticipproj;
	}

	public Ijpdcaagndacmp(IjpdcaagndacmpId id,
			Ijpdcaparticipproj ijpdcaparticipproj, Date dtenviorelatorio) {
		this.id = id;
		this.ijpdcaparticipproj = ijpdcaparticipproj;
		this.dtenviorelatorio = dtenviorelatorio;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrprojeto", column = @Column(name = "NRPROJETO", nullable = false, length = 10)),
			@AttributeOverride(name = "idparticipante", column = @Column(name = "IDPARTICIPANTE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "dtagendamento", column = @Column(name = "DTAGENDAMENTO", nullable = false, length = 7)) })
	public IjpdcaagndacmpId getId() {
		return this.id;
	}

	public void setId(IjpdcaagndacmpId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "NRPROJETO", referencedColumnName = "NRPROJETO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "IDPARTICIPANTE", referencedColumnName = "IDPARTICIPANTE", nullable = false, insertable = false, updatable = false) })
	public Ijpdcaparticipproj getIjpdcaparticipproj() {
		return this.ijpdcaparticipproj;
	}

	public void setIjpdcaparticipproj(Ijpdcaparticipproj ijpdcaparticipproj) {
		this.ijpdcaparticipproj = ijpdcaparticipproj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTENVIORELATORIO", length = 7)
	public Date getDtenviorelatorio() {
		return this.dtenviorelatorio;
	}

	public void setDtenviorelatorio(Date dtenviorelatorio) {
		this.dtenviorelatorio = dtenviorelatorio;
	}

}
