package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijpdcaacao generated by hbm2java
 */
@Entity
@Table(name = "IJPDCAACAO")
public class Ijpdcaacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 251435818346481584L;
	private IjpdcaacaoId id;
	private Ijtbaco ijtbaco;
	private Ijpdcaprojeto ijpdcaprojeto;
	private Ijareres ijareres;
	private Ijtbcau ijtbcau;
	private String idacao;
	private BigDecimal posicaoordinal;
	private BigDecimal nivel;
	private BigDecimal idagendaassociada;
	private BigDecimal tpefeito;
	private String cdefeito;
	private BigDecimal fatormanufatura;
	private String dsacao;
	private BigDecimal idparticipante;
	private String porque;
	private String onde;
	private Double quanto;
	private String compacao;
	private BigDecimal tmpexec;
	private Date dtpreviniexec;
	private Date dtprevfimexec;
	private Date dtrealiniexec;
	private Date dtrealfimexec;
	private BigDecimal tmpvresult;
	private Date dtprevinivresult;
	private Date dtprevfimvresult;
	private Date dtrealinivresult;
	private Date dtrealfimvresult;
	private BigDecimal resultadoacao;
	private Date dtcancelamento;
	private Set<Ijpdcafupacao> ijpdcafupacaos = new HashSet<Ijpdcafupacao>(0);

	public Ijpdcaacao() {
	}

	public Ijpdcaacao(IjpdcaacaoId id, Ijpdcaprojeto ijpdcaprojeto,
			Ijareres ijareres, Ijtbcau ijtbcau, BigDecimal posicaoordinal,
			BigDecimal nivel, BigDecimal idagendaassociada,
			BigDecimal tpefeito, String cdefeito, BigDecimal fatormanufatura,
			BigDecimal idparticipante, BigDecimal tmpexec, Date dtpreviniexec,
			Date dtprevfimexec, BigDecimal tmpvresult, Date dtprevinivresult,
			Date dtprevfimvresult) {
		this.id = id;
		this.ijpdcaprojeto = ijpdcaprojeto;
		this.ijareres = ijareres;
		this.ijtbcau = ijtbcau;
		this.posicaoordinal = posicaoordinal;
		this.nivel = nivel;
		this.idagendaassociada = idagendaassociada;
		this.tpefeito = tpefeito;
		this.cdefeito = cdefeito;
		this.fatormanufatura = fatormanufatura;
		this.idparticipante = idparticipante;
		this.tmpexec = tmpexec;
		this.dtpreviniexec = dtpreviniexec;
		this.dtprevfimexec = dtprevfimexec;
		this.tmpvresult = tmpvresult;
		this.dtprevinivresult = dtprevinivresult;
		this.dtprevfimvresult = dtprevfimvresult;
	}

	public Ijpdcaacao(IjpdcaacaoId id, Ijtbaco ijtbaco,
			Ijpdcaprojeto ijpdcaprojeto, Ijareres ijareres, Ijtbcau ijtbcau,
			String idacao, BigDecimal posicaoordinal, BigDecimal nivel,
			BigDecimal idagendaassociada, BigDecimal tpefeito, String cdefeito,
			BigDecimal fatormanufatura, String dsacao,
			BigDecimal idparticipante, String porque, String onde,
			Double quanto, String compacao, BigDecimal tmpexec,
			Date dtpreviniexec, Date dtprevfimexec, Date dtrealiniexec,
			Date dtrealfimexec, BigDecimal tmpvresult, Date dtprevinivresult,
			Date dtprevfimvresult, Date dtrealinivresult,
			Date dtrealfimvresult, BigDecimal resultadoacao,
			Date dtcancelamento, Set<Ijpdcafupacao> ijpdcafupacaos) {
		this.id = id;
		this.ijtbaco = ijtbaco;
		this.ijpdcaprojeto = ijpdcaprojeto;
		this.ijareres = ijareres;
		this.ijtbcau = ijtbcau;
		this.idacao = idacao;
		this.posicaoordinal = posicaoordinal;
		this.nivel = nivel;
		this.idagendaassociada = idagendaassociada;
		this.tpefeito = tpefeito;
		this.cdefeito = cdefeito;
		this.fatormanufatura = fatormanufatura;
		this.dsacao = dsacao;
		this.idparticipante = idparticipante;
		this.porque = porque;
		this.onde = onde;
		this.quanto = quanto;
		this.compacao = compacao;
		this.tmpexec = tmpexec;
		this.dtpreviniexec = dtpreviniexec;
		this.dtprevfimexec = dtprevfimexec;
		this.dtrealiniexec = dtrealiniexec;
		this.dtrealfimexec = dtrealfimexec;
		this.tmpvresult = tmpvresult;
		this.dtprevinivresult = dtprevinivresult;
		this.dtprevfimvresult = dtprevfimvresult;
		this.dtrealinivresult = dtrealinivresult;
		this.dtrealfimvresult = dtrealfimvresult;
		this.resultadoacao = resultadoacao;
		this.dtcancelamento = dtcancelamento;
		this.ijpdcafupacaos = ijpdcafupacaos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrprojeto", column = @Column(name = "NRPROJETO", nullable = false, length = 10)),
			@AttributeOverride(name = "idagendamento", column = @Column(name = "IDAGENDAMENTO", nullable = false, precision = 22, scale = 0)) })
	public IjpdcaacaoId getId() {
		return this.id;
	}

	public void setId(IjpdcaacaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDACAOSELECIONADA")
	public Ijtbaco getIjtbaco() {
		return this.ijtbaco;
	}

	public void setIjtbaco(Ijtbaco ijtbaco) {
		this.ijtbaco = ijtbaco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NRPROJETO", nullable = false, insertable = false, updatable = false)
	public Ijpdcaprojeto getIjpdcaprojeto() {
		return this.ijpdcaprojeto;
	}

	public void setIjpdcaprojeto(Ijpdcaprojeto ijpdcaprojeto) {
		this.ijpdcaprojeto = ijpdcaprojeto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDAREARESPACAO", nullable = false)
	public Ijareres getIjareres() {
		return this.ijareres;
	}

	public void setIjareres(Ijareres ijareres) {
		this.ijareres = ijareres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCAUSASELECIONADA", nullable = false)
	public Ijtbcau getIjtbcau() {
		return this.ijtbcau;
	}

	public void setIjtbcau(Ijtbcau ijtbcau) {
		this.ijtbcau = ijtbcau;
	}

	@Column(name = "IDACAO", length = 12)
	public String getIdacao() {
		return this.idacao;
	}

	public void setIdacao(String idacao) {
		this.idacao = idacao;
	}

	@Column(name = "POSICAOORDINAL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPosicaoordinal() {
		return this.posicaoordinal;
	}

	public void setPosicaoordinal(BigDecimal posicaoordinal) {
		this.posicaoordinal = posicaoordinal;
	}

	@Column(name = "NIVEL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNivel() {
		return this.nivel;
	}

	public void setNivel(BigDecimal nivel) {
		this.nivel = nivel;
	}

	@Column(name = "IDAGENDAASSOCIADA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdagendaassociada() {
		return this.idagendaassociada;
	}

	public void setIdagendaassociada(BigDecimal idagendaassociada) {
		this.idagendaassociada = idagendaassociada;
	}

	@Column(name = "TPEFEITO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpefeito() {
		return this.tpefeito;
	}

	public void setTpefeito(BigDecimal tpefeito) {
		this.tpefeito = tpefeito;
	}

	@Column(name = "CDEFEITO", nullable = false, length = 6)
	public String getCdefeito() {
		return this.cdefeito;
	}

	public void setCdefeito(String cdefeito) {
		this.cdefeito = cdefeito;
	}

	@Column(name = "FATORMANUFATURA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getFatormanufatura() {
		return this.fatormanufatura;
	}

	public void setFatormanufatura(BigDecimal fatormanufatura) {
		this.fatormanufatura = fatormanufatura;
	}

	@Column(name = "DSACAO")
	public String getDsacao() {
		return this.dsacao;
	}

	public void setDsacao(String dsacao) {
		this.dsacao = dsacao;
	}

	@Column(name = "IDPARTICIPANTE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdparticipante() {
		return this.idparticipante;
	}

	public void setIdparticipante(BigDecimal idparticipante) {
		this.idparticipante = idparticipante;
	}

	@Column(name = "PORQUE")
	public String getPorque() {
		return this.porque;
	}

	public void setPorque(String porque) {
		this.porque = porque;
	}

	@Column(name = "ONDE")
	public String getOnde() {
		return this.onde;
	}

	public void setOnde(String onde) {
		this.onde = onde;
	}

	@Column(name = "QUANTO", precision = 126, scale = 0)
	public Double getQuanto() {
		return this.quanto;
	}

	public void setQuanto(Double quanto) {
		this.quanto = quanto;
	}

	@Column(name = "COMPACAO")
	public String getCompacao() {
		return this.compacao;
	}

	public void setCompacao(String compacao) {
		this.compacao = compacao;
	}

	@Column(name = "TMPEXEC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmpexec() {
		return this.tmpexec;
	}

	public void setTmpexec(BigDecimal tmpexec) {
		this.tmpexec = tmpexec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPREVINIEXEC", nullable = false, length = 7)
	public Date getDtpreviniexec() {
		return this.dtpreviniexec;
	}

	public void setDtpreviniexec(Date dtpreviniexec) {
		this.dtpreviniexec = dtpreviniexec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPREVFIMEXEC", nullable = false, length = 7)
	public Date getDtprevfimexec() {
		return this.dtprevfimexec;
	}

	public void setDtprevfimexec(Date dtprevfimexec) {
		this.dtprevfimexec = dtprevfimexec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTREALINIEXEC", length = 7)
	public Date getDtrealiniexec() {
		return this.dtrealiniexec;
	}

	public void setDtrealiniexec(Date dtrealiniexec) {
		this.dtrealiniexec = dtrealiniexec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTREALFIMEXEC", length = 7)
	public Date getDtrealfimexec() {
		return this.dtrealfimexec;
	}

	public void setDtrealfimexec(Date dtrealfimexec) {
		this.dtrealfimexec = dtrealfimexec;
	}

	@Column(name = "TMPVRESULT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmpvresult() {
		return this.tmpvresult;
	}

	public void setTmpvresult(BigDecimal tmpvresult) {
		this.tmpvresult = tmpvresult;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPREVINIVRESULT", nullable = false, length = 7)
	public Date getDtprevinivresult() {
		return this.dtprevinivresult;
	}

	public void setDtprevinivresult(Date dtprevinivresult) {
		this.dtprevinivresult = dtprevinivresult;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPREVFIMVRESULT", nullable = false, length = 7)
	public Date getDtprevfimvresult() {
		return this.dtprevfimvresult;
	}

	public void setDtprevfimvresult(Date dtprevfimvresult) {
		this.dtprevfimvresult = dtprevfimvresult;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTREALINIVRESULT", length = 7)
	public Date getDtrealinivresult() {
		return this.dtrealinivresult;
	}

	public void setDtrealinivresult(Date dtrealinivresult) {
		this.dtrealinivresult = dtrealinivresult;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTREALFIMVRESULT", length = 7)
	public Date getDtrealfimvresult() {
		return this.dtrealfimvresult;
	}

	public void setDtrealfimvresult(Date dtrealfimvresult) {
		this.dtrealfimvresult = dtrealfimvresult;
	}

	@Column(name = "RESULTADOACAO", precision = 22, scale = 0)
	public BigDecimal getResultadoacao() {
		return this.resultadoacao;
	}

	public void setResultadoacao(BigDecimal resultadoacao) {
		this.resultadoacao = resultadoacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTCANCELAMENTO", length = 7)
	public Date getDtcancelamento() {
		return this.dtcancelamento;
	}

	public void setDtcancelamento(Date dtcancelamento) {
		this.dtcancelamento = dtcancelamento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijpdcaacao")
	public Set<Ijpdcafupacao> getIjpdcafupacaos() {
		return this.ijpdcafupacaos;
	}

	public void setIjpdcafupacaos(Set<Ijpdcafupacao> ijpdcafupacaos) {
		this.ijpdcafupacaos = ijpdcafupacaos;
	}

}
