package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjpdcaparticipprojId generated by hbm2java
 */
@Embeddable
public class IjpdcaparticipprojId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5041515539987542367L;
	private String nrprojeto;
	private BigDecimal idparticipante;

	public IjpdcaparticipprojId() {
	}

	public IjpdcaparticipprojId(String nrprojeto, BigDecimal idparticipante) {
		this.nrprojeto = nrprojeto;
		this.idparticipante = idparticipante;
	}

	@Column(name = "NRPROJETO", nullable = false, length = 10)
	public String getNrprojeto() {
		return this.nrprojeto;
	}

	public void setNrprojeto(String nrprojeto) {
		this.nrprojeto = nrprojeto;
	}

	@Column(name = "IDPARTICIPANTE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdparticipante() {
		return this.idparticipante;
	}

	public void setIdparticipante(BigDecimal idparticipante) {
		this.idparticipante = idparticipante;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjpdcaparticipprojId))
			return false;
		IjpdcaparticipprojId castOther = (IjpdcaparticipprojId) other;

		return ((this.getNrprojeto() == castOther.getNrprojeto()) || (this
				.getNrprojeto() != null && castOther.getNrprojeto() != null && this
				.getNrprojeto().equals(castOther.getNrprojeto())))
				&& ((this.getIdparticipante() == castOther.getIdparticipante()) || (this
						.getIdparticipante() != null
						&& castOther.getIdparticipante() != null && this
						.getIdparticipante().equals(
								castOther.getIdparticipante())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNrprojeto() == null ? 0 : this.getNrprojeto().hashCode());
		result = 37
				* result
				+ (getIdparticipante() == null ? 0 : this.getIdparticipante()
						.hashCode());
		return result;
	}

}
