package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijpdcaprojeto generated by hbm2java
 */
@Entity
@Table(name = "IJPDCAPROJETO")
public class Ijpdcaprojeto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5873908986508722967L;
	private String nrprojeto;
	private String nmprojeto;
	private String dsprojeto;
	private Date dtprojeto;
	private BigDecimal idparticipante;
	private double indicadorparada;
	private double indicadorrefugo;
	private double indicadorrea;
	private double indicadorciclo;
	private double indicadorperdas;
	private Date dtconcprojeto;
	private BigDecimal resultadoprojeto;
	private Date dtcancprojeto;
	private Date dtpreviniproj;
	private Date dtprevfimproj;
	private Set<Ijpdcaparticipproj> ijpdcaparticipprojs = new HashSet<Ijpdcaparticipproj>(
			0);
	private Set<Ijpdcafiltroproj> ijpdcafiltroprojs = new HashSet<Ijpdcafiltroproj>(
			0);
	private Set<Ijpdcagrafverific> ijpdcagrafverifics = new HashSet<Ijpdcagrafverific>(
			0);
	private Set<Ijpdcaacao> ijpdcaacaos = new HashSet<Ijpdcaacao>(0);

	public Ijpdcaprojeto() {
	}

	public Ijpdcaprojeto(String nrprojeto, String nmprojeto, String dsprojeto,
			Date dtprojeto, BigDecimal idparticipante, double indicadorparada,
			double indicadorrefugo, double indicadorrea, double indicadorciclo,
			double indicadorperdas) {
		this.nrprojeto = nrprojeto;
		this.nmprojeto = nmprojeto;
		this.dsprojeto = dsprojeto;
		this.dtprojeto = dtprojeto;
		this.idparticipante = idparticipante;
		this.indicadorparada = indicadorparada;
		this.indicadorrefugo = indicadorrefugo;
		this.indicadorrea = indicadorrea;
		this.indicadorciclo = indicadorciclo;
		this.indicadorperdas = indicadorperdas;
	}

	public Ijpdcaprojeto(String nrprojeto, String nmprojeto, String dsprojeto,
			Date dtprojeto, BigDecimal idparticipante, double indicadorparada,
			double indicadorrefugo, double indicadorrea, double indicadorciclo,
			double indicadorperdas, Date dtconcprojeto,
			BigDecimal resultadoprojeto, Date dtcancprojeto,
			Date dtpreviniproj, Date dtprevfimproj,
			Set<Ijpdcaparticipproj> ijpdcaparticipprojs,
			Set<Ijpdcafiltroproj> ijpdcafiltroprojs,
			Set<Ijpdcagrafverific> ijpdcagrafverifics,
			Set<Ijpdcaacao> ijpdcaacaos) {
		this.nrprojeto = nrprojeto;
		this.nmprojeto = nmprojeto;
		this.dsprojeto = dsprojeto;
		this.dtprojeto = dtprojeto;
		this.idparticipante = idparticipante;
		this.indicadorparada = indicadorparada;
		this.indicadorrefugo = indicadorrefugo;
		this.indicadorrea = indicadorrea;
		this.indicadorciclo = indicadorciclo;
		this.indicadorperdas = indicadorperdas;
		this.dtconcprojeto = dtconcprojeto;
		this.resultadoprojeto = resultadoprojeto;
		this.dtcancprojeto = dtcancprojeto;
		this.dtpreviniproj = dtpreviniproj;
		this.dtprevfimproj = dtprevfimproj;
		this.ijpdcaparticipprojs = ijpdcaparticipprojs;
		this.ijpdcafiltroprojs = ijpdcafiltroprojs;
		this.ijpdcagrafverifics = ijpdcagrafverifics;
		this.ijpdcaacaos = ijpdcaacaos;
	}

	@Id
	@Column(name = "NRPROJETO", unique = true, nullable = false, length = 10)
	public String getNrprojeto() {
		return this.nrprojeto;
	}

	public void setNrprojeto(String nrprojeto) {
		this.nrprojeto = nrprojeto;
	}

	@Column(name = "NMPROJETO", nullable = false, length = 40)
	public String getNmprojeto() {
		return this.nmprojeto;
	}

	public void setNmprojeto(String nmprojeto) {
		this.nmprojeto = nmprojeto;
	}

	@Column(name = "DSPROJETO", nullable = false)
	public String getDsprojeto() {
		return this.dsprojeto;
	}

	public void setDsprojeto(String dsprojeto) {
		this.dsprojeto = dsprojeto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPROJETO", nullable = false, length = 7)
	public Date getDtprojeto() {
		return this.dtprojeto;
	}

	public void setDtprojeto(Date dtprojeto) {
		this.dtprojeto = dtprojeto;
	}

	@Column(name = "IDPARTICIPANTE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdparticipante() {
		return this.idparticipante;
	}

	public void setIdparticipante(BigDecimal idparticipante) {
		this.idparticipante = idparticipante;
	}

	@Column(name = "INDICADORPARADA", nullable = false, precision = 126, scale = 0)
	public double getIndicadorparada() {
		return this.indicadorparada;
	}

	public void setIndicadorparada(double indicadorparada) {
		this.indicadorparada = indicadorparada;
	}

	@Column(name = "INDICADORREFUGO", nullable = false, precision = 126, scale = 0)
	public double getIndicadorrefugo() {
		return this.indicadorrefugo;
	}

	public void setIndicadorrefugo(double indicadorrefugo) {
		this.indicadorrefugo = indicadorrefugo;
	}

	@Column(name = "INDICADORREA", nullable = false, precision = 126, scale = 0)
	public double getIndicadorrea() {
		return this.indicadorrea;
	}

	public void setIndicadorrea(double indicadorrea) {
		this.indicadorrea = indicadorrea;
	}

	@Column(name = "INDICADORCICLO", nullable = false, precision = 126, scale = 0)
	public double getIndicadorciclo() {
		return this.indicadorciclo;
	}

	public void setIndicadorciclo(double indicadorciclo) {
		this.indicadorciclo = indicadorciclo;
	}

	@Column(name = "INDICADORPERDAS", nullable = false, precision = 126, scale = 0)
	public double getIndicadorperdas() {
		return this.indicadorperdas;
	}

	public void setIndicadorperdas(double indicadorperdas) {
		this.indicadorperdas = indicadorperdas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTCONCPROJETO", length = 7)
	public Date getDtconcprojeto() {
		return this.dtconcprojeto;
	}

	public void setDtconcprojeto(Date dtconcprojeto) {
		this.dtconcprojeto = dtconcprojeto;
	}

	@Column(name = "RESULTADOPROJETO", precision = 22, scale = 0)
	public BigDecimal getResultadoprojeto() {
		return this.resultadoprojeto;
	}

	public void setResultadoprojeto(BigDecimal resultadoprojeto) {
		this.resultadoprojeto = resultadoprojeto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTCANCPROJETO", length = 7)
	public Date getDtcancprojeto() {
		return this.dtcancprojeto;
	}

	public void setDtcancprojeto(Date dtcancprojeto) {
		this.dtcancprojeto = dtcancprojeto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPREVINIPROJ", length = 7)
	public Date getDtpreviniproj() {
		return this.dtpreviniproj;
	}

	public void setDtpreviniproj(Date dtpreviniproj) {
		this.dtpreviniproj = dtpreviniproj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPREVFIMPROJ", length = 7)
	public Date getDtprevfimproj() {
		return this.dtprevfimproj;
	}

	public void setDtprevfimproj(Date dtprevfimproj) {
		this.dtprevfimproj = dtprevfimproj;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijpdcaprojeto")
	public Set<Ijpdcaparticipproj> getIjpdcaparticipprojs() {
		return this.ijpdcaparticipprojs;
	}

	public void setIjpdcaparticipprojs(
			Set<Ijpdcaparticipproj> ijpdcaparticipprojs) {
		this.ijpdcaparticipprojs = ijpdcaparticipprojs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijpdcaprojeto")
	public Set<Ijpdcafiltroproj> getIjpdcafiltroprojs() {
		return this.ijpdcafiltroprojs;
	}

	public void setIjpdcafiltroprojs(Set<Ijpdcafiltroproj> ijpdcafiltroprojs) {
		this.ijpdcafiltroprojs = ijpdcafiltroprojs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijpdcaprojeto")
	public Set<Ijpdcagrafverific> getIjpdcagrafverifics() {
		return this.ijpdcagrafverifics;
	}

	public void setIjpdcagrafverifics(Set<Ijpdcagrafverific> ijpdcagrafverifics) {
		this.ijpdcagrafverifics = ijpdcagrafverifics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijpdcaprojeto")
	public Set<Ijpdcaacao> getIjpdcaacaos() {
		return this.ijpdcaacaos;
	}

	public void setIjpdcaacaos(Set<Ijpdcaacao> ijpdcaacaos) {
		this.ijpdcaacaos = ijpdcaacaos;
	}

}
