package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijplano generated by hbm2java
 */
@Entity
@Table(name = "IJPLANO")
public class Ijplano implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7803198900279753359L;
	private String nrplano;
	private Ijcarteira ijcarteira;
	private Date dthremissao;
	private String documento;
	private Set<Ijop> ijops = new HashSet<Ijop>(0);
	private Set<Ijproplano> ijproplanos = new HashSet<Ijproplano>(0);

	public Ijplano() {
	}

	public Ijplano(String nrplano, Ijcarteira ijcarteira) {
		this.nrplano = nrplano;
		this.ijcarteira = ijcarteira;
	}

	public Ijplano(String nrplano, Ijcarteira ijcarteira, Date dthremissao,
			String documento, Set<Ijop> ijops, Set<Ijproplano> ijproplanos) {
		this.nrplano = nrplano;
		this.ijcarteira = ijcarteira;
		this.dthremissao = dthremissao;
		this.documento = documento;
		this.ijops = ijops;
		this.ijproplanos = ijproplanos;
	}

	@Id
	@Column(name = "NRPLANO", unique = true, nullable = false, length = 10)
	public String getNrplano() {
		return this.nrplano;
	}

	public void setNrplano(String nrplano) {
		this.nrplano = nrplano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NRCARTEIRA", nullable = false)
	public Ijcarteira getIjcarteira() {
		return this.ijcarteira;
	}

	public void setIjcarteira(Ijcarteira ijcarteira) {
		this.ijcarteira = ijcarteira;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHREMISSAO", length = 7)
	public Date getDthremissao() {
		return this.dthremissao;
	}

	public void setDthremissao(Date dthremissao) {
		this.dthremissao = dthremissao;
	}

	@Column(name = "DOCUMENTO", length = 10)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijplano")
	public Set<Ijop> getIjops() {
		return this.ijops;
	}

	public void setIjops(Set<Ijop> ijops) {
		this.ijops = ijops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijplano")
	public Set<Ijproplano> getIjproplanos() {
		return this.ijproplanos;
	}

	public void setIjproplanos(Set<Ijproplano> ijproplanos) {
		this.ijproplanos = ijproplanos;
	}

}
