package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjpostogrpestprocId generated by hbm2java
 */
@Embeddable
public class IjpostogrpestprocId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4884583366517238603L;
	private String cdgrupoestproc;
	private String cdposto;

	public IjpostogrpestprocId() {
	}

	public IjpostogrpestprocId(String cdgrupoestproc, String cdposto) {
		this.cdgrupoestproc = cdgrupoestproc;
		this.cdposto = cdposto;
	}

	@Column(name = "CDGRUPOESTPROC", nullable = false, length = 6)
	public String getCdgrupoestproc() {
		return this.cdgrupoestproc;
	}

	public void setCdgrupoestproc(String cdgrupoestproc) {
		this.cdgrupoestproc = cdgrupoestproc;
	}

	@Column(name = "CDPOSTO", nullable = false, length = 6)
	public String getCdposto() {
		return this.cdposto;
	}

	public void setCdposto(String cdposto) {
		this.cdposto = cdposto;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjpostogrpestprocId))
			return false;
		IjpostogrpestprocId castOther = (IjpostogrpestprocId) other;

		return ((this.getCdgrupoestproc() == castOther.getCdgrupoestproc()) || (this
				.getCdgrupoestproc() != null
				&& castOther.getCdgrupoestproc() != null && this
				.getCdgrupoestproc().equals(castOther.getCdgrupoestproc())))
				&& ((this.getCdposto() == castOther.getCdposto()) || (this
						.getCdposto() != null && castOther.getCdposto() != null && this
						.getCdposto().equals(castOther.getCdposto())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdgrupoestproc() == null ? 0 : this.getCdgrupoestproc()
						.hashCode());
		result = 37 * result
				+ (getCdposto() == null ? 0 : this.getCdposto().hashCode());
		return result;
	}

}
