package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijprocarteira generated by hbm2java
 */
@Entity
@Table(name = "IJPROCARTEIRA")
public class Ijprocarteira implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7754172577138375477L;
	private IjprocarteiraId id;
	private Ijcarteira ijcarteira;
	private Ijtbpro ijtbpro;
	private double qtpedida;
	private double qtatendida;

	public Ijprocarteira() {
	}

	public Ijprocarteira(IjprocarteiraId id, Ijcarteira ijcarteira,
			Ijtbpro ijtbpro, double qtpedida, double qtatendida) {
		this.id = id;
		this.ijcarteira = ijcarteira;
		this.ijtbpro = ijtbpro;
		this.qtpedida = qtpedida;
		this.qtatendida = qtatendida;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrcarteira", column = @Column(name = "NRCARTEIRA", nullable = false, length = 10)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)) })
	public IjprocarteiraId getId() {
		return this.id;
	}

	public void setId(IjprocarteiraId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NRCARTEIRA", nullable = false, insertable = false, updatable = false)
	public Ijcarteira getIjcarteira() {
		return this.ijcarteira;
	}

	public void setIjcarteira(Ijcarteira ijcarteira) {
		this.ijcarteira = ijcarteira;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "QTPEDIDA", nullable = false, precision = 126, scale = 0)
	public double getQtpedida() {
		return this.qtpedida;
	}

	public void setQtpedida(double qtpedida) {
		this.qtpedida = qtpedida;
	}

	@Column(name = "QTATENDIDA", nullable = false, precision = 126, scale = 0)
	public double getQtatendida() {
		return this.qtatendida;
	}

	public void setQtatendida(double qtatendida) {
		this.qtatendida = qtatendida;
	}

}
