package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijproxgrcarcrtctrl generated by hbm2java
 */
@Entity
@Table(name = "IJPROXGRCARCRTCTRL")
public class Ijproxgrcarcrtctrl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8367306187130732015L;
	private IjproxgrcarcrtctrlId id;
	private Ijgrcarcrtctrl ijgrcarcrtctrl;
	private Ijtbpro ijtbpro;

	public Ijproxgrcarcrtctrl() {
	}

	public Ijproxgrcarcrtctrl(IjproxgrcarcrtctrlId id,
			Ijgrcarcrtctrl ijgrcarcrtctrl, Ijtbpro ijtbpro) {
		this.id = id;
		this.ijgrcarcrtctrl = ijgrcarcrtctrl;
		this.ijtbpro = ijtbpro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "cdgrproctrctrl", column = @Column(name = "CDGRPROCTRCTRL", nullable = false, length = 6)) })
	public IjproxgrcarcrtctrlId getId() {
		return this.id;
	}

	public void setId(IjproxgrcarcrtctrlId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRPROCTRCTRL", nullable = false, insertable = false, updatable = false)
	public Ijgrcarcrtctrl getIjgrcarcrtctrl() {
		return this.ijgrcarcrtctrl;
	}

	public void setIjgrcarcrtctrl(Ijgrcarcrtctrl ijgrcarcrtctrl) {
		this.ijgrcarcrtctrl = ijgrcarcrtctrl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

}
