package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijproultop generated by hbm2java
 */
@Entity
@Table(name = "IJPROULTOP")
public class Ijproultop implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -888938887341817235L;
	private String cdproduto;
	private Ijop ijop;
	private Ijtbpro ijtbpro;

	public Ijproultop() {
	}

	public Ijproultop(String cdproduto, Ijop ijop, Ijtbpro ijtbpro) {
		this.cdproduto = cdproduto;
		this.ijop = ijop;
		this.ijtbpro = ijtbpro;
	}

	@Id
	@Column(name = "CDPRODUTO", unique = true, nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

}
