package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijproplano generated by hbm2java
 */
@Entity
@Table(name = "IJPROPLANO")
public class Ijproplano implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6046367115610091152L;
	private IjproplanoId id;
	private Ijplano ijplano;
	private Ijtbpro ijtbpro;
	private double qtplanejada;
	private double qtproduzida;

	public Ijproplano() {
	}

	public Ijproplano(IjproplanoId id, Ijplano ijplano, Ijtbpro ijtbpro,
			double qtplanejada, double qtproduzida) {
		this.id = id;
		this.ijplano = ijplano;
		this.ijtbpro = ijtbpro;
		this.qtplanejada = qtplanejada;
		this.qtproduzida = qtproduzida;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrplano", column = @Column(name = "NRPLANO", nullable = false, length = 10)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)) })
	public IjproplanoId getId() {
		return this.id;
	}

	public void setId(IjproplanoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NRPLANO", nullable = false, insertable = false, updatable = false)
	public Ijplano getIjplano() {
		return this.ijplano;
	}

	public void setIjplano(Ijplano ijplano) {
		this.ijplano = ijplano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "QTPLANEJADA", nullable = false, precision = 126, scale = 0)
	public double getQtplanejada() {
		return this.qtplanejada;
	}

	public void setQtplanejada(double qtplanejada) {
		this.qtplanejada = qtplanejada;
	}

	@Column(name = "QTPRODUZIDA", nullable = false, precision = 126, scale = 0)
	public double getQtproduzida() {
		return this.qtproduzida;
	}

	public void setQtproduzida(double qtproduzida) {
		this.qtproduzida = qtproduzida;
	}

}
