package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijprodxgrpparam generated by hbm2java
 */
@Entity
@Table(name = "IJPRODXGRPPARAM")
public class Ijprodxgrpparam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6359077590360350862L;
	private IjprodxgrpparamId id;
	private Ijgrpparaminsp ijgrpparaminsp;
	private Ijtbpro ijtbpro;
	private double tamminlote;
	private BigDecimal tpfrequencia;
	private double qtdprodaleiniop;
	private double qtdrejgeracaoale;
	private BigDecimal tpcentralexec;
	private double qtdprodaposprobqld;
	private BigDecimal cfgjustdbqld1;
	private BigDecimal qtdjustdbqld1;
	private BigDecimal cfgjustdbqld2;
	private BigDecimal qtdjustdbqld2;
	private BigDecimal cfgjustdbqld3;
	private BigDecimal qtdjustdbqld3;
	private Set<Ijregultinspqld2> ijregultinspqld2s = new HashSet<Ijregultinspqld2>(
			0);
	private Set<Ijprodxparamfreq> ijprodxparamfreqs = new HashSet<Ijprodxparamfreq>(
			0);
	private Set<Ijdrvcntexecprtdef> ijdrvcntexecprtdefs = new HashSet<Ijdrvcntexecprtdef>(
			0);

	public Ijprodxgrpparam() {
	}

	public Ijprodxgrpparam(IjprodxgrpparamId id, Ijgrpparaminsp ijgrpparaminsp,
			Ijtbpro ijtbpro, double tamminlote, BigDecimal tpfrequencia,
			double qtdprodaleiniop, double qtdrejgeracaoale,
			BigDecimal tpcentralexec, double qtdprodaposprobqld,
			BigDecimal cfgjustdbqld1, BigDecimal qtdjustdbqld1,
			BigDecimal cfgjustdbqld2, BigDecimal qtdjustdbqld2,
			BigDecimal cfgjustdbqld3, BigDecimal qtdjustdbqld3) {
		this.id = id;
		this.ijgrpparaminsp = ijgrpparaminsp;
		this.ijtbpro = ijtbpro;
		this.tamminlote = tamminlote;
		this.tpfrequencia = tpfrequencia;
		this.qtdprodaleiniop = qtdprodaleiniop;
		this.qtdrejgeracaoale = qtdrejgeracaoale;
		this.tpcentralexec = tpcentralexec;
		this.qtdprodaposprobqld = qtdprodaposprobqld;
		this.cfgjustdbqld1 = cfgjustdbqld1;
		this.qtdjustdbqld1 = qtdjustdbqld1;
		this.cfgjustdbqld2 = cfgjustdbqld2;
		this.qtdjustdbqld2 = qtdjustdbqld2;
		this.cfgjustdbqld3 = cfgjustdbqld3;
		this.qtdjustdbqld3 = qtdjustdbqld3;
	}

	public Ijprodxgrpparam(IjprodxgrpparamId id, Ijgrpparaminsp ijgrpparaminsp,
			Ijtbpro ijtbpro, double tamminlote, BigDecimal tpfrequencia,
			double qtdprodaleiniop, double qtdrejgeracaoale,
			BigDecimal tpcentralexec, double qtdprodaposprobqld,
			BigDecimal cfgjustdbqld1, BigDecimal qtdjustdbqld1,
			BigDecimal cfgjustdbqld2, BigDecimal qtdjustdbqld2,
			BigDecimal cfgjustdbqld3, BigDecimal qtdjustdbqld3,
			Set<Ijregultinspqld2> ijregultinspqld2s,
			Set<Ijprodxparamfreq> ijprodxparamfreqs,
			Set<Ijdrvcntexecprtdef> ijdrvcntexecprtdefs) {
		this.id = id;
		this.ijgrpparaminsp = ijgrpparaminsp;
		this.ijtbpro = ijtbpro;
		this.tamminlote = tamminlote;
		this.tpfrequencia = tpfrequencia;
		this.qtdprodaleiniop = qtdprodaleiniop;
		this.qtdrejgeracaoale = qtdrejgeracaoale;
		this.tpcentralexec = tpcentralexec;
		this.qtdprodaposprobqld = qtdprodaposprobqld;
		this.cfgjustdbqld1 = cfgjustdbqld1;
		this.qtdjustdbqld1 = qtdjustdbqld1;
		this.cfgjustdbqld2 = cfgjustdbqld2;
		this.qtdjustdbqld2 = qtdjustdbqld2;
		this.cfgjustdbqld3 = cfgjustdbqld3;
		this.qtdjustdbqld3 = qtdjustdbqld3;
		this.ijregultinspqld2s = ijregultinspqld2s;
		this.ijprodxparamfreqs = ijprodxparamfreqs;
		this.ijdrvcntexecprtdefs = ijdrvcntexecprtdefs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "cdgrpparam", column = @Column(name = "CDGRPPARAM", nullable = false, length = 6)) })
	public IjprodxgrpparamId getId() {
		return this.id;
	}

	public void setId(IjprodxgrpparamId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRPPARAM", nullable = false, insertable = false, updatable = false)
	public Ijgrpparaminsp getIjgrpparaminsp() {
		return this.ijgrpparaminsp;
	}

	public void setIjgrpparaminsp(Ijgrpparaminsp ijgrpparaminsp) {
		this.ijgrpparaminsp = ijgrpparaminsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "TAMMINLOTE", nullable = false, precision = 126, scale = 0)
	public double getTamminlote() {
		return this.tamminlote;
	}

	public void setTamminlote(double tamminlote) {
		this.tamminlote = tamminlote;
	}

	@Column(name = "TPFREQUENCIA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpfrequencia() {
		return this.tpfrequencia;
	}

	public void setTpfrequencia(BigDecimal tpfrequencia) {
		this.tpfrequencia = tpfrequencia;
	}

	@Column(name = "QTDPRODALEINIOP", nullable = false, precision = 126, scale = 0)
	public double getQtdprodaleiniop() {
		return this.qtdprodaleiniop;
	}

	public void setQtdprodaleiniop(double qtdprodaleiniop) {
		this.qtdprodaleiniop = qtdprodaleiniop;
	}

	@Column(name = "QTDREJGERACAOALE", nullable = false, precision = 126, scale = 0)
	public double getQtdrejgeracaoale() {
		return this.qtdrejgeracaoale;
	}

	public void setQtdrejgeracaoale(double qtdrejgeracaoale) {
		this.qtdrejgeracaoale = qtdrejgeracaoale;
	}

	@Column(name = "TPCENTRALEXEC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpcentralexec() {
		return this.tpcentralexec;
	}

	public void setTpcentralexec(BigDecimal tpcentralexec) {
		this.tpcentralexec = tpcentralexec;
	}

	@Column(name = "QTDPRODAPOSPROBQLD", nullable = false, precision = 126, scale = 0)
	public double getQtdprodaposprobqld() {
		return this.qtdprodaposprobqld;
	}

	public void setQtdprodaposprobqld(double qtdprodaposprobqld) {
		this.qtdprodaposprobqld = qtdprodaposprobqld;
	}

	@Column(name = "CFGJUSTDBQLD1", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCfgjustdbqld1() {
		return this.cfgjustdbqld1;
	}

	public void setCfgjustdbqld1(BigDecimal cfgjustdbqld1) {
		this.cfgjustdbqld1 = cfgjustdbqld1;
	}

	@Column(name = "QTDJUSTDBQLD1", nullable = false, precision = 22, scale = 0)
	public BigDecimal getQtdjustdbqld1() {
		return this.qtdjustdbqld1;
	}

	public void setQtdjustdbqld1(BigDecimal qtdjustdbqld1) {
		this.qtdjustdbqld1 = qtdjustdbqld1;
	}

	@Column(name = "CFGJUSTDBQLD2", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCfgjustdbqld2() {
		return this.cfgjustdbqld2;
	}

	public void setCfgjustdbqld2(BigDecimal cfgjustdbqld2) {
		this.cfgjustdbqld2 = cfgjustdbqld2;
	}

	@Column(name = "QTDJUSTDBQLD2", nullable = false, precision = 22, scale = 0)
	public BigDecimal getQtdjustdbqld2() {
		return this.qtdjustdbqld2;
	}

	public void setQtdjustdbqld2(BigDecimal qtdjustdbqld2) {
		this.qtdjustdbqld2 = qtdjustdbqld2;
	}

	@Column(name = "CFGJUSTDBQLD3", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCfgjustdbqld3() {
		return this.cfgjustdbqld3;
	}

	public void setCfgjustdbqld3(BigDecimal cfgjustdbqld3) {
		this.cfgjustdbqld3 = cfgjustdbqld3;
	}

	@Column(name = "QTDJUSTDBQLD3", nullable = false, precision = 22, scale = 0)
	public BigDecimal getQtdjustdbqld3() {
		return this.qtdjustdbqld3;
	}

	public void setQtdjustdbqld3(BigDecimal qtdjustdbqld3) {
		this.qtdjustdbqld3 = qtdjustdbqld3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijprodxgrpparam")
	public Set<Ijregultinspqld2> getIjregultinspqld2s() {
		return this.ijregultinspqld2s;
	}

	public void setIjregultinspqld2s(Set<Ijregultinspqld2> ijregultinspqld2s) {
		this.ijregultinspqld2s = ijregultinspqld2s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijprodxgrpparam")
	public Set<Ijprodxparamfreq> getIjprodxparamfreqs() {
		return this.ijprodxparamfreqs;
	}

	public void setIjprodxparamfreqs(Set<Ijprodxparamfreq> ijprodxparamfreqs) {
		this.ijprodxparamfreqs = ijprodxparamfreqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijprodxgrpparam")
	public Set<Ijdrvcntexecprtdef> getIjdrvcntexecprtdefs() {
		return this.ijdrvcntexecprtdefs;
	}

	public void setIjdrvcntexecprtdefs(
			Set<Ijdrvcntexecprtdef> ijdrvcntexecprtdefs) {
		this.ijdrvcntexecprtdefs = ijdrvcntexecprtdefs;
	}

}
