package idw.model.pojos.injet;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ijqldcqipackchem generated by hbm2java
 */
@Entity
@Table(name = "Ijqldcqipackchem",uniqueConstraints = @UniqueConstraint(columnNames = "nropInjet"))
public class Ijqldcqipackchem implements java.io.Serializable {

	private static final long serialVersionUID = 2780667422065274174L;
	private Long idregistro;
	private String nropInjet;
	private String nropErp;
	private int stregistro;
	private String obsregistro;
	private Date dthrregistro;

	public Ijqldcqipackchem() {
	}

	public Ijqldcqipackchem(Long idregistro, String nropInjet,
			String nropErp, int stregistro, Date dthrregistro) {
		this.idregistro = idregistro;
		this.nropInjet = nropInjet;
		this.nropErp = nropErp;
		this.stregistro = stregistro;
		this.dthrregistro = dthrregistro;
	}

	public Ijqldcqipackchem(Long idregistro, String nropInjet,
			String nropErp, int stregistro, String obsregistro,
			Date dthrregistro) {
		this.idregistro = idregistro;
		this.nropInjet = nropInjet;
		this.nropErp = nropErp;
		this.stregistro = stregistro;
		this.obsregistro = obsregistro;
		this.dthrregistro = dthrregistro;
	}

	@Id
	@Column(name = "idregistro", unique = true, nullable = false, precision = 30, scale = 0)
	public Long getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(Long idregistro) {
		this.idregistro = idregistro;
	}

	@Column(name = "nropInjet", unique = true, nullable = false, length = 6)
	public String getNropInjet() {
		return this.nropInjet;
	}

	public void setNropInjet(String nropInjet) {
		this.nropInjet = nropInjet;
	}

	@Column(name = "nropERP", nullable = false, length = 20)
	public String getNropErp() {
		return this.nropErp;
	}

	public void setNropErp(String nropErp) {
		this.nropErp = nropErp;
	}

	@Column(name = "stregistro", nullable = false)
	public int getStregistro() {
		return this.stregistro;
	}

	public void setStregistro(int stregistro) {
		this.stregistro = stregistro;
	}

	@Column(name = "obsregistro")
	public String getObsregistro() {
		return this.obsregistro;
	}

	public void setObsregistro(String obsregistro) {
		this.obsregistro = obsregistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthrregistro", nullable = false, length = 23)
	public Date getDthrregistro() {
		return this.dthrregistro;
	}

	public void setDthrregistro(Date dthrregistro) {
		this.dthrregistro = dthrregistro;
	}

}
