package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijqldprodinsplote generated by hbm2java
 */
@Entity
@Table(name = "IJQLDPRODINSPLOTE")
public class Ijqldprodinsplote implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4195936301860637614L;
	private String nrlote;
	private Ijtbusu ijtbusuByCdusuabriulote;
	private Ijop ijop;
	private Ijtbusu ijtbusuByCdusucanceloulote;
	private Ijtbinj ijtbinj;
	private Ijtbusu ijtbusuByCdusufechoulote;
	private Ijmolpro ijmolpro;
	private Date dthrperiodoprod;
	private Date dthraberturalote;
	private double tamamostra;
	private double tamlote;
	private Date dthrfechamentolote;
	private Character stfechamentolote;
	private Character nivelinspaplicado;
	private Double nivelact;
	private Date dthrcanclote;
	private String obscanc;
	private Set<Ijqldinsploterep> ijqldinsplotereps = new HashSet<Ijqldinsploterep>(
			0);

	public Ijqldprodinsplote() {
	}

	public Ijqldprodinsplote(String nrlote, Ijtbusu ijtbusuByCdusuabriulote,
			Ijop ijop, Ijtbinj ijtbinj, Ijmolpro ijmolpro,
			Date dthrperiodoprod, Date dthraberturalote, double tamamostra,
			double tamlote) {
		this.nrlote = nrlote;
		this.ijtbusuByCdusuabriulote = ijtbusuByCdusuabriulote;
		this.ijop = ijop;
		this.ijtbinj = ijtbinj;
		this.ijmolpro = ijmolpro;
		this.dthrperiodoprod = dthrperiodoprod;
		this.dthraberturalote = dthraberturalote;
		this.tamamostra = tamamostra;
		this.tamlote = tamlote;
	}

	public Ijqldprodinsplote(String nrlote, Ijtbusu ijtbusuByCdusuabriulote,
			Ijop ijop, Ijtbusu ijtbusuByCdusucanceloulote, Ijtbinj ijtbinj,
			Ijtbusu ijtbusuByCdusufechoulote, Ijmolpro ijmolpro,
			Date dthrperiodoprod, Date dthraberturalote, double tamamostra,
			double tamlote, Date dthrfechamentolote,
			Character stfechamentolote, Character nivelinspaplicado,
			Double nivelact, Date dthrcanclote, String obscanc,
			Set<Ijqldinsploterep> ijqldinsplotereps) {
		this.nrlote = nrlote;
		this.ijtbusuByCdusuabriulote = ijtbusuByCdusuabriulote;
		this.ijop = ijop;
		this.ijtbusuByCdusucanceloulote = ijtbusuByCdusucanceloulote;
		this.ijtbinj = ijtbinj;
		this.ijtbusuByCdusufechoulote = ijtbusuByCdusufechoulote;
		this.ijmolpro = ijmolpro;
		this.dthrperiodoprod = dthrperiodoprod;
		this.dthraberturalote = dthraberturalote;
		this.tamamostra = tamamostra;
		this.tamlote = tamlote;
		this.dthrfechamentolote = dthrfechamentolote;
		this.stfechamentolote = stfechamentolote;
		this.nivelinspaplicado = nivelinspaplicado;
		this.nivelact = nivelact;
		this.dthrcanclote = dthrcanclote;
		this.obscanc = obscanc;
		this.ijqldinsplotereps = ijqldinsplotereps;
	}

	@Id
	@Column(name = "NRLOTE", unique = true, nullable = false, length = 12)
	public String getNrlote() {
		return this.nrlote;
	}

	public void setNrlote(String nrlote) {
		this.nrlote = nrlote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUABRIULOTE", nullable = false)
	public Ijtbusu getIjtbusuByCdusuabriulote() {
		return this.ijtbusuByCdusuabriulote;
	}

	public void setIjtbusuByCdusuabriulote(Ijtbusu ijtbusuByCdusuabriulote) {
		this.ijtbusuByCdusuabriulote = ijtbusuByCdusuabriulote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUCANCELOULOTE")
	public Ijtbusu getIjtbusuByCdusucanceloulote() {
		return this.ijtbusuByCdusucanceloulote;
	}

	public void setIjtbusuByCdusucanceloulote(Ijtbusu ijtbusuByCdusucanceloulote) {
		this.ijtbusuByCdusucanceloulote = ijtbusuByCdusucanceloulote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUFECHOULOTE")
	public Ijtbusu getIjtbusuByCdusufechoulote() {
		return this.ijtbusuByCdusufechoulote;
	}

	public void setIjtbusuByCdusufechoulote(Ijtbusu ijtbusuByCdusufechoulote) {
		this.ijtbusuByCdusufechoulote = ijtbusuByCdusufechoulote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false),
			@JoinColumn(name = "DTHRIVALESTRU", referencedColumnName = "DTHRIVAL", nullable = false) })
	public Ijmolpro getIjmolpro() {
		return this.ijmolpro;
	}

	public void setIjmolpro(Ijmolpro ijmolpro) {
		this.ijmolpro = ijmolpro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRPERIODOPROD", nullable = false, length = 7)
	public Date getDthrperiodoprod() {
		return this.dthrperiodoprod;
	}

	public void setDthrperiodoprod(Date dthrperiodoprod) {
		this.dthrperiodoprod = dthrperiodoprod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRABERTURALOTE", nullable = false, length = 7)
	public Date getDthraberturalote() {
		return this.dthraberturalote;
	}

	public void setDthraberturalote(Date dthraberturalote) {
		this.dthraberturalote = dthraberturalote;
	}

	@Column(name = "TAMAMOSTRA", nullable = false, precision = 126, scale = 0)
	public double getTamamostra() {
		return this.tamamostra;
	}

	public void setTamamostra(double tamamostra) {
		this.tamamostra = tamamostra;
	}

	@Column(name = "TAMLOTE", nullable = false, precision = 126, scale = 0)
	public double getTamlote() {
		return this.tamlote;
	}

	public void setTamlote(double tamlote) {
		this.tamlote = tamlote;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFECHAMENTOLOTE", length = 7)
	public Date getDthrfechamentolote() {
		return this.dthrfechamentolote;
	}

	public void setDthrfechamentolote(Date dthrfechamentolote) {
		this.dthrfechamentolote = dthrfechamentolote;
	}

	@Column(name = "STFECHAMENTOLOTE", length = 1)
	public Character getStfechamentolote() {
		return this.stfechamentolote;
	}

	public void setStfechamentolote(Character stfechamentolote) {
		this.stfechamentolote = stfechamentolote;
	}

	@Column(name = "NIVELINSPAPLICADO", length = 1)
	public Character getNivelinspaplicado() {
		return this.nivelinspaplicado;
	}

	public void setNivelinspaplicado(Character nivelinspaplicado) {
		this.nivelinspaplicado = nivelinspaplicado;
	}

	@Column(name = "NIVELACT", precision = 126, scale = 0)
	public Double getNivelact() {
		return this.nivelact;
	}

	public void setNivelact(Double nivelact) {
		this.nivelact = nivelact;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRCANCLOTE", length = 7)
	public Date getDthrcanclote() {
		return this.dthrcanclote;
	}

	public void setDthrcanclote(Date dthrcanclote) {
		this.dthrcanclote = dthrcanclote;
	}

	@Column(name = "OBSCANC")
	public String getObscanc() {
		return this.obscanc;
	}

	public void setObscanc(String obscanc) {
		this.obscanc = obscanc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijqldprodinsplote")
	public Set<Ijqldinsploterep> getIjqldinsplotereps() {
		return this.ijqldinsplotereps;
	}

	public void setIjqldinsplotereps(Set<Ijqldinsploterep> ijqldinsplotereps) {
		this.ijqldinsplotereps = ijqldinsplotereps;
	}

}
