package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijqldsupervisor generated by hbm2java
 */
@Entity
@Table(name = "IJQLDSUPERVISOR")
public class Ijqldsupervisor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -540740042121865499L;
	private IjqldsupervisorId id;
	private Ijtbusu ijtbusu;
	private Ijtbinj ijtbinj;
	private Date dthrinspecao;

	public Ijqldsupervisor() {
	}

	public Ijqldsupervisor(IjqldsupervisorId id, Ijtbinj ijtbinj) {
		this.id = id;
		this.ijtbinj = ijtbinj;
	}

	public Ijqldsupervisor(IjqldsupervisorId id, Ijtbusu ijtbusu,
			Ijtbinj ijtbinj, Date dthrinspecao) {
		this.id = id;
		this.ijtbusu = ijtbusu;
		this.ijtbinj = ijtbinj;
		this.dthrinspecao = dthrinspecao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthriniintervalo", column = @Column(name = "DTHRINIINTERVALO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public IjqldsupervisorId getId() {
		return this.id;
	}

	public void setId(IjqldsupervisorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDSUPERVISOR")
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRINSPECAO", length = 7)
	public Date getDthrinspecao() {
		return this.dthrinspecao;
	}

	public void setDthrinspecao(Date dthrinspecao) {
		this.dthrinspecao = dthrinspecao;
	}

}
