package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijqldinspecao generated by hbm2java
 */
@Entity
@Table(name = "IJQLDINSPECAO")
public class Ijqldinspecao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7432105187036882025L;
	private IjqldinspecaoId id;
	private Ijtbusu ijtbusuByCdusuariornc;
	private Ijop ijop;
	private Ijtbusu ijtbusuByCdusuarioexclusao;
	private Ijtbinj ijtbinj;
	private Ijmolpro ijmolpro;
	private Ijtbusu ijtbusuByCdusuariobaixa;
	private Ijtbusu ijtbusuByCdusuarioinspecao;
	private Ijtbref ijtbref;
	private Ijtbusu ijtbusuByCdusuarioalteracao;

	public Ijqldinspecao() {
	}

	public Ijqldinspecao(IjqldinspecaoId id, Ijop ijop, Ijtbinj ijtbinj,
			Ijmolpro ijmolpro, Ijtbusu ijtbusuByCdusuarioinspecao,
			Ijtbref ijtbref) {
		this.id = id;
		this.ijop = ijop;
		this.ijtbinj = ijtbinj;
		this.ijmolpro = ijmolpro;
		this.ijtbusuByCdusuarioinspecao = ijtbusuByCdusuarioinspecao;
		this.ijtbref = ijtbref;
	}

	public Ijqldinspecao(IjqldinspecaoId id, Ijtbusu ijtbusuByCdusuariornc,
			Ijop ijop, Ijtbusu ijtbusuByCdusuarioexclusao, Ijtbinj ijtbinj,
			Ijmolpro ijmolpro, Ijtbusu ijtbusuByCdusuariobaixa,
			Ijtbusu ijtbusuByCdusuarioinspecao, Ijtbref ijtbref,
			Ijtbusu ijtbusuByCdusuarioalteracao) {
		this.id = id;
		this.ijtbusuByCdusuariornc = ijtbusuByCdusuariornc;
		this.ijop = ijop;
		this.ijtbusuByCdusuarioexclusao = ijtbusuByCdusuarioexclusao;
		this.ijtbinj = ijtbinj;
		this.ijmolpro = ijmolpro;
		this.ijtbusuByCdusuariobaixa = ijtbusuByCdusuariobaixa;
		this.ijtbusuByCdusuarioinspecao = ijtbusuByCdusuarioinspecao;
		this.ijtbref = ijtbref;
		this.ijtbusuByCdusuarioalteracao = ijtbusuByCdusuarioalteracao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "dthrival", column = @Column(name = "DTHRIVAL", nullable = false, length = 7)),
			@AttributeOverride(name = "cdrefugo", column = @Column(name = "CDREFUGO", nullable = false, length = 6)),
			@AttributeOverride(name = "cdusuarioinspecao", column = @Column(name = "CDUSUARIOINSPECAO", nullable = false, length = 6)),
			@AttributeOverride(name = "qtpcsref", column = @Column(name = "QTPCSREF", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "dthrinspecao", column = @Column(name = "DTHRINSPECAO", nullable = false, length = 7)),
			@AttributeOverride(name = "observacao", column = @Column(name = "OBSERVACAO", length = 200)),
			@AttributeOverride(name = "nrrnc", column = @Column(name = "NRRNC", length = 20)),
			@AttributeOverride(name = "cdusuariornc", column = @Column(name = "CDUSUARIORNC", length = 6)),
			@AttributeOverride(name = "dthrrnc", column = @Column(name = "DTHRRNC", length = 7)),
			@AttributeOverride(name = "cdusuariobaixa", column = @Column(name = "CDUSUARIOBAIXA", length = 6)),
			@AttributeOverride(name = "dthrbaixa", column = @Column(name = "DTHRBAIXA", length = 7)),
			@AttributeOverride(name = "stbaixa", column = @Column(name = "STBAIXA", length = 1)),
			@AttributeOverride(name = "cdusuarioalteracao", column = @Column(name = "CDUSUARIOALTERACAO", length = 6)),
			@AttributeOverride(name = "dthralteracao", column = @Column(name = "DTHRALTERACAO", length = 7)),
			@AttributeOverride(name = "cdusuarioexclusao", column = @Column(name = "CDUSUARIOEXCLUSAO", length = 6)),
			@AttributeOverride(name = "dthrexclusao", column = @Column(name = "DTHREXCLUSAO", length = 7)),
			@AttributeOverride(name = "dthriniintervalo", column = @Column(name = "DTHRINIINTERVALO", length = 7)) })
	public IjqldinspecaoId getId() {
		return this.id;
	}

	public void setId(IjqldinspecaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIORNC", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuariornc() {
		return this.ijtbusuByCdusuariornc;
	}

	public void setIjtbusuByCdusuariornc(Ijtbusu ijtbusuByCdusuariornc) {
		this.ijtbusuByCdusuariornc = ijtbusuByCdusuariornc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIOEXCLUSAO", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuarioexclusao() {
		return this.ijtbusuByCdusuarioexclusao;
	}

	public void setIjtbusuByCdusuarioexclusao(Ijtbusu ijtbusuByCdusuarioexclusao) {
		this.ijtbusuByCdusuarioexclusao = ijtbusuByCdusuarioexclusao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "DTHRIVAL", referencedColumnName = "DTHRIVAL", nullable = false, insertable = false, updatable = false) })
	public Ijmolpro getIjmolpro() {
		return this.ijmolpro;
	}

	public void setIjmolpro(Ijmolpro ijmolpro) {
		this.ijmolpro = ijmolpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIOBAIXA", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuariobaixa() {
		return this.ijtbusuByCdusuariobaixa;
	}

	public void setIjtbusuByCdusuariobaixa(Ijtbusu ijtbusuByCdusuariobaixa) {
		this.ijtbusuByCdusuariobaixa = ijtbusuByCdusuariobaixa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIOINSPECAO", nullable = false, insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuarioinspecao() {
		return this.ijtbusuByCdusuarioinspecao;
	}

	public void setIjtbusuByCdusuarioinspecao(Ijtbusu ijtbusuByCdusuarioinspecao) {
		this.ijtbusuByCdusuarioinspecao = ijtbusuByCdusuarioinspecao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDREFUGO", nullable = false, insertable = false, updatable = false)
	public Ijtbref getIjtbref() {
		return this.ijtbref;
	}

	public void setIjtbref(Ijtbref ijtbref) {
		this.ijtbref = ijtbref;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIOALTERACAO", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuarioalteracao() {
		return this.ijtbusuByCdusuarioalteracao;
	}

	public void setIjtbusuByCdusuarioalteracao(
			Ijtbusu ijtbusuByCdusuarioalteracao) {
		this.ijtbusuByCdusuarioalteracao = ijtbusuByCdusuarioalteracao;
	}

}
