package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijreajuscav generated by hbm2java
 */
@Entity
@Table(name = "IJREAJUSCAV")
public class Ijreajuscav implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2115357437978823705L;
	private IjreajuscavId id;
	private Ijestmol ijestmol;
	private Ijtbusu ijtbusu;
	private Ijtbjuscav ijtbjuscav;
	private String cdturnoref;
	private Date dtrefturno;

	public Ijreajuscav() {
	}

	public Ijreajuscav(IjreajuscavId id, Ijestmol ijestmol, Ijtbusu ijtbusu,
			Ijtbjuscav ijtbjuscav, String cdturnoref, Date dtrefturno) {
		this.id = id;
		this.ijestmol = ijestmol;
		this.ijtbusu = ijtbusu;
		this.ijtbjuscav = ijtbjuscav;
		this.cdturnoref = cdturnoref;
		this.dtrefturno = dtrefturno;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "dthrivalestru", column = @Column(name = "DTHRIVALESTRU", nullable = false, length = 7)) })
	public IjreajuscavId getId() {
		return this.id;
	}

	public void setId(IjreajuscavId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false, insertable = false, updatable = false) })
	public Ijestmol getIjestmol() {
		return this.ijestmol;
	}

	public void setIjestmol(Ijestmol ijestmol) {
		this.ijestmol = ijestmol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSURESP", nullable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDJUSCAV", nullable = false)
	public Ijtbjuscav getIjtbjuscav() {
		return this.ijtbjuscav;
	}

	public void setIjtbjuscav(Ijtbjuscav ijtbjuscav) {
		this.ijtbjuscav = ijtbjuscav;
	}

	@Column(name = "CDTURNOREF", nullable = false, length = 6)
	public String getCdturnoref() {
		return this.cdturnoref;
	}

	public void setCdturnoref(String cdturnoref) {
		this.cdturnoref = cdturnoref;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTREFTURNO", nullable = false, length = 7)
	public Date getDtrefturno() {
		return this.dtrefturno;
	}

	public void setDtrefturno(Date dtrefturno) {
		this.dtrefturno = dtrefturno;
	}

}
