package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijregultinspqld2fr generated by hbm2java
 */
@Entity
@Table(name = "IJREGULTINSPQLD2FR")
public class Ijregultinspqld2fr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3047873115101248459L;
	private Ijregultinspqld2frId id;
	private Ijregultinspqld2 ijregultinspqld2;

	public Ijregultinspqld2fr() {
	}

	public Ijregultinspqld2fr(Ijregultinspqld2frId id,
			Ijregultinspqld2 ijregultinspqld2) {
		this.id = id;
		this.ijregultinspqld2 = ijregultinspqld2;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "cdgrpparam", column = @Column(name = "CDGRPPARAM", nullable = false, length = 6)),
			@AttributeOverride(name = "vlreferencia", column = @Column(name = "VLREFERENCIA", nullable = false, precision = 126, scale = 0)) })
	public Ijregultinspqld2frId getId() {
		return this.id;
	}

	public void setId(Ijregultinspqld2frId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "NROP", referencedColumnName = "NROP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDGRPPARAM", referencedColumnName = "CDGRPPARAM", nullable = false, insertable = false, updatable = false) })
	public Ijregultinspqld2 getIjregultinspqld2() {
		return this.ijregultinspqld2;
	}

	public void setIjregultinspqld2(Ijregultinspqld2 ijregultinspqld2) {
		this.ijregultinspqld2 = ijregultinspqld2;
	}

}
