package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijrelproreflog generated by hbm2java
 */
@Entity
@Table(name = "IJRELPROREFLOG")
public class Ijrelproreflog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9047537659300155172L;
	private String idlogrelproref;
	private String cdmestre;
	private String cdproduto;
	private String cdrefugo;
	private char tpmanutencao;
	private char stlog;
	private Date dthrstlog;

	public Ijrelproreflog() {
	}

	public Ijrelproreflog(String idlogrelproref, String cdmestre,
			String cdproduto, String cdrefugo, char tpmanutencao, char stlog,
			Date dthrstlog) {
		this.idlogrelproref = idlogrelproref;
		this.cdmestre = cdmestre;
		this.cdproduto = cdproduto;
		this.cdrefugo = cdrefugo;
		this.tpmanutencao = tpmanutencao;
		this.stlog = stlog;
		this.dthrstlog = dthrstlog;
	}

	@Id
	@Column(name = "IDLOGRELPROREF", unique = true, nullable = false, length = 15)
	public String getIdlogrelproref() {
		return this.idlogrelproref;
	}

	public void setIdlogrelproref(String idlogrelproref) {
		this.idlogrelproref = idlogrelproref;
	}

	@Column(name = "CDMESTRE", nullable = false, length = 6)
	public String getCdmestre() {
		return this.cdmestre;
	}

	public void setCdmestre(String cdmestre) {
		this.cdmestre = cdmestre;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "CDREFUGO", nullable = false, length = 6)
	public String getCdrefugo() {
		return this.cdrefugo;
	}

	public void setCdrefugo(String cdrefugo) {
		this.cdrefugo = cdrefugo;
	}

	@Column(name = "TPMANUTENCAO", nullable = false, length = 1)
	public char getTpmanutencao() {
		return this.tpmanutencao;
	}

	public void setTpmanutencao(char tpmanutencao) {
		this.tpmanutencao = tpmanutencao;
	}

	@Column(name = "STLOG", nullable = false, length = 1)
	public char getStlog() {
		return this.stlog;
	}

	public void setStlog(char stlog) {
		this.stlog = stlog;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRSTLOG", nullable = false, length = 7)
	public Date getDthrstlog() {
		return this.dthrstlog;
	}

	public void setDthrstlog(Date dthrstlog) {
		this.dthrstlog = dthrstlog;
	}

}
