package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijreamovsemprog generated by hbm2java
 */
@Entity
@Table(name = "IJREAMOVSEMPROG")
public class Ijreamovsemprog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7535234760659011215L;
	private IjreamovsemprogId id;
	private Ijtbinj ijtbinj;
	private Ijtbmotsemprog ijtbmotsemprog;
	private Ijtbusu ijtbusuByCdtecfsemprog;
	private Ijtbusu ijtbusuByCdtecisemprog;
	private Date dthrfsemprog;

	public Ijreamovsemprog() {
	}

	public Ijreamovsemprog(IjreamovsemprogId id, Ijtbinj ijtbinj,
			Ijtbmotsemprog ijtbmotsemprog, Ijtbusu ijtbusuByCdtecisemprog) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijtbmotsemprog = ijtbmotsemprog;
		this.ijtbusuByCdtecisemprog = ijtbusuByCdtecisemprog;
	}

	public Ijreamovsemprog(IjreamovsemprogId id, Ijtbinj ijtbinj,
			Ijtbmotsemprog ijtbmotsemprog, Ijtbusu ijtbusuByCdtecfsemprog,
			Ijtbusu ijtbusuByCdtecisemprog, Date dthrfsemprog) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijtbmotsemprog = ijtbmotsemprog;
		this.ijtbusuByCdtecfsemprog = ijtbusuByCdtecfsemprog;
		this.ijtbusuByCdtecisemprog = ijtbusuByCdtecisemprog;
		this.dthrfsemprog = dthrfsemprog;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrisemprog", column = @Column(name = "DTHRISEMPROG", nullable = false, length = 7)) })
	public IjreamovsemprogId getId() {
		return this.id;
	}

	public void setId(IjreamovsemprogId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMOTSEMPROG", nullable = false)
	public Ijtbmotsemprog getIjtbmotsemprog() {
		return this.ijtbmotsemprog;
	}

	public void setIjtbmotsemprog(Ijtbmotsemprog ijtbmotsemprog) {
		this.ijtbmotsemprog = ijtbmotsemprog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTECFSEMPROG")
	public Ijtbusu getIjtbusuByCdtecfsemprog() {
		return this.ijtbusuByCdtecfsemprog;
	}

	public void setIjtbusuByCdtecfsemprog(Ijtbusu ijtbusuByCdtecfsemprog) {
		this.ijtbusuByCdtecfsemprog = ijtbusuByCdtecfsemprog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTECISEMPROG", nullable = false)
	public Ijtbusu getIjtbusuByCdtecisemprog() {
		return this.ijtbusuByCdtecisemprog;
	}

	public void setIjtbusuByCdtecisemprog(Ijtbusu ijtbusuByCdtecisemprog) {
		this.ijtbusuByCdtecisemprog = ijtbusuByCdtecisemprog;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFSEMPROG", length = 7)
	public Date getDthrfsemprog() {
		return this.dthrfsemprog;
	}

	public void setDthrfsemprog(Date dthrfsemprog) {
		this.dthrfsemprog = dthrfsemprog;
	}

}
