package idw.model.pojos.injet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijreproms generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="ijreproms"
	, uniqueConstraints = @UniqueConstraint(columnNames={"ano", "mes", "cdturno"}) 
)
public class Ijreproms  implements java.io.Serializable {


	private long idReproms;
	private Ijtbtur ijtbtur;
	private Integer ano;
	private Integer mes;

	public Ijreproms() {
	}


	public Ijreproms(long idReproms, Ijtbtur ijtbtur) {
		this.idReproms = idReproms;
		this.ijtbtur = ijtbtur;
	}
	public Ijreproms(long idReproms, Ijtbtur ijtbtur, Integer ano, Integer mes) {
		this.idReproms = idReproms;
		this.ijtbtur = ijtbtur;
		this.ano = ano;
		this.mes = mes;
	}

	@Id 
	@javax.persistence.GeneratedValue(strategy=GenerationType.AUTO, generator = "IJREPROMS_SEQ")
	@SequenceGenerator(name = "IJREPROMS_SEQ", sequenceName = "ijreproms_seq")
	@Column(name="id_reproms", unique=true, nullable=false)
	public long getIdReproms() {
		return this.idReproms;
	}

	public void setIdReproms(long idReproms) {
		this.idReproms = idReproms;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="cdturno", nullable=false)
	public Ijtbtur getIjtbtur() {
		return this.ijtbtur;
	}

	public void setIjtbtur(Ijtbtur ijtbtur) {
		this.ijtbtur = ijtbtur;
	}

	@Column(name="ano")
	public Integer getAno() {
		return this.ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	@Column(name="mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}




}


