package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjrefmanId generated by hbm2java
 */
@Embeddable
public class IjrefmanId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4004569348923037175L;
	private String nrop;
	private String cdmolde;
	private String cdinjetora;
	private String cdestrutura;
	private String cdproduto;
	private Date dthrival;
	private String cdrefugo;
	private double qtpcsref;
	private Date dtrefturno;
	private String cdturno;
	private Date dthrinclusao;
	private String cdusuarioinclusao;
	private Date dthrexclusao;
	private String cdusuarioexclusao;

	public IjrefmanId() {
	}

	public IjrefmanId(String nrop, String cdmolde, String cdestrutura,
			String cdproduto, Date dthrival, String cdrefugo, double qtpcsref,
			Date dtrefturno, String cdturno, Date dthrinclusao,
			String cdusuarioinclusao) {
		this.nrop = nrop;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.cdproduto = cdproduto;
		this.dthrival = dthrival;
		this.cdrefugo = cdrefugo;
		this.qtpcsref = qtpcsref;
		this.dtrefturno = dtrefturno;
		this.cdturno = cdturno;
		this.dthrinclusao = dthrinclusao;
		this.cdusuarioinclusao = cdusuarioinclusao;
	}

	public IjrefmanId(String nrop, String cdmolde, String cdinjetora,
			String cdestrutura, String cdproduto, Date dthrival,
			String cdrefugo, double qtpcsref, Date dtrefturno, String cdturno,
			Date dthrinclusao, String cdusuarioinclusao, Date dthrexclusao,
			String cdusuarioexclusao) {
		this.nrop = nrop;
		this.cdmolde = cdmolde;
		this.cdinjetora = cdinjetora;
		this.cdestrutura = cdestrutura;
		this.cdproduto = cdproduto;
		this.dthrival = dthrival;
		this.cdrefugo = cdrefugo;
		this.qtpcsref = qtpcsref;
		this.dtrefturno = dtrefturno;
		this.cdturno = cdturno;
		this.dthrinclusao = dthrinclusao;
		this.cdusuarioinclusao = cdusuarioinclusao;
		this.dthrexclusao = dthrexclusao;
		this.cdusuarioexclusao = cdusuarioexclusao;
	}

	@Column(name = "NROP", nullable = false, length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "CDMOLDE", nullable = false, length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "CDINJETORA", length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Column(name = "CDESTRUTURA", nullable = false, length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "DTHRIVAL", nullable = false, length = 7)
	public Date getDthrival() {
		return this.dthrival;
	}

	public void setDthrival(Date dthrival) {
		this.dthrival = dthrival;
	}

	@Column(name = "CDREFUGO", nullable = false, length = 6)
	public String getCdrefugo() {
		return this.cdrefugo;
	}

	public void setCdrefugo(String cdrefugo) {
		this.cdrefugo = cdrefugo;
	}

	@Column(name = "QTPCSREF", nullable = false, precision = 126, scale = 0)
	public double getQtpcsref() {
		return this.qtpcsref;
	}

	public void setQtpcsref(double qtpcsref) {
		this.qtpcsref = qtpcsref;
	}

	@Column(name = "DTREFTURNO", nullable = false, length = 7)
	public Date getDtrefturno() {
		return this.dtrefturno;
	}

	public void setDtrefturno(Date dtrefturno) {
		this.dtrefturno = dtrefturno;
	}

	@Column(name = "CDTURNO", nullable = false, length = 6)
	public String getCdturno() {
		return this.cdturno;
	}

	public void setCdturno(String cdturno) {
		this.cdturno = cdturno;
	}

	@Column(name = "DTHRINCLUSAO", nullable = false, length = 7)
	public Date getDthrinclusao() {
		return this.dthrinclusao;
	}

	public void setDthrinclusao(Date dthrinclusao) {
		this.dthrinclusao = dthrinclusao;
	}

	@Column(name = "CDUSUARIOINCLUSAO", nullable = false, length = 6)
	public String getCdusuarioinclusao() {
		return this.cdusuarioinclusao;
	}

	public void setCdusuarioinclusao(String cdusuarioinclusao) {
		this.cdusuarioinclusao = cdusuarioinclusao;
	}

	@Column(name = "DTHREXCLUSAO", length = 7)
	public Date getDthrexclusao() {
		return this.dthrexclusao;
	}

	public void setDthrexclusao(Date dthrexclusao) {
		this.dthrexclusao = dthrexclusao;
	}

	@Column(name = "CDUSUARIOEXCLUSAO", length = 6)
	public String getCdusuarioexclusao() {
		return this.cdusuarioexclusao;
	}

	public void setCdusuarioexclusao(String cdusuarioexclusao) {
		this.cdusuarioexclusao = cdusuarioexclusao;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjrefmanId))
			return false;
		IjrefmanId castOther = (IjrefmanId) other;

		return ((this.getNrop() == castOther.getNrop()) || (this.getNrop() != null
				&& castOther.getNrop() != null && this.getNrop().equals(
				castOther.getNrop())))
				&& ((this.getCdmolde() == castOther.getCdmolde()) || (this
						.getCdmolde() != null && castOther.getCdmolde() != null && this
						.getCdmolde().equals(castOther.getCdmolde())))
				&& ((this.getCdinjetora() == castOther.getCdinjetora()) || (this
						.getCdinjetora() != null
						&& castOther.getCdinjetora() != null && this
						.getCdinjetora().equals(castOther.getCdinjetora())))
				&& ((this.getCdestrutura() == castOther.getCdestrutura()) || (this
						.getCdestrutura() != null
						&& castOther.getCdestrutura() != null && this
						.getCdestrutura().equals(castOther.getCdestrutura())))
				&& ((this.getCdproduto() == castOther.getCdproduto()) || (this
						.getCdproduto() != null
						&& castOther.getCdproduto() != null && this
						.getCdproduto().equals(castOther.getCdproduto())))
				&& ((this.getDthrival() == castOther.getDthrival()) || (this
						.getDthrival() != null
						&& castOther.getDthrival() != null && this
						.getDthrival().equals(castOther.getDthrival())))
				&& ((this.getCdrefugo() == castOther.getCdrefugo()) || (this
						.getCdrefugo() != null
						&& castOther.getCdrefugo() != null && this
						.getCdrefugo().equals(castOther.getCdrefugo())))
				&& (this.getQtpcsref() == castOther.getQtpcsref())
				&& ((this.getDtrefturno() == castOther.getDtrefturno()) || (this
						.getDtrefturno() != null
						&& castOther.getDtrefturno() != null && this
						.getDtrefturno().equals(castOther.getDtrefturno())))
				&& ((this.getCdturno() == castOther.getCdturno()) || (this
						.getCdturno() != null && castOther.getCdturno() != null && this
						.getCdturno().equals(castOther.getCdturno())))
				&& ((this.getDthrinclusao() == castOther.getDthrinclusao()) || (this
						.getDthrinclusao() != null
						&& castOther.getDthrinclusao() != null && this
						.getDthrinclusao().equals(castOther.getDthrinclusao())))
				&& ((this.getCdusuarioinclusao() == castOther
						.getCdusuarioinclusao()) || (this
						.getCdusuarioinclusao() != null
						&& castOther.getCdusuarioinclusao() != null && this
						.getCdusuarioinclusao().equals(
								castOther.getCdusuarioinclusao())))
				&& ((this.getDthrexclusao() == castOther.getDthrexclusao()) || (this
						.getDthrexclusao() != null
						&& castOther.getDthrexclusao() != null && this
						.getDthrexclusao().equals(castOther.getDthrexclusao())))
				&& ((this.getCdusuarioexclusao() == castOther
						.getCdusuarioexclusao()) || (this
						.getCdusuarioexclusao() != null
						&& castOther.getCdusuarioexclusao() != null && this
						.getCdusuarioexclusao().equals(
								castOther.getCdusuarioexclusao())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNrop() == null ? 0 : this.getNrop().hashCode());
		result = 37 * result
				+ (getCdmolde() == null ? 0 : this.getCdmolde().hashCode());
		result = 37
				* result
				+ (getCdinjetora() == null ? 0 : this.getCdinjetora()
						.hashCode());
		result = 37
				* result
				+ (getCdestrutura() == null ? 0 : this.getCdestrutura()
						.hashCode());
		result = 37 * result
				+ (getCdproduto() == null ? 0 : this.getCdproduto().hashCode());
		result = 37 * result
				+ (getDthrival() == null ? 0 : this.getDthrival().hashCode());
		result = 37 * result
				+ (getCdrefugo() == null ? 0 : this.getCdrefugo().hashCode());
		result = 37 * result + (int) this.getQtpcsref();
		result = 37
				* result
				+ (getDtrefturno() == null ? 0 : this.getDtrefturno()
						.hashCode());
		result = 37 * result
				+ (getCdturno() == null ? 0 : this.getCdturno().hashCode());
		result = 37
				* result
				+ (getDthrinclusao() == null ? 0 : this.getDthrinclusao()
						.hashCode());
		result = 37
				* result
				+ (getCdusuarioinclusao() == null ? 0 : this
						.getCdusuarioinclusao().hashCode());
		result = 37
				* result
				+ (getDthrexclusao() == null ? 0 : this.getDthrexclusao()
						.hashCode());
		result = 37
				* result
				+ (getCdusuarioexclusao() == null ? 0 : this
						.getCdusuarioexclusao().hashCode());
		return result;
	}

}
