package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijreaparaberta generated by hbm2java
 */
@Entity
@Table(name = "IJREAPARABERTA")
public class Ijreaparaberta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2479694381096042388L;
	private String cdinjetora;
	private Date dthriparada;
	private Date dthrultconsol;
	private String cdmolde;
	private String cdestrutura;
	private Date dthrivalestru;
	private Date dthrivalcic;
	private String nrop;
	private String cdparada;

	public Ijreaparaberta() {
	}

	public Ijreaparaberta(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	public Ijreaparaberta(String cdinjetora, Date dthriparada,
			Date dthrultconsol, String cdmolde, String cdestrutura,
			Date dthrivalestru, Date dthrivalcic, String nrop, String cdparada) {
		this.cdinjetora = cdinjetora;
		this.dthriparada = dthriparada;
		this.dthrultconsol = dthrultconsol;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.dthrivalestru = dthrivalestru;
		this.dthrivalcic = dthrivalcic;
		this.nrop = nrop;
		this.cdparada = cdparada;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIPARADA", length = 7)
	public Date getDthriparada() {
		return this.dthriparada;
	}

	public void setDthriparada(Date dthriparada) {
		this.dthriparada = dthriparada;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRULTCONSOL", length = 7)
	public Date getDthrultconsol() {
		return this.dthrultconsol;
	}

	public void setDthrultconsol(Date dthrultconsol) {
		this.dthrultconsol = dthrultconsol;
	}

	@Column(name = "CDMOLDE", length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "CDESTRUTURA", length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIVALESTRU", length = 7)
	public Date getDthrivalestru() {
		return this.dthrivalestru;
	}

	public void setDthrivalestru(Date dthrivalestru) {
		this.dthrivalestru = dthrivalestru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIVALCIC", length = 7)
	public Date getDthrivalcic() {
		return this.dthrivalcic;
	}

	public void setDthrivalcic(Date dthrivalcic) {
		this.dthrivalcic = dthrivalcic;
	}

	@Column(name = "NROP", length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "CDPARADA", length = 6)
	public String getCdparada() {
		return this.cdparada;
	}

	public void setCdparada(String cdparada) {
		this.cdparada = cdparada;
	}

}
