package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijregultinspqld1fr generated by hbm2java
 */
@Entity
@Table(name = "IJREGULTINSPQLD1FR")
public class Ijregultinspqld1fr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3160014193871300883L;
	private Ijregultinspqld1frId id;
	private Ijregultinspqld1 ijregultinspqld1;

	public Ijregultinspqld1fr() {
	}

	public Ijregultinspqld1fr(Ijregultinspqld1frId id,
			Ijregultinspqld1 ijregultinspqld1) {
		this.id = id;
		this.ijregultinspqld1 = ijregultinspqld1;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "vlreferencia", column = @Column(name = "VLREFERENCIA", nullable = false, precision = 126, scale = 0)) })
	public Ijregultinspqld1frId getId() {
		return this.id;
	}

	public void setId(Ijregultinspqld1frId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "NROP", referencedColumnName = "NROP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false) })
	public Ijregultinspqld1 getIjregultinspqld1() {
		return this.ijregultinspqld1;
	}

	public void setIjregultinspqld1(Ijregultinspqld1 ijregultinspqld1) {
		this.ijregultinspqld1 = ijregultinspqld1;
	}

}
