package idw.model.pojos.injet;

// Generated 30/07/2013 09:08:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijreaaptpesomedio generated by hbm2java
 */
@Entity
@Table(name = "IJREAAPTPESOMEDIO")
public class Ijreaaptpesomedio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5185469368424066698L;
	private double idregistro;
	private Ijop ijop;
	private Ijfictec ijfictec;
	private Ijtbusu ijtbusu;
	private Ijmolpro ijmolpro;
	private Date dthraptpesomedio;
	private double pesomedio;
	private BigDecimal origemcoleta;

	public Ijreaaptpesomedio() {
	}

	public Ijreaaptpesomedio(double idregistro, Ijop ijop, Ijfictec ijfictec,
			Ijtbusu ijtbusu, Ijmolpro ijmolpro, Date dthraptpesomedio,
			double pesomedio, BigDecimal origemcoleta) {
		this.idregistro = idregistro;
		this.ijop = ijop;
		this.ijfictec = ijfictec;
		this.ijtbusu = ijtbusu;
		this.ijmolpro = ijmolpro;
		this.dthraptpesomedio = dthraptpesomedio;
		this.pesomedio = pesomedio;
		this.origemcoleta = origemcoleta;
	}

	@Id
	@Column(name = "IDREGISTRO", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(double idregistro) {
		this.idregistro = idregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDINJETORA", referencedColumnName = "CDINJETORA", nullable = false),
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false),
			@JoinColumn(name = "DTHRIVALCIC", referencedColumnName = "DTHRIVALCIC", nullable = false) })
	public Ijfictec getIjfictec() {
		return this.ijfictec;
	}

	public void setIjfictec(Ijfictec ijfictec) {
		this.ijfictec = ijfictec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIO", nullable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "DTHRIVALESTRU", referencedColumnName = "DTHRIVAL", nullable = false, insertable = false, updatable = false) })
	public Ijmolpro getIjmolpro() {
		return this.ijmolpro;
	}

	public void setIjmolpro(Ijmolpro ijmolpro) {
		this.ijmolpro = ijmolpro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRAPTPESOMEDIO", nullable = false, length = 7)
	public Date getDthraptpesomedio() {
		return this.dthraptpesomedio;
	}

	public void setDthraptpesomedio(Date dthraptpesomedio) {
		this.dthraptpesomedio = dthraptpesomedio;
	}

	@Column(name = "PESOMEDIO", nullable = false, precision = 126, scale = 0)
	public double getPesomedio() {
		return this.pesomedio;
	}

	public void setPesomedio(double pesomedio) {
		this.pesomedio = pesomedio;
	}

	@Column(name = "ORIGEMCOLETA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOrigemcoleta() {
		return this.origemcoleta;
	}

	public void setOrigemcoleta(BigDecimal origemcoleta) {
		this.origemcoleta = origemcoleta;
	}

}
