package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijreaparoprd generated by hbm2java
 */
@Entity
@Table(name = "IJREAPAROPRD")
public class Ijreaparoprd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6653708947372964815L;
	private IjreaparoprdId id;
	private Ijreapar ijreapar;
	private Ijtbusu ijtbusu;
	private Date dthrlogoutpar;

	public Ijreaparoprd() {
	}

	public Ijreaparoprd(IjreaparoprdId id, Ijreapar ijreapar, Ijtbusu ijtbusu) {
		this.id = id;
		this.ijreapar = ijreapar;
		this.ijtbusu = ijtbusu;
	}

	public Ijreaparoprd(IjreaparoprdId id, Ijreapar ijreapar, Ijtbusu ijtbusu,
			Date dthrlogoutpar) {
		this.id = id;
		this.ijreapar = ijreapar;
		this.ijtbusu = ijtbusu;
		this.dthrlogoutpar = dthrlogoutpar;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthriparada", column = @Column(name = "DTHRIPARADA", nullable = false, length = 7)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdoperador", column = @Column(name = "CDOPERADOR", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrloginpar", column = @Column(name = "DTHRLOGINPAR", nullable = false, length = 7)) })
	public IjreaparoprdId getId() {
		return this.id;
	}

	public void setId(IjreaparoprdId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "DTHRIPARADA", referencedColumnName = "DTHRIPARADA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDINJETORA", referencedColumnName = "CDINJETORA", nullable = false, insertable = false, updatable = false) })
	public Ijreapar getIjreapar() {
		return this.ijreapar;
	}

	public void setIjreapar(Ijreapar ijreapar) {
		this.ijreapar = ijreapar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDOPERADOR", nullable = false, insertable = false, updatable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRLOGOUTPAR", length = 7)
	public Date getDthrlogoutpar() {
		return this.dthrlogoutpar;
	}

	public void setDthrlogoutpar(Date dthrlogoutpar) {
		this.dthrlogoutpar = dthrlogoutpar;
	}

}
