package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijreacicopoprd generated by hbm2java
 */
@Entity
@Table(name = "IJREACICOPOPRD")
public class Ijreacicopoprd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4095480567211201165L;
	private IjreacicopoprdId id;
	private Ijtbusu ijtbusu;
	private Ijreacicop ijreacicop;

	public Ijreacicopoprd() {
	}

	public Ijreacicopoprd(IjreacicopoprdId id, Ijtbusu ijtbusu,
			Ijreacicop ijreacicop) {
		this.id = id;
		this.ijtbusu = ijtbusu;
		this.ijreacicop = ijreacicop;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "dthriciclo", column = @Column(name = "DTHRICICLO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdoperador", column = @Column(name = "CDOPERADOR", nullable = false, length = 6)) })
	public IjreacicopoprdId getId() {
		return this.id;
	}

	public void setId(IjreacicopoprdId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDOPERADOR", nullable = false, insertable = false, updatable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "NROP", referencedColumnName = "NROP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "DTHRICICLO", referencedColumnName = "DTHRICICLO", nullable = false, insertable = false, updatable = false) })
	public Ijreacicop getIjreacicop() {
		return this.ijreacicop;
	}

	public void setIjreacicop(Ijreacicop ijreacicop) {
		this.ijreacicop = ijreacicop;
	}

}
