package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijregultinspqld1 generated by hbm2java
 */
@Entity
@Table(name = "IJREGULTINSPQLD1")
public class Ijregultinspqld1 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5624929327746432825L;
	private Ijregultinspqld1Id id;
	private Ijop ijop;
	private Ijprodinspfreq ijprodinspfreq;
	private double tamminlote;
	private BigDecimal tpfrequencia;
	private double qtdprodaleiniop;
	private double qtdrejgeracaoale;
	private BigDecimal tmpliminspqld;
	private double qtdprodrefultale;
	private Date dthrrefultale;
	private double percrefultale;
	private char houvealertaini;
	private double qtdprodaposprobqld;
	private double qtprodultprobqld;
	private BigDecimal avaliandoprobqld;
	private Set<Ijregultinspqld1fr> ijregultinspqld1frs = new HashSet<Ijregultinspqld1fr>(
			0);

	public Ijregultinspqld1() {
	}

	public Ijregultinspqld1(Ijregultinspqld1Id id, Ijop ijop,
			Ijprodinspfreq ijprodinspfreq, double tamminlote,
			BigDecimal tpfrequencia, double qtdprodaleiniop,
			double qtdrejgeracaoale, BigDecimal tmpliminspqld,
			double qtdprodrefultale, Date dthrrefultale, double percrefultale,
			char houvealertaini, double qtdprodaposprobqld,
			double qtprodultprobqld, BigDecimal avaliandoprobqld) {
		this.id = id;
		this.ijop = ijop;
		this.ijprodinspfreq = ijprodinspfreq;
		this.tamminlote = tamminlote;
		this.tpfrequencia = tpfrequencia;
		this.qtdprodaleiniop = qtdprodaleiniop;
		this.qtdrejgeracaoale = qtdrejgeracaoale;
		this.tmpliminspqld = tmpliminspqld;
		this.qtdprodrefultale = qtdprodrefultale;
		this.dthrrefultale = dthrrefultale;
		this.percrefultale = percrefultale;
		this.houvealertaini = houvealertaini;
		this.qtdprodaposprobqld = qtdprodaposprobqld;
		this.qtprodultprobqld = qtprodultprobqld;
		this.avaliandoprobqld = avaliandoprobqld;
	}

	public Ijregultinspqld1(Ijregultinspqld1Id id, Ijop ijop,
			Ijprodinspfreq ijprodinspfreq, double tamminlote,
			BigDecimal tpfrequencia, double qtdprodaleiniop,
			double qtdrejgeracaoale, BigDecimal tmpliminspqld,
			double qtdprodrefultale, Date dthrrefultale, double percrefultale,
			char houvealertaini, double qtdprodaposprobqld,
			double qtprodultprobqld, BigDecimal avaliandoprobqld,
			Set<Ijregultinspqld1fr> ijregultinspqld1frs) {
		this.id = id;
		this.ijop = ijop;
		this.ijprodinspfreq = ijprodinspfreq;
		this.tamminlote = tamminlote;
		this.tpfrequencia = tpfrequencia;
		this.qtdprodaleiniop = qtdprodaleiniop;
		this.qtdrejgeracaoale = qtdrejgeracaoale;
		this.tmpliminspqld = tmpliminspqld;
		this.qtdprodrefultale = qtdprodrefultale;
		this.dthrrefultale = dthrrefultale;
		this.percrefultale = percrefultale;
		this.houvealertaini = houvealertaini;
		this.qtdprodaposprobqld = qtdprodaposprobqld;
		this.qtprodultprobqld = qtprodultprobqld;
		this.avaliandoprobqld = avaliandoprobqld;
		this.ijregultinspqld1frs = ijregultinspqld1frs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)) })
	public Ijregultinspqld1Id getId() {
		return this.id;
	}

	public void setId(Ijregultinspqld1Id id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijprodinspfreq getIjprodinspfreq() {
		return this.ijprodinspfreq;
	}

	public void setIjprodinspfreq(Ijprodinspfreq ijprodinspfreq) {
		this.ijprodinspfreq = ijprodinspfreq;
	}

	@Column(name = "TAMMINLOTE", nullable = false, precision = 126, scale = 0)
	public double getTamminlote() {
		return this.tamminlote;
	}

	public void setTamminlote(double tamminlote) {
		this.tamminlote = tamminlote;
	}

	@Column(name = "TPFREQUENCIA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpfrequencia() {
		return this.tpfrequencia;
	}

	public void setTpfrequencia(BigDecimal tpfrequencia) {
		this.tpfrequencia = tpfrequencia;
	}

	@Column(name = "QTDPRODALEINIOP", nullable = false, precision = 126, scale = 0)
	public double getQtdprodaleiniop() {
		return this.qtdprodaleiniop;
	}

	public void setQtdprodaleiniop(double qtdprodaleiniop) {
		this.qtdprodaleiniop = qtdprodaleiniop;
	}

	@Column(name = "QTDREJGERACAOALE", nullable = false, precision = 126, scale = 0)
	public double getQtdrejgeracaoale() {
		return this.qtdrejgeracaoale;
	}

	public void setQtdrejgeracaoale(double qtdrejgeracaoale) {
		this.qtdrejgeracaoale = qtdrejgeracaoale;
	}

	@Column(name = "TMPLIMINSPQLD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmpliminspqld() {
		return this.tmpliminspqld;
	}

	public void setTmpliminspqld(BigDecimal tmpliminspqld) {
		this.tmpliminspqld = tmpliminspqld;
	}

	@Column(name = "QTDPRODREFULTALE", nullable = false, precision = 126, scale = 0)
	public double getQtdprodrefultale() {
		return this.qtdprodrefultale;
	}

	public void setQtdprodrefultale(double qtdprodrefultale) {
		this.qtdprodrefultale = qtdprodrefultale;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRREFULTALE", nullable = false, length = 7)
	public Date getDthrrefultale() {
		return this.dthrrefultale;
	}

	public void setDthrrefultale(Date dthrrefultale) {
		this.dthrrefultale = dthrrefultale;
	}

	@Column(name = "PERCREFULTALE", nullable = false, precision = 126, scale = 0)
	public double getPercrefultale() {
		return this.percrefultale;
	}

	public void setPercrefultale(double percrefultale) {
		this.percrefultale = percrefultale;
	}

	@Column(name = "HOUVEALERTAINI", nullable = false, length = 1)
	public char getHouvealertaini() {
		return this.houvealertaini;
	}

	public void setHouvealertaini(char houvealertaini) {
		this.houvealertaini = houvealertaini;
	}

	@Column(name = "QTDPRODAPOSPROBQLD", nullable = false, precision = 126, scale = 0)
	public double getQtdprodaposprobqld() {
		return this.qtdprodaposprobqld;
	}

	public void setQtdprodaposprobqld(double qtdprodaposprobqld) {
		this.qtdprodaposprobqld = qtdprodaposprobqld;
	}

	@Column(name = "QTPRODULTPROBQLD", nullable = false, precision = 126, scale = 0)
	public double getQtprodultprobqld() {
		return this.qtprodultprobqld;
	}

	public void setQtprodultprobqld(double qtprodultprobqld) {
		this.qtprodultprobqld = qtprodultprobqld;
	}

	@Column(name = "AVALIANDOPROBQLD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAvaliandoprobqld() {
		return this.avaliandoprobqld;
	}

	public void setAvaliandoprobqld(BigDecimal avaliandoprobqld) {
		this.avaliandoprobqld = avaliandoprobqld;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijregultinspqld1")
	public Set<Ijregultinspqld1fr> getIjregultinspqld1frs() {
		return this.ijregultinspqld1frs;
	}

	public void setIjregultinspqld1frs(
			Set<Ijregultinspqld1fr> ijregultinspqld1frs) {
		this.ijregultinspqld1frs = ijregultinspqld1frs;
	}

}
