package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijreacic generated by hbm2java
 */
@Entity
@Table(name = "IJREACIC")
public class Ijreacic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1703852717790147132L;
	private IjreacicId id;
	private Ijestmol ijestmol;
	private Ijop ijop;
	private Ijtbinj ijtbinj;
	private Date dthrfciclo;
	private Double teciclo;
	private Double teinjecao;
	private Double teabemol;
	private BigDecimal permanece;
	private String stestado;
	private BigDecimal quedaescravo;
	private BigDecimal forasequencia;
	private Double ciclopadrao;
	private Date dthrivalestru;
	private Date dthrivalcic;
	private Double tmpcicespera;
	private Double tmpcicpadraoespera;

	public Ijreacic() {
	}

	public Ijreacic(IjreacicId id, Ijtbinj ijtbinj) {
		this.id = id;
		this.ijtbinj = ijtbinj;
	}

	public Ijreacic(IjreacicId id, Ijestmol ijestmol, Ijop ijop,
			Ijtbinj ijtbinj, Date dthrfciclo, Double teciclo, Double teinjecao,
			Double teabemol, BigDecimal permanece, String stestado,
			BigDecimal quedaescravo, BigDecimal forasequencia,
			Double ciclopadrao, Date dthrivalestru, Date dthrivalcic,
			Double tmpcicespera, Double tmpcicpadraoespera) {
		this.id = id;
		this.ijestmol = ijestmol;
		this.ijop = ijop;
		this.ijtbinj = ijtbinj;
		this.dthrfciclo = dthrfciclo;
		this.teciclo = teciclo;
		this.teinjecao = teinjecao;
		this.teabemol = teabemol;
		this.permanece = permanece;
		this.stestado = stestado;
		this.quedaescravo = quedaescravo;
		this.forasequencia = forasequencia;
		this.ciclopadrao = ciclopadrao;
		this.dthrivalestru = dthrivalestru;
		this.dthrivalcic = dthrivalcic;
		this.tmpcicespera = tmpcicespera;
		this.tmpcicpadraoespera = tmpcicpadraoespera;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "dthriciclo", column = @Column(name = "DTHRICICLO", nullable = false, length = 7)) })
	public IjreacicId getId() {
		return this.id;
	}

	public void setId(IjreacicId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE"),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA") })
	public Ijestmol getIjestmol() {
		return this.ijestmol;
	}

	public void setIjestmol(Ijestmol ijestmol) {
		this.ijestmol = ijestmol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP")
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRFCICLO", length = 7)
	public Date getDthrfciclo() {
		return this.dthrfciclo;
	}

	public void setDthrfciclo(Date dthrfciclo) {
		this.dthrfciclo = dthrfciclo;
	}

	@Column(name = "TECICLO", precision = 126, scale = 0)
	public Double getTeciclo() {
		return this.teciclo;
	}

	public void setTeciclo(Double teciclo) {
		this.teciclo = teciclo;
	}

	@Column(name = "TEINJECAO", precision = 126, scale = 0)
	public Double getTeinjecao() {
		return this.teinjecao;
	}

	public void setTeinjecao(Double teinjecao) {
		this.teinjecao = teinjecao;
	}

	@Column(name = "TEABEMOL", precision = 126, scale = 0)
	public Double getTeabemol() {
		return this.teabemol;
	}

	public void setTeabemol(Double teabemol) {
		this.teabemol = teabemol;
	}

	@Column(name = "PERMANECE", precision = 22, scale = 0)
	public BigDecimal getPermanece() {
		return this.permanece;
	}

	public void setPermanece(BigDecimal permanece) {
		this.permanece = permanece;
	}

	@Column(name = "STESTADO", length = 18)
	public String getStestado() {
		return this.stestado;
	}

	public void setStestado(String stestado) {
		this.stestado = stestado;
	}

	@Column(name = "QUEDAESCRAVO", precision = 22, scale = 0)
	public BigDecimal getQuedaescravo() {
		return this.quedaescravo;
	}

	public void setQuedaescravo(BigDecimal quedaescravo) {
		this.quedaescravo = quedaescravo;
	}

	@Column(name = "FORASEQUENCIA", precision = 22, scale = 0)
	public BigDecimal getForasequencia() {
		return this.forasequencia;
	}

	public void setForasequencia(BigDecimal forasequencia) {
		this.forasequencia = forasequencia;
	}

	@Column(name = "CICLOPADRAO", precision = 126, scale = 0)
	public Double getCiclopadrao() {
		return this.ciclopadrao;
	}

	public void setCiclopadrao(Double ciclopadrao) {
		this.ciclopadrao = ciclopadrao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIVALESTRU", length = 7)
	public Date getDthrivalestru() {
		return this.dthrivalestru;
	}

	public void setDthrivalestru(Date dthrivalestru) {
		this.dthrivalestru = dthrivalestru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRIVALCIC", length = 7)
	public Date getDthrivalcic() {
		return this.dthrivalcic;
	}

	public void setDthrivalcic(Date dthrivalcic) {
		this.dthrivalcic = dthrivalcic;
	}

	@Column(name = "TMPCICESPERA", precision = 126, scale = 0)
	public Double getTmpcicespera() {
		return this.tmpcicespera;
	}

	public void setTmpcicespera(Double tmpcicespera) {
		this.tmpcicespera = tmpcicespera;
	}

	@Column(name = "TMPCICPADRAOESPERA", precision = 126, scale = 0)
	public Double getTmpcicpadraoespera() {
		return this.tmpcicpadraoespera;
	}

	public void setTmpcicpadraoespera(Double tmpcicpadraoespera) {
		this.tmpcicpadraoespera = tmpcicpadraoespera;
	}

}
