package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijregultocorop generated by hbm2java
 */
@Entity
@Table(name = "IJREGULTOCOROP")
public class Ijregultocorop implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6541301666989601727L;
	private IjregultocoropId id;
	private Ijop ijop;
	private Ijtbinj ijtbinj;
	private Date dthrultimaocor;

	public Ijregultocorop() {
	}

	public Ijregultocorop(IjregultocoropId id, Ijop ijop, Ijtbinj ijtbinj,
			Date dthrultimaocor) {
		this.id = id;
		this.ijop = ijop;
		this.ijtbinj = ijtbinj;
		this.dthrultimaocor = dthrultimaocor;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)) })
	public IjregultocoropId getId() {
		return this.id;
	}

	public void setId(IjregultocoropId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRULTIMAOCOR", nullable = false, length = 7)
	public Date getDthrultimaocor() {
		return this.dthrultimaocor;
	}

	public void setDthrultimaocor(Date dthrultimaocor) {
		this.dthrultimaocor = dthrultimaocor;
	}

}
