package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijrearefoprd generated by hbm2java
 */
@Entity
@Table(name = "IJREAREFOPRD")
public class Ijrearefoprd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4365169528881962348L;
	private IjrearefoprdId id;
	private Ijtbusu ijtbusu;
	private Ijrearef ijrearef;

	public Ijrearefoprd() {
	}

	public Ijrearefoprd(IjrearefoprdId id, Ijtbusu ijtbusu, Ijrearef ijrearef) {
		this.id = id;
		this.ijtbusu = ijtbusu;
		this.ijrearef = ijrearef;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthrirefugo", column = @Column(name = "DTHRIREFUGO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdidentificacao", column = @Column(name = "CDIDENTIFICACAO", nullable = false, length = 1)),
			@AttributeOverride(name = "cdoperador", column = @Column(name = "CDOPERADOR", nullable = false, length = 6)) })
	public IjrearefoprdId getId() {
		return this.id;
	}

	public void setId(IjrearefoprdId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDOPERADOR", nullable = false, insertable = false, updatable = false)
	public Ijtbusu getIjtbusu() {
		return this.ijtbusu;
	}

	public void setIjtbusu(Ijtbusu ijtbusu) {
		this.ijtbusu = ijtbusu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "DTHRIREFUGO", referencedColumnName = "DTHRIREFUGO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDINJETORA", referencedColumnName = "CDINJETORA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDIDENTIFICACAO", referencedColumnName = "CDIDENTIFICACAO", nullable = false, insertable = false, updatable = false) })
	public Ijrearef getIjrearef() {
		return this.ijrearef;
	}

	public void setIjrearef(Ijrearef ijrearef) {
		this.ijrearef = ijrearef;
	}

}
