package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijrefman generated by hbm2java
 */
@Entity
@Table(name = "IJREFMAN")
public class Ijrefman implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8357670146433105981L;
	private IjrefmanId id;
	private Ijtbtur ijtbtur;
	private Ijop ijop;
	private Ijtbusu ijtbusuByCdusuarioexclusao;
	private Ijtbinj ijtbinj;
	private Ijmolpro ijmolpro;
	private Ijtbusu ijtbusuByCdusuarioinclusao;
	private Ijtbref ijtbref;

	public Ijrefman() {
	}

	public Ijrefman(IjrefmanId id, Ijtbtur ijtbtur, Ijop ijop,
			Ijmolpro ijmolpro, Ijtbusu ijtbusuByCdusuarioinclusao,
			Ijtbref ijtbref) {
		this.id = id;
		this.ijtbtur = ijtbtur;
		this.ijop = ijop;
		this.ijmolpro = ijmolpro;
		this.ijtbusuByCdusuarioinclusao = ijtbusuByCdusuarioinclusao;
		this.ijtbref = ijtbref;
	}

	public Ijrefman(IjrefmanId id, Ijtbtur ijtbtur, Ijop ijop,
			Ijtbusu ijtbusuByCdusuarioexclusao, Ijtbinj ijtbinj,
			Ijmolpro ijmolpro, Ijtbusu ijtbusuByCdusuarioinclusao,
			Ijtbref ijtbref) {
		this.id = id;
		this.ijtbtur = ijtbtur;
		this.ijop = ijop;
		this.ijtbusuByCdusuarioexclusao = ijtbusuByCdusuarioexclusao;
		this.ijtbinj = ijtbinj;
		this.ijmolpro = ijmolpro;
		this.ijtbusuByCdusuarioinclusao = ijtbusuByCdusuarioinclusao;
		this.ijtbref = ijtbref;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 10)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", length = 6)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "dthrival", column = @Column(name = "DTHRIVAL", nullable = false, length = 7)),
			@AttributeOverride(name = "cdrefugo", column = @Column(name = "CDREFUGO", nullable = false, length = 6)),
			@AttributeOverride(name = "qtpcsref", column = @Column(name = "QTPCSREF", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "dtrefturno", column = @Column(name = "DTREFTURNO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdturno", column = @Column(name = "CDTURNO", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrinclusao", column = @Column(name = "DTHRINCLUSAO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdusuarioinclusao", column = @Column(name = "CDUSUARIOINCLUSAO", nullable = false, length = 6)),
			@AttributeOverride(name = "dthrexclusao", column = @Column(name = "DTHREXCLUSAO", length = 7)),
			@AttributeOverride(name = "cdusuarioexclusao", column = @Column(name = "CDUSUARIOEXCLUSAO", length = 6)) })
	public IjrefmanId getId() {
		return this.id;
	}

	public void setId(IjrefmanId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTURNO", nullable = false, insertable = false, updatable = false)
	public Ijtbtur getIjtbtur() {
		return this.ijtbtur;
	}

	public void setIjtbtur(Ijtbtur ijtbtur) {
		this.ijtbtur = ijtbtur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP", nullable = false, insertable = false, updatable = false)
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIOEXCLUSAO", insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuarioexclusao() {
		return this.ijtbusuByCdusuarioexclusao;
	}

	public void setIjtbusuByCdusuarioexclusao(Ijtbusu ijtbusuByCdusuarioexclusao) {
		this.ijtbusuByCdusuarioexclusao = ijtbusuByCdusuarioexclusao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDPRODUTO", referencedColumnName = "CDPRODUTO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "DTHRIVAL", referencedColumnName = "DTHRIVAL", nullable = false, insertable = false, updatable = false) })
	public Ijmolpro getIjmolpro() {
		return this.ijmolpro;
	}

	public void setIjmolpro(Ijmolpro ijmolpro) {
		this.ijmolpro = ijmolpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUARIOINCLUSAO", nullable = false, insertable = false, updatable = false)
	public Ijtbusu getIjtbusuByCdusuarioinclusao() {
		return this.ijtbusuByCdusuarioinclusao;
	}

	public void setIjtbusuByCdusuarioinclusao(Ijtbusu ijtbusuByCdusuarioinclusao) {
		this.ijtbusuByCdusuarioinclusao = ijtbusuByCdusuarioinclusao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDREFUGO", nullable = false, insertable = false, updatable = false)
	public Ijtbref getIjtbref() {
		return this.ijtbref;
	}

	public void setIjtbref(Ijtbref ijtbref) {
		this.ijtbref = ijtbref;
	}

}
