package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijrptreports generated by hbm2java
 */
@Entity
@Table(name = "IJRPTREPORTS")
public class Ijrptreports implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7814505066340437022L;
	private IjrptreportsId id;
	private Ijlinguas ijlinguas;
	private String titulo;
	private String subtagrupamento;
	private String subtcontagem;
	private String subtturnos;
	private String subtperiodo;
	private Set<Ijrptlabels> ijrptlabelses = new HashSet<Ijrptlabels>(0);

	public Ijrptreports() {
	}

	public Ijrptreports(IjrptreportsId id, Ijlinguas ijlinguas) {
		this.id = id;
		this.ijlinguas = ijlinguas;
	}

	public Ijrptreports(IjrptreportsId id, Ijlinguas ijlinguas, String titulo,
			String subtagrupamento, String subtcontagem, String subtturnos,
			String subtperiodo, Set<Ijrptlabels> ijrptlabelses) {
		this.id = id;
		this.ijlinguas = ijlinguas;
		this.titulo = titulo;
		this.subtagrupamento = subtagrupamento;
		this.subtcontagem = subtcontagem;
		this.subtturnos = subtturnos;
		this.subtperiodo = subtperiodo;
		this.ijrptlabelses = ijrptlabelses;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdreport", column = @Column(name = "CDREPORT", nullable = false, length = 6)),
			@AttributeOverride(name = "cdlingua", column = @Column(name = "CDLINGUA", nullable = false, length = 6)) })
	public IjrptreportsId getId() {
		return this.id;
	}

	public void setId(IjrptreportsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLINGUA", nullable = false, insertable = false, updatable = false)
	public Ijlinguas getIjlinguas() {
		return this.ijlinguas;
	}

	public void setIjlinguas(Ijlinguas ijlinguas) {
		this.ijlinguas = ijlinguas;
	}

	@Column(name = "TITULO", length = 40)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "SUBTAGRUPAMENTO", length = 40)
	public String getSubtagrupamento() {
		return this.subtagrupamento;
	}

	public void setSubtagrupamento(String subtagrupamento) {
		this.subtagrupamento = subtagrupamento;
	}

	@Column(name = "SUBTCONTAGEM", length = 40)
	public String getSubtcontagem() {
		return this.subtcontagem;
	}

	public void setSubtcontagem(String subtcontagem) {
		this.subtcontagem = subtcontagem;
	}

	@Column(name = "SUBTTURNOS", length = 40)
	public String getSubtturnos() {
		return this.subtturnos;
	}

	public void setSubtturnos(String subtturnos) {
		this.subtturnos = subtturnos;
	}

	@Column(name = "SUBTPERIODO", length = 40)
	public String getSubtperiodo() {
		return this.subtperiodo;
	}

	public void setSubtperiodo(String subtperiodo) {
		this.subtperiodo = subtperiodo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijrptreports")
	public Set<Ijrptlabels> getIjrptlabelses() {
		return this.ijrptlabelses;
	}

	public void setIjrptlabelses(Set<Ijrptlabels> ijrptlabelses) {
		this.ijrptlabelses = ijrptlabelses;
	}

}
