package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijrptlabels generated by hbm2java
 */
@Entity
@Table(name = "IJRPTLABELS")
public class Ijrptlabels implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7238762952737261760L;
	private IjrptlabelsId id;
	private Ijrptreports ijrptreports;
	private String dslabel;

	public Ijrptlabels() {
	}

	public Ijrptlabels(IjrptlabelsId id, Ijrptreports ijrptreports) {
		this.id = id;
		this.ijrptreports = ijrptreports;
	}

	public Ijrptlabels(IjrptlabelsId id, Ijrptreports ijrptreports,
			String dslabel) {
		this.id = id;
		this.ijrptreports = ijrptreports;
		this.dslabel = dslabel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdreport", column = @Column(name = "CDREPORT", nullable = false, length = 6)),
			@AttributeOverride(name = "cdlingua", column = @Column(name = "CDLINGUA", nullable = false, length = 6)),
			@AttributeOverride(name = "seqlabel", column = @Column(name = "SEQLABEL", nullable = false, precision = 22, scale = 0)) })
	public IjrptlabelsId getId() {
		return this.id;
	}

	public void setId(IjrptlabelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDREPORT", referencedColumnName = "CDREPORT", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDLINGUA", referencedColumnName = "CDLINGUA", nullable = false, insertable = false, updatable = false) })
	public Ijrptreports getIjrptreports() {
		return this.ijrptreports;
	}

	public void setIjrptreports(Ijrptreports ijrptreports) {
		this.ijrptreports = ijrptreports;
	}

	@Column(name = "DSLABEL", length = 15)
	public String getDslabel() {
		return this.dslabel;
	}

	public void setDslabel(String dslabel) {
		this.dslabel = dslabel;
	}

}
