package idw.model.pojos.injet;

//Generated 19/08/2009 14:35:42 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
* Ijrt generated by hbm2java
*/
@SuppressWarnings("serial")
@Entity
@Table(name = "IJRT", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DT_REFERENCIA", "CDTURNO", "CDINJETORA" }))
public class Ijrt implements java.io.Serializable {

	private long idrt;
	private Ijestmol ijestmol;
	private Ijtbtur ijtbtur;
	private VMaqDataBi VMaqDataBi;
	private VMaqAnoBi VMaqAnoBi;
	private Ijtbinj ijtbinj;
	private Ijtbpar ijtbpar;
	private VMaqMesBi VMaqMesBi;
	private Date dtReferencia;
	private String corfrenteturno;
	private String corfundoturno;
	private Character isoperador;
	private Character stfuncionamento;
	private Date dthriparada;
	private Date dthrfparada;
	private BigDecimal duracao;

	public Ijrt() {
	}

	public Ijrt(long idrt, Ijtbtur ijtbtur, Ijtbinj ijtbinj) {
		this.idrt = idrt;
		this.ijtbtur = ijtbtur;
		this.ijtbinj = ijtbinj;
	}

	public Ijrt(long idrt, Ijestmol ijestmol, Ijtbtur ijtbtur,
			VMaqDataBi VMaqDataBi, VMaqAnoBi VMaqAnoBi, Ijtbinj ijtbinj,
			Ijtbpar ijtbpar, VMaqMesBi VMaqMesBi, Date dtReferencia,
			String corfrenteturno, String corfundoturno, Character isoperador,
			Character stfuncionamento, Date dthriparada, Date dthrfparada,
			BigDecimal duracao) {
		this.idrt = idrt;
		this.ijestmol = ijestmol;
		this.ijtbtur = ijtbtur;
		this.VMaqDataBi = VMaqDataBi;
		this.VMaqAnoBi = VMaqAnoBi;
		this.ijtbinj = ijtbinj;
		this.ijtbpar = ijtbpar;
		this.VMaqMesBi = VMaqMesBi;
		this.dtReferencia = dtReferencia;
		this.corfrenteturno = corfrenteturno;
		this.corfundoturno = corfundoturno;
		this.isoperador = isoperador;
		this.stfuncionamento = stfuncionamento;
		this.dthriparada = dthriparada;
		this.dthrfparada = dthrfparada;
		this.duracao = duracao;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=GenerationType.AUTO, generator = "IJRT_SEQ")
	@SequenceGenerator(name = "IJRT_SEQ", sequenceName = "ijrt_seq")
	@Column(name = "IDRT", unique = true, nullable = false, precision = 126, scale = 0)
	public long getIdrt() {
		return this.idrt;
	}

	public void setIdrt(long idrt) {
		this.idrt = idrt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "CDMOLDE", referencedColumnName = "CDMOLDE"),
			@JoinColumn(name = "CDESTRUTURA", referencedColumnName = "CDESTRUTURA") })
	public Ijestmol getIjestmol() {
		return this.ijestmol;
	}

	public void setIjestmol(Ijestmol ijestmol) {
		this.ijestmol = ijestmol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTURNO", nullable = false)
	public Ijtbtur getIjtbtur() {
		return this.ijtbtur;
	}

	public void setIjtbtur(Ijtbtur ijtbtur) {
		this.ijtbtur = ijtbtur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAQ_DATA_BI")
	public VMaqDataBi getVMaqDataBi() {
		return this.VMaqDataBi;
	}

	public void setVMaqDataBi(VMaqDataBi VMaqDataBi) {
		this.VMaqDataBi = VMaqDataBi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAQ_ANO_BI")
	public VMaqAnoBi getVMaqAnoBi() {
		return this.VMaqAnoBi;
	}

	public void setVMaqAnoBi(VMaqAnoBi VMaqAnoBi) {
		this.VMaqAnoBi = VMaqAnoBi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPARADA")
	public Ijtbpar getIjtbpar() {
		return this.ijtbpar;
	}

	public void setIjtbpar(Ijtbpar ijtbpar) {
		this.ijtbpar = ijtbpar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAQ_MES_BI")
	public VMaqMesBi getVMaqMesBi() {
		return this.VMaqMesBi;
	}

	public void setVMaqMesBi(VMaqMesBi VMaqMesBi) {
		this.VMaqMesBi = VMaqMesBi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_REFERENCIA", length = 7)
	public Date getDtReferencia() {
		return this.dtReferencia;
	}

	public void setDtReferencia(Date dtReferencia) {
		this.dtReferencia = dtReferencia;
	}

	@Column(name = "CORFRENTETURNO", length = 40)
	public String getCorfrenteturno() {
		return this.corfrenteturno;
	}

	public void setCorfrenteturno(String corfrenteturno) {
		this.corfrenteturno = corfrenteturno;
	}

	@Column(name = "CORFUNDOTURNO", length = 40)
	public String getCorfundoturno() {
		return this.corfundoturno;
	}

	public void setCorfundoturno(String corfundoturno) {
		this.corfundoturno = corfundoturno;
	}

	@Column(name = "ISOPERADOR", length=1)
	public Character getIsoperador() {
		return this.isoperador;
	}

	public void setIsoperador(Character isoperador) {
		this.isoperador = isoperador;
	}

	@Column(name = "STFUNCIONAMENTO", length = 1)
	public Character getStfuncionamento() {
		return this.stfuncionamento;
	}

	public void setStfuncionamento(Character stfuncionamento) {
		this.stfuncionamento = stfuncionamento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRIPARADA")
	public Date getDthriparada() {
		return this.dthriparada;
	}

	public void setDthriparada(Date dthriparada) {
		this.dthriparada = dthriparada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRFPARADA")
	public Date getDthrfparada() {
		return this.dthrfparada;
	}

	public void setDthrfparada(Date dthrfparada) {
		this.dthrfparada = dthrfparada;
	}

	@Column(name = "DURACAO", precision = 20, scale = 10)
	public BigDecimal getDuracao() {
		return this.duracao;
	}

	public void setDuracao(BigDecimal duracao) {
		this.duracao = duracao;
	}

}
