package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijselecao generated by hbm2java
 */
@Entity
@Table(name = "IJSELECAO")
public class Ijselecao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5940861129995198055L;
	private String cdselecao;
	private Ijgrpemail ijgrpemail;
	private String dsselecao;
	private Date dthrcadastro;
	private String indativa;
	private Set<Ijselitensmen> ijselitensmens = new HashSet<Ijselitensmen>(0);
	private Set<Ijselitensarq> ijselitensarqs = new HashSet<Ijselitensarq>(0);

	public Ijselecao() {
	}

	public Ijselecao(String cdselecao, Ijgrpemail ijgrpemail, String dsselecao,
			Date dthrcadastro, String indativa) {
		this.cdselecao = cdselecao;
		this.ijgrpemail = ijgrpemail;
		this.dsselecao = dsselecao;
		this.dthrcadastro = dthrcadastro;
		this.indativa = indativa;
	}

	public Ijselecao(String cdselecao, Ijgrpemail ijgrpemail, String dsselecao,
			Date dthrcadastro, String indativa,
			Set<Ijselitensmen> ijselitensmens, Set<Ijselitensarq> ijselitensarqs) {
		this.cdselecao = cdselecao;
		this.ijgrpemail = ijgrpemail;
		this.dsselecao = dsselecao;
		this.dthrcadastro = dthrcadastro;
		this.indativa = indativa;
		this.ijselitensmens = ijselitensmens;
		this.ijselitensarqs = ijselitensarqs;
	}

	@Id
	@Column(name = "CDSELECAO", unique = true, nullable = false, length = 6)
	public String getCdselecao() {
		return this.cdselecao;
	}

	public void setCdselecao(String cdselecao) {
		this.cdselecao = cdselecao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDGRPEMAIL", nullable = false)
	public Ijgrpemail getIjgrpemail() {
		return this.ijgrpemail;
	}

	public void setIjgrpemail(Ijgrpemail ijgrpemail) {
		this.ijgrpemail = ijgrpemail;
	}

	@Column(name = "DSSELECAO", nullable = false, length = 30)
	public String getDsselecao() {
		return this.dsselecao;
	}

	public void setDsselecao(String dsselecao) {
		this.dsselecao = dsselecao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHRCADASTRO", nullable = false, length = 7)
	public Date getDthrcadastro() {
		return this.dthrcadastro;
	}

	public void setDthrcadastro(Date dthrcadastro) {
		this.dthrcadastro = dthrcadastro;
	}

	@Column(name = "INDATIVA", nullable = false, length = 1)
	public String getIndativa() {
		return this.indativa;
	}

	public void setIndativa(String indativa) {
		this.indativa = indativa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijselecao")
	public Set<Ijselitensmen> getIjselitensmens() {
		return this.ijselitensmens;
	}

	public void setIjselitensmens(Set<Ijselitensmen> ijselitensmens) {
		this.ijselitensmens = ijselitensmens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijselecao")
	public Set<Ijselitensarq> getIjselitensarqs() {
		return this.ijselitensarqs;
	}

	public void setIjselitensarqs(Set<Ijselitensarq> ijselitensarqs) {
		this.ijselitensarqs = ijselitensarqs;
	}

}
