package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijsitipe generated by hbm2java
 */
@Entity
@Table(name = "IJSITIPE")
public class Ijsitipe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1067149331604907627L;
	private String cdinjetora;
	private Ijtbinj ijtbinj;
	private String ipeok;

	public Ijsitipe() {
	}

	public Ijsitipe(String cdinjetora, Ijtbinj ijtbinj) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
	}

	public Ijsitipe(String cdinjetora, Ijtbinj ijtbinj, String ipeok) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.ipeok = ipeok;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "IPEOK", length = 3)
	public String getIpeok() {
		return this.ipeok;
	}

	public void setIpeok(String ipeok) {
		this.ipeok = ipeok;
	}

}
