package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbusumailsms generated by hbm2java
 */
@Entity
@Table(name = "IJTBUSUMAILSMS")
public class Ijtbusumailsms implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7127211263969609910L;
	private IjtbusumailsmsId id;
	private Ijtbusumail ijtbusumail;

	public Ijtbusumailsms() {
	}

	public Ijtbusumailsms(IjtbusumailsmsId id, Ijtbusumail ijtbusumail) {
		this.id = id;
		this.ijtbusumail = ijtbusumail;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdusumail", column = @Column(name = "CDUSUMAIL", nullable = false, length = 6)),
			@AttributeOverride(name = "idoperadora", column = @Column(name = "IDOPERADORA", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "numtelcelular", column = @Column(name = "NUMTELCELULAR", nullable = false, length = 20)) })
	public IjtbusumailsmsId getId() {
		return this.id;
	}

	public void setId(IjtbusumailsmsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUMAIL", nullable = false, insertable = false, updatable = false)
	public Ijtbusumail getIjtbusumail() {
		return this.ijtbusumail;
	}

	public void setIjtbusumail(Ijtbusumail ijtbusumail) {
		this.ijtbusumail = ijtbusumail;
	}

}
