package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbinjstatus generated by hbm2java
 */
@Entity
@Table(name = "IJTBINJSTATUS")
public class Ijtbinjstatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5270245963082517085L;
	private String cdinjetora;
	private Ijtbinj ijtbinj;
	private char stprobqld;
	private char stperdasinc;
	private char stmanut;
	private char stdelayconsol;

	public Ijtbinjstatus() {
	}

	public Ijtbinjstatus(String cdinjetora, Ijtbinj ijtbinj, char stprobqld,
			char stperdasinc, char stmanut, char stdelayconsol) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.stprobqld = stprobqld;
		this.stperdasinc = stperdasinc;
		this.stmanut = stmanut;
		this.stdelayconsol = stdelayconsol;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "STPROBQLD", nullable = false, length = 1)
	public char getStprobqld() {
		return this.stprobqld;
	}

	public void setStprobqld(char stprobqld) {
		this.stprobqld = stprobqld;
	}

	@Column(name = "STPERDASINC", nullable = false, length = 1)
	public char getStperdasinc() {
		return this.stperdasinc;
	}

	public void setStperdasinc(char stperdasinc) {
		this.stperdasinc = stperdasinc;
	}

	@Column(name = "STMANUT", nullable = false, length = 1)
	public char getStmanut() {
		return this.stmanut;
	}

	public void setStmanut(char stmanut) {
		this.stmanut = stmanut;
	}

	@Column(name = "STDELAYCONSOL", nullable = false, length = 1)
	public char getStdelayconsol() {
		return this.stdelayconsol;
	}

	public void setStdelayconsol(char stdelayconsol) {
		this.stdelayconsol = stdelayconsol;
	}

}
