package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbrecmanut generated by hbm2java
 */
@Entity
@Table(name = "IJTBRECMANUT")
public class Ijtbrecmanut implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -121673003171990349L;
	private String cdrecman;
	private Ijclassrecmanut ijclassrecmanut;
	private String dsrecman;

	public Ijtbrecmanut() {
	}

	public Ijtbrecmanut(String cdrecman, Ijclassrecmanut ijclassrecmanut,
			String dsrecman) {
		this.cdrecman = cdrecman;
		this.ijclassrecmanut = ijclassrecmanut;
		this.dsrecman = dsrecman;
	}

	@Id
	@Column(name = "CDRECMAN", unique = true, nullable = false, length = 6)
	public String getCdrecman() {
		return this.cdrecman;
	}

	public void setCdrecman(String cdrecman) {
		this.cdrecman = cdrecman;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCLASSRECURSO", nullable = false)
	public Ijclassrecmanut getIjclassrecmanut() {
		return this.ijclassrecmanut;
	}

	public void setIjclassrecmanut(Ijclassrecmanut ijclassrecmanut) {
		this.ijclassrecmanut = ijclassrecmanut;
	}

	@Column(name = "DSRECMAN", nullable = false, length = 40)
	public String getDsrecman() {
		return this.dsrecman;
	}

	public void setDsrecman(String dsrecman) {
		this.dsrecman = dsrecman;
	}

}
