package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbmotreploteins generated by hbm2java
 */
@Entity
@Table(name = "IJTBMOTREPLOTEINS")
public class Ijtbmotreploteins implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -265485229515169778L;
	private String cdmotreploteins;
	private String dsmotreploteins;
	private Set<Ijocorreploteins> ijocorreploteinses = new HashSet<Ijocorreploteins>(
			0);

	public Ijtbmotreploteins() {
	}

	public Ijtbmotreploteins(String cdmotreploteins, String dsmotreploteins) {
		this.cdmotreploteins = cdmotreploteins;
		this.dsmotreploteins = dsmotreploteins;
	}

	public Ijtbmotreploteins(String cdmotreploteins, String dsmotreploteins,
			Set<Ijocorreploteins> ijocorreploteinses) {
		this.cdmotreploteins = cdmotreploteins;
		this.dsmotreploteins = dsmotreploteins;
		this.ijocorreploteinses = ijocorreploteinses;
	}

	@Id
	@Column(name = "CDMOTREPLOTEINS", unique = true, nullable = false, length = 6)
	public String getCdmotreploteins() {
		return this.cdmotreploteins;
	}

	public void setCdmotreploteins(String cdmotreploteins) {
		this.cdmotreploteins = cdmotreploteins;
	}

	@Column(name = "DSMOTREPLOTEINS", nullable = false, length = 40)
	public String getDsmotreploteins() {
		return this.dsmotreploteins;
	}

	public void setDsmotreploteins(String dsmotreploteins) {
		this.dsmotreploteins = dsmotreploteins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmotreploteins")
	public Set<Ijocorreploteins> getIjocorreploteinses() {
		return this.ijocorreploteinses;
	}

	public void setIjocorreploteinses(Set<Ijocorreploteins> ijocorreploteinses) {
		this.ijocorreploteinses = ijocorreploteinses;
	}

}
