package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbgrids generated by hbm2java
 */
@Entity
@Table(name = "IJTBGRIDS")
public class Ijtbgrids implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7652748028280786176L;
	private IjtbgridsId id;
	private Ijlinguas ijlinguas;
	private String headercol;
	private BigDecimal tamcolgrid;

	public Ijtbgrids() {
	}

	public Ijtbgrids(IjtbgridsId id, Ijlinguas ijlinguas, String headercol) {
		this.id = id;
		this.ijlinguas = ijlinguas;
		this.headercol = headercol;
	}

	public Ijtbgrids(IjtbgridsId id, Ijlinguas ijlinguas, String headercol,
			BigDecimal tamcolgrid) {
		this.id = id;
		this.ijlinguas = ijlinguas;
		this.headercol = headercol;
		this.tamcolgrid = tamcolgrid;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nmform", column = @Column(name = "NMFORM", nullable = false, length = 30)),
			@AttributeOverride(name = "nmgrid", column = @Column(name = "NMGRID", nullable = false, length = 30)),
			@AttributeOverride(name = "cdlingua", column = @Column(name = "CDLINGUA", nullable = false, length = 6)),
			@AttributeOverride(name = "ordemcol", column = @Column(name = "ORDEMCOL", nullable = false, precision = 22, scale = 0)) })
	public IjtbgridsId getId() {
		return this.id;
	}

	public void setId(IjtbgridsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLINGUA", nullable = false, insertable = false, updatable = false)
	public Ijlinguas getIjlinguas() {
		return this.ijlinguas;
	}

	public void setIjlinguas(Ijlinguas ijlinguas) {
		this.ijlinguas = ijlinguas;
	}

	@Column(name = "HEADERCOL", nullable = false, length = 30)
	public String getHeadercol() {
		return this.headercol;
	}

	public void setHeadercol(String headercol) {
		this.headercol = headercol;
	}

	@Column(name = "TAMCOLGRID", precision = 22, scale = 0)
	public BigDecimal getTamcolgrid() {
		return this.tamcolgrid;
	}

	public void setTamcolgrid(BigDecimal tamcolgrid) {
		this.tamcolgrid = tamcolgrid;
	}

}
