package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ijtbprocfgespqld generated by hbm2java
 */
@Entity
@Table(name = "IJTBPROCFGESPQLD", uniqueConstraints = @UniqueConstraint(columnNames = "CDPRODUTO"))
public class Ijtbprocfgespqld implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8209888072075440934L;
	private double idregistro;
	private Ijtbpro ijtbpro;
	private BigDecimal cfgespqld;

	public Ijtbprocfgespqld() {
	}

	public Ijtbprocfgespqld(double idregistro, Ijtbpro ijtbpro,
			BigDecimal cfgespqld) {
		this.idregistro = idregistro;
		this.ijtbpro = ijtbpro;
		this.cfgespqld = cfgespqld;
	}

	@Id
	@Column(name = "IDREGISTRO", unique = true, nullable = false, precision = 126, scale = 0)
	public double getIdregistro() {
		return this.idregistro;
	}

	public void setIdregistro(double idregistro) {
		this.idregistro = idregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", unique = true, nullable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "CFGESPQLD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCfgespqld() {
		return this.cfgespqld;
	}

	public void setCfgespqld(BigDecimal cfgespqld) {
		this.cfgespqld = cfgespqld;
	}

}
