package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbmprima generated by hbm2java
 */
@Entity
@Table(name = "IJTBMPRIMA")
public class Ijtbmprima implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2107728983829599242L;
	private String cdmprima;
	private Ijtbunidmedida ijtbunidmedida;
	private Ijtbfab ijtbfab;
	private String dsmprima;
	private String tpmprima;
	private Character controlalote;
	private Set<Ijbroneproseccomp> ijbroneproseccomps = new HashSet<Ijbroneproseccomp>(
			0);
	private Set<Ijlotenipponins> ijlotenipponinses = new HashSet<Ijlotenipponins>(
			0);
	private Set<Ijopmprima> ijopmprimas = new HashSet<Ijopmprima>(0);
	private Set<Ijcomppromprima> ijcomppromprimas = new HashSet<Ijcomppromprima>(
			0);
	private Set<Ijctrlcgqxmprima> ijctrlcgqxmprimas = new HashSet<Ijctrlcgqxmprima>(
			0);
	private Set<Ijprocompmprimacgq> ijprocompmprimacgqs = new HashSet<Ijprocompmprimacgq>(
			0);
	private Set<Ijopnipponinsumo> ijopnipponinsumos = new HashSet<Ijopnipponinsumo>(
			0);

	public Ijtbmprima() {
	}

	public Ijtbmprima(String cdmprima, Ijtbunidmedida ijtbunidmedida,
			Ijtbfab ijtbfab, String dsmprima) {
		this.cdmprima = cdmprima;
		this.ijtbunidmedida = ijtbunidmedida;
		this.ijtbfab = ijtbfab;
		this.dsmprima = dsmprima;
	}

	public Ijtbmprima(String cdmprima, Ijtbunidmedida ijtbunidmedida,
			Ijtbfab ijtbfab, String dsmprima, String tpmprima,
			Character controlalote, Set<Ijbroneproseccomp> ijbroneproseccomps,
			Set<Ijlotenipponins> ijlotenipponinses,
			Set<Ijopmprima> ijopmprimas, Set<Ijcomppromprima> ijcomppromprimas,
			Set<Ijctrlcgqxmprima> ijctrlcgqxmprimas,
			Set<Ijprocompmprimacgq> ijprocompmprimacgqs,
			Set<Ijopnipponinsumo> ijopnipponinsumos) {
		this.cdmprima = cdmprima;
		this.ijtbunidmedida = ijtbunidmedida;
		this.ijtbfab = ijtbfab;
		this.dsmprima = dsmprima;
		this.tpmprima = tpmprima;
		this.controlalote = controlalote;
		this.ijbroneproseccomps = ijbroneproseccomps;
		this.ijlotenipponinses = ijlotenipponinses;
		this.ijopmprimas = ijopmprimas;
		this.ijcomppromprimas = ijcomppromprimas;
		this.ijctrlcgqxmprimas = ijctrlcgqxmprimas;
		this.ijprocompmprimacgqs = ijprocompmprimacgqs;
		this.ijopnipponinsumos = ijopnipponinsumos;
	}

	@Id
	@Column(name = "CDMPRIMA", unique = true, nullable = false, length = 20)
	public String getCdmprima() {
		return this.cdmprima;
	}

	public void setCdmprima(String cdmprima) {
		this.cdmprima = cdmprima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUNIDADE", nullable = false)
	public Ijtbunidmedida getIjtbunidmedida() {
		return this.ijtbunidmedida;
	}

	public void setIjtbunidmedida(Ijtbunidmedida ijtbunidmedida) {
		this.ijtbunidmedida = ijtbunidmedida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDFABRICANTE", nullable = false)
	public Ijtbfab getIjtbfab() {
		return this.ijtbfab;
	}

	public void setIjtbfab(Ijtbfab ijtbfab) {
		this.ijtbfab = ijtbfab;
	}

	@Column(name = "DSMPRIMA", nullable = false, length = 40)
	public String getDsmprima() {
		return this.dsmprima;
	}

	public void setDsmprima(String dsmprima) {
		this.dsmprima = dsmprima;
	}

	@Column(name = "TPMPRIMA", length = 50)
	public String getTpmprima() {
		return this.tpmprima;
	}

	public void setTpmprima(String tpmprima) {
		this.tpmprima = tpmprima;
	}

	@Column(name = "CONTROLALOTE", length = 1)
	public Character getControlalote() {
		return this.controlalote;
	}

	public void setControlalote(Character controlalote) {
		this.controlalote = controlalote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmprima")
	public Set<Ijbroneproseccomp> getIjbroneproseccomps() {
		return this.ijbroneproseccomps;
	}

	public void setIjbroneproseccomps(Set<Ijbroneproseccomp> ijbroneproseccomps) {
		this.ijbroneproseccomps = ijbroneproseccomps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmprima")
	public Set<Ijlotenipponins> getIjlotenipponinses() {
		return this.ijlotenipponinses;
	}

	public void setIjlotenipponinses(Set<Ijlotenipponins> ijlotenipponinses) {
		this.ijlotenipponinses = ijlotenipponinses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmprima")
	public Set<Ijopmprima> getIjopmprimas() {
		return this.ijopmprimas;
	}

	public void setIjopmprimas(Set<Ijopmprima> ijopmprimas) {
		this.ijopmprimas = ijopmprimas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmprima")
	public Set<Ijcomppromprima> getIjcomppromprimas() {
		return this.ijcomppromprimas;
	}

	public void setIjcomppromprimas(Set<Ijcomppromprima> ijcomppromprimas) {
		this.ijcomppromprimas = ijcomppromprimas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmprima")
	public Set<Ijctrlcgqxmprima> getIjctrlcgqxmprimas() {
		return this.ijctrlcgqxmprimas;
	}

	public void setIjctrlcgqxmprimas(Set<Ijctrlcgqxmprima> ijctrlcgqxmprimas) {
		this.ijctrlcgqxmprimas = ijctrlcgqxmprimas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmprima")
	public Set<Ijprocompmprimacgq> getIjprocompmprimacgqs() {
		return this.ijprocompmprimacgqs;
	}

	public void setIjprocompmprimacgqs(
			Set<Ijprocompmprimacgq> ijprocompmprimacgqs) {
		this.ijprocompmprimacgqs = ijprocompmprimacgqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmprima")
	public Set<Ijopnipponinsumo> getIjopnipponinsumos() {
		return this.ijopnipponinsumos;
	}

	public void setIjopnipponinsumos(Set<Ijopnipponinsumo> ijopnipponinsumos) {
		this.ijopnipponinsumos = ijopnipponinsumos;
	}

}
