package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijtbleader generated by hbm2java
 */
@Entity
@Table(name = "IJTBLEADER")
public class Ijtbleader implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2769138936513316757L;
	private IjtbleaderId id;

	public Ijtbleader() {
	}

	public Ijtbleader(IjtbleaderId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "campo1", column = @Column(name = "CAMPO1", nullable = false, length = 100)),
			@AttributeOverride(name = "campo2", column = @Column(name = "CAMPO2", nullable = false, length = 8)),
			@AttributeOverride(name = "campo3", column = @Column(name = "CAMPO3", nullable = false, length = 30)) })
	public IjtbleaderId getId() {
		return this.id;
	}

	public void setId(IjtbleaderId id) {
		this.id = id;
	}

}
