package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbsubcoletores generated by hbm2java
 */
@Entity
@Table(name = "IJTBSUBCOLETORES")
public class Ijtbsubcoletores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8575622544314079581L;
	private IjtbsubcoletoresId id;
	private Ijtbcoletores ijtbcoletores;

	public Ijtbsubcoletores() {
	}

	public Ijtbsubcoletores(IjtbsubcoletoresId id, Ijtbcoletores ijtbcoletores) {
		this.id = id;
		this.ijtbcoletores = ijtbcoletores;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdmestre", column = @Column(name = "CDMESTRE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdcoletor", column = @Column(name = "CDCOLETOR", nullable = false, length = 6)),
			@AttributeOverride(name = "cdsubcoletor", column = @Column(name = "CDSUBCOLETOR", nullable = false, precision = 22, scale = 0)) })
	public IjtbsubcoletoresId getId() {
		return this.id;
	}

	public void setId(IjtbsubcoletoresId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CDMESTRE", referencedColumnName = "CDMESTRE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CDCOLETOR", referencedColumnName = "CDCOLETOR", nullable = false, insertable = false, updatable = false) })
	public Ijtbcoletores getIjtbcoletores() {
		return this.ijtbcoletores;
	}

	public void setIjtbcoletores(Ijtbcoletores ijtbcoletores) {
		this.ijtbcoletores = ijtbcoletores;
	}

}
