package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbidgraf generated by hbm2java
 */
@Entity
@Table(name = "IJTBIDGRAF")
public class Ijtbidgraf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2803958237796026951L;
	private IjtbidgrafId id;
	private Ijtbmodulos ijtbmodulos;
	private String cdgraf;

	public Ijtbidgraf() {
	}

	public Ijtbidgraf(IjtbidgrafId id, Ijtbmodulos ijtbmodulos, String cdgraf) {
		this.id = id;
		this.ijtbmodulos = ijtbmodulos;
		this.cdgraf = cdgraf;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdmodulo", column = @Column(name = "CDMODULO", nullable = false, length = 6)),
			@AttributeOverride(name = "nmform", column = @Column(name = "NMFORM", nullable = false, length = 40)),
			@AttributeOverride(name = "nmformorigem", column = @Column(name = "NMFORMORIGEM", nullable = false, length = 40)) })
	public IjtbidgrafId getId() {
		return this.id;
	}

	public void setId(IjtbidgrafId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMODULO", nullable = false, insertable = false, updatable = false)
	public Ijtbmodulos getIjtbmodulos() {
		return this.ijtbmodulos;
	}

	public void setIjtbmodulos(Ijtbmodulos ijtbmodulos) {
		this.ijtbmodulos = ijtbmodulos;
	}

	@Column(name = "CDGRAF", nullable = false, length = 6)
	public String getCdgraf() {
		return this.cdgraf;
	}

	public void setCdgraf(String cdgraf) {
		this.cdgraf = cdgraf;
	}

}
