package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijtbusu generated by hbm2java
 */
@Entity
@Table(name = "IJTBUSU")
public class Ijtbusu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1193061230350844612L;
	private String cdusuario;
	private Ijtbemp ijtbemp;
	private Ijtbcar ijtbcar;
	private Ijtbusumail ijtbusumail;
	private Ijtbset ijtbset;
	private String nmacesso;
	private String nmusuario;
	private Date dtcadastro;
	private String senha;
	private Date dthrultimoacesso;
	private String matricula;
	private BigDecimal tpusuario;
	private Date dtsaida;
	private Integer stusuario;
	private BigDecimal habilitfuncavanc;
	private char operadorauxiliar;
	private Set<Exportacao001> exportacao001s = new HashSet<Exportacao001>(0);
	private Set<Ijalemanutprev> ijalemanutprevs = new HashSet<Ijalemanutprev>(0);
	private Set<Ijalertas> ijalertases = new HashSet<Ijalertas>(0);
	private Set<Ijcfgusu> ijcfgusus = new HashSet<Ijcfgusu>(0);
	private Set<Ijreaparoprd> ijreaparoprds = new HashSet<Ijreaparoprd>(0);
	private Set<Ijrearefoprd> ijrearefoprds = new HashSet<Ijrearefoprd>(0);
	private Set<Ijrefman> ijrefmansForCdusuarioinclusao = new HashSet<Ijrefman>(
			0);
	private Set<Ijrefman> ijrefmansForCdusuarioexclusao = new HashSet<Ijrefman>(
			0);
	private Set<Ijtbmodisp> ijtbmodisps = new HashSet<Ijtbmodisp>(0);
	private Set<Ijtbprodescont> ijtbprodesconts = new HashSet<Ijtbprodescont>(0);
	private Set<Ijtbprousu> ijtbprousus = new HashSet<Ijtbprousu>(0);
	private Set<Ijconplanning> ijconplannings = new HashSet<Ijconplanning>(0);
	private Set<Ijctrliniproc> ijctrliniprocsForCdtecinicio = new HashSet<Ijctrliniproc>(
			0);
	private Set<Ijctrlcgqalt> ijctrlcgqalts = new HashSet<Ijctrlcgqalt>(0);
	private Set<Ijlogsenhatm> ijlogsenhatmsForCdusuario = new HashSet<Ijlogsenhatm>(
			0);
	private Set<Ijreapar> ijreaparsForDrtresponsa = new HashSet<Ijreapar>(0);
	private Set<Ijctrliniproc> ijctrliniprocsForCdtecfinal = new HashSet<Ijctrliniproc>(
			0);
	private Set<Ijreapar> ijreaparsForDrttecnico2 = new HashSet<Ijreapar>(0);
	private Set<Ijlogvidautil> ijlogvidautils = new HashSet<Ijlogvidautil>(0);
	private Set<Ijreapar> ijreaparsForDrtecnico1 = new HashSet<Ijreapar>(0);
	private Set<Ijlogsenhatm> ijlogsenhatmsForCdadmin = new HashSet<Ijlogsenhatm>(
			0);
	private Set<Ijlogcorrreq> ijlogcorrreqsForDrttecnico2 = new HashSet<Ijlogcorrreq>(
			0);
	private Set<Ijlogcorrreq> ijlogcorrreqsForDrtresponsa = new HashSet<Ijlogcorrreq>(
			0);
	private Set<Ijkanbanmov> ijkanbanmovs = new HashSet<Ijkanbanmov>(0);
	private Set<Ijlogcorrpar> ijlogcorrpars = new HashSet<Ijlogcorrpar>(0);
	private Set<Ijlogcorrreq> ijlogcorrreqsForCdusuario = new HashSet<Ijlogcorrreq>(
			0);
	private Set<Ijqldinspecao> ijqldinspecaosForCdusuariornc = new HashSet<Ijqldinspecao>(
			0);
	private Set<Ijreacicopoprd> ijreacicopoprds = new HashSet<Ijreacicopoprd>(0);
	private Set<Ijreainspprod> ijreainspprodsForCdoperador = new HashSet<Ijreainspprod>(
			0);
	private Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusucanceloulote = new HashSet<Ijqldprodinsplote>(
			0);
	private Set<Ijqldsupervisor> ijqldsupervisors = new HashSet<Ijqldsupervisor>(
			0);
	private Set<Ijreamovsemprog> ijreamovsemprogsForCdtecisemprog = new HashSet<Ijreamovsemprog>(
			0);
	private Set<Ijreamovsemprog> ijreamovsemprogsForCdtecfsemprog = new HashSet<Ijreamovsemprog>(
			0);
	private Set<Ijreainspprod> ijreainspprodsForCdusujustificativa = new HashSet<Ijreainspprod>(
			0);
	private Set<Ijreajuscav> ijreajuscavs = new HashSet<Ijreajuscav>(0);
	private Set<Ijlogexcdadosmolde> ijlogexcdadosmoldes = new HashSet<Ijlogexcdadosmolde>(
			0);
	private Set<Ijlogcorrreq> ijlogcorrreqsForDrttecnico1 = new HashSet<Ijlogcorrreq>(
			0);
	private Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusuabriulote = new HashSet<Ijqldprodinsplote>(
			0);
	private Set<Ijlogopemaq> ijlogopemaqs = new HashSet<Ijlogopemaq>(0);
	private Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusufechoulote = new HashSet<Ijqldprodinsplote>(
			0);
	private Set<Ijlogope> ijlogopes = new HashSet<Ijlogope>(0);
	private Set<Ijlogipesemconexao> ijlogipesemconexaos = new HashSet<Ijlogipesemconexao>(
			0);
	private Set<Ijloggalabc> ijloggalabcs = new HashSet<Ijloggalabc>(0);
	private Set<Ijmolproautorizusu> ijmolproautorizususForCdusuarioaut = new HashSet<Ijmolproautorizusu>(
			0);
	private Set<Ijmolproautorizusu> ijmolproautorizususForCdususubstituto = new HashSet<Ijmolproautorizusu>(
			0);
	private Set<Ijduimpressaocgq> ijduimpressaocgqs = new HashSet<Ijduimpressaocgq>(
			0);
	private Set<Ijembapont> ijembaponts = new HashSet<Ijembapont>(0);
	private Set<Ijmovpostos> ijmovpostoses = new HashSet<Ijmovpostos>(0);
	private Set<Ijqldinspecao> ijqldinspecaosForCdusuariobaixa = new HashSet<Ijqldinspecao>(
			0);
	private Set<Ijqldinspecao> ijqldinspecaosForCdusuarioinspecao = new HashSet<Ijqldinspecao>(
			0);
	private Set<Ijqldinspecao> ijqldinspecaosForCdusuarioexclusao = new HashSet<Ijqldinspecao>(
			0);
	private Set<Ijqldinspecao> ijqldinspecaosForCdusuarioalteracao = new HashSet<Ijqldinspecao>(
			0);
	private Set<Ijopbloqdet> ijopbloqdets = new HashSet<Ijopbloqdet>(0);
	private Set<Ijocorvarritmo> ijocorvarritmos = new HashSet<Ijocorvarritmo>(0);
	private Set<Ijpdcaparticipproj> ijpdcaparticipprojs = new HashSet<Ijpdcaparticipproj>(
			0);
	private Set<Ijpdcafupacao> ijpdcafupacaos = new HashSet<Ijpdcafupacao>(0);
	private Set<Ijgrpemail> ijgrpemails = new HashSet<Ijgrpemail>(0);
	private Set<Ijinspecao> ijinspecaosForCdoperador = new HashSet<Ijinspecao>(
			0);
	private Set<Ijmanut> ijmanutsForCdusufimmanut = new HashSet<Ijmanut>(0);
	private Set<Ijinspecao> ijinspecaosForCdsupervisor = new HashSet<Ijinspecao>(
			0);
	private Set<Ijgruusu> ijgruusus = new HashSet<Ijgruusu>(0);
	private Set<Ijmanut> ijmanutsForCdusuabeos = new HashSet<Ijmanut>(0);
	private Set<Ijinspecao> ijinspecaosForCdusucancelalerta = new HashSet<Ijinspecao>(
			0);
	private Set<Ijmanut> ijmanutsForCdusuinimanut = new HashSet<Ijmanut>(0);
	private Set<Ijaledbqldanot> ijaledbqldanots = new HashSet<Ijaledbqldanot>(0);
	private Set<Ijespecinsppro> ijespecinsppros = new HashSet<Ijespecinsppro>(0);
	private Set<Imp002Logexcops> imp002Logexcopses = new HashSet<Imp002Logexcops>(
			0);
	private Set<Ijfictecautorizmod> ijfictecautorizmods = new HashSet<Ijfictecautorizmod>(
			0);
	private Set<Ijmolproautorizmod> ijmolproautorizmods = new HashSet<Ijmolproautorizmod>(
			0);
	private Set<Ijtbusureqtec> ijtbusureqtecs = new HashSet<Ijtbusureqtec>(0);
	private Set<Ijfictec> ijfictecs = new HashSet<Ijfictec>(0);
	private Set<Ijmolpro> ijmolpros = new HashSet<Ijmolpro>(0);
	private Set<Ijtbusutecespec> ijtbusutecespecs = new HashSet<Ijtbusutecespec>(
			0);
	private Set<Ijenglogciclos> ijenglogcicloses = new HashSet<Ijenglogciclos>(
			0);
	private Set<Ijmdoaloc> ijmdoalocs = new HashSet<Ijmdoaloc>(0);
	private Set<Ijusudirespec> ijusudirespecs = new HashSet<Ijusudirespec>(0);
	private Set<Ijengleituraciclos> ijengleituracicloses = new HashSet<Ijengleituraciclos>(
			0);
	private Set<Ijmanutregliber> ijmanutreglibers = new HashSet<Ijmanutregliber>(
			0);
	private Set<Ijmanutexectec> ijmanutexectecs = new HashSet<Ijmanutexectec>(0);
	private Set<Ijmanutexec> ijmanutexecsForCdusufimexec = new HashSet<Ijmanutexec>(
			0);
	private Set<Ijfictecautorizusu> ijfictecautorizususForCdususubstituto = new HashSet<Ijfictecautorizusu>(
			0);
	private Set<Ijmanutexec> ijmanutexecsForCdusuiniexec = new HashSet<Ijmanutexec>(
			0);
	private Set<Ijfictecautorizusu> ijfictecautorizususForCdusuarioaut = new HashSet<Ijfictecautorizusu>(
			0);
	private Set<Ijmanutchklst> ijmanutchklsts = new HashSet<Ijmanutchklst>(0);

	public Ijtbusu() {
	}

	public Ijtbusu(String cdusuario, Ijtbemp ijtbemp, Ijtbcar ijtbcar,
			Ijtbset ijtbset, String nmacesso, BigDecimal habilitfuncavanc,
			char operadorauxiliar) {
		this.cdusuario = cdusuario;
		this.ijtbemp = ijtbemp;
		this.ijtbcar = ijtbcar;
		this.ijtbset = ijtbset;
		this.nmacesso = nmacesso;
		this.habilitfuncavanc = habilitfuncavanc;
		this.operadorauxiliar = operadorauxiliar;
	}

	public Ijtbusu(String cdusuario, Ijtbemp ijtbemp, Ijtbcar ijtbcar,
			Ijtbusumail ijtbusumail, Ijtbset ijtbset, String nmacesso,
			String nmusuario, Date dtcadastro, String senha,
			Date dthrultimoacesso, String matricula, BigDecimal tpusuario,
			Date dtsaida, Integer stusuario, BigDecimal habilitfuncavanc,
			char operadorauxiliar, Set<Exportacao001> exportacao001s,
			Set<Ijalemanutprev> ijalemanutprevs, Set<Ijalertas> ijalertases,
			Set<Ijcfgusu> ijcfgusus, Set<Ijreaparoprd> ijreaparoprds,
			Set<Ijrearefoprd> ijrearefoprds,
			Set<Ijrefman> ijrefmansForCdusuarioinclusao,
			Set<Ijrefman> ijrefmansForCdusuarioexclusao,
			Set<Ijtbmodisp> ijtbmodisps, Set<Ijtbprodescont> ijtbprodesconts,
			Set<Ijtbprousu> ijtbprousus, Set<Ijconplanning> ijconplannings,
			Set<Ijctrliniproc> ijctrliniprocsForCdtecinicio,
			Set<Ijctrlcgqalt> ijctrlcgqalts,
			Set<Ijlogsenhatm> ijlogsenhatmsForCdusuario,
			Set<Ijreapar> ijreaparsForDrtresponsa,
			Set<Ijctrliniproc> ijctrliniprocsForCdtecfinal,
			Set<Ijreapar> ijreaparsForDrttecnico2,
			Set<Ijlogvidautil> ijlogvidautils,
			Set<Ijreapar> ijreaparsForDrtecnico1,
			Set<Ijlogsenhatm> ijlogsenhatmsForCdadmin,
			Set<Ijlogcorrreq> ijlogcorrreqsForDrttecnico2,
			Set<Ijlogcorrreq> ijlogcorrreqsForDrtresponsa,
			Set<Ijkanbanmov> ijkanbanmovs, Set<Ijlogcorrpar> ijlogcorrpars,
			Set<Ijlogcorrreq> ijlogcorrreqsForCdusuario,
			Set<Ijqldinspecao> ijqldinspecaosForCdusuariornc,
			Set<Ijreacicopoprd> ijreacicopoprds,
			Set<Ijreainspprod> ijreainspprodsForCdoperador,
			Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusucanceloulote,
			Set<Ijqldsupervisor> ijqldsupervisors,
			Set<Ijreamovsemprog> ijreamovsemprogsForCdtecisemprog,
			Set<Ijreamovsemprog> ijreamovsemprogsForCdtecfsemprog,
			Set<Ijreainspprod> ijreainspprodsForCdusujustificativa,
			Set<Ijreajuscav> ijreajuscavs,
			Set<Ijlogexcdadosmolde> ijlogexcdadosmoldes,
			Set<Ijlogcorrreq> ijlogcorrreqsForDrttecnico1,
			Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusuabriulote,
			Set<Ijlogopemaq> ijlogopemaqs,
			Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusufechoulote,
			Set<Ijlogope> ijlogopes,
			Set<Ijlogipesemconexao> ijlogipesemconexaos,
			Set<Ijloggalabc> ijloggalabcs,
			Set<Ijmolproautorizusu> ijmolproautorizususForCdusuarioaut,
			Set<Ijmolproautorizusu> ijmolproautorizususForCdususubstituto,
			Set<Ijduimpressaocgq> ijduimpressaocgqs,
			Set<Ijembapont> ijembaponts, Set<Ijmovpostos> ijmovpostoses,
			Set<Ijqldinspecao> ijqldinspecaosForCdusuariobaixa,
			Set<Ijqldinspecao> ijqldinspecaosForCdusuarioinspecao,
			Set<Ijqldinspecao> ijqldinspecaosForCdusuarioexclusao,
			Set<Ijqldinspecao> ijqldinspecaosForCdusuarioalteracao,
			Set<Ijopbloqdet> ijopbloqdets, Set<Ijocorvarritmo> ijocorvarritmos,
			Set<Ijpdcaparticipproj> ijpdcaparticipprojs,
			Set<Ijpdcafupacao> ijpdcafupacaos, Set<Ijgrpemail> ijgrpemails,
			Set<Ijinspecao> ijinspecaosForCdoperador,
			Set<Ijmanut> ijmanutsForCdusufimmanut,
			Set<Ijinspecao> ijinspecaosForCdsupervisor,
			Set<Ijgruusu> ijgruusus, Set<Ijmanut> ijmanutsForCdusuabeos,
			Set<Ijinspecao> ijinspecaosForCdusucancelalerta,
			Set<Ijmanut> ijmanutsForCdusuinimanut,
			Set<Ijaledbqldanot> ijaledbqldanots,
			Set<Ijespecinsppro> ijespecinsppros,
			Set<Imp002Logexcops> imp002Logexcopses,
			Set<Ijfictecautorizmod> ijfictecautorizmods,
			Set<Ijmolproautorizmod> ijmolproautorizmods,
			Set<Ijtbusureqtec> ijtbusureqtecs, Set<Ijfictec> ijfictecs,
			Set<Ijmolpro> ijmolpros, Set<Ijtbusutecespec> ijtbusutecespecs,
			Set<Ijenglogciclos> ijenglogcicloses, Set<Ijmdoaloc> ijmdoalocs,
			Set<Ijusudirespec> ijusudirespecs,
			Set<Ijengleituraciclos> ijengleituracicloses,
			Set<Ijmanutregliber> ijmanutreglibers,
			Set<Ijmanutexectec> ijmanutexectecs,
			Set<Ijmanutexec> ijmanutexecsForCdusufimexec,
			Set<Ijfictecautorizusu> ijfictecautorizususForCdususubstituto,
			Set<Ijmanutexec> ijmanutexecsForCdusuiniexec,
			Set<Ijfictecautorizusu> ijfictecautorizususForCdusuarioaut,
			Set<Ijmanutchklst> ijmanutchklsts) {
		this.cdusuario = cdusuario;
		this.ijtbemp = ijtbemp;
		this.ijtbcar = ijtbcar;
		this.ijtbusumail = ijtbusumail;
		this.ijtbset = ijtbset;
		this.nmacesso = nmacesso;
		this.nmusuario = nmusuario;
		this.dtcadastro = dtcadastro;
		this.senha = senha;
		this.dthrultimoacesso = dthrultimoacesso;
		this.matricula = matricula;
		this.tpusuario = tpusuario;
		this.dtsaida = dtsaida;
		this.stusuario = stusuario;
		this.habilitfuncavanc = habilitfuncavanc;
		this.operadorauxiliar = operadorauxiliar;
		this.exportacao001s = exportacao001s;
		this.ijalemanutprevs = ijalemanutprevs;
		this.ijalertases = ijalertases;
		this.ijcfgusus = ijcfgusus;
		this.ijreaparoprds = ijreaparoprds;
		this.ijrearefoprds = ijrearefoprds;
		this.ijrefmansForCdusuarioinclusao = ijrefmansForCdusuarioinclusao;
		this.ijrefmansForCdusuarioexclusao = ijrefmansForCdusuarioexclusao;
		this.ijtbmodisps = ijtbmodisps;
		this.ijtbprodesconts = ijtbprodesconts;
		this.ijtbprousus = ijtbprousus;
		this.ijconplannings = ijconplannings;
		this.ijctrliniprocsForCdtecinicio = ijctrliniprocsForCdtecinicio;
		this.ijctrlcgqalts = ijctrlcgqalts;
		this.ijlogsenhatmsForCdusuario = ijlogsenhatmsForCdusuario;
		this.ijreaparsForDrtresponsa = ijreaparsForDrtresponsa;
		this.ijctrliniprocsForCdtecfinal = ijctrliniprocsForCdtecfinal;
		this.ijreaparsForDrttecnico2 = ijreaparsForDrttecnico2;
		this.ijlogvidautils = ijlogvidautils;
		this.ijreaparsForDrtecnico1 = ijreaparsForDrtecnico1;
		this.ijlogsenhatmsForCdadmin = ijlogsenhatmsForCdadmin;
		this.ijlogcorrreqsForDrttecnico2 = ijlogcorrreqsForDrttecnico2;
		this.ijlogcorrreqsForDrtresponsa = ijlogcorrreqsForDrtresponsa;
		this.ijkanbanmovs = ijkanbanmovs;
		this.ijlogcorrpars = ijlogcorrpars;
		this.ijlogcorrreqsForCdusuario = ijlogcorrreqsForCdusuario;
		this.ijqldinspecaosForCdusuariornc = ijqldinspecaosForCdusuariornc;
		this.ijreacicopoprds = ijreacicopoprds;
		this.ijreainspprodsForCdoperador = ijreainspprodsForCdoperador;
		this.ijqldprodinsplotesForCdusucanceloulote = ijqldprodinsplotesForCdusucanceloulote;
		this.ijqldsupervisors = ijqldsupervisors;
		this.ijreamovsemprogsForCdtecisemprog = ijreamovsemprogsForCdtecisemprog;
		this.ijreamovsemprogsForCdtecfsemprog = ijreamovsemprogsForCdtecfsemprog;
		this.ijreainspprodsForCdusujustificativa = ijreainspprodsForCdusujustificativa;
		this.ijreajuscavs = ijreajuscavs;
		this.ijlogexcdadosmoldes = ijlogexcdadosmoldes;
		this.ijlogcorrreqsForDrttecnico1 = ijlogcorrreqsForDrttecnico1;
		this.ijqldprodinsplotesForCdusuabriulote = ijqldprodinsplotesForCdusuabriulote;
		this.ijlogopemaqs = ijlogopemaqs;
		this.ijqldprodinsplotesForCdusufechoulote = ijqldprodinsplotesForCdusufechoulote;
		this.ijlogopes = ijlogopes;
		this.ijlogipesemconexaos = ijlogipesemconexaos;
		this.ijloggalabcs = ijloggalabcs;
		this.ijmolproautorizususForCdusuarioaut = ijmolproautorizususForCdusuarioaut;
		this.ijmolproautorizususForCdususubstituto = ijmolproautorizususForCdususubstituto;
		this.ijduimpressaocgqs = ijduimpressaocgqs;
		this.ijembaponts = ijembaponts;
		this.ijmovpostoses = ijmovpostoses;
		this.ijqldinspecaosForCdusuariobaixa = ijqldinspecaosForCdusuariobaixa;
		this.ijqldinspecaosForCdusuarioinspecao = ijqldinspecaosForCdusuarioinspecao;
		this.ijqldinspecaosForCdusuarioexclusao = ijqldinspecaosForCdusuarioexclusao;
		this.ijqldinspecaosForCdusuarioalteracao = ijqldinspecaosForCdusuarioalteracao;
		this.ijopbloqdets = ijopbloqdets;
		this.ijocorvarritmos = ijocorvarritmos;
		this.ijpdcaparticipprojs = ijpdcaparticipprojs;
		this.ijpdcafupacaos = ijpdcafupacaos;
		this.ijgrpemails = ijgrpemails;
		this.ijinspecaosForCdoperador = ijinspecaosForCdoperador;
		this.ijmanutsForCdusufimmanut = ijmanutsForCdusufimmanut;
		this.ijinspecaosForCdsupervisor = ijinspecaosForCdsupervisor;
		this.ijgruusus = ijgruusus;
		this.ijmanutsForCdusuabeos = ijmanutsForCdusuabeos;
		this.ijinspecaosForCdusucancelalerta = ijinspecaosForCdusucancelalerta;
		this.ijmanutsForCdusuinimanut = ijmanutsForCdusuinimanut;
		this.ijaledbqldanots = ijaledbqldanots;
		this.ijespecinsppros = ijespecinsppros;
		this.imp002Logexcopses = imp002Logexcopses;
		this.ijfictecautorizmods = ijfictecautorizmods;
		this.ijmolproautorizmods = ijmolproautorizmods;
		this.ijtbusureqtecs = ijtbusureqtecs;
		this.ijfictecs = ijfictecs;
		this.ijmolpros = ijmolpros;
		this.ijtbusutecespecs = ijtbusutecespecs;
		this.ijenglogcicloses = ijenglogcicloses;
		this.ijmdoalocs = ijmdoalocs;
		this.ijusudirespecs = ijusudirespecs;
		this.ijengleituracicloses = ijengleituracicloses;
		this.ijmanutreglibers = ijmanutreglibers;
		this.ijmanutexectecs = ijmanutexectecs;
		this.ijmanutexecsForCdusufimexec = ijmanutexecsForCdusufimexec;
		this.ijfictecautorizususForCdususubstituto = ijfictecautorizususForCdususubstituto;
		this.ijmanutexecsForCdusuiniexec = ijmanutexecsForCdusuiniexec;
		this.ijfictecautorizususForCdusuarioaut = ijfictecautorizususForCdusuarioaut;
		this.ijmanutchklsts = ijmanutchklsts;
	}

	@Id
	@Column(name = "CDUSUARIO", unique = true, nullable = false, length = 6)
	public String getCdusuario() {
		return this.cdusuario;
	}

	public void setCdusuario(String cdusuario) {
		this.cdusuario = cdusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDEMPRESA", nullable = false)
	public Ijtbemp getIjtbemp() {
		return this.ijtbemp;
	}

	public void setIjtbemp(Ijtbemp ijtbemp) {
		this.ijtbemp = ijtbemp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDCARGO", nullable = false)
	public Ijtbcar getIjtbcar() {
		return this.ijtbcar;
	}

	public void setIjtbcar(Ijtbcar ijtbcar) {
		this.ijtbcar = ijtbcar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REFCDUSUINJETMAIL")
	public Ijtbusumail getIjtbusumail() {
		return this.ijtbusumail;
	}

	public void setIjtbusumail(Ijtbusumail ijtbusumail) {
		this.ijtbusumail = ijtbusumail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDSETOR", nullable = false)
	public Ijtbset getIjtbset() {
		return this.ijtbset;
	}

	public void setIjtbset(Ijtbset ijtbset) {
		this.ijtbset = ijtbset;
	}

	@Column(name = "NMACESSO", nullable = false, length = 10)
	public String getNmacesso() {
		return this.nmacesso;
	}

	public void setNmacesso(String nmacesso) {
		this.nmacesso = nmacesso;
	}

	@Column(name = "NMUSUARIO", length = 40)
	public String getNmusuario() {
		return this.nmusuario;
	}

	public void setNmusuario(String nmusuario) {
		this.nmusuario = nmusuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTCADASTRO", length = 7)
	public Date getDtcadastro() {
		return this.dtcadastro;
	}

	public void setDtcadastro(Date dtcadastro) {
		this.dtcadastro = dtcadastro;
	}

	@Column(name = "SENHA", length = 6)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRULTIMOACESSO", length = 7)
	public Date getDthrultimoacesso() {
		return this.dthrultimoacesso;
	}

	public void setDthrultimoacesso(Date dthrultimoacesso) {
		this.dthrultimoacesso = dthrultimoacesso;
	}

	@Column(name = "MATRICULA", length = 10)
	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	@Column(name = "TPUSUARIO", precision = 22, scale = 0)
	public BigDecimal getTpusuario() {
		return this.tpusuario;
	}

	public void setTpusuario(BigDecimal tpusuario) {
		this.tpusuario = tpusuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTSAIDA", length = 7)
	public Date getDtsaida() {
		return this.dtsaida;
	}

	public void setDtsaida(Date dtsaida) {
		this.dtsaida = dtsaida;
	}

	@Column(name = "STUSUARIO")
	public Integer getStusuario() {
		return this.stusuario;
	}

	public void setStusuario(Integer stusuario) {
		this.stusuario = stusuario;
	}

	@Column(name = "HABILITFUNCAVANC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getHabilitfuncavanc() {
		return this.habilitfuncavanc;
	}

	public void setHabilitfuncavanc(BigDecimal habilitfuncavanc) {
		this.habilitfuncavanc = habilitfuncavanc;
	}

	@Column(name = "OPERADORAUXILIAR", nullable = false, length = 1)
	public char getOperadorauxiliar() {
		return this.operadorauxiliar;
	}

	public void setOperadorauxiliar(char operadorauxiliar) {
		this.operadorauxiliar = operadorauxiliar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Exportacao001> getExportacao001s() {
		return this.exportacao001s;
	}

	public void setExportacao001s(Set<Exportacao001> exportacao001s) {
		this.exportacao001s = exportacao001s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijalemanutprev> getIjalemanutprevs() {
		return this.ijalemanutprevs;
	}

	public void setIjalemanutprevs(Set<Ijalemanutprev> ijalemanutprevs) {
		this.ijalemanutprevs = ijalemanutprevs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijalertas> getIjalertases() {
		return this.ijalertases;
	}

	public void setIjalertases(Set<Ijalertas> ijalertases) {
		this.ijalertases = ijalertases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijcfgusu> getIjcfgusus() {
		return this.ijcfgusus;
	}

	public void setIjcfgusus(Set<Ijcfgusu> ijcfgusus) {
		this.ijcfgusus = ijcfgusus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijreaparoprd> getIjreaparoprds() {
		return this.ijreaparoprds;
	}

	public void setIjreaparoprds(Set<Ijreaparoprd> ijreaparoprds) {
		this.ijreaparoprds = ijreaparoprds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijrearefoprd> getIjrearefoprds() {
		return this.ijrearefoprds;
	}

	public void setIjrearefoprds(Set<Ijrearefoprd> ijrearefoprds) {
		this.ijrearefoprds = ijrearefoprds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuarioinclusao")
	public Set<Ijrefman> getIjrefmansForCdusuarioinclusao() {
		return this.ijrefmansForCdusuarioinclusao;
	}

	public void setIjrefmansForCdusuarioinclusao(
			Set<Ijrefman> ijrefmansForCdusuarioinclusao) {
		this.ijrefmansForCdusuarioinclusao = ijrefmansForCdusuarioinclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuarioexclusao")
	public Set<Ijrefman> getIjrefmansForCdusuarioexclusao() {
		return this.ijrefmansForCdusuarioexclusao;
	}

	public void setIjrefmansForCdusuarioexclusao(
			Set<Ijrefman> ijrefmansForCdusuarioexclusao) {
		this.ijrefmansForCdusuarioexclusao = ijrefmansForCdusuarioexclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijtbmodisp> getIjtbmodisps() {
		return this.ijtbmodisps;
	}

	public void setIjtbmodisps(Set<Ijtbmodisp> ijtbmodisps) {
		this.ijtbmodisps = ijtbmodisps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijtbprodescont> getIjtbprodesconts() {
		return this.ijtbprodesconts;
	}

	public void setIjtbprodesconts(Set<Ijtbprodescont> ijtbprodesconts) {
		this.ijtbprodesconts = ijtbprodesconts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijtbprousu> getIjtbprousus() {
		return this.ijtbprousus;
	}

	public void setIjtbprousus(Set<Ijtbprousu> ijtbprousus) {
		this.ijtbprousus = ijtbprousus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijconplanning> getIjconplannings() {
		return this.ijconplannings;
	}

	public void setIjconplannings(Set<Ijconplanning> ijconplannings) {
		this.ijconplannings = ijconplannings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdtecinicio")
	public Set<Ijctrliniproc> getIjctrliniprocsForCdtecinicio() {
		return this.ijctrliniprocsForCdtecinicio;
	}

	public void setIjctrliniprocsForCdtecinicio(
			Set<Ijctrliniproc> ijctrliniprocsForCdtecinicio) {
		this.ijctrliniprocsForCdtecinicio = ijctrliniprocsForCdtecinicio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijctrlcgqalt> getIjctrlcgqalts() {
		return this.ijctrlcgqalts;
	}

	public void setIjctrlcgqalts(Set<Ijctrlcgqalt> ijctrlcgqalts) {
		this.ijctrlcgqalts = ijctrlcgqalts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuario")
	public Set<Ijlogsenhatm> getIjlogsenhatmsForCdusuario() {
		return this.ijlogsenhatmsForCdusuario;
	}

	public void setIjlogsenhatmsForCdusuario(
			Set<Ijlogsenhatm> ijlogsenhatmsForCdusuario) {
		this.ijlogsenhatmsForCdusuario = ijlogsenhatmsForCdusuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByDrtresponsa")
	public Set<Ijreapar> getIjreaparsForDrtresponsa() {
		return this.ijreaparsForDrtresponsa;
	}

	public void setIjreaparsForDrtresponsa(Set<Ijreapar> ijreaparsForDrtresponsa) {
		this.ijreaparsForDrtresponsa = ijreaparsForDrtresponsa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdtecfinal")
	public Set<Ijctrliniproc> getIjctrliniprocsForCdtecfinal() {
		return this.ijctrliniprocsForCdtecfinal;
	}

	public void setIjctrliniprocsForCdtecfinal(
			Set<Ijctrliniproc> ijctrliniprocsForCdtecfinal) {
		this.ijctrliniprocsForCdtecfinal = ijctrliniprocsForCdtecfinal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByDrttecnico2")
	public Set<Ijreapar> getIjreaparsForDrttecnico2() {
		return this.ijreaparsForDrttecnico2;
	}

	public void setIjreaparsForDrttecnico2(Set<Ijreapar> ijreaparsForDrttecnico2) {
		this.ijreaparsForDrttecnico2 = ijreaparsForDrttecnico2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijlogvidautil> getIjlogvidautils() {
		return this.ijlogvidautils;
	}

	public void setIjlogvidautils(Set<Ijlogvidautil> ijlogvidautils) {
		this.ijlogvidautils = ijlogvidautils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByDrtecnico1")
	public Set<Ijreapar> getIjreaparsForDrtecnico1() {
		return this.ijreaparsForDrtecnico1;
	}

	public void setIjreaparsForDrtecnico1(Set<Ijreapar> ijreaparsForDrtecnico1) {
		this.ijreaparsForDrtecnico1 = ijreaparsForDrtecnico1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdadmin")
	public Set<Ijlogsenhatm> getIjlogsenhatmsForCdadmin() {
		return this.ijlogsenhatmsForCdadmin;
	}

	public void setIjlogsenhatmsForCdadmin(
			Set<Ijlogsenhatm> ijlogsenhatmsForCdadmin) {
		this.ijlogsenhatmsForCdadmin = ijlogsenhatmsForCdadmin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByDrttecnico2")
	public Set<Ijlogcorrreq> getIjlogcorrreqsForDrttecnico2() {
		return this.ijlogcorrreqsForDrttecnico2;
	}

	public void setIjlogcorrreqsForDrttecnico2(
			Set<Ijlogcorrreq> ijlogcorrreqsForDrttecnico2) {
		this.ijlogcorrreqsForDrttecnico2 = ijlogcorrreqsForDrttecnico2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByDrtresponsa")
	public Set<Ijlogcorrreq> getIjlogcorrreqsForDrtresponsa() {
		return this.ijlogcorrreqsForDrtresponsa;
	}

	public void setIjlogcorrreqsForDrtresponsa(
			Set<Ijlogcorrreq> ijlogcorrreqsForDrtresponsa) {
		this.ijlogcorrreqsForDrtresponsa = ijlogcorrreqsForDrtresponsa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijkanbanmov> getIjkanbanmovs() {
		return this.ijkanbanmovs;
	}

	public void setIjkanbanmovs(Set<Ijkanbanmov> ijkanbanmovs) {
		this.ijkanbanmovs = ijkanbanmovs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijlogcorrpar> getIjlogcorrpars() {
		return this.ijlogcorrpars;
	}

	public void setIjlogcorrpars(Set<Ijlogcorrpar> ijlogcorrpars) {
		this.ijlogcorrpars = ijlogcorrpars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuario")
	public Set<Ijlogcorrreq> getIjlogcorrreqsForCdusuario() {
		return this.ijlogcorrreqsForCdusuario;
	}

	public void setIjlogcorrreqsForCdusuario(
			Set<Ijlogcorrreq> ijlogcorrreqsForCdusuario) {
		this.ijlogcorrreqsForCdusuario = ijlogcorrreqsForCdusuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuariornc")
	public Set<Ijqldinspecao> getIjqldinspecaosForCdusuariornc() {
		return this.ijqldinspecaosForCdusuariornc;
	}

	public void setIjqldinspecaosForCdusuariornc(
			Set<Ijqldinspecao> ijqldinspecaosForCdusuariornc) {
		this.ijqldinspecaosForCdusuariornc = ijqldinspecaosForCdusuariornc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijreacicopoprd> getIjreacicopoprds() {
		return this.ijreacicopoprds;
	}

	public void setIjreacicopoprds(Set<Ijreacicopoprd> ijreacicopoprds) {
		this.ijreacicopoprds = ijreacicopoprds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdoperador")
	public Set<Ijreainspprod> getIjreainspprodsForCdoperador() {
		return this.ijreainspprodsForCdoperador;
	}

	public void setIjreainspprodsForCdoperador(
			Set<Ijreainspprod> ijreainspprodsForCdoperador) {
		this.ijreainspprodsForCdoperador = ijreainspprodsForCdoperador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusucanceloulote")
	public Set<Ijqldprodinsplote> getIjqldprodinsplotesForCdusucanceloulote() {
		return this.ijqldprodinsplotesForCdusucanceloulote;
	}

	public void setIjqldprodinsplotesForCdusucanceloulote(
			Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusucanceloulote) {
		this.ijqldprodinsplotesForCdusucanceloulote = ijqldprodinsplotesForCdusucanceloulote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijqldsupervisor> getIjqldsupervisors() {
		return this.ijqldsupervisors;
	}

	public void setIjqldsupervisors(Set<Ijqldsupervisor> ijqldsupervisors) {
		this.ijqldsupervisors = ijqldsupervisors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdtecisemprog")
	public Set<Ijreamovsemprog> getIjreamovsemprogsForCdtecisemprog() {
		return this.ijreamovsemprogsForCdtecisemprog;
	}

	public void setIjreamovsemprogsForCdtecisemprog(
			Set<Ijreamovsemprog> ijreamovsemprogsForCdtecisemprog) {
		this.ijreamovsemprogsForCdtecisemprog = ijreamovsemprogsForCdtecisemprog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdtecfsemprog")
	public Set<Ijreamovsemprog> getIjreamovsemprogsForCdtecfsemprog() {
		return this.ijreamovsemprogsForCdtecfsemprog;
	}

	public void setIjreamovsemprogsForCdtecfsemprog(
			Set<Ijreamovsemprog> ijreamovsemprogsForCdtecfsemprog) {
		this.ijreamovsemprogsForCdtecfsemprog = ijreamovsemprogsForCdtecfsemprog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusujustificativa")
	public Set<Ijreainspprod> getIjreainspprodsForCdusujustificativa() {
		return this.ijreainspprodsForCdusujustificativa;
	}

	public void setIjreainspprodsForCdusujustificativa(
			Set<Ijreainspprod> ijreainspprodsForCdusujustificativa) {
		this.ijreainspprodsForCdusujustificativa = ijreainspprodsForCdusujustificativa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijreajuscav> getIjreajuscavs() {
		return this.ijreajuscavs;
	}

	public void setIjreajuscavs(Set<Ijreajuscav> ijreajuscavs) {
		this.ijreajuscavs = ijreajuscavs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijlogexcdadosmolde> getIjlogexcdadosmoldes() {
		return this.ijlogexcdadosmoldes;
	}

	public void setIjlogexcdadosmoldes(
			Set<Ijlogexcdadosmolde> ijlogexcdadosmoldes) {
		this.ijlogexcdadosmoldes = ijlogexcdadosmoldes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByDrttecnico1")
	public Set<Ijlogcorrreq> getIjlogcorrreqsForDrttecnico1() {
		return this.ijlogcorrreqsForDrttecnico1;
	}

	public void setIjlogcorrreqsForDrttecnico1(
			Set<Ijlogcorrreq> ijlogcorrreqsForDrttecnico1) {
		this.ijlogcorrreqsForDrttecnico1 = ijlogcorrreqsForDrttecnico1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuabriulote")
	public Set<Ijqldprodinsplote> getIjqldprodinsplotesForCdusuabriulote() {
		return this.ijqldprodinsplotesForCdusuabriulote;
	}

	public void setIjqldprodinsplotesForCdusuabriulote(
			Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusuabriulote) {
		this.ijqldprodinsplotesForCdusuabriulote = ijqldprodinsplotesForCdusuabriulote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijlogopemaq> getIjlogopemaqs() {
		return this.ijlogopemaqs;
	}

	public void setIjlogopemaqs(Set<Ijlogopemaq> ijlogopemaqs) {
		this.ijlogopemaqs = ijlogopemaqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusufechoulote")
	public Set<Ijqldprodinsplote> getIjqldprodinsplotesForCdusufechoulote() {
		return this.ijqldprodinsplotesForCdusufechoulote;
	}

	public void setIjqldprodinsplotesForCdusufechoulote(
			Set<Ijqldprodinsplote> ijqldprodinsplotesForCdusufechoulote) {
		this.ijqldprodinsplotesForCdusufechoulote = ijqldprodinsplotesForCdusufechoulote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijlogope> getIjlogopes() {
		return this.ijlogopes;
	}

	public void setIjlogopes(Set<Ijlogope> ijlogopes) {
		this.ijlogopes = ijlogopes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijlogipesemconexao> getIjlogipesemconexaos() {
		return this.ijlogipesemconexaos;
	}

	public void setIjlogipesemconexaos(
			Set<Ijlogipesemconexao> ijlogipesemconexaos) {
		this.ijlogipesemconexaos = ijlogipesemconexaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijloggalabc> getIjloggalabcs() {
		return this.ijloggalabcs;
	}

	public void setIjloggalabcs(Set<Ijloggalabc> ijloggalabcs) {
		this.ijloggalabcs = ijloggalabcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuarioaut")
	public Set<Ijmolproautorizusu> getIjmolproautorizususForCdusuarioaut() {
		return this.ijmolproautorizususForCdusuarioaut;
	}

	public void setIjmolproautorizususForCdusuarioaut(
			Set<Ijmolproautorizusu> ijmolproautorizususForCdusuarioaut) {
		this.ijmolproautorizususForCdusuarioaut = ijmolproautorizususForCdusuarioaut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdususubstituto")
	public Set<Ijmolproautorizusu> getIjmolproautorizususForCdususubstituto() {
		return this.ijmolproautorizususForCdususubstituto;
	}

	public void setIjmolproautorizususForCdususubstituto(
			Set<Ijmolproautorizusu> ijmolproautorizususForCdususubstituto) {
		this.ijmolproautorizususForCdususubstituto = ijmolproautorizususForCdususubstituto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijduimpressaocgq> getIjduimpressaocgqs() {
		return this.ijduimpressaocgqs;
	}

	public void setIjduimpressaocgqs(Set<Ijduimpressaocgq> ijduimpressaocgqs) {
		this.ijduimpressaocgqs = ijduimpressaocgqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijembapont> getIjembaponts() {
		return this.ijembaponts;
	}

	public void setIjembaponts(Set<Ijembapont> ijembaponts) {
		this.ijembaponts = ijembaponts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijmovpostos> getIjmovpostoses() {
		return this.ijmovpostoses;
	}

	public void setIjmovpostoses(Set<Ijmovpostos> ijmovpostoses) {
		this.ijmovpostoses = ijmovpostoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuariobaixa")
	public Set<Ijqldinspecao> getIjqldinspecaosForCdusuariobaixa() {
		return this.ijqldinspecaosForCdusuariobaixa;
	}

	public void setIjqldinspecaosForCdusuariobaixa(
			Set<Ijqldinspecao> ijqldinspecaosForCdusuariobaixa) {
		this.ijqldinspecaosForCdusuariobaixa = ijqldinspecaosForCdusuariobaixa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuarioinspecao")
	public Set<Ijqldinspecao> getIjqldinspecaosForCdusuarioinspecao() {
		return this.ijqldinspecaosForCdusuarioinspecao;
	}

	public void setIjqldinspecaosForCdusuarioinspecao(
			Set<Ijqldinspecao> ijqldinspecaosForCdusuarioinspecao) {
		this.ijqldinspecaosForCdusuarioinspecao = ijqldinspecaosForCdusuarioinspecao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuarioexclusao")
	public Set<Ijqldinspecao> getIjqldinspecaosForCdusuarioexclusao() {
		return this.ijqldinspecaosForCdusuarioexclusao;
	}

	public void setIjqldinspecaosForCdusuarioexclusao(
			Set<Ijqldinspecao> ijqldinspecaosForCdusuarioexclusao) {
		this.ijqldinspecaosForCdusuarioexclusao = ijqldinspecaosForCdusuarioexclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuarioalteracao")
	public Set<Ijqldinspecao> getIjqldinspecaosForCdusuarioalteracao() {
		return this.ijqldinspecaosForCdusuarioalteracao;
	}

	public void setIjqldinspecaosForCdusuarioalteracao(
			Set<Ijqldinspecao> ijqldinspecaosForCdusuarioalteracao) {
		this.ijqldinspecaosForCdusuarioalteracao = ijqldinspecaosForCdusuarioalteracao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijopbloqdet> getIjopbloqdets() {
		return this.ijopbloqdets;
	}

	public void setIjopbloqdets(Set<Ijopbloqdet> ijopbloqdets) {
		this.ijopbloqdets = ijopbloqdets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijocorvarritmo> getIjocorvarritmos() {
		return this.ijocorvarritmos;
	}

	public void setIjocorvarritmos(Set<Ijocorvarritmo> ijocorvarritmos) {
		this.ijocorvarritmos = ijocorvarritmos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijpdcaparticipproj> getIjpdcaparticipprojs() {
		return this.ijpdcaparticipprojs;
	}

	public void setIjpdcaparticipprojs(
			Set<Ijpdcaparticipproj> ijpdcaparticipprojs) {
		this.ijpdcaparticipprojs = ijpdcaparticipprojs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijpdcafupacao> getIjpdcafupacaos() {
		return this.ijpdcafupacaos;
	}

	public void setIjpdcafupacaos(Set<Ijpdcafupacao> ijpdcafupacaos) {
		this.ijpdcafupacaos = ijpdcafupacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijgrpemail> getIjgrpemails() {
		return this.ijgrpemails;
	}

	public void setIjgrpemails(Set<Ijgrpemail> ijgrpemails) {
		this.ijgrpemails = ijgrpemails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdoperador")
	public Set<Ijinspecao> getIjinspecaosForCdoperador() {
		return this.ijinspecaosForCdoperador;
	}

	public void setIjinspecaosForCdoperador(
			Set<Ijinspecao> ijinspecaosForCdoperador) {
		this.ijinspecaosForCdoperador = ijinspecaosForCdoperador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusufimmanut")
	public Set<Ijmanut> getIjmanutsForCdusufimmanut() {
		return this.ijmanutsForCdusufimmanut;
	}

	public void setIjmanutsForCdusufimmanut(
			Set<Ijmanut> ijmanutsForCdusufimmanut) {
		this.ijmanutsForCdusufimmanut = ijmanutsForCdusufimmanut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdsupervisor")
	public Set<Ijinspecao> getIjinspecaosForCdsupervisor() {
		return this.ijinspecaosForCdsupervisor;
	}

	public void setIjinspecaosForCdsupervisor(
			Set<Ijinspecao> ijinspecaosForCdsupervisor) {
		this.ijinspecaosForCdsupervisor = ijinspecaosForCdsupervisor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijgruusu> getIjgruusus() {
		return this.ijgruusus;
	}

	public void setIjgruusus(Set<Ijgruusu> ijgruusus) {
		this.ijgruusus = ijgruusus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuabeos")
	public Set<Ijmanut> getIjmanutsForCdusuabeos() {
		return this.ijmanutsForCdusuabeos;
	}

	public void setIjmanutsForCdusuabeos(Set<Ijmanut> ijmanutsForCdusuabeos) {
		this.ijmanutsForCdusuabeos = ijmanutsForCdusuabeos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusucancelalerta")
	public Set<Ijinspecao> getIjinspecaosForCdusucancelalerta() {
		return this.ijinspecaosForCdusucancelalerta;
	}

	public void setIjinspecaosForCdusucancelalerta(
			Set<Ijinspecao> ijinspecaosForCdusucancelalerta) {
		this.ijinspecaosForCdusucancelalerta = ijinspecaosForCdusucancelalerta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuinimanut")
	public Set<Ijmanut> getIjmanutsForCdusuinimanut() {
		return this.ijmanutsForCdusuinimanut;
	}

	public void setIjmanutsForCdusuinimanut(
			Set<Ijmanut> ijmanutsForCdusuinimanut) {
		this.ijmanutsForCdusuinimanut = ijmanutsForCdusuinimanut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijaledbqldanot> getIjaledbqldanots() {
		return this.ijaledbqldanots;
	}

	public void setIjaledbqldanots(Set<Ijaledbqldanot> ijaledbqldanots) {
		this.ijaledbqldanots = ijaledbqldanots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijespecinsppro> getIjespecinsppros() {
		return this.ijespecinsppros;
	}

	public void setIjespecinsppros(Set<Ijespecinsppro> ijespecinsppros) {
		this.ijespecinsppros = ijespecinsppros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Imp002Logexcops> getImp002Logexcopses() {
		return this.imp002Logexcopses;
	}

	public void setImp002Logexcopses(Set<Imp002Logexcops> imp002Logexcopses) {
		this.imp002Logexcopses = imp002Logexcopses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijfictecautorizmod> getIjfictecautorizmods() {
		return this.ijfictecautorizmods;
	}

	public void setIjfictecautorizmods(
			Set<Ijfictecautorizmod> ijfictecautorizmods) {
		this.ijfictecautorizmods = ijfictecautorizmods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijmolproautorizmod> getIjmolproautorizmods() {
		return this.ijmolproautorizmods;
	}

	public void setIjmolproautorizmods(
			Set<Ijmolproautorizmod> ijmolproautorizmods) {
		this.ijmolproautorizmods = ijmolproautorizmods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijtbusureqtec> getIjtbusureqtecs() {
		return this.ijtbusureqtecs;
	}

	public void setIjtbusureqtecs(Set<Ijtbusureqtec> ijtbusureqtecs) {
		this.ijtbusureqtecs = ijtbusureqtecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijfictec> getIjfictecs() {
		return this.ijfictecs;
	}

	public void setIjfictecs(Set<Ijfictec> ijfictecs) {
		this.ijfictecs = ijfictecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijmolpro> getIjmolpros() {
		return this.ijmolpros;
	}

	public void setIjmolpros(Set<Ijmolpro> ijmolpros) {
		this.ijmolpros = ijmolpros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijtbusutecespec> getIjtbusutecespecs() {
		return this.ijtbusutecespecs;
	}

	public void setIjtbusutecespecs(Set<Ijtbusutecespec> ijtbusutecespecs) {
		this.ijtbusutecespecs = ijtbusutecespecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijenglogciclos> getIjenglogcicloses() {
		return this.ijenglogcicloses;
	}

	public void setIjenglogcicloses(Set<Ijenglogciclos> ijenglogcicloses) {
		this.ijenglogcicloses = ijenglogcicloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijmdoaloc> getIjmdoalocs() {
		return this.ijmdoalocs;
	}

	public void setIjmdoalocs(Set<Ijmdoaloc> ijmdoalocs) {
		this.ijmdoalocs = ijmdoalocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijusudirespec> getIjusudirespecs() {
		return this.ijusudirespecs;
	}

	public void setIjusudirespecs(Set<Ijusudirespec> ijusudirespecs) {
		this.ijusudirespecs = ijusudirespecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijengleituraciclos> getIjengleituracicloses() {
		return this.ijengleituracicloses;
	}

	public void setIjengleituracicloses(
			Set<Ijengleituraciclos> ijengleituracicloses) {
		this.ijengleituracicloses = ijengleituracicloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijmanutregliber> getIjmanutreglibers() {
		return this.ijmanutreglibers;
	}

	public void setIjmanutreglibers(Set<Ijmanutregliber> ijmanutreglibers) {
		this.ijmanutreglibers = ijmanutreglibers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijmanutexectec> getIjmanutexectecs() {
		return this.ijmanutexectecs;
	}

	public void setIjmanutexectecs(Set<Ijmanutexectec> ijmanutexectecs) {
		this.ijmanutexectecs = ijmanutexectecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusufimexec")
	public Set<Ijmanutexec> getIjmanutexecsForCdusufimexec() {
		return this.ijmanutexecsForCdusufimexec;
	}

	public void setIjmanutexecsForCdusufimexec(
			Set<Ijmanutexec> ijmanutexecsForCdusufimexec) {
		this.ijmanutexecsForCdusufimexec = ijmanutexecsForCdusufimexec;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdususubstituto")
	public Set<Ijfictecautorizusu> getIjfictecautorizususForCdususubstituto() {
		return this.ijfictecautorizususForCdususubstituto;
	}

	public void setIjfictecautorizususForCdususubstituto(
			Set<Ijfictecautorizusu> ijfictecautorizususForCdususubstituto) {
		this.ijfictecautorizususForCdususubstituto = ijfictecautorizususForCdususubstituto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuiniexec")
	public Set<Ijmanutexec> getIjmanutexecsForCdusuiniexec() {
		return this.ijmanutexecsForCdusuiniexec;
	}

	public void setIjmanutexecsForCdusuiniexec(
			Set<Ijmanutexec> ijmanutexecsForCdusuiniexec) {
		this.ijmanutexecsForCdusuiniexec = ijmanutexecsForCdusuiniexec;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusuByCdusuarioaut")
	public Set<Ijfictecautorizusu> getIjfictecautorizususForCdusuarioaut() {
		return this.ijfictecautorizususForCdusuarioaut;
	}

	public void setIjfictecautorizususForCdusuarioaut(
			Set<Ijfictecautorizusu> ijfictecautorizususForCdusuarioaut) {
		this.ijfictecautorizususForCdusuarioaut = ijfictecautorizususForCdusuarioaut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusu")
	public Set<Ijmanutchklst> getIjmanutchklsts() {
		return this.ijmanutchklsts;
	}

	public void setIjmanutchklsts(Set<Ijmanutchklst> ijmanutchklsts) {
		this.ijmanutchklsts = ijmanutchklsts;
	}

}
