package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbtipoinf generated by hbm2java
 */
@Entity
@Table(name = "IJTBTIPOINF")
public class Ijtbtipoinf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6699968273501143385L;
	private String cdtipoinf;
	private String dstipoinf;
	private String nomeicone;
	private String cdinterno;
	private Set<Ijclassificcont> ijclassificconts = new HashSet<Ijclassificcont>(
			0);
	private Set<Ijclassificinf> ijclassificinfs = new HashSet<Ijclassificinf>(0);

	public Ijtbtipoinf() {
	}

	public Ijtbtipoinf(String cdtipoinf, String dstipoinf, String nomeicone,
			String cdinterno) {
		this.cdtipoinf = cdtipoinf;
		this.dstipoinf = dstipoinf;
		this.nomeicone = nomeicone;
		this.cdinterno = cdinterno;
	}

	public Ijtbtipoinf(String cdtipoinf, String dstipoinf, String nomeicone,
			String cdinterno, Set<Ijclassificcont> ijclassificconts,
			Set<Ijclassificinf> ijclassificinfs) {
		this.cdtipoinf = cdtipoinf;
		this.dstipoinf = dstipoinf;
		this.nomeicone = nomeicone;
		this.cdinterno = cdinterno;
		this.ijclassificconts = ijclassificconts;
		this.ijclassificinfs = ijclassificinfs;
	}

	@Id
	@Column(name = "CDTIPOINF", unique = true, nullable = false, length = 6)
	public String getCdtipoinf() {
		return this.cdtipoinf;
	}

	public void setCdtipoinf(String cdtipoinf) {
		this.cdtipoinf = cdtipoinf;
	}

	@Column(name = "DSTIPOINF", nullable = false, length = 30)
	public String getDstipoinf() {
		return this.dstipoinf;
	}

	public void setDstipoinf(String dstipoinf) {
		this.dstipoinf = dstipoinf;
	}

	@Column(name = "NOMEICONE", nullable = false, length = 20)
	public String getNomeicone() {
		return this.nomeicone;
	}

	public void setNomeicone(String nomeicone) {
		this.nomeicone = nomeicone;
	}

	@Column(name = "CDINTERNO", nullable = false, length = 20)
	public String getCdinterno() {
		return this.cdinterno;
	}

	public void setCdinterno(String cdinterno) {
		this.cdinterno = cdinterno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbtipoinf")
	public Set<Ijclassificcont> getIjclassificconts() {
		return this.ijclassificconts;
	}

	public void setIjclassificconts(Set<Ijclassificcont> ijclassificconts) {
		this.ijclassificconts = ijclassificconts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbtipoinf")
	public Set<Ijclassificinf> getIjclassificinfs() {
		return this.ijclassificinfs;
	}

	public void setIjclassificinfs(Set<Ijclassificinf> ijclassificinfs) {
		this.ijclassificinfs = ijclassificinfs;
	}

}
