package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbmenipe generated by hbm2java
 */
@Entity
@Table(name = "IJTBMENIPE")
public class Ijtbmenipe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7600339170698160844L;
	private String cdmensagemipe;
	private String dsmensagemipe;
	private Set<Ijocormenipe> ijocormenipes = new HashSet<Ijocormenipe>(0);

	public Ijtbmenipe() {
	}

	public Ijtbmenipe(String cdmensagemipe) {
		this.cdmensagemipe = cdmensagemipe;
	}

	public Ijtbmenipe(String cdmensagemipe, String dsmensagemipe,
			Set<Ijocormenipe> ijocormenipes) {
		this.cdmensagemipe = cdmensagemipe;
		this.dsmensagemipe = dsmensagemipe;
		this.ijocormenipes = ijocormenipes;
	}

	@Id
	@Column(name = "CDMENSAGEMIPE", unique = true, nullable = false, length = 6)
	public String getCdmensagemipe() {
		return this.cdmensagemipe;
	}

	public void setCdmensagemipe(String cdmensagemipe) {
		this.cdmensagemipe = cdmensagemipe;
	}

	@Column(name = "DSMENSAGEMIPE", length = 60)
	public String getDsmensagemipe() {
		return this.dsmensagemipe;
	}

	public void setDsmensagemipe(String dsmensagemipe) {
		this.dsmensagemipe = dsmensagemipe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmenipe")
	public Set<Ijocormenipe> getIjocormenipes() {
		return this.ijocormenipes;
	}

	public void setIjocormenipes(Set<Ijocormenipe> ijocormenipes) {
		this.ijocormenipes = ijocormenipes;
	}

}
