package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbmolusaidcav generated by hbm2java
 */
@Entity
@Table(name = "IJTBMOLUSAIDCAV")
public class Ijtbmolusaidcav implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3834569319892044178L;
	private String cdmolde;
	private Ijtbmol ijtbmol;
	private String usaidcav;

	public Ijtbmolusaidcav() {
	}

	public Ijtbmolusaidcav(String cdmolde, Ijtbmol ijtbmol, String usaidcav) {
		this.cdmolde = cdmolde;
		this.ijtbmol = ijtbmol;
		this.usaidcav = usaidcav;
	}

	@Id
	@Column(name = "CDMOLDE", unique = true, nullable = false, length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMOLDE", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbmol getIjtbmol() {
		return this.ijtbmol;
	}

	public void setIjtbmol(Ijtbmol ijtbmol) {
		this.ijtbmol = ijtbmol;
	}

	@Column(name = "USAIDCAV", nullable = false, length = 1)
	public String getUsaidcav() {
		return this.usaidcav;
	}

	public void setUsaidcav(String usaidcav) {
		this.usaidcav = usaidcav;
	}

}
