package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbtipofiltro generated by hbm2java
 */
@Entity
@Table(name = "IJTBTIPOFILTRO")
public class Ijtbtipofiltro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6689735946377104302L;
	private String cdtipofiltro;
	private Ijlinguas ijlinguas;
	private String dstipofiltrocomp;
	private String dstipofiltrored;
	private String indtipofiltro;
	private String nometabela;
	private String cdinterno;
	private Set<Ijitensfiltro> ijitensfiltros = new HashSet<Ijitensfiltro>(0);
	private Set<Ijfiltroitensmen> ijfiltroitensmens = new HashSet<Ijfiltroitensmen>(
			0);
	private Set<Ijfiltrocont> ijfiltroconts = new HashSet<Ijfiltrocont>(0);

	public Ijtbtipofiltro() {
	}

	public Ijtbtipofiltro(String cdtipofiltro, String dstipofiltrocomp,
			String dstipofiltrored, String indtipofiltro, String cdinterno) {
		this.cdtipofiltro = cdtipofiltro;
		this.dstipofiltrocomp = dstipofiltrocomp;
		this.dstipofiltrored = dstipofiltrored;
		this.indtipofiltro = indtipofiltro;
		this.cdinterno = cdinterno;
	}

	public Ijtbtipofiltro(String cdtipofiltro, Ijlinguas ijlinguas,
			String dstipofiltrocomp, String dstipofiltrored,
			String indtipofiltro, String nometabela, String cdinterno,
			Set<Ijitensfiltro> ijitensfiltros,
			Set<Ijfiltroitensmen> ijfiltroitensmens,
			Set<Ijfiltrocont> ijfiltroconts) {
		this.cdtipofiltro = cdtipofiltro;
		this.ijlinguas = ijlinguas;
		this.dstipofiltrocomp = dstipofiltrocomp;
		this.dstipofiltrored = dstipofiltrored;
		this.indtipofiltro = indtipofiltro;
		this.nometabela = nometabela;
		this.cdinterno = cdinterno;
		this.ijitensfiltros = ijitensfiltros;
		this.ijfiltroitensmens = ijfiltroitensmens;
		this.ijfiltroconts = ijfiltroconts;
	}

	@Id
	@Column(name = "CDTIPOFILTRO", unique = true, nullable = false, length = 6)
	public String getCdtipofiltro() {
		return this.cdtipofiltro;
	}

	public void setCdtipofiltro(String cdtipofiltro) {
		this.cdtipofiltro = cdtipofiltro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLINGUA")
	public Ijlinguas getIjlinguas() {
		return this.ijlinguas;
	}

	public void setIjlinguas(Ijlinguas ijlinguas) {
		this.ijlinguas = ijlinguas;
	}

	@Column(name = "DSTIPOFILTROCOMP", nullable = false, length = 50)
	public String getDstipofiltrocomp() {
		return this.dstipofiltrocomp;
	}

	public void setDstipofiltrocomp(String dstipofiltrocomp) {
		this.dstipofiltrocomp = dstipofiltrocomp;
	}

	@Column(name = "DSTIPOFILTRORED", nullable = false, length = 15)
	public String getDstipofiltrored() {
		return this.dstipofiltrored;
	}

	public void setDstipofiltrored(String dstipofiltrored) {
		this.dstipofiltrored = dstipofiltrored;
	}

	@Column(name = "INDTIPOFILTRO", nullable = false, length = 1)
	public String getIndtipofiltro() {
		return this.indtipofiltro;
	}

	public void setIndtipofiltro(String indtipofiltro) {
		this.indtipofiltro = indtipofiltro;
	}

	@Column(name = "NOMETABELA", length = 20)
	public String getNometabela() {
		return this.nometabela;
	}

	public void setNometabela(String nometabela) {
		this.nometabela = nometabela;
	}

	@Column(name = "CDINTERNO", nullable = false, length = 20)
	public String getCdinterno() {
		return this.cdinterno;
	}

	public void setCdinterno(String cdinterno) {
		this.cdinterno = cdinterno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbtipofiltro")
	public Set<Ijitensfiltro> getIjitensfiltros() {
		return this.ijitensfiltros;
	}

	public void setIjitensfiltros(Set<Ijitensfiltro> ijitensfiltros) {
		this.ijitensfiltros = ijitensfiltros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbtipofiltro")
	public Set<Ijfiltroitensmen> getIjfiltroitensmens() {
		return this.ijfiltroitensmens;
	}

	public void setIjfiltroitensmens(Set<Ijfiltroitensmen> ijfiltroitensmens) {
		this.ijfiltroitensmens = ijfiltroitensmens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbtipofiltro")
	public Set<Ijfiltrocont> getIjfiltroconts() {
		return this.ijfiltroconts;
	}

	public void setIjfiltroconts(Set<Ijfiltrocont> ijfiltroconts) {
		this.ijfiltroconts = ijfiltroconts;
	}

}
