package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbinjtpcoletor generated by hbm2java
 */
@Entity
@Table(name = "IJTBINJTPCOLETOR")
public class Ijtbinjtpcoletor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7164301381666920496L;
	private String cdinjetora;
	private Ijtbinj ijtbinj;
	private BigDecimal idtpcoletor;

	public Ijtbinjtpcoletor() {
	}

	public Ijtbinjtpcoletor(String cdinjetora, Ijtbinj ijtbinj,
			BigDecimal idtpcoletor) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.idtpcoletor = idtpcoletor;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "IDTPCOLETOR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdtpcoletor() {
		return this.idtpcoletor;
	}

	public void setIdtpcoletor(BigDecimal idtpcoletor) {
		this.idtpcoletor = idtpcoletor;
	}

}
