package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbfamiliamaq generated by hbm2java
 */
@Entity
@Table(name = "IJTBFAMILIAMAQ")
public class Ijtbfamiliamaq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7060526559126171916L;
	private String cdfamilia;
	private String nmfamilia;
	private String empresa;
	private Set<Ijfilakanbanintbet> ijfilakanbanintbets = new HashSet<Ijfilakanbanintbet>(
			0);
	private Set<Ijfamiliaxmaq> ijfamiliaxmaqs = new HashSet<Ijfamiliaxmaq>(0);

	public Ijtbfamiliamaq() {
	}

	public Ijtbfamiliamaq(String cdfamilia, String nmfamilia, String empresa) {
		this.cdfamilia = cdfamilia;
		this.nmfamilia = nmfamilia;
		this.empresa = empresa;
	}

	public Ijtbfamiliamaq(String cdfamilia, String nmfamilia, String empresa,
			Set<Ijfilakanbanintbet> ijfilakanbanintbets,
			Set<Ijfamiliaxmaq> ijfamiliaxmaqs) {
		this.cdfamilia = cdfamilia;
		this.nmfamilia = nmfamilia;
		this.empresa = empresa;
		this.ijfilakanbanintbets = ijfilakanbanintbets;
		this.ijfamiliaxmaqs = ijfamiliaxmaqs;
	}

	@Id
	@Column(name = "CDFAMILIA", unique = true, nullable = false, length = 8)
	public String getCdfamilia() {
		return this.cdfamilia;
	}

	public void setCdfamilia(String cdfamilia) {
		this.cdfamilia = cdfamilia;
	}

	@Column(name = "NMFAMILIA", nullable = false, length = 40)
	public String getNmfamilia() {
		return this.nmfamilia;
	}

	public void setNmfamilia(String nmfamilia) {
		this.nmfamilia = nmfamilia;
	}

	@Column(name = "EMPRESA", nullable = false, length = 10)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbfamiliamaq")
	public Set<Ijfilakanbanintbet> getIjfilakanbanintbets() {
		return this.ijfilakanbanintbets;
	}

	public void setIjfilakanbanintbets(
			Set<Ijfilakanbanintbet> ijfilakanbanintbets) {
		this.ijfilakanbanintbets = ijfilakanbanintbets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbfamiliamaq")
	public Set<Ijfamiliaxmaq> getIjfamiliaxmaqs() {
		return this.ijfamiliaxmaqs;
	}

	public void setIjfamiliaxmaqs(Set<Ijfamiliaxmaq> ijfamiliaxmaqs) {
		this.ijfamiliaxmaqs = ijfamiliaxmaqs;
	}

}
