package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjtbmenId generated by hbm2java
 */
@Embeddable
public class IjtbmenId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1900426341932136594L;
	private String cdmensagem;
	private String cdlingua;

	public IjtbmenId() {
	}

	public IjtbmenId(String cdmensagem, String cdlingua) {
		this.cdmensagem = cdmensagem;
		this.cdlingua = cdlingua;
	}

	@Column(name = "CDMENSAGEM", nullable = false, length = 6)
	public String getCdmensagem() {
		return this.cdmensagem;
	}

	public void setCdmensagem(String cdmensagem) {
		this.cdmensagem = cdmensagem;
	}

	@Column(name = "CDLINGUA", nullable = false, length = 6)
	public String getCdlingua() {
		return this.cdlingua;
	}

	public void setCdlingua(String cdlingua) {
		this.cdlingua = cdlingua;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjtbmenId))
			return false;
		IjtbmenId castOther = (IjtbmenId) other;

		return ((this.getCdmensagem() == castOther.getCdmensagem()) || (this
				.getCdmensagem() != null && castOther.getCdmensagem() != null && this
				.getCdmensagem().equals(castOther.getCdmensagem())))
				&& ((this.getCdlingua() == castOther.getCdlingua()) || (this
						.getCdlingua() != null
						&& castOther.getCdlingua() != null && this
						.getCdlingua().equals(castOther.getCdlingua())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdmensagem() == null ? 0 : this.getCdmensagem()
						.hashCode());
		result = 37 * result
				+ (getCdlingua() == null ? 0 : this.getCdlingua().hashCode());
		return result;
	}

}
