package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbjuscav generated by hbm2java
 */
@Entity
@Table(name = "IJTBJUSCAV")
public class Ijtbjuscav implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6858302206628708840L;
	private String cdjuscav;
	private String dsjuscav;
	private char status;
	private Set<Ijmolproautorizmod> ijmolproautorizmods = new HashSet<Ijmolproautorizmod>(
			0);
	private Set<Ijpdcapadrao> ijpdcapadraos = new HashSet<Ijpdcapadrao>(0);
	private Set<Ijreajuscav> ijreajuscavs = new HashSet<Ijreajuscav>(0);

	public Ijtbjuscav() {
	}

	public Ijtbjuscav(String cdjuscav, String dsjuscav, char status) {
		this.cdjuscav = cdjuscav;
		this.dsjuscav = dsjuscav;
		this.status = status;
	}

	public Ijtbjuscav(String cdjuscav, String dsjuscav, char status,
			Set<Ijmolproautorizmod> ijmolproautorizmods,
			Set<Ijpdcapadrao> ijpdcapadraos, Set<Ijreajuscav> ijreajuscavs) {
		this.cdjuscav = cdjuscav;
		this.dsjuscav = dsjuscav;
		this.status = status;
		this.ijmolproautorizmods = ijmolproautorizmods;
		this.ijpdcapadraos = ijpdcapadraos;
		this.ijreajuscavs = ijreajuscavs;
	}

	@Id
	@Column(name = "CDJUSCAV", unique = true, nullable = false, length = 6)
	public String getCdjuscav() {
		return this.cdjuscav;
	}

	public void setCdjuscav(String cdjuscav) {
		this.cdjuscav = cdjuscav;
	}

	@Column(name = "DSJUSCAV", nullable = false, length = 40)
	public String getDsjuscav() {
		return this.dsjuscav;
	}

	public void setDsjuscav(String dsjuscav) {
		this.dsjuscav = dsjuscav;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbjuscav")
	public Set<Ijmolproautorizmod> getIjmolproautorizmods() {
		return this.ijmolproautorizmods;
	}

	public void setIjmolproautorizmods(
			Set<Ijmolproautorizmod> ijmolproautorizmods) {
		this.ijmolproautorizmods = ijmolproautorizmods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbjuscav")
	public Set<Ijpdcapadrao> getIjpdcapadraos() {
		return this.ijpdcapadraos;
	}

	public void setIjpdcapadraos(Set<Ijpdcapadrao> ijpdcapadraos) {
		this.ijpdcapadraos = ijpdcapadraos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbjuscav")
	public Set<Ijreajuscav> getIjreajuscavs() {
		return this.ijreajuscavs;
	}

	public void setIjreajuscavs(Set<Ijreajuscav> ijreajuscavs) {
		this.ijreajuscavs = ijreajuscavs;
	}

}
