package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbintemail generated by hbm2java
 */
@Entity
@Table(name = "IJTBINTEMAIL")
public class Ijtbintemail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7133851908986366583L;
	private String cdintervalo;
	private String dsintervalo;
	private String cdinterno;
	private Set<Ijintinf> ijintinfs = new HashSet<Ijintinf>(0);

	public Ijtbintemail() {
	}

	public Ijtbintemail(String cdintervalo, String dsintervalo, String cdinterno) {
		this.cdintervalo = cdintervalo;
		this.dsintervalo = dsintervalo;
		this.cdinterno = cdinterno;
	}

	public Ijtbintemail(String cdintervalo, String dsintervalo,
			String cdinterno, Set<Ijintinf> ijintinfs) {
		this.cdintervalo = cdintervalo;
		this.dsintervalo = dsintervalo;
		this.cdinterno = cdinterno;
		this.ijintinfs = ijintinfs;
	}

	@Id
	@Column(name = "CDINTERVALO", unique = true, nullable = false, length = 6)
	public String getCdintervalo() {
		return this.cdintervalo;
	}

	public void setCdintervalo(String cdintervalo) {
		this.cdintervalo = cdintervalo;
	}

	@Column(name = "DSINTERVALO", nullable = false, length = 30)
	public String getDsintervalo() {
		return this.dsintervalo;
	}

	public void setDsintervalo(String dsintervalo) {
		this.dsintervalo = dsintervalo;
	}

	@Column(name = "CDINTERNO", nullable = false, length = 20)
	public String getCdinterno() {
		return this.cdinterno;
	}

	public void setCdinterno(String cdinterno) {
		this.cdinterno = cdinterno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbintemail")
	public Set<Ijintinf> getIjintinfs() {
		return this.ijintinfs;
	}

	public void setIjintinfs(Set<Ijintinf> ijintinfs) {
		this.ijintinfs = ijintinfs;
	}

}
