package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbtpocorea generated by hbm2java
 */
@Entity
@Table(name = "IJTBTPOCOREA")
public class Ijtbtpocorea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8345559588062001672L;
	private IjtbtpocoreaId id;
	private Ijlinguas ijlinguas;
	private String dstipooco;

	public Ijtbtpocorea() {
	}

	public Ijtbtpocorea(IjtbtpocoreaId id, Ijlinguas ijlinguas) {
		this.id = id;
		this.ijlinguas = ijlinguas;
	}

	public Ijtbtpocorea(IjtbtpocoreaId id, Ijlinguas ijlinguas, String dstipooco) {
		this.id = id;
		this.ijlinguas = ijlinguas;
		this.dstipooco = dstipooco;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdtipooco", column = @Column(name = "CDTIPOOCO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdlingua", column = @Column(name = "CDLINGUA", nullable = false, length = 6)) })
	public IjtbtpocoreaId getId() {
		return this.id;
	}

	public void setId(IjtbtpocoreaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLINGUA", nullable = false, insertable = false, updatable = false)
	public Ijlinguas getIjlinguas() {
		return this.ijlinguas;
	}

	public void setIjlinguas(Ijlinguas ijlinguas) {
		this.ijlinguas = ijlinguas;
	}

	@Column(name = "DSTIPOOCO", length = 40)
	public String getDstipooco() {
		return this.dstipooco;
	}

	public void setDstipooco(String dstipooco) {
		this.dstipooco = dstipooco;
	}

}
