package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbmen generated by hbm2java
 */
@Entity
@Table(name = "IJTBMEN")
public class Ijtbmen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6775964049231782500L;
	private IjtbmenId id;
	private Ijlinguas ijlinguas;
	private String titulo;
	private String dsmensagem1;
	private String dsmensagem2;
	private String dsmensagem3;
	private BigDecimal lgmax;
	private BigDecimal botoes;
	private BigDecimal botaodefault;
	private String helpfile;
	private BigDecimal contexto;

	public Ijtbmen() {
	}

	public Ijtbmen(IjtbmenId id, Ijlinguas ijlinguas, String titulo,
			String dsmensagem1, BigDecimal botoes, BigDecimal botaodefault) {
		this.id = id;
		this.ijlinguas = ijlinguas;
		this.titulo = titulo;
		this.dsmensagem1 = dsmensagem1;
		this.botoes = botoes;
		this.botaodefault = botaodefault;
	}

	public Ijtbmen(IjtbmenId id, Ijlinguas ijlinguas, String titulo,
			String dsmensagem1, String dsmensagem2, String dsmensagem3,
			BigDecimal lgmax, BigDecimal botoes, BigDecimal botaodefault,
			String helpfile, BigDecimal contexto) {
		this.id = id;
		this.ijlinguas = ijlinguas;
		this.titulo = titulo;
		this.dsmensagem1 = dsmensagem1;
		this.dsmensagem2 = dsmensagem2;
		this.dsmensagem3 = dsmensagem3;
		this.lgmax = lgmax;
		this.botoes = botoes;
		this.botaodefault = botaodefault;
		this.helpfile = helpfile;
		this.contexto = contexto;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdmensagem", column = @Column(name = "CDMENSAGEM", nullable = false, length = 6)),
			@AttributeOverride(name = "cdlingua", column = @Column(name = "CDLINGUA", nullable = false, length = 6)) })
	public IjtbmenId getId() {
		return this.id;
	}

	public void setId(IjtbmenId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLINGUA", nullable = false, insertable = false, updatable = false)
	public Ijlinguas getIjlinguas() {
		return this.ijlinguas;
	}

	public void setIjlinguas(Ijlinguas ijlinguas) {
		this.ijlinguas = ijlinguas;
	}

	@Column(name = "TITULO", nullable = false, length = 40)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "DSMENSAGEM1", nullable = false)
	public String getDsmensagem1() {
		return this.dsmensagem1;
	}

	public void setDsmensagem1(String dsmensagem1) {
		this.dsmensagem1 = dsmensagem1;
	}

	@Column(name = "DSMENSAGEM2")
	public String getDsmensagem2() {
		return this.dsmensagem2;
	}

	public void setDsmensagem2(String dsmensagem2) {
		this.dsmensagem2 = dsmensagem2;
	}

	@Column(name = "DSMENSAGEM3")
	public String getDsmensagem3() {
		return this.dsmensagem3;
	}

	public void setDsmensagem3(String dsmensagem3) {
		this.dsmensagem3 = dsmensagem3;
	}

	@Column(name = "LGMAX", precision = 22, scale = 0)
	public BigDecimal getLgmax() {
		return this.lgmax;
	}

	public void setLgmax(BigDecimal lgmax) {
		this.lgmax = lgmax;
	}

	@Column(name = "BOTOES", nullable = false, precision = 22, scale = 0)
	public BigDecimal getBotoes() {
		return this.botoes;
	}

	public void setBotoes(BigDecimal botoes) {
		this.botoes = botoes;
	}

	@Column(name = "BOTAODEFAULT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getBotaodefault() {
		return this.botaodefault;
	}

	public void setBotaodefault(BigDecimal botaodefault) {
		this.botaodefault = botaodefault;
	}

	@Column(name = "HELPFILE", length = 12)
	public String getHelpfile() {
		return this.helpfile;
	}

	public void setHelpfile(String helpfile) {
		this.helpfile = helpfile;
	}

	@Column(name = "CONTEXTO", precision = 22, scale = 0)
	public BigDecimal getContexto() {
		return this.contexto;
	}

	public void setContexto(BigDecimal contexto) {
		this.contexto = contexto;
	}

}
