package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbcau generated by hbm2java
 */
@Entity
@Table(name = "IJTBCAU")
public class Ijtbcau implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3281021564813450805L;
	private String cdcausas;
	private String dscausas;
	private Character tipocausa;
	private Integer stativo;
	private Set<Ijrearef> ijrearefs = new HashSet<Ijrearef>(0);
	private Set<Ijreapar> ijreapars = new HashSet<Ijreapar>(0);
	private Set<Ijlogcorrreq> ijlogcorrreqs = new HashSet<Ijlogcorrreq>(0);
	private Set<Ijpdcapadrao> ijpdcapadraos = new HashSet<Ijpdcapadrao>(0);
	private Set<Ijpdcaacao> ijpdcaacaos = new HashSet<Ijpdcaacao>(0);

	public Ijtbcau() {
	}

	public Ijtbcau(String cdcausas, Integer stativo) {
		this.cdcausas = cdcausas;
		this.stativo = stativo;
	}

	public Ijtbcau(String cdcausas, String dscausas, Character tipocausa,
			Integer stativo, Set<Ijrearef> ijrearefs,
			Set<Ijreapar> ijreapars, Set<Ijlogcorrreq> ijlogcorrreqs,
			Set<Ijpdcapadrao> ijpdcapadraos, Set<Ijpdcaacao> ijpdcaacaos) {
		this.cdcausas = cdcausas;
		this.dscausas = dscausas;
		this.tipocausa = tipocausa;
		this.stativo = stativo;
		this.ijrearefs = ijrearefs;
		this.ijreapars = ijreapars;
		this.ijlogcorrreqs = ijlogcorrreqs;
		this.ijpdcapadraos = ijpdcapadraos;
		this.ijpdcaacaos = ijpdcaacaos;
	}

	@Id
	@Column(name = "CDCAUSAS", unique = true, nullable = false, length = 6)
	public String getCdcausas() {
		return this.cdcausas;
	}

	public void setCdcausas(String cdcausas) {
		this.cdcausas = cdcausas;
	}

	@Column(name = "DSCAUSAS")
	public String getDscausas() {
		return this.dscausas;
	}

	public void setDscausas(String dscausas) {
		this.dscausas = dscausas;
	}

	@Column(name = "TIPOCAUSA", length = 1)
	public Character getTipocausa() {
		return this.tipocausa;
	}

	public void setTipocausa(Character tipocausa) {
		this.tipocausa = tipocausa;
	}

	@Column(name = "STATIVO", nullable = false, precision = 22, scale = 0)
	public Integer getStativo() {
		return this.stativo;
	}

	public void setStativo(Integer stativo) {
		this.stativo = stativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbcau")
	public Set<Ijrearef> getIjrearefs() {
		return this.ijrearefs;
	}

	public void setIjrearefs(Set<Ijrearef> ijrearefs) {
		this.ijrearefs = ijrearefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbcau")
	public Set<Ijreapar> getIjreapars() {
		return this.ijreapars;
	}

	public void setIjreapars(Set<Ijreapar> ijreapars) {
		this.ijreapars = ijreapars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbcau")
	public Set<Ijlogcorrreq> getIjlogcorrreqs() {
		return this.ijlogcorrreqs;
	}

	public void setIjlogcorrreqs(Set<Ijlogcorrreq> ijlogcorrreqs) {
		this.ijlogcorrreqs = ijlogcorrreqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbcau")
	public Set<Ijpdcapadrao> getIjpdcapadraos() {
		return this.ijpdcapadraos;
	}

	public void setIjpdcapadraos(Set<Ijpdcapadrao> ijpdcapadraos) {
		this.ijpdcapadraos = ijpdcapadraos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbcau")
	public Set<Ijpdcaacao> getIjpdcaacaos() {
		return this.ijpdcaacaos;
	}

	public void setIjpdcaacaos(Set<Ijpdcaacao> ijpdcaacaos) {
		this.ijpdcaacaos = ijpdcaacaos;
	}

}
