package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbinf generated by hbm2java
 */
@Entity
@Table(name = "IJTBINF")
public class Ijtbinf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3100870494516882108L;
	private String cdinf;
	private Ijtbtipoger ijtbtipoger;
	private Ijlinguas ijlinguas;
	private String titulocomp;
	private String titulored;
	private String tipografico;
	private String indinftotal;
	private String cdinterno;
	private Set<Ijintinf> ijintinfs = new HashSet<Ijintinf>(0);
	private Set<Ijclassificinf> ijclassificinfs = new HashSet<Ijclassificinf>(0);
	private Set<Ijparaminf> ijparaminfs = new HashSet<Ijparaminf>(0);

	public Ijtbinf() {
	}

	public Ijtbinf(String cdinf, Ijtbtipoger ijtbtipoger, String titulocomp,
			String titulored, String cdinterno) {
		this.cdinf = cdinf;
		this.ijtbtipoger = ijtbtipoger;
		this.titulocomp = titulocomp;
		this.titulored = titulored;
		this.cdinterno = cdinterno;
	}

	public Ijtbinf(String cdinf, Ijtbtipoger ijtbtipoger, Ijlinguas ijlinguas,
			String titulocomp, String titulored, String tipografico,
			String indinftotal, String cdinterno, Set<Ijintinf> ijintinfs,
			Set<Ijclassificinf> ijclassificinfs, Set<Ijparaminf> ijparaminfs) {
		this.cdinf = cdinf;
		this.ijtbtipoger = ijtbtipoger;
		this.ijlinguas = ijlinguas;
		this.titulocomp = titulocomp;
		this.titulored = titulored;
		this.tipografico = tipografico;
		this.indinftotal = indinftotal;
		this.cdinterno = cdinterno;
		this.ijintinfs = ijintinfs;
		this.ijclassificinfs = ijclassificinfs;
		this.ijparaminfs = ijparaminfs;
	}

	@Id
	@Column(name = "CDINF", unique = true, nullable = false, length = 6)
	public String getCdinf() {
		return this.cdinf;
	}

	public void setCdinf(String cdinf) {
		this.cdinf = cdinf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTIPOGER", nullable = false)
	public Ijtbtipoger getIjtbtipoger() {
		return this.ijtbtipoger;
	}

	public void setIjtbtipoger(Ijtbtipoger ijtbtipoger) {
		this.ijtbtipoger = ijtbtipoger;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDLINGUA")
	public Ijlinguas getIjlinguas() {
		return this.ijlinguas;
	}

	public void setIjlinguas(Ijlinguas ijlinguas) {
		this.ijlinguas = ijlinguas;
	}

	@Column(name = "TITULOCOMP", nullable = false, length = 50)
	public String getTitulocomp() {
		return this.titulocomp;
	}

	public void setTitulocomp(String titulocomp) {
		this.titulocomp = titulocomp;
	}

	@Column(name = "TITULORED", nullable = false, length = 15)
	public String getTitulored() {
		return this.titulored;
	}

	public void setTitulored(String titulored) {
		this.titulored = titulored;
	}

	@Column(name = "TIPOGRAFICO", length = 1)
	public String getTipografico() {
		return this.tipografico;
	}

	public void setTipografico(String tipografico) {
		this.tipografico = tipografico;
	}

	@Column(name = "INDINFTOTAL", length = 1)
	public String getIndinftotal() {
		return this.indinftotal;
	}

	public void setIndinftotal(String indinftotal) {
		this.indinftotal = indinftotal;
	}

	@Column(name = "CDINTERNO", nullable = false, length = 20)
	public String getCdinterno() {
		return this.cdinterno;
	}

	public void setCdinterno(String cdinterno) {
		this.cdinterno = cdinterno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinf")
	public Set<Ijintinf> getIjintinfs() {
		return this.ijintinfs;
	}

	public void setIjintinfs(Set<Ijintinf> ijintinfs) {
		this.ijintinfs = ijintinfs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinf")
	public Set<Ijclassificinf> getIjclassificinfs() {
		return this.ijclassificinfs;
	}

	public void setIjclassificinfs(Set<Ijclassificinf> ijclassificinfs) {
		this.ijclassificinfs = ijclassificinfs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinf")
	public Set<Ijparaminf> getIjparaminfs() {
		return this.ijparaminfs;
	}

	public void setIjparaminfs(Set<Ijparaminf> ijparaminfs) {
		this.ijparaminfs = ijparaminfs;
	}

}
