package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijtbacolog generated by hbm2java
 */
@Entity
@Table(name = "IJTBACOLOG")
public class Ijtbacolog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 843891686948364138L;
	private IjtbacologId id;

	public Ijtbacolog() {
	}

	public Ijtbacolog(IjtbacologId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdacoes", column = @Column(name = "CDACOES", nullable = false, length = 6)),
			@AttributeOverride(name = "dsacoes", column = @Column(name = "DSACOES")),
			@AttributeOverride(name = "tipoacao", column = @Column(name = "TIPOACAO", length = 1)),
			@AttributeOverride(name = "stativo", column = @Column(name = "STATIVO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", nullable = false, length = 6)) })
	public IjtbacologId getId() {
		return this.id;
	}

	public void setId(IjtbacologId id) {
		this.id = id;
	}

}
