package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijtbusumail generated by hbm2java
 */
@Entity
@Table(name = "IJTBUSUMAIL")
public class Ijtbusumail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4135259952572626172L;
	private String cdusumail;
	private Ijtbusumail ijtbusumail;
	private Ijtbset ijtbset;
	private String nome;
	private String endemail1;
	private String endemail2;
	private Date dthrcadastro;
	private Date dthrsaida;
	private String indenvioemail;
	private String indformatitulo;
	private String indformacorpo;
	private Set<Ijtbusu> ijtbusus = new HashSet<Ijtbusu>(0);
	private Set<Ijpdcaparticipproj> ijpdcaparticipprojs = new HashSet<Ijpdcaparticipproj>(
			0);
	private Set<Ijgrpusuemail> ijgrpusuemails = new HashSet<Ijgrpusuemail>(0);
	private Set<Ijtbusumail> ijtbusumails = new HashSet<Ijtbusumail>(0);
	private Set<Ijtbusumailsms> ijtbusumailsmses = new HashSet<Ijtbusumailsms>(
			0);

	public Ijtbusumail() {
	}

	public Ijtbusumail(String cdusumail, String nome, String endemail1,
			Date dthrcadastro, String indenvioemail, String indformatitulo,
			String indformacorpo) {
		this.cdusumail = cdusumail;
		this.nome = nome;
		this.endemail1 = endemail1;
		this.dthrcadastro = dthrcadastro;
		this.indenvioemail = indenvioemail;
		this.indformatitulo = indformatitulo;
		this.indformacorpo = indformacorpo;
	}

	public Ijtbusumail(String cdusumail, Ijtbusumail ijtbusumail,
			Ijtbset ijtbset, String nome, String endemail1, String endemail2,
			Date dthrcadastro, Date dthrsaida, String indenvioemail,
			String indformatitulo, String indformacorpo, Set<Ijtbusu> ijtbusus,
			Set<Ijpdcaparticipproj> ijpdcaparticipprojs,
			Set<Ijgrpusuemail> ijgrpusuemails, Set<Ijtbusumail> ijtbusumails,
			Set<Ijtbusumailsms> ijtbusumailsmses) {
		this.cdusumail = cdusumail;
		this.ijtbusumail = ijtbusumail;
		this.ijtbset = ijtbset;
		this.nome = nome;
		this.endemail1 = endemail1;
		this.endemail2 = endemail2;
		this.dthrcadastro = dthrcadastro;
		this.dthrsaida = dthrsaida;
		this.indenvioemail = indenvioemail;
		this.indformatitulo = indformatitulo;
		this.indformacorpo = indformacorpo;
		this.ijtbusus = ijtbusus;
		this.ijpdcaparticipprojs = ijpdcaparticipprojs;
		this.ijgrpusuemails = ijgrpusuemails;
		this.ijtbusumails = ijtbusumails;
		this.ijtbusumailsmses = ijtbusumailsmses;
	}

	@Id
	@Column(name = "CDUSUMAIL", unique = true, nullable = false, length = 6)
	public String getCdusumail() {
		return this.cdusumail;
	}

	public void setCdusumail(String cdusumail) {
		this.cdusumail = cdusumail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDUSUSUP")
	public Ijtbusumail getIjtbusumail() {
		return this.ijtbusumail;
	}

	public void setIjtbusumail(Ijtbusumail ijtbusumail) {
		this.ijtbusumail = ijtbusumail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDSETOR")
	public Ijtbset getIjtbset() {
		return this.ijtbset;
	}

	public void setIjtbset(Ijtbset ijtbset) {
		this.ijtbset = ijtbset;
	}

	@Column(name = "NOME", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "ENDEMAIL1", nullable = false, length = 50)
	public String getEndemail1() {
		return this.endemail1;
	}

	public void setEndemail1(String endemail1) {
		this.endemail1 = endemail1;
	}

	@Column(name = "ENDEMAIL2", length = 50)
	public String getEndemail2() {
		return this.endemail2;
	}

	public void setEndemail2(String endemail2) {
		this.endemail2 = endemail2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRCADASTRO", nullable = false, length = 7)
	public Date getDthrcadastro() {
		return this.dthrcadastro;
	}

	public void setDthrcadastro(Date dthrcadastro) {
		this.dthrcadastro = dthrcadastro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRSAIDA", length = 7)
	public Date getDthrsaida() {
		return this.dthrsaida;
	}

	public void setDthrsaida(Date dthrsaida) {
		this.dthrsaida = dthrsaida;
	}

	@Column(name = "INDENVIOEMAIL", nullable = false, length = 1)
	public String getIndenvioemail() {
		return this.indenvioemail;
	}

	public void setIndenvioemail(String indenvioemail) {
		this.indenvioemail = indenvioemail;
	}

	@Column(name = "INDFORMATITULO", nullable = false, length = 1)
	public String getIndformatitulo() {
		return this.indformatitulo;
	}

	public void setIndformatitulo(String indformatitulo) {
		this.indformatitulo = indformatitulo;
	}

	@Column(name = "INDFORMACORPO", nullable = false, length = 1)
	public String getIndformacorpo() {
		return this.indformacorpo;
	}

	public void setIndformacorpo(String indformacorpo) {
		this.indformacorpo = indformacorpo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusumail")
	public Set<Ijtbusu> getIjtbusus() {
		return this.ijtbusus;
	}

	public void setIjtbusus(Set<Ijtbusu> ijtbusus) {
		this.ijtbusus = ijtbusus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusumail")
	public Set<Ijpdcaparticipproj> getIjpdcaparticipprojs() {
		return this.ijpdcaparticipprojs;
	}

	public void setIjpdcaparticipprojs(
			Set<Ijpdcaparticipproj> ijpdcaparticipprojs) {
		this.ijpdcaparticipprojs = ijpdcaparticipprojs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusumail")
	public Set<Ijgrpusuemail> getIjgrpusuemails() {
		return this.ijgrpusuemails;
	}

	public void setIjgrpusuemails(Set<Ijgrpusuemail> ijgrpusuemails) {
		this.ijgrpusuemails = ijgrpusuemails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusumail")
	public Set<Ijtbusumail> getIjtbusumails() {
		return this.ijtbusumails;
	}

	public void setIjtbusumails(Set<Ijtbusumail> ijtbusumails) {
		this.ijtbusumails = ijtbusumails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbusumail")
	public Set<Ijtbusumailsms> getIjtbusumailsmses() {
		return this.ijtbusumailsmses;
	}

	public void setIjtbusumailsmses(Set<Ijtbusumailsms> ijtbusumailsmses) {
		this.ijtbusumailsmses = ijtbusumailsmses;
	}

}
