package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbpardefctrlipro generated by hbm2java
 */
@Entity
@Table(name = "IJTBPARDEFCTRLIPRO")
public class Ijtbpardefctrlipro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -48082107447114079L;
	private String cdparada;
	private Ijtbpar ijtbpar;

	public Ijtbpardefctrlipro() {
	}

	public Ijtbpardefctrlipro(String cdparada) {
		this.cdparada = cdparada;
	}

	public Ijtbpardefctrlipro(String cdparada, Ijtbpar ijtbpar) {
		this.cdparada = cdparada;
		this.ijtbpar = ijtbpar;
	}

	@Id
	@Column(name = "CDPARADA", length = 6)
	public String getCdparada() {
		return this.cdparada;
	}

	public void setCdparada(String cdparada) {
		this.cdparada = cdparada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPARADA", insertable = false, updatable = false)
	public Ijtbpar getIjtbpar() {
		return this.ijtbpar;
	}

	public void setIjtbpar(Ijtbpar ijtbpar) {
		this.ijtbpar = ijtbpar;
	}

}
