package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijtbreflog generated by hbm2java
 */
@Entity
@Table(name = "IJTBREFLOG")
public class Ijtbreflog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1637545082450468393L;
	private IjtbreflogId id;

	public Ijtbreflog() {
	}

	public Ijtbreflog(IjtbreflogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdrefugo", column = @Column(name = "CDREFUGO", nullable = false, length = 6)),
			@AttributeOverride(name = "cdarea", column = @Column(name = "CDAREA", nullable = false, length = 6)),
			@AttributeOverride(name = "dsrefugo", column = @Column(name = "DSREFUGO", length = 40)),
			@AttributeOverride(name = "lrequercausa", column = @Column(name = "LREQUERCAUSA", precision = 22, scale = 0)),
			@AttributeOverride(name = "lrequeracao", column = @Column(name = "LREQUERACAO", precision = 22, scale = 0)),
			@AttributeOverride(name = "indtolerqld", column = @Column(name = "INDTOLERQLD", precision = 126, scale = 0)),
			@AttributeOverride(name = "stativo", column = @Column(name = "STATIVO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "refreprocesso", column = @Column(name = "REFREPROCESSO", nullable = false, length = 1)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", length = 6)) })
	public IjtbreflogId getId() {
		return this.id;
	}

	public void setId(IjtbreflogId id) {
		this.id = id;
	}

}
