package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijtbinjlog generated by hbm2java
 */
@Entity
@Table(name = "IJTBINJLOG")
public class Ijtbinjlog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8714054920677461991L;
	private IjtbinjlogId id;

	public Ijtbinjlog() {
	}

	public Ijtbinjlog(IjtbinjlogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "opatual", column = @Column(name = "OPATUAL", length = 10)),
			@AttributeOverride(name = "cdfabricante", column = @Column(name = "CDFABRICANTE", nullable = false, length = 6)),
			@AttributeOverride(name = "cdidentific", column = @Column(name = "CDIDENTIFIC", length = 10)),
			@AttributeOverride(name = "tonelagem", column = @Column(name = "TONELAGEM", length = 10)),
			@AttributeOverride(name = "marca", column = @Column(name = "MARCA", length = 20)),
			@AttributeOverride(name = "modelo", column = @Column(name = "MODELO", length = 20)),
			@AttributeOverride(name = "dtcompra", column = @Column(name = "DTCOMPRA", length = 7)),
			@AttributeOverride(name = "dtinstalacao", column = @Column(name = "DTINSTALACAO", length = 7)),
			@AttributeOverride(name = "dtfgarantia", column = @Column(name = "DTFGARANTIA", length = 7)),
			@AttributeOverride(name = "dtsaida", column = @Column(name = "DTSAIDA", length = 7)),
			@AttributeOverride(name = "paraonde", column = @Column(name = "PARAONDE", length = 30)),
			@AttributeOverride(name = "stinjetora", column = @Column(name = "STINJETORA", precision = 22, scale = 0)),
			@AttributeOverride(name = "stfuncionamento", column = @Column(name = "STFUNCIONAMENTO", length = 1)),
			@AttributeOverride(name = "maquinaemalerta", column = @Column(name = "MAQUINAEMALERTA", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "aguardandomolde", column = @Column(name = "AGUARDANDOMOLDE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdparada", column = @Column(name = "CDPARADA", length = 6)),
			@AttributeOverride(name = "dthriparada", column = @Column(name = "DTHRIPARADA", length = 7)),
			@AttributeOverride(name = "dthrfparada", column = @Column(name = "DTHRFPARADA", length = 7)),
			@AttributeOverride(name = "cdmestre", column = @Column(name = "CDMESTRE", length = 6)),
			@AttributeOverride(name = "cdcoletor", column = @Column(name = "CDCOLETOR", length = 6)),
			@AttributeOverride(name = "contadoracesso", column = @Column(name = "CONTADORACESSO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizartabparada", column = @Column(name = "ATUALIZARTABPARADA", precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizartabrefugo", column = @Column(name = "ATUALIZARTABREFUGO", precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizartabmolde", column = @Column(name = "ATUALIZARTABMOLDE", precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizartabcausas", column = @Column(name = "ATUALIZARTABCAUSAS", precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizartabacoes", column = @Column(name = "ATUALIZARTABACOES", precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizartabjustif", column = @Column(name = "ATUALIZARTABJUSTIF", precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizartabalerta", column = @Column(name = "ATUALIZARTABALERTA", precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizartabtecnic", column = @Column(name = "ATUALIZARTABTECNIC", precision = 22, scale = 0)),
			@AttributeOverride(name = "atualizaconfigsys", column = @Column(name = "ATUALIZACONFIGSYS", precision = 22, scale = 0)),
			@AttributeOverride(name = "hrtrabalhadas", column = @Column(name = "HRTRABALHADAS", precision = 126, scale = 0)),
			@AttributeOverride(name = "hrparamanutencao", column = @Column(name = "HRPARAMANUTENCAO", precision = 126, scale = 0)),
			@AttributeOverride(name = "hrconttrab", column = @Column(name = "HRCONTTRAB", precision = 126, scale = 0)),
			@AttributeOverride(name = "vaolivrehor", column = @Column(name = "VAOLIVREHOR", precision = 126, scale = 0)),
			@AttributeOverride(name = "vaolivrever", column = @Column(name = "VAOLIVREVER", precision = 126, scale = 0)),
			@AttributeOverride(name = "capacidadeinjecao", column = @Column(name = "CAPACIDADEINJECAO", precision = 126, scale = 0)),
			@AttributeOverride(name = "altmin", column = @Column(name = "ALTMIN", precision = 126, scale = 0)),
			@AttributeOverride(name = "altmax", column = @Column(name = "ALTMAX", precision = 126, scale = 0)),
			@AttributeOverride(name = "txhora", column = @Column(name = "TXHORA", precision = 126, scale = 0)),
			@AttributeOverride(name = "tipomaquina", column = @Column(name = "TIPOMAQUINA", precision = 22, scale = 0)),
			@AttributeOverride(name = "coletaautomatica", column = @Column(name = "COLETAAUTOMATICA", precision = 22, scale = 0)),
			@AttributeOverride(name = "fatortickrelogio", column = @Column(name = "FATORTICKRELOGIO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "precisaocompact", column = @Column(name = "PRECISAOCOMPACT", precision = 126, scale = 0)),
			@AttributeOverride(name = "cdsetor", column = @Column(name = "CDSETOR", length = 6)),
			@AttributeOverride(name = "alertainspqld", column = @Column(name = "ALERTAINSPQLD", length = 1)),
			@AttributeOverride(name = "freqmanutprev", column = @Column(name = "FREQMANUTPREV", precision = 126, scale = 0)),
			@AttributeOverride(name = "qthorastrabalhadas", column = @Column(name = "QTHORASTRABALHADAS", precision = 126, scale = 0)),
			@AttributeOverride(name = "stultinspqld", column = @Column(name = "STULTINSPQLD", length = 1)),
			@AttributeOverride(name = "metaoee", column = @Column(name = "METAOEE", precision = 126, scale = 0)),
			@AttributeOverride(name = "cdmoldeatual", column = @Column(name = "CDMOLDEATUAL", length = 6)),
			@AttributeOverride(name = "cdestruturaatual", column = @Column(name = "CDESTRUTURAATUAL", length = 4)),
			@AttributeOverride(name = "tpicone", column = @Column(name = "TPICONE", length = 20)),
			@AttributeOverride(name = "tpabertsessaoprod", column = @Column(name = "TPABERTSESSAOPROD", length = 1)),
			@AttributeOverride(name = "procmultiferr", column = @Column(name = "PROCMULTIFERR", length = 1)),
			@AttributeOverride(name = "cdsubcoletor", column = @Column(name = "CDSUBCOLETOR", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdinjestendido", column = @Column(name = "CDINJESTENDIDO", nullable = false, length = 8)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", nullable = false, length = 6)) })
	public IjtbinjlogId getId() {
		return this.id;
	}

	public void setId(IjtbinjlogId id) {
		this.id = id;
	}

}
