package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbale generated by hbm2java
 */
@Entity
@Table(name = "IJTBALE")
public class Ijtbale implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1451097484237802564L;
	private String cdalerta;
	private String dsalerta;
	private Set<Ijalertas> ijalertases = new HashSet<Ijalertas>(0);

	public Ijtbale() {
	}

	public Ijtbale(String cdalerta) {
		this.cdalerta = cdalerta;
	}

	public Ijtbale(String cdalerta, String dsalerta, Set<Ijalertas> ijalertases) {
		this.cdalerta = cdalerta;
		this.dsalerta = dsalerta;
		this.ijalertases = ijalertases;
	}

	@Id
	@Column(name = "CDALERTA", unique = true, nullable = false, length = 6)
	public String getCdalerta() {
		return this.cdalerta;
	}

	public void setCdalerta(String cdalerta) {
		this.cdalerta = cdalerta;
	}

	@Column(name = "DSALERTA", length = 40)
	public String getDsalerta() {
		return this.dsalerta;
	}

	public void setDsalerta(String dsalerta) {
		this.dsalerta = dsalerta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbale")
	public Set<Ijalertas> getIjalertases() {
		return this.ijalertases;
	}

	public void setIjalertases(Set<Ijalertas> ijalertases) {
		this.ijalertases = ijalertases;
	}

}
