package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbboard generated by hbm2java
 */
@Entity
@Table(name = "IJTBBOARD")
public class Ijtbboard implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3841208154369216461L;
	private double campo01;
	private char campo04;
	private double campo05;
	private double campo06;
	private Set<Ijtbboardtranslate> ijtbboardtranslates = new HashSet<Ijtbboardtranslate>(
			0);
	private Set<Ijtbboardmach> ijtbboardmachs = new HashSet<Ijtbboardmach>(0);

	public Ijtbboard() {
	}

	public Ijtbboard(double campo01, char campo04, double campo05,
			double campo06) {
		this.campo01 = campo01;
		this.campo04 = campo04;
		this.campo05 = campo05;
		this.campo06 = campo06;
	}

	public Ijtbboard(double campo01, char campo04, double campo05,
			double campo06, Set<Ijtbboardtranslate> ijtbboardtranslates,
			Set<Ijtbboardmach> ijtbboardmachs) {
		this.campo01 = campo01;
		this.campo04 = campo04;
		this.campo05 = campo05;
		this.campo06 = campo06;
		this.ijtbboardtranslates = ijtbboardtranslates;
		this.ijtbboardmachs = ijtbboardmachs;
	}

	@Id
	@Column(name = "CAMPO01", unique = true, nullable = false, precision = 126, scale = 0)
	public double getCampo01() {
		return this.campo01;
	}

	public void setCampo01(double campo01) {
		this.campo01 = campo01;
	}

	@Column(name = "CAMPO04", nullable = false, length = 1)
	public char getCampo04() {
		return this.campo04;
	}

	public void setCampo04(char campo04) {
		this.campo04 = campo04;
	}

	@Column(name = "CAMPO05", nullable = false, precision = 126, scale = 0)
	public double getCampo05() {
		return this.campo05;
	}

	public void setCampo05(double campo05) {
		this.campo05 = campo05;
	}

	@Column(name = "CAMPO06", nullable = false, precision = 126, scale = 0)
	public double getCampo06() {
		return this.campo06;
	}

	public void setCampo06(double campo06) {
		this.campo06 = campo06;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbboard")
	public Set<Ijtbboardtranslate> getIjtbboardtranslates() {
		return this.ijtbboardtranslates;
	}

	public void setIjtbboardtranslates(
			Set<Ijtbboardtranslate> ijtbboardtranslates) {
		this.ijtbboardtranslates = ijtbboardtranslates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbboard")
	public Set<Ijtbboardmach> getIjtbboardmachs() {
		return this.ijtbboardmachs;
	}

	public void setIjtbboardmachs(Set<Ijtbboardmach> ijtbboardmachs) {
		this.ijtbboardmachs = ijtbboardmachs;
	}

}
