package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbinjclassabc generated by hbm2java
 */
@Entity
@Table(name = "IJTBINJCLASSABC")
public class Ijtbinjclassabc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7095116042047794161L;
	private String cdinjetora;
	private Ijtbinj ijtbinj;
	private char classe;

	public Ijtbinjclassabc() {
	}

	public Ijtbinjclassabc(String cdinjetora, Ijtbinj ijtbinj, char classe) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.classe = classe;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "CLASSE", nullable = false, length = 1)
	public char getClasse() {
		return this.classe;
	}

	public void setClasse(char classe) {
		this.classe = classe;
	}

}
