package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbopcmenu generated by hbm2java
 */
@Entity
@Table(name = "IJTBOPCMENU")
public class Ijtbopcmenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4077993796088012505L;
	private String cdopcao;
	private Ijtbmodulos ijtbmodulos;
	private String nmopcao;
	private String dsopcao;
	private String shortcut;
	private String nmfuncao;
	private String nmobjeto;
	private BigDecimal stopcao;
	private BigDecimal nivel;
	private String subniveldecdopcao;
	private Set<Ijdiremp> ijdiremps = new HashSet<Ijdiremp>(0);
	private Set<Ijdirace> ijdiraces = new HashSet<Ijdirace>(0);

	public Ijtbopcmenu() {
	}

	public Ijtbopcmenu(String cdopcao, Ijtbmodulos ijtbmodulos) {
		this.cdopcao = cdopcao;
		this.ijtbmodulos = ijtbmodulos;
	}

	public Ijtbopcmenu(String cdopcao, Ijtbmodulos ijtbmodulos, String nmopcao,
			String dsopcao, String shortcut, String nmfuncao, String nmobjeto,
			BigDecimal stopcao, BigDecimal nivel, String subniveldecdopcao,
			Set<Ijdiremp> ijdiremps, Set<Ijdirace> ijdiraces) {
		this.cdopcao = cdopcao;
		this.ijtbmodulos = ijtbmodulos;
		this.nmopcao = nmopcao;
		this.dsopcao = dsopcao;
		this.shortcut = shortcut;
		this.nmfuncao = nmfuncao;
		this.nmobjeto = nmobjeto;
		this.stopcao = stopcao;
		this.nivel = nivel;
		this.subniveldecdopcao = subniveldecdopcao;
		this.ijdiremps = ijdiremps;
		this.ijdiraces = ijdiraces;
	}

	@Id
	@Column(name = "CDOPCAO", unique = true, nullable = false, length = 6)
	public String getCdopcao() {
		return this.cdopcao;
	}

	public void setCdopcao(String cdopcao) {
		this.cdopcao = cdopcao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMODULO", nullable = false)
	public Ijtbmodulos getIjtbmodulos() {
		return this.ijtbmodulos;
	}

	public void setIjtbmodulos(Ijtbmodulos ijtbmodulos) {
		this.ijtbmodulos = ijtbmodulos;
	}

	@Column(name = "NMOPCAO", length = 40)
	public String getNmopcao() {
		return this.nmopcao;
	}

	public void setNmopcao(String nmopcao) {
		this.nmopcao = nmopcao;
	}

	@Column(name = "DSOPCAO", length = 60)
	public String getDsopcao() {
		return this.dsopcao;
	}

	public void setDsopcao(String dsopcao) {
		this.dsopcao = dsopcao;
	}

	@Column(name = "SHORTCUT", length = 20)
	public String getShortcut() {
		return this.shortcut;
	}

	public void setShortcut(String shortcut) {
		this.shortcut = shortcut;
	}

	@Column(name = "NMFUNCAO", length = 30)
	public String getNmfuncao() {
		return this.nmfuncao;
	}

	public void setNmfuncao(String nmfuncao) {
		this.nmfuncao = nmfuncao;
	}

	@Column(name = "NMOBJETO", length = 30)
	public String getNmobjeto() {
		return this.nmobjeto;
	}

	public void setNmobjeto(String nmobjeto) {
		this.nmobjeto = nmobjeto;
	}

	@Column(name = "STOPCAO", precision = 22, scale = 0)
	public BigDecimal getStopcao() {
		return this.stopcao;
	}

	public void setStopcao(BigDecimal stopcao) {
		this.stopcao = stopcao;
	}

	@Column(name = "NIVEL", precision = 22, scale = 0)
	public BigDecimal getNivel() {
		return this.nivel;
	}

	public void setNivel(BigDecimal nivel) {
		this.nivel = nivel;
	}

	@Column(name = "SUBNIVELDECDOPCAO", length = 6)
	public String getSubniveldecdopcao() {
		return this.subniveldecdopcao;
	}

	public void setSubniveldecdopcao(String subniveldecdopcao) {
		this.subniveldecdopcao = subniveldecdopcao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbopcmenu")
	public Set<Ijdiremp> getIjdiremps() {
		return this.ijdiremps;
	}

	public void setIjdiremps(Set<Ijdiremp> ijdiremps) {
		this.ijdiremps = ijdiremps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbopcmenu")
	public Set<Ijdirace> getIjdiraces() {
		return this.ijdiraces;
	}

	public void setIjdiraces(Set<Ijdirace> ijdiraces) {
		this.ijdiraces = ijdiraces;
	}

}
