package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbtpdado generated by hbm2java
 */
@Entity
@Table(name = "IJTBTPDADO")
public class Ijtbtpdado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1969186779699821332L;
	private String cdtpdado;
	private String dstpdado;
	private String mascara;
	private Set<Ijtbesttab> ijtbesttabs = new HashSet<Ijtbesttab>(0);

	public Ijtbtpdado() {
	}

	public Ijtbtpdado(String cdtpdado, String dstpdado) {
		this.cdtpdado = cdtpdado;
		this.dstpdado = dstpdado;
	}

	public Ijtbtpdado(String cdtpdado, String dstpdado, String mascara,
			Set<Ijtbesttab> ijtbesttabs) {
		this.cdtpdado = cdtpdado;
		this.dstpdado = dstpdado;
		this.mascara = mascara;
		this.ijtbesttabs = ijtbesttabs;
	}

	@Id
	@Column(name = "CDTPDADO", unique = true, nullable = false, length = 6)
	public String getCdtpdado() {
		return this.cdtpdado;
	}

	public void setCdtpdado(String cdtpdado) {
		this.cdtpdado = cdtpdado;
	}

	@Column(name = "DSTPDADO", nullable = false, length = 40)
	public String getDstpdado() {
		return this.dstpdado;
	}

	public void setDstpdado(String dstpdado) {
		this.dstpdado = dstpdado;
	}

	@Column(name = "MASCARA", length = 40)
	public String getMascara() {
		return this.mascara;
	}

	public void setMascara(String mascara) {
		this.mascara = mascara;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbtpdado")
	public Set<Ijtbesttab> getIjtbesttabs() {
		return this.ijtbesttabs;
	}

	public void setIjtbesttabs(Set<Ijtbesttab> ijtbesttabs) {
		this.ijtbesttabs = ijtbesttabs;
	}

}
