package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ijtbinj generated by hbm2java
 */
@Entity
@Table(name = "IJTBINJ", uniqueConstraints = @UniqueConstraint(columnNames = "CDINJESTENDIDO"))
public class Ijtbinj extends IjtbinjTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2780667422065274174L;
	private String cdinjetora;
	private Ijtbpar ijtbpar;
	private Ijtbfab ijtbfab;
	private Ijtbset ijtbset;
	private String opatual;
	private String cdidentific;
	private String tonelagem;
	private String marca;
	private String modelo;
	private Date dtcompra;
	private Date dtinstalacao;
	private Date dtfgarantia;
	private Date dtsaida;
	private String paraonde;
	private Integer stinjetora;
	private String stfuncionamento;
	private BigDecimal maquinaemalerta;
	private BigDecimal aguardandomolde;
	private Date dthriparada;
	private Date dthrfparada;
	private String cdmestre;
	private String cdcoletor;
	private BigDecimal contadoracesso;
	private BigDecimal atualizartabparada;
	private BigDecimal atualizartabrefugo;
	private BigDecimal atualizartabmolde;
	private BigDecimal atualizartabcausas;
	private BigDecimal atualizartabacoes;
	private BigDecimal atualizartabjustif;
	private BigDecimal atualizartabalerta;
	private BigDecimal atualizartabtecnic;
	private BigDecimal atualizaconfigsys;
	private Double hrtrabalhadas;
	private Double hrparamanutencao;
	private Double hrconttrab;
	private Double vaolivrehor;
	private Double vaolivrever;
	private Double capacidadeinjecao;
	private Double altmin;
	private Double altmax;
	private Double txhora;
	private BigDecimal tipomaquina;
	private BigDecimal coletaautomatica;
	private BigDecimal fatortickrelogio;
	private Double precisaocompact;
	private Character alertainspqld;
	private Double freqmanutprev;
	private Double qthorastrabalhadas;
	private Character stultinspqld;
	private Double metaoee;
	private String cdmoldeatual;
	private String cdestruturaatual;
	private String tpicone;
	private Character tpabertsessaoprod;
	private Character procmultiferr;
	private BigDecimal cdsubcoletor;
	private String cdinjestendido;
	private Set<Ijhorexc> ijhorexcs = new HashSet<Ijhorexc>(0);
	private Set<Ijinspecao> ijinspecaos = new HashSet<Ijinspecao>(0);
	private Set<Ijiniopinj> ijiniopinjs = new HashSet<Ijiniopinj>(0);
	private Set<Ijlogcorrpar> ijlogcorrpars = new HashSet<Ijlogcorrpar>(0);
	private Set<Ijkanbanlote> ijkanbanlotes = new HashSet<Ijkanbanlote>(0);
	private Set<Ijloginj> ijloginjs = new HashSet<Ijloginj>(0);
	private Set<Ijlogcorrreq> ijlogcorrreqs = new HashSet<Ijlogcorrreq>(0);
	private Set<Ijlogopemaq> ijlogopemaqs = new HashSet<Ijlogopemaq>(0);
	private Set<Ijlogipesemconexao> ijlogipesemconexaos = new HashSet<Ijlogipesemconexao>(
			0);
	private Set<Ijgrpinjpar> ijgrpinjpars = new HashSet<Ijgrpinjpar>(0);
	private Set<Ijgrpinjref> ijgrpinjrefs = new HashSet<Ijgrpinjref>(0);
	private Set<Ijgalobj> ijgalobjs = new HashSet<Ijgalobj>(0);
	private Set<Ijfictecconfig> ijfictecconfigs = new HashSet<Ijfictecconfig>(0);
	private Set<Ijfictec> ijfictecs = new HashSet<Ijfictec>(0);
	private Set<Ijficinj> ijficinjs = new HashSet<Ijficinj>(0);
	private Set<Ijgrpdetinj> ijgrpdetinjs = new HashSet<Ijgrpdetinj>(0);
	private Set<Ijgrpdetestproc> ijgrpdetestprocs = new HashSet<Ijgrpdetestproc>(
			0);
	private Set<Ijgalobjmtrz> ijgalobjmtrzsForCdinjetora = new HashSet<Ijgalobjmtrz>(
			0);
	private Set<Ijgalobjmtrz> ijgalobjmtrzsForCdposto = new HashSet<Ijgalobjmtrz>(
			0);
	private Set<Ijficcnc> ijficcncs = new HashSet<Ijficcnc>(0);
	private Set<Ijentsaiopmaq> ijentsaiopmaqs = new HashSet<Ijentsaiopmaq>(0);
	private Set<Ijfamiliaxmaq> ijfamiliaxmaqs = new HashSet<Ijfamiliaxmaq>(0);
	private Set<Ijcfgandmaqevt> ijcfgandmaqevts = new HashSet<Ijcfgandmaqevt>(0);
	private Set<Ijcomequipamento> ijcomequipamentos = new HashSet<Ijcomequipamento>(
			0);
	private Set<Ijcncturno> ijcncturnos = new HashSet<Ijcncturno>(0);
	private Set<Ijctrlresultinsp> ijctrlresultinsps = new HashSet<Ijctrlresultinsp>(
			0);
	private Set<Ijctrlresnegqld2> ijctrlresnegqld2s = new HashSet<Ijctrlresnegqld2>(
			0);
	private Set<Ijinjctrlultparmon> ijinjctrlultparmons = new HashSet<Ijinjctrlultparmon>(
			0);
	private Set<Ijmatrizsetup> ijmatrizsetups = new HashSet<Ijmatrizsetup>(0);
	private Set<Ijinjcfgmetamonit> ijinjcfgmetamonits = new HashSet<Ijinjcfgmetamonit>(
			0);
	private Set<Ijctrliniproc> ijctrliniprocs = new HashSet<Ijctrliniproc>(0);
	private Set<Ijctrlalertaandon> ijctrlalertaandons = new HashSet<Ijctrlalertaandon>(
			0);
	private Set<Ijtbinjqldctrl> ijtbinjqldctrls = new HashSet<Ijtbinjqldctrl>(0);
	private Set<Ijctrlresnegqld1> ijctrlresnegqld1s = new HashSet<Ijctrlresnegqld1>(
			0);
	private Set<Ijctrliniproctemp> ijctrliniproctemps = new HashSet<Ijctrliniproctemp>(
			0);
	private Set<Ijversaoproducao> ijversaoproducaos = new HashSet<Ijversaoproducao>(
			0);
	private Set<Ijtmpsetup> ijtmpsetups = new HashSet<Ijtmpsetup>(0);
	private Set<Ijtmpultst> ijtmpultsts = new HashSet<Ijtmpultst>(0);
	private Set<Ijtbmol> ijtbmols = new HashSet<Ijtbmol>(0);
	private Set<Ijtbslidesxmaq> ijtbslidesxmaqs = new HashSet<Ijtbslidesxmaq>(0);
	private Set<Ijacumpar> ijacumpars = new HashSet<Ijacumpar>(0);
	private Set<Exportacao006> exportacao006s = new HashSet<Exportacao006>(0);
	private Set<Ijtbinjtpcoletor> ijtbinjtpcoletors = new HashSet<Ijtbinjtpcoletor>(
			0);
	private Set<Ijcentrocustoxmaq> ijcentrocustoxmaqs = new HashSet<Ijcentrocustoxmaq>(
			0);
	private Set<Ijcelxmaq> ijcelxmaqsForCdmaqdestino = new HashSet<Ijcelxmaq>(0);
	private Set<Ijtbinjsincparprog> ijtbinjsincparprogs = new HashSet<Ijtbinjsincparprog>(
			0);
	private Set<Ijtbinjultop> ijtbinjultops = new HashSet<Ijtbinjultop>(0);
	private Set<Ijcelxmaq> ijcelxmaqsForCdinjetora = new HashSet<Ijcelxmaq>(0);
	private Set<Ijtbinjtpproc> ijtbinjtpprocs = new HashSet<Ijtbinjtpproc>(0);
	private Set<Ijbroneinjapt> ijbroneinjapts = new HashSet<Ijbroneinjapt>(0);
	private Set<Ijalertasauto> ijalertasautos = new HashSet<Ijalertasauto>(0);
	private Set<Ijaleinj> ijaleinjs = new HashSet<Ijaleinj>(0);
	private Set<Ijacumref> ijacumrefs = new HashSet<Ijacumref>(0);
	private Set<Ijtbinjplanning> ijtbinjplannings = new HashSet<Ijtbinjplanning>(
			0);
	private Set<Ijacumprod> ijacumprods = new HashSet<Ijacumprod>(0);
	private Set<Ijtbinjmodinsp> ijtbinjmodinsps = new HashSet<Ijtbinjmodinsp>(0);
	private Set<Ijtbinjoper> ijtbinjopers = new HashSet<Ijtbinjoper>(0);
	private Set<Ijtbinjclassabc> ijtbinjclassabcs = new HashSet<Ijtbinjclassabc>(
			0);
	private Set<Ijtbinjconfig> ijtbinjconfigs = new HashSet<Ijtbinjconfig>(0);
	private Set<Exportacao004> exportacao004s = new HashSet<Exportacao004>(0);
	private Set<Ijtbinjctrliniproc> ijtbinjctrliniprocs = new HashSet<Ijtbinjctrliniproc>(
			0);
	private Set<Ijtbinjlinhamontag> ijtbinjlinhamontags = new HashSet<Ijtbinjlinhamontag>(
			0);
	private Set<Ijtbinjbloq> ijtbinjbloqs = new HashSet<Ijtbinjbloq>(0);
	private Set<Ijtbinjcfgerp> ijtbinjcfgerps = new HashSet<Ijtbinjcfgerp>(0);
	private Set<Ijtbinjandonprcsft> ijtbinjandonprcsfts = new HashSet<Ijtbinjandonprcsft>(
			0);
	private Set<Ijtbinjauxdrvcelc> ijtbinjauxdrvcelcs = new HashSet<Ijtbinjauxdrvcelc>(
			0);
	private Set<Ijregultocorop> ijregultocorops = new HashSet<Ijregultocorop>(0);
	private Set<Ijregultocorinj> ijregultocorinjs = new HashSet<Ijregultocorinj>(
			0);
	private Set<Ijrefman> ijrefmans = new HashSet<Ijrefman>(0);
	private Set<Ijrefextra> ijrefextras = new HashSet<Ijrefextra>(0);
	private Set<Ijtbinjalerta> ijtbinjalertas = new HashSet<Ijtbinjalerta>(0);
	private Set<Ijtbdnc> ijtbdncs = new HashSet<Ijtbdnc>(0);
	private Set<Ijsitipe> ijsitipes = new HashSet<Ijsitipe>(0);
	private Set<Ijtbinjstatus> ijtbinjstatuses = new HashSet<Ijtbinjstatus>(0);
	private Set<Ijreapar> ijreapars = new HashSet<Ijreapar>(0);
	private Set<Ijreapeso> ijreapesos = new HashSet<Ijreapeso>(0);
	private Set<Ijrearea> ijreareas = new HashSet<Ijrearea>(0);
	private Set<Ijqldprodinsplote> ijqldprodinsplotes = new HashSet<Ijqldprodinsplote>(
			0);
	private Set<Ijqldinspecao> ijqldinspecaos = new HashSet<Ijqldinspecao>(0);
	private Set<Ijreacic> ijreacics = new HashSet<Ijreacic>(0);
	private Set<Ijqldsupervisor> ijqldsupervisors = new HashSet<Ijqldsupervisor>(
			0);
	private Set<Ijreacnc> ijreacncs = new HashSet<Ijreacnc>(0);
	private Set<Ijreacicop> ijreacicops = new HashSet<Ijreacicop>(0);
	private Set<Ijreamovsemprog> ijreamovsemprogs = new HashSet<Ijreamovsemprog>(
			0);
	private Set<Ijreainspprod> ijreainspprods = new HashSet<Ijreainspprod>(0);
	private Set<Ijpropeso> ijpropesos = new HashSet<Ijpropeso>(0);
	private Set<Ijproqtope> ijproqtopes = new HashSet<Ijproqtope>(0);
	private Set<Ijplanop> ijplanops = new HashSet<Ijplanop>(0);
	private Set<Ijparprog> ijparprogs = new HashSet<Ijparprog>(0);
	private Set<Ijoproteiro> ijoproteiros = new HashSet<Ijoproteiro>(0);
	private Set<Ijopproqtope> ijopproqtopes = new HashSet<Ijopproqtope>(0);
	private Set<Ijoplotes> ijoploteses = new HashSet<Ijoplotes>(0);
	private Set<Ijop> ijops = new HashSet<Ijop>(0);
	private Set<Ijocorvarritmo> ijocorvarritmos = new HashSet<Ijocorvarritmo>(0);
	private Set<Ijocorreploteins> ijocorreploteinses = new HashSet<Ijocorreploteins>(
			0);
	private Set<Ijmovpostos> ijmovpostoses = new HashSet<Ijmovpostos>(0);
	private Set<Ijmdoaloc> ijmdoalocs = new HashSet<Ijmdoaloc>(0);
	private Set<Ijctrlturnoint> ijctrlturnoints = new HashSet<Ijctrlturnoint>(0);
	private Set<Ijengleituraciclos> ijengleituracicloses = new HashSet<Ijengleituraciclos>(
			0);
	private Set<Ijenglogciclos> ijenglogcicloses = new HashSet<Ijenglogciclos>(
			0);
	private Set<Ijctrlultturmaq> ijctrlultturmaqs = new HashSet<Ijctrlultturmaq>(
			0);
	private Set<Ijdeparamaq> ijdeparamaqs = new HashSet<Ijdeparamaq>(0);

	public Ijtbinj() {
	}

	public Ijtbinj(String cdinjetora, Ijtbfab ijtbfab,
			BigDecimal maquinaemalerta, BigDecimal aguardandomolde,
			BigDecimal contadoracesso, BigDecimal fatortickrelogio,
			BigDecimal cdsubcoletor, String cdinjestendido) {
		this.cdinjetora = cdinjetora;
		this.ijtbfab = ijtbfab;
		this.maquinaemalerta = maquinaemalerta;
		this.aguardandomolde = aguardandomolde;
		this.contadoracesso = contadoracesso;
		this.fatortickrelogio = fatortickrelogio;
		this.cdsubcoletor = cdsubcoletor;
		this.cdinjestendido = cdinjestendido;
	}

	public Ijtbinj(String cdinjetora, Ijtbpar ijtbpar, Ijtbfab ijtbfab,
			Ijtbset ijtbset, String opatual, String cdidentific,
			String tonelagem, String marca, String modelo, Date dtcompra,
			Date dtinstalacao, Date dtfgarantia, Date dtsaida, String paraonde,
			Integer stinjetora, String stfuncionamento,
			BigDecimal maquinaemalerta, BigDecimal aguardandomolde,
			Date dthriparada, Date dthrfparada, String cdmestre,
			String cdcoletor, BigDecimal contadoracesso,
			BigDecimal atualizartabparada, BigDecimal atualizartabrefugo,
			BigDecimal atualizartabmolde, BigDecimal atualizartabcausas,
			BigDecimal atualizartabacoes, BigDecimal atualizartabjustif,
			BigDecimal atualizartabalerta, BigDecimal atualizartabtecnic,
			BigDecimal atualizaconfigsys, Double hrtrabalhadas,
			Double hrparamanutencao, Double hrconttrab, Double vaolivrehor,
			Double vaolivrever, Double capacidadeinjecao, Double altmin,
			Double altmax, Double txhora, BigDecimal tipomaquina,
			BigDecimal coletaautomatica, BigDecimal fatortickrelogio,
			Double precisaocompact, Character alertainspqld,
			Double freqmanutprev, Double qthorastrabalhadas,
			Character stultinspqld, Double metaoee, String cdmoldeatual,
			String cdestruturaatual, String tpicone,
			Character tpabertsessaoprod, Character procmultiferr,
			BigDecimal cdsubcoletor, String cdinjestendido,
			Set<Ijhorexc> ijhorexcs, Set<Ijinspecao> ijinspecaos,
			Set<Ijiniopinj> ijiniopinjs, Set<Ijlogcorrpar> ijlogcorrpars,
			Set<Ijkanbanlote> ijkanbanlotes, Set<Ijloginj> ijloginjs,
			Set<Ijlogcorrreq> ijlogcorrreqs, Set<Ijlogopemaq> ijlogopemaqs,
			Set<Ijlogipesemconexao> ijlogipesemconexaos,
			Set<Ijgrpinjpar> ijgrpinjpars, Set<Ijgrpinjref> ijgrpinjrefs,
			Set<Ijgalobj> ijgalobjs, Set<Ijfictecconfig> ijfictecconfigs,
			Set<Ijfictec> ijfictecs, Set<Ijficinj> ijficinjs,
			Set<Ijgrpdetinj> ijgrpdetinjs,
			Set<Ijgrpdetestproc> ijgrpdetestprocs,
			Set<Ijgalobjmtrz> ijgalobjmtrzsForCdinjetora,
			Set<Ijgalobjmtrz> ijgalobjmtrzsForCdposto, Set<Ijficcnc> ijficcncs,
			Set<Ijentsaiopmaq> ijentsaiopmaqs,
			Set<Ijfamiliaxmaq> ijfamiliaxmaqs,
			Set<Ijcfgandmaqevt> ijcfgandmaqevts,
			Set<Ijcomequipamento> ijcomequipamentos,
			Set<Ijcncturno> ijcncturnos,
			Set<Ijctrlresultinsp> ijctrlresultinsps,
			Set<Ijctrlresnegqld2> ijctrlresnegqld2s,
			Set<Ijinjctrlultparmon> ijinjctrlultparmons,
			Set<Ijmatrizsetup> ijmatrizsetups,
			Set<Ijinjcfgmetamonit> ijinjcfgmetamonits,
			Set<Ijctrliniproc> ijctrliniprocs,
			Set<Ijctrlalertaandon> ijctrlalertaandons,
			Set<Ijtbinjqldctrl> ijtbinjqldctrls,
			Set<Ijctrlresnegqld1> ijctrlresnegqld1s,
			Set<Ijctrliniproctemp> ijctrliniproctemps,
			Set<Ijversaoproducao> ijversaoproducaos,
			Set<Ijtmpsetup> ijtmpsetups, Set<Ijtmpultst> ijtmpultsts,
			Set<Ijtbmol> ijtbmols, Set<Ijtbslidesxmaq> ijtbslidesxmaqs,
			Set<Ijacumpar> ijacumpars, Set<Exportacao006> exportacao006s,
			Set<Ijtbinjtpcoletor> ijtbinjtpcoletors,
			Set<Ijcentrocustoxmaq> ijcentrocustoxmaqs,
			Set<Ijcelxmaq> ijcelxmaqsForCdmaqdestino,
			Set<Ijtbinjsincparprog> ijtbinjsincparprogs,
			Set<Ijtbinjultop> ijtbinjultops,
			Set<Ijcelxmaq> ijcelxmaqsForCdinjetora,
			Set<Ijtbinjtpproc> ijtbinjtpprocs,
			Set<Ijbroneinjapt> ijbroneinjapts,
			Set<Ijalertasauto> ijalertasautos, Set<Ijaleinj> ijaleinjs,
			Set<Ijacumref> ijacumrefs, Set<Ijtbinjplanning> ijtbinjplannings,
			Set<Ijacumprod> ijacumprods, Set<Ijtbinjmodinsp> ijtbinjmodinsps,
			Set<Ijtbinjoper> ijtbinjopers,
			Set<Ijtbinjclassabc> ijtbinjclassabcs,
			Set<Ijtbinjconfig> ijtbinjconfigs,
			Set<Exportacao004> exportacao004s,
			Set<Ijtbinjctrliniproc> ijtbinjctrliniprocs,
			Set<Ijtbinjlinhamontag> ijtbinjlinhamontags,
			Set<Ijtbinjbloq> ijtbinjbloqs, Set<Ijtbinjcfgerp> ijtbinjcfgerps,
			Set<Ijtbinjandonprcsft> ijtbinjandonprcsfts,
			Set<Ijtbinjauxdrvcelc> ijtbinjauxdrvcelcs,
			Set<Ijregultocorop> ijregultocorops,
			Set<Ijregultocorinj> ijregultocorinjs, Set<Ijrefman> ijrefmans,
			Set<Ijrefextra> ijrefextras, Set<Ijtbinjalerta> ijtbinjalertas,
			Set<Ijtbdnc> ijtbdncs, Set<Ijsitipe> ijsitipes,
			Set<Ijtbinjstatus> ijtbinjstatuses, Set<Ijreapar> ijreapars,
			Set<Ijreapeso> ijreapesos, Set<Ijrearea> ijreareas,
			Set<Ijqldprodinsplote> ijqldprodinsplotes,
			Set<Ijqldinspecao> ijqldinspecaos, Set<Ijreacic> ijreacics,
			Set<Ijqldsupervisor> ijqldsupervisors, Set<Ijreacnc> ijreacncs,
			Set<Ijreacicop> ijreacicops, Set<Ijreamovsemprog> ijreamovsemprogs,
			Set<Ijreainspprod> ijreainspprods, Set<Ijpropeso> ijpropesos,
			Set<Ijproqtope> ijproqtopes, Set<Ijplanop> ijplanops,
			Set<Ijparprog> ijparprogs, Set<Ijoproteiro> ijoproteiros,
			Set<Ijopproqtope> ijopproqtopes, Set<Ijoplotes> ijoploteses,
			Set<Ijop> ijops, Set<Ijocorvarritmo> ijocorvarritmos,
			Set<Ijocorreploteins> ijocorreploteinses,
			Set<Ijmovpostos> ijmovpostoses, Set<Ijmdoaloc> ijmdoalocs,
			Set<Ijctrlturnoint> ijctrlturnoints,
			Set<Ijengleituraciclos> ijengleituracicloses,
			Set<Ijenglogciclos> ijenglogcicloses,
			Set<Ijctrlultturmaq> ijctrlultturmaqs, Set<Ijdeparamaq> ijdeparamaqs) {
		this.cdinjetora = cdinjetora;
		this.ijtbpar = ijtbpar;
		this.ijtbfab = ijtbfab;
		this.ijtbset = ijtbset;
		this.opatual = opatual;
		this.cdidentific = cdidentific;
		this.tonelagem = tonelagem;
		this.marca = marca;
		this.modelo = modelo;
		this.dtcompra = dtcompra;
		this.dtinstalacao = dtinstalacao;
		this.dtfgarantia = dtfgarantia;
		this.dtsaida = dtsaida;
		this.paraonde = paraonde;
		this.stinjetora = stinjetora;
		this.stfuncionamento = stfuncionamento;
		this.maquinaemalerta = maquinaemalerta;
		this.aguardandomolde = aguardandomolde;
		this.dthriparada = dthriparada;
		this.dthrfparada = dthrfparada;
		this.cdmestre = cdmestre;
		this.cdcoletor = cdcoletor;
		this.contadoracesso = contadoracesso;
		this.atualizartabparada = atualizartabparada;
		this.atualizartabrefugo = atualizartabrefugo;
		this.atualizartabmolde = atualizartabmolde;
		this.atualizartabcausas = atualizartabcausas;
		this.atualizartabacoes = atualizartabacoes;
		this.atualizartabjustif = atualizartabjustif;
		this.atualizartabalerta = atualizartabalerta;
		this.atualizartabtecnic = atualizartabtecnic;
		this.atualizaconfigsys = atualizaconfigsys;
		this.hrtrabalhadas = hrtrabalhadas;
		this.hrparamanutencao = hrparamanutencao;
		this.hrconttrab = hrconttrab;
		this.vaolivrehor = vaolivrehor;
		this.vaolivrever = vaolivrever;
		this.capacidadeinjecao = capacidadeinjecao;
		this.altmin = altmin;
		this.altmax = altmax;
		this.txhora = txhora;
		this.tipomaquina = tipomaquina;
		this.coletaautomatica = coletaautomatica;
		this.fatortickrelogio = fatortickrelogio;
		this.precisaocompact = precisaocompact;
		this.alertainspqld = alertainspqld;
		this.freqmanutprev = freqmanutprev;
		this.qthorastrabalhadas = qthorastrabalhadas;
		this.stultinspqld = stultinspqld;
		this.metaoee = metaoee;
		this.cdmoldeatual = cdmoldeatual;
		this.cdestruturaatual = cdestruturaatual;
		this.tpicone = tpicone;
		this.tpabertsessaoprod = tpabertsessaoprod;
		this.procmultiferr = procmultiferr;
		this.cdsubcoletor = cdsubcoletor;
		this.cdinjestendido = cdinjestendido;
		this.ijhorexcs = ijhorexcs;
		this.ijinspecaos = ijinspecaos;
		this.ijiniopinjs = ijiniopinjs;
		this.ijlogcorrpars = ijlogcorrpars;
		this.ijkanbanlotes = ijkanbanlotes;
		this.ijloginjs = ijloginjs;
		this.ijlogcorrreqs = ijlogcorrreqs;
		this.ijlogopemaqs = ijlogopemaqs;
		this.ijlogipesemconexaos = ijlogipesemconexaos;
		this.ijgrpinjpars = ijgrpinjpars;
		this.ijgrpinjrefs = ijgrpinjrefs;
		this.ijgalobjs = ijgalobjs;
		this.ijfictecconfigs = ijfictecconfigs;
		this.ijfictecs = ijfictecs;
		this.ijficinjs = ijficinjs;
		this.ijgrpdetinjs = ijgrpdetinjs;
		this.ijgrpdetestprocs = ijgrpdetestprocs;
		this.ijgalobjmtrzsForCdinjetora = ijgalobjmtrzsForCdinjetora;
		this.ijgalobjmtrzsForCdposto = ijgalobjmtrzsForCdposto;
		this.ijficcncs = ijficcncs;
		this.ijentsaiopmaqs = ijentsaiopmaqs;
		this.ijfamiliaxmaqs = ijfamiliaxmaqs;
		this.ijcfgandmaqevts = ijcfgandmaqevts;
		this.ijcomequipamentos = ijcomequipamentos;
		this.ijcncturnos = ijcncturnos;
		this.ijctrlresultinsps = ijctrlresultinsps;
		this.ijctrlresnegqld2s = ijctrlresnegqld2s;
		this.ijinjctrlultparmons = ijinjctrlultparmons;
		this.ijmatrizsetups = ijmatrizsetups;
		this.ijinjcfgmetamonits = ijinjcfgmetamonits;
		this.ijctrliniprocs = ijctrliniprocs;
		this.ijctrlalertaandons = ijctrlalertaandons;
		this.ijtbinjqldctrls = ijtbinjqldctrls;
		this.ijctrlresnegqld1s = ijctrlresnegqld1s;
		this.ijctrliniproctemps = ijctrliniproctemps;
		this.ijversaoproducaos = ijversaoproducaos;
		this.ijtmpsetups = ijtmpsetups;
		this.ijtmpultsts = ijtmpultsts;
		this.ijtbmols = ijtbmols;
		this.ijtbslidesxmaqs = ijtbslidesxmaqs;
		this.ijacumpars = ijacumpars;
		this.exportacao006s = exportacao006s;
		this.ijtbinjtpcoletors = ijtbinjtpcoletors;
		this.ijcentrocustoxmaqs = ijcentrocustoxmaqs;
		this.ijcelxmaqsForCdmaqdestino = ijcelxmaqsForCdmaqdestino;
		this.ijtbinjsincparprogs = ijtbinjsincparprogs;
		this.ijtbinjultops = ijtbinjultops;
		this.ijcelxmaqsForCdinjetora = ijcelxmaqsForCdinjetora;
		this.ijtbinjtpprocs = ijtbinjtpprocs;
		this.ijbroneinjapts = ijbroneinjapts;
		this.ijalertasautos = ijalertasautos;
		this.ijaleinjs = ijaleinjs;
		this.ijacumrefs = ijacumrefs;
		this.ijtbinjplannings = ijtbinjplannings;
		this.ijacumprods = ijacumprods;
		this.ijtbinjmodinsps = ijtbinjmodinsps;
		this.ijtbinjopers = ijtbinjopers;
		this.ijtbinjclassabcs = ijtbinjclassabcs;
		this.ijtbinjconfigs = ijtbinjconfigs;
		this.exportacao004s = exportacao004s;
		this.ijtbinjctrliniprocs = ijtbinjctrliniprocs;
		this.ijtbinjlinhamontags = ijtbinjlinhamontags;
		this.ijtbinjbloqs = ijtbinjbloqs;
		this.ijtbinjcfgerps = ijtbinjcfgerps;
		this.ijtbinjandonprcsfts = ijtbinjandonprcsfts;
		this.ijtbinjauxdrvcelcs = ijtbinjauxdrvcelcs;
		this.ijregultocorops = ijregultocorops;
		this.ijregultocorinjs = ijregultocorinjs;
		this.ijrefmans = ijrefmans;
		this.ijrefextras = ijrefextras;
		this.ijtbinjalertas = ijtbinjalertas;
		this.ijtbdncs = ijtbdncs;
		this.ijsitipes = ijsitipes;
		this.ijtbinjstatuses = ijtbinjstatuses;
		this.ijreapars = ijreapars;
		this.ijreapesos = ijreapesos;
		this.ijreareas = ijreareas;
		this.ijqldprodinsplotes = ijqldprodinsplotes;
		this.ijqldinspecaos = ijqldinspecaos;
		this.ijreacics = ijreacics;
		this.ijqldsupervisors = ijqldsupervisors;
		this.ijreacncs = ijreacncs;
		this.ijreacicops = ijreacicops;
		this.ijreamovsemprogs = ijreamovsemprogs;
		this.ijreainspprods = ijreainspprods;
		this.ijpropesos = ijpropesos;
		this.ijproqtopes = ijproqtopes;
		this.ijplanops = ijplanops;
		this.ijparprogs = ijparprogs;
		this.ijoproteiros = ijoproteiros;
		this.ijopproqtopes = ijopproqtopes;
		this.ijoploteses = ijoploteses;
		this.ijops = ijops;
		this.ijocorvarritmos = ijocorvarritmos;
		this.ijocorreploteinses = ijocorreploteinses;
		this.ijmovpostoses = ijmovpostoses;
		this.ijmdoalocs = ijmdoalocs;
		this.ijctrlturnoints = ijctrlturnoints;
		this.ijengleituracicloses = ijengleituracicloses;
		this.ijenglogcicloses = ijenglogcicloses;
		this.ijctrlultturmaqs = ijctrlultturmaqs;
		this.ijdeparamaqs = ijdeparamaqs;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPARADA")
	public Ijtbpar getIjtbpar() {
		return this.ijtbpar;
	}

	public void setIjtbpar(Ijtbpar ijtbpar) {
		this.ijtbpar = ijtbpar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDFABRICANTE", nullable = false)
	public Ijtbfab getIjtbfab() {
		return this.ijtbfab;
	}

	public void setIjtbfab(Ijtbfab ijtbfab) {
		this.ijtbfab = ijtbfab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDSETOR")
	public Ijtbset getIjtbset() {
		return this.ijtbset;
	}

	public void setIjtbset(Ijtbset ijtbset) {
		this.ijtbset = ijtbset;
	}

	@Column(name = "OPATUAL", length = 10)
	public String getOpatual() {
		return this.opatual;
	}

	public void setOpatual(String opatual) {
		this.opatual = opatual;
	}

	@Column(name = "CDIDENTIFIC", length = 10)
	public String getCdidentific() {
		return this.cdidentific;
	}

	public void setCdidentific(String cdidentific) {
		this.cdidentific = cdidentific;
	}

	@Column(name = "TONELAGEM", length = 10)
	public String getTonelagem() {
		return this.tonelagem;
	}

	public void setTonelagem(String tonelagem) {
		this.tonelagem = tonelagem;
	}

	@Column(name = "MARCA", length = 20)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "MODELO", length = 20)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTCOMPRA", length = 7)
	public Date getDtcompra() {
		return this.dtcompra;
	}

	public void setDtcompra(Date dtcompra) {
		this.dtcompra = dtcompra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINSTALACAO", length = 7)
	public Date getDtinstalacao() {
		return this.dtinstalacao;
	}

	public void setDtinstalacao(Date dtinstalacao) {
		this.dtinstalacao = dtinstalacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTFGARANTIA", length = 7)
	public Date getDtfgarantia() {
		return this.dtfgarantia;
	}

	public void setDtfgarantia(Date dtfgarantia) {
		this.dtfgarantia = dtfgarantia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTSAIDA", length = 7)
	public Date getDtsaida() {
		return this.dtsaida;
	}

	public void setDtsaida(Date dtsaida) {
		this.dtsaida = dtsaida;
	}

	@Column(name = "PARAONDE", length = 30)
	public String getParaonde() {
		return this.paraonde;
	}

	public void setParaonde(String paraonde) {
		this.paraonde = paraonde;
	}

	@Column(name = "STINJETORA")
	public Integer getStinjetora() {
		return this.stinjetora;
	}

	public void setStinjetora(Integer stinjetora) {
		this.stinjetora = stinjetora;
	}

	@Column(name = "STFUNCIONAMENTO", length = 1)
	public String getStfuncionamento() {
		return this.stfuncionamento;
	}

	public void setStfuncionamento(String stfuncionamento) {
		this.stfuncionamento = stfuncionamento;
	}

	@Column(name = "MAQUINAEMALERTA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getMaquinaemalerta() {
		return this.maquinaemalerta;
	}

	public void setMaquinaemalerta(BigDecimal maquinaemalerta) {
		this.maquinaemalerta = maquinaemalerta;
	}

	@Column(name = "AGUARDANDOMOLDE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAguardandomolde() {
		return this.aguardandomolde;
	}

	public void setAguardandomolde(BigDecimal aguardandomolde) {
		this.aguardandomolde = aguardandomolde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRIPARADA", length = 7)
	public Date getDthriparada() {
		return this.dthriparada;
	}

	public void setDthriparada(Date dthriparada) {
		this.dthriparada = dthriparada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRFPARADA", length = 7)
	public Date getDthrfparada() {
		return this.dthrfparada;
	}

	public void setDthrfparada(Date dthrfparada) {
		this.dthrfparada = dthrfparada;
	}

	@Column(name = "CDMESTRE", length = 6)
	public String getCdmestre() {
		return this.cdmestre;
	}

	public void setCdmestre(String cdmestre) {
		this.cdmestre = cdmestre;
	}

	@Column(name = "CDCOLETOR", length = 6)
	public String getCdcoletor() {
		return this.cdcoletor;
	}

	public void setCdcoletor(String cdcoletor) {
		this.cdcoletor = cdcoletor;
	}

	@Column(name = "CONTADORACESSO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getContadoracesso() {
		return this.contadoracesso;
	}

	public void setContadoracesso(BigDecimal contadoracesso) {
		this.contadoracesso = contadoracesso;
	}

	@Column(name = "ATUALIZARTABPARADA", precision = 22, scale = 0)
	public BigDecimal getAtualizartabparada() {
		return this.atualizartabparada;
	}

	public void setAtualizartabparada(BigDecimal atualizartabparada) {
		this.atualizartabparada = atualizartabparada;
	}

	@Column(name = "ATUALIZARTABREFUGO", precision = 22, scale = 0)
	public BigDecimal getAtualizartabrefugo() {
		return this.atualizartabrefugo;
	}

	public void setAtualizartabrefugo(BigDecimal atualizartabrefugo) {
		this.atualizartabrefugo = atualizartabrefugo;
	}

	@Column(name = "ATUALIZARTABMOLDE", precision = 22, scale = 0)
	public BigDecimal getAtualizartabmolde() {
		return this.atualizartabmolde;
	}

	public void setAtualizartabmolde(BigDecimal atualizartabmolde) {
		this.atualizartabmolde = atualizartabmolde;
	}

	@Column(name = "ATUALIZARTABCAUSAS", precision = 22, scale = 0)
	public BigDecimal getAtualizartabcausas() {
		return this.atualizartabcausas;
	}

	public void setAtualizartabcausas(BigDecimal atualizartabcausas) {
		this.atualizartabcausas = atualizartabcausas;
	}

	@Column(name = "ATUALIZARTABACOES", precision = 22, scale = 0)
	public BigDecimal getAtualizartabacoes() {
		return this.atualizartabacoes;
	}

	public void setAtualizartabacoes(BigDecimal atualizartabacoes) {
		this.atualizartabacoes = atualizartabacoes;
	}

	@Column(name = "ATUALIZARTABJUSTIF", precision = 22, scale = 0)
	public BigDecimal getAtualizartabjustif() {
		return this.atualizartabjustif;
	}

	public void setAtualizartabjustif(BigDecimal atualizartabjustif) {
		this.atualizartabjustif = atualizartabjustif;
	}

	@Column(name = "ATUALIZARTABALERTA", precision = 22, scale = 0)
	public BigDecimal getAtualizartabalerta() {
		return this.atualizartabalerta;
	}

	public void setAtualizartabalerta(BigDecimal atualizartabalerta) {
		this.atualizartabalerta = atualizartabalerta;
	}

	@Column(name = "ATUALIZARTABTECNIC", precision = 22, scale = 0)
	public BigDecimal getAtualizartabtecnic() {
		return this.atualizartabtecnic;
	}

	public void setAtualizartabtecnic(BigDecimal atualizartabtecnic) {
		this.atualizartabtecnic = atualizartabtecnic;
	}

	@Column(name = "ATUALIZACONFIGSYS", precision = 22, scale = 0)
	public BigDecimal getAtualizaconfigsys() {
		return this.atualizaconfigsys;
	}

	public void setAtualizaconfigsys(BigDecimal atualizaconfigsys) {
		this.atualizaconfigsys = atualizaconfigsys;
	}

	@Column(name = "HRTRABALHADAS", precision = 126, scale = 0)
	public Double getHrtrabalhadas() {
		return this.hrtrabalhadas;
	}

	public void setHrtrabalhadas(Double hrtrabalhadas) {
		this.hrtrabalhadas = hrtrabalhadas;
	}

	@Column(name = "HRPARAMANUTENCAO", precision = 126, scale = 0)
	public Double getHrparamanutencao() {
		return this.hrparamanutencao;
	}

	public void setHrparamanutencao(Double hrparamanutencao) {
		this.hrparamanutencao = hrparamanutencao;
	}

	@Column(name = "HRCONTTRAB", precision = 126, scale = 0)
	public Double getHrconttrab() {
		return this.hrconttrab;
	}

	public void setHrconttrab(Double hrconttrab) {
		this.hrconttrab = hrconttrab;
	}

	@Column(name = "VAOLIVREHOR", precision = 126, scale = 0)
	public Double getVaolivrehor() {
		return this.vaolivrehor;
	}

	public void setVaolivrehor(Double vaolivrehor) {
		this.vaolivrehor = vaolivrehor;
	}

	@Column(name = "VAOLIVREVER", precision = 126, scale = 0)
	public Double getVaolivrever() {
		return this.vaolivrever;
	}

	public void setVaolivrever(Double vaolivrever) {
		this.vaolivrever = vaolivrever;
	}

	@Column(name = "CAPACIDADEINJECAO", precision = 126, scale = 0)
	public Double getCapacidadeinjecao() {
		return this.capacidadeinjecao;
	}

	public void setCapacidadeinjecao(Double capacidadeinjecao) {
		this.capacidadeinjecao = capacidadeinjecao;
	}

	@Column(name = "ALTMIN", precision = 126, scale = 0)
	public Double getAltmin() {
		return this.altmin;
	}

	public void setAltmin(Double altmin) {
		this.altmin = altmin;
	}

	@Column(name = "ALTMAX", precision = 126, scale = 0)
	public Double getAltmax() {
		return this.altmax;
	}

	public void setAltmax(Double altmax) {
		this.altmax = altmax;
	}

	@Column(name = "TXHORA", precision = 126, scale = 0)
	public Double getTxhora() {
		return this.txhora;
	}

	public void setTxhora(Double txhora) {
		this.txhora = txhora;
	}

	@Column(name = "TIPOMAQUINA", precision = 22, scale = 0)
	public BigDecimal getTipomaquina() {
		return this.tipomaquina;
	}

	public void setTipomaquina(BigDecimal tipomaquina) {
		this.tipomaquina = tipomaquina;
	}

	@Column(name = "COLETAAUTOMATICA", precision = 22, scale = 0)
	public BigDecimal getColetaautomatica() {
		return this.coletaautomatica;
	}

	public void setColetaautomatica(BigDecimal coletaautomatica) {
		this.coletaautomatica = coletaautomatica;
	}

	@Column(name = "FATORTICKRELOGIO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getFatortickrelogio() {
		return this.fatortickrelogio;
	}

	public void setFatortickrelogio(BigDecimal fatortickrelogio) {
		this.fatortickrelogio = fatortickrelogio;
	}

	@Column(name = "PRECISAOCOMPACT", precision = 126, scale = 0)
	public Double getPrecisaocompact() {
		return this.precisaocompact;
	}

	public void setPrecisaocompact(Double precisaocompact) {
		this.precisaocompact = precisaocompact;
	}

	@Column(name = "ALERTAINSPQLD", length = 1)
	public Character getAlertainspqld() {
		return this.alertainspqld;
	}

	public void setAlertainspqld(Character alertainspqld) {
		this.alertainspqld = alertainspqld;
	}

	@Column(name = "FREQMANUTPREV", precision = 126, scale = 0)
	public Double getFreqmanutprev() {
		return this.freqmanutprev;
	}

	public void setFreqmanutprev(Double freqmanutprev) {
		this.freqmanutprev = freqmanutprev;
	}

	@Column(name = "QTHORASTRABALHADAS", precision = 126, scale = 0)
	public Double getQthorastrabalhadas() {
		return this.qthorastrabalhadas;
	}

	public void setQthorastrabalhadas(Double qthorastrabalhadas) {
		this.qthorastrabalhadas = qthorastrabalhadas;
	}

	@Column(name = "STULTINSPQLD", length = 1)
	public Character getStultinspqld() {
		return this.stultinspqld;
	}

	public void setStultinspqld(Character stultinspqld) {
		this.stultinspqld = stultinspqld;
	}

	@Column(name = "METAOEE", precision = 126, scale = 0)
	public Double getMetaoee() {
		return this.metaoee;
	}

	public void setMetaoee(Double metaoee) {
		this.metaoee = metaoee;
	}

	@Column(name = "CDMOLDEATUAL", length = 6)
	public String getCdmoldeatual() {
		return this.cdmoldeatual;
	}

	public void setCdmoldeatual(String cdmoldeatual) {
		this.cdmoldeatual = cdmoldeatual;
	}

	@Column(name = "CDESTRUTURAATUAL", length = 4)
	public String getCdestruturaatual() {
		return this.cdestruturaatual;
	}

	public void setCdestruturaatual(String cdestruturaatual) {
		this.cdestruturaatual = cdestruturaatual;
	}

	@Column(name = "TPICONE", length = 20)
	public String getTpicone() {
		return this.tpicone;
	}

	public void setTpicone(String tpicone) {
		this.tpicone = tpicone;
	}

	@Column(name = "TPABERTSESSAOPROD", length = 1)
	public Character getTpabertsessaoprod() {
		return this.tpabertsessaoprod;
	}

	public void setTpabertsessaoprod(Character tpabertsessaoprod) {
		this.tpabertsessaoprod = tpabertsessaoprod;
	}

	@Column(name = "PROCMULTIFERR", length = 1)
	public Character getProcmultiferr() {
		return this.procmultiferr;
	}

	public void setProcmultiferr(Character procmultiferr) {
		this.procmultiferr = procmultiferr;
	}

	@Column(name = "CDSUBCOLETOR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCdsubcoletor() {
		return this.cdsubcoletor;
	}

	public void setCdsubcoletor(BigDecimal cdsubcoletor) {
		this.cdsubcoletor = cdsubcoletor;
	}

	@Column(name = "CDINJESTENDIDO", unique = true, nullable = false, length = 8)
	public String getCdinjestendido() {
		return this.cdinjestendido;
	}

	public void setCdinjestendido(String cdinjestendido) {
		this.cdinjestendido = cdinjestendido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijhorexc> getIjhorexcs() {
		return this.ijhorexcs;
	}

	public void setIjhorexcs(Set<Ijhorexc> ijhorexcs) {
		this.ijhorexcs = ijhorexcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijinspecao> getIjinspecaos() {
		return this.ijinspecaos;
	}

	public void setIjinspecaos(Set<Ijinspecao> ijinspecaos) {
		this.ijinspecaos = ijinspecaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijiniopinj> getIjiniopinjs() {
		return this.ijiniopinjs;
	}

	public void setIjiniopinjs(Set<Ijiniopinj> ijiniopinjs) {
		this.ijiniopinjs = ijiniopinjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijlogcorrpar> getIjlogcorrpars() {
		return this.ijlogcorrpars;
	}

	public void setIjlogcorrpars(Set<Ijlogcorrpar> ijlogcorrpars) {
		this.ijlogcorrpars = ijlogcorrpars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijkanbanlote> getIjkanbanlotes() {
		return this.ijkanbanlotes;
	}

	public void setIjkanbanlotes(Set<Ijkanbanlote> ijkanbanlotes) {
		this.ijkanbanlotes = ijkanbanlotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijloginj> getIjloginjs() {
		return this.ijloginjs;
	}

	public void setIjloginjs(Set<Ijloginj> ijloginjs) {
		this.ijloginjs = ijloginjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijlogcorrreq> getIjlogcorrreqs() {
		return this.ijlogcorrreqs;
	}

	public void setIjlogcorrreqs(Set<Ijlogcorrreq> ijlogcorrreqs) {
		this.ijlogcorrreqs = ijlogcorrreqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijlogopemaq> getIjlogopemaqs() {
		return this.ijlogopemaqs;
	}

	public void setIjlogopemaqs(Set<Ijlogopemaq> ijlogopemaqs) {
		this.ijlogopemaqs = ijlogopemaqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijlogipesemconexao> getIjlogipesemconexaos() {
		return this.ijlogipesemconexaos;
	}

	public void setIjlogipesemconexaos(
			Set<Ijlogipesemconexao> ijlogipesemconexaos) {
		this.ijlogipesemconexaos = ijlogipesemconexaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijgrpinjpar> getIjgrpinjpars() {
		return this.ijgrpinjpars;
	}

	public void setIjgrpinjpars(Set<Ijgrpinjpar> ijgrpinjpars) {
		this.ijgrpinjpars = ijgrpinjpars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijgrpinjref> getIjgrpinjrefs() {
		return this.ijgrpinjrefs;
	}

	public void setIjgrpinjrefs(Set<Ijgrpinjref> ijgrpinjrefs) {
		this.ijgrpinjrefs = ijgrpinjrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijgalobj> getIjgalobjs() {
		return this.ijgalobjs;
	}

	public void setIjgalobjs(Set<Ijgalobj> ijgalobjs) {
		this.ijgalobjs = ijgalobjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijfictecconfig> getIjfictecconfigs() {
		return this.ijfictecconfigs;
	}

	public void setIjfictecconfigs(Set<Ijfictecconfig> ijfictecconfigs) {
		this.ijfictecconfigs = ijfictecconfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijfictec> getIjfictecs() {
		return this.ijfictecs;
	}

	public void setIjfictecs(Set<Ijfictec> ijfictecs) {
		this.ijfictecs = ijfictecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijficinj> getIjficinjs() {
		return this.ijficinjs;
	}

	public void setIjficinjs(Set<Ijficinj> ijficinjs) {
		this.ijficinjs = ijficinjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijgrpdetinj> getIjgrpdetinjs() {
		return this.ijgrpdetinjs;
	}

	public void setIjgrpdetinjs(Set<Ijgrpdetinj> ijgrpdetinjs) {
		this.ijgrpdetinjs = ijgrpdetinjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijgrpdetestproc> getIjgrpdetestprocs() {
		return this.ijgrpdetestprocs;
	}

	public void setIjgrpdetestprocs(Set<Ijgrpdetestproc> ijgrpdetestprocs) {
		this.ijgrpdetestprocs = ijgrpdetestprocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinjByCdinjetora")
	public Set<Ijgalobjmtrz> getIjgalobjmtrzsForCdinjetora() {
		return this.ijgalobjmtrzsForCdinjetora;
	}

	public void setIjgalobjmtrzsForCdinjetora(
			Set<Ijgalobjmtrz> ijgalobjmtrzsForCdinjetora) {
		this.ijgalobjmtrzsForCdinjetora = ijgalobjmtrzsForCdinjetora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinjByCdposto")
	public Set<Ijgalobjmtrz> getIjgalobjmtrzsForCdposto() {
		return this.ijgalobjmtrzsForCdposto;
	}

	public void setIjgalobjmtrzsForCdposto(
			Set<Ijgalobjmtrz> ijgalobjmtrzsForCdposto) {
		this.ijgalobjmtrzsForCdposto = ijgalobjmtrzsForCdposto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijficcnc> getIjficcncs() {
		return this.ijficcncs;
	}

	public void setIjficcncs(Set<Ijficcnc> ijficcncs) {
		this.ijficcncs = ijficcncs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijentsaiopmaq> getIjentsaiopmaqs() {
		return this.ijentsaiopmaqs;
	}

	public void setIjentsaiopmaqs(Set<Ijentsaiopmaq> ijentsaiopmaqs) {
		this.ijentsaiopmaqs = ijentsaiopmaqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijfamiliaxmaq> getIjfamiliaxmaqs() {
		return this.ijfamiliaxmaqs;
	}

	public void setIjfamiliaxmaqs(Set<Ijfamiliaxmaq> ijfamiliaxmaqs) {
		this.ijfamiliaxmaqs = ijfamiliaxmaqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijcfgandmaqevt> getIjcfgandmaqevts() {
		return this.ijcfgandmaqevts;
	}

	public void setIjcfgandmaqevts(Set<Ijcfgandmaqevt> ijcfgandmaqevts) {
		this.ijcfgandmaqevts = ijcfgandmaqevts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijcomequipamento> getIjcomequipamentos() {
		return this.ijcomequipamentos;
	}

	public void setIjcomequipamentos(Set<Ijcomequipamento> ijcomequipamentos) {
		this.ijcomequipamentos = ijcomequipamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijcncturno> getIjcncturnos() {
		return this.ijcncturnos;
	}

	public void setIjcncturnos(Set<Ijcncturno> ijcncturnos) {
		this.ijcncturnos = ijcncturnos;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijctrlresultinsp> getIjctrlresultinsps() {
		return this.ijctrlresultinsps;
	}

	public void setIjctrlresultinsps(Set<Ijctrlresultinsp> ijctrlresultinsps) {
		this.ijctrlresultinsps = ijctrlresultinsps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijctrlresnegqld2> getIjctrlresnegqld2s() {
		return this.ijctrlresnegqld2s;
	}

	public void setIjctrlresnegqld2s(Set<Ijctrlresnegqld2> ijctrlresnegqld2s) {
		this.ijctrlresnegqld2s = ijctrlresnegqld2s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijinjctrlultparmon> getIjinjctrlultparmons() {
		return this.ijinjctrlultparmons;
	}

	public void setIjinjctrlultparmons(
			Set<Ijinjctrlultparmon> ijinjctrlultparmons) {
		this.ijinjctrlultparmons = ijinjctrlultparmons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijmatrizsetup> getIjmatrizsetups() {
		return this.ijmatrizsetups;
	}

	public void setIjmatrizsetups(Set<Ijmatrizsetup> ijmatrizsetups) {
		this.ijmatrizsetups = ijmatrizsetups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijinjcfgmetamonit> getIjinjcfgmetamonits() {
		return this.ijinjcfgmetamonits;
	}

	public void setIjinjcfgmetamonits(Set<Ijinjcfgmetamonit> ijinjcfgmetamonits) {
		this.ijinjcfgmetamonits = ijinjcfgmetamonits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijctrliniproc> getIjctrliniprocs() {
		return this.ijctrliniprocs;
	}

	public void setIjctrliniprocs(Set<Ijctrliniproc> ijctrliniprocs) {
		this.ijctrliniprocs = ijctrliniprocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijctrlalertaandon> getIjctrlalertaandons() {
		return this.ijctrlalertaandons;
	}

	public void setIjctrlalertaandons(Set<Ijctrlalertaandon> ijctrlalertaandons) {
		this.ijctrlalertaandons = ijctrlalertaandons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjqldctrl> getIjtbinjqldctrls() {
		return this.ijtbinjqldctrls;
	}

	public void setIjtbinjqldctrls(Set<Ijtbinjqldctrl> ijtbinjqldctrls) {
		this.ijtbinjqldctrls = ijtbinjqldctrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijctrlresnegqld1> getIjctrlresnegqld1s() {
		return this.ijctrlresnegqld1s;
	}

	public void setIjctrlresnegqld1s(Set<Ijctrlresnegqld1> ijctrlresnegqld1s) {
		this.ijctrlresnegqld1s = ijctrlresnegqld1s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijctrliniproctemp> getIjctrliniproctemps() {
		return this.ijctrliniproctemps;
	}

	public void setIjctrliniproctemps(Set<Ijctrliniproctemp> ijctrliniproctemps) {
		this.ijctrliniproctemps = ijctrliniproctemps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijversaoproducao> getIjversaoproducaos() {
		return this.ijversaoproducaos;
	}

	public void setIjversaoproducaos(Set<Ijversaoproducao> ijversaoproducaos) {
		this.ijversaoproducaos = ijversaoproducaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtmpsetup> getIjtmpsetups() {
		return this.ijtmpsetups;
	}

	public void setIjtmpsetups(Set<Ijtmpsetup> ijtmpsetups) {
		this.ijtmpsetups = ijtmpsetups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtmpultst> getIjtmpultsts() {
		return this.ijtmpultsts;
	}

	public void setIjtmpultsts(Set<Ijtmpultst> ijtmpultsts) {
		this.ijtmpultsts = ijtmpultsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbmol> getIjtbmols() {
		return this.ijtbmols;
	}

	public void setIjtbmols(Set<Ijtbmol> ijtbmols) {
		this.ijtbmols = ijtbmols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbslidesxmaq> getIjtbslidesxmaqs() {
		return this.ijtbslidesxmaqs;
	}

	public void setIjtbslidesxmaqs(Set<Ijtbslidesxmaq> ijtbslidesxmaqs) {
		this.ijtbslidesxmaqs = ijtbslidesxmaqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijacumpar> getIjacumpars() {
		return this.ijacumpars;
	}

	public void setIjacumpars(Set<Ijacumpar> ijacumpars) {
		this.ijacumpars = ijacumpars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Exportacao006> getExportacao006s() {
		return this.exportacao006s;
	}

	public void setExportacao006s(Set<Exportacao006> exportacao006s) {
		this.exportacao006s = exportacao006s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjtpcoletor> getIjtbinjtpcoletors() {
		return this.ijtbinjtpcoletors;
	}

	public void setIjtbinjtpcoletors(Set<Ijtbinjtpcoletor> ijtbinjtpcoletors) {
		this.ijtbinjtpcoletors = ijtbinjtpcoletors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijcentrocustoxmaq> getIjcentrocustoxmaqs() {
		return this.ijcentrocustoxmaqs;
	}

	public void setIjcentrocustoxmaqs(Set<Ijcentrocustoxmaq> ijcentrocustoxmaqs) {
		this.ijcentrocustoxmaqs = ijcentrocustoxmaqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinjByCdmaqdestino")
	public Set<Ijcelxmaq> getIjcelxmaqsForCdmaqdestino() {
		return this.ijcelxmaqsForCdmaqdestino;
	}

	public void setIjcelxmaqsForCdmaqdestino(
			Set<Ijcelxmaq> ijcelxmaqsForCdmaqdestino) {
		this.ijcelxmaqsForCdmaqdestino = ijcelxmaqsForCdmaqdestino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjsincparprog> getIjtbinjsincparprogs() {
		return this.ijtbinjsincparprogs;
	}

	public void setIjtbinjsincparprogs(
			Set<Ijtbinjsincparprog> ijtbinjsincparprogs) {
		this.ijtbinjsincparprogs = ijtbinjsincparprogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjultop> getIjtbinjultops() {
		return this.ijtbinjultops;
	}

	public void setIjtbinjultops(Set<Ijtbinjultop> ijtbinjultops) {
		this.ijtbinjultops = ijtbinjultops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinjByCdinjetora")
	public Set<Ijcelxmaq> getIjcelxmaqsForCdinjetora() {
		return this.ijcelxmaqsForCdinjetora;
	}

	public void setIjcelxmaqsForCdinjetora(
			Set<Ijcelxmaq> ijcelxmaqsForCdinjetora) {
		this.ijcelxmaqsForCdinjetora = ijcelxmaqsForCdinjetora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjtpproc> getIjtbinjtpprocs() {
		return this.ijtbinjtpprocs;
	}

	public void setIjtbinjtpprocs(Set<Ijtbinjtpproc> ijtbinjtpprocs) {
		this.ijtbinjtpprocs = ijtbinjtpprocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijbroneinjapt> getIjbroneinjapts() {
		return this.ijbroneinjapts;
	}

	public void setIjbroneinjapts(Set<Ijbroneinjapt> ijbroneinjapts) {
		this.ijbroneinjapts = ijbroneinjapts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijalertasauto> getIjalertasautos() {
		return this.ijalertasautos;
	}

	public void setIjalertasautos(Set<Ijalertasauto> ijalertasautos) {
		this.ijalertasautos = ijalertasautos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijaleinj> getIjaleinjs() {
		return this.ijaleinjs;
	}

	public void setIjaleinjs(Set<Ijaleinj> ijaleinjs) {
		this.ijaleinjs = ijaleinjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijacumref> getIjacumrefs() {
		return this.ijacumrefs;
	}

	public void setIjacumrefs(Set<Ijacumref> ijacumrefs) {
		this.ijacumrefs = ijacumrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjplanning> getIjtbinjplannings() {
		return this.ijtbinjplannings;
	}

	public void setIjtbinjplannings(Set<Ijtbinjplanning> ijtbinjplannings) {
		this.ijtbinjplannings = ijtbinjplannings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijacumprod> getIjacumprods() {
		return this.ijacumprods;
	}

	public void setIjacumprods(Set<Ijacumprod> ijacumprods) {
		this.ijacumprods = ijacumprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjmodinsp> getIjtbinjmodinsps() {
		return this.ijtbinjmodinsps;
	}

	public void setIjtbinjmodinsps(Set<Ijtbinjmodinsp> ijtbinjmodinsps) {
		this.ijtbinjmodinsps = ijtbinjmodinsps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjoper> getIjtbinjopers() {
		return this.ijtbinjopers;
	}

	public void setIjtbinjopers(Set<Ijtbinjoper> ijtbinjopers) {
		this.ijtbinjopers = ijtbinjopers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjclassabc> getIjtbinjclassabcs() {
		return this.ijtbinjclassabcs;
	}

	public void setIjtbinjclassabcs(Set<Ijtbinjclassabc> ijtbinjclassabcs) {
		this.ijtbinjclassabcs = ijtbinjclassabcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjconfig> getIjtbinjconfigs() {
		return this.ijtbinjconfigs;
	}

	public void setIjtbinjconfigs(Set<Ijtbinjconfig> ijtbinjconfigs) {
		this.ijtbinjconfigs = ijtbinjconfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Exportacao004> getExportacao004s() {
		return this.exportacao004s;
	}

	public void setExportacao004s(Set<Exportacao004> exportacao004s) {
		this.exportacao004s = exportacao004s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjctrliniproc> getIjtbinjctrliniprocs() {
		return this.ijtbinjctrliniprocs;
	}

	public void setIjtbinjctrliniprocs(
			Set<Ijtbinjctrliniproc> ijtbinjctrliniprocs) {
		this.ijtbinjctrliniprocs = ijtbinjctrliniprocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjlinhamontag> getIjtbinjlinhamontags() {
		return this.ijtbinjlinhamontags;
	}

	public void setIjtbinjlinhamontags(
			Set<Ijtbinjlinhamontag> ijtbinjlinhamontags) {
		this.ijtbinjlinhamontags = ijtbinjlinhamontags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjbloq> getIjtbinjbloqs() {
		return this.ijtbinjbloqs;
	}

	public void setIjtbinjbloqs(Set<Ijtbinjbloq> ijtbinjbloqs) {
		this.ijtbinjbloqs = ijtbinjbloqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjcfgerp> getIjtbinjcfgerps() {
		return this.ijtbinjcfgerps;
	}

	public void setIjtbinjcfgerps(Set<Ijtbinjcfgerp> ijtbinjcfgerps) {
		this.ijtbinjcfgerps = ijtbinjcfgerps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjandonprcsft> getIjtbinjandonprcsfts() {
		return this.ijtbinjandonprcsfts;
	}

	public void setIjtbinjandonprcsfts(
			Set<Ijtbinjandonprcsft> ijtbinjandonprcsfts) {
		this.ijtbinjandonprcsfts = ijtbinjandonprcsfts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjauxdrvcelc> getIjtbinjauxdrvcelcs() {
		return this.ijtbinjauxdrvcelcs;
	}

	public void setIjtbinjauxdrvcelcs(Set<Ijtbinjauxdrvcelc> ijtbinjauxdrvcelcs) {
		this.ijtbinjauxdrvcelcs = ijtbinjauxdrvcelcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijregultocorop> getIjregultocorops() {
		return this.ijregultocorops;
	}

	public void setIjregultocorops(Set<Ijregultocorop> ijregultocorops) {
		this.ijregultocorops = ijregultocorops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijregultocorinj> getIjregultocorinjs() {
		return this.ijregultocorinjs;
	}

	public void setIjregultocorinjs(Set<Ijregultocorinj> ijregultocorinjs) {
		this.ijregultocorinjs = ijregultocorinjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijrefman> getIjrefmans() {
		return this.ijrefmans;
	}

	public void setIjrefmans(Set<Ijrefman> ijrefmans) {
		this.ijrefmans = ijrefmans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijrefextra> getIjrefextras() {
		return this.ijrefextras;
	}

	public void setIjrefextras(Set<Ijrefextra> ijrefextras) {
		this.ijrefextras = ijrefextras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjalerta> getIjtbinjalertas() {
		return this.ijtbinjalertas;
	}

	public void setIjtbinjalertas(Set<Ijtbinjalerta> ijtbinjalertas) {
		this.ijtbinjalertas = ijtbinjalertas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbdnc> getIjtbdncs() {
		return this.ijtbdncs;
	}

	public void setIjtbdncs(Set<Ijtbdnc> ijtbdncs) {
		this.ijtbdncs = ijtbdncs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijsitipe> getIjsitipes() {
		return this.ijsitipes;
	}

	public void setIjsitipes(Set<Ijsitipe> ijsitipes) {
		this.ijsitipes = ijsitipes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijtbinjstatus> getIjtbinjstatuses() {
		return this.ijtbinjstatuses;
	}

	public void setIjtbinjstatuses(Set<Ijtbinjstatus> ijtbinjstatuses) {
		this.ijtbinjstatuses = ijtbinjstatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijreapar> getIjreapars() {
		return this.ijreapars;
	}

	public void setIjreapars(Set<Ijreapar> ijreapars) {
		this.ijreapars = ijreapars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijreapeso> getIjreapesos() {
		return this.ijreapesos;
	}

	public void setIjreapesos(Set<Ijreapeso> ijreapesos) {
		this.ijreapesos = ijreapesos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijrearea> getIjreareas() {
		return this.ijreareas;
	}

	public void setIjreareas(Set<Ijrearea> ijreareas) {
		this.ijreareas = ijreareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijqldprodinsplote> getIjqldprodinsplotes() {
		return this.ijqldprodinsplotes;
	}

	public void setIjqldprodinsplotes(Set<Ijqldprodinsplote> ijqldprodinsplotes) {
		this.ijqldprodinsplotes = ijqldprodinsplotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijqldinspecao> getIjqldinspecaos() {
		return this.ijqldinspecaos;
	}

	public void setIjqldinspecaos(Set<Ijqldinspecao> ijqldinspecaos) {
		this.ijqldinspecaos = ijqldinspecaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijreacic> getIjreacics() {
		return this.ijreacics;
	}

	public void setIjreacics(Set<Ijreacic> ijreacics) {
		this.ijreacics = ijreacics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijqldsupervisor> getIjqldsupervisors() {
		return this.ijqldsupervisors;
	}

	public void setIjqldsupervisors(Set<Ijqldsupervisor> ijqldsupervisors) {
		this.ijqldsupervisors = ijqldsupervisors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijreacnc> getIjreacncs() {
		return this.ijreacncs;
	}

	public void setIjreacncs(Set<Ijreacnc> ijreacncs) {
		this.ijreacncs = ijreacncs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijreacicop> getIjreacicops() {
		return this.ijreacicops;
	}

	public void setIjreacicops(Set<Ijreacicop> ijreacicops) {
		this.ijreacicops = ijreacicops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijreamovsemprog> getIjreamovsemprogs() {
		return this.ijreamovsemprogs;
	}

	public void setIjreamovsemprogs(Set<Ijreamovsemprog> ijreamovsemprogs) {
		this.ijreamovsemprogs = ijreamovsemprogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijreainspprod> getIjreainspprods() {
		return this.ijreainspprods;
	}

	public void setIjreainspprods(Set<Ijreainspprod> ijreainspprods) {
		this.ijreainspprods = ijreainspprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijpropeso> getIjpropesos() {
		return this.ijpropesos;
	}

	public void setIjpropesos(Set<Ijpropeso> ijpropesos) {
		this.ijpropesos = ijpropesos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijproqtope> getIjproqtopes() {
		return this.ijproqtopes;
	}

	public void setIjproqtopes(Set<Ijproqtope> ijproqtopes) {
		this.ijproqtopes = ijproqtopes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijplanop> getIjplanops() {
		return this.ijplanops;
	}

	public void setIjplanops(Set<Ijplanop> ijplanops) {
		this.ijplanops = ijplanops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijparprog> getIjparprogs() {
		return this.ijparprogs;
	}

	public void setIjparprogs(Set<Ijparprog> ijparprogs) {
		this.ijparprogs = ijparprogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijoproteiro> getIjoproteiros() {
		return this.ijoproteiros;
	}

	public void setIjoproteiros(Set<Ijoproteiro> ijoproteiros) {
		this.ijoproteiros = ijoproteiros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijopproqtope> getIjopproqtopes() {
		return this.ijopproqtopes;
	}

	public void setIjopproqtopes(Set<Ijopproqtope> ijopproqtopes) {
		this.ijopproqtopes = ijopproqtopes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijoplotes> getIjoploteses() {
		return this.ijoploteses;
	}

	public void setIjoploteses(Set<Ijoplotes> ijoploteses) {
		this.ijoploteses = ijoploteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijop> getIjops() {
		return this.ijops;
	}

	public void setIjops(Set<Ijop> ijops) {
		this.ijops = ijops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijocorvarritmo> getIjocorvarritmos() {
		return this.ijocorvarritmos;
	}

	public void setIjocorvarritmos(Set<Ijocorvarritmo> ijocorvarritmos) {
		this.ijocorvarritmos = ijocorvarritmos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijocorreploteins> getIjocorreploteinses() {
		return this.ijocorreploteinses;
	}

	public void setIjocorreploteinses(Set<Ijocorreploteins> ijocorreploteinses) {
		this.ijocorreploteinses = ijocorreploteinses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijmovpostos> getIjmovpostoses() {
		return this.ijmovpostoses;
	}

	public void setIjmovpostoses(Set<Ijmovpostos> ijmovpostoses) {
		this.ijmovpostoses = ijmovpostoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijmdoaloc> getIjmdoalocs() {
		return this.ijmdoalocs;
	}

	public void setIjmdoalocs(Set<Ijmdoaloc> ijmdoalocs) {
		this.ijmdoalocs = ijmdoalocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijctrlturnoint> getIjctrlturnoints() {
		return this.ijctrlturnoints;
	}

	public void setIjctrlturnoints(Set<Ijctrlturnoint> ijctrlturnoints) {
		this.ijctrlturnoints = ijctrlturnoints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijengleituraciclos> getIjengleituracicloses() {
		return this.ijengleituracicloses;
	}

	public void setIjengleituracicloses(
			Set<Ijengleituraciclos> ijengleituracicloses) {
		this.ijengleituracicloses = ijengleituracicloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijenglogciclos> getIjenglogcicloses() {
		return this.ijenglogcicloses;
	}

	public void setIjenglogcicloses(Set<Ijenglogciclos> ijenglogcicloses) {
		this.ijenglogcicloses = ijenglogcicloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijctrlultturmaq> getIjctrlultturmaqs() {
		return this.ijctrlultturmaqs;
	}

	public void setIjctrlultturmaqs(Set<Ijctrlultturmaq> ijctrlultturmaqs) {
		this.ijctrlultturmaqs = ijctrlultturmaqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbinj")
	public Set<Ijdeparamaq> getIjdeparamaqs() {
		return this.ijdeparamaqs;
	}

	public void setIjdeparamaqs(Set<Ijdeparamaq> ijdeparamaqs) {
		this.ijdeparamaqs = ijdeparamaqs;
	}

}
