package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbtphor generated by hbm2java
 */
@Entity
@Table(name = "IJTBTPHOR")
public class Ijtbtphor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1277376503901966633L;
	private String cdtphor;
	private String dstphor;
	private BigDecimal paradatrabextra;
	private Set<Ijhorexc> ijhorexcs = new HashSet<Ijhorexc>(0);

	public Ijtbtphor() {
	}

	public Ijtbtphor(String cdtphor, String dstphor, BigDecimal paradatrabextra) {
		this.cdtphor = cdtphor;
		this.dstphor = dstphor;
		this.paradatrabextra = paradatrabextra;
	}

	public Ijtbtphor(String cdtphor, String dstphor,
			BigDecimal paradatrabextra, Set<Ijhorexc> ijhorexcs) {
		this.cdtphor = cdtphor;
		this.dstphor = dstphor;
		this.paradatrabextra = paradatrabextra;
		this.ijhorexcs = ijhorexcs;
	}

	@Id
	@Column(name = "CDTPHOR", unique = true, nullable = false, length = 6)
	public String getCdtphor() {
		return this.cdtphor;
	}

	public void setCdtphor(String cdtphor) {
		this.cdtphor = cdtphor;
	}

	@Column(name = "DSTPHOR", nullable = false, length = 40)
	public String getDstphor() {
		return this.dstphor;
	}

	public void setDstphor(String dstphor) {
		this.dstphor = dstphor;
	}

	@Column(name = "PARADATRABEXTRA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getParadatrabextra() {
		return this.paradatrabextra;
	}

	public void setParadatrabextra(BigDecimal paradatrabextra) {
		this.paradatrabextra = paradatrabextra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbtphor")
	public Set<Ijhorexc> getIjhorexcs() {
		return this.ijhorexcs;
	}

	public void setIjhorexcs(Set<Ijhorexc> ijhorexcs) {
		this.ijhorexcs = ijhorexcs;
	}

}
