package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbinjandonprcsft generated by hbm2java
 */
@Entity
@Table(name = "IJTBINJANDONPRCSFT")
public class Ijtbinjandonprcsft implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -197182602291740463L;
	private String cdinjetora;
	private Ijtbinj ijtbinj;
	private char strele6;
	private BigDecimal tmprele6lig;
	private BigDecimal tmprele6des;
	private char strele7;
	private double tmplimparnaoinf;
	private BigDecimal tmprele7lig;
	private BigDecimal tmprele7des;
	private char strele8;
	private double vlrefeficultciclo;
	private BigDecimal tmprele8lig;
	private BigDecimal tmprele8des;
	private char stsincronismo;
	private BigDecimal strele7sldzero;
	private BigDecimal tmprele7ligsldzero;
	private BigDecimal tmprele7dessldzero;

	public Ijtbinjandonprcsft() {
	}

	public Ijtbinjandonprcsft(String cdinjetora, Ijtbinj ijtbinj, char strele6,
			BigDecimal tmprele6lig, BigDecimal tmprele6des, char strele7,
			double tmplimparnaoinf, BigDecimal tmprele7lig,
			BigDecimal tmprele7des, char strele8, double vlrefeficultciclo,
			BigDecimal tmprele8lig, BigDecimal tmprele8des, char stsincronismo) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.strele6 = strele6;
		this.tmprele6lig = tmprele6lig;
		this.tmprele6des = tmprele6des;
		this.strele7 = strele7;
		this.tmplimparnaoinf = tmplimparnaoinf;
		this.tmprele7lig = tmprele7lig;
		this.tmprele7des = tmprele7des;
		this.strele8 = strele8;
		this.vlrefeficultciclo = vlrefeficultciclo;
		this.tmprele8lig = tmprele8lig;
		this.tmprele8des = tmprele8des;
		this.stsincronismo = stsincronismo;
	}

	public Ijtbinjandonprcsft(String cdinjetora, Ijtbinj ijtbinj, char strele6,
			BigDecimal tmprele6lig, BigDecimal tmprele6des, char strele7,
			double tmplimparnaoinf, BigDecimal tmprele7lig,
			BigDecimal tmprele7des, char strele8, double vlrefeficultciclo,
			BigDecimal tmprele8lig, BigDecimal tmprele8des, char stsincronismo,
			BigDecimal strele7sldzero, BigDecimal tmprele7ligsldzero,
			BigDecimal tmprele7dessldzero) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.strele6 = strele6;
		this.tmprele6lig = tmprele6lig;
		this.tmprele6des = tmprele6des;
		this.strele7 = strele7;
		this.tmplimparnaoinf = tmplimparnaoinf;
		this.tmprele7lig = tmprele7lig;
		this.tmprele7des = tmprele7des;
		this.strele8 = strele8;
		this.vlrefeficultciclo = vlrefeficultciclo;
		this.tmprele8lig = tmprele8lig;
		this.tmprele8des = tmprele8des;
		this.stsincronismo = stsincronismo;
		this.strele7sldzero = strele7sldzero;
		this.tmprele7ligsldzero = tmprele7ligsldzero;
		this.tmprele7dessldzero = tmprele7dessldzero;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "STRELE6", nullable = false, length = 1)
	public char getStrele6() {
		return this.strele6;
	}

	public void setStrele6(char strele6) {
		this.strele6 = strele6;
	}

	@Column(name = "TMPRELE6LIG", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmprele6lig() {
		return this.tmprele6lig;
	}

	public void setTmprele6lig(BigDecimal tmprele6lig) {
		this.tmprele6lig = tmprele6lig;
	}

	@Column(name = "TMPRELE6DES", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmprele6des() {
		return this.tmprele6des;
	}

	public void setTmprele6des(BigDecimal tmprele6des) {
		this.tmprele6des = tmprele6des;
	}

	@Column(name = "STRELE7", nullable = false, length = 1)
	public char getStrele7() {
		return this.strele7;
	}

	public void setStrele7(char strele7) {
		this.strele7 = strele7;
	}

	@Column(name = "TMPLIMPARNAOINF", nullable = false, precision = 126, scale = 0)
	public double getTmplimparnaoinf() {
		return this.tmplimparnaoinf;
	}

	public void setTmplimparnaoinf(double tmplimparnaoinf) {
		this.tmplimparnaoinf = tmplimparnaoinf;
	}

	@Column(name = "TMPRELE7LIG", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmprele7lig() {
		return this.tmprele7lig;
	}

	public void setTmprele7lig(BigDecimal tmprele7lig) {
		this.tmprele7lig = tmprele7lig;
	}

	@Column(name = "TMPRELE7DES", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmprele7des() {
		return this.tmprele7des;
	}

	public void setTmprele7des(BigDecimal tmprele7des) {
		this.tmprele7des = tmprele7des;
	}

	@Column(name = "STRELE8", nullable = false, length = 1)
	public char getStrele8() {
		return this.strele8;
	}

	public void setStrele8(char strele8) {
		this.strele8 = strele8;
	}

	@Column(name = "VLREFEFICULTCICLO", nullable = false, precision = 126, scale = 0)
	public double getVlrefeficultciclo() {
		return this.vlrefeficultciclo;
	}

	public void setVlrefeficultciclo(double vlrefeficultciclo) {
		this.vlrefeficultciclo = vlrefeficultciclo;
	}

	@Column(name = "TMPRELE8LIG", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmprele8lig() {
		return this.tmprele8lig;
	}

	public void setTmprele8lig(BigDecimal tmprele8lig) {
		this.tmprele8lig = tmprele8lig;
	}

	@Column(name = "TMPRELE8DES", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTmprele8des() {
		return this.tmprele8des;
	}

	public void setTmprele8des(BigDecimal tmprele8des) {
		this.tmprele8des = tmprele8des;
	}

	@Column(name = "STSINCRONISMO", nullable = false, length = 1)
	public char getStsincronismo() {
		return this.stsincronismo;
	}

	public void setStsincronismo(char stsincronismo) {
		this.stsincronismo = stsincronismo;
	}

	@Column(name = "STRELE7SLDZERO", precision = 22, scale = 0)
	public BigDecimal getStrele7sldzero() {
		return this.strele7sldzero;
	}

	public void setStrele7sldzero(BigDecimal strele7sldzero) {
		this.strele7sldzero = strele7sldzero;
	}

	@Column(name = "TMPRELE7LIGSLDZERO", precision = 22, scale = 0)
	public BigDecimal getTmprele7ligsldzero() {
		return this.tmprele7ligsldzero;
	}

	public void setTmprele7ligsldzero(BigDecimal tmprele7ligsldzero) {
		this.tmprele7ligsldzero = tmprele7ligsldzero;
	}

	@Column(name = "TMPRELE7DESSLDZERO", precision = 22, scale = 0)
	public BigDecimal getTmprele7dessldzero() {
		return this.tmprele7dessldzero;
	}

	public void setTmprele7dessldzero(BigDecimal tmprele7dessldzero) {
		this.tmprele7dessldzero = tmprele7dessldzero;
	}

}
