package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbinjmodinsp generated by hbm2java
 */
@Entity
@Table(name = "IJTBINJMODINSP")
public class Ijtbinjmodinsp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7294017616456755955L;
	private String cdinjetora;
	private Ijtbinj ijtbinj;
	private String tpmoduloinspecao;

	public Ijtbinjmodinsp() {
	}

	public Ijtbinjmodinsp(String cdinjetora, Ijtbinj ijtbinj,
			String tpmoduloinspecao) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
		this.tpmoduloinspecao = tpmoduloinspecao;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "TPMODULOINSPECAO", nullable = false, length = 2)
	public String getTpmoduloinspecao() {
		return this.tpmoduloinspecao;
	}

	public void setTpmoduloinspecao(String tpmoduloinspecao) {
		this.tpmoduloinspecao = tpmoduloinspecao;
	}

}
