package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijtbmodisplog generated by hbm2java
 */
@Entity
@Table(name = "IJTBMODISPLOG")
public class Ijtbmodisplog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2208464460049961376L;
	private IjtbmodisplogId id;

	public Ijtbmodisplog() {
	}

	public Ijtbmodisplog(IjtbmodisplogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dthroperacao", column = @Column(name = "DTHROPERACAO", nullable = false, length = 7)),
			@AttributeOverride(name = "tpoperacao", column = @Column(name = "TPOPERACAO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "dtturno", column = @Column(name = "DTTURNO", nullable = false, length = 7)),
			@AttributeOverride(name = "cdturno", column = @Column(name = "CDTURNO", nullable = false, length = 6)),
			@AttributeOverride(name = "qtdmo", column = @Column(name = "QTDMO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdusuario", column = @Column(name = "CDUSUARIO", nullable = false, length = 6)),
			@AttributeOverride(name = "motivoalteracao", column = @Column(name = "MOTIVOALTERACAO", length = 250)) })
	public IjtbmodisplogId getId() {
		return this.id;
	}

	public void setId(IjtbmodisplogId id) {
		this.id = id;
	}

}
