package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbvarritmo generated by hbm2java
 */
@Entity
@Table(name = "IJTBVARRITMO")
public class Ijtbvarritmo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3333047205554913555L;
	private String cdvarritmo;
	private String dsvarritmo;
	private char stativo;
	private BigDecimal percmax;
	private Set<Ijocorvarritmoitem> ijocorvarritmoitems = new HashSet<Ijocorvarritmoitem>(
			0);
	private Set<Exportacao003> exportacao003s = new HashSet<Exportacao003>(0);
	private Set<Exportacao001> exportacao001s = new HashSet<Exportacao001>(0);

	public Ijtbvarritmo() {
	}

	public Ijtbvarritmo(String cdvarritmo, String dsvarritmo, char stativo) {
		this.cdvarritmo = cdvarritmo;
		this.dsvarritmo = dsvarritmo;
		this.stativo = stativo;
	}

	public Ijtbvarritmo(String cdvarritmo, String dsvarritmo, char stativo,
			BigDecimal percmax, Set<Ijocorvarritmoitem> ijocorvarritmoitems,
			Set<Exportacao003> exportacao003s, Set<Exportacao001> exportacao001s) {
		this.cdvarritmo = cdvarritmo;
		this.dsvarritmo = dsvarritmo;
		this.stativo = stativo;
		this.percmax = percmax;
		this.ijocorvarritmoitems = ijocorvarritmoitems;
		this.exportacao003s = exportacao003s;
		this.exportacao001s = exportacao001s;
	}

	@Id
	@Column(name = "CDVARRITMO", unique = true, nullable = false, length = 6)
	public String getCdvarritmo() {
		return this.cdvarritmo;
	}

	public void setCdvarritmo(String cdvarritmo) {
		this.cdvarritmo = cdvarritmo;
	}

	@Column(name = "DSVARRITMO", nullable = false, length = 40)
	public String getDsvarritmo() {
		return this.dsvarritmo;
	}

	public void setDsvarritmo(String dsvarritmo) {
		this.dsvarritmo = dsvarritmo;
	}

	@Column(name = "STATIVO", nullable = false, length = 1)
	public char getStativo() {
		return this.stativo;
	}

	public void setStativo(char stativo) {
		this.stativo = stativo;
	}

	@Column(name = "PERCMAX", precision = 22, scale = 0)
	public BigDecimal getPercmax() {
		return this.percmax;
	}

	public void setPercmax(BigDecimal percmax) {
		this.percmax = percmax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbvarritmo")
	public Set<Ijocorvarritmoitem> getIjocorvarritmoitems() {
		return this.ijocorvarritmoitems;
	}

	public void setIjocorvarritmoitems(
			Set<Ijocorvarritmoitem> ijocorvarritmoitems) {
		this.ijocorvarritmoitems = ijocorvarritmoitems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbvarritmo")
	public Set<Exportacao003> getExportacao003s() {
		return this.exportacao003s;
	}

	public void setExportacao003s(Set<Exportacao003> exportacao003s) {
		this.exportacao003s = exportacao003s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbvarritmo")
	public Set<Exportacao001> getExportacao001s() {
		return this.exportacao001s;
	}

	public void setExportacao001s(Set<Exportacao001> exportacao001s) {
		this.exportacao001s = exportacao001s;
	}

}
