package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbaco generated by hbm2java
 */
@Entity
@Table(name = "IJTBACO")
public class Ijtbaco implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5777354130650253654L;
	private String cdacoes;
	private String dsacoes;
	private Character tipoacao;
	private Integer stativo;
	private Set<Ijrearef> ijrearefs = new HashSet<Ijrearef>(0);
	private Set<Ijreapar> ijreapars = new HashSet<Ijreapar>(0);
	private Set<Ijpdcapadrao> ijpdcapadraos = new HashSet<Ijpdcapadrao>(0);
	private Set<Ijpdcaacao> ijpdcaacaos = new HashSet<Ijpdcaacao>(0);
	private Set<Ijlogcorrreq> ijlogcorrreqs = new HashSet<Ijlogcorrreq>(0);

	public Ijtbaco() {
	}

	public Ijtbaco(String cdacoes, Integer stativo) {
		this.cdacoes = cdacoes;
		this.stativo = stativo;
	}

	public Ijtbaco(String cdacoes, String dsacoes, Character tipoacao,
			Integer stativo, Set<Ijrearef> ijrearefs,
			Set<Ijreapar> ijreapars, Set<Ijpdcapadrao> ijpdcapadraos,
			Set<Ijpdcaacao> ijpdcaacaos, Set<Ijlogcorrreq> ijlogcorrreqs) {
		this.cdacoes = cdacoes;
		this.dsacoes = dsacoes;
		this.tipoacao = tipoacao;
		this.stativo = stativo;
		this.ijrearefs = ijrearefs;
		this.ijreapars = ijreapars;
		this.ijpdcapadraos = ijpdcapadraos;
		this.ijpdcaacaos = ijpdcaacaos;
		this.ijlogcorrreqs = ijlogcorrreqs;
	}

	@Id
	@Column(name = "CDACOES", unique = true, nullable = false, length = 6)
	public String getCdacoes() {
		return this.cdacoes;
	}

	public void setCdacoes(String cdacoes) {
		this.cdacoes = cdacoes;
	}

	@Column(name = "DSACOES")
	public String getDsacoes() {
		return this.dsacoes;
	}

	public void setDsacoes(String dsacoes) {
		this.dsacoes = dsacoes;
	}

	@Column(name = "TIPOACAO", length = 1)
	public Character getTipoacao() {
		return this.tipoacao;
	}

	public void setTipoacao(Character tipoacao) {
		this.tipoacao = tipoacao;
	}

	@Column(name = "STATIVO", nullable = false, precision = 22, scale = 0)
	public Integer getStativo() {
		return this.stativo;
	}

	public void setStativo(Integer stativo) {
		this.stativo = stativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbaco")
	public Set<Ijrearef> getIjrearefs() {
		return this.ijrearefs;
	}

	public void setIjrearefs(Set<Ijrearef> ijrearefs) {
		this.ijrearefs = ijrearefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbaco")
	public Set<Ijreapar> getIjreapars() {
		return this.ijreapars;
	}

	public void setIjreapars(Set<Ijreapar> ijreapars) {
		this.ijreapars = ijreapars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbaco")
	public Set<Ijpdcapadrao> getIjpdcapadraos() {
		return this.ijpdcapadraos;
	}

	public void setIjpdcapadraos(Set<Ijpdcapadrao> ijpdcapadraos) {
		this.ijpdcapadraos = ijpdcapadraos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbaco")
	public Set<Ijpdcaacao> getIjpdcaacaos() {
		return this.ijpdcaacaos;
	}

	public void setIjpdcaacaos(Set<Ijpdcaacao> ijpdcaacaos) {
		this.ijpdcaacaos = ijpdcaacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbaco")
	public Set<Ijlogcorrreq> getIjlogcorrreqs() {
		return this.ijlogcorrreqs;
	}

	public void setIjlogcorrreqs(Set<Ijlogcorrreq> ijlogcorrreqs) {
		this.ijlogcorrreqs = ijlogcorrreqs;
	}

}
