package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijtbcarlog generated by hbm2java
 */
@Entity
@Table(name = "IJTBCARLOG")
public class Ijtbcarlog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7563950446333888076L;
	private IjtbcarlogId id;

	public Ijtbcarlog() {
	}

	public Ijtbcarlog(IjtbcarlogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdcargo", column = @Column(name = "CDCARGO", nullable = false, length = 6)),
			@AttributeOverride(name = "dscargo", column = @Column(name = "DSCARGO", length = 40)),
			@AttributeOverride(name = "vlhora", column = @Column(name = "VLHORA", precision = 126, scale = 0)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 20)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", nullable = false, length = 6)) })
	public IjtbcarlogId getId() {
		return this.id;
	}

	public void setId(IjtbcarlogId id) {
		this.id = id;
	}

}
