package idw.model.pojos.injet;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import idw.model.pojos.injet.template.IjtbfreshTemplate;

/**
 * Ijtbfresh generated by hbm2java
 */
@Entity
@Table(name = "IJTBFRESH")
public class Ijtbfresh extends IjtbfreshTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3713261483374382351L;
	private IjtbfreshId pk;

	public Ijtbfresh() {
	}

	public Ijtbfresh(IjtbfreshId id) {
		this.pk = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "campo01", column = @Column(name = "CAMPO01", nullable = false, length = 60)),
			@AttributeOverride(name = "campo02", column = @Column(name = "CAMPO02", nullable = false, length = 60)),
			@AttributeOverride(name = "campo03", column = @Column(name = "CAMPO03", nullable = false, length = 60)),
			@AttributeOverride(name = "campo04", column = @Column(name = "CAMPO04", nullable = false, length = 60)),
			@AttributeOverride(name = "campo05", column = @Column(name = "CAMPO05", nullable = false, length = 60)),
			@AttributeOverride(name = "campo06", column = @Column(name = "CAMPO06", nullable = false, length = 60)),
			@AttributeOverride(name = "campo07", column = @Column(name = "CAMPO07", nullable = false, length = 60)),
			@AttributeOverride(name = "campo08", column = @Column(name = "CAMPO08", nullable = false, length = 60)),
			@AttributeOverride(name = "campo09", column = @Column(name = "CAMPO09", nullable = false, length = 60)),
			@AttributeOverride(name = "campo10", column = @Column(name = "CAMPO10", nullable = false, length = 60)),
			@AttributeOverride(name = "campo11", column = @Column(name = "CAMPO11", nullable = false, length = 60)),
			@AttributeOverride(name = "campo12", column = @Column(name = "CAMPO12", nullable = false, length = 60)),
			@AttributeOverride(name = "campo13", column = @Column(name = "CAMPO13", nullable = false, length = 60)),
			@AttributeOverride(name = "campo14", column = @Column(name = "CAMPO14", nullable = false, length = 60)),
			@AttributeOverride(name = "campo15", column = @Column(name = "CAMPO15", nullable = false, length = 60)),
			@AttributeOverride(name = "campo16", column = @Column(name = "CAMPO16", nullable = false, length = 60)),
			@AttributeOverride(name = "campo17", column = @Column(name = "CAMPO17", nullable = false, length = 60)),
			@AttributeOverride(name = "campo18", column = @Column(name = "CAMPO18", nullable = false, length = 60)),
			@AttributeOverride(name = "campo19", column = @Column(name = "CAMPO19", length = 60)),
			@AttributeOverride(name = "campo20", column = @Column(name = "CAMPO20", length = 60)),
			@AttributeOverride(name = "campo21", column = @Column(name = "CAMPO21", length = 60)),
			@AttributeOverride(name = "campo22", column = @Column(name = "CAMPO22", length = 60)),
			@AttributeOverride(name = "campo23", column = @Column(name = "CAMPO23", length = 60)),
			@AttributeOverride(name = "campo24", column = @Column(name = "CAMPO24", length = 60)),
			@AttributeOverride(name = "campo25", column = @Column(name = "CAMPO25", length = 60)),
			@AttributeOverride(name = "campo26", column = @Column(name = "CAMPO26", length = 60)),
			@AttributeOverride(name = "campo27", column = @Column(name = "CAMPO27", length = 60)),
			@AttributeOverride(name = "campo28", column = @Column(name = "CAMPO28", length = 60)),
			@AttributeOverride(name = "campo29", column = @Column(name = "CAMPO29", length = 60)),
			@AttributeOverride(name = "campo30", column = @Column(name = "CAMPO30", length = 60)),
			@AttributeOverride(name = "campo31", column = @Column(name = "CAMPO31", length = 60)),
			@AttributeOverride(name = "campo32", column = @Column(name = "CAMPO32", length = 60)),
			@AttributeOverride(name = "campo33", column = @Column(name = "CAMPO33", length = 60)),
			@AttributeOverride(name = "campo34", column = @Column(name = "CAMPO34", length = 60)),
			@AttributeOverride(name = "campo35", column = @Column(name = "CAMPO35", length = 60)),
			@AttributeOverride(name = "campo36", column = @Column(name = "CAMPO36", length = 60)),
			@AttributeOverride(name = "campo38", column = @Column(name = "CAMPO38", length = 60)),
			@AttributeOverride(name = "campo37", column = @Column(name = "CAMPO37", length = 60)) })
	public IjtbfreshId getPk() {
		return this.pk;
	}

	public void setPk(IjtbfreshId id) {
		this.pk = id;
	}

}
