package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbmetodocgq generated by hbm2java
 */
@Entity
@Table(name = "IJTBMETODOCGQ")
public class Ijtbmetodocgq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6381797044803120496L;
	private String idmetodo;
	private Set<Ijespecinsproatrib> ijespecinsproatribs = new HashSet<Ijespecinsproatrib>(
			0);
	private Set<Ijespecinsppro> ijespecinsppros = new HashSet<Ijespecinsppro>(0);

	public Ijtbmetodocgq() {
	}

	public Ijtbmetodocgq(String idmetodo) {
		this.idmetodo = idmetodo;
	}

	public Ijtbmetodocgq(String idmetodo,
			Set<Ijespecinsproatrib> ijespecinsproatribs,
			Set<Ijespecinsppro> ijespecinsppros) {
		this.idmetodo = idmetodo;
		this.ijespecinsproatribs = ijespecinsproatribs;
		this.ijespecinsppros = ijespecinsppros;
	}

	@Id
	@Column(name = "IDMETODO", unique = true, nullable = false, length = 20)
	public String getIdmetodo() {
		return this.idmetodo;
	}

	public void setIdmetodo(String idmetodo) {
		this.idmetodo = idmetodo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmetodocgq")
	public Set<Ijespecinsproatrib> getIjespecinsproatribs() {
		return this.ijespecinsproatribs;
	}

	public void setIjespecinsproatribs(
			Set<Ijespecinsproatrib> ijespecinsproatribs) {
		this.ijespecinsproatribs = ijespecinsproatribs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmetodocgq")
	public Set<Ijespecinsppro> getIjespecinsppros() {
		return this.ijespecinsppros;
	}

	public void setIjespecinsppros(Set<Ijespecinsppro> ijespecinsppros) {
		this.ijespecinsppros = ijespecinsppros;
	}

}
