package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijtbcaulog generated by hbm2java
 */
@Entity
@Table(name = "IJTBCAULOG")
public class Ijtbcaulog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8527741992436642266L;
	private IjtbcaulogId id;

	public Ijtbcaulog() {
	}

	public Ijtbcaulog(IjtbcaulogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdcausas", column = @Column(name = "CDCAUSAS", nullable = false, length = 6)),
			@AttributeOverride(name = "dscausas", column = @Column(name = "DSCAUSAS")),
			@AttributeOverride(name = "tipocausa", column = @Column(name = "TIPOCAUSA", length = 1)),
			@AttributeOverride(name = "stativo", column = @Column(name = "STATIVO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", nullable = false, length = 6)) })
	public IjtbcaulogId getId() {
		return this.id;
	}

	public void setId(IjtbcaulogId id) {
		this.id = id;
	}

}
