package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbcar generated by hbm2java
 */
@Entity
@Table(name = "IJTBCAR")
public class Ijtbcar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6269701403777906710L;
	private String cdcargo;
	private String dscargo;
	private Double vlhora;
	private Set<Ijtbusu> ijtbusus = new HashSet<Ijtbusu>(0);
	private Set<Ijmdoalocdet> ijmdoalocdets = new HashSet<Ijmdoalocdet>(0);

	public Ijtbcar() {
	}

	public Ijtbcar(String cdcargo) {
		this.cdcargo = cdcargo;
	}

	public Ijtbcar(String cdcargo, String dscargo, Double vlhora,
			Set<Ijtbusu> ijtbusus, Set<Ijmdoalocdet> ijmdoalocdets) {
		this.cdcargo = cdcargo;
		this.dscargo = dscargo;
		this.vlhora = vlhora;
		this.ijtbusus = ijtbusus;
		this.ijmdoalocdets = ijmdoalocdets;
	}

	@Id
	@Column(name = "CDCARGO", unique = true, nullable = false, length = 6)
	public String getCdcargo() {
		return this.cdcargo;
	}

	public void setCdcargo(String cdcargo) {
		this.cdcargo = cdcargo;
	}

	@Column(name = "DSCARGO", length = 40)
	public String getDscargo() {
		return this.dscargo;
	}

	public void setDscargo(String dscargo) {
		this.dscargo = dscargo;
	}

	@Column(name = "VLHORA", precision = 126, scale = 0)
	public Double getVlhora() {
		return this.vlhora;
	}

	public void setVlhora(Double vlhora) {
		this.vlhora = vlhora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbcar")
	public Set<Ijtbusu> getIjtbusus() {
		return this.ijtbusus;
	}

	public void setIjtbusus(Set<Ijtbusu> ijtbusus) {
		this.ijtbusus = ijtbusus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbcar")
	public Set<Ijmdoalocdet> getIjmdoalocdets() {
		return this.ijmdoalocdets;
	}

	public void setIjmdoalocdets(Set<Ijmdoalocdet> ijmdoalocdets) {
		this.ijmdoalocdets = ijmdoalocdets;
	}

}
