package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbmolgen generated by hbm2java
 */
@Entity
@Table(name = "IJTBMOLGEN")
public class Ijtbmolgen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6356499029977151006L;
	private String cdmolde;
	private Ijtbmol ijtbmol;
	private char generico;

	public Ijtbmolgen() {
	}

	public Ijtbmolgen(String cdmolde, Ijtbmol ijtbmol, char generico) {
		this.cdmolde = cdmolde;
		this.ijtbmol = ijtbmol;
		this.generico = generico;
	}

	@Id
	@Column(name = "CDMOLDE", unique = true, nullable = false, length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMOLDE", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbmol getIjtbmol() {
		return this.ijtbmol;
	}

	public void setIjtbmol(Ijtbmol ijtbmol) {
		this.ijtbmol = ijtbmol;
	}

	@Column(name = "GENERICO", nullable = false, length = 1)
	public char getGenerico() {
		return this.generico;
	}

	public void setGenerico(char generico) {
		this.generico = generico;
	}

}
