package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtbmotsemprog generated by hbm2java
 */
@Entity
@Table(name = "IJTBMOTSEMPROG")
public class Ijtbmotsemprog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4437268972417440921L;
	private String cdmotsemprog;
	private String dsmotsemprog;
	private char stativo;
	private Set<Ijreamovsemprog> ijreamovsemprogs = new HashSet<Ijreamovsemprog>(
			0);

	public Ijtbmotsemprog() {
	}

	public Ijtbmotsemprog(String cdmotsemprog, String dsmotsemprog, char stativo) {
		this.cdmotsemprog = cdmotsemprog;
		this.dsmotsemprog = dsmotsemprog;
		this.stativo = stativo;
	}

	public Ijtbmotsemprog(String cdmotsemprog, String dsmotsemprog,
			char stativo, Set<Ijreamovsemprog> ijreamovsemprogs) {
		this.cdmotsemprog = cdmotsemprog;
		this.dsmotsemprog = dsmotsemprog;
		this.stativo = stativo;
		this.ijreamovsemprogs = ijreamovsemprogs;
	}

	@Id
	@Column(name = "CDMOTSEMPROG", unique = true, nullable = false, length = 6)
	public String getCdmotsemprog() {
		return this.cdmotsemprog;
	}

	public void setCdmotsemprog(String cdmotsemprog) {
		this.cdmotsemprog = cdmotsemprog;
	}

	@Column(name = "DSMOTSEMPROG", nullable = false, length = 60)
	public String getDsmotsemprog() {
		return this.dsmotsemprog;
	}

	public void setDsmotsemprog(String dsmotsemprog) {
		this.dsmotsemprog = dsmotsemprog;
	}

	@Column(name = "STATIVO", nullable = false, length = 1)
	public char getStativo() {
		return this.stativo;
	}

	public void setStativo(char stativo) {
		this.stativo = stativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtbmotsemprog")
	public Set<Ijreamovsemprog> getIjreamovsemprogs() {
		return this.ijreamovsemprogs;
	}

	public void setIjreamovsemprogs(Set<Ijreamovsemprog> ijreamovsemprogs) {
		this.ijreamovsemprogs = ijreamovsemprogs;
	}

}
