package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IjtbslidesxmaqId generated by hbm2java
 */
@Embeddable
public class IjtbslidesxmaqId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4734749805809452686L;
	private String cdslide;
	private BigDecimal ordemmaquina;

	public IjtbslidesxmaqId() {
	}

	public IjtbslidesxmaqId(String cdslide, BigDecimal ordemmaquina) {
		this.cdslide = cdslide;
		this.ordemmaquina = ordemmaquina;
	}

	@Column(name = "CDSLIDE", nullable = false, length = 6)
	public String getCdslide() {
		return this.cdslide;
	}

	public void setCdslide(String cdslide) {
		this.cdslide = cdslide;
	}

	@Column(name = "ORDEMMAQUINA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOrdemmaquina() {
		return this.ordemmaquina;
	}

	public void setOrdemmaquina(BigDecimal ordemmaquina) {
		this.ordemmaquina = ordemmaquina;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IjtbslidesxmaqId))
			return false;
		IjtbslidesxmaqId castOther = (IjtbslidesxmaqId) other;

		return ((this.getCdslide() == castOther.getCdslide()) || (this
				.getCdslide() != null && castOther.getCdslide() != null && this
				.getCdslide().equals(castOther.getCdslide())))
				&& ((this.getOrdemmaquina() == castOther.getOrdemmaquina()) || (this
						.getOrdemmaquina() != null
						&& castOther.getOrdemmaquina() != null && this
						.getOrdemmaquina().equals(castOther.getOrdemmaquina())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCdslide() == null ? 0 : this.getCdslide().hashCode());
		result = 37
				* result
				+ (getOrdemmaquina() == null ? 0 : this.getOrdemmaquina()
						.hashCode());
		return result;
	}

}
