package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbboardmach generated by hbm2java
 */
@Entity
@Table(name = "IJTBBOARDMACH")
public class Ijtbboardmach implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6699658068054359230L;
	private IjtbboardmachId id;
	private Ijtbboard ijtbboard;
	private char campo08;

	public Ijtbboardmach() {
	}

	public Ijtbboardmach(IjtbboardmachId id, Ijtbboard ijtbboard, char campo08) {
		this.id = id;
		this.ijtbboard = ijtbboard;
		this.campo08 = campo08;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "campo01", column = @Column(name = "CAMPO01", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "campo07", column = @Column(name = "CAMPO07", nullable = false, length = 10)) })
	public IjtbboardmachId getId() {
		return this.id;
	}

	public void setId(IjtbboardmachId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAMPO01", nullable = false, insertable = false, updatable = false)
	public Ijtbboard getIjtbboard() {
		return this.ijtbboard;
	}

	public void setIjtbboard(Ijtbboard ijtbboard) {
		this.ijtbboard = ijtbboard;
	}

	@Column(name = "CAMPO08", nullable = false, length = 1)
	public char getCampo08() {
		return this.campo08;
	}

	public void setCampo08(char campo08) {
		this.campo08 = campo08;
	}

}
