package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbinjoper generated by hbm2java
 */
@Entity
@Table(name = "IJTBINJOPER")
public class Ijtbinjoper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 704892358153839949L;
	private IjtbinjoperId id;
	private Ijtbinj ijtbinj;
	private String ativa;

	public Ijtbinjoper() {
	}

	public Ijtbinjoper(IjtbinjoperId id, Ijtbinj ijtbinj, String ativa) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ativa = ativa;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "operacao", column = @Column(name = "OPERACAO", nullable = false, length = 4)) })
	public IjtbinjoperId getId() {
		return this.id;
	}

	public void setId(IjtbinjoperId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "ATIVA", nullable = false, length = 1)
	public String getAtiva() {
		return this.ativa;
	}

	public void setAtiva(String ativa) {
		this.ativa = ativa;
	}

}
