package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijtbsetlog generated by hbm2java
 */
@Entity
@Table(name = "IJTBSETLOG")
public class Ijtbsetlog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2850507790339753690L;
	private IjtbsetlogId id;

	public Ijtbsetlog() {
	}

	public Ijtbsetlog(IjtbsetlogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdsetor", column = @Column(name = "CDSETOR", nullable = false, length = 6)),
			@AttributeOverride(name = "dssetor", column = @Column(name = "DSSETOR", length = 40)),
			@AttributeOverride(name = "ramal", column = @Column(name = "RAMAL", length = 10)),
			@AttributeOverride(name = "telefone", column = @Column(name = "TELEFONE", length = 10)),
			@AttributeOverride(name = "gerente", column = @Column(name = "GERENTE", length = 20)),
			@AttributeOverride(name = "dtcadastro", column = @Column(name = "DTCADASTRO", length = 7)),
			@AttributeOverride(name = "dthrmanut", column = @Column(name = "DTHRMANUT", nullable = false, length = 7)),
			@AttributeOverride(name = "tpmanut", column = @Column(name = "TPMANUT", nullable = false, length = 1)),
			@AttributeOverride(name = "cdusuresp", column = @Column(name = "CDUSURESP", nullable = false, length = 6)) })
	public IjtbsetlogId getId() {
		return this.id;
	}

	public void setId(IjtbsetlogId id) {
		this.id = id;
	}

}
