package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijtboperacoes generated by hbm2java
 */
@Entity
@Table(name = "IJTBOPERACOES")
public class Ijtboperacoes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8107531028062018309L;
	private String cdoperacao;
	private Ijtbunidmedida ijtbunidmedida;
	private String dsoperacao;
	private BigDecimal tpoperacao;
	private BigDecimal reqfim;
	private BigDecimal reqqtd;
	private BigDecimal reqmaq;
	private BigDecimal reqop;
	private BigDecimal reqoper;
	private BigDecimal permiteopergrupo;
	private Set<Ijtbmol> ijtbmols = new HashSet<Ijtbmol>(0);
	private Set<Ijgrpdetestproc> ijgrpdetestprocs = new HashSet<Ijgrpdetestproc>(
			0);
	private Set<Ijgrpestproc> ijgrpestprocs = new HashSet<Ijgrpestproc>(0);
	private Set<Ijmovpostos> ijmovpostoses = new HashSet<Ijmovpostos>(0);
	private Set<Ijoprotoper> ijoprotopers = new HashSet<Ijoprotoper>(0);
	private Set<Ijroteiroprodhst> ijroteiroprodhsts = new HashSet<Ijroteiroprodhst>(
			0);
	private Set<Ijroteiroprod> ijroteiroprods = new HashSet<Ijroteiroprod>(0);

	public Ijtboperacoes() {
	}

	public Ijtboperacoes(String cdoperacao, String dsoperacao) {
		this.cdoperacao = cdoperacao;
		this.dsoperacao = dsoperacao;
	}

	public Ijtboperacoes(String cdoperacao, Ijtbunidmedida ijtbunidmedida,
			String dsoperacao, BigDecimal tpoperacao, BigDecimal reqfim,
			BigDecimal reqqtd, BigDecimal reqmaq, BigDecimal reqop,
			BigDecimal reqoper, BigDecimal permiteopergrupo,
			Set<Ijtbmol> ijtbmols, Set<Ijgrpdetestproc> ijgrpdetestprocs,
			Set<Ijgrpestproc> ijgrpestprocs, Set<Ijmovpostos> ijmovpostoses,
			Set<Ijoprotoper> ijoprotopers,
			Set<Ijroteiroprodhst> ijroteiroprodhsts,
			Set<Ijroteiroprod> ijroteiroprods) {
		this.cdoperacao = cdoperacao;
		this.ijtbunidmedida = ijtbunidmedida;
		this.dsoperacao = dsoperacao;
		this.tpoperacao = tpoperacao;
		this.reqfim = reqfim;
		this.reqqtd = reqqtd;
		this.reqmaq = reqmaq;
		this.reqop = reqop;
		this.reqoper = reqoper;
		this.permiteopergrupo = permiteopergrupo;
		this.ijtbmols = ijtbmols;
		this.ijgrpdetestprocs = ijgrpdetestprocs;
		this.ijgrpestprocs = ijgrpestprocs;
		this.ijmovpostoses = ijmovpostoses;
		this.ijoprotopers = ijoprotopers;
		this.ijroteiroprodhsts = ijroteiroprodhsts;
		this.ijroteiroprods = ijroteiroprods;
	}

	@Id
	@Column(name = "CDOPERACAO", nullable = false, length = 6)
	public String getCdoperacao() {
		return this.cdoperacao;
	}

	public void setCdoperacao(String cdoperacao) {
		this.cdoperacao = cdoperacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIDQTDPROC")
	public Ijtbunidmedida getIjtbunidmedida() {
		return this.ijtbunidmedida;
	}

	public void setIjtbunidmedida(Ijtbunidmedida ijtbunidmedida) {
		this.ijtbunidmedida = ijtbunidmedida;
	}

	@Column(name = "DSOPERACAO", nullable = false, length = 40)
	public String getDsoperacao() {
		return this.dsoperacao;
	}

	public void setDsoperacao(String dsoperacao) {
		this.dsoperacao = dsoperacao;
	}

	@Column(name = "TPOPERACAO", precision = 22, scale = 0)
	public BigDecimal getTpoperacao() {
		return this.tpoperacao;
	}

	public void setTpoperacao(BigDecimal tpoperacao) {
		this.tpoperacao = tpoperacao;
	}

	@Column(name = "REQFIM", precision = 22, scale = 0)
	public BigDecimal getReqfim() {
		return this.reqfim;
	}

	public void setReqfim(BigDecimal reqfim) {
		this.reqfim = reqfim;
	}

	@Column(name = "REQQTD", precision = 22, scale = 0)
	public BigDecimal getReqqtd() {
		return this.reqqtd;
	}

	public void setReqqtd(BigDecimal reqqtd) {
		this.reqqtd = reqqtd;
	}

	@Column(name = "REQMAQ", precision = 22, scale = 0)
	public BigDecimal getReqmaq() {
		return this.reqmaq;
	}

	public void setReqmaq(BigDecimal reqmaq) {
		this.reqmaq = reqmaq;
	}

	@Column(name = "REQOP", precision = 22, scale = 0)
	public BigDecimal getReqop() {
		return this.reqop;
	}

	public void setReqop(BigDecimal reqop) {
		this.reqop = reqop;
	}

	@Column(name = "REQOPER", precision = 22, scale = 0)
	public BigDecimal getReqoper() {
		return this.reqoper;
	}

	public void setReqoper(BigDecimal reqoper) {
		this.reqoper = reqoper;
	}

	@Column(name = "PERMITEOPERGRUPO", precision = 22, scale = 0)
	public BigDecimal getPermiteopergrupo() {
		return this.permiteopergrupo;
	}

	public void setPermiteopergrupo(BigDecimal permiteopergrupo) {
		this.permiteopergrupo = permiteopergrupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtboperacoes")
	public Set<Ijtbmol> getIjtbmols() {
		return this.ijtbmols;
	}

	public void setIjtbmols(Set<Ijtbmol> ijtbmols) {
		this.ijtbmols = ijtbmols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtboperacoes")
	public Set<Ijgrpdetestproc> getIjgrpdetestprocs() {
		return this.ijgrpdetestprocs;
	}

	public void setIjgrpdetestprocs(Set<Ijgrpdetestproc> ijgrpdetestprocs) {
		this.ijgrpdetestprocs = ijgrpdetestprocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtboperacoes")
	public Set<Ijgrpestproc> getIjgrpestprocs() {
		return this.ijgrpestprocs;
	}

	public void setIjgrpestprocs(Set<Ijgrpestproc> ijgrpestprocs) {
		this.ijgrpestprocs = ijgrpestprocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtboperacoes")
	public Set<Ijmovpostos> getIjmovpostoses() {
		return this.ijmovpostoses;
	}

	public void setIjmovpostoses(Set<Ijmovpostos> ijmovpostoses) {
		this.ijmovpostoses = ijmovpostoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtboperacoes")
	public Set<Ijoprotoper> getIjoprotopers() {
		return this.ijoprotopers;
	}

	public void setIjoprotopers(Set<Ijoprotoper> ijoprotopers) {
		this.ijoprotopers = ijoprotopers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtboperacoes")
	public Set<Ijroteiroprodhst> getIjroteiroprodhsts() {
		return this.ijroteiroprodhsts;
	}

	public void setIjroteiroprodhsts(Set<Ijroteiroprodhst> ijroteiroprodhsts) {
		this.ijroteiroprodhsts = ijroteiroprodhsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijtboperacoes")
	public Set<Ijroteiroprod> getIjroteiroprods() {
		return this.ijroteiroprods;
	}

	public void setIjroteiroprods(Set<Ijroteiroprod> ijroteiroprods) {
		this.ijroteiroprods = ijroteiroprods;
	}

}
