package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ijtbparreqtecespec generated by hbm2java
 */
@Entity
@Table(name = "IJTBPARREQTECESPEC")
public class Ijtbparreqtecespec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -354782071333389312L;
	private String cdparada;
	private Ijtbpar ijtbpar;
	private char reqidtrocadorferr;
	private char reqidmaster;

	public Ijtbparreqtecespec() {
	}

	public Ijtbparreqtecespec(String cdparada, Ijtbpar ijtbpar,
			char reqidtrocadorferr, char reqidmaster) {
		this.cdparada = cdparada;
		this.ijtbpar = ijtbpar;
		this.reqidtrocadorferr = reqidtrocadorferr;
		this.reqidmaster = reqidmaster;
	}

	@Id
	@Column(name = "CDPARADA", unique = true, nullable = false, length = 6)
	public String getCdparada() {
		return this.cdparada;
	}

	public void setCdparada(String cdparada) {
		this.cdparada = cdparada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPARADA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbpar getIjtbpar() {
		return this.ijtbpar;
	}

	public void setIjtbpar(Ijtbpar ijtbpar) {
		this.ijtbpar = ijtbpar;
	}

	@Column(name = "REQIDTROCADORFERR", nullable = false, length = 1)
	public char getReqidtrocadorferr() {
		return this.reqidtrocadorferr;
	}

	public void setReqidtrocadorferr(char reqidtrocadorferr) {
		this.reqidtrocadorferr = reqidtrocadorferr;
	}

	@Column(name = "REQIDMASTER", nullable = false, length = 1)
	public char getReqidmaster() {
		return this.reqidmaster;
	}

	public void setReqidmaster(char reqidmaster) {
		this.reqidmaster = reqidmaster;
	}

}
