package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijtmpultst generated by hbm2java
 */
@Entity
@Table(name = "IJTMPULTST")
public class Ijtmpultst implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8631450484881954660L;
	private String cdinjetora;
	private Ijop ijop;
	private Ijtbinj ijtbinj;
	private Character situacao;
	private Date dthrinist;
	private Date dthrfimst;

	public Ijtmpultst() {
	}

	public Ijtmpultst(String cdinjetora, Ijtbinj ijtbinj) {
		this.cdinjetora = cdinjetora;
		this.ijtbinj = ijtbinj;
	}

	public Ijtmpultst(String cdinjetora, Ijop ijop, Ijtbinj ijtbinj,
			Character situacao, Date dthrinist, Date dthrfimst) {
		this.cdinjetora = cdinjetora;
		this.ijop = ijop;
		this.ijtbinj = ijtbinj;
		this.situacao = situacao;
		this.dthrinist = dthrinist;
		this.dthrfimst = dthrfimst;
	}

	@Id
	@Column(name = "CDINJETORA", unique = true, nullable = false, length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NROP")
	public Ijop getIjop() {
		return this.ijop;
	}

	public void setIjop(Ijop ijop) {
		this.ijop = ijop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@Column(name = "SITUACAO", length = 1)
	public Character getSituacao() {
		return this.situacao;
	}

	public void setSituacao(Character situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRINIST", length = 7)
	public Date getDthrinist() {
		return this.dthrinist;
	}

	public void setDthrinist(Date dthrinist) {
		this.dthrinist = dthrinist;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRFIMST", length = 7)
	public Date getDthrfimst() {
		return this.dthrfimst;
	}

	public void setDthrfimst(Date dthrfimst) {
		this.dthrfimst = dthrfimst;
	}

}
