package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ijtrealmestre generated by hbm2java
 */
@Entity
@Table(name = "IJTREALMESTRE")
public class Ijtrealmestre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2584464799873971509L;
	private String cdmestre;
	private Ijtbmestres ijtbmestres;
	private Date dtrefturno;
	private String cdturno;
	private Date dthriturno;
	private Date dthrfturno;
	private Date dthrsistema;

	public Ijtrealmestre() {
	}

	public Ijtrealmestre(String cdmestre, Ijtbmestres ijtbmestres,
			Date dtrefturno, String cdturno, Date dthriturno, Date dthrfturno,
			Date dthrsistema) {
		this.cdmestre = cdmestre;
		this.ijtbmestres = ijtbmestres;
		this.dtrefturno = dtrefturno;
		this.cdturno = cdturno;
		this.dthriturno = dthriturno;
		this.dthrfturno = dthrfturno;
		this.dthrsistema = dthrsistema;
	}

	@Id
	@Column(name = "CDMESTRE", unique = true, nullable = false, length = 6)
	public String getCdmestre() {
		return this.cdmestre;
	}

	public void setCdmestre(String cdmestre) {
		this.cdmestre = cdmestre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDMESTRE", unique = true, nullable = false, insertable = false, updatable = false)
	public Ijtbmestres getIjtbmestres() {
		return this.ijtbmestres;
	}

	public void setIjtbmestres(Ijtbmestres ijtbmestres) {
		this.ijtbmestres = ijtbmestres;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTREFTURNO", nullable = false, length = 7)
	public Date getDtrefturno() {
		return this.dtrefturno;
	}

	public void setDtrefturno(Date dtrefturno) {
		this.dtrefturno = dtrefturno;
	}

	@Column(name = "CDTURNO", nullable = false, length = 6)
	public String getCdturno() {
		return this.cdturno;
	}

	public void setCdturno(String cdturno) {
		this.cdturno = cdturno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRITURNO", nullable = false, length = 7)
	public Date getDthriturno() {
		return this.dthriturno;
	}

	public void setDthriturno(Date dthriturno) {
		this.dthriturno = dthriturno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRFTURNO", nullable = false, length = 7)
	public Date getDthrfturno() {
		return this.dthrfturno;
	}

	public void setDthrfturno(Date dthrfturno) {
		this.dthrfturno = dthrfturno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRSISTEMA", nullable = false, length = 7)
	public Date getDthrsistema() {
		return this.dthrsistema;
	}

	public void setDthrsistema(Date dthrsistema) {
		this.dthrsistema = dthrsistema;
	}

}
