package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ijversaoproducao generated by hbm2java
 */
@Entity
@Table(name = "IJVERSAOPRODUCAO")
public class Ijversaoproducao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8136460767061600489L;
	private IjversaoproducaoId id;
	private Ijtbinj ijtbinj;
	private Ijtbpro ijtbpro;
	private String ativa;
	private Set<Ijopversaopro> ijopversaopros = new HashSet<Ijopversaopro>(0);

	public Ijversaoproducao() {
	}

	public Ijversaoproducao(IjversaoproducaoId id, Ijtbinj ijtbinj,
			Ijtbpro ijtbpro, String ativa) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijtbpro = ijtbpro;
		this.ativa = ativa;
	}

	public Ijversaoproducao(IjversaoproducaoId id, Ijtbinj ijtbinj,
			Ijtbpro ijtbpro, String ativa, Set<Ijopversaopro> ijopversaopros) {
		this.id = id;
		this.ijtbinj = ijtbinj;
		this.ijtbpro = ijtbpro;
		this.ativa = ativa;
		this.ijopversaopros = ijopversaopros;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "versaoproducao", column = @Column(name = "VERSAOPRODUCAO", nullable = false, length = 4)) })
	public IjversaoproducaoId getId() {
		return this.id;
	}

	public void setId(IjversaoproducaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDINJETORA", nullable = false, insertable = false, updatable = false)
	public Ijtbinj getIjtbinj() {
		return this.ijtbinj;
	}

	public void setIjtbinj(Ijtbinj ijtbinj) {
		this.ijtbinj = ijtbinj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDPRODUTO", nullable = false, insertable = false, updatable = false)
	public Ijtbpro getIjtbpro() {
		return this.ijtbpro;
	}

	public void setIjtbpro(Ijtbpro ijtbpro) {
		this.ijtbpro = ijtbpro;
	}

	@Column(name = "ATIVA", nullable = false, length = 1)
	public String getAtiva() {
		return this.ativa;
	}

	public void setAtiva(String ativa) {
		this.ativa = ativa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ijversaoproducao")
	public Set<Ijopversaopro> getIjopversaopros() {
		return this.ijopversaopros;
	}

	public void setIjopversaopros(Set<Ijopversaopro> ijopversaopros) {
		this.ijopversaopros = ijopversaopros;
	}

}
