package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijviewproducao generated by hbm2java
 */
@Entity
@Table(name = "IJVIEWPRODUCAO")
public class Ijviewproducao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6429699987342284550L;
	private IjviewproducaoId id;

	public Ijviewproducao() {
	}

	public Ijviewproducao(IjviewproducaoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", length = 25)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", length = 20)),
			@AttributeOverride(name = "dsproduto", column = @Column(name = "DSPRODUTO", length = 40)),
			@AttributeOverride(name = "cdmaquina", column = @Column(name = "CDMAQUINA", length = 6)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", length = 18)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", length = 4)),
			@AttributeOverride(name = "dtrefturno", column = @Column(name = "DTREFTURNO", length = 7)),
			@AttributeOverride(name = "cdturno", column = @Column(name = "CDTURNO", length = 6)),
			@AttributeOverride(name = "qtprodbruta", column = @Column(name = "QTPRODBRUTA", precision = 22, scale = 0)),
			@AttributeOverride(name = "qtprodrefugada", column = @Column(name = "QTPRODREFUGADA", precision = 22, scale = 0)),
			@AttributeOverride(name = "qthorastrabalhadas", column = @Column(name = "QTHORASTRABALHADAS", precision = 22, scale = 0)),
			@AttributeOverride(name = "tmpciclomedio", column = @Column(name = "TMPCICLOMEDIO", precision = 22, scale = 0)) })
	public IjviewproducaoId getId() {
		return this.id;
	}

	public void setId(IjviewproducaoId id) {
		this.id = id;
	}

}
