package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ijviewparadas generated by hbm2java
 */
@Entity
@Table(name = "IJVIEWPARADAS")
public class Ijviewparadas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1609037155068582861L;
	private IjviewparadasId id;

	public Ijviewparadas() {
	}

	public Ijviewparadas(IjviewparadasId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrop", column = @Column(name = "NROP", nullable = false, length = 25)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "dsproduto", column = @Column(name = "DSPRODUTO", length = 40)),
			@AttributeOverride(name = "cdmaquina", column = @Column(name = "CDMAQUINA", nullable = false, length = 8)),
			@AttributeOverride(name = "cdmolde", column = @Column(name = "CDMOLDE", nullable = false, length = 18)),
			@AttributeOverride(name = "cdestrutura", column = @Column(name = "CDESTRUTURA", nullable = false, length = 4)),
			@AttributeOverride(name = "dtturnoref", column = @Column(name = "DTTURNOREF", nullable = false, length = 7)),
			@AttributeOverride(name = "cdturno", column = @Column(name = "CDTURNO", nullable = false, length = 6)),
			@AttributeOverride(name = "cdparada", column = @Column(name = "CDPARADA", nullable = false, length = 6)),
			@AttributeOverride(name = "dsparada", column = @Column(name = "DSPARADA", length = 40)),
			@AttributeOverride(name = "cdarearesp", column = @Column(name = "CDAREARESP", nullable = false, length = 6)),
			@AttributeOverride(name = "dsarearesp", column = @Column(name = "DSAREARESP", length = 40)),
			@AttributeOverride(name = "tmpparada", column = @Column(name = "TMPPARADA", precision = 22, scale = 0)),
			@AttributeOverride(name = "qtdparadas", column = @Column(name = "QTDPARADAS", precision = 22, scale = 0)) })
	public IjviewparadasId getId() {
		return this.id;
	}

	public void setId(IjviewparadasId id) {
		this.id = id;
	}

}
