package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Importacao001 generated by hbm2java
 */
@Entity
@Table(name = "IMPORTACAO_001")
public class Importacao001 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4984324175564410708L;
	private String nrop;
	private String cdproduto;
	private Double qtdplan;
	private String cdmolde;
	private String cdmaqreal;
	private String cdmaqaltern;
	private String cliente;
	private Date dtentrega;
	private BigDecimal opagrupada;
	private Double tmpsetup;

	public Importacao001() {
	}

	public Importacao001(String nrop) {
		this.nrop = nrop;
	}

	public Importacao001(String nrop, String cdproduto, Double qtdplan,
			String cdmolde, String cdmaqreal, String cdmaqaltern,
			String cliente, Date dtentrega, BigDecimal opagrupada,
			Double tmpsetup) {
		this.nrop = nrop;
		this.cdproduto = cdproduto;
		this.qtdplan = qtdplan;
		this.cdmolde = cdmolde;
		this.cdmaqreal = cdmaqreal;
		this.cdmaqaltern = cdmaqaltern;
		this.cliente = cliente;
		this.dtentrega = dtentrega;
		this.opagrupada = opagrupada;
		this.tmpsetup = tmpsetup;
	}

	@Id
	@Column(name = "NROP", unique = true, nullable = false, length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "CDPRODUTO", length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "QTDPLAN", precision = 126, scale = 0)
	public Double getQtdplan() {
		return this.qtdplan;
	}

	public void setQtdplan(Double qtdplan) {
		this.qtdplan = qtdplan;
	}

	@Column(name = "CDMOLDE", length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "CDMAQREAL", length = 6)
	public String getCdmaqreal() {
		return this.cdmaqreal;
	}

	public void setCdmaqreal(String cdmaqreal) {
		this.cdmaqreal = cdmaqreal;
	}

	@Column(name = "CDMAQALTERN", length = 6)
	public String getCdmaqaltern() {
		return this.cdmaqaltern;
	}

	public void setCdmaqaltern(String cdmaqaltern) {
		this.cdmaqaltern = cdmaqaltern;
	}

	@Column(name = "CLIENTE", length = 40)
	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTENTREGA", length = 7)
	public Date getDtentrega() {
		return this.dtentrega;
	}

	public void setDtentrega(Date dtentrega) {
		this.dtentrega = dtentrega;
	}

	@Column(name = "OPAGRUPADA", precision = 22, scale = 0)
	public BigDecimal getOpagrupada() {
		return this.opagrupada;
	}

	public void setOpagrupada(BigDecimal opagrupada) {
		this.opagrupada = opagrupada;
	}

	@Column(name = "TMPSETUP", precision = 126, scale = 0)
	public Double getTmpsetup() {
		return this.tmpsetup;
	}

	public void setTmpsetup(Double tmpsetup) {
		this.tmpsetup = tmpsetup;
	}

}
