package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Importacao003Id generated by hbm2java
 */
@Embeddable
public class Importacao003Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2264355962382134066L;
	private String nrop;
	private String cdproduto;
	private Double qtplanejada;
	private String cdinjetora;
	private String cdmolde;
	private String cdestrutura;
	private String cdcliente;
	private Date dtprevini;
	private String hrprevini;
	private Date dtentrega;
	private Character tpordemproducao;
	private Double eficrea;
	private BigDecimal numsmnentrega;

	public Importacao003Id() {
	}

	public Importacao003Id(String nrop, String cdproduto, Double qtplanejada,
			String cdinjetora, String cdmolde, String cdestrutura,
			String cdcliente, Date dtprevini, String hrprevini, Date dtentrega,
			Character tpordemproducao, Double eficrea, BigDecimal numsmnentrega) {
		this.nrop = nrop;
		this.cdproduto = cdproduto;
		this.qtplanejada = qtplanejada;
		this.cdinjetora = cdinjetora;
		this.cdmolde = cdmolde;
		this.cdestrutura = cdestrutura;
		this.cdcliente = cdcliente;
		this.dtprevini = dtprevini;
		this.hrprevini = hrprevini;
		this.dtentrega = dtentrega;
		this.tpordemproducao = tpordemproducao;
		this.eficrea = eficrea;
		this.numsmnentrega = numsmnentrega;
	}

	@Column(name = "NROP", length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "CDPRODUTO", length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "QTPLANEJADA", precision = 126, scale = 0)
	public Double getQtplanejada() {
		return this.qtplanejada;
	}

	public void setQtplanejada(Double qtplanejada) {
		this.qtplanejada = qtplanejada;
	}

	@Column(name = "CDINJETORA", length = 6)
	public String getCdinjetora() {
		return this.cdinjetora;
	}

	public void setCdinjetora(String cdinjetora) {
		this.cdinjetora = cdinjetora;
	}

	@Column(name = "CDMOLDE", length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "CDESTRUTURA", length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Column(name = "CDCLIENTE", length = 6)
	public String getCdcliente() {
		return this.cdcliente;
	}

	public void setCdcliente(String cdcliente) {
		this.cdcliente = cdcliente;
	}

	@Column(name = "DTPREVINI", length = 7)
	public Date getDtprevini() {
		return this.dtprevini;
	}

	public void setDtprevini(Date dtprevini) {
		this.dtprevini = dtprevini;
	}

	@Column(name = "HRPREVINI", length = 8)
	public String getHrprevini() {
		return this.hrprevini;
	}

	public void setHrprevini(String hrprevini) {
		this.hrprevini = hrprevini;
	}

	@Column(name = "DTENTREGA", length = 7)
	public Date getDtentrega() {
		return this.dtentrega;
	}

	public void setDtentrega(Date dtentrega) {
		this.dtentrega = dtentrega;
	}

	@Column(name = "TPORDEMPRODUCAO", length = 1)
	public Character getTpordemproducao() {
		return this.tpordemproducao;
	}

	public void setTpordemproducao(Character tpordemproducao) {
		this.tpordemproducao = tpordemproducao;
	}

	@Column(name = "EFICREA", precision = 126, scale = 0)
	public Double getEficrea() {
		return this.eficrea;
	}

	public void setEficrea(Double eficrea) {
		this.eficrea = eficrea;
	}

	@Column(name = "NUMSMNENTREGA", precision = 22, scale = 0)
	public BigDecimal getNumsmnentrega() {
		return this.numsmnentrega;
	}

	public void setNumsmnentrega(BigDecimal numsmnentrega) {
		this.numsmnentrega = numsmnentrega;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Importacao003Id))
			return false;
		Importacao003Id castOther = (Importacao003Id) other;

		return ((this.getNrop() == castOther.getNrop()) || (this.getNrop() != null
				&& castOther.getNrop() != null && this.getNrop().equals(
				castOther.getNrop())))
				&& ((this.getCdproduto() == castOther.getCdproduto()) || (this
						.getCdproduto() != null
						&& castOther.getCdproduto() != null && this
						.getCdproduto().equals(castOther.getCdproduto())))
				&& ((this.getQtplanejada() == castOther.getQtplanejada()) || (this
						.getQtplanejada() != null
						&& castOther.getQtplanejada() != null && this
						.getQtplanejada().equals(castOther.getQtplanejada())))
				&& ((this.getCdinjetora() == castOther.getCdinjetora()) || (this
						.getCdinjetora() != null
						&& castOther.getCdinjetora() != null && this
						.getCdinjetora().equals(castOther.getCdinjetora())))
				&& ((this.getCdmolde() == castOther.getCdmolde()) || (this
						.getCdmolde() != null && castOther.getCdmolde() != null && this
						.getCdmolde().equals(castOther.getCdmolde())))
				&& ((this.getCdestrutura() == castOther.getCdestrutura()) || (this
						.getCdestrutura() != null
						&& castOther.getCdestrutura() != null && this
						.getCdestrutura().equals(castOther.getCdestrutura())))
				&& ((this.getCdcliente() == castOther.getCdcliente()) || (this
						.getCdcliente() != null
						&& castOther.getCdcliente() != null && this
						.getCdcliente().equals(castOther.getCdcliente())))
				&& ((this.getDtprevini() == castOther.getDtprevini()) || (this
						.getDtprevini() != null
						&& castOther.getDtprevini() != null && this
						.getDtprevini().equals(castOther.getDtprevini())))
				&& ((this.getHrprevini() == castOther.getHrprevini()) || (this
						.getHrprevini() != null
						&& castOther.getHrprevini() != null && this
						.getHrprevini().equals(castOther.getHrprevini())))
				&& ((this.getDtentrega() == castOther.getDtentrega()) || (this
						.getDtentrega() != null
						&& castOther.getDtentrega() != null && this
						.getDtentrega().equals(castOther.getDtentrega())))
				&& ((this.getTpordemproducao() == castOther
						.getTpordemproducao()) || (this.getTpordemproducao() != null
						&& castOther.getTpordemproducao() != null && this
						.getTpordemproducao().equals(
								castOther.getTpordemproducao())))
				&& ((this.getEficrea() == castOther.getEficrea()) || (this
						.getEficrea() != null && castOther.getEficrea() != null && this
						.getEficrea().equals(castOther.getEficrea())))
				&& ((this.getNumsmnentrega() == castOther.getNumsmnentrega()) || (this
						.getNumsmnentrega() != null
						&& castOther.getNumsmnentrega() != null && this
						.getNumsmnentrega()
						.equals(castOther.getNumsmnentrega())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNrop() == null ? 0 : this.getNrop().hashCode());
		result = 37 * result
				+ (getCdproduto() == null ? 0 : this.getCdproduto().hashCode());
		result = 37
				* result
				+ (getQtplanejada() == null ? 0 : this.getQtplanejada()
						.hashCode());
		result = 37
				* result
				+ (getCdinjetora() == null ? 0 : this.getCdinjetora()
						.hashCode());
		result = 37 * result
				+ (getCdmolde() == null ? 0 : this.getCdmolde().hashCode());
		result = 37
				* result
				+ (getCdestrutura() == null ? 0 : this.getCdestrutura()
						.hashCode());
		result = 37 * result
				+ (getCdcliente() == null ? 0 : this.getCdcliente().hashCode());
		result = 37 * result
				+ (getDtprevini() == null ? 0 : this.getDtprevini().hashCode());
		result = 37 * result
				+ (getHrprevini() == null ? 0 : this.getHrprevini().hashCode());
		result = 37 * result
				+ (getDtentrega() == null ? 0 : this.getDtentrega().hashCode());
		result = 37
				* result
				+ (getTpordemproducao() == null ? 0 : this.getTpordemproducao()
						.hashCode());
		result = 37 * result
				+ (getEficrea() == null ? 0 : this.getEficrea().hashCode());
		result = 37
				* result
				+ (getNumsmnentrega() == null ? 0 : this.getNumsmnentrega()
						.hashCode());
		return result;
	}

}
