package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Importacao005 generated by hbm2java
 */
@Entity
@Table(name = "IMPORTACAO_005")
public class Importacao005 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6322877082797864724L;
	private Importacao005Id id;
	private String ordemProducao;
	private String item;
	private String tipProduto;
	private double tempoCiclo;
	private String prioridade;
	private double qtdPlanejada;
	private Date datEntrega;
	private String statusRegistro;
	private String observacao;

	public Importacao005() {
	}

	public Importacao005(Importacao005Id id, String ordemProducao, String item,
			String tipProduto, double tempoCiclo, String prioridade,
			double qtdPlanejada, Date datEntrega, String statusRegistro) {
		this.id = id;
		this.ordemProducao = ordemProducao;
		this.item = item;
		this.tipProduto = tipProduto;
		this.tempoCiclo = tempoCiclo;
		this.prioridade = prioridade;
		this.qtdPlanejada = qtdPlanejada;
		this.datEntrega = datEntrega;
		this.statusRegistro = statusRegistro;
	}

	public Importacao005(Importacao005Id id, String ordemProducao, String item,
			String tipProduto, double tempoCiclo, String prioridade,
			double qtdPlanejada, Date datEntrega, String statusRegistro,
			String observacao) {
		this.id = id;
		this.ordemProducao = ordemProducao;
		this.item = item;
		this.tipProduto = tipProduto;
		this.tempoCiclo = tempoCiclo;
		this.prioridade = prioridade;
		this.qtdPlanejada = qtdPlanejada;
		this.datEntrega = datEntrega;
		this.statusRegistro = statusRegistro;
		this.observacao = observacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "registro", column = @Column(name = "REGISTRO", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "empresa", column = @Column(name = "EMPRESA", nullable = false, length = 2)) })
	public Importacao005Id getId() {
		return this.id;
	}

	public void setId(Importacao005Id id) {
		this.id = id;
	}

	@Column(name = "ORDEM_PRODUCAO", nullable = false, length = 10)
	public String getOrdemProducao() {
		return this.ordemProducao;
	}

	public void setOrdemProducao(String ordemProducao) {
		this.ordemProducao = ordemProducao;
	}

	@Column(name = "ITEM", nullable = false, length = 15)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "TIP_PRODUTO", nullable = false, length = 1)
	public String getTipProduto() {
		return this.tipProduto;
	}

	public void setTipProduto(String tipProduto) {
		this.tipProduto = tipProduto;
	}

	@Column(name = "TEMPO_CICLO", nullable = false, precision = 126, scale = 0)
	public double getTempoCiclo() {
		return this.tempoCiclo;
	}

	public void setTempoCiclo(double tempoCiclo) {
		this.tempoCiclo = tempoCiclo;
	}

	@Column(name = "PRIORIDADE", nullable = false, length = 1)
	public String getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(String prioridade) {
		this.prioridade = prioridade;
	}

	@Column(name = "QTD_PLANEJADA", nullable = false, precision = 126, scale = 0)
	public double getQtdPlanejada() {
		return this.qtdPlanejada;
	}

	public void setQtdPlanejada(double qtdPlanejada) {
		this.qtdPlanejada = qtdPlanejada;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DAT_ENTREGA", nullable = false, length = 7)
	public Date getDatEntrega() {
		return this.datEntrega;
	}

	public void setDatEntrega(Date datEntrega) {
		this.datEntrega = datEntrega;
	}

	@Column(name = "STATUS_REGISTRO", nullable = false, length = 1)
	public String getStatusRegistro() {
		return this.statusRegistro;
	}

	public void setStatusRegistro(String statusRegistro) {
		this.statusRegistro = statusRegistro;
	}

	@Column(name = "OBSERVACAO", length = 2)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

}
