package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Importacao002 generated by hbm2java
 */
@Entity
@Table(name = "IMPORTACAO_002")
public class Importacao002 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1293472519631696235L;
	private Importacao002Id id;
	private double qtProgramada;
	private double vlTempoPadrao;
	private BigDecimal idStatusOp;
	private String cdFerramenta;
	private Date dtProducao;
	private Date dtCriacaoOp;

	public Importacao002() {
	}

	public Importacao002(Importacao002Id id, double qtProgramada,
			double vlTempoPadrao, BigDecimal idStatusOp, String cdFerramenta,
			Date dtProducao, Date dtCriacaoOp) {
		this.id = id;
		this.qtProgramada = qtProgramada;
		this.vlTempoPadrao = vlTempoPadrao;
		this.idStatusOp = idStatusOp;
		this.cdFerramenta = cdFerramenta;
		this.dtProducao = dtProducao;
		this.dtCriacaoOp = dtCriacaoOp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdOrdemProducao", column = @Column(name = "CD_ORDEM_PRODUCAO", nullable = false, length = 16)),
			@AttributeOverride(name = "cdCentroTrabalho", column = @Column(name = "CD_CENTRO_TRABALHO", nullable = false, length = 8)),
			@AttributeOverride(name = "cdMaterial", column = @Column(name = "CD_MATERIAL", nullable = false, length = 18)) })
	public Importacao002Id getId() {
		return this.id;
	}

	public void setId(Importacao002Id id) {
		this.id = id;
	}

	@Column(name = "QT_PROGRAMADA", nullable = false, precision = 126, scale = 0)
	public double getQtProgramada() {
		return this.qtProgramada;
	}

	public void setQtProgramada(double qtProgramada) {
		this.qtProgramada = qtProgramada;
	}

	@Column(name = "VL_TEMPO_PADRAO", nullable = false, precision = 126, scale = 0)
	public double getVlTempoPadrao() {
		return this.vlTempoPadrao;
	}

	public void setVlTempoPadrao(double vlTempoPadrao) {
		this.vlTempoPadrao = vlTempoPadrao;
	}

	@Column(name = "ID_STATUS_OP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdStatusOp() {
		return this.idStatusOp;
	}

	public void setIdStatusOp(BigDecimal idStatusOp) {
		this.idStatusOp = idStatusOp;
	}

	@Column(name = "CD_FERRAMENTA", nullable = false, length = 18)
	public String getCdFerramenta() {
		return this.cdFerramenta;
	}

	public void setCdFerramenta(String cdFerramenta) {
		this.cdFerramenta = cdFerramenta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_PRODUCAO", nullable = false, length = 7)
	public Date getDtProducao() {
		return this.dtProducao;
	}

	public void setDtProducao(Date dtProducao) {
		this.dtProducao = dtProducao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_CRIACAO_OP", nullable = false, length = 7)
	public Date getDtCriacaoOp() {
		return this.dtCriacaoOp;
	}

	public void setDtCriacaoOp(Date dtCriacaoOp) {
		this.dtCriacaoOp = dtCriacaoOp;
	}

}
