package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Importacao002Id generated by hbm2java
 */
@Embeddable
public class Importacao002Id implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1454978623259908790L;
	private String cdOrdemProducao;
	private String cdCentroTrabalho;
	private String cdMaterial;

	public Importacao002Id() {
	}

	public Importacao002Id(String cdOrdemProducao, String cdCentroTrabalho,
			String cdMaterial) {
		this.cdOrdemProducao = cdOrdemProducao;
		this.cdCentroTrabalho = cdCentroTrabalho;
		this.cdMaterial = cdMaterial;
	}

	@Column(name = "CD_ORDEM_PRODUCAO", nullable = false, length = 16)
	public String getCdOrdemProducao() {
		return this.cdOrdemProducao;
	}

	public void setCdOrdemProducao(String cdOrdemProducao) {
		this.cdOrdemProducao = cdOrdemProducao;
	}

	@Column(name = "CD_CENTRO_TRABALHO", nullable = false, length = 8)
	public String getCdCentroTrabalho() {
		return this.cdCentroTrabalho;
	}

	public void setCdCentroTrabalho(String cdCentroTrabalho) {
		this.cdCentroTrabalho = cdCentroTrabalho;
	}

	@Column(name = "CD_MATERIAL", nullable = false, length = 18)
	public String getCdMaterial() {
		return this.cdMaterial;
	}

	public void setCdMaterial(String cdMaterial) {
		this.cdMaterial = cdMaterial;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Importacao002Id))
			return false;
		Importacao002Id castOther = (Importacao002Id) other;

		return ((this.getCdOrdemProducao() == castOther.getCdOrdemProducao()) || (this
				.getCdOrdemProducao() != null
				&& castOther.getCdOrdemProducao() != null && this
				.getCdOrdemProducao().equals(castOther.getCdOrdemProducao())))
				&& ((this.getCdCentroTrabalho() == castOther
						.getCdCentroTrabalho()) || (this.getCdCentroTrabalho() != null
						&& castOther.getCdCentroTrabalho() != null && this
						.getCdCentroTrabalho().equals(
								castOther.getCdCentroTrabalho())))
				&& ((this.getCdMaterial() == castOther.getCdMaterial()) || (this
						.getCdMaterial() != null
						&& castOther.getCdMaterial() != null && this
						.getCdMaterial().equals(castOther.getCdMaterial())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdOrdemProducao() == null ? 0 : this.getCdOrdemProducao()
						.hashCode());
		result = 37
				* result
				+ (getCdCentroTrabalho() == null ? 0 : this
						.getCdCentroTrabalho().hashCode());
		result = 37
				* result
				+ (getCdMaterial() == null ? 0 : this.getCdMaterial()
						.hashCode());
		return result;
	}

}
