package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Viewgrafosexec generated by hbm2java
 */
@Entity
@Table(name = "VIEWGRAFOSEXEC")
public class Viewgrafosexec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5013687399251303608L;
	private ViewgrafosexecId id;

	public Viewgrafosexec() {
	}

	public Viewgrafosexec(ViewgrafosexecId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ano", column = @Column(name = "ANO", length = 4)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", length = 2)),
			@AttributeOverride(name = "tpmanutencao", column = @Column(name = "TPMANUTENCAO", length = 1)),
			@AttributeOverride(name = "tprecurso", column = @Column(name = "TPRECURSO", length = 2)),
			@AttributeOverride(name = "idrecurso", column = @Column(name = "IDRECURSO", length = 6)),
			@AttributeOverride(name = "qtdhrs", column = @Column(name = "QTDHRS", precision = 22, scale = 0)) })
	public ViewgrafosexecId getId() {
		return this.id;
	}

	public void setId(ViewgrafosexecId id) {
		this.id = id;
	}

}
