package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Viewgrafparmtbf generated by hbm2java
 */
@Entity
@Table(name = "VIEWGRAFPARMTBF")
public class Viewgrafparmtbf implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2162837757264293198L;
	private ViewgrafparmtbfId id;

	public Viewgrafparmtbf() {
	}

	public Viewgrafparmtbf(ViewgrafparmtbfId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ano", column = @Column(name = "ANO", length = 4)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", length = 2)),
			@AttributeOverride(name = "cdinjetora", column = @Column(name = "CDINJETORA", nullable = false, length = 6)),
			@AttributeOverride(name = "qtdhrs", column = @Column(name = "QTDHRS", precision = 22, scale = 0)),
			@AttributeOverride(name = "qtdocorr", column = @Column(name = "QTDOCORR", precision = 22, scale = 0)) })
	public ViewgrafparmtbfId getId() {
		return this.id;
	}

	public void setId(ViewgrafparmtbfId id) {
		this.id = id;
	}

}
