package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Viewgrafostec generated by hbm2java
 */
@Entity
@Table(name = "VIEWGRAFOSTEC")
public class Viewgrafostec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3092776224436670608L;
	private ViewgrafostecId id;

	public Viewgrafostec() {
	}

	public Viewgrafostec(ViewgrafostecId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ano", column = @Column(name = "ANO", length = 4)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", length = 2)),
			@AttributeOverride(name = "tpmanutencao", column = @Column(name = "TPMANUTENCAO", length = 1)),
			@AttributeOverride(name = "tprecurso", column = @Column(name = "TPRECURSO", length = 2)),
			@AttributeOverride(name = "idrecurso", column = @Column(name = "IDRECURSO", length = 6)),
			@AttributeOverride(name = "cdclasstarefa", column = @Column(name = "CDCLASSTAREFA", length = 6)),
			@AttributeOverride(name = "cdusuario", column = @Column(name = "CDUSUARIO", length = 6)),
			@AttributeOverride(name = "nmusuario", column = @Column(name = "NMUSUARIO", length = 40)),
			@AttributeOverride(name = "qtdhrs", column = @Column(name = "QTDHRS", precision = 22, scale = 0)),
			@AttributeOverride(name = "qtdtarefas", column = @Column(name = "QTDTAREFAS", precision = 22, scale = 0)) })
	public ViewgrafostecId getId() {
		return this.id;
	}

	public void setId(ViewgrafostecId id) {
		this.id = id;
	}

}
