package idw.model.pojos.injet;

// Generated 28/08/2012 14:05:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Viewultmanutexec generated by hbm2java
 */
@Entity
@Table(name = "VIEWULTMANUTEXEC")
public class Viewultmanutexec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1293715526978129376L;
	private ViewultmanutexecId id;

	public Viewultmanutexec() {
	}

	public Viewultmanutexec(ViewultmanutexecId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nros", column = @Column(name = "NROS", nullable = false, length = 12)),
			@AttributeOverride(name = "dtfimmanut", column = @Column(name = "DTFIMMANUT", length = 7)),
			@AttributeOverride(name = "idrecurso", column = @Column(name = "IDRECURSO", nullable = false, length = 6)),
			@AttributeOverride(name = "tprecurso", column = @Column(name = "TPRECURSO", nullable = false, length = 2)),
			@AttributeOverride(name = "idchklst", column = @Column(name = "IDCHKLST", length = 15)) })
	public ViewultmanutexecId getId() {
		return this.id;
	}

	public void setId(ViewultmanutexecId id) {
		this.id = id;
	}

}
