package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwCalavuTemplate;


/**
 * DwCalavu generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_calavu")
public class DwCalavu extends DwCalavuTemplate implements java.io.Serializable {

	private long idCalavu;
	private DwCal dwCal;
	private DwTurno dwTurno;
	private DwCalsem dwCalsem;
	private Date dtAvulso;
	private BigDecimal hrinicial;
	private BigDecimal hrFinal;
	private String hrInicialGui;
	private String hrFinalGui;
	private BigDecimal segTempocalendario;
	private BigDecimal segTempocalsempeso;
	private BigDecimal segToleranciapre;
	private BigDecimal segToleranciapos;
	private Byte tpDtreferencia;
	private Boolean isCalsemdesativado;
	private Boolean isInicioturno;
	private Boolean isFimturno;
	private Byte tpCalavu;

	public DwCalavu() {
	}

	public DwCalavu(long idCalavu, DwCal dwCal, DwTurno dwTurno) {
		this.idCalavu = idCalavu;
		this.dwCal = dwCal;
		this.dwTurno = dwTurno;
	}

	public DwCalavu(long idCalavu, DwCal dwCal, DwTurno dwTurno,
			DwCalsem dwCalsem, Date dtAvulso, BigDecimal hrinicial,
			BigDecimal hrFinal, String hrInicialGui, String hrFinalGui,
			BigDecimal segTempocalendario, BigDecimal segTempocalsempeso,
			BigDecimal segToleranciapre, BigDecimal segToleranciapos,
			Byte tpDtreferencia, Boolean isCalsemdesativado,
			Boolean isInicioturno, Boolean isFimturno, Byte tpCalavu) {
		this.idCalavu = idCalavu;
		this.dwCal = dwCal;
		this.dwTurno = dwTurno;
		this.dwCalsem = dwCalsem;
		this.dtAvulso = dtAvulso;
		this.hrinicial = hrinicial;
		this.hrFinal = hrFinal;
		this.hrInicialGui = hrInicialGui;
		this.hrFinalGui = hrFinalGui;
		this.segTempocalendario = segTempocalendario;
		this.segTempocalsempeso = segTempocalsempeso;
		this.segToleranciapre = segToleranciapre;
		this.segToleranciapos = segToleranciapos;
		this.tpDtreferencia = tpDtreferencia;
		this.isCalsemdesativado = isCalsemdesativado;
		this.isInicioturno = isInicioturno;
		this.isFimturno = isFimturno;
		this.tpCalavu = tpCalavu;
	}

	@Id	
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CALAVU_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CALAVU_SEQ", sequenceName = "DW_CALAVU_SEQ")
	@Column(name = "id_calavu", nullable = false)
	public long getIdCalavu() {
		return this.idCalavu;
	}

	public void setIdCalavu(long idCalavu) {
		this.idCalavu = idCalavu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cal", nullable = false)
	public DwCal getDwCal() {
		return this.dwCal;
	}

	public void setDwCal(DwCal dwCal) {
		this.dwCal = dwCal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_turno", nullable = false)
	public DwTurno getDwTurno() {
		return this.dwTurno;
	}

	public void setDwTurno(DwTurno dwTurno) {
		this.dwTurno = dwTurno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_calsem")
	public DwCalsem getDwCalsem() {
		return this.dwCalsem;
	}

	public void setDwCalsem(DwCalsem dwCalsem) {
		this.dwCalsem = dwCalsem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_avulso", length = 23)
	public Date getDtAvulso() {
		return this.dtAvulso;
	}

	public void setDtAvulso(Date dtAvulso) {
		this.dtAvulso = dtAvulso;
	}

	@Column(name = "hrinicial", precision = 20, scale = 10)
	public BigDecimal getHrinicial() {
		return this.hrinicial;
	}

	public void setHrinicial(BigDecimal hrinicial) {
		this.hrinicial = hrinicial;
	}

	@Column(name = "hrFinal", precision = 20, scale = 10)
	public BigDecimal getHrFinal() {
		return this.hrFinal;
	}

	public void setHrFinal(BigDecimal hrFinal) {
		this.hrFinal = hrFinal;
	}

	@Column(name = "hrInicialGUI", length = 40)
	public String getHrInicialGui() {
		return this.hrInicialGui;
	}

	public void setHrInicialGui(String hrInicialGui) {
		this.hrInicialGui = hrInicialGui;
	}

	@Column(name = "hrFinalGUI", length = 40)
	public String getHrFinalGui() {
		return this.hrFinalGui;
	}

	public void setHrFinalGui(String hrFinalGui) {
		this.hrFinalGui = hrFinalGui;
	}

	@Column(name = "seg_tempocalendario", precision = 20, scale = 10)
	public BigDecimal getSegTempocalendario() {
		return this.segTempocalendario;
	}

	public void setSegTempocalendario(BigDecimal segTempocalendario) {
		this.segTempocalendario = segTempocalendario;
	}

	@Column(name = "seg_tempocalsempeso", precision = 20, scale = 10)
	public BigDecimal getSegTempocalsempeso() {
		return this.segTempocalsempeso;
	}

	public void setSegTempocalsempeso(BigDecimal segTempocalsempeso) {
		this.segTempocalsempeso = segTempocalsempeso;
	}

	@Column(name = "seg_toleranciapre", precision = 20, scale = 10)
	public BigDecimal getSegToleranciapre() {
		return this.segToleranciapre;
	}

	public void setSegToleranciapre(BigDecimal segToleranciapre) {
		this.segToleranciapre = segToleranciapre;
	}

	@Column(name = "seg_toleranciapos", precision = 20, scale = 10)
	public BigDecimal getSegToleranciapos() {
		return this.segToleranciapos;
	}

	public void setSegToleranciapos(BigDecimal segToleranciapos) {
		this.segToleranciapos = segToleranciapos;
	}

	@Column(name = "tp_dtreferencia")
	public Byte getTpDtreferencia() {
		return this.tpDtreferencia;
	}

	public void setTpDtreferencia(Byte tpDtreferencia) {
		this.tpDtreferencia = tpDtreferencia;
	}

	@Column(name = "is_calsemdesativado")
	public Boolean getIsCalsemdesativado() {
		return this.isCalsemdesativado;
	}

	public void setIsCalsemdesativado(Boolean isCalsemdesativado) {
		this.isCalsemdesativado = isCalsemdesativado;
	}

	@Column(name = "is_inicioturno")
	public Boolean getIsInicioturno() {
		return this.isInicioturno;
	}

	public void setIsInicioturno(Boolean isInicioturno) {
		this.isInicioturno = isInicioturno;
	}

	@Column(name = "is_fimturno")
	public Boolean getIsFimturno() {
		return this.isFimturno;
	}

	public void setIsFimturno(Boolean isFimturno) {
		this.isFimturno = isFimturno;
	}

	@Column(name = "tp_calavu")
	public Byte getTpCalavu() {
		return this.tpCalavu;
	}

	public void setTpCalavu(Byte tpCalavu) {
		this.tpCalavu = tpCalavu;
	}

}
