package idw.model.pojos;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwCalptTemplate;


/**
 * DwCalpt generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_calpt")
public class DwCalpt extends DwCalptTemplate implements java.io.Serializable {

	private long idCalpt;
	private DwCal dwCal;
	private OmPt omPt;
	private Date dthrStativo;
	private Byte stAtivo;
	private Date dthrivalidade;

	public DwCalpt() {
	}

	public DwCalpt(long idCalpt, DwCal dwCal, OmPt omPt) {
		this.idCalpt = idCalpt;
		this.dwCal = dwCal;
		this.omPt = omPt;
	}

	public DwCalpt(long idCalpt, DwCal dwCal, OmPt omPt, Date dthrStativo,
			Byte stAtivo, Date dthrivalidade) {
		this.idCalpt = idCalpt;
		this.dwCal = dwCal;
		this.omPt = omPt;
		this.dthrStativo = dthrStativo;
		this.stAtivo = stAtivo;
		this.dthrivalidade = dthrivalidade;
	}

	@Id	
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CALPT_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CALPT_SEQ", sequenceName = "DW_CALPT_SEQ")
	@Column(name = "id_calpt", nullable = false)
	public long getIdCalpt() {
		return this.idCalpt;
	}

	public void setIdCalpt(long idCalpt) {
		this.idCalpt = idCalpt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cal", nullable = false)
	public DwCal getDwCal() {
		return this.dwCal;
	}

	public void setDwCal(DwCal dwCal) {
		this.dwCal = dwCal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pt", nullable = false)
	public OmPt getOmPt() {
		return this.omPt;
	}

	public void setOmPt(OmPt omPt) {
		this.omPt = omPt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_stativo", length = 23)
	public Date getDthrStativo() {
		return this.dthrStativo;
	}

	public void setDthrStativo(Date dthrStativo) {
		this.dthrStativo = dthrStativo;
	}

	@Column(name = "st_ativo", length = 1)
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthrivalidade", length = 23)
	public Date getDthrivalidade() {
		return this.dthrivalidade;
	}

	public void setDthrivalidade(Date dthrivalidade) {
		this.dthrivalidade = dthrivalidade;
	}

}
