package idw.model.pojos;
// Generated 05/02/2016 09:02:37 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DwConsolvaritmologcau generated by hbm2java
 */
@Entity
@Table(name = "dw_consolvaritmologcau")
public class DwConsolvaritmologcau implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idConsolvartimologcau;
	private Date dthrVaritmo;
	private OmUsr omUsr;
	private DwTRitmo dwTRitmo;
	private DwConsolvaritmolog dwConsolvaritmolog;

	public DwConsolvaritmologcau() {
	}

	public DwConsolvaritmologcau(Long idConsolvartimologcau, OmUsr omUsr, DwConsolvaritmolog dwConsolvaritmolog) {
		this.idConsolvartimologcau = idConsolvartimologcau;
		this.omUsr = omUsr;
		this.dwConsolvaritmolog = dwConsolvaritmolog;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CONSOLVARITMOLOGCAU_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CONSOLVARITMOLOGCAU_SEQ", sequenceName = "DW_CONSOLVARITMOLOGCAU_SEQ")
	@Column(name = "id_consolvartimologcau", unique = true, nullable = false)
	public Long getIdConsolvartimologcau() {
		return this.idConsolvartimologcau;
	}

	public void setIdConsolvartimologcau(Long idConsolvartimologcau) {
		this.idConsolvartimologcau = idConsolvartimologcau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usr", nullable = false)
	public OmUsr getOmUsr() {
		return this.omUsr;
	}

	public void setOmUsr(OmUsr omUsr) {
		this.omUsr = omUsr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_consolvaritmolog", nullable = false)
	public DwConsolvaritmolog getDwConsolvaritmolog() {
		return this.dwConsolvaritmolog;
	}

	public void setDwConsolvaritmolog(DwConsolvaritmolog dwConsolvaritmolog) {
		this.dwConsolvaritmolog = dwConsolvaritmolog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tritmo", nullable = false)
	public DwTRitmo getDwTRitmo() {
		return this.dwTRitmo;
	}

	public void setDwTRitmo(DwTRitmo dwTRitmo) {
		this.dwTRitmo = dwTRitmo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_VARITMO")
	public Date getDthrVaritmo() {
		return dthrVaritmo;
	}

	public void setDthrVaritmo(Date dthrVaritmo) {
		this.dthrVaritmo = dthrVaritmo;
	}
}
