package idw.model.pojos;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DwConsolpamo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "DW_CONSOLPAMO")
public class DwConsolpamo implements java.io.Serializable {

	private Long idConsolpamo;
	private DwConsolmo dwConsolmo;
	private DwConsolpa dwConsolpa;
	private BigDecimal qtAutoTempoparadaCp;
	private BigDecimal qtAutoTempoparadaSp;
	private BigDecimal qtManuTempoparadaCp;
	private BigDecimal qtManuTempoparadaSp;
	private BigDecimal segAutoTempoparadaCp;
	private BigDecimal segAutoTempoparadaSp;
	private BigDecimal segManuTempoparadaCp;
	private BigDecimal segManuTempoparadaSp;
	private BigDecimal segAutoTempoparadaCpVr; //
	private BigDecimal segAutoTempoparadaSpVr;
	private BigDecimal segManuTempoparadaCpVr;
	private BigDecimal segManuTempoparadaSpVr;
	private BigDecimal qtAutoOcoparadaCpVr;
	private BigDecimal qtAutoOcoparadaSpVr;
	private BigDecimal qtManuOcoparadaCpVr;
	private BigDecimal qtManuOcoparadaSpVr;
	private BigDecimal segAutoTempoparadaDefault;
	private BigDecimal segAutoTempoparadaSemOp;
	private BigDecimal segAutoTempoparadaSemEvt;
	private BigDecimal segAutoTempoparadaSemCnx;
	private BigDecimal segManuTempoparadaDefault;
	private BigDecimal segManuTempoparadaSemOp;
	private BigDecimal segManuTempoparadaSemEvt;
	private BigDecimal segManuTempoparadaSemCnx;
	private BigDecimal qtAutoTempoparadaDefault;
	private BigDecimal qtAutoTempoparadaSemOp;
	private BigDecimal qtAutoTempoparadaSemEvt;
	private BigDecimal qtAutoTempoparadaSemCnx;
	private BigDecimal qtManuTempoparadaDefault;
	private BigDecimal qtManuTempoparadaSemOp;
	private BigDecimal qtManuTempoparadaSemEvt;
	private BigDecimal qtManuTempoparadaSemCnx;
	private BigDecimal segAutoCta;
	private BigDecimal segManuCta;
	
	public DwConsolpamo() {
	}

	public DwConsolpamo(Long idConsolpamo, DwConsolmo dwConsolmo,
			DwConsolpa dwConsolpa) {
		this.idConsolpamo = idConsolpamo;
		this.dwConsolmo = dwConsolmo;
		this.dwConsolpa = dwConsolpa;
	}

	public DwConsolpamo(Long idConsolpamo, DwConsolmo dwConsolmo,
			DwConsolpa dwConsolpa, BigDecimal qtAutoTempoparadaCp,
			BigDecimal qtAutoTempoparadaSp, BigDecimal qtManuTempoparadaCp,
			BigDecimal qtManuTempoparadaSp, BigDecimal segAutoTempoparadaCp,
			BigDecimal segAutoTempoparadaSp, BigDecimal segManuTempoparadaCp,
			BigDecimal segManuTempoparadaSp,
			BigDecimal segAutoTempoparadaCpVr, //
			BigDecimal segAutoTempoparadaSpVr, BigDecimal segManuTempoparadaCpVr,
			BigDecimal segManuTempoparadaSpVr, BigDecimal qtAutoOcoparadaCpVr,
			BigDecimal qtAutoOcoparadaSpVr, BigDecimal qtManuOcoparadaCpVr,
			BigDecimal qtManuOcoparadaSpVr, BigDecimal segAutoTempoparadaDefault,
			BigDecimal segAutoTempoparadaSemOp, BigDecimal segAutoTempoparadaSemEvt,
			BigDecimal segAutoTempoparadaSemCnx, BigDecimal segManuTempoparadaDefault,
			BigDecimal segManuTempoparadaSemOp, BigDecimal segManuTempoparadaSemEvt,
			BigDecimal segManuTempoparadaSemCnx, BigDecimal qtAutoTempoparadaDefault,
			BigDecimal qtAutoTempoparadaSemOp, BigDecimal qtAutoTempoparadaSemEvt,
			BigDecimal qtAutoTempoparadaSemCnx, BigDecimal qtManuTempoparadaDefault,
			BigDecimal qtManuTempoparadaSemOp, BigDecimal qtManuTempoparadaSemEvt,
			BigDecimal qtManuTempoparadaSemCnx, BigDecimal segAutoCta,
			BigDecimal segManuCta) {
		this.idConsolpamo = idConsolpamo;
		this.dwConsolmo = dwConsolmo;
		this.dwConsolpa = dwConsolpa;
		this.qtAutoTempoparadaCp = qtAutoTempoparadaCp;
		this.qtAutoTempoparadaSp = qtAutoTempoparadaSp;
		this.qtManuTempoparadaCp = qtManuTempoparadaCp;
		this.qtManuTempoparadaSp = qtManuTempoparadaSp;
		this.segAutoTempoparadaCp = segAutoTempoparadaCp;
		this.segAutoTempoparadaSp = segAutoTempoparadaSp;
		this.segManuTempoparadaCp = segManuTempoparadaCp;
		this.segManuTempoparadaSp = segManuTempoparadaSp;	
		this.segAutoTempoparadaCpVr = segAutoTempoparadaCpVr; //
		this.segAutoTempoparadaSpVr = segAutoTempoparadaSpVr;
		this.segManuTempoparadaCpVr = segManuTempoparadaCpVr;
		this.segManuTempoparadaSpVr = segManuTempoparadaSpVr;
		this.qtAutoOcoparadaCpVr = qtAutoOcoparadaCpVr;
		this.qtAutoOcoparadaSpVr = qtAutoOcoparadaSpVr;
		this.qtManuOcoparadaCpVr = qtManuOcoparadaCpVr;
		this.qtManuOcoparadaSpVr = qtManuOcoparadaSpVr;
		this.segAutoTempoparadaDefault = segAutoTempoparadaDefault;
		this.segAutoTempoparadaSemOp = segAutoTempoparadaSemOp;
		this.segAutoTempoparadaSemEvt = segAutoTempoparadaSemEvt;
		this.segAutoTempoparadaSemCnx = segAutoTempoparadaSemCnx;
		this.segManuTempoparadaDefault = segManuTempoparadaDefault;
		this.segManuTempoparadaSemOp = segManuTempoparadaSemOp;
		this.segManuTempoparadaSemEvt = segManuTempoparadaSemEvt;
		this.segManuTempoparadaSemCnx = segManuTempoparadaSemCnx;
		this.qtAutoTempoparadaDefault = qtAutoTempoparadaDefault;
		this.qtAutoTempoparadaSemOp = qtAutoTempoparadaSemOp;
		this.qtAutoTempoparadaSemEvt = qtAutoTempoparadaSemEvt;
		this.qtAutoTempoparadaSemCnx = qtAutoTempoparadaSemCnx;
		this.qtManuTempoparadaDefault = qtManuTempoparadaDefault;
		this.qtManuTempoparadaSemOp = qtManuTempoparadaSemOp;
		this.qtManuTempoparadaSemEvt = qtManuTempoparadaSemEvt;
		this.qtManuTempoparadaSemCnx = qtManuTempoparadaSemCnx;
		this.segAutoCta = segAutoCta;
		this.segManuCta = segManuCta;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CONSOLPAMO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CONSOLPAMO_SEQ", sequenceName = "DW_CONSOLPAMO_SEQ")
	@Column(name = "ID_CONSOLPAMO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdConsolpamo() {
		return this.idConsolpamo;
	}

	public void setIdConsolpamo(Long idConsolpamo) {
		this.idConsolpamo = idConsolpamo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CONSOLMO", nullable = false)
	public DwConsolmo getDwConsolmo() {
		return this.dwConsolmo;
	}

	public void setDwConsolmo(DwConsolmo dwConsolmo) {
		this.dwConsolmo = dwConsolmo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CONSOLPA", nullable = false)
	public DwConsolpa getDwConsolpa() {
		return this.dwConsolpa;
	}

	public void setDwConsolpa(DwConsolpa dwConsolpa) {
		this.dwConsolpa = dwConsolpa;
	}

	@Column(name = "QT_AUTO_TEMPOPARADA_CP", precision = 14, scale = 4)
	public BigDecimal getQtAutoTempoparadaCp() {
		return this.qtAutoTempoparadaCp;
	}

	public void setQtAutoTempoparadaCp(BigDecimal qtAutoTempoparadaCp) {
		this.qtAutoTempoparadaCp = qtAutoTempoparadaCp;
	}

	@Column(name = "QT_AUTO_TEMPOPARADA_SP", precision = 14, scale = 4)
	public BigDecimal getQtAutoTempoparadaSp() {
		return this.qtAutoTempoparadaSp;
	}

	public void setQtAutoTempoparadaSp(BigDecimal qtAutoTempoparadaSp) {
		this.qtAutoTempoparadaSp = qtAutoTempoparadaSp;
	}

	@Column(name = "QT_MANU_TEMPOPARADA_CP", precision = 14, scale = 4)
	public BigDecimal getQtManuTempoparadaCp() {
		return this.qtManuTempoparadaCp;
	}

	public void setQtManuTempoparadaCp(BigDecimal qtManuTempoparadaCp) {
		this.qtManuTempoparadaCp = qtManuTempoparadaCp;
	}

	@Column(name = "QT_MANU_TEMPOPARADA_SP", precision = 14, scale = 4)
	public BigDecimal getQtManuTempoparadaSp() {
		return this.qtManuTempoparadaSp;
	}

	public void setQtManuTempoparadaSp(BigDecimal qtManuTempoparadaSp) {
		this.qtManuTempoparadaSp = qtManuTempoparadaSp;
	}

	@Column(name = "SEG_AUTO_TEMPOPARADA_CP", precision = 20, scale = 10)
	public BigDecimal getSegAutoTempoparadaCp() {
		return this.segAutoTempoparadaCp;
	}

	public void setSegAutoTempoparadaCp(BigDecimal segAutoTempoparadaCp) {
		this.segAutoTempoparadaCp = segAutoTempoparadaCp;
	}

	@Column(name = "SEG_AUTO_TEMPOPARADA_SP", precision = 20, scale = 10)
	public BigDecimal getSegAutoTempoparadaSp() {
		return this.segAutoTempoparadaSp;
	}

	public void setSegAutoTempoparadaSp(BigDecimal segAutoTempoparadaSp) {
		this.segAutoTempoparadaSp = segAutoTempoparadaSp;
	}

	@Column(name = "SEG_MANU_TEMPOPARADA_CP", precision = 20, scale = 10)
	public BigDecimal getSegManuTempoparadaCp() {
		return this.segManuTempoparadaCp;
	}

	public void setSegManuTempoparadaCp(BigDecimal segManuTempoparadaCp) {
		this.segManuTempoparadaCp = segManuTempoparadaCp;
	}

	@Column(name = "SEG_MANU_TEMPOPARADA_SP", precision = 20, scale = 10)
	public BigDecimal getSegManuTempoparadaSp() {
		return this.segManuTempoparadaSp;
	}

	public void setSegManuTempoparadaSp(BigDecimal segManuTempoparadaSp) {
		this.segManuTempoparadaSp = segManuTempoparadaSp;
	}

	@Column(name = "seg_auto_tempoparada_cp_vr", precision = 20, scale = 10)
	public BigDecimal getSegAutoTempoparadaCpVr() {
		return this.segAutoTempoparadaCpVr;
	}

	public void setSegAutoTempoparadaCpVr(BigDecimal segAutoTempoparadaCpVr) {
		this.segAutoTempoparadaCpVr = segAutoTempoparadaCpVr;
	}

	@Column(name = "seg_auto_tempoparada_sp_vr", precision = 20, scale = 10)
	public BigDecimal getSegAutoTempoparadaSpVr() {
		return this.segAutoTempoparadaSpVr;
	}

	public void setSegAutoTempoparadaSpVr(BigDecimal segAutoTempoparadaSpVr) {
		this.segAutoTempoparadaSpVr = segAutoTempoparadaSpVr;
	}

	@Column(name = "seg_manu_tempoparada_cp_vr", precision = 20, scale = 10)
	public BigDecimal getSegManuTempoparadaCpVr() {
		return this.segManuTempoparadaCpVr;
	}

	public void setSegManuTempoparadaCpVr(BigDecimal segManuTempoparadaCpVr) {
		this.segManuTempoparadaCpVr = segManuTempoparadaCpVr;
	}

	@Column(name = "seg_manu_tempoparada_sp_vr", precision = 20, scale = 10)
	public BigDecimal getSegManuTempoparadaSpVr() {
		return this.segManuTempoparadaSpVr;
	}

	public void setSegManuTempoparadaSpVr(BigDecimal segManuTempoparadaSpVr) {
		this.segManuTempoparadaSpVr = segManuTempoparadaSpVr;
	}

	@Column(name = "qt_auto_ocoparada_cp_vr", precision = 14, scale = 4)
	public BigDecimal getQtAutoOcoparadaCpVr() {
		return this.qtAutoOcoparadaCpVr;
	}

	public void setQtAutoOcoparadaCpVr(BigDecimal qtAutoOcoparadaCpVr) {
		this.qtAutoOcoparadaCpVr = qtAutoOcoparadaCpVr;
	}

	@Column(name = "qt_auto_ocoparada_sp_vr", precision = 14, scale = 4)
	public BigDecimal getQtAutoOcoparadaSpVr() {
		return this.qtAutoOcoparadaSpVr;
	}

	public void setQtAutoOcoparadaSpVr(BigDecimal qtAutoOcoparadaSpVr) {
		this.qtAutoOcoparadaSpVr = qtAutoOcoparadaSpVr;
	}

	@Column(name = "qt_manu_ocoparada_cp_vr", precision = 14, scale = 4)
	public BigDecimal getQtManuOcoparadaCpVr() {
		return this.qtManuOcoparadaCpVr;
	}

	public void setQtManuOcoparadaCpVr(BigDecimal qtManuOcoparadaCpVr) {
		this.qtManuOcoparadaCpVr = qtManuOcoparadaCpVr;
	}

	@Column(name = "qt_manu_ocoparada_sp_vr", precision = 14, scale = 4)
	public BigDecimal getQtManuOcoparadaSpVr() {
		return this.qtManuOcoparadaSpVr;
	}

	public void setQtManuOcoparadaSpVr(BigDecimal qtManuOcoparadaSpVr) {
		this.qtManuOcoparadaSpVr = qtManuOcoparadaSpVr;
	}

	@Column(name = "seg_auto_tempoparada_default", precision = 20, scale = 10)
	public BigDecimal getSegAutoTempoparadaDefault() {
		return this.segAutoTempoparadaDefault;
	}

	public void setSegAutoTempoparadaDefault(
			BigDecimal segAutoTempoparadaDefault) {
		this.segAutoTempoparadaDefault = segAutoTempoparadaDefault;
	}

	@Column(name = "seg_auto_tempoparada_sem_op", precision = 20, scale = 10)
	public BigDecimal getSegAutoTempoparadaSemOp() {
		return this.segAutoTempoparadaSemOp;
	}

	public void setSegAutoTempoparadaSemOp(BigDecimal segAutoTempoparadaSemOp) {
		this.segAutoTempoparadaSemOp = segAutoTempoparadaSemOp;
	}

	@Column(name = "seg_auto_tempoparada_sem_evt", precision = 20, scale = 10)
	public BigDecimal getSegAutoTempoparadaSemEvt() {
		return this.segAutoTempoparadaSemEvt;
	}

	public void setSegAutoTempoparadaSemEvt(BigDecimal segAutoTempoparadaSemEvt) {
		this.segAutoTempoparadaSemEvt = segAutoTempoparadaSemEvt;
	}

	@Column(name = "seg_auto_tempoparada_sem_cnx", precision = 20, scale = 10)
	public BigDecimal getSegAutoTempoparadaSemCnx() {
		return this.segAutoTempoparadaSemCnx;
	}

	public void setSegAutoTempoparadaSemCnx(BigDecimal segAutoTempoparadaSemCnx) {
		this.segAutoTempoparadaSemCnx = segAutoTempoparadaSemCnx;
	}

	@Column(name = "seg_manu_tempoparada_default", precision = 20, scale = 10)
	public BigDecimal getSegManuTempoparadaDefault() {
		return this.segManuTempoparadaDefault;
	}

	public void setSegManuTempoparadaDefault(
			BigDecimal segManuTempoparadaDefault) {
		this.segManuTempoparadaDefault = segManuTempoparadaDefault;
	}

	@Column(name = "seg_manu_tempoparada_sem_op", precision = 20, scale = 10)
	public BigDecimal getSegManuTempoparadaSemOp() {
		return this.segManuTempoparadaSemOp;
	}

	public void setSegManuTempoparadaSemOp(BigDecimal segManuTempoparadaSemOp) {
		this.segManuTempoparadaSemOp = segManuTempoparadaSemOp;
	}

	@Column(name = "seg_manu_tempoparada_sem_evt", precision = 20, scale = 10)
	public BigDecimal getSegManuTempoparadaSemEvt() {
		return this.segManuTempoparadaSemEvt;
	}

	public void setSegManuTempoparadaSemEvt(BigDecimal segManuTempoparadaSemEvt) {
		this.segManuTempoparadaSemEvt = segManuTempoparadaSemEvt;
	}

	@Column(name = "seg_manu_tempoparada_sem_cnx", precision = 20, scale = 10)
	public BigDecimal getSegManuTempoparadaSemCnx() {
		return this.segManuTempoparadaSemCnx;
	}

	public void setSegManuTempoparadaSemCnx(BigDecimal segManuTempoparadaSemCnx) {
		this.segManuTempoparadaSemCnx = segManuTempoparadaSemCnx;
	}

	@Column(name = "qt_auto_tempoparada_default", precision = 14, scale = 4)
	public BigDecimal getQtAutoTempoparadaDefault() {
		return this.qtAutoTempoparadaDefault;
	}

	public void setQtAutoTempoparadaDefault(BigDecimal qtAutoTempoparadaDefault) {
		this.qtAutoTempoparadaDefault = qtAutoTempoparadaDefault;
	}

	@Column(name = "qt_auto_tempoparada_sem_op", precision = 14, scale = 4)
	public BigDecimal getQtAutoTempoparadaSemOp() {
		return this.qtAutoTempoparadaSemOp;
	}

	public void setQtAutoTempoparadaSemOp(BigDecimal qtAutoTempoparadaSemOp) {
		this.qtAutoTempoparadaSemOp = qtAutoTempoparadaSemOp;
	}

	@Column(name = "qt_auto_tempoparada_sem_evt", precision = 14, scale = 4)
	public BigDecimal getQtAutoTempoparadaSemEvt() {
		return this.qtAutoTempoparadaSemEvt;
	}

	public void setQtAutoTempoparadaSemEvt(BigDecimal qtAutoTempoparadaSemEvt) {
		this.qtAutoTempoparadaSemEvt = qtAutoTempoparadaSemEvt;
	}

	@Column(name = "qt_auto_tempoparada_sem_cnx", precision = 14, scale = 4)
	public BigDecimal getQtAutoTempoparadaSemCnx() {
		return this.qtAutoTempoparadaSemCnx;
	}

	public void setQtAutoTempoparadaSemCnx(BigDecimal qtAutoTempoparadaSemCnx) {
		this.qtAutoTempoparadaSemCnx = qtAutoTempoparadaSemCnx;
	}

	@Column(name = "qt_manu_tempoparada_default", precision = 14, scale = 4)
	public BigDecimal getQtManuTempoparadaDefault() {
		return this.qtManuTempoparadaDefault;
	}

	public void setQtManuTempoparadaDefault(BigDecimal qtManuTempoparadaDefault) {
		this.qtManuTempoparadaDefault = qtManuTempoparadaDefault;
	}

	@Column(name = "qt_manu_tempoparada_sem_op", precision = 14, scale = 4)
	public BigDecimal getQtManuTempoparadaSemOp() {
		return this.qtManuTempoparadaSemOp;
	}

	public void setQtManuTempoparadaSemOp(BigDecimal qtManuTempoparadaSemOp) {
		this.qtManuTempoparadaSemOp = qtManuTempoparadaSemOp;
	}

	@Column(name = "qt_manu_tempoparada_sem_evt", precision = 14, scale = 4)
	public BigDecimal getQtManuTempoparadaSemEvt() {
		return this.qtManuTempoparadaSemEvt;
	}

	public void setQtManuTempoparadaSemEvt(BigDecimal qtManuTempoparadaSemEvt) {
		this.qtManuTempoparadaSemEvt = qtManuTempoparadaSemEvt;
	}

	@Column(name = "qt_manu_tempoparada_sem_cnx", precision = 14, scale = 4)
	public BigDecimal getQtManuTempoparadaSemCnx() {
		return this.qtManuTempoparadaSemCnx;
	}

	public void setQtManuTempoparadaSemCnx(BigDecimal qtManuTempoparadaSemCnx) {
		this.qtManuTempoparadaSemCnx = qtManuTempoparadaSemCnx;
	}

	@Column(name = "seg_auto_cta", precision = 20, scale = 10)
	public BigDecimal getSegAutoCta() {
		return this.segAutoCta;
	}

	public void setSegAutoCta(BigDecimal segAutoCta) {
		this.segAutoCta = segAutoCta;
	}

	@Column(name = "seg_manu_cta", precision = 20, scale = 10)
	public BigDecimal getSegManuCta() {
		return this.segManuCta;
	}

	public void setSegManuCta(BigDecimal segManuCta) {
		this.segManuCta = segManuCta;
	}
}
