package idw.model.pojos;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DwConsolmooco generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_consolmooco")
public class DwConsolmooco implements java.io.Serializable {

	private long idConsolmooco;
	private DwConsolmolog dwConsolmolog;
	private DwConsolmo dwConsolmo;
	private Date dthrIlogin;
	private Byte msDthrilogin;
	private Date dthrFlogin;
	private Byte msDthrflogin;
	private Boolean isContinuaproximoperiodo;

	public DwConsolmooco() {
	}

	public DwConsolmooco(long idConsolmooco, DwConsolmolog dwConsolmolog,
			DwConsolmo dwConsolmo) {
		this.idConsolmooco = idConsolmooco;
		this.dwConsolmolog = dwConsolmolog;
		this.dwConsolmo = dwConsolmo;
	}

	public DwConsolmooco(long idConsolmooco, DwConsolmolog dwConsolmolog,
			DwConsolmo dwConsolmo, Date dthrIlogin, Byte msDthrilogin,
			Date dthrFlogin, Byte msDthrflogin, Boolean isContinuaproximoperiodo) {
		this.idConsolmooco = idConsolmooco;
		this.dwConsolmolog = dwConsolmolog;
		this.dwConsolmo = dwConsolmo;
		this.dthrIlogin = dthrIlogin;
		this.msDthrilogin = msDthrilogin;
		this.dthrFlogin = dthrFlogin;
		this.msDthrflogin = msDthrflogin;
		this.isContinuaproximoperiodo = isContinuaproximoperiodo;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CONSOLMOOCO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CONSOLMOOCO_SEQ", sequenceName = "DW_CONSOLMOOCO_SEQ")		
	@Column(name = "id_consolmooco", unique = true, nullable = false)
	public long getIdConsolmooco() {
		return this.idConsolmooco;
	}

	public void setIdConsolmooco(long idConsolmooco) {
		this.idConsolmooco = idConsolmooco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_consolmolog", nullable = false)
	public DwConsolmolog getDwConsolmolog() {
		return this.dwConsolmolog;
	}

	public void setDwConsolmolog(DwConsolmolog dwConsolmolog) {
		this.dwConsolmolog = dwConsolmolog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_consolmo", nullable = false)
	public DwConsolmo getDwConsolmo() {
		return this.dwConsolmo;
	}

	public void setDwConsolmo(DwConsolmo dwConsolmo) {
		this.dwConsolmo = dwConsolmo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_ilogin", length = 23)
	public Date getDthrIlogin() {
		return this.dthrIlogin;
	}

	public void setDthrIlogin(Date dthrIlogin) {
		this.dthrIlogin = dthrIlogin;
	}

	@Column(name = "ms_dthrilogin")
	public Byte getMsDthrilogin() {
		return this.msDthrilogin;
	}

	public void setMsDthrilogin(Byte msDthrilogin) {
		this.msDthrilogin = msDthrilogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_flogin", length = 23)
	public Date getDthrFlogin() {
		return this.dthrFlogin;
	}

	public void setDthrFlogin(Date dthrFlogin) {
		this.dthrFlogin = dthrFlogin;
	}

	@Column(name = "ms_dthrflogin")
	public Byte getMsDthrflogin() {
		return this.msDthrflogin;
	}

	public void setMsDthrflogin(Byte msDthrflogin) {
		this.msDthrflogin = msDthrflogin;
	}

	@Column(name = "is_continuaproximoperiodo")
	public Boolean getIsContinuaproximoperiodo() {
		return this.isContinuaproximoperiodo;
	}

	public void setIsContinuaproximoperiodo(Boolean isContinuaproximoperiodo) {
		this.isContinuaproximoperiodo = isContinuaproximoperiodo;
	}

}
