package idw.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// default package
// Generated 30/04/2013 11:32:48 by Hibernate Tools 3.4.0.CR1


import idw.model.pojos.template.DwConsolpempocoTemplate;

/**
 * DwConsolpempoco generated by hbm2java
 */
@Entity
@Table(name="dw_consolpempoco"
		)
public class DwConsolpempoco extends DwConsolpempocoTemplate implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -5509157889922605378L;
	private long idConsolpempoco;
	private DwConsolpemp dwConsolpemp;
	private DwConsolperdamplog dwConsolperdamplog;

	public DwConsolpempoco() {
	}

	public DwConsolpempoco(long idConsolpempoco, DwConsolpemp dwConsolpemp, DwConsolperdamplog dwConsolperdamplog) {
		this.idConsolpempoco = idConsolpempoco;
		this.dwConsolpemp = dwConsolpemp;
		this.dwConsolperdamplog = dwConsolperdamplog;
	}

	@Id 
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CONSOLPEMPOCO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CONSOLPEMPOCO_SEQ", sequenceName = "DW_CONSOLPEMPOCO_SEQ")


	@Column(name="id_consolpempoco", unique=true, nullable=false)
	public long getIdConsolpempoco() {
		return this.idConsolpempoco;
	}

	public void setIdConsolpempoco(long idConsolpempoco) {
		this.idConsolpempoco = idConsolpempoco;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="id_consolpemp", nullable=false)
	public DwConsolpemp getDwConsolpemp() {
		return this.dwConsolpemp;
	}

	public void setDwConsolpemp(DwConsolpemp dwConsolpemp) {
		this.dwConsolpemp = dwConsolpemp;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="id_consolpemplog", nullable=false)
	public DwConsolperdamplog getDwConsolperdamplog() {
		return this.dwConsolperdamplog;
	}

	public void setDwConsolperdamplog(DwConsolperdamplog dwConsolperdamplog) {
		this.dwConsolperdamplog = dwConsolperdamplog;
	}




}


