package idw.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import idw.model.pojos.template.DwConsolParammedTemplate;

/**
 * DwConsolParammed generated by hbm2java
 */
@Entity
@Table(name="dw_consol_parammed"
)
public class DwConsolParammed extends DwConsolParammedTemplate implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idConsolparammed;
     private DwConsolmedparamlog dwConsolmedparamlog;
     private DwConsolParam dwConsolParam;
     private DwConsolpaParam dwConsolpaParam;
     private DwConsolpaoco dwConsolpaoco;

    public DwConsolParammed() {
    }

	
    public DwConsolParammed(Long idConsolparammed) {
        this.idConsolparammed = idConsolparammed;
    }
    public DwConsolParammed(Long idConsolparammed, DwConsolmedparamlog dwConsolmedparamlog, DwConsolParam dwConsolParam, DwConsolpaParam dwConsolpaParam, DwConsolpaoco dwConsolpaoco) {
       this.idConsolparammed = idConsolparammed;
       this.dwConsolmedparamlog = dwConsolmedparamlog;
       this.dwConsolParam = dwConsolParam;
       this.dwConsolpaParam = dwConsolpaParam;
       this.dwConsolpaoco = dwConsolpaoco;
    }
   
    @Id 
 	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CONSOL_PARAMMED_SEQ")
 	@javax.persistence.SequenceGenerator(name = "DW_CONSOL_PARAMMED_SEQ", sequenceName = "DW_CONSOL_PARAMMED_SEQ")
    @Column(name="id_consolparammed", unique=true, nullable=false)
    public Long getIdConsolparammed() {
        return this.idConsolparammed;
    }
    
    public void setIdConsolparammed(Long idConsolparammed) {
        this.idConsolparammed = idConsolparammed;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consolmedparamlog")
    public DwConsolmedparamlog getDwConsolmedparamlog() {
        return this.dwConsolmedparamlog;
    }
    
    public void setDwConsolmedparamlog(DwConsolmedparamlog dwConsolmedparamlog) {
        this.dwConsolmedparamlog = dwConsolmedparamlog;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consolparam")
    public DwConsolParam getDwConsolParam() {
        return this.dwConsolParam;
    }
    
    public void setDwConsolParam(DwConsolParam dwConsolParam) {
        this.dwConsolParam = dwConsolParam;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consolpa_param")
    public DwConsolpaParam getDwConsolpaParam() {
        return this.dwConsolpaParam;
    }
    
    public void setDwConsolpaParam(DwConsolpaParam dwConsolpaParam) {
        this.dwConsolpaParam = dwConsolpaParam;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consolpaoco")
    public DwConsolpaoco getDwConsolpaoco() {
        return this.dwConsolpaoco;
    }
    
    public void setDwConsolpaoco(DwConsolpaoco dwConsolpaoco) {
        this.dwConsolpaoco = dwConsolpaoco;
    }

}


