package idw.model.pojos;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DwConsolsplog generated by hbm2java
 */
@Entity
@Table(name = "dw_consolsplog")
public class DwConsolsplog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idConsolsplog;
	private OmPt omPt;
	private Date dthrInicio;
	private Date dthrFim;

	public DwConsolsplog() {
	}

	public DwConsolsplog(Long idConsolsplog, OmPt omPt) {
		this.idConsolsplog = idConsolsplog;
		this.omPt = omPt;
	}

	public DwConsolsplog(Long idConsolsplog, OmPt omPt, Date dthrInicio, Date dthrFim) {
		this.idConsolsplog = idConsolsplog;
		this.omPt = omPt;
		this.dthrInicio = dthrInicio;
		this.dthrFim = dthrFim;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CONSOLSPLOG_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CONSOLSPLOG_SEQ", sequenceName = "DW_CONSOLSPLOG_SEQ")			
	@Column(name = "id_consolsplog", unique = true, nullable = false)
	public Long getIdConsolsplog() {
		return this.idConsolsplog;
	}

	public void setIdConsolsplog(Long idConsolsplog) {
		this.idConsolsplog = idConsolsplog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pt", nullable = false)
	public OmPt getOmPt() {
		return this.omPt;
	}

	public void setOmPt(OmPt omPt) {
		this.omPt = omPt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_inicio", length = 27)
	public Date getDthrInicio() {
		return this.dthrInicio;
	}

	public void setDthrInicio(Date dthrInicio) {
		this.dthrInicio = dthrInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_fim", length = 27)
	public Date getDthrFim() {
		return this.dthrFim;
	}

	public void setDthrFim(Date dthrFim) {
		this.dthrFim = dthrFim;
	}

}
