package idw.model.pojos;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DwConsolaloco generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_consolaloco")
public class DwConsolaloco implements java.io.Serializable {

	private Long idConsolaloco;
	private DwConsolallog dwConsolallog;
	private DwConsolal dwConsolal;
	private Date dthrIalerta;
	private Byte msDthrialerta;
	private Date dthrFalerta;
	private Byte msDthrfalerta;
	private Boolean isContinuaproximoperiodo;

	public DwConsolaloco() {
	}

	public DwConsolaloco(long idConsolaloco, DwConsolal dwConsolal, DwConsolallog dwConsolallog) {
		this.idConsolaloco = idConsolaloco;
		this.dwConsolal = dwConsolal;
		this.dwConsolallog = dwConsolallog;
	}

	public DwConsolaloco(long idConsolaloco, DwConsolal dwConsolal,
			DwConsolallog dwConsolallog,
			Date dthrIalerta, Byte msDthrialerta, Date dthrFalerta,
			Byte msDthrfalerta, Boolean isContinuaproximoperiodo) {
		this.idConsolaloco = idConsolaloco;
		this.dwConsolal = dwConsolal;
		this.dwConsolallog = dwConsolallog;
		this.dthrIalerta = dthrIalerta;
		this.msDthrialerta = msDthrialerta;
		this.dthrFalerta = dthrFalerta;
		this.msDthrfalerta = msDthrfalerta;
		this.isContinuaproximoperiodo = isContinuaproximoperiodo;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CONSOLALOCO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CONSOLALOCO_SEQ", sequenceName = "DW_CONSOLALOCO_SEQ")	
	@Column(name = "id_consolaloco", unique = true, nullable = false)	
	public Long getIdConsolaloco() {
		return this.idConsolaloco;
	}

	public void setIdConsolaloco(Long idConsolaloco) {
		this.idConsolaloco = idConsolaloco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_consolal", nullable = false)
	public DwConsolal getDwConsolal() {
		return this.dwConsolal;
	}

	public void setDwConsolal(DwConsolal dwConsolal) {
		this.dwConsolal = dwConsolal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_consolallog", nullable = false)
	public DwConsolallog getDwConsolallog() {
		return this.dwConsolallog;
	}

	public void setDwConsolallog(DwConsolallog dwConsolallog) {
		this.dwConsolallog = dwConsolallog;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_ialerta", length = 23)
	public Date getDthrIalerta() {
		return this.dthrIalerta;
	}

	public void setDthrIalerta(Date dthrIalerta) {
		this.dthrIalerta = dthrIalerta;
	}

	@Column(name = "ms_dthrialerta")
	public Byte getMsDthrialerta() {
		return this.msDthrialerta;
	}

	public void setMsDthrialerta(Byte msDthrialerta) {
		this.msDthrialerta = msDthrialerta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_falerta", length = 23)
	public Date getDthrFalerta() {
		return this.dthrFalerta;
	}

	public void setDthrFalerta(Date dthrFalerta) {
		this.dthrFalerta = dthrFalerta;
	}

	@Column(name = "ms_dthrfalerta")
	public Byte getMsDthrfalerta() {
		return this.msDthrfalerta;
	}

	public void setMsDthrfalerta(Byte msDthrfalerta) {
		this.msDthrfalerta = msDthrfalerta;
	}

	@Column(name = "is_continuaproximoperiodo")
	public Boolean getIsContinuaproximoperiodo() {
		return this.isContinuaproximoperiodo;
	}

	public void setIsContinuaproximoperiodo(Boolean isContinuaproximoperiodo) {
		this.isContinuaproximoperiodo = isContinuaproximoperiodo;
	}

}
