package idw.model.pojos;

// Generated 30/04/2013 11:32:48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.DwConsolpempTemplate;

/**
 * DwConsolpemp generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_consolpemp")
public class DwConsolpemp extends DwConsolpempTemplate implements java.io.Serializable {

	private long idConsolpemp;
	private DwConsol dwConsol;
	private DwTPerdamp dwTPerdamp;
	private BigDecimal qtAutoPerdamp;
	private BigDecimal qtManuPerdamp;
	private Set<DwConsolpempoco> dwConsolpempocos = new HashSet<DwConsolpempoco>(0);

	public DwConsolpemp() {
	}

	public DwConsolpemp(long idConsolpemp, DwConsol dwConsol,
			DwTPerdamp dwTPerdamp, BigDecimal qtAutoPerdamp,
			BigDecimal qtManuPerdamp) {
		this.idConsolpemp = idConsolpemp;
		this.dwConsol = dwConsol;
		this.dwTPerdamp = dwTPerdamp;
		this.qtAutoPerdamp = qtAutoPerdamp;
		this.qtManuPerdamp = qtManuPerdamp;
	}

	public DwConsolpemp(long idConsolpemp, DwConsol dwConsol,
			DwTPerdamp dwTPerdamp, BigDecimal qtAutoPerdamp,
			BigDecimal qtManuPerdamp, Set<DwConsolpempoco> dwConsolpempocos) {
		this.idConsolpemp = idConsolpemp;
		this.dwConsol = dwConsol;
		this.dwTPerdamp = dwTPerdamp;
		this.qtAutoPerdamp = qtAutoPerdamp;
		this.qtManuPerdamp = qtManuPerdamp;
		this.dwConsolpempocos = dwConsolpempocos;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DW_CONSOLPEMP_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CONSOLPEMP_SEQ", sequenceName = "DW_CONSOLPEMP_SEQ")
	@Column(name = "id_consolpemp", unique = true, nullable = false)
	public long getIdConsolpemp() {
		return this.idConsolpemp;
	}

	public void setIdConsolpemp(long idConsolpemp) {
		this.idConsolpemp = idConsolpemp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_consol", nullable = false)
	public DwConsol getDwConsol() {
		return this.dwConsol;
	}

	public void setDwConsol(DwConsol dwConsol) {
		this.dwConsol = dwConsol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tperdamp", nullable = false)
	public DwTPerdamp getDwTPerdamp() {
		return this.dwTPerdamp;
	}

	public void setDwTPerdamp(DwTPerdamp dwTPerdamp) {
		this.dwTPerdamp = dwTPerdamp;
	}

	@Column(name = "qt_auto_perdamp", nullable = false, precision = 22, scale = 0)
	public BigDecimal getQtAutoPerdamp() {
		return this.qtAutoPerdamp;
	}

	public void setQtAutoPerdamp(BigDecimal qtAutoPerdamp) {
		this.qtAutoPerdamp = qtAutoPerdamp;
	}

	@Column(name = "qt_manu_perdamp", nullable = false, precision = 22, scale = 0)
	public BigDecimal getQtManuPerdamp() {
		return this.qtManuPerdamp;
	}

	public void setQtManuPerdamp(BigDecimal qtManuPerdamp) {
		this.qtManuPerdamp = qtManuPerdamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwConsolpemp")
	public Set<DwConsolpempoco> getDwConsolpempocos() {
		return this.dwConsolpempocos;
	}

	public void setDwConsolpempocos(Set<DwConsolpempoco> dwConsolpempocos) {
		this.dwConsolpempocos = dwConsolpempocos;
	}

}
