package idw.model.pojos;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwConsolprTemplate;

/**
 * DwConsolpr generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_consolpr")
public class DwConsolpr extends DwConsolprTemplate implements java.io.Serializable {

	private Long idConsolpr;
	private OmProduto omProduto;
	private DwConsol dwConsol;
	private BigDecimal pcsAutoProducaobruta;
	private BigDecimal pcsAutoProducaoliquida;
	private BigDecimal pcsAutoProducaorefugada;
	private BigDecimal pcsManuProducaobruta;
	private BigDecimal pcsManuProducaoliquida;
	private BigDecimal pcsManuProducaorefugada;
	private BigDecimal gAutoPesoBruto;
	private BigDecimal gAutoPesoLiquido;
	private BigDecimal gManuPesoBruto;
	private BigDecimal gManuPesoLiquido;
	private BigDecimal segAutoTempoparada;
    private BigDecimal segAutoTempoparadaSp;
    
    // Acrescentar todas as perdas por produto
	private BigDecimal segAutoRitmo;
	private BigDecimal pcsAutoProducaoprevista;
	private BigDecimal pcsAutoPerdacavidades;
	private BigDecimal pcsAutoPerdaciclo;
	private BigDecimal pcsAutoPerdaparadaSp;
	private BigDecimal pcsAutoPerdaparadaCp;

	
	private Set<DwConsolprmo> dwConsolprmos = new HashSet<DwConsolprmo>(0);

	public DwConsolpr() {
	}

	public DwConsolpr(Long idConsolpr, OmProduto omProduto, DwConsol dwConsol) {
		this.idConsolpr = idConsolpr;
		this.omProduto = omProduto;
		this.dwConsol = dwConsol;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_CONSOLPR_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_CONSOLPR_SEQ", sequenceName = "DW_CONSOLPR_SEQ")
	@Column(name = "id_consolpr", unique = true, nullable = false)
	public Long getIdConsolpr() {
		return this.idConsolpr;
	}

	public void setIdConsolpr(Long idConsolpr) {
		this.idConsolpr = idConsolpr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produto", nullable = false)
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_consol", nullable = false)
	public DwConsol getDwConsol() {
		return this.dwConsol;
	}

	public void setDwConsol(DwConsol dwConsol) {
		this.dwConsol = dwConsol;
	}

	@Column(name = "pcs_auto_producaobruta", precision = 14, scale = 4)
	public BigDecimal getPcsAutoProducaobruta() {
		return this.pcsAutoProducaobruta;
	}

	public void setPcsAutoProducaobruta(BigDecimal pcsAutoProducaobruta) {
		this.pcsAutoProducaobruta = pcsAutoProducaobruta;
	}

	@Column(name = "pcs_auto_producaorefugada", precision = 14, scale = 4)
	public BigDecimal getPcsAutoProducaorefugada() {
		return this.pcsAutoProducaorefugada;
	}

	public void setPcsAutoProducaorefugada(BigDecimal pcsAutoProducaorefugada) {
		this.pcsAutoProducaorefugada = pcsAutoProducaorefugada;
	}

	@Column(name = "pcs_manu_producaobruta", precision = 14, scale = 4)
	public BigDecimal getPcsManuProducaobruta() {
		return this.pcsManuProducaobruta;
	}

	public void setPcsManuProducaobruta(BigDecimal pcsManuProducaobruta) {
		this.pcsManuProducaobruta = pcsManuProducaobruta;
	}

	@Column(name = "pcs_manu_producaorefugada", precision = 14, scale = 4)
	public BigDecimal getPcsManuProducaorefugada() {
		return this.pcsManuProducaorefugada;
	}

	public void setPcsManuProducaorefugada(BigDecimal pcsManuProducaorefugada) {
		this.pcsManuProducaorefugada = pcsManuProducaorefugada;
	}

	@Column(name = "g_auto_peso_bruto", precision = 20, scale = 3)
	public BigDecimal getGAutoPesoBruto() {
		return this.gAutoPesoBruto;
	}

	public void setGAutoPesoBruto(BigDecimal gAutoPesoBruto) {
		this.gAutoPesoBruto = gAutoPesoBruto;
	}

	@Column(name = "g_manu_peso_bruto", precision = 20, scale = 3)
	public BigDecimal getGManuPesoBruto() {
		return this.gManuPesoBruto;
	}

	public void setGManuPesoBruto(BigDecimal gManuPesoBruto) {
		this.gManuPesoBruto = gManuPesoBruto;
	}	
	
	@Column(name = "g_auto_peso_liquido", precision = 20, scale = 3)
	public BigDecimal getGAutoPesoLiquido() {
		return this.gAutoPesoLiquido;
	}

	public void setGAutoPesoLiquido(BigDecimal gAutoPesoLiquido) {
		this.gAutoPesoLiquido = gAutoPesoLiquido;
	}

	@Column(name = "g_manu_peso_liquido", precision = 20, scale = 3)
	public BigDecimal getGManuPesoLiquido() {
		return this.gManuPesoLiquido;
	}

	public void setGManuPesoLiquido(BigDecimal gManuPesoLiquido) {
		this.gManuPesoLiquido = gManuPesoLiquido;
	}	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwConsolpr")
	public Set<DwConsolprmo> getDwConsolprmos() {
		return this.dwConsolprmos;
	}

	public void setDwConsolprmos(Set<DwConsolprmo> dwConsolprmos) {
		this.dwConsolprmos = dwConsolprmos;
	}
	
	@Column(name="SEG_AUTO_TEMPOPARADA", precision=20, scale=10)
    public BigDecimal getSegAutoTempoparada() {
        return this.segAutoTempoparada;
    }
    
    public void setSegAutoTempoparada(BigDecimal segAutoTempoparada) {
        this.segAutoTempoparada = segAutoTempoparada;
    }

    
    @Column(name="SEG_AUTO_TEMPOPARADA_SP", precision=20, scale=10)
    public BigDecimal getSegAutoTempoparadaSp() {
        return this.segAutoTempoparadaSp;
    }
    
    public void setSegAutoTempoparadaSp(BigDecimal segAutoTempoparadaSp) {
        this.segAutoTempoparadaSp = segAutoTempoparadaSp;
    }

	@Column(name = "PCS_AUTO_PERDACAVIDADES", precision = 22, scale = 0)
	public BigDecimal getPcsAutoPerdacavidades() {
		return this.pcsAutoPerdacavidades;
	}

	public void setPcsAutoPerdacavidades(BigDecimal pcsAutoPerdacavidades) {
		this.pcsAutoPerdacavidades = pcsAutoPerdacavidades;
	}

	@Column(name = "PCS_AUTO_PERDACICLO", precision = 22, scale = 0)
	public BigDecimal getPcsAutoPerdaciclo() {
		return this.pcsAutoPerdaciclo;
	}

	public void setPcsAutoPerdaciclo(BigDecimal pcsAutoPerdaciclo) {
		this.pcsAutoPerdaciclo = pcsAutoPerdaciclo;
	}

	@Column(name = "PCS_AUTO_PERDAPARADA_SP", precision = 22, scale = 0)
	public BigDecimal getPcsAutoPerdaparadaSp() {
		return this.pcsAutoPerdaparadaSp;
	}

	public void setPcsAutoPerdaparadaSp(BigDecimal pcsAutoPerdaparadaSp) {
		this.pcsAutoPerdaparadaSp = pcsAutoPerdaparadaSp;
	}
	@Column(name = "PCS_AUTO_PERDAPARADA_CP", precision = 22, scale = 0)
	public BigDecimal getPcsAutoPerdaparadaCp() {
		return this.pcsAutoPerdaparadaCp;
	}

	public void setPcsAutoPerdaparadaCp(BigDecimal pcsAutoPerdaparadaCp) {
		this.pcsAutoPerdaparadaCp = pcsAutoPerdaparadaCp;
	}
	@Column(name = "SEG_AUTO_RITMO", precision = 20, scale = 10)
	public BigDecimal getSegAutoRitmo() {
		return this.segAutoRitmo;
	}

	public void setSegAutoRitmo(BigDecimal segAutoRitmo) {
		this.segAutoRitmo = segAutoRitmo;
	}
	@Column(name = "PCS_AUTO_PRODUCAOPREVISTA", precision = 22, scale = 0)
	public BigDecimal getPcsAutoProducaoprevista() {
		return this.pcsAutoProducaoprevista;
	}

	public void setPcsAutoProducaoprevista(BigDecimal pcsAutoProducaoprevista) {
		this.pcsAutoProducaoprevista = pcsAutoProducaoprevista;
	}
	@Column(name = "PCS_AUTO_PRODUCAOLIQUIDA", precision = 14, scale = 4)
	public BigDecimal getPcsAutoProducaoliquida() {
		return this.pcsAutoProducaoliquida;
	}

	public void setPcsAutoProducaoliquida(BigDecimal valor) {
		this.pcsAutoProducaoliquida = valor;
	}
	@Column(name = "PCS_MANU_PRODUCAOLIQUIDA", precision = 14, scale = 4)
	public BigDecimal getPcsManuProducaoliquida() {
		return this.pcsManuProducaoliquida;
	}

	public void setPcsManuProducaoliquida(BigDecimal valor) {
		this.pcsManuProducaoliquida = valor;
	}
}
