package idw.model.pojos;
// Generated 28/07/2011 10:26:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.DwEstProTemplate;

/**
 * DwEstpro generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "DW_ESTPRO")
public class DwEstpro  extends DwEstProTemplate implements java.io.Serializable {

	private Long idEstpro;
	private OmProduto omProduto;
	private DwEst dwEst;
	private PpCliente ppCliente;
	
	private BigDecimal qtEntrada;
	private BigDecimal qtSaida;
	private BigDecimal qtAjuste;
	private BigDecimal qtReservada;
	private BigDecimal qtTotal;
	private Date dthrAjuste;
	private Date dthrEntrada;
	private Date dthrSaida;
	private Date dthrTotal;

	private Set<DwEstmov> dwEstmovs = new HashSet<DwEstmov>(0);

	public DwEstpro() {
	}

	public DwEstpro(long idEstpro, OmProduto omProduto, DwEst dwEst) {
		this.idEstpro = idEstpro;
		this.omProduto = omProduto;
		this.dwEst = dwEst;
	}

	public DwEstpro(long idEstpro, OmProduto omProduto, DwEst dwEst,
			BigDecimal qtEntrada, BigDecimal qtSaida, BigDecimal qtReservada, BigDecimal qtTotal, 
			Date dthrAjuste, Date dthrEntrada, Date dthrSaida, Date dthrTotal) {
		this.idEstpro = idEstpro;
		this.omProduto = omProduto;
		this.dwEst = dwEst;
		this.qtEntrada = qtEntrada;
		this.qtSaida = qtSaida;
		this.qtReservada = qtReservada;
		this.qtTotal = qtTotal;
		this.dthrAjuste = dthrAjuste;
		this.dthrEntrada = dthrEntrada;
		this.dthrSaida = dthrSaida;
		this.dthrTotal = dthrTotal;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_ESTPRO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_ESTPRO_SEQ", sequenceName = "DW_ESTPRO_SEQ")
	@Column(name = "ID_ESTPRO", nullable = false)
	public Long getIdEstpro() {
		return this.idEstpro;
	}

	public void setIdEstpro(Long idEstpro) {
		this.idEstpro = idEstpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUTO", nullable = false)
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EST", nullable = false)
	public DwEst getDwEst() {
		return this.dwEst;
	}

	public void setDwEst(DwEst dwEst) {
		this.dwEst = dwEst;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENTE")
	public PpCliente getPpCliente() {
		return this.ppCliente;
	}

	public void setPpCliente(PpCliente ppCliente) {
		this.ppCliente = ppCliente;
	}

	@Column(name = "QT_SAIDA", precision = 14, scale = 4)
	public BigDecimal getQtSaida() {
		return this.qtSaida;
	}

	public void setQtSaida(BigDecimal qtSaida) {
		this.qtSaida = qtSaida;
	}

	@Column(name = "QT_RESERVADA", precision = 14, scale = 4)
	public BigDecimal getQtReservada() {
		return this.qtReservada;
	}

	public void setQtReservada(BigDecimal qtReservada) {
		this.qtReservada = qtReservada;
	}

	@OneToMany( cascade = CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "dwEstpro")
	public Set<DwEstmov> getDwEstmovs() {
		return this.dwEstmovs;
	}

	public void setDwEstmovs(Set<DwEstmov> dwEstmovs) {
		this.dwEstmovs = dwEstmovs;
	}

	@Column(name = "QT_ENTRADA", precision = 14, scale = 4)
	public BigDecimal getQtEntrada() {
		return this.qtEntrada;
	}

	public void setQtEntrada(BigDecimal qtEntrada) {
		this.qtEntrada = qtEntrada;
	}

	@Column(name = "QT_AJUSTE", precision = 14, scale = 4)
	public BigDecimal getQtAjuste() {
		return this.qtAjuste;
	}

	public void setQtAjuste(BigDecimal qtAjusteP) {
		this.qtAjuste = qtAjusteP;
	}
	
	@Column(name = "QT_TOTAL", precision = 14, scale = 4)
	public BigDecimal getQtTotal() {
		return this.qtTotal;
	}

	public void setQtTotal(BigDecimal qtTotal) {
		this.qtTotal = qtTotal;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_AJUSTE", length = 23)
	public Date getDthrAjuste(){
		return this.dthrAjuste;
	}
	
	public void setDthrAjuste(Date dthrAjuste){
		this.dthrAjuste = dthrAjuste;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_ENTRADA", length = 23)
	public Date getDthrEntrada(){
		return this.dthrEntrada;
	}
	
	public void setDthrEntrada(Date dthrEntrada){
		this.dthrEntrada = dthrEntrada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_SAIDA", length = 23)
	public Date getDthrSaida(){
		return this.dthrSaida;
	}
	
	public void setDthrSaida(Date dthrSaida){
		this.dthrSaida = dthrSaida;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_TOTAL", length = 23)
	public Date getDthrTotal(){
		return this.dthrTotal;
	}
	
	public void setDthrTotal(Date dthrTotal){
		this.dthrTotal = dthrTotal;
	}	
	
}
