package idw.model.pojos;



import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;

import idw.model.pojos.template.DwEstMovTemplate;

/**
 * DwEstmov generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "DW_ESTMOV")
public class DwEstmov extends DwEstMovTemplate implements java.io.Serializable {

	private Long idEstmov;
	private OmUsr omUsr;
	private DwEstpro dwEstpro;
	private Date dthrMov;
	private Integer tpMov;
	private Integer tpOrigem;
	private Boolean isEfetivado;
	private BigDecimal qtAjuste;
	private BigDecimal qtEntradaAnt;
	private BigDecimal qtSaidaAnt;
	private BigDecimal qtReservadaAnt;
	private Date dthrCadastro;
	private BigDecimal qtAjusteAnt;
	private BigDecimal qtTotal;
	private BigDecimal qtTotalAnt;

	private Integer ano;
	private Integer mes;

	private OmPt omPt;
	private DwTurno dwTurno;
	private OmGt omGt;

	private String lancamento;

	private DwEstlocalpro dwEstlocalpro;
	
	public DwEstmov() {
	}

	public DwEstmov(Long idEstmov, OmUsr omUsr, DwEstpro dwEstpro) {
		this.idEstmov = idEstmov;
		this.omUsr = omUsr;
		this.dwEstpro = dwEstpro;
	}

	public DwEstmov(Long idEstmov, OmUsr omUsr, DwEstpro dwEstpro,
			Date dthrMov, Integer tpMov, Integer tpOrigem,
			Boolean isEfetivado, BigDecimal qtAjuste,
			BigDecimal qtEntradaAnt, BigDecimal qtSaidaAnt,
			BigDecimal qtReservadaAnt, Date dthrCadastro, BigDecimal qtTotal, BigDecimal qtTotalAnt,
			DwEstlocalpro dwEstlocalpro) {
		this.idEstmov = idEstmov;
		this.omUsr = omUsr;
		this.dwEstpro = dwEstpro;
		this.dthrMov = dthrMov;
		this.tpMov = tpMov;
		this.tpOrigem = tpOrigem;
		this.isEfetivado = isEfetivado;
		this.qtAjuste = qtAjuste;
		this.qtEntradaAnt = qtEntradaAnt;
		this.qtSaidaAnt = qtSaidaAnt;
		this.qtReservadaAnt = qtReservadaAnt;
		this.dthrCadastro = dthrCadastro;
		this.qtTotal = qtTotal;
		this.qtTotalAnt = qtTotalAnt;
		this.dwEstlocalpro = dwEstlocalpro;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_ESTMOV_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_ESTMOV_SEQ", sequenceName = "DW_ESTMOV_SEQ")
	@Column(name = "ID_ESTMOV", nullable = false, precision = 22, scale = 0)
	public Long getIdEstmov() {
		return this.idEstmov;
	}

	public void setIdEstmov(Long idEstmov) {
		this.idEstmov = idEstmov;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USR", nullable = false)
	public OmUsr getOmUsr() {
		return this.omUsr;
	}

	public void setOmUsr(OmUsr omUsr) {
		this.omUsr = omUsr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@Cascade(org.hibernate.annotations.CascadeType.ALL)
	@JoinColumn( name = "ID_ESTPRO", nullable = false)
	public DwEstpro getDwEstpro() {
		return this.dwEstpro;
	}

	public void setDwEstpro(DwEstpro dwEstpro) {
		this.dwEstpro = dwEstpro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_MOV", length = 23)
	public Date getDthrMov() {
		return this.dthrMov;
	}

	public void setDthrMov(Date dthrMov) {
		this.dthrMov = dthrMov;
	}

	public void setQtAjusteAnt(BigDecimal qtAjusteAnt) {
		this.qtAjusteAnt = qtAjusteAnt;
	}

	@Column(name = "QT_AJUSTE_ANT", precision = 14, scale = 4)
	public BigDecimal getQtAjusteAnt() {
		return this.qtAjusteAnt;
	}

	@Column(name = "TP_MOV", precision = 22, scale = 0)
	public Integer getTpMov() {
		return this.tpMov;
	}

	public void setTpMov(Integer tpMov) {
		this.tpMov = tpMov;
	}

	@Column(name = "TP_ORIGEM", precision = 22, scale = 0)
	public Integer getTpOrigem() {
		return this.tpOrigem;
	}

	public void setTpOrigem(Integer tpOrigem) {
		this.tpOrigem = tpOrigem;
	}

	@Column(name = "IS_EFETIVADO", precision = 22, scale = 0)
	public Boolean getIsEfetivado() {
		return this.isEfetivado;
	}

	public void setIsEfetivado(Boolean isEfetivado) {
		this.isEfetivado = isEfetivado;
	}

	@Column(name = "QT_AJUSTE", precision = 14, scale = 4)
	public BigDecimal getQtAjuste() {
		return this.qtAjuste;
	}

	public void setQtAjuste(BigDecimal qtAjuste) {
		this.qtAjuste = qtAjuste;
	}

	@Column(name = "QT_ENTRADA_ANT", precision = 14, scale = 4)
	public BigDecimal getQtEntradaAnt() {
		return this.qtEntradaAnt;
	}

	public void setQtEntradaAnt(BigDecimal qtEntradaAnt) {
		this.qtEntradaAnt = qtEntradaAnt;
	}

	@Column(name = "QT_SAIDA_ANT", precision = 14, scale = 4)
	public BigDecimal getQtSaidaAnt() {
		return this.qtSaidaAnt;
	}

	public void setQtSaidaAnt(BigDecimal qtSaidaAnt) {
		this.qtSaidaAnt = qtSaidaAnt;
	}

	@Column(name = "QT_RESERVADA_ANT", precision = 14, scale = 4)
	public BigDecimal getQtReservadaAnt() {
		return this.qtReservadaAnt;
	}

	public void setQtReservadaAnt(BigDecimal qtReservadaAnt) {
		this.qtReservadaAnt = qtReservadaAnt;
	}

	@Column(name = "QT_TOTAL_ANT", precision = 14, scale = 4)
	public BigDecimal getQtTotalAnt() {
		return this.qtTotalAnt;
	}

	public void setQtTotalAnt(BigDecimal qtTotalAnt) {
		this.qtTotalAnt = qtTotalAnt;
	}

	@Column(name = "QT_TOTAL", precision = 14, scale = 4)
	public BigDecimal getQtTotal() {
		return this.qtTotal;
	}

	public void setQtTotal(BigDecimal qtTotal) {
		this.qtTotal = qtTotal;
	}
	
	@Column(name = "LANCAMENTO")
	public String getLancamento() {
		return this.lancamento;
	}

	public void setLancamento(String lancamento) {
		this.lancamento = lancamento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_CADASTRO", length = 23)
	public Date getDthrCadastro() {
		return this.dthrCadastro;
	}

	public void setDthrCadastro(Date dthrCadastro) {
		this.dthrCadastro = dthrCadastro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gt")
	public OmGt getOmGt() {
		return this.omGt;
	}

	public void setOmGt(OmGt omGt) {
		this.omGt = omGt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pt", nullable = true)
	public OmPt getOmPt() {
		return this.omPt;
	}

	public void setOmPt(OmPt omPt) {
		this.omPt = omPt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_turno", nullable = true)
	public DwTurno getDwTurno() {
		return this.dwTurno;
	}

	public void setDwTurno(DwTurno dwTurno) {
		this.dwTurno = dwTurno;
	}
	@Column(name = "ano")
	public Integer getAno() {
		return this.ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estlocalpro", nullable = true)
	public DwEstlocalpro getDwEstlocalpro() {
		return this.dwEstlocalpro;
	}

	public void setDwEstlocalpro(DwEstlocalpro dwEstlocalpro) {
		this.dwEstlocalpro = dwEstlocalpro;
	}
	
}
