package idw.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 29/01/2010 13:18:21 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwFolhamoncompTemplate;


/**
 * DwFolhamoncomp generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_folhamoncomp")
public class DwFolhamoncomp extends DwFolhamoncompTemplate implements java.io.Serializable {

	private long idFolhamoncomp;
	private OmProduto omProduto;
	private DwFolhamon dwFolhamon;
	private String dsMon;
	private Integer ordem;
	private Boolean isAceitarAlter;
	private Integer qtAmontar;
	
	private Boolean isAvaliarlimites;
	private Integer limiteMinCb;
	private Integer limiteMaxCb;
	private Integer tpValidacao;

	private Boolean isAceitarNsDesconhecido;
	
	private String mascara;
	
	public DwFolhamoncomp() {
	}

	public DwFolhamoncomp(long idFolhamoncomp, OmProduto omProduto) {
		this.idFolhamoncomp = idFolhamoncomp;
		this.omProduto = omProduto;
	}

	public DwFolhamoncomp(long idFolhamoncomp, OmProduto omProduto,
			DwFolhamon dwFolhamon, String dsMon, Integer ordem,
			Boolean isAceitarAlter) {
		this.idFolhamoncomp = idFolhamoncomp;
		this.omProduto = omProduto;
		this.dwFolhamon = dwFolhamon;
		this.dsMon = dsMon;
		this.ordem = ordem;
		this.isAceitarAlter = isAceitarAlter;
	}

	@Id	
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_FOLHAMONCOMP_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_FOLHAMONCOMP_SEQ", sequenceName = "DW_FOLHAMONCOMP_SEQ")
	@Column(name = "id_folhamoncomp", nullable = false)
	public long getIdFolhamoncomp() {
		return this.idFolhamoncomp;
	}

	public void setIdFolhamoncomp(long idFolhamoncomp) {
		this.idFolhamoncomp = idFolhamoncomp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produtoFilho", nullable = false)
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_folhamon")
	public DwFolhamon getDwFolhamon() {
		return this.dwFolhamon;
	}

	public void setDwFolhamon(DwFolhamon dwFolhamon) {
		this.dwFolhamon = dwFolhamon;
	}

	@Column(name = "ds_mon", length = 40)
	public String getDsMon() {
		return this.dsMon;
	}

	public void setDsMon(String dsMon) {
		this.dsMon = dsMon;
	}

	@Column(name = "ordem")
	public Integer getOrdem() {
		return this.ordem;
	}

	public void setOrdem(Integer ordem) {
		this.ordem = ordem;
	}

	@Column(name = "is_aceitarAlter")
	public Boolean getIsAceitarAlter() {
		return this.isAceitarAlter;
	}

	public void setIsAceitarAlter(Boolean isAceitarAlter) {
		this.isAceitarAlter = isAceitarAlter;
	}

	@Column(name = "QT_AMONTAR")
	public Integer getQtAmontar() {
		return this.qtAmontar;
	}

	public void setQtAmontar(Integer valor) {
		this.qtAmontar = valor;
	}

	@Column(name = "IS_AVALIARLIMITES")
	public Boolean getIsAvaliarlimites() {
		return isAvaliarlimites;
	}

	public void setIsAvaliarlimites(Boolean isAvaliarlimites) {
		this.isAvaliarlimites = isAvaliarlimites;
	}

	@Column(name = "LIMITE_MIN_CB")
	public Integer getLimiteMinCb() {
		return limiteMinCb;
	}

	public void setLimiteMinCb(Integer limiteMinCb) {
		this.limiteMinCb = limiteMinCb;
	}

	@Column(name = "LIMITE_MAX_CB")
	public Integer getLimiteMaxCb() {
		return limiteMaxCb;
	}

	public void setLimiteMaxCb(Integer limiteMaxCb) {
		this.limiteMaxCb = limiteMaxCb;
	}

	@Column(name = "TP_VALIDACAO")
	public Integer getTpValidacao() {
		return tpValidacao;
	}

	public void setTpValidacao(Integer tpValidacao) {
		this.tpValidacao = tpValidacao;
	}



	@Column(name = "IS_ACEITAR_NS_DESCONHECIDO")
	public Boolean getIsAceitarNsDesconhecido() {
		return isAceitarNsDesconhecido;
	}

	public void setIsAceitarNsDesconhecido(Boolean isAceitarNSDesconhecido) {
		this.isAceitarNsDesconhecido = isAceitarNSDesconhecido;
	}

	@Column(name = "mascara", length = 100)
	public String getMascara() {
		return mascara;
	}

	public void setMascara(String mascara) {
		this.mascara = mascara;
	}

	
}
