package idw.model.pojos;
// Generated 28/07/2011 10:26:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.DwFolharapTemplate;

/**
 * DwFolharap generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "DW_FOLHARAP")
public class DwFolharap extends DwFolharapTemplate implements java.io.Serializable {

	private Long idFolharap;
	private DwFolha dwFolha;
	private DwRap dwRap;
	private BigDecimal qtUsada;
	private BigDecimal segTempopreparacao;
	private Set<DwFolharapcom> dwFolharapcoms = new HashSet<DwFolharapcom>(0);

	public DwFolharap() {
	}

	public DwFolharap(Long idFolharap, DwFolha dwFolha, DwRap dwRap) {
		this.idFolharap = idFolharap;
		this.dwFolha = dwFolha;
		this.dwRap = dwRap;
	}

	public DwFolharap(Long idFolharap, DwFolha dwFolha, DwRap dwRap,
			BigDecimal qtUsada, BigDecimal segTempopreparacao,
			Set<DwFolharapcom> dwFolharapcoms) {
		this.idFolharap = idFolharap;
		this.dwFolha = dwFolha;
		this.dwRap = dwRap;
		this.qtUsada = qtUsada;
		this.segTempopreparacao = segTempopreparacao;
		this.dwFolharapcoms = dwFolharapcoms;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_FOLHARAP_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_FOLHARAP_SEQ", sequenceName = "DW_FOLHARAP_SEQ")
	@Column(name = "ID_FOLHARAP", unique = true, nullable = false, precision = 63, scale = 0)
	public Long getIdFolharap() {
		return this.idFolharap;
	}

	public void setIdFolharap(Long idFolharap) {
		this.idFolharap = idFolharap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FOLHA", nullable = false)
	public DwFolha getDwFolha() {
		return this.dwFolha;
	}

	public void setDwFolha(DwFolha dwFolha) {
		this.dwFolha = dwFolha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RAP", nullable = false)
	public DwRap getDwRap() {
		return this.dwRap;
	}

	public void setDwRap(DwRap dwRap) {
		this.dwRap = dwRap;
	}

	@Column(name = "QT_USADA", precision = 22, scale = 0)
	public BigDecimal getQtUsada() {
		return this.qtUsada;
	}

	public void setQtUsada(BigDecimal qtUsada) {
		this.qtUsada = qtUsada;
	}

	@Column(name = "SEG_TEMPOPREPARACAO", precision = 20, scale = 10)
	public BigDecimal getSegTempopreparacao() {
		return this.segTempopreparacao;
	}

	public void setSegTempopreparacao(BigDecimal segTempopreparacao) {
		this.segTempopreparacao = segTempopreparacao;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwFolharap")
	public Set<DwFolharapcom> getDwFolharapcoms() {
		return this.dwFolharapcoms;
	}

	public void setDwFolharapcoms(Set<DwFolharapcom> dwFolharapcoms) {
		this.dwFolharapcoms = dwFolharapcoms;
	}

}
