package idw.model.pojos;
// Generated 12/09/2011 09:05:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import idw.model.pojos.template.DwFolhaiacTemplate;

/**
 * DwFolhaiac generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "DW_FOLHAIAC")
public class DwFolhaiac extends DwFolhaiacTemplate implements java.io.Serializable {

	private Long idFolhaiac;
	private OmProduto omProduto;
	private OmProduto omProdutodois;
	private DwFolha dwFolha;
	private OmPrg omPrg;
	private BigDecimal qtAtiva;
	private BigDecimal qtMpporciclo;

	public DwFolhaiac() {
	}

	public DwFolhaiac(Long idFolhaiac, OmProduto omProduto, OmPrg omPrg) {
		this.idFolhaiac = idFolhaiac;
		this.omProduto = omProduto;
		this.omPrg = omPrg;
	}

	public DwFolhaiac(Long idFolhaiac, OmProduto omProduto, DwFolha dwFolha,
			OmPrg omPrg, BigDecimal qtAtiva) {
		this.idFolhaiac = idFolhaiac;
		this.omProduto = omProduto;
		this.dwFolha = dwFolha;
		this.omPrg = omPrg;
		this.qtAtiva = qtAtiva;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_FOLHAIAC_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_FOLHAIAC_SEQ", sequenceName = "DW_FOLHAIAC_SEQ")
	@Column(name = "ID_FOLHAIAC", unique = true, nullable = false, precision = 63, scale = 0)
	public Long getIdFolhaiac() {
		return this.idFolhaiac;
	}

	public void setIdFolhaiac(Long idFolhaiac) {
		this.idFolhaiac = idFolhaiac;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUTO", nullable = false)
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUTODOIS", nullable = true)
	public OmProduto getOmProdutodois() {
		return this.omProdutodois;
	}

	public void setOmProdutodois(OmProduto omProduto) {
		this.omProdutodois = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FOLHA")
	public DwFolha getDwFolha() {
		return this.dwFolha;
	}

	public void setDwFolha(DwFolha dwFolha) {
		this.dwFolha = dwFolha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRG", nullable = true)
	public OmPrg getOmPrg() {
		return this.omPrg;
	}

	public void setOmPrg(OmPrg omPrg) {
		this.omPrg = omPrg;
	}

	@Column(name = "QT_ATIVA", precision = 22, scale = 0)
	public BigDecimal getQtAtiva() {
		return this.qtAtiva;
	}

	public void setQtAtiva(BigDecimal qtAtiva) {
		this.qtAtiva = qtAtiva;
	}

	@Column(name = "QT_MPPORCICLO", precision = 22, scale = 0)
	public BigDecimal getQtMpporciclo() {
		return this.qtMpporciclo;
	}

	public void setQtMpporciclo(BigDecimal valor) {
		this.qtMpporciclo = valor;
	}
}
