package idw.model.pojos;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 18/01/2013 14:45:49 by Hibernate Tools 3.4.0.CR1

import idw.model.pojos.template.DwFolhamedtemphorcfgTemplate;

/**
 * DwFolhamedtemphorcfg generated by hbm2java
 */
@Entity
@Table(name = "DW_FOLHAMEDTEMPHORCFG")
public class DwFolhamedtemphorcfg extends DwFolhamedtemphorcfgTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5157454534180326560L;
	private BigDecimal idFolhamedtemphorcfg;
	private DwFolhamedtemhor dwFolhamedtemhor;
	private String dsCfg;
	private BigDecimal limInfTemp;
	private BigDecimal limSupTemp;
	private String corIntervalo;

	public DwFolhamedtemphorcfg() {
	}

	public DwFolhamedtemphorcfg(BigDecimal idFolhamedtemphorcfg,
			DwFolhamedtemhor dwFolhamedtemhor, String dsCfg, String corIntervalo) {
		this.idFolhamedtemphorcfg = idFolhamedtemphorcfg;
		this.dwFolhamedtemhor = dwFolhamedtemhor;
		this.dsCfg = dsCfg;
		this.corIntervalo = corIntervalo;
	}

	public DwFolhamedtemphorcfg(BigDecimal idFolhamedtemphorcfg,
			DwFolhamedtemhor dwFolhamedtemhor, String dsCfg,
			BigDecimal limInfTemp, BigDecimal limSupTemp, String corIntervalo) {
		this.idFolhamedtemphorcfg = idFolhamedtemphorcfg;
		this.dwFolhamedtemhor = dwFolhamedtemhor;
		this.dsCfg = dsCfg;
		this.limInfTemp = limInfTemp;
		this.limSupTemp = limSupTemp;
		this.corIntervalo = corIntervalo;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_FOLHAMEDTEMPHORCFG_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_FOLHAMEDTEMPHORCFG_SEQ", sequenceName = "DW_FOLHAMEDTEMPHORCFG_SEQ")
	@Column(name = "ID_FOLHAMEDTEMPHORCFG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdFolhamedtemphorcfg() {
		return this.idFolhamedtemphorcfg;
	}

	public void setIdFolhamedtemphorcfg(BigDecimal idFolhamedtemphorcfg) {
		this.idFolhamedtemphorcfg = idFolhamedtemphorcfg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FOLHAMEDTEMPHORARIO", nullable = false)
	public DwFolhamedtemhor getDwFolhamedtemhor() {
		return this.dwFolhamedtemhor;
	}

	public void setDwFolhamedtemhor(DwFolhamedtemhor dwFolhamedtemhor) {
		this.dwFolhamedtemhor = dwFolhamedtemhor;
	}

	@Column(name = "DS_CFG", nullable = false, length = 40)
	public String getDsCfg() {
		return this.dsCfg;
	}

	public void setDsCfg(String dsCfg) {
		this.dsCfg = dsCfg;
	}

	@Column(name = "LIM_INF_TEMP", precision = 20, scale = 10)
	public BigDecimal getLimInfTemp() {
		return this.limInfTemp;
	}

	public void setLimInfTemp(BigDecimal limInfTemp) {
		this.limInfTemp = limInfTemp;
	}

	@Column(name = "LIM_SUP_TEMP", precision = 20, scale = 10)
	public BigDecimal getLimSupTemp() {
		return this.limSupTemp;
	}

	public void setLimSupTemp(BigDecimal limSupTemp) {
		this.limSupTemp = limSupTemp;
	}

	@Column(name = "COR_INTERVALO", nullable = false, length = 11)
	public String getCorIntervalo() {
		return this.corIntervalo;
	}

	public void setCorIntervalo(String corIntervalo) {
		this.corIntervalo = corIntervalo;
	}

}
