package idw.model.pojos;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwFtSubTemplate;


/**
 * DwFtSub generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_ft_sub")
public class DwFtSub extends DwFtSubTemplate implements java.io.Serializable {

	private long idFtSub;
	private OmProduto omProduto;
	private DwFtParam dwFtParam;
	private DwFtEtapa dwFtEtapa;
	private String dsSub;
	private Byte tpFtSub;
	private Byte tpStatus;
	private Integer ms;
	private Integer x41;
	private Integer x42;
	private Integer x45;
	private Integer x46;
	private Integer x47;
	private Integer x48;
	private Integer x49;
	private BigDecimal y81;
	private BigDecimal y82;
	private BigDecimal y83;
	private BigDecimal y84;
	private Byte tpFtParam;
	private BigDecimal vlFtParam;
	private Byte stFtParam;
	private Set<DwFtSubparam> dwFtSubparams = new HashSet<DwFtSubparam>(0);
	private Set<DwTestesub> dwTestesubs = new HashSet<DwTestesub>(0);

	public DwFtSub() {
	}

	public DwFtSub(long idFtSub, DwFtEtapa dwFtEtapa) {
		this.idFtSub = idFtSub;
		this.dwFtEtapa = dwFtEtapa;
	}

	public DwFtSub(long idFtSub, OmProduto omProduto, DwFtParam dwFtParam,
			DwFtEtapa dwFtEtapa, String dsSub, Byte tpFtSub, Byte tpStatus,
			Integer ms, Integer x41, Integer x42, BigDecimal y81,
			BigDecimal y82, BigDecimal y83, BigDecimal y84, Byte tpFtParam,
			BigDecimal vlFtParam, Byte stFtParam,
			Set<DwFtSubparam> dwFtSubparams) {
		this.idFtSub = idFtSub;
		this.omProduto = omProduto;
		this.dwFtParam = dwFtParam;
		this.dwFtEtapa = dwFtEtapa;
		this.dsSub = dsSub;
		this.tpFtSub = tpFtSub;
		this.tpStatus = tpStatus;
		this.ms = ms;
		this.x41 = x41;
		this.x42 = x42;
		this.y81 = y81;
		this.y82 = y82;
		this.y83 = y83;
		this.y84 = y84;
		this.tpFtParam = tpFtParam;
		this.vlFtParam = vlFtParam;
		this.stFtParam = stFtParam;
		this.dwFtSubparams = dwFtSubparams;
	}

	@Id	
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_FT_SUB_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_FT_SUB_SEQ", sequenceName = "DW_FT_SUB_SEQ")
	@Column(name = "id_ft_sub", nullable = false)
	public long getIdFtSub() {
		return this.idFtSub;
	}

	public void setIdFtSub(long idFtSub) {
		this.idFtSub = idFtSub;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produto")
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ft_param")
	public DwFtParam getDwFtParam() {
		return this.dwFtParam;
	}

	public void setDwFtParam(DwFtParam dwFtParam) {
		this.dwFtParam = dwFtParam;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ft_etapa", nullable = false)
	public DwFtEtapa getDwFtEtapa() {
		return this.dwFtEtapa;
	}

	public void setDwFtEtapa(DwFtEtapa dwFtEtapa) {
		this.dwFtEtapa = dwFtEtapa;
	}

	@Column(name = "ds_sub", length = 100)
	public String getDsSub() {
		return this.dsSub;
	}

	public void setDsSub(String dsSub) {
		this.dsSub = dsSub;
	}

	@Column(name = "tp_ft_sub")
	public Byte getTpFtSub() {
		return this.tpFtSub;
	}

	public void setTpFtSub(Byte tpFtSub) {
		this.tpFtSub = tpFtSub;
	}

	@Column(name = "tp_status")
	public Byte getTpStatus() {
		return this.tpStatus;
	}

	public void setTpStatus(Byte tpStatus) {
		this.tpStatus = tpStatus;
	}

	@Column(name = "ms")
	public Integer getMs() {
		return this.ms;
	}

	public void setMs(Integer ms) {
		this.ms = ms;
	}

	@Column(name = "x41")
	public Integer getX41() {
		return this.x41;
	}

	public void setX41(Integer x41) {
		this.x41 = x41;
	}

	@Column(name = "x42")
	public Integer getX42() {
		return this.x42;
	}

	public void setX42(Integer x42) {
		this.x42 = x42;
	}
	@Column(name = "x45")
	public Integer getX45() {
		return this.x45;
	}

	public void setX45(Integer x45) {
		this.x45 = x45;
	}
	@Column(name = "x46")
	public Integer getX46() {
		return this.x46;
	}

	public void setX46(Integer x46) {
		this.x46 = x46;
	}
	@Column(name = "x47")
	public Integer getX47() {
		return this.x47;
	}

	public void setX47(Integer x47) {
		this.x47 = x47;
	}
	@Column(name = "x48")
	public Integer getX48() {
		return this.x48;
	}
	public void setX48(Integer x48) {
		this.x48 = x48;
	}
	@Column(name = "x49")
	public Integer getX49() {
		return this.x49;
	}

	public void setX49(Integer x49) {
		this.x49 = x49;
	}
	@Column(name = "y81", precision = 10, scale = 3)
	public BigDecimal getY81() {
		return this.y81;
	}

	public void setY81(BigDecimal y81) {
		this.y81 = y81;
	}

	@Column(name = "y82", precision = 10, scale = 3)
	public BigDecimal getY82() {
		return this.y82;
	}

	public void setY82(BigDecimal y82) {
		this.y82 = y82;
	}

	@Column(name = "y83", precision = 10, scale = 3)
	public BigDecimal getY83() {
		return this.y83;
	}

	public void setY83(BigDecimal y83) {
		this.y83 = y83;
	}

	@Column(name = "y84", precision = 10, scale = 3)
	public BigDecimal getY84() {
		return this.y84;
	}

	public void setY84(BigDecimal y84) {
		this.y84 = y84;
	}

	@Column(name = "tp_ft_param")
	public Byte getTpFtParam() {
		return this.tpFtParam;
	}

	public void setTpFtParam(Byte tpFtParam) {
		this.tpFtParam = tpFtParam;
	}

	@Column(name = "vl_ft_param", precision = 10, scale = 3)
	public BigDecimal getVlFtParam() {
		return this.vlFtParam;
	}

	public void setVlFtParam(BigDecimal vlFtParam) {
		this.vlFtParam = vlFtParam;
	}

	@Column(name = "st_ft_param")
	public Byte getStFtParam() {
		return this.stFtParam;
	}

	public void setStFtParam(Byte stFtParam) {
		this.stFtParam = stFtParam;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwFtSub")
	public Set<DwFtSubparam> getDwFtSubparams() {
		return this.dwFtSubparams;
	}

	public void setDwFtSubparams(Set<DwFtSubparam> dwFtSubparams) {
		this.dwFtSubparams = dwFtSubparams;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwFtSub")
	public Set<DwTestesub> getDwTestesubs() {
		return this.dwTestesubs;
	}

	public void setDwTestesubs(Set<DwTestesub> dwTestesub) {
		this.dwTestesubs = dwTestesub;
	}
}
