package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwFtEtapaTemplate;


/**
 * DwFtEtapa generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_ft_etapa")
public class DwFtEtapa extends DwFtEtapaTemplate implements java.io.Serializable {

	private long idFtEtapa;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String dsEtapa;
	private String dsMensagemok;
	private String dsMensagemnok;
	private String cdEtapa;
	private Long revisao;
	private Byte stAtivo;
	private Date dtRevisao;
	private Date dtStativo;
	private Set<DwFtSub> dwFtSubs = new HashSet<DwFtSub>(0);

	public DwFtEtapa() {
	}

	public DwFtEtapa(long idFtEtapa, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idFtEtapa = idFtEtapa;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public DwFtEtapa(long idFtEtapa, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String dsEtapa, String dsMensagemok,
			String dsMensagemnok, String cdEtapa, Long revisao, Byte stAtivo,
			Date dtRevisao, Date dtStativo, Set<DwFtSub> dwFtSubs) {
		this.idFtEtapa = idFtEtapa;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.dsEtapa = dsEtapa;
		this.dsMensagemok = dsMensagemok;
		this.dsMensagemnok = dsMensagemnok;
		this.cdEtapa = cdEtapa;
		this.revisao = revisao;
		this.stAtivo = stAtivo;
		this.dtRevisao = dtRevisao;
		this.dtStativo = dtStativo;
		this.dwFtSubs = dwFtSubs;
	}

	@Id	
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_FT_ETAPA_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_FT_ETAPA_SEQ", sequenceName = "DW_FT_ETAPA_SEQ")
	@Column(name = "id_ft_etapa", nullable = false)
	public long getIdFtEtapa() {
		return this.idFtEtapa;
	}

	public void setIdFtEtapa(long idFtEtapa) {
		this.idFtEtapa = idFtEtapa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "ds_etapa", length = 40)
	public String getDsEtapa() {
		return this.dsEtapa;
	}

	public void setDsEtapa(String dsEtapa) {
		this.dsEtapa = dsEtapa;
	}

	@Column(name = "ds_mensagemok", length = 100)
	public String getDsMensagemok() {
		return this.dsMensagemok;
	}

	public void setDsMensagemok(String dsMensagemok) {
		this.dsMensagemok = dsMensagemok;
	}

	@Column(name = "ds_mensagemnok", length = 100)
	public String getDsMensagemnok() {
		return this.dsMensagemnok;
	}

	public void setDsMensagemnok(String dsMensagemnok) {
		this.dsMensagemnok = dsMensagemnok;
	}

	@Column(name = "cd_etapa", length = 30)
	public String getCdEtapa() {
		return this.cdEtapa;
	}

	public void setCdEtapa(String cdEtapa) {
		this.cdEtapa = cdEtapa;
	}

	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwFtEtapa")
	public Set<DwFtSub> getDwFtSubs() {
		return this.dwFtSubs;
	}

	public void setDwFtSubs(Set<DwFtSub> dwFtSubs) {
		this.dwFtSubs = dwFtSubs;
	}

}
