package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 19/02/2016 13:57:41 by Hibernate Tools 4.0.0

import idw.model.pojos.template.DwOperacaoTemplate;

/**
 * DwOperacao generated by hbm2java
 */
@Entity
@Table(name = "dw_operacao")
public class DwOperacao extends DwOperacaoTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idOperacao;
	private OmTppt omTppt;
	private OmProduto omProdutoByIdProdutosemiacabado;
	private OmProduto omProdutoByIdProdutoacabado;
	private OmGt omGt;
	private OmUsr omUsrByIdUsrstativo;
	private OmPt omPt;
	private DwTOperacao dwTOperacao;
	private OmUsr omUsrByIdUsrrevisao;
	private BigDecimal segCiclopadrao;
	private String cdOperacao;
	private Long revisao;
	private Byte stAtivo;
	private Date dtStativo;
	private Date dtRevisao;
	private String dsOperacao;
	private Integer grupooperacoes;
	private BigDecimal x;
	private BigDecimal y;
	
	
	private Byte tpProducao;
	private Byte tpColeta;

	
	
	private Set<DwOperacaopredecessora> dwOperacaopredecessorasForIdOperacaoanterior = new HashSet<DwOperacaopredecessora>(
			0);
	private Set<DwOperacaorap> dwOperacaoraps = new HashSet<DwOperacaorap>(0);
	private Set<DwOperacaopredecessora> dwOperacaopredecessorasForIdOperacao = new HashSet<DwOperacaopredecessora>(0);
	private Set<DwOperacaocomp> dwOperacaocomps = new HashSet<DwOperacaocomp>(0);
	private Set<DwOperacaomidia> dwOperacaomidias = new HashSet<DwOperacaomidia>(0);
	private Set<DwFolhaoperacao> dwFolhaoperacoes = new HashSet<DwFolhaoperacao>(0);

	public DwOperacao() {
	}

	public DwOperacao(Long idOperacao, OmProduto omProdutoByIdProdutosemiacabado, OmProduto omProdutoByIdProdutoacabado,
			DwTOperacao dwTOperacao) {
		this.idOperacao = idOperacao;
		this.omProdutoByIdProdutosemiacabado = omProdutoByIdProdutosemiacabado;
		this.omProdutoByIdProdutoacabado = omProdutoByIdProdutoacabado;
		this.dwTOperacao = dwTOperacao;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_OPERACAO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_OPERACAO_SEQ", sequenceName = "DW_OPERACAO_SEQ")
	@Column(name = "id_operacao", unique = true, nullable = false)
	public Long getIdOperacao() {
		return this.idOperacao;
	}

	public void setIdOperacao(Long idOperacao) {
		this.idOperacao = idOperacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tppt")
	public OmTppt getOmTppt() {
		return this.omTppt;
	}

	public void setOmTppt(OmTppt omTppt) {
		this.omTppt = omTppt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produtosemiacabado", nullable = false)
	public OmProduto getOmProdutoByIdProdutosemiacabado() {
		return this.omProdutoByIdProdutosemiacabado;
	}

	public void setOmProdutoByIdProdutosemiacabado(OmProduto omProdutoByIdProdutosemiacabado) {
		this.omProdutoByIdProdutosemiacabado = omProdutoByIdProdutosemiacabado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produtoacabado", nullable = false)
	public OmProduto getOmProdutoByIdProdutoacabado() {
		return this.omProdutoByIdProdutoacabado;
	}

	public void setOmProdutoByIdProdutoacabado(OmProduto omProdutoByIdProdutoacabado) {
		this.omProdutoByIdProdutoacabado = omProdutoByIdProdutoacabado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gtfase")
	public OmGt getOmGt() {
		return this.omGt;
	}

	public void setOmGt(OmGt omGt) {
		this.omGt = omGt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo")
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pt")
	public OmPt getOmPt() {
		return this.omPt;
	}

	public void setOmPt(OmPt omPt) {
		this.omPt = omPt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_toperacao", nullable = false)
	public DwTOperacao getDwTOperacao() {
		return this.dwTOperacao;
	}

	public void setDwTOperacao(DwTOperacao dwTOperacao) {
		this.dwTOperacao = dwTOperacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao")
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "seg_ciclopadrao", precision = 20, scale = 10)
	public BigDecimal getSegCiclopadrao() {
		return this.segCiclopadrao;
	}

	public void setSegCiclopadrao(BigDecimal segCiclopadrao) {
		this.segCiclopadrao = segCiclopadrao;
	}

	@Column(name = "cd_operacao", length = 60)
	public String getCdOperacao() {
		return this.cdOperacao;
	}

	public void setCdOperacao(String cdOperacao) {
		this.cdOperacao = cdOperacao;
	}

	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 29)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 29)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Column(name = "ds_operacao", length = 256)
	public String getDsOperacao() {
		return this.dsOperacao;
	}

	public void setDsOperacao(String dsOperacao) {
		this.dsOperacao = dsOperacao;
	}

	@Column(name = "grupooperacoes")
	public Integer getGrupooperacoes() {
		return this.grupooperacoes;
	}

	public void setGrupooperacoes(Integer grupooperacoes) {
		this.grupooperacoes = grupooperacoes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwOperacaoByIdOperacaoanterior")
	public Set<DwOperacaopredecessora> getDwOperacaopredecessorasForIdOperacaoanterior() {
		return this.dwOperacaopredecessorasForIdOperacaoanterior;
	}

	public void setDwOperacaopredecessorasForIdOperacaoanterior(
			Set<DwOperacaopredecessora> dwOperacaopredecessorasForIdOperacaoanterior) {
		this.dwOperacaopredecessorasForIdOperacaoanterior = dwOperacaopredecessorasForIdOperacaoanterior;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwOperacao")
	public Set<DwOperacaorap> getDwOperacaoraps() {
		return this.dwOperacaoraps;
	}

	public void setDwOperacaoraps(Set<DwOperacaorap> dwOperacaoraps) {
		this.dwOperacaoraps = dwOperacaoraps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwOperacaoByIdOperacao")
	public Set<DwOperacaopredecessora> getDwOperacaopredecessorasForIdOperacao() {
		return this.dwOperacaopredecessorasForIdOperacao;
	}

	public void setDwOperacaopredecessorasForIdOperacao(
			Set<DwOperacaopredecessora> dwOperacaopredecessorasForIdOperacao) {
		this.dwOperacaopredecessorasForIdOperacao = dwOperacaopredecessorasForIdOperacao;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwOperacao")
	public Set<DwOperacaocomp> getDwOperacaocomps() {
		return this.dwOperacaocomps;
	}

	public void setDwOperacaocomps(Set<DwOperacaocomp> dwOperacaocomps) {
		this.dwOperacaocomps = dwOperacaocomps;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwOperacao")
	public Set<DwOperacaomidia> getDwOperacaomidias() {
		return this.dwOperacaomidias;
	}

	public void setDwOperacaomidias(Set<DwOperacaomidia> dwOperacaomidias) {
		this.dwOperacaomidias = dwOperacaomidias;
	}
	
	@Column(name = "x", precision = 10, scale = 3)
	public BigDecimal getX() {
		return this.x;
	}

	public void setX(BigDecimal x) {
		this.x = x;
	}

	@Column(name = "y", precision = 10, scale = 3)
	public BigDecimal getY() {
		return this.y;
	}

	public void setY(BigDecimal y) {
		this.y = y;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwOperacao")
	public Set<DwFolhaoperacao> getDwFolhaoperacoes() {
		return this.dwFolhaoperacoes;
	}

	public void setDwFolhaoperacoes(Set<DwFolhaoperacao> dwFolhaoperacao) {
		this.dwFolhaoperacoes = dwFolhaoperacao;
	}
	@Column(name = "tp_producao")
	public Byte getTpProducao() {
		return tpProducao;
	}

	public void setTpProducao(Byte tpProducao) {
		this.tpProducao = tpProducao;
	}

	@Column(name = "tp_coleta")
	public Byte getTpColeta() {
		return tpColeta;
	}

	public void setTpColeta(Byte tpColeta) {
		this.tpColeta = tpColeta;
	}
}
