package idw.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 29/01/2010 13:18:21 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwPassmonTemplate;


/**
 * DwPassmon generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_passmon")
public class DwPassmon extends DwPassmonTemplate implements java.io.Serializable {

	private long idPassmon;
	private DwPassagem dwPassagem;
	private OmProduto omProduto;
	private Boolean isAlternativo;
	private String dsMon;
	private String cb;
	private Integer ordem;

	public DwPassmon() {
	}

	public DwPassmon(long idPassmon, DwPassagem dwPassagem, OmProduto omProduto) {
		this.idPassmon = idPassmon;
		this.dwPassagem = dwPassagem;
		this.omProduto = omProduto;
	}

	public DwPassmon(long idPassmon, DwPassagem dwPassagem,
			OmProduto omProduto, Boolean isAlternativo, String dsMon) {
		this.idPassmon = idPassmon;
		this.dwPassagem = dwPassagem;
		this.omProduto = omProduto;
		this.isAlternativo = isAlternativo;
		this.dsMon = dsMon;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_PASSMON_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_PASSMON_SEQ", sequenceName = "DW_PASSMON_SEQ")
	@Column(name = "id_passmon", unique = true, nullable = false)
	public long getIdPassmon() {
		return this.idPassmon;
	}

	public void setIdPassmon(long idPassmon) {
		this.idPassmon = idPassmon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_passagem", nullable = false)
	public DwPassagem getDwPassagem() {
		return this.dwPassagem;
	}

	public void setDwPassagem(DwPassagem dwPassagem) {
		this.dwPassagem = dwPassagem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produto", nullable = false)
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@Column(name = "is_alternativo")
	public Boolean getIsAlternativo() {
		return this.isAlternativo;
	}

	public void setIsAlternativo(Boolean isAlternativo) {
		this.isAlternativo = isAlternativo;
	}

	@Column(name = "ds_mon", length = 40)
	public String getDsMon() {
		return this.dsMon;
	}

	public void setDsMon(String dsMon) {
		this.dsMon = dsMon;
	}

	@Column(name = "cb", length = 40)
	public String getCb() {
		return this.cb;
	}

	public void setCb(String ds) {
		this.cb = ds;
	}

	@Column(name = "ordem")
	public Integer getOrdem() {
		return ordem;
	}

	public void setOrdem(Integer ordem) {
		this.ordem = ordem;
	}
	
	
	
}
