package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.DwPasstfseTemplate;

/**
 * DwPasstfse generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "DW_PASSTFSE")
public class DwPasstfse extends DwPasstfseTemplate implements java.io.Serializable {

	private long idPasstfse;
	private Integer stSubetapa;
	private Integer ordemsubetapa;
	private Date dthrIsubetapa;
	private BigDecimal msDthrisubetapa;
	private Date dthrFsubetapa;
	private BigDecimal msDthrfsubetapa;
	private Date dthrIposfalha;
	private BigDecimal msDthriposfalha;
	private Date dthrFposfalha;
	private BigDecimal msDthrfposfalha;
	private DwFtSub dwFtSub;
	private DwPasstf dwPasstf;
	private Set<DwPasstfsepm> dwPasstfsepms = new HashSet<DwPasstfsepm>(0);
	private Set<DwPasstfsepmView> dwPasstfsepmViews = new HashSet<DwPasstfsepmView>(0);

	public DwPasstfse() {
	}

	public DwPasstfse(long idPasstfse, DwFtSub dwFtSub, DwPasstf dwPasstf) {
		this.idPasstfse = idPasstfse;
		this.dwFtSub = dwFtSub;
		this.dwPasstf = dwPasstf;
	}

	public DwPasstfse(long idPasstfse, DwFtSub dwFtSub,
			DwPasstf dwPasstf, Integer stSubetapa, Date dthrIsubetapa,
			BigDecimal msDthrisubetapa, Date dthrFsubetapa,
			BigDecimal msDthrfsubetapa, Date dthrIposfalha,
			BigDecimal msDthriposfalha, Date dthrFposfalha,
			BigDecimal msDthrfposfalha, Set<DwPasstfsepm> dwPasstfsepms) {
		this.idPasstfse = idPasstfse;
		this.dwFtSub = dwFtSub;
		this.dwPasstf = dwPasstf;
		this.stSubetapa = stSubetapa;
		this.dthrIsubetapa = dthrIsubetapa;
		this.msDthrisubetapa = msDthrisubetapa;
		this.dthrFsubetapa = dthrFsubetapa;
		this.msDthrfsubetapa = msDthrfsubetapa;
		this.dthrIposfalha = dthrIposfalha;
		this.msDthriposfalha = msDthriposfalha;
		this.dthrFposfalha = dthrFposfalha;
		this.msDthrfposfalha = msDthrfposfalha;
		this.dwPasstfsepms = dwPasstfsepms;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_PASSTFSE_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_PASSTFSE_SEQ", sequenceName = "DW_PASSTFSE_SEQ")
	@Column(name = "ID_PASSTFSE", unique = true, nullable = false, precision = 22, scale = 0)
	public long getIdPasstfse() {
		return this.idPasstfse;
	}

	public void setIdPasstfse(long idPasstfse) {
		this.idPasstfse = idPasstfse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FT_SUB", nullable = false)
	public DwFtSub getDwFtSub() {
		return this.dwFtSub;
	}

	public void setDwFtSub(DwFtSub dwFtSub) {
		this.dwFtSub = dwFtSub;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PASSTF", nullable = false)
	public DwPasstf getDwPasstf() {
		return this.dwPasstf;
	}

	public void setDwPasstf(DwPasstf dwPasstf) {
		this.dwPasstf = dwPasstf;
	}

	@Column(name = "ST_SUBETAPA")
	public Integer getStSubetapa() {
		return this.stSubetapa;
	}

	public void setStSubetapa(Integer stSubetapa) {
		this.stSubetapa = stSubetapa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_ISUBETAPA")
	public Date getDthrIsubetapa() {
		return this.dthrIsubetapa;
	}

	public void setDthrIsubetapa(Date dthrIsubetapa) {
		this.dthrIsubetapa = dthrIsubetapa;
	}

	@Column(name = "MS_DTHRISUBETAPA", precision = 22, scale = 0)
	public BigDecimal getMsDthrisubetapa() {
		return this.msDthrisubetapa;
	}

	public void setMsDthrisubetapa(BigDecimal msDthrisubetapa) {
		this.msDthrisubetapa = msDthrisubetapa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FSUBETAPA")
	public Date getDthrFsubetapa() {
		return this.dthrFsubetapa;
	}

	public void setDthrFsubetapa(Date dthrFsubetapa) {
		this.dthrFsubetapa = dthrFsubetapa;
	}

	@Column(name = "MS_DTHRFSUBETAPA", precision = 22, scale = 0)
	public BigDecimal getMsDthrfsubetapa() {
		return this.msDthrfsubetapa;
	}

	public void setMsDthrfsubetapa(BigDecimal msDthrfsubetapa) {
		this.msDthrfsubetapa = msDthrfsubetapa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_IPOSFALHA")
	public Date getDthrIposfalha() {
		return this.dthrIposfalha;
	}

	public void setDthrIposfalha(Date dthrIposfalha) {
		this.dthrIposfalha = dthrIposfalha;
	}

	@Column(name = "MS_DTHRIPOSFALHA", precision = 22, scale = 0)
	public BigDecimal getMsDthriposfalha() {
		return this.msDthriposfalha;
	}

	public void setMsDthriposfalha(BigDecimal msDthriposfalha) {
		this.msDthriposfalha = msDthriposfalha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FPOSFALHA")
	public Date getDthrFposfalha() {
		return this.dthrFposfalha;
	}

	public void setDthrFposfalha(Date dthrFposfalha) {
		this.dthrFposfalha = dthrFposfalha;
	}

	@Column(name = "MS_DTHRFPOSFALHA", precision = 22, scale = 0)
	public BigDecimal getMsDthrfposfalha() {
		return this.msDthrfposfalha;
	}

	public void setMsDthrfposfalha(BigDecimal msDthrfposfalha) {
		this.msDthrfposfalha = msDthrfposfalha;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwPasstfse")
	public Set<DwPasstfsepm> getDwPasstfsepms() {
		return this.dwPasstfsepms;
	}

	public void setDwPasstfsepms(Set<DwPasstfsepm> dwPasstfsepms) {
		this.dwPasstfsepms = dwPasstfsepms;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwPasstfse")
	public Set<DwPasstfsepmView> getDwPasstfsepmViews() {
		return this.dwPasstfsepmViews;
	}

	public void setDwPasstfsepmViews(Set<DwPasstfsepmView> dwPasstfsepms) {
		this.dwPasstfsepmViews = dwPasstfsepms;
	}

	@Column(name = "ordemsubetapa")
	public Integer getOrdemsubetapa() {
		return this.ordemsubetapa;
	}

	public void setOrdemsubetapa(Integer ordemsubetapa) {
		this.ordemsubetapa = ordemsubetapa;
	}

}
