package idw.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import idw.model.pojos.template.DwProcarhomTemplate;

/**
 * DwProcarhom generated by hbm2java
 */
@XmlRootElement
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_procarhom")
public class DwProcarhom extends DwProcarhomTemplate implements java.io.Serializable {

	private long idProcarhom;
	private OmCargo omCargo;
	private DwProcedimento dwProcedimento;
	private Short tpHomologacao;

	public DwProcarhom() {
	}

	public DwProcarhom(long idProcarhom) {
		this.idProcarhom = idProcarhom;
	}

	public DwProcarhom(long idProcarhom, OmCargo omCargo,
			DwProcedimento dwProcedimento, Short tpHomologacao) {
		this.idProcarhom = idProcarhom;
		this.omCargo = omCargo;
		this.dwProcedimento = dwProcedimento;
		this.tpHomologacao = tpHomologacao;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_PROCARHOM_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_PROCARHOM_SEQ", sequenceName = "DW_PROCARHOM_SEQ")
	@Column(name = "id_procarhom", unique = true, nullable = false)
	public long getIdProcarhom() {
		return this.idProcarhom;
	}

	public void setIdProcarhom(long idProcarhom) {
		this.idProcarhom = idProcarhom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cargo")
	public OmCargo getOmCargo() {
		return this.omCargo;
	}

	public void setOmCargo(OmCargo omCargo) {
		this.omCargo = omCargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_procedimento")
	public DwProcedimento getDwProcedimento() {
		return this.dwProcedimento;
	}

	public void setDwProcedimento(DwProcedimento dwProcedimento) {
		this.dwProcedimento = dwProcedimento;
	}

	@Column(name = "tp_homologacao")
	public Short getTpHomologacao() {
		return this.tpHomologacao;
	}

	public void setTpHomologacao(Short tpHomologacao) {
		this.tpHomologacao = tpHomologacao;
	}

}
