package idw.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 10/12/2014 11:50:58 by Hibernate Tools 4.0.0

import idw.model.pojos.template.DwRapGrupoTemplate;

/**
 * DwRapGrupo generated by hbm2java
 */
@Entity
@Table(name = "dw_rap_grupo")
public class DwRapGrupo extends DwRapGrupoTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idRapGrupo;
	private DwGrupoFerramenta dwGrupoFerramenta;
	private DwRap dwRap;

	public DwRapGrupo() {
	}

	public DwRapGrupo(Long idRapGrupo, DwGrupoFerramenta dwGrupoFerramenta,
			DwRap dwRap) {
		this.idRapGrupo = idRapGrupo;
		this.dwGrupoFerramenta = dwGrupoFerramenta;
		this.dwRap = dwRap;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_RAP_GRUPO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_RAP_GRUPO_SEQ", sequenceName = "DW_RAP_GRUPO_SEQ")
	@Column(name = "id_rap_grupo", unique = true, nullable = false)
	public Long getIdRapGrupo() {
		return this.idRapGrupo;
	}

	public void setIdRapGrupo(Long idRapGrupo) {
		this.idRapGrupo = idRapGrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_ferramenta", nullable = false)
	public DwGrupoFerramenta getDwGrupoFerramenta() {
		return this.dwGrupoFerramenta;
	}

	public void setDwGrupoFerramenta(DwGrupoFerramenta dwGrupoFerramenta) {
		this.dwGrupoFerramenta = dwGrupoFerramenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rap", nullable = false)
	public DwRap getDwRap() {
		return this.dwRap;
	}

	public void setDwRap(DwRap dwRap) {
		this.dwRap = dwRap;
	}

}
