package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwRotaTemplate;


/**
 * DwRota generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_rota", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "cd_rota", "revisao" }),
		@UniqueConstraint(columnNames = { "id_gt", "id_produto" }) })
public class DwRota extends DwRotaTemplate implements java.io.Serializable {

	private long idRota;
	private OmProduto omProduto;
	private OmGt omGt;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdRota;
	
	private Long revisao;
	private Date dtRevisao;
	private Byte stAtivo;
	private Date dtStativo;
	private String dsRota;
	private Boolean isModelo;
	private BigDecimal largura;
	private BigDecimal altura;
	private BigDecimal gridx;
	private BigDecimal gridy;
	private Set<DwRotapasso> dwRotapassos = new HashSet<DwRotapasso>(0);
	private Set<OmObj> omObjsForIdRota = new HashSet<OmObj>(0);
	private Boolean isPassaadiante;
	
	public DwRota() {
	}

	public DwRota(long idRota, OmProduto omProduto, OmGt omGt) {
		this.idRota = idRota;
		this.omProduto = omProduto;
		this.omGt = omGt;
	}

	public DwRota(long idRota, OmProduto omProduto, OmGt omGt, String cdRota,
			Long revisao, Date dtRevisao, Byte stAtivo, Date dtStativo,
			String dsRota, Boolean isModelo, Set<DwRotapasso> dwRotapassos, Set<OmObj> omObjsForIdRota,
			BigDecimal largura, BigDecimal altura, BigDecimal gridx,
			BigDecimal gridy) {
		this.idRota = idRota;
		this.omProduto = omProduto;
		this.omGt = omGt;
		this.cdRota = cdRota;
		this.revisao = revisao;
		this.dtRevisao = dtRevisao;
		this.stAtivo = stAtivo;
		this.dtStativo = dtStativo;
		this.dsRota = dsRota;
		this.isModelo = isModelo;
		this.largura = largura;
		this.altura = altura;
		this.gridx = gridx;
		this.gridy = gridy;
		this.dwRotapassos = dwRotapassos;
		this.omObjsForIdRota = omObjsForIdRota;
	}

	@Id	
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_ROTA_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_ROTA_SEQ", sequenceName = "DW_ROTA_SEQ")
	@Column(name = "id_rota", nullable = false)
	public long getIdRota() {
		return this.idRota;
	}

	public void setIdRota(long idRota) {
		this.idRota = idRota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produto", nullable = false)
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gt", nullable = false)
	public OmGt getOmGt() {
		return this.omGt;
	}

	public void setOmGt(OmGt omGt) {
		this.omGt = omGt;
	}

	@Column(name = "cd_rota", length = 30)
	public String getCdRota() {
		return this.cdRota;
	}

	public void setCdRota(String cdRota) {
		this.cdRota = cdRota;
	}

	@Override
	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "ds_rota", length = 40)
	public String getDsRota() {
		return this.dsRota;
	}

	public void setDsRota(String dsRota) {
		this.dsRota = dsRota;
	}

	@Column(name = "is_modelo")
	public Boolean getIsModelo() {
		return this.isModelo;
	}

	public void setIsModelo(Boolean isModelo) {
		this.isModelo = isModelo;
	}

	@Column(name = "largura", precision = 8, scale = 4)
	public BigDecimal getLargura() {
		return this.largura;
	}

	public void setLargura(BigDecimal largura) {
		this.largura = largura;
	}

	@Column(name = "altura", precision = 8, scale = 4)
	public BigDecimal getAltura() {
		return this.altura;
	}

	public void setAltura(BigDecimal altura) {
		this.altura = altura;
	}

	@Column(name = "gridx", precision = 8, scale = 4)
	public BigDecimal getGridx() {
		return this.gridx;
	}

	public void setGridx(BigDecimal gridx) {
		this.gridx = gridx;
	}

	@Column(name = "gridy", precision = 8, scale = 4)
	public BigDecimal getGridy() {
		return this.gridy;
	}

	public void setGridy(BigDecimal gridy) {
		this.gridy = gridy;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwRotaByIdRota")
	public Set<OmObj> getOmObjsForIdRota() {
		return this.omObjsForIdRota;
	}

	public void setOmObjsForIdRota(Set<OmObj> omObjsForIdRota) {
		this.omObjsForIdRota = omObjsForIdRota;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dwRota")
	public Set<DwRotapasso> getDwRotapassos() {
		return this.dwRotapassos;
	}

	public void setDwRotapassos(Set<DwRotapasso> dwRotapassos) {
		this.dwRotapassos = dwRotapassos;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}
	@Column(name = "is_passaadiante")
	public Boolean getIsPassaadiante() {
		return this.isPassaadiante;
	}

	public void setIsPassaadiante(Boolean isPassaadiante) {
		this.isPassaadiante = isPassaadiante;
	}

	
}
