package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import idw.model.pojos.template.DwTAreaTemplate;

/**
 * DwTArea generated by hbm2java
 */
//@Entity
//@Table(name = "DW_T_AREA")

@Entity
@Table(name = "dw_t_area", uniqueConstraints = @UniqueConstraint(columnNames = {
		"cd_area", "revisao" }))
public class DwTArea extends DwTAreaTemplate implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private long idArea;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdArea;
	private Long revisao;
	private String dsArea;
	private Byte stAtivo;
	private Date dtStativo;
	private Date dtRevisao;
	private String email;
	private Set<DwTParada> dwTParadas = new HashSet<DwTParada>(0);
	private Set<DwTRefugo> dwTRefugos = new HashSet<DwTRefugo>(0);
	private Set<DwProcativ> dwProcativs = new HashSet<DwProcativ>(0);

	public DwTArea() {
	}

	public DwTArea(long idArea) {
		this.idArea = idArea;
	}

	public DwTArea(long idArea, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdArea, Long revisao,
			String dsArea, Byte stAtivo, Date dthrStativo,
			Date dthrRevisao, Set<DwTParada> dwTParadas,
			Set<DwTRefugo> dwTRefugos) {
		this.idArea = idArea;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdArea = cdArea;
		this.revisao = revisao;
		this.dsArea = dsArea;
		this.stAtivo = stAtivo;
		this.dtStativo = dthrStativo;
		this.dtRevisao = dthrRevisao;
		this.dwTParadas = dwTParadas;
		this.dwTRefugos = dwTRefugos;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_T_AREA_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_T_AREA_SEQ", sequenceName = "DW_T_AREA_SEQ")
	@Column(name = "ID_AREA", unique = true, nullable = false, precision = 63, scale = 0)
	public long getIdArea() {
		return this.idArea;
	}


	public void setIdArea(long idArea) {
		this.idArea = idArea;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRSTATIVO")
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRREVISAO")
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "CD_AREA", length = 30)
	public String getCdArea() {
		return this.cdArea;
	}

	public void setCdArea(String cdArea) {
		this.cdArea = cdArea;
	}

	@Override
	@Column(name = "REVISAO")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "DS_AREA", length = 100)
	public String getDsArea() {
		return this.dsArea;
	}

	public void setDsArea(String dsArea) {
		this.dsArea = dsArea;
	}
	
	@Column(name = "EMAIL")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	@Column(name = "ST_ATIVO")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_STATIVO", length = 7)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_REVISAO", length = 7)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTArea")
	public Set<DwTParada> getDwTParadas() {
		return this.dwTParadas;
	}

	public void setDwTParadas(Set<DwTParada> dwTParadas) {
		this.dwTParadas = dwTParadas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTArea")
	public Set<DwTRefugo> getDwTRefugos() {
		return this.dwTRefugos;
	}

	public void setDwTRefugos(Set<DwTRefugo> dwTRefugos) {
		this.dwTRefugos = dwTRefugos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTArea")
	public Set<DwProcativ> getDwProcativs() {
		return this.dwProcativs;
	}

	public void setDwProcativs(Set<DwProcativ> dwProcativs) {
		this.dwProcativs = dwProcativs;
	}
}
