package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwTAcaoTemplate;


/**
 * DwTAcao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_t_acao", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_tppt", "cd_tacao", "revisao" }))
public class DwTAcao extends DwTAcaoTemplate implements java.io.Serializable {

	private long idTacao;
	private OmTppt omTppt;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdTacao;
	private Long revisao;
	private String dsTacao;
	private Date dtRevisao;
	private Byte stAtivo;
	private Date dtStativo;
	private Set<DwConsolpalog> dwConsolpalogs = new HashSet<DwConsolpalog>(0);
	private Set<DwExpcvs> dwExpcvses = new HashSet<DwExpcvs>(0);
	private Set<DwPasscau> dwPasscaus = new HashSet<DwPasscau>(0);
	private Set<DwConsolrelog> dwConsolrelogs = new HashSet<DwConsolrelog>(0);
	private Set<DwConsolpaoco> dwConsolpaocos = new HashSet<DwConsolpaoco>(0);

	public DwTAcao() {
	}

	public DwTAcao(long idTacao, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idTacao = idTacao;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public DwTAcao(long idTacao, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdTacao, Long revisao,
			String dsTdefeito, Date dtRevisao, Byte stAtivo, Date dtStativo,
			Set<DwConsolpalog> dwConsolpalogs,
			Set<DwExpcvs> dwExpcvses,
			Set<DwPasscau> dwPasscaus,
			Set<DwConsolrelog> dwConsolrelogs) {
		this.idTacao = idTacao;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdTacao = cdTacao;
		this.revisao = revisao;
		this.dsTacao = dsTdefeito;
		this.dtRevisao = dtRevisao;
		this.stAtivo = stAtivo;
		this.dtStativo = dtStativo;
		this.dwConsolpalogs = dwConsolpalogs;
		this.dwExpcvses = dwExpcvses;
		this.dwPasscaus = dwPasscaus;
		this.dwConsolrelogs = dwConsolrelogs;
	}

	@Id	
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_T_ACAO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_T_ACAO_SEQ", sequenceName = "DW_T_ACAO_SEQ")
	@Column(name = "id_tacao", nullable = false)
	public long getIdTacao() {
		return this.idTacao;
	}

	public void setIdTacao(long idTacao) {
		this.idTacao = idTacao;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tppt", nullable = false)
	public OmTppt getOmTppt() {
		return this.omTppt;
	}

	@Override
	public void setOmTppt(OmTppt omTppt) {
		this.omTppt = omTppt;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "cd_tacao", length = 30)
	public String getCdTacao() {
		return this.cdTacao;
	}

	public void setCdTacao(String cdTacao) {
		this.cdTacao = cdTacao;
	}

	@Override
	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_tacao", length = 40)
	public String getDsTacao() {
		return this.dsTacao;
	}

	public void setDsTacao(String dsTacao) {
		this.dsTacao = dsTacao;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTAcao")
	public Set<DwConsolpalog> getDwConsolpalogs() {
		return this.dwConsolpalogs;
	}

	public void setDwConsolpalogs(Set<DwConsolpalog> dwConsolpalogs) {
		this.dwConsolpalogs = dwConsolpalogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTAcao")
	public Set<DwExpcvs> getDwExpcvses() {
		return this.dwExpcvses;
	}

	public void setDwExpcvses(Set<DwExpcvs> dwExpcvses) {
		this.dwExpcvses = dwExpcvses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTAcao")
	public Set<DwPasscau> getDwPasscaus() {
		return this.dwPasscaus;
	}

	public void setDwPasscaus(Set<DwPasscau> dwPasscaus) {
		this.dwPasscaus = dwPasscaus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTAcao")
	public Set<DwConsolrelog> getDwConsolrelogs() {
		return this.dwConsolrelogs;
	}

	public void setDwConsolrelogs(Set<DwConsolrelog> dwConsolrelogs) {
		this.dwConsolrelogs = dwConsolrelogs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTAcao")
	public Set<DwConsolpaoco> getDwConsolpaocos() {
		return this.dwConsolpaocos;
	}

	public void setDwConsolpaocos(Set<DwConsolpaoco> dwConsolpaocos) {
		this.dwConsolpaocos = dwConsolpaocos;
	}
	
}
