package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwTJustTemplate;


/**
 * DwTJust generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_t_just", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_tppt", "cd_tjust", "revisao" }))
public class DwTJust extends DwTJustTemplate implements java.io.Serializable {

	private Long idTjust;
	private OmTppt omTppt;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdTjust;
	private Long revisao;
	private String dsTjust;
	private Date dtRevisao;
	private Byte stAtivo;
	private Date dtStativo;
	private Set<DwConsolpalog> dwConsolpalogs = new HashSet<DwConsolpalog>(0);
	private Set<DwConsolpaoco> dwConsolpaocos = new HashSet<DwConsolpaoco>(0);

	public DwTJust() {
	}

	public DwTJust(Long idTjust, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idTjust = idTjust;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public DwTJust(Long idTjust, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdTjust, Long revisao,
			String dsTjust, Date dtRevisao, Byte stAtivo, Date dtStativo,
			Set<DwConsolpalog> dwConsolpalogs, Set<DwConsolpaoco> dwConsolpaocos) {
		this.idTjust = idTjust;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdTjust = cdTjust;
		this.revisao = revisao;
		this.dsTjust = dsTjust;
		this.dtRevisao = dtRevisao;
		this.stAtivo = stAtivo;
		this.dtStativo = dtStativo;
		this.dwConsolpalogs = dwConsolpalogs;
		this.dwConsolpaocos = dwConsolpaocos;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_T_JUST_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_T_JUST_SEQ", sequenceName = "DW_T_JUST_SEQ")
	@Column(name = "id_tjust", nullable = false)
	public Long getIdTjust() {
		return this.idTjust;
	}

	public void setIdTjust(Long idTjust) {
		this.idTjust = idTjust;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tppt", nullable = false)
	public OmTppt getOmTppt() {
		return this.omTppt;
	}

	@Override
	public void setOmTppt(OmTppt omTppt) {
		this.omTppt = omTppt;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "cd_tjust", length = 30)
	public String getCdTjust() {
		return this.cdTjust;
	}

	public void setCdTjust(String cdTjust) {
		this.cdTjust = cdTjust;
	}

	@Override
	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_tjust", length = 40)
	public String getDsTjust() {
		return this.dsTjust;
	}

	public void setDsTjust(String dsTjust) {
		this.dsTjust = dsTjust;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTJust")
	public Set<DwConsolpalog> getDwConsolpalogs() {
		return this.dwConsolpalogs;
	}

	public void setDwConsolpalogs(Set<DwConsolpalog> dwConsolpalogs) {
		this.dwConsolpalogs = dwConsolpalogs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTJust")
	public Set<DwConsolpaoco> getDwConsolpaocos() {
		return this.dwConsolpaocos;
	}

	public void setDwConsolpaocos(Set<DwConsolpaoco> dwConsolpaocos) {
		this.dwConsolpaocos = dwConsolpaocos;
	}
	
}
