package idw.model.pojos;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// Generated 19/02/2016 13:57:41 by Hibernate Tools 4.0.0

import idw.model.pojos.template.DwTOperacaoTemplate;

/**
 * DwTOperacao generated by hbm2java
 */
@Entity
@Table(name = "dw_t_operacao")
public class DwTOperacao extends DwTOperacaoTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idToperacao;
	private String dsToperacao;
	private Set<DwOperacao> dwOperacaos = new HashSet<DwOperacao>(0);

	public DwTOperacao() {
	}

	public DwTOperacao(Long idToperacao) {
		this.idToperacao = idToperacao;
	}

	public DwTOperacao(Long idToperacao, String dsToperacao, Set<DwOperacao> dwOperacaos) {
		this.idToperacao = idToperacao;
		this.dsToperacao = dsToperacao;
		this.dwOperacaos = dwOperacaos;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_T_OPERACAO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_T_OPERACAO_SEQ", sequenceName = "DW_T_OPERACAO_SEQ")
	@Column(name = "id_toperacao", unique = true, nullable = false)
	public Long getIdToperacao() {
		return this.idToperacao;
	}

	public void setIdToperacao(Long idToperacao) {
		this.idToperacao = idToperacao;
	}

	@Column(name = "ds_toperacao", length = 256)
	public String getDsToperacao() {
		return this.dsToperacao;
	}

	public void setDsToperacao(String dsToperacao) {
		this.dsToperacao = dsToperacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTOperacao")
	public Set<DwOperacao> getDwOperacaos() {
		return this.dwOperacaos;
	}

	public void setDwOperacaos(Set<DwOperacao> dwOperacaos) {
		this.dwOperacaos = dwOperacaos;
	}

	@Override
	public String toString() {
		return getDsToperacao();
	}
}
