package idw.model.pojos;

// default package
// Generated 30/04/2013 11:32:48 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.DwTPerdampTemplate;
/**
 * DwTPerdamp generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="dw_t_perdamp")
public class DwTPerdamp extends DwTPerdampTemplate  implements java.io.Serializable {


     private long idTperdamp;
     private String dsPerdamp;
     private Set<DwConsolperdamplog> dwConsolperdamplogs = new HashSet<DwConsolperdamplog>(0);
     private Set<DwConsolpemp> dwConsolpemps = new HashSet<DwConsolpemp>(0);

    public DwTPerdamp() {
    }

	
    public DwTPerdamp(long idTperdamp, String dsPerdamp) {
        this.idTperdamp = idTperdamp;
        this.dsPerdamp = dsPerdamp;
    }
    public DwTPerdamp(long idTperdamp, String dsPerdamp, Set<DwConsolperdamplog> dwConsolperdamplogs, Set<DwConsolpemp> dwConsolpemps) {
       this.idTperdamp = idTperdamp;
       this.dsPerdamp = dsPerdamp;
       this.dwConsolperdamplogs = dwConsolperdamplogs;
       this.dwConsolpemps = dwConsolpemps;
    }
   
    @Id 
    @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_T_PERDAMP_SEQ")
    @javax.persistence.SequenceGenerator(name = "DW_T_PERDAMP_SEQ", sequenceName = "DW_T_PERDAMP_SEQ")
    @Column(name="id_tperdamp", unique=true, nullable=false)
    public long getIdTperdamp() {
        return this.idTperdamp;
    }
    
    public void setIdTperdamp(long idTperdamp) {
        this.idTperdamp = idTperdamp;
    }

    
    @Column(name="ds_perdamp", nullable=false, length=40)
    public String getDsPerdamp() {
        return this.dsPerdamp;
    }
    
    public void setDsPerdamp(String dsPerdamp) {
        this.dsPerdamp = dsPerdamp;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="dwTPerdamp")
    public Set<DwConsolperdamplog> getDwConsolperdamplogs() {
        return this.dwConsolperdamplogs;
    }
    
    public void setDwConsolperdamplogs(Set<DwConsolperdamplog> dwConsolperdamplogs) {
        this.dwConsolperdamplogs = dwConsolperdamplogs;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="dwTPerdamp")
    public Set<DwConsolpemp> getDwConsolpemps() {
        return this.dwConsolpemps;
    }
    
    public void setDwConsolpemps(Set<DwConsolpemp> dwConsolpemps) {
        this.dwConsolpemps = dwConsolpemps;
    }




}


