package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 20/01/2010 15:07:16 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwTParadaTemplate;

/**
 * DwTParada generated by hbm2java
 */

@SuppressWarnings("serial")
@Entity
@Table(name = "dw_t_parada")
public class DwTParada extends DwTParadaTemplate implements java.io.Serializable {

	private Long idTparada;
	private OmTppt omTppt;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdTparada;
	private Long revisao;
	private String dsTparada;
	private Date dtRevisao;
	private Byte stAtivo;
	private Date dtStativo;
	private Boolean isRequerCausa;
	private Boolean isRequerAcao;
	private Boolean isRequerJust;
	private Boolean isPesa;
	private Boolean isRegulagem;
	private Boolean isPermitecorrecao;
	private Boolean isFds;
	private Boolean isMdo;
	private Boolean isMtbf;
	private Boolean isPa;
	private Boolean isPao;
	private Boolean isPrev;
	private Boolean isPp;
	private Boolean isPtp;
	private Boolean isScp;
	private Integer qtTec;
	private Boolean isDefault;
	private Boolean isSemOp;
	private Boolean isSemConexao;
	private Boolean isSemEvento;
	private Boolean isEntradarap;
	private Boolean isSaidarap;
	private Boolean isSolicitarOS;
	private DwTArea dwTArea;
	private Set<OmCfg> omCfgs = new HashSet<OmCfg>(0);
	private Set<DwConsolpalog> dwConsolpalogs = new HashSet<DwConsolpalog>(0);
	private Set<DwConsolpa> dwConsolpas = new HashSet<DwConsolpa>(0);

	private BigDecimal segExtrapolacao;
	private BigDecimal segTimeoutalerta;
	
	private DwTAlerta dwTAlerta;
	private DwTParada dwTParadaextra;
	
	public DwTParada() {
	}

	public DwTParada(Long idTparada, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idTparada = idTparada;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}


	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_T_PARADA_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_T_PARADA_SEQ", sequenceName = "DW_T_PARADA_SEQ")
	@Column(name = "id_tparada", unique = true, nullable = false)
	public Long getIdTparada() {
		return this.idTparada;
	}

	public void setIdTparada(Long idTparada) {
		this.idTparada = idTparada;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tppt", nullable = false)
	public OmTppt getOmTppt() {
		return this.omTppt;
	}

	@Override
	public void setOmTppt(OmTppt omTppt) {
		this.omTppt = omTppt;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "cd_tparada", length = 30)
	public String getCdTparada() {
		return this.cdTparada;
	}

	public void setCdTparada(String cdTparada) {
		this.cdTparada = cdTparada;
	}

	@Override
	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_tparada")
	public String getDsTparada() {
		return this.dsTparada;
	}

	public void setDsTparada(String dsTparada) {
		this.dsTparada = dsTparada;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "IS_REQUER_CAUSA")
	public Boolean getIsRequerCausa() {
		return this.isRequerCausa;
	}

	public void setIsRequerCausa(Boolean isRequerCausa) {
		this.isRequerCausa = isRequerCausa;
	}

	@Column(name = "IS_REQUER_ACAO")
	public Boolean getIsRequerAcao() {
		return this.isRequerAcao;
	}

	public void setIsRequerAcao(Boolean isRequerAcao) {
		this.isRequerAcao = isRequerAcao;
	}

	@Column(name = "IS_REQUER_JUST")
	public Boolean getIsRequerJust() {
		return this.isRequerJust;
	}

	public void setIsRequerJust(Boolean isRequerJust) {
		this.isRequerJust = isRequerJust;
	}

	@Column(name = "IS_PESA")
	public Boolean getIsPesa() {
		return this.isPesa;
	}

	public void setIsPesa(Boolean isPesa) {
		this.isPesa = isPesa;
	}

	@Column(name = "IS_REGULAGEM")
	public Boolean getIsRegulagem() {
		return this.isRegulagem;
	}

	public void setIsRegulagem(Boolean isRegulagem) {
		this.isRegulagem = isRegulagem;
	}
	@Column(name = "IS_PERMITECORRECAO")
	public Boolean getIsPermitecorrecao() {
		return this.isPermitecorrecao;
	}

	public void setIsPermitecorrecao(Boolean isvalor) {
		this.isPermitecorrecao = isvalor;
	}

	@Column(name = "IS_FDS")
	public Boolean getIsFds() {
		return this.isFds;
	}

	public void setIsFds(Boolean isFds) {
		this.isFds = isFds;
	}

	@Column(name = "IS_MDO")
	public Boolean getIsMdo() {
		return this.isMdo;
	}

	public void setIsMdo(Boolean isMdo) {
		this.isMdo = isMdo;
	}

	@Column(name = "IS_MTBF")
	public Boolean getIsMtbf() {
		return this.isMtbf;
	}

	public void setIsMtbf(Boolean isMtbf) {
		this.isMtbf = isMtbf;
	}


	@Column(name = "IS_PA")
	public Boolean getIsPa() {
		return this.isPa;
	}

	public void setIsPa(Boolean isPa) {
		this.isPa = isPa;
	}

	@Column(name = "IS_PAO")
	public Boolean getIsPao() {
		return this.isPao;
	}

	public void setIsPao(Boolean isPao) {
		this.isPao = isPao;
	}

	@Column(name = "IS_PREV")
	public Boolean getIsPrev() {
		return this.isPrev;
	}

	public void setIsPrev(Boolean isPrev) {
		this.isPrev = isPrev;
	}

	@Column(name = "IS_PP")
	public Boolean getIsPp() {
		return this.isPp;
	}

	public void setIsPp(Boolean isPp) {
		this.isPp = isPp;
	}

	@Column(name = "IS_PTP")
	public Boolean getIsPtp() {
		return this.isPtp;
	}

	public void setIsPtp(Boolean isPtp) {
		this.isPtp = isPtp;
	}

	@Column(name = "IS_SCP")
	public Boolean getIsScp() {
		return this.isScp;
	}

	public void setIsScp(Boolean isScp) {
		this.isScp = isScp;
	}

	@Column(name = "QT_TEC")
	public Integer getQtTec() {
		return this.qtTec;
	}

	public void setQtTec(Integer qtTec) {
		this.qtTec = qtTec;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTParada")
	public Set<OmCfg> getOmCfgs() {
		return this.omCfgs;
	}

	public void setOmCfgs(Set<OmCfg> omCfgs) {
		this.omCfgs = omCfgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTParada")
	public Set<DwConsolpa> getDwConsolpas() {
		return this.dwConsolpas;
	}

	public void setDwConsolpas(Set<DwConsolpa> dwConsolpas) {
		this.dwConsolpas = dwConsolpas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTParada")
	public Set<DwConsolpalog> getDwConsolpalogs() {
		return this.dwConsolpalogs;
	}

	public void setDwConsolpalogs(Set<DwConsolpalog> dwConsolpalogs) {
		this.dwConsolpalogs = dwConsolpalogs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AREA")
	public DwTArea getDwTArea() {
		return this.dwTArea;
	}

	public void setDwTArea(DwTArea dwTArea) {
		this.dwTArea = dwTArea;
	}
	
	@Column(name = "is_default")
	public Boolean getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}
	
	@Column(name = "is_sem_op")
	public Boolean getIsSemOp() {
		return this.isSemOp;
	}

	public void setIsSemOp(Boolean isSemOp) {
		this.isSemOp = isSemOp;
	}
	
	@Column(name = "is_sem_conexao")
	public Boolean getIsSemConexao() {
		return this.isSemConexao;
	}

	public void setIsSemConexao(Boolean isSemConexao) {
		this.isSemConexao = isSemConexao;
	}
	
	@Column(name = "is_sem_evento")
	public Boolean getIsSemEvento() {
		return this.isSemEvento;
	}

	public void setIsSemEvento(Boolean isSemEvento) {
		this.isSemEvento = isSemEvento;
	}
	
	@Column(name = "is_entradarap")
	public Boolean getIsEntradarap() {
		return this.isEntradarap;
	}

	public void setIsEntradarap(Boolean isEntradarap) {
		this.isEntradarap = isEntradarap;
	}

	@Column(name = "is_saidarap")
	public Boolean getIsSaidarap() {
		return this.isSaidarap;
	}

	public void setIsSaidarap(Boolean isSaidarap) {
		this.isSaidarap = isSaidarap;
	}
	@Column(name = "seg_extrapolacao", precision = 20, scale = 10)
	public BigDecimal getSegExtrapolacao() {
		return this.segExtrapolacao;
	}

	public void setSegExtrapolacao(BigDecimal segExtrapolacao) {
		this.segExtrapolacao = segExtrapolacao;
	}

	@Column(name = "seg_timeoutalerta", precision = 20, scale = 10)
	public BigDecimal getSegTimeoutalerta() {
		return this.segTimeoutalerta;
	}

	public void setSegTimeoutalerta(BigDecimal segTimeoutalerta) {
		this.segTimeoutalerta = segTimeoutalerta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_talerta")
	public DwTAlerta getDwTAlerta() {
		return this.dwTAlerta;
	}

	public void setDwTAlerta(DwTAlerta dwTAlerta) {
		this.dwTAlerta = dwTAlerta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tparadaextra")
	public DwTParada getDwTParadaextra() {
		return this.dwTParadaextra;
	}

	public void setDwTParadaextra(DwTParada dwTParada) {
		this.dwTParadaextra = dwTParada;
	}

	@Column(name = "is_solicitaros")
	public Boolean getIsSolicitarOS() {
		return isSolicitarOS;
	}

	public void setIsSolicitarOS(Boolean isSolicitarOS) {
		this.isSolicitarOS = isSolicitarOS;
	}


}
