package idw.model.pojos;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.DwTRitmoTemplate;

/**
 * DwTRitmo generated by hbm2java
 */
@Entity
@Table(name = "dw_t_ritmo")
public class DwTRitmo extends DwTRitmoTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idTritmo;
	private OmTppt omTppt;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdTritmo;
	private Long revisao;
	private String dsTritmo;
	private Byte stAtivo;
	private Date dtStativo;
	private Date dtRevisao;
	private Set<OmCfg> omCfgs = new HashSet<OmCfg>(0);

	public DwTRitmo() {
	}

	public DwTRitmo(Long idTritmo, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idTritmo = idTritmo;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public DwTRitmo(Long idTritmo, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdTritmo, Long revisao,
			String dsTritmo, Date dtRevisao, Byte stAtivo, Date dtStativo,
			Set<OmCfg> omCfgs) {
		this.idTritmo = idTritmo;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdTritmo = cdTritmo;
		this.revisao = revisao;
		this.dsTritmo = dsTritmo;
		this.dtRevisao = dtRevisao;
		this.stAtivo = stAtivo;
		this.dtStativo = dtStativo;
		this.omCfgs = omCfgs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_T_RITMO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_T_RITMO_SEQ", sequenceName = "DW_T_RITMO_SEQ")
	@Column(name = "id_tritmo", unique = true, nullable = false)
	public Long getIdTritmo() {
		return this.idTritmo;
	}

	public void setIdTritmo(Long idTritmo) {
		this.idTritmo = idTritmo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tppt", nullable = false)
	public OmTppt getOmTppt() {
		return this.omTppt;
	}

	public void setOmTppt(OmTppt omTppt) {
		this.omTppt = omTppt;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "cd_tritmo", length = 60)
	public String getCdTritmo() {
		return this.cdTritmo;
	}

	public void setCdTritmo(String cdTritmo) {
		this.cdTritmo = cdTritmo;
	}

	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_tritmo", length = 100)
	public String getDsTritmo() {
		return this.dsTritmo;
	}

	public void setDsTritmo(String dsTritmo) {
		this.dsTritmo = dsTritmo;
	}

	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTRitmo")
	public Set<OmCfg> getOmCfgs() {
		return this.omCfgs;
	}

	public void setOmCfgs(Set<OmCfg> omCfgs) {
		this.omCfgs = omCfgs;
	}

}
