package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.DwTRefugoTemplate;

/**
 * DwTRefugo generated by hbm2javaid
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "dw_t_refugo", uniqueConstraints = @UniqueConstraint(columnNames = { "id_tppt", "cd_trefugo", "revisao" }))
public class DwTRefugo extends DwTRefugoTemplate implements java.io.Serializable {

	private Long idTrefugo;
	private OmTppt omTppt;
	private DwTArea dwTArea;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdTrefugo;
	private Long revisao;
	private String dsTrefugo;
	private Date dtRevisao;
	private Byte stAtivo;
	private Date dtStativo;
	private Set<DwConsolre> dwConsolres = new HashSet<DwConsolre>(0);
	private Set<DwConsolrelog> dwConsolrelogs = new HashSet<DwConsolrelog>(0);
	private Boolean isRequerCausa;
	private Boolean isRequerAcao;
	private Boolean isAutomatico;

	public DwTRefugo() {
	}

	public DwTRefugo(Long idTrefugo, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idTrefugo = idTrefugo;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public DwTRefugo(Long idTrefugo, OmTppt omTppt, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdTrefugo, Long revisao,
			String dsTrefugo, Date dtRevisao, Byte stAtivo, Date dtStativo,
			Boolean isRequerCausa, Boolean isRequerAcao,
			Set<DwConsolre> dwConsolres, Set<DwConsolrelog> dwConsolrelogs) {
		this.idTrefugo = idTrefugo;
		this.omTppt = omTppt;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdTrefugo = cdTrefugo;
		this.revisao = revisao;
		this.dsTrefugo = dsTrefugo;
		this.dtRevisao = dtRevisao;
		this.stAtivo = stAtivo;
		this.dtStativo = dtStativo;
		this.isRequerCausa = isRequerCausa;
		this.isRequerAcao = isRequerAcao;
		this.dwConsolres = dwConsolres;
		this.dwConsolrelogs = dwConsolrelogs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "DW_T_REFUGO_SEQ")
	@javax.persistence.SequenceGenerator(name = "DW_T_REFUGO_SEQ", sequenceName = "DW_T_REFUGO_SEQ")
	@Column(name = "id_trefugo", unique = true, nullable = false)
	public Long getIdTrefugo() {
		return this.idTrefugo;
	}

	public void setIdTrefugo(Long idTrefugo) {
		this.idTrefugo = idTrefugo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tppt", nullable = false)
	public OmTppt getOmTppt() {
		return this.omTppt;
	}

	@Override
	public void setOmTppt(OmTppt omTppt) {
		this.omTppt = omTppt;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "cd_trefugo", length = 30)
	public String getCdTrefugo() {
		return this.cdTrefugo;
	}

	public void setCdTrefugo(String cdTrefugo) {
		this.cdTrefugo = cdTrefugo;
	}

	@Override
	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_trefugo", length = 40)
	public String getDsTrefugo() {
		return this.dsTrefugo;
	}

	public void setDsTrefugo(String dsTrefugo) {
		this.dsTrefugo = dsTrefugo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "IS_REQUER_CAUSA")
	public Boolean getIsRequerCausa() {
		return this.isRequerCausa;
	}

	public void setIsRequerCausa(Boolean isRequerCausa) {
		this.isRequerCausa = isRequerCausa;
	}

	@Column(name = "IS_REQUER_ACAO")
	public Boolean getIsRequerAcao() {
		return this.isRequerAcao;
	}

	public void setIsRequerAcao(Boolean isRequerAcao) {
		this.isRequerAcao = isRequerAcao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTRefugo")
	public Set<DwConsolre> getDwConsolres() {
		return this.dwConsolres;
	}

	public void setDwConsolres(Set<DwConsolre> dwConsolres) {
		this.dwConsolres = dwConsolres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dwTRefugo")
	public Set<DwConsolrelog> getDwConsolrelogs() {
		return this.dwConsolrelogs;
	}

	public void setDwConsolrelogs(Set<DwConsolrelog> dwConsolrelogs) {
		this.dwConsolrelogs = dwConsolrelogs;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AREA")
	public DwTArea getDwTArea() {
		return this.dwTArea;
	}

	public void setDwTArea(DwTArea dwTArea) {
		this.dwTArea = dwTArea;
	}

	@Column(name = "IS_AUTOMATICO")
	public Boolean getIsAutomatico() {
		return this.isAutomatico;
	}

	public void setIsAutomatico(Boolean valor) {
		this.isAutomatico = valor;
	}
	
	
}
