package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 19/02/2016 13:57:41 by Hibernate Tools 4.0.0

import idw.model.pojos.template.IpBalanceamentoTemplate;

/**
 * IpBalanceamento generated by hbm2java
 */
@Entity
@Table(name = "ip_balanceamento")
public class IpBalanceamento extends IpBalanceamentoTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idBalanceamento;
	private OmProduto omProdutoByIdProdutosemiacabado;
	private OmProduto omProdutoByIdProdutoacabado;
	private OmGt omGt;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdBalanceamento;
	private Long revisao;
	private Date dtRevisao;
	private Byte stAtivo;
	private Date dtStativo;
	private String dsBalanceamento;
	private Byte stBalanceamento;
	private BigDecimal pcsProducaoplanejadadiaria;
	private BigDecimal segTempodisponiveldiario;
	private BigDecimal segTakttime;
	private BigDecimal indFadiga;
	private Byte tpAlgoritmo;

	private Set<DwFolhaoperacao> dwFolhaoperacoes = new HashSet<DwFolhaoperacao>(0);

	public IpBalanceamento() {
	}

	public IpBalanceamento(Long idBalanceamento) {
		this.idBalanceamento = idBalanceamento;
	}
	
	


	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "IP_BALANCEAMENTO_SEQ")
	@javax.persistence.SequenceGenerator(name = "IP_BALANCEAMENTO_SEQ", sequenceName = "IP_BALANCEAMENTO_SEQ")
	@Column(name = "id_balanceamento", unique = true, nullable = false)
	public Long getIdBalanceamento() {
		return this.idBalanceamento;
	}

	public void setIdBalanceamento(Long idBalanceamento) {
		this.idBalanceamento = idBalanceamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produtosemiacabado")
	public OmProduto getOmProdutoByIdProdutosemiacabado() {
		return this.omProdutoByIdProdutosemiacabado;
	}

	public void setOmProdutoByIdProdutosemiacabado(OmProduto omProdutoByIdProdutosemiacabado) {
		this.omProdutoByIdProdutosemiacabado = omProdutoByIdProdutosemiacabado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produtoacabado")
	public OmProduto getOmProdutoByIdProdutoacabado() {
		return this.omProdutoByIdProdutoacabado;
	}

	public void setOmProdutoByIdProdutoacabado(OmProduto omProdutoByIdProdutoacabado) {
		this.omProdutoByIdProdutoacabado = omProdutoByIdProdutoacabado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gt")
	public OmGt getOmGt() {
		return this.omGt;
	}

	public void setOmGt(OmGt omGt) {
		this.omGt = omGt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo")
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao")
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "cd_balanceamento", length = 60)
	public String getCdBalanceamento() {
		return this.cdBalanceamento;
	}

	public void setCdBalanceamento(String cdBalanceamento) {
		this.cdBalanceamento = cdBalanceamento;
	}

	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 29)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 29)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "st_balanceamento")
	public Byte getStBalanceamento() {
		return this.stBalanceamento;
	}

	public void setStBalanceamento(Byte stBalanceamento) {
		this.stBalanceamento = stBalanceamento;
	}

	@Column(name = "pcs_producaoplanejadadiaria", precision = 14, scale = 4)
	public BigDecimal getPcsProducaoplanejadadiaria() {
		return this.pcsProducaoplanejadadiaria;
	}

	public void setPcsProducaoplanejadadiaria(BigDecimal pcsProducaoplanejadadiaria) {
		this.pcsProducaoplanejadadiaria = pcsProducaoplanejadadiaria;
	}

	@Column(name = "seg_tempodisponiveldiario", precision = 20, scale = 10)
	public BigDecimal getSegTempodisponiveldiario() {
		return this.segTempodisponiveldiario;
	}

	public void setSegTempodisponiveldiario(BigDecimal segTempodisponiveldiario) {
		this.segTempodisponiveldiario = segTempodisponiveldiario;
	}

	@Column(name = "seg_takttime", precision = 20, scale = 10)
	public BigDecimal getSegTakttime() {
		return this.segTakttime;
	}

	public void setSegTakttime(BigDecimal segTakttime) {
		this.segTakttime = segTakttime;
	}

	@Column(name = "ind_fadiga", precision = 6, scale = 3)
	public BigDecimal getIndFadiga() {
		return this.indFadiga;
	}

	public void setIndFadiga(BigDecimal indFadiga) {
		this.indFadiga = indFadiga;
	}

	@Column(name = "tp_algoritmo")
	public Byte getTpAlgoritmo() {
		return this.tpAlgoritmo;
	}

	public void setTpAlgoritmo(Byte tpAlgoritmo) {
		this.tpAlgoritmo = tpAlgoritmo;
	}

	@Column(name = "ds_balanceamento", length = 256)
	public String getDsBalanceamento() {
		return dsBalanceamento;
	}

	public void setDsBalanceamento(String dsBalanceamento) {
		this.dsBalanceamento = dsBalanceamento;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ipBalanceamento")
	public Set<DwFolhaoperacao> getDwFolhaoperacoes() {
		return this.dwFolhaoperacoes;
	}

	public void setDwFolhaoperacoes(Set<DwFolhaoperacao> dwFolhaoperacao) {
		this.dwFolhaoperacoes = dwFolhaoperacao;
	}
}
