package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.MsDetectorTemplate;

/**
 * MsDetector generated by hbm2java
 */
@Entity
@Table(name = "MS_DETECTOR")
public class MsDetector extends MsDetectorTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1167835220414166288L;
	private Long idDetector;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsrgrp omUsrgrp;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdDetector;
	private BigDecimal revisao;
	private String dsDetector;
	private BigDecimal stAtivo;
	private Date dthrRevisao;
	private Date dthrStativo;
	private Boolean isEmail;
	private Boolean isSms;
	private Set<MsDetectorusr> msDetectorusrs = new HashSet<MsDetectorusr>(0);
	private Set<MsTrigger> msTriggers = new HashSet<MsTrigger>(0);

	public MsDetector() {
	}

	public MsDetector(Long idDetector, OmUsrgrp omUsrgrp,
			OmUsr omUsrByIdUsrrevisao) {
		this.idDetector = idDetector;
		this.omUsrgrp = omUsrgrp;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public MsDetector(Long idDetector, OmUsr omUsrByIdUsrstativo,
			OmUsrgrp omUsrgrp, OmUsr omUsrByIdUsrrevisao, String cdDetector,
			BigDecimal revisao, String dsDetector, BigDecimal stAtivo,
			Date dthrRevisao, Date dthrStativo, Boolean isEmail,
			Boolean isSms, Set<MsDetectorusr> msDetectorusrs,
			Set<MsTrigger> msTriggers) {
		this.idDetector = idDetector;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrgrp = omUsrgrp;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdDetector = cdDetector;
		this.revisao = revisao;
		this.dsDetector = dsDetector;
		this.stAtivo = stAtivo;
		this.dthrRevisao = dthrRevisao;
		this.dthrStativo = dthrStativo;
		this.isEmail = isEmail;
		this.isSms = isSms;
		this.msDetectorusrs = msDetectorusrs;
		this.msTriggers = msTriggers;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "MS_DETECTOR_SEQ")
	@javax.persistence.SequenceGenerator(name = "MS_DETECTOR_SEQ", sequenceName = "MS_DETECTOR_SEQ")
	@Column(name = "ID_DETECTOR", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdDetector() {
		return this.idDetector;
	}

	public void setIdDetector(Long idDetector) {
		this.idDetector = idDetector;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRSTATIVO")
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRGRP", nullable = false)
	public OmUsrgrp getOmUsrgrp() {
		return this.omUsrgrp;
	}

	public void setOmUsrgrp(OmUsrgrp omUsrgrp) {
		this.omUsrgrp = omUsrgrp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRREVISAO", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "CD_DETECTOR", length = 60)
	public String getCdDetector() {
		return this.cdDetector;
	}

	public void setCdDetector(String cdDetector) {
		this.cdDetector = cdDetector;
	}

	@Column(name = "REVISAO", precision = 22, scale = 0)
	public BigDecimal getRevisao() {
		return this.revisao;
	}

	public void setRevisao(BigDecimal revisao) {
		this.revisao = revisao;
	}

	@Column(name = "DS_DETECTOR", length = 100)
	public String getDsDetector() {
		return this.dsDetector;
	}

	public void setDsDetector(String dsDetector) {
		this.dsDetector = dsDetector;
	}

	@Column(name = "ST_ATIVO", precision = 22, scale = 0)
	public BigDecimal getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(BigDecimal stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHR_REVISAO", length = 7)
	public Date getDthrRevisao() {
		return this.dthrRevisao;
	}

	public void setDthrRevisao(Date dthrRevisao) {
		this.dthrRevisao = dthrRevisao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHR_STATIVO", length = 7)
	public Date getDthrStativo() {
		return this.dthrStativo;
	}

	public void setDthrStativo(Date dthrStativo) {
		this.dthrStativo = dthrStativo;
	}

	@Column(name = "IS_EMAIL")
	public Boolean getIsEmail() {
		return this.isEmail;
	}

	public void setIsEmail(Boolean isEmail) {
		this.isEmail = isEmail;
	}

	@Column(name = "IS_SMS", precision = 22, scale = 0)
	public Boolean getIsSms() {
		return this.isSms;
	}

	public void setIsSms(Boolean isSms) {
		this.isSms = isSms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msDetector")
	public Set<MsDetectorusr> getMsDetectorusrs() {
		return this.msDetectorusrs;
	}

	public void setMsDetectorusrs(Set<MsDetectorusr> msDetectorusrs) {
		this.msDetectorusrs = msDetectorusrs;
	}

	@OneToMany(cascade = CascadeType.ALL,  fetch = FetchType.LAZY, mappedBy = "msDetector")
	public Set<MsTrigger> getMsTriggers() {
		return this.msTriggers;
	}

	public void setMsTriggers(Set<MsTrigger> msTriggers) {
		this.msTriggers = msTriggers;
	}

}
