package idw.model.pojos;
// Generated 01/06/2011 17:13:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.MsEvtTemplate;

/**
 * MsEvt generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MS_EVT")
public class MsEvt extends MsEvtTemplate implements java.io.Serializable {

	private Long idEvt;
	private MsTpevt msTpevt;
	private MsMsicup msMsicup;
	private MsEvt msEvt;
	private DwPepro dwPepro;

	private String cdUp;

	
	private MsUpihm msUpihm;
	private Date dthrEvento;
	private BigDecimal stEvt;
	private Date dthrEventoanterior;
	private Date dthrCadastrobanco;
	private Date dthrCadastroserver;
	private Date dthrProcessaserver;
	private Date dthrIprocessaserver;
	private Long miliDuracaoevento;
	private Date dthrEnvioprcoletoreventos;
	private BigDecimal idPrcoletoreventos;
	private String depara;
	
	private Set<MsMonitor> msMonitors = new HashSet<MsMonitor>(0);
	private Set<MsEvt> msEvts = new HashSet<MsEvt>(0);
	private Set<MsUp> msUpsForIdEvtinicioparada = new HashSet<MsUp>(0);
	private Set<MsUp> msUpsForIdEvtiniciociclo = new HashSet<MsUp>(0);
	private Set<MsEvtcep> msEvtceps = new HashSet<MsEvtcep>(0);
	private Set<MsEvtmontagem> msEvtmontagems = new HashSet<MsEvtmontagem>(0);
	private Set<MsEvtdefeito> msEvtdefeitos = new HashSet<MsEvtdefeito>(0);

	private String login;
	private BigDecimal qtdeCiclos;
	private BigDecimal qtde;
	private BigDecimal segCiclopadrao;
	
	private BigDecimal producaoliquida;
	private BigDecimal producaorefugada;
	
	private String cdParada;
	private String cdDefeito;
	private String cdRefugo;
	private String cdConsulta;
	private String cdAcao;
	private String cdCausa;
	private String cdJustificativa;
	private String cdAlerta;
	private String cdArea;
	private String cdTec1;
	private String cdTec2;
	private String cdTecresp;
	private String cdProdutoredz;
	private String cdProduto;
	private String nrop;
	private String cb;
	private String cbserial;
	private String cdMolde;
	private String cdEstrutura;
	private String origem;
	private Integer sequencial;
	private String erroconsol;
	
	 private String cdComponente;
     private String cdFeeder;
     private String cdNozzle;
     private Integer tpErromontagem;
     private Integer qtErromontagem;
     
     private Boolean isRegulagem;
     private Boolean isMontagemfechadaantecipadamente;

 	private Long seqbigint;
 	
 	private String cdOrigem;

	public MsEvt() {
	}

	public MsEvt(Long idEvt, MsTpevt msTpevt) {
		this.idEvt = idEvt;
		this.msTpevt = msTpevt;
	}

	public MsEvt(Long idEvt, MsTpevt msTpevt, MsMsicup msMsicup,
			MsEvt msEvt, MsUpihm msUpihm, Date dthrIevento,
			BigDecimal stEvt, Date dthrFevento, String cdApoio1,
			String cdApoio2, String cdApoio3, Date dthrCadastrobanco,
			Date dthrCadastroserver, Long segDuracaoevento,
			Date dthrEnvioprcoletoreventos,
			BigDecimal idPrcoletoreventos, String cdComponente, 
			String cdFeeder, String cdNozzle, Integer tpErromontagem, 
			Integer qtErromontagem,
			Set<MsMonitor> msMonitors,
			Set<MsEvt> msEvts) {
		this.idEvt = idEvt;
		this.msTpevt = msTpevt;
		this.msMsicup = msMsicup;
		this.msEvt = msEvt;
		this.msUpihm = msUpihm;
		this.dthrEvento = dthrIevento;
		this.stEvt = stEvt;
		this.dthrEventoanterior = dthrFevento;
		this.dthrCadastrobanco = dthrCadastrobanco;
		this.dthrCadastroserver = dthrCadastroserver;
		this.miliDuracaoevento = segDuracaoevento;
		this.dthrEnvioprcoletoreventos = dthrEnvioprcoletoreventos;
		this.idPrcoletoreventos = idPrcoletoreventos;
		this.cdComponente = cdComponente;
		this.cdFeeder = cdFeeder;
		this.cdNozzle = cdNozzle;
		this.tpErromontagem = tpErromontagem;
		this.qtErromontagem = qtErromontagem;
		this.msMonitors = msMonitors;
		this.msEvts = msEvts;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "MS_EVT_SEQ")
	@javax.persistence.SequenceGenerator(name = "MS_EVT_SEQ", sequenceName = "MS_EVT_SEQ")
	@Column(name = "ID_EVT", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdEvt() {
		return this.idEvt;
	}

	public void setIdEvt(Long idEvt) {
		this.idEvt = idEvt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TPEVT", nullable = false)
	public MsTpevt getMsTpevt() {
		return this.msTpevt;
	}

	public void setMsTpevt(MsTpevt msTpevt) {
		this.msTpevt = msTpevt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MSICUP")
	public MsMsicup getMsMsicup() {
		return this.msMsicup;
	}

	public void setMsMsicup(MsMsicup msMsicup) {
		this.msMsicup = msMsicup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EVTINICIO")
	public MsEvt getMsEvt() {
		return this.msEvt;
	}

	public void setMsEvt(MsEvt msEvt) {
		this.msEvt = msEvt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UPIHM")
	public MsUpihm getMsUpihm() {
		return this.msUpihm;
	}

	public void setMsUpihm(MsUpihm msUpihm) {
		this.msUpihm = msUpihm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_EVENTO")
	public Date getDthrEvento() {
		return this.dthrEvento;
	}

	public void setDthrEvento(Date dthrIevento) {
		this.dthrEvento = dthrIevento;
	}

	@Column(name = "ST_EVT", precision = 22, scale = 0)
	public BigDecimal getStEvt() {
		return this.stEvt;
	}

	public void setStEvt(BigDecimal stEvt) {
		this.stEvt = stEvt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_EVENTOANTERIOR")
	public Date getDthrEventoanterior() {
		return this.dthrEventoanterior;
	}

	public void setDthrEventoanterior(Date dthrFevento) {
		this.dthrEventoanterior = dthrFevento;
	}

	@Column(name = "DTHR_CADASTROBANCO")
	public Date getDthrCadastrobanco() {
		return this.dthrCadastrobanco;
	}

	public void setDthrCadastrobanco(Date dthrCadastrobanco) {
		this.dthrCadastrobanco = dthrCadastrobanco;
	}

	@Column(name = "DTHR_CADASTROSERVER")
	public Date getDthrCadastroserver() {
		return this.dthrCadastroserver;
	}

	public void setDthrCadastroserver(Date dthrCadastroserver) {
		this.dthrCadastroserver = dthrCadastroserver;
	}

	@Column(name = "DTHR_PROCESSASERVER")
	public Date getDthrProcessaserver() {
		return this.dthrProcessaserver;
	}

	public void setDthrProcessaserver(Date dthrserver) {
		this.dthrProcessaserver = dthrserver;
	}
	@Column(name = "DTHR_IPROCESSASERVER")
	public Date getDthrIprocessaserver() {
		return this.dthrIprocessaserver;
	}

	public void setDthrIprocessaserver(Date dthrserver) {
		this.dthrIprocessaserver = dthrserver;
	}

	@Column(name = "MILI_DURACAOEVENTO")
	public Long getMiliDuracaoevento() {
		return this.miliDuracaoevento;
	}

	public void setMiliDuracaoevento(Long miliDuracaoevento) {
		this.miliDuracaoevento = miliDuracaoevento;
	}

	@Column(name = "DTHR_ENVIOPRCOLETOREVENTOS")
	public Date getDthrEnvioprcoletoreventos() {
		return this.dthrEnvioprcoletoreventos;
	}

	public void setDthrEnvioprcoletoreventos(
			Date dthrEnvioprcoletoreventos) {
		this.dthrEnvioprcoletoreventos = dthrEnvioprcoletoreventos;
	}

	@Column(name = "ID_PRCOLETOREVENTOS", precision = 22, scale = 0)
	public BigDecimal getIdPrcoletoreventos() {
		return this.idPrcoletoreventos;
	}

	public void setIdPrcoletoreventos(BigDecimal idPrcoletoreventos) {
		this.idPrcoletoreventos = idPrcoletoreventos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msEvt")
	public Set<MsMonitor> getMsMonitors() {
		return this.msMonitors;
	}

	public void setMsMonitors(Set<MsMonitor> msMonitors) {
		this.msMonitors = msMonitors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msEvt")
	public Set<MsEvt> getMsEvts() {
		return this.msEvts;
	}

	public void setMsEvts(Set<MsEvt> msEvts) {
		this.msEvts = msEvts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msEvtByIdEvtinicioparada")
	public Set<MsUp> getMsUpsForIdEvtinicioparada() {
		return this.msUpsForIdEvtinicioparada;
	}

	public void setMsUpsForIdEvtinicioparada(Set<MsUp> msUpsForIdEvtinicioparada) {
		this.msUpsForIdEvtinicioparada = msUpsForIdEvtinicioparada;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msEvtByIdEvtiniciociclo")
	public Set<MsUp> getMsUpsForIdEvtiniciociclo() {
		return this.msUpsForIdEvtiniciociclo;
	}

	public void setMsUpsForIdEvtiniciociclo(Set<MsUp> msUpsForIdEvtiniciociclo) {
		this.msUpsForIdEvtiniciociclo = msUpsForIdEvtiniciociclo;
	}
	@Column(name = "LOGIN", length = 40)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "QTDE_CICLOS", precision = 14, scale = 4)
	public BigDecimal getQtdeCiclos() {
		return this.qtdeCiclos;
	}

	public void setQtdeCiclos(BigDecimal qtdeCiclos) {
		this.qtdeCiclos = qtdeCiclos;
	}
	@Column(name = "QTDE", precision = 14, scale = 4)
	public BigDecimal getQtde() {
		return this.qtde;
	}

	public void setQtde(BigDecimal qtde) {
		this.qtde = qtde;
	}

	@Column(name = "CD_PARADA", length = 40)
	public String getCdParada() {
		return this.cdParada;
	}

	public void setCdParada(String cdParada) {
		this.cdParada = cdParada;
	}

	@Column(name = "CD_REFUGO", length = 40)
	public String getCdRefugo() {
		return this.cdRefugo;
	}

	public void setCdRefugo(String cdRefugo) {
		this.cdRefugo = cdRefugo;
	}

	@Column(name = "CD_CONSULTA", length = 40)
	public String getCdConsulta() {
		return this.cdConsulta;
	}

	public void setCdConsulta(String cdConsulta) {
		this.cdConsulta = cdConsulta;
	}

	@Column(name = "CD_ACAO", length = 40)
	public String getCdAcao() {
		return this.cdAcao;
	}

	public void setCdAcao(String cdAcao) {
		this.cdAcao = cdAcao;
	}

	@Column(name = "CD_CAUSA", length = 40)
	public String getCdCausa() {
		return this.cdCausa;
	}

	public void setCdCausa(String cdCausa) {
		this.cdCausa = cdCausa;
	}

	@Column(name = "CD_JUSTIFICATIVA", length = 40)
	public String getCdJustificativa() {
		return this.cdJustificativa;
	}

	public void setCdJustificativa(String cdJustificativa) {
		this.cdJustificativa = cdJustificativa;
	}

	@Column(name = "CD_ALERTA", length = 40)
	public String getCdAlerta() {
		return this.cdAlerta;
	}

	public void setCdAlerta(String cdAlerta) {
		this.cdAlerta = cdAlerta;
	}

	
	@Column(name = "CD_AREA", length = 60)
	public String getCdArea() {
		return this.cdArea;
	}

	public void setCdArea(String cd) {
		this.cdArea = cd;
	}
	
	
	@Column(name = "CD_TEC1", length = 40)
	public String getCdTec1() {
		return this.cdTec1;
	}

	public void setCdTec1(String cdTec1) {
		this.cdTec1 = cdTec1;
	}

	@Column(name = "CD_TEC2", length = 40)
	public String getCdTec2() {
		return this.cdTec2;
	}

	public void setCdTec2(String cdTec2) {
		this.cdTec2 = cdTec2;
	}

	@Column(name = "CD_TECRESP", length = 40)
	public String getCdTecresp() {
		return this.cdTecresp;
	}

	public void setCdTecresp(String cdTecresp) {
		this.cdTecresp = cdTecresp;
	}

	@Column(name = "CD_PRODUTOREDZ", length = 30)
	public String getCdProdutoredz() {
		return this.cdProdutoredz;
	}

	public void setCdProdutoredz(String cdProdutoredz) {
		this.cdProdutoredz = cdProdutoredz;
	}

	@Column(name = "CD_PRODUTO", length = 40)
	public String getCdProduto() {
		return this.cdProduto;
	}

	public void setCdProduto(String cdProduto) {
		this.cdProduto = cdProduto;
	}

	@Column(name = "NROP", length = 60)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "CB", length = 255)
	public String getCb() {
		return this.cb;
	}

	public void setCb(String valor) {
		this.cb = valor;
	}

	@Column(name = "CD_MOLDE", length = 40)
	public String getCdMolde() {
		return this.cdMolde;
	}

	public void setCdMolde(String cdMolde) {
		this.cdMolde = cdMolde;
	}

	@Column(name = "CD_ESTRUTURA", length = 4)
	public String getCdEstrutura() {
		return this.cdEstrutura;
	}

	public void setCdEstrutura(String cdEstrutura) {
		this.cdEstrutura = cdEstrutura;
	}


	@Column(name = "SEQUENCIAL")
	public Integer getSequencial() {
		return this.sequencial;
	}
	public void setSequencial(Integer sequencial) {
		this.sequencial = sequencial;
	}
	
	@Column(name = "ORIGEM")
	public String getOrigem() {
		return origem;
	}

	public void setOrigem(String origem) {
		this.origem = origem;
	}
	

	@Column(name = "ERROCONSOL")
	public String getErroconsol() {
		return this.erroconsol;
	}

	public void setErroconsol(String erroconsol) {
		this.erroconsol = erroconsol;
	}
    
    @Column(name="CD_COMPONENTE", length=60)
    public String getCdComponente() {
        return this.cdComponente;
    }
    
	public void setCdComponente(String cdComponente) {
        this.cdComponente = cdComponente;
    }

    @Column(name="cd_feeder", length=20)
    public String getCdFeeder() {
        return this.cdFeeder;
    }
    
    public void setCdFeeder(String cdFeeder) {
        this.cdFeeder = cdFeeder;
    }

    
    @Column(name="cd_nozzle", length=20)
    public String getCdNozzle() {
        return this.cdNozzle;
    }
    
    public void setCdNozzle(String cdNozzle) {
        this.cdNozzle = cdNozzle;
    }

	@Column(name = "IS_REGULAGEM")
	public Boolean getIsRegulagem() {
		return this.isRegulagem;
	}

	public void setIsRegulagem(Boolean isRegulagem) {
		this.isRegulagem = isRegulagem;
	}
	
	

	@Column(name = "IS_MONTAGEMFECHADAANTECIP")
    public Boolean getIsMontagemfechadaantecipadamente() {
		return isMontagemfechadaantecipadamente;
	}

	public void setIsMontagemfechadaantecipadamente(Boolean isMontagemfechadaantecipadamente) {
		this.isMontagemfechadaantecipadamente = isMontagemfechadaantecipadamente;
	}

	@Column(name="tp_erromontagem")
    public Integer getTpErromontagem() {
        return this.tpErromontagem;
    }
    
    public void setTpErromontagem(Integer tpErromontagem) {
        this.tpErromontagem = tpErromontagem;
    }

    
    @Column(name="qt_erromontagem")
    public Integer getQtErromontagem() {
        return this.qtErromontagem;
    }
    
    public void setQtErromontagem(Integer qtErromontagem) {
        this.qtErromontagem = qtErromontagem;
    }

    @Column(name="depara")
    public String getDepara() {
        return this.depara;
    }
    
    public void setDepara(String valor) {
        this.depara = valor;
    }
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "msEvt")
	public Set<MsEvtcep> getMsEvtceps() {
		return this.msEvtceps;
	}

	public void setMsEvtceps(Set<MsEvtcep> msEvtceps) {
		this.msEvtceps = msEvtceps;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pepro")
	public DwPepro getDwPepro() {
		return this.dwPepro;
	}

	public void setDwPepro(DwPepro dwPepro) {
		this.dwPepro = dwPepro;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "msEvt")
	public Set<MsEvtmontagem> getMsEvtmontagems() {
		return this.msEvtmontagems;
	}

	public void setMsEvtmontagems(Set<MsEvtmontagem> msEvtmontagems) {
		this.msEvtmontagems = msEvtmontagems;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "msEvt")
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "msEvt")
	public Set<MsEvtdefeito> getMsEvtdefeitos() {
		return this.msEvtdefeitos;
	}

	public void setMsEvtdefeitos(Set<MsEvtdefeito> msEvtdefeitos) {
		this.msEvtdefeitos = msEvtdefeitos;
	}

	@Column(name = "CD_DEFEITO", length = 60)
	public String getCdDefeito() {
		return this.cdDefeito;
	}

	public void setCdDefeito(String cd) {
		this.cdDefeito = cd;
	}

	@Column(name = "PRODUCAOLIQUIDA", precision = 14, scale = 4)
	public BigDecimal getProducaoliquida() {
		return producaoliquida;
	}

	public void setProducaoliquida(BigDecimal producaoliquida) {
		this.producaoliquida = producaoliquida;
	}

	@Column(name = "PRODUCAOREFUGADA", precision = 14, scale = 4)
	public BigDecimal getProducaorefugada() {
		return producaorefugada;
	}

	public void setProducaorefugada(BigDecimal producaorefugada) {
		this.producaorefugada = producaorefugada;
	}

	@Column(name = "CD_UP", length = 60)
	public String getCdUp() {
		return this.cdUp;
	}

	public void setCdUp(String cdUp) {
		this.cdUp = cdUp;
	}

	public String getCbserial() {
		return cbserial;
	}

	public void setCbserial(String cbserial) {
		this.cbserial = cbserial;
	}
	
	@Column(name = "seqbigint")
	public Long getSeqbigint() {
		return seqbigint;
	}
	public void setSeqbigint(Long seqbigint) {
		this.seqbigint = seqbigint;
	}
	
	@Column(name = "CD_ORIGEM", length = 40)
	public String getCdOrigem() {
		return this.cdOrigem;
	}

	public void setCdOrigem(String cdOrigem) {
		this.cdOrigem = cdOrigem;
	}

	@Column(name = "SEG_CICLOPADRAO", precision = 14, scale = 4)
	public BigDecimal getSegCiclopadrao() {
		return segCiclopadrao;
	}

	public void setSegCiclopadrao(BigDecimal segCiclopadrao) {
		this.segCiclopadrao = segCiclopadrao;
	}

	
}
