package idw.model.pojos;
// Generated 11/10/2011 08:52:14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.MsIhmTemplate;

/**
 * MsIhm generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MS_IHM")
public class MsIhm extends MsIhmTemplate implements java.io.Serializable {

	private BigDecimal idIhm;
	private MsUsr msUsr;
	private Date dthrHeartbeat;
	private Date dthrCadastro;
	private String urlConexao;
	
	private Boolean isEvtpnd;
	private Boolean isEvtciclofechado;
	private Boolean isEvttrabalhando;
	private Boolean isEvtparada;
	private Boolean isEvtrefugo;
	private Boolean isEvtalerta;
	private Boolean isEvtlogin;
	private Boolean isUpreg;
	private Boolean isEvttodos;
	
	private String urlIp;
	private String cdIhm;
	private String urlConexaoalt;
	private Set<MsMsihm> msMsihms = new HashSet<MsMsihm>(0);
	private Set<MsUpihm> msUpihms = new HashSet<MsUpihm>(0);

	public MsIhm() {
	}

	public MsIhm(BigDecimal idIhm, MsUsr msUsr) {
		this.idIhm = idIhm;
		this.msUsr = msUsr;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "MS_IHM_SEQ")
	@javax.persistence.SequenceGenerator(name = "MS_IHM_SEQ", sequenceName = "MS_IHM_SEQ")
	@Column(name = "ID_IHM", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdIhm() {
		return this.idIhm;
	}

	public void setIdIhm(BigDecimal idIhm) {
		this.idIhm = idIhm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USR", nullable = false)
	public MsUsr getMsUsr() {
		return this.msUsr;
	}

	public void setMsUsr(MsUsr msUsr) {
		this.msUsr = msUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_HEARTBEAT")
	public Date getDthrHeartbeat() {
		return this.dthrHeartbeat;
	}

	public void setDthrHeartbeat(Date dthrHeartbeat) {
		this.dthrHeartbeat = dthrHeartbeat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_CADASTRO")
	public Date getDthrCadastro() {
		return this.dthrCadastro;
	}

	public void setDthrCadastro(Date dthrCadastro) {
		this.dthrCadastro = dthrCadastro;
	}

	@Column(name = "URL_CONEXAO", length = 100)
	public String getUrlConexao() {
		return this.urlConexao;
	}

	public void setUrlConexao(String urlConexao) {
		this.urlConexao = urlConexao;
	}

	@Column(name = "IS_EVTPND", length = 1)
	public Boolean getIsEvtpnd() {
		return this.isEvtpnd;
	}

	public void setIsEvtpnd(Boolean isEvtpnd) {
		this.isEvtpnd = isEvtpnd;
	}

	@Column(name = "IS_EVTCICLOFECHADO", length = 1)
	public Boolean getIsEvtciclofechado() {
		return this.isEvtciclofechado;
	}

	public void setIsEvtciclofechado(Boolean isEvtciclofechado) {
		this.isEvtciclofechado = isEvtciclofechado;
	}

	@Column(name = "IS_EVTTRABALHANDO", length = 1)
	public Boolean getIsEvttrabalhando() {
		return this.isEvttrabalhando;
	}

	public void setIsEvttrabalhando(Boolean isEvttrabalhando) {
		this.isEvttrabalhando = isEvttrabalhando;
	}

	@Column(name = "IS_EVTPARADA", length = 1)
	public Boolean getIsEvtparada() {
		return this.isEvtparada;
	}

	public void setIsEvtparada(Boolean isEvtparada) {
		this.isEvtparada = isEvtparada;
	}

	@Column(name = "IS_EVTREFUGO", length = 1)
	public Boolean getIsEvtrefugo() {
		return this.isEvtrefugo;
	}

	public void setIsEvtrefugo(Boolean isEvtrefugo) {
		this.isEvtrefugo = isEvtrefugo;
	}

	@Column(name = "IS_EVTALERTA", length = 1)
	public Boolean getIsEvtalerta() {
		return this.isEvtalerta;
	}

	public void setIsEvtalerta(Boolean isEvtalerta) {
		this.isEvtalerta = isEvtalerta;
	}

	@Column(name = "IS_EVTLOGIN", length = 1)
	public Boolean getIsEvtlogin() {
		return this.isEvtlogin;
	}

	public void setIsEvtlogin(Boolean isEvtlogin) {
		this.isEvtlogin = isEvtlogin;
	}

	@Column(name = "IS_UPREG", length = 1)
	public Boolean getIsUpreg() {
		return this.isUpreg;
	}

	public void setIsUpreg(Boolean isUpreg) {
		this.isUpreg = isUpreg;
	}

	@Column(name = "IS_EVTTODOS", length = 1)
	public Boolean getIsEvttodos() {
		return this.isEvttodos;
	}

	public void setIsEvttodos(Boolean isEvttodos) {
		this.isEvttodos = isEvttodos;
	}

	@Column(name = "URL_IP", length = 100)
	public String getUrlIp() {
		return this.urlIp;
	}

	public void setUrlIp(String urlIp) {
		this.urlIp = urlIp;
	}

	@Column(name = "CD_IHM", length = 40)
	public String getCdIhm() {
		return this.cdIhm;
	}

	public void setCdIhm(String cdIhm) {
		this.cdIhm = cdIhm;
	}

	@Column(name = "URL_CONEXAOALT", length = 100)
	public String getUrlConexaoalt() {
		return this.urlConexaoalt;
	}

	public void setUrlConexaoalt(String urlConexaoalt) {
		this.urlConexaoalt = urlConexaoalt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msIhm")
	public Set<MsMsihm> getMsMsihms() {
		return this.msMsihms;
	}

	public void setMsMsihms(Set<MsMsihm> msMsihms) {
		this.msMsihms = msMsihms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msIhm")
	public Set<MsUpihm> getMsUpihms() {
		return this.msUpihms;
	}

	public void setMsUpihms(Set<MsUpihm> msUpihms) {
		this.msUpihms = msUpihms;
	}

}
