package idw.model.pojos;

// default package
// Generated 10/01/2011 10:46:16 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.MsMsicupTemplate;

/**
 * MsMsicup generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MS_MSICUP")
public class MsMsicup extends MsMsicupTemplate implements java.io.Serializable {

	private BigDecimal idMsicup;
	private MsUp msUp;
	private MsMs msMs;
	private MsIc msIc;
	private String urlConexao;
	private BigDecimal tpConexao;
	
	private String urlAuxiliar;
	
	private Boolean isAtivo;
	
	private Set<MsEvt> msEvts = new HashSet<MsEvt>(0);
	private Set<MsMsicupProduto> msMsicupProdutos = new HashSet<>();

	public MsMsicup() {
	}

	public MsMsicup(BigDecimal idMsicup) {
		this.idMsicup = idMsicup;
	}

	public MsMsicup(BigDecimal idMsicup, MsUp msUp, MsMs msMs, MsIc msIc,
			String urlConexao, String urlAuxiliar, BigDecimal tpConexao,String atributo, Set<MsEvt> msEvtpnds) {
		this.idMsicup = idMsicup;
		this.msUp = msUp;
		this.msMs = msMs;
		this.msIc = msIc;
		this.urlConexao = urlConexao;
		this.tpConexao = tpConexao;
		this.msEvts = msEvtpnds;
		this.urlAuxiliar = urlAuxiliar;
		
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "MS_MSICUP_SEQ")
	@javax.persistence.SequenceGenerator(name = "MS_MSICUP_SEQ", sequenceName = "MS_MSICUP_SEQ")
	@Column(name = "ID_MSICUP", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdMsicup() {
		return this.idMsicup;
	}

	public void setIdMsicup(BigDecimal idMsicup) {
		this.idMsicup = idMsicup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UP")
	public MsUp getMsUp() {
		return this.msUp;
	}

	public void setMsUp(MsUp msUp) {
		this.msUp = msUp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MS")
	public MsMs getMsMs() {
		return this.msMs;
	}

	public void setMsMs(MsMs msMs) {
		this.msMs = msMs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_IC")
	public MsIc getMsIc() {
		return this.msIc;
	}

	public void setMsIc(MsIc msIc) {
		this.msIc = msIc;
	}

	@Column(name = "URL_CONEXAO", length = 100)
	public String getUrlConexao() {
		return this.urlConexao;
	}

	public void setUrlConexao(String urlConexao) {
		this.urlConexao = urlConexao;
	}
	
	@Column(name = "URL_AUXILIAR", length = 100)
	public String getUrlAuxiliar() {
		return urlAuxiliar;
	}

	public void setUrlAuxiliar(String urlAuxiliar) {
		this.urlAuxiliar = urlAuxiliar;
	}

	@Column(name = "TP_CONEXAO", precision = 22, scale = 0)
	public BigDecimal getTpConexao() {
		return this.tpConexao;
	}

	public void setTpConexao(BigDecimal tpConexao) {
		this.tpConexao = tpConexao;
	}

	/* Alessandre Comentei o ATRIBUTO pois acho q foi incluido errado
	@Column(name = "ATRIBUTO", length = 50)
	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}
	*/
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msMsicup")
	public Set<MsEvt> getMsEvts() {
		return this.msEvts;
	}

	public void setMsEvts(Set<MsEvt> msEvts) {
		this.msEvts = msEvts;
	}

	@Column(name = "IS_ATIVO")
	public Boolean getIsAtivo() {
		return isAtivo;
	}

	public void setIsAtivo(Boolean isAtivo) {
		this.isAtivo = isAtivo;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "msMsicup")
	public Set<MsMsicupProduto> getMsMsicupProdutos() {
		return this.msMsicupProdutos;
	}

	public void setMsMsicupProdutos(Set<MsMsicupProduto> valor) {
		this.msMsicupProdutos = valor;
	}

}
