package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 07/07/2015 11:26:39 by Hibernate Tools 4.0.0

import idw.model.pojos.template.MsPerfilandonTemplate;

/**
 * MsPerfilandon generated by hbm2java
 */
@Entity
@Table(name = "ms_perfilandon")
public class MsPerfilandon extends MsPerfilandonTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idPerfilandon;
	private MsUsr msUsrByIdUsrStAtivo;
	private MsUsr msUsrByIdUsrRevisao;
	private String cdPerfilandon;
	private Long revisao;
	private String dsPerfilandon;
	private Byte stAtivo;
	private Date dtRevisao;
	private Date dtStativo;
	private Set<MsPerfilregras> msPerfilregrases = new HashSet<MsPerfilregras>(0);
	private Set<MsIc> msIcs = new HashSet<MsIc>(0);

	public MsPerfilandon() {
	}

	public MsPerfilandon(Long idPerfilandon) {
		this.idPerfilandon = idPerfilandon;
	}

	public MsPerfilandon(Long idPerfilandon, MsUsr msUsrByIdUsrStAtivo,
			MsUsr msUsrByIdUsrRevisao, String cdPerfilandon, Long revisao,
			String dsPerfilandon, Byte stAtivo, Date dtRevisao,
			Date dtStativo, Set<MsPerfilregras> msPerfilregrases,
			Set<MsIc> msIcs) {
		this.idPerfilandon = idPerfilandon;
		this.msUsrByIdUsrStAtivo = msUsrByIdUsrStAtivo;
		this.msUsrByIdUsrRevisao = msUsrByIdUsrRevisao;
		this.cdPerfilandon = cdPerfilandon;
		this.revisao = revisao;
		this.dsPerfilandon = dsPerfilandon;
		this.stAtivo = stAtivo;
		this.dtRevisao = dtRevisao;
		this.dtStativo = dtStativo;
		this.msPerfilregrases = msPerfilregrases;
		this.msIcs = msIcs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "MS_PERFILANDON_SEQ")
	@javax.persistence.SequenceGenerator(name = "MS_PERFILANDON_SEQ", sequenceName = "MS_PERFILANDON_SEQ")
	@Column(name = "id_perfilandon", unique = true, nullable = false)
	public Long getIdPerfilandon() {
		return this.idPerfilandon;
	}

	public void setIdPerfilandon(Long idPerfilandon) {
		this.idPerfilandon = idPerfilandon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrStAtivo")
	public MsUsr getMsUsrByIdUsrStAtivo() {
		return this.msUsrByIdUsrStAtivo;
	}

	public void setMsUsrByIdUsrStAtivo(MsUsr msUsrByIdUsrStAtivo) {
		this.msUsrByIdUsrStAtivo = msUsrByIdUsrStAtivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrRevisao")
	public MsUsr getMsUsrByIdUsrRevisao() {
		return this.msUsrByIdUsrRevisao;
	}

	public void setMsUsrByIdUsrRevisao(MsUsr msUsrByIdUsrRevisao) {
		this.msUsrByIdUsrRevisao = msUsrByIdUsrRevisao;
	}

	@Column(name = "cd_perfilandon", length = 60)
	public String getCdPerfilandon() {
		return this.cdPerfilandon;
	}

	public void setCdPerfilandon(String cdPerfilandon) {
		this.cdPerfilandon = cdPerfilandon;
	}

	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_perfilandon", length = 100)
	public String getDsPerfilandon() {
		return this.dsPerfilandon;
	}

	public void setDsPerfilandon(String dsPerfilandon) {
		this.dsPerfilandon = dsPerfilandon;
	}

	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	//@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "msPerfilandon")
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "msPerfilandon")
	public Set<MsPerfilregras> getMsPerfilregrases() {
		return this.msPerfilregrases;
	}

	public void setMsPerfilregrases(Set<MsPerfilregras> msPerfilregrases) {
		this.msPerfilregrases = msPerfilregrases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msPerfilandon")
	public Set<MsIc> getMsIcs() {
		return this.msIcs;
	}

	public void setMsIcs(Set<MsIc> msIcs) {
		this.msIcs = msIcs;
	}

}
