package idw.model.pojos;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MsPtColetaLogin generated by hbm2java
 */
@Entity
@Table(name="ms_pt_coleta_login")
public class MsPtColetaLogin  implements java.io.Serializable {


     /**
	 * 
	 */
	 private static final long serialVersionUID = 1L;
	 private Long idColetalogin;
     private MsPtColeta msPtColeta;
     private OmUsr omUsr;
     private Date dthrIlogin;

    public MsPtColetaLogin() {
    }

	
    public MsPtColetaLogin(Long idColetalogin, MsPtColeta msPtColeta) {
        this.idColetalogin = idColetalogin;
        this.msPtColeta = msPtColeta;
    }
    public MsPtColetaLogin(Long idColetalogin, MsPtColeta msPtColeta, OmUsr omUsr, Date dthrIlogin) {
       this.idColetalogin = idColetalogin;
       this.msPtColeta = msPtColeta;
       this.omUsr = omUsr;
       this.dthrIlogin = dthrIlogin;
    }
   
    @Id 
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "MS_PT_COLETA_LOGIN_SEQ")
	@javax.persistence.SequenceGenerator(name = "MS_PT_COLETA_LOGIN_SEQ", sequenceName = "MS_PT_COLETA_LOGIN_SEQ")
    @Column(name="id_coletalogin", unique=true, nullable=false)
    public Long getIdColetalogin() {
        return this.idColetalogin;
    }
    
    public void setIdColetalogin(Long idColetalogin) {
        this.idColetalogin = idColetalogin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pt", nullable=false)
    public MsPtColeta getMsPtColeta() {
        return this.msPtColeta;
    }
    
    public void setMsPtColeta(MsPtColeta msPtColeta) {
        this.msPtColeta = msPtColeta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usr")
    public OmUsr getOmUsr() {
        return this.omUsr;
    }
    
    public void setOmUsr(OmUsr omUsr) {
        this.omUsr = omUsr;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dthr_ilogin", length=23)
    public Date getDthrIlogin() {
        return this.dthrIlogin;
    }
    
    public void setDthrIlogin(Date dthrIlogin) {
        this.dthrIlogin = dthrIlogin;
    }




}


