package idw.model.pojos;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.MsTpevtTemplate;

/**
 * MsTpevt generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MS_TPEVT")
public class MsTpevt extends MsTpevtTemplate implements java.io.Serializable {

	private Long idTpevt;
	private String dsTpevt;
	private BigDecimal deparaPdba;
	private Set<MsEvt> msEvts = new HashSet<MsEvt>(0);

	public MsTpevt() {
	}

	public MsTpevt(Long idTpevt) {
		this.idTpevt = idTpevt;
	}

	public MsTpevt(Long idTpevt, String dsTppevt, BigDecimal deparaPdba,
			Set<MsEvt> msEvts) {
		this.idTpevt = idTpevt;
		this.dsTpevt = dsTppevt;
		this.deparaPdba = deparaPdba;
		this.msEvts = msEvts;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "MS_TPEVT_SEQ")
	@javax.persistence.SequenceGenerator(name = "MS_TPEVT_SEQ", sequenceName = "MS_TPEVT_SEQ")
	@Column(name = "ID_TPEVT", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdTpevt() {
		return this.idTpevt;
	}

	public void setIdTpevt(Long idTpevt) {
		this.idTpevt = idTpevt;
	}

	@Column(name = "DS_TPEVT", length = 100)
	public String getDsTpevt() {
		return this.dsTpevt;
	}

	public void setDsTpevt(String dsTppevt) {
		this.dsTpevt = dsTppevt;
	}

	@Column(name = "DEPARA_PDBA", precision = 22, scale = 0)
	public BigDecimal getDeparaPdba() {
		return this.deparaPdba;
	}

	public void setDeparaPdba(BigDecimal deparaPdba) {
		this.deparaPdba = deparaPdba;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msTpevt")
	public Set<MsEvt> getMsEvts() {
		return this.msEvts;
	}

	public void setMsEvts(Set<MsEvt> msEvts) {
		this.msEvts = msEvts;
	}

}
