package idw.model.pojos;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.MsUsrTemplate;

/**
 * MsUsr generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MS_USR")
public class MsUsr extends MsUsrTemplate implements java.io.Serializable {

	private BigDecimal idUsr;
	private String cdUsr;
	private BigDecimal revisao;
	private String nmUsr;
	private Date dthrRevisao;
	private Date dthrStativo;
	private BigDecimal stAtivo;
	private String login;
	private String senha;
	private Set<MsIhm> msIhms = new HashSet<MsIhm>(0);
	private Set<MsMs> msMses = new HashSet<MsMs>(0);
	private Set<MsIc> msIcs = new HashSet<MsIc>(0);
	private Set<MsUp> msUps = new HashSet<MsUp>(0);
	private Set<MsCfg> msCfgs = new HashSet<MsCfg>(0);
	private Set<MsDetectorusr> msDetectorusrs = new HashSet<MsDetectorusr>(0);

	public MsUsr() {
	}

	public MsUsr(BigDecimal idUsr) {
		this.idUsr = idUsr;
	}

	public MsUsr(BigDecimal idUsr, String cdUsr, BigDecimal revisao,
			String nmUsr, Date dthrRevisao, Date dthrStativo,
			BigDecimal stAtivo, String login, String senha, Set<MsIhm> msIhms,
			Set<MsMs> msMses, Set<MsIc> msIcs, Set<MsUp> msUps,
			Set<MsDetectorusr> msDetectorusrs) {
		this.idUsr = idUsr;
		this.cdUsr = cdUsr;
		this.revisao = revisao;
		this.nmUsr = nmUsr;
		this.dthrRevisao = dthrRevisao;
		this.dthrStativo = dthrStativo;
		this.stAtivo = stAtivo;
		this.login = login;
		this.senha = senha;
		this.msIhms = msIhms;
		this.msMses = msMses;
		this.msIcs = msIcs;
		this.msUps = msUps;
		this.msDetectorusrs = msDetectorusrs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "MS_USR_SEQ")
	@javax.persistence.SequenceGenerator(name = "MS_USR_SEQ", sequenceName = "MS_USR_SEQ")
	@Column(name = "ID_USR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUsr() {
		return this.idUsr;
	}

	public void setIdUsr(BigDecimal idUsr) {
		this.idUsr = idUsr;
	}

	@Column(name = "CD_USR", length = 40)
	public String getCdUsr() {
		return this.cdUsr;
	}

	public void setCdUsr(String cdUsr) {
		this.cdUsr = cdUsr;
	}

	@Column(name = "REVISAO", precision = 22, scale = 0)
	public BigDecimal getRevisao() {
		return this.revisao;
	}

	public void setRevisao(BigDecimal revisao) {
		this.revisao = revisao;
	}

	@Column(name = "NM_USR", length = 100)
	public String getNmUsr() {
		return this.nmUsr;
	}

	public void setNmUsr(String nmUsr) {
		this.nmUsr = nmUsr;
	}

	@Column(name = "DTHR_REVISAO")
	public Date getDthrRevisao() {
		return this.dthrRevisao;
	}

	public void setDthrRevisao(Date dthrRevisao) {
		this.dthrRevisao = dthrRevisao;
	}

	@Column(name = "DTHR_STATIVO")
	public Date getDthrStativo() {
		return this.dthrStativo;
	}

	public void setDthrStativo(Date dthrStativo) {
		this.dthrStativo = dthrStativo;
	}

	@Column(name = "ST_ATIVO", precision = 22, scale = 0)
	public BigDecimal getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(BigDecimal stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "LOGIN", length = 40)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "SENHA", length = 40)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msUsr")
	public Set<MsIhm> getMsIhms() {
		return this.msIhms;
	}

	public void setMsIhms(Set<MsIhm> msIhms) {
		this.msIhms = msIhms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msUsr")
	public Set<MsMs> getMsMses() {
		return this.msMses;
	}

	public void setMsMses(Set<MsMs> msMses) {
		this.msMses = msMses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msUsr")
	public Set<MsIc> getMsIcs() {
		return this.msIcs;
	}

	public void setMsIcs(Set<MsIc> msIcs) {
		this.msIcs = msIcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msUsr")
	public Set<MsUp> getMsUps() {
		return this.msUps;
	}

	public void setMsUps(Set<MsUp> msUps) {
		this.msUps = msUps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msUsr")
	public Set<MsCfg> getMsCfgs() {
		return this.msCfgs;
	}

	public void setMsCfgs(Set<MsCfg> msCfgs) {
		this.msCfgs = msCfgs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msUsr")
	public Set<MsDetectorusr> getMsDetectorusrs() {
		return this.msDetectorusrs;
	}

	public void setMsDetectorusrs(Set<MsDetectorusr> msDetectorusrs) {
		this.msDetectorusrs = msDetectorusrs;
	}
}
