package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.OmCargoTemplate;

/**
 * OmCargo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "OM_CARGO")
public class OmCargo extends OmCargoTemplate implements java.io.Serializable {

	private long idCargo;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdCargo;
	private Long revisao;
	private String dsCargo;
	private Byte stAtivo;
	private Date dtStativo;
	private Date dtRevisao;
	private Set<OmUsr> omUsrs = new HashSet<OmUsr>(0);

	public OmCargo() {
	}

	public OmCargo(long idCargo, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idCargo = idCargo;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public OmCargo(long idCargo, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdCargo, Long revisao,
			String dsCargo, Byte stAtivo, Date dtStativo, Date dtRevisao,
			Set<OmUsr> omUsrs) {
		this.idCargo = idCargo;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdCargo = cdCargo;
		this.revisao = revisao;
		this.dsCargo = dsCargo;
		this.stAtivo = stAtivo;
		this.dtStativo = dtStativo;
		this.dtRevisao = dtRevisao;
		this.omUsrs = omUsrs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_CARGO_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_CARGO_SEQ", sequenceName = "OM_CARGO_SEQ")
	@Column(name = "ID_CARGO", unique = true, nullable = false, precision = 22, scale = 0)
	public long getIdCargo() {
		return this.idCargo;
	}

	public void setIdCargo(long idCargo) {
		this.idCargo = idCargo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRSTATIVO", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRREVISAO", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "CD_CARGO", length = 30)
	public String getCdCargo() {
		return this.cdCargo;
	}

	public void setCdCargo(String cdCargo) {
		this.cdCargo = cdCargo;
	}

	@Override
	@Column(name = "REVISAO", precision = 22, scale = 0)
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "DS_CARGO", length = 100)
	public String getDsCargo() {
		return this.dsCargo;
	}

	public void setDsCargo(String dsCargo) {
		this.dsCargo = dsCargo;
	}

	@Override
	@Column(name = "ST_ATIVO")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_STATIVO", length = 7)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_REVISAO", length = 7)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omCargo")
	public Set<OmUsr> getOmUsrs() {
		return this.omUsrs;
	}

	public void setOmUsrs(Set<OmUsr> omUsrs) {
		this.omUsrs = omUsrs;
	}

}
