package idw.model.pojos;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import idw.model.pojos.template.OmCfgindTemplate;

/**
 * OmCfgind generated by hbm2java
 */
@Entity
@Table(name = "OM_CFGIND")
public class OmCfgind extends OmCfgindTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idCfgind;
	private OmCfg omCfg;
	private OmInd omInd;
	private BigDecimal indInferior;
	private BigDecimal indSuperior;
	private BigDecimal indMeta;

	public OmCfgind() {
	}

	public OmCfgind(Long idCfgind) {
		this.idCfgind = idCfgind;
	}

	public OmCfgind(Long idCfgind, OmCfg omCfg, OmInd omInd,
			BigDecimal indInferior, BigDecimal indSuperior, BigDecimal indMeta) {
		this.idCfgind = idCfgind;
		this.omCfg = omCfg;
		this.omInd = omInd;
		this.indInferior = indInferior;
		this.indSuperior = indSuperior;
		this.indMeta = indMeta;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_CFGIND_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_CFGIND_SEQ", sequenceName = "OM_CFGIND_SEQ")
	@Column(name = "ID_CFGIND", nullable = false, precision = 63, scale = 0)
	//unique = true, 
	public Long getIdCfgind() {
		return this.idCfgind;
	}

	public void setIdCfgind(Long idCfgind) {
		this.idCfgind = idCfgind;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CFG")
	public OmCfg getOmCfg() {
		return this.omCfg;
	}

	public void setOmCfg(OmCfg omCfg) {
		this.omCfg = omCfg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_IND")
	public OmInd getOmInd() {
		return this.omInd;
	}

	public void setOmInd(OmInd omInd) {
		this.omInd = omInd;
	}

	@Column(name = "IND_INFERIOR", precision = 6, scale = 3)
	public BigDecimal getIndInferior() {
		return this.indInferior;
	}

	public void setIndInferior(BigDecimal indInferior) {
		this.indInferior = indInferior;
	}

	@Column(name = "IND_SUPERIOR", precision = 6, scale = 3)
	public BigDecimal getIndSuperior() {
		return this.indSuperior;
	}

	public void setIndSuperior(BigDecimal indSuperior) {
		this.indSuperior = indSuperior;
	}

	@Column(name = "IND_META", precision = 6, scale = 3)
	public BigDecimal getIndMeta() {
		return this.indMeta;
	}

	public void setIndMeta(BigDecimal indMeta) {
		this.indMeta = indMeta;
	}

}
