package idw.model.pojos;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.OmEmpresaTemplate;

/**
 * OmEmpresa generated by hbm2java
 */
@Entity
@Table(name = "om_empresa")
public class OmEmpresa extends OmEmpresaTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idEmpresa;
	private String cdEmpresa;
	private String dsEmpresa;
	private String endereco;
	private String cidade;
	private String estado;
	private String pais;
	private String chaveVerificacao;
	private byte[] imgLogotipo;
	private byte[] imgBackground;
	private byte[] imgRodape;
	private Set<OmLicenca> omLicencas = new HashSet<OmLicenca>(0);
	private Set<OmCfg> omCfgs = new HashSet<OmCfg>(0);

	public OmEmpresa() {
	}

	public OmEmpresa(Long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public OmEmpresa(Long idEmpresa, String cdEmpresa, String dsEmpresa,
			String endereco, String cidade, String estado, String pais,
			byte[] imgLogotipo, byte[] imgBackground, byte[] imgRodape,
			Set<OmCfg> omCfgs) {
		this.idEmpresa = idEmpresa;
		this.cdEmpresa = cdEmpresa;
		this.dsEmpresa = dsEmpresa;
		this.endereco = endereco;
		this.cidade = cidade;
		this.estado = estado;
		this.pais = pais;
		this.imgLogotipo = imgLogotipo;
		this.imgBackground = imgBackground;
		this.imgRodape = imgRodape;
		this.omCfgs = omCfgs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_EMPRESA_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_EMPRESA_SEQ", sequenceName = "OM_EMPRESA_SEQ")
	@Column(name = "id_empresa", unique = true, nullable = false)
	public Long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "cd_empresa", length = 60)
	public String getCdEmpresa() {
		return this.cdEmpresa;
	}

	public void setCdEmpresa(String cdEmpresa) {
		this.cdEmpresa = cdEmpresa;
	}

	@Column(name = "ds_empresa", length = 256)
	public String getDsEmpresa() {
		return this.dsEmpresa;
	}

	public void setDsEmpresa(String dsEmpresa) {
		this.dsEmpresa = dsEmpresa;
	}

	@Column(name = "endereco", length = 256)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "cidade", length = 256)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "estado", length = 60)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "pais", length = 60)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omEmpresa")
	public Set<OmCfg> getOmCfgs() {
		return this.omCfgs;
	}

	public void setOmCfgs(Set<OmCfg> omCfgs) {
		this.omCfgs = omCfgs;
	}

	@Column(name = "chave_verificacao", length = 512)
	public String getChaveVerificacao() {
		return this.chaveVerificacao;
	}

	public void setChaveVerificacao(String chaveVerificacao) {
		this.chaveVerificacao = chaveVerificacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omEmpresa")
	public Set<OmLicenca> getOmLicencas() {
		return this.omLicencas;
	}

	public void setOmLicencas(Set<OmLicenca> omLicencas) {
		this.omLicencas = omLicencas;
	}

	@Column(name = "img_logotipo")
	public byte[] getImgLogotipo() {
		return this.imgLogotipo;
	}

	public void setImgLogotipo(byte[] imgLogotipo) {
		this.imgLogotipo = imgLogotipo;
	}

	@Column(name = "img_rodape")
	public byte[] getImgRodape() {
		return this.imgRodape;
	}

	public void setImgRodape(byte[] imgRodape) {
		this.imgRodape = imgRodape;
	}

	@Column(name = "img_background")
	public byte[] getImgBackground() {
		return this.imgBackground;
	}

	public void setImgBackground(byte[] imgBackground) {
		this.imgBackground = imgBackground;
	}

}
