package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 05/01/2010 11:04:20 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.OmForTemplate;


/**
 * OmFor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_for")
public class OmFor extends OmForTemplate implements java.io.Serializable {

	private long idFor;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdFor;
	private Long revisao;
	private String nmFornecedor;
	private Date dtRevisao;
	private Date dtStativo;
	private Byte stAtivo;
	private Set<OmProduto> omProdutos = new HashSet<OmProduto>(0);

	public OmFor() {
	}

	public OmFor(long idFor, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idFor = idFor;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public OmFor(long idFor, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdFor, Long revisao,
			String nmFornecedor, Date dtRevisao, Date dtStativo, Byte stAtivo,
			Set<OmProduto> omProdutos) {
		this.idFor = idFor;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdFor = cdFor;
		this.revisao = revisao;
		this.nmFornecedor = nmFornecedor;
		this.dtRevisao = dtRevisao;
		this.dtStativo = dtStativo;
		this.stAtivo = stAtivo;
		this.omProdutos = omProdutos;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_FOR_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_FOR_SEQ", sequenceName = "OM_FOR_SEQ")
	@Column(name = "id_for", unique = true, nullable = false)
	public long getIdFor() {
		return this.idFor;
	}

	public void setIdFor(long idFor) {
		this.idFor = idFor;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "cd_for", length = 30)
	public String getCdFor() {
		return this.cdFor;
	}

	public void setCdFor(String cdFor) {
		this.cdFor = cdFor;
	}

	@Override
	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "nm_fornecedor", length = 256)
	public String getNmFornecedor() {
		return this.nmFornecedor;
	}

	public void setNmFornecedor(String nmFornecedor) {
		this.nmFornecedor = nmFornecedor;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Override
	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omFor")
	public Set<OmProduto> getOmProdutos() {
		return this.omProdutos;
	}

	public void setOmProdutos(Set<OmProduto> omProdutos) {
		this.omProdutos = omProdutos;
	}

}
