package idw.model.pojos;
// Generated 28/07/2011 10:26:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OmGarpro generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "OM_GARPRO")
public class OmGarpro implements java.io.Serializable {

	private Long idGarpro;
	private OmProduto omProduto;
	private OmGarantia omGarantia;
	private Date dthrIniciovalidade;
	private Date dthrFimvalidade;
	private String ns;
	private BigDecimal tpLicenca;
	private BigDecimal qtLicencasvendidas;
	private BigDecimal qtLicencascontratomanu;

	public OmGarpro() {
	}

	public OmGarpro(Long idGarpro, OmProduto omProduto, OmGarantia omGarantia) {
		this.idGarpro = idGarpro;
		this.omProduto = omProduto;
		this.omGarantia = omGarantia;
	}

	public OmGarpro(Long idGarpro, OmProduto omProduto,
			OmGarantia omGarantia, Date dthrIniciovalidade,
			Date dthrFimvalidade, String ns, BigDecimal tpLicenca,
			BigDecimal qtLicencasvendidas, BigDecimal qtLicencascontratomanu) {
		this.idGarpro = idGarpro;
		this.omProduto = omProduto;
		this.omGarantia = omGarantia;
		this.dthrIniciovalidade = dthrIniciovalidade;
		this.dthrFimvalidade = dthrFimvalidade;
		this.ns = ns;
		this.tpLicenca = tpLicenca;
		this.qtLicencasvendidas = qtLicencasvendidas;
		this.qtLicencascontratomanu = qtLicencascontratomanu;
	}

	@Id
	@Column(name = "ID_GARPRO", unique = true, nullable = false, precision = 63, scale = 0)
	public Long getIdGarpro() {
		return this.idGarpro;
	}

	public void setIdGarpro(Long idGarpro) {
		this.idGarpro = idGarpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUTO", nullable = false)
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GARANTIA", nullable = false)
	public OmGarantia getOmGarantia() {
		return this.omGarantia;
	}

	public void setOmGarantia(OmGarantia omGarantia) {
		this.omGarantia = omGarantia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHR_INICIOVALIDADE", length = 7)
	public Date getDthrIniciovalidade() {
		return this.dthrIniciovalidade;
	}

	public void setDthrIniciovalidade(Date dthrIniciovalidade) {
		this.dthrIniciovalidade = dthrIniciovalidade;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHR_FIMVALIDADE", length = 7)
	public Date getDthrFimvalidade() {
		return this.dthrFimvalidade;
	}

	public void setDthrFimvalidade(Date dthrFimvalidade) {
		this.dthrFimvalidade = dthrFimvalidade;
	}

	@Column(name = "NS", length = 30)
	public String getNs() {
		return this.ns;
	}

	public void setNs(String ns) {
		this.ns = ns;
	}

	@Column(name = "TP_LICENCA", precision = 22, scale = 0)
	public BigDecimal getTpLicenca() {
		return this.tpLicenca;
	}

	public void setTpLicenca(BigDecimal tpLicenca) {
		this.tpLicenca = tpLicenca;
	}

	@Column(name = "QT_LICENCASVENDIDAS", precision = 22, scale = 0)
	public BigDecimal getQtLicencasvendidas() {
		return this.qtLicencasvendidas;
	}

	public void setQtLicencasvendidas(BigDecimal qtLicencasvendidas) {
		this.qtLicencasvendidas = qtLicencasvendidas;
	}

	@Column(name = "QT_LICENCASCONTRATOMANU", precision = 22, scale = 0)
	public BigDecimal getQtLicencascontratomanu() {
		return this.qtLicencascontratomanu;
	}

	public void setQtLicencascontratomanu(BigDecimal qtLicencascontratomanu) {
		this.qtLicencascontratomanu = qtLicencascontratomanu;
	}

}
