package idw.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 05/01/2010 11:04:20 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.OmGrntsTemplate;


/**
 * OmGrnts generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_grnts")
public class OmGrnts extends OmGrntsTemplate implements java.io.Serializable {

	private long idGrnts;
	private OmResgui omResgui;
	private OmUsrgrp omUsrgrp;
	private Byte tpAcesso;

	public OmGrnts() {
	}

	public OmGrnts(long idGrnts, OmResgui omResgui, OmUsrgrp omUsrgrp) {
		this.idGrnts = idGrnts;
		this.omResgui = omResgui;
		this.omUsrgrp = omUsrgrp;
	}

	public OmGrnts(long idGrnts, OmResgui omResgui, OmUsrgrp omUsrgrp,
			Byte tpAcesso) {
		this.idGrnts = idGrnts;
		this.omResgui = omResgui;
		this.omUsrgrp = omUsrgrp;
		this.tpAcesso = tpAcesso;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_GRNTS_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_GRNTS_SEQ", sequenceName = "OM_GRNTS_SEQ")
	@Column(name = "id_grnts", nullable = false)
	public long getIdGrnts() {
		return this.idGrnts;
	}

	public void setIdGrnts(long idGrnts) {
		this.idGrnts = idGrnts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resgui", nullable = false)
	public OmResgui getOmResgui() {
		return this.omResgui;
	}

	public void setOmResgui(OmResgui omResgui) {
		this.omResgui = omResgui;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrgrp", nullable = false)
	public OmUsrgrp getOmUsrgrp() {
		return this.omUsrgrp;
	}

	public void setOmUsrgrp(OmUsrgrp omUsrgrp) {
		this.omUsrgrp = omUsrgrp;
	}

	@Column(name = "tp_acesso")
	public Byte getTpAcesso() {
		return this.tpAcesso;
	}

	public void setTpAcesso(Byte tpAcesso) {
		this.tpAcesso = tpAcesso;
	}

}
