package idw.model.pojos;

// Generated 05/01/2010 11:04:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OmIndpt generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_indpt")
public class OmIndpt implements java.io.Serializable {

	private long idIndpt;
	private OmInd omInd;
	private OmPt omPt;
	private BigDecimal indInferior;
	private BigDecimal indSuperior;
	private BigDecimal indMeta;

	public OmIndpt() {
	}

	public OmIndpt(long idIndpt, OmInd omInd, OmPt omPt) {
		this.idIndpt = idIndpt;
		this.omInd = omInd;
		this.omPt = omPt;
	}

	public OmIndpt(long idIndpt, OmInd omInd, OmPt omPt, BigDecimal indInferior,
			BigDecimal indSuperior, BigDecimal indMeta) {
		this.idIndpt = idIndpt;
		this.omInd = omInd;
		this.omPt = omPt;
		this.indInferior = indInferior;
		this.indSuperior = indSuperior;
		this.indMeta = indMeta;
	}

	@Id
	@Column(name = "id_indpt", unique = true, nullable = false)
	public long getIdIndpt() {
		return this.idIndpt;
	}

	public void setIdIndpt(long idIndpt) {
		this.idIndpt = idIndpt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ind", nullable = false)
	public OmInd getOmInd() {
		return this.omInd;
	}

	public void setOmInd(OmInd omInd) {
		this.omInd = omInd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pt", nullable = false)
	public OmPt getOmPt() {
		return this.omPt;
	}

	public void setOmPt(OmPt omPt) {
		this.omPt = omPt;
	}

	@Column(name = "IND_INFERIOR", precision = 6, scale = 3)
	public BigDecimal getIndInferior() {
		return this.indInferior;
	}

	public void setIndInferior(BigDecimal indInferior) {
		this.indInferior = indInferior;
	}

	@Column(name = "ind_superior", precision = 6, scale = 3)
	public BigDecimal getIndSuperior() {
		return this.indSuperior;
	}

	public void setIndSuperior(BigDecimal indSuperior) {
		this.indSuperior = indSuperior;
	}

	@Column(name = "ind_meta", precision = 6, scale = 3)
	public BigDecimal getIndMeta() {
		return this.indMeta;
	}

	public void setIndMeta(BigDecimal indMeta) {
		this.indMeta = indMeta;
	}

}
