package idw.model.pojos;

// Generated 05/01/2010 11:04:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OmIndtppt generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_indtppt")
public class OmIndtppt implements java.io.Serializable {

	private long idIndtppt;
	private OmTppt omTppt;
	private OmInd omInd;
	private BigDecimal numInferior;
	private BigDecimal numSuperior;
	private BigDecimal numMeta;

	public OmIndtppt() {
	}

	public OmIndtppt(long idIndtppt, OmTppt omTppt, OmInd omInd) {
		this.idIndtppt = idIndtppt;
		this.omTppt = omTppt;
		this.omInd = omInd;
	}

	public OmIndtppt(long idIndtppt, OmTppt omTppt, OmInd omInd,
			BigDecimal numInf, BigDecimal numSuperior, BigDecimal numMeta) {
		this.idIndtppt = idIndtppt;
		this.omTppt = omTppt;
		this.omInd = omInd;
		this.numInferior = numInf;
		this.numSuperior = numSuperior;
		this.numMeta = numMeta;
	}

	@Id
	@Column(name = "id_indtppt", unique = true, nullable = false)
	public long getIdIndtppt() {
		return this.idIndtppt;
	}

	public void setIdIndtppt(long idIndtppt) {
		this.idIndtppt = idIndtppt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tppt", nullable = false)
	public OmTppt getOmTppt() {
		return this.omTppt;
	}

	public void setOmTppt(OmTppt omTppt) {
		this.omTppt = omTppt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ind", nullable = false)
	public OmInd getOmInd() {
		return this.omInd;
	}

	public void setOmInd(OmInd omInd) {
		this.omInd = omInd;
	}

	@Column(name = "IND_INFERIOR", precision = 6, scale = 3)
	public BigDecimal getNumInferior() {
		return this.numInferior;
	}

	public void setNumInferior(BigDecimal numInferior) {
		this.numInferior = numInferior;
	}

	@Column(name = "ind_superior", precision = 6, scale = 3)
	public BigDecimal getNumSuperior() {
		return this.numSuperior;
	}

	public void setNumSuperior(BigDecimal numSuperior) {
		this.numSuperior = numSuperior;
	}

	@Column(name = "ind_meta", precision = 6, scale = 3)
	public BigDecimal getNumMeta() {
		return this.numMeta;
	}

	public void setNumMeta(BigDecimal numMeta) {
		this.numMeta = numMeta;
	}

}
