package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OmLicenca generated by hbm2java
 */
@Entity
@Table(name = "om_licenca")
public class OmLicenca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idLicenca;
	private OmEmpresa omEmpresa;
	private OmTplicenca omTplicenca;
	private Date dtValidade;
	private Boolean isTryout;
	private String chaveVerificacao;
	private Integer qtLicencas;
	private Date dtEmissao;
	private Integer qtVezesclienteautoupdate;
	private String documento;
	private String chaveVerificacaoEmpresa;
	private Set<OmLicencaPt> omLicencaPts = new HashSet<OmLicencaPt>(0);
	private Set<OmLicmodrec> omLicmodrecs = new HashSet<OmLicmodrec>(0);

	public OmLicenca() {
	}

	public OmLicenca(Long idLicenca, OmEmpresa omEmpresa, OmTplicenca omTplicenca) {
		this.idLicenca = idLicenca;
		this.omEmpresa = omEmpresa;
		this.omTplicenca = omTplicenca;
	}

	public OmLicenca(Long idLicenca, OmEmpresa omEmpresa, OmTplicenca omTplicenca, Date dtValidade, Boolean isTryout,
			String chaveVerificacao, Integer qtLicencas, Date dtEmissao, Integer qtVezesclienteautoupdate,
			String documento, String chaveVerificacaoEmpresa, Set<OmLicencaPt> omLicencaPts,
			Set<OmLicmodrec> omLicmodrecs) {
		this.idLicenca = idLicenca;
		this.omEmpresa = omEmpresa;
		this.omTplicenca = omTplicenca;
		this.dtValidade = dtValidade;
		this.isTryout = isTryout;
		this.chaveVerificacao = chaveVerificacao;
		this.qtLicencas = qtLicencas;
		this.dtEmissao = dtEmissao;
		this.qtVezesclienteautoupdate = qtVezesclienteautoupdate;
		this.documento = documento;
		this.chaveVerificacaoEmpresa = chaveVerificacaoEmpresa;
		this.omLicencaPts = omLicencaPts;
		this.omLicmodrecs = omLicmodrecs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_LICENCA_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_LICENCA_SEQ", sequenceName = "OM_LICENCA_SEQ")
	@Column(name = "id_licenca", unique = true, nullable = false)
	public Long getIdLicenca() {
		return this.idLicenca;
	}

	public void setIdLicenca(Long idLicenca) {
		this.idLicenca = idLicenca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public OmEmpresa getOmEmpresa() {
		return this.omEmpresa;
	}

	public void setOmEmpresa(OmEmpresa omEmpresa) {
		this.omEmpresa = omEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tplicenca", nullable = false)
	public OmTplicenca getOmTplicenca() {
		return this.omTplicenca;
	}

	public void setOmTplicenca(OmTplicenca omTplicenca) {
		this.omTplicenca = omTplicenca;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_validade")
	public Date getDtValidade() {
		return this.dtValidade;
	}

	public void setDtValidade(Date dtValidade) {
		this.dtValidade = dtValidade;
	}

	@Column(name = "is_tryout")
	public Boolean getIsTryout() {
		return this.isTryout;
	}

	public void setIsTryout(Boolean isTryout) {
		this.isTryout = isTryout;
	}

	@Column(name = "chave_verificacao", length = 512)
	public String getChaveVerificacao() {
		return this.chaveVerificacao;
	}

	public void setChaveVerificacao(String chaveVerificacao) {
		this.chaveVerificacao = chaveVerificacao;
	}

	@Column(name = "qt_licencas")
	public Integer getQtLicencas() {
		return this.qtLicencas;
	}

	public void setQtLicencas(Integer qtLicencas) {
		this.qtLicencas = qtLicencas;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_emissao")
	public Date getDtEmissao() {
		return this.dtEmissao;
	}

	public void setDtEmissao(Date dtEmissao) {
		this.dtEmissao = dtEmissao;
	}

	@Column(name = "qt_vezesclienteautoupdate")
	public Integer getQtVezesclienteautoupdate() {
		return this.qtVezesclienteautoupdate;
	}

	public void setQtVezesclienteautoupdate(Integer qtVezesclienteautoupdate) {
		this.qtVezesclienteautoupdate = qtVezesclienteautoupdate;
	}

	@Column(name = "documento", length = 100)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "chave_verificacao_empresa", length = 512)
	public String getChaveVerificacaoEmpresa() {
		return this.chaveVerificacaoEmpresa;
	}

	public void setChaveVerificacaoEmpresa(String chaveVerificacaoEmpresa) {
		this.chaveVerificacaoEmpresa = chaveVerificacaoEmpresa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omLicenca")
	public Set<OmLicencaPt> getOmLicencaPts() {
		return this.omLicencaPts;
	}

	public void setOmLicencaPts(Set<OmLicencaPt> omLicencaPts) {
		this.omLicencaPts = omLicencaPts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omLicenca")
	public Set<OmLicmodrec> getOmLicmodrecs() {
		return this.omLicmodrecs;
	}

	public void setOmLicmodrecs(Set<OmLicmodrec> omLicmodrecs) {
		this.omLicmodrecs = omLicmodrecs;
	}

}
