package idw.model.pojos;

// Generated 05/01/2010 11:04:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OmProaltglo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_proaltglo")
public class OmProaltglo implements java.io.Serializable {

	private long idProalt;
	private OmProduto omProdutoByIdProdutoFilho;
	private OmProduto omProdutoByIdProdutoMae;
	private OmProduto omProdutoBySemiacabado;
	private BigDecimal qt;
	private Integer prioridade;
	
	public OmProaltglo() {
	}

	public OmProaltglo(long idProalt, OmProduto omProdutoByIdProdutoFilho,
			OmProduto omProdutoByIdProdutoMae, BigDecimal qt, Integer prioridade) {
		this.idProalt = idProalt;
		this.omProdutoByIdProdutoFilho = omProdutoByIdProdutoFilho;
		this.omProdutoByIdProdutoMae = omProdutoByIdProdutoMae;
		this.qt = qt;
		this.prioridade = prioridade;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_PROALTGLO_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_PROALTGLO_SEQ", sequenceName = "OM_PROALTGLO_SEQ")
	@Column(name = "id_proalt", unique = true, nullable = false)
	public long getIdProalt() {
		return this.idProalt;
	}

	public void setIdProalt(long idProalt) {
		this.idProalt = idProalt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produtoFilho", nullable = false)
	public OmProduto getOmProdutoByIdProdutoFilho() {
		return this.omProdutoByIdProdutoFilho;
	}

	public void setOmProdutoByIdProdutoFilho(OmProduto omProdutoByIdProdutoFilho) {
		this.omProdutoByIdProdutoFilho = omProdutoByIdProdutoFilho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produtoMae", nullable = false)
	public OmProduto getOmProdutoByIdProdutoMae() {
		return this.omProdutoByIdProdutoMae;
	}

	public void setOmProdutoByIdProdutoMae(OmProduto omProdutoByIdProdutoMae) {
		this.omProdutoByIdProdutoMae = omProdutoByIdProdutoMae;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUTOSEMIACABADO", nullable = true)
	public OmProduto getOmProdutoBySemiacabado() {
		return this.omProdutoBySemiacabado;
	}

	public void setOmProdutoBySemiacabado(OmProduto omProduto) {
		this.omProdutoBySemiacabado = omProduto;
	}

	@Column(name = "QT", precision = 14, scale = 4)
	public BigDecimal getQt() {
		return this.qt;
	}

	public void setQt(BigDecimal qt) {
		this.qt = qt;
	}

	@Column(name = "PRIORIDADE")
	public Integer getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(Integer prioridade) {
		this.prioridade = prioridade;
	}	
}
