package idw.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import idw.model.pojos.template.OmProturnoTemplate;
/**
 * OmProturno generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "OM_PROTURNO")
public class OmProturno extends OmProturnoTemplate implements java.io.Serializable {

	private Long idOmproturno;
	private OmProduto omProduto;
	private DwTurno dwTurno;
	private Integer tpRelacao;
	

	public OmProturno() {
	}

	public OmProturno(Long idOmproturno, OmProduto omProduto,
			DwTurno dwTurno) {
		this.idOmproturno = idOmproturno;
		this.omProduto = omProduto;
		this.dwTurno = dwTurno;
	}

	public OmProturno(Long idOmproturno, OmProduto omProduto,
			DwTurno dwTurno, Integer tpRelacao) {
		this.idOmproturno = idOmproturno;
		this.omProduto = omProduto;
		this.dwTurno = dwTurno;
		this.tpRelacao = tpRelacao;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_PROTURNO_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_PROTURNO_SEQ", sequenceName = "OM_PROTURNO_SEQ")
	@Column(name = "ID_OMPROTURNO", unique = true, nullable = false,  scale = 0)
	public Long getIdOmproturno() {
		return this.idOmproturno;
	}

	public void setIdOmproturno(Long idOmproturno) {
		this.idOmproturno = idOmproturno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUTO", nullable = false)
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TURNO", nullable = false)
	public DwTurno getDwTurno() {
		return this.dwTurno;
	}

	public void setDwTurno(DwTurno dwTurno) {
		this.dwTurno = dwTurno;
	}

	@Column(name = "TP_RELACAO", scale = 0)
	public Integer getTpRelacao() {
		return this.tpRelacao;
	}

	public void setTpRelacao(Integer tpRelacao) {
		this.tpRelacao = tpRelacao;
	}

}