package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 11/01/2010 15:35:09 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.OmProgrpTemplate;


/**
 * OmProgrp generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_progrp")
public class OmProgrp extends OmProgrpTemplate implements java.io.Serializable {

	private long idProgrp;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdProgrp;
	private Long revisao;
	private String dsProgrp;
	private Date dtRevisao;
	private Byte stAtivo;
	private Date dtStativo;
	private Set<OmProduto> omProdutos = new HashSet<OmProduto>(0);

	private Boolean isArivarexportacaobc;
	
	public OmProgrp() {
	}

	public OmProgrp(long idProgrp, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idProgrp = idProgrp;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public OmProgrp(long idProgrp, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdProgrp, Long revisao,
			String dsProgrp, Date dtRevisao, Byte stAtivo, Date dtStativo,
			Set<OmProduto> omProdutos) {
		this.idProgrp = idProgrp;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdProgrp = cdProgrp;
		this.revisao = revisao;
		this.dsProgrp = dsProgrp;
		this.dtRevisao = dtRevisao;
		this.stAtivo = stAtivo;
		this.dtStativo = dtStativo;
		this.omProdutos = omProdutos;
	}

	@Id	
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_PROGRP_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_PROGRP_SEQ", sequenceName = "OM_PROGRP_SEQ")
	@Column(name = "id_progrp", nullable = false)
	public long getIdProgrp() {
		return this.idProgrp;
	}

	public void setIdProgrp(long idProgrp) {
		this.idProgrp = idProgrp;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrstativo", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usrrevisao", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "cd_progrp", length = 30)
	public String getCdProgrp() {
		return this.cdProgrp;
	}

	public void setCdProgrp(String cdProgrp) {
		this.cdProgrp = cdProgrp;
	}

	@Override
	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_progrp", length = 40)
	public String getDsProgrp() {
		return this.dsProgrp;
	}

	public void setDsProgrp(String dsProgrp) {
		this.dsProgrp = dsProgrp;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omProgrp")
	public Set<OmProduto> getOmProdutos() {
		return this.omProdutos;
	}

	public void setOmProdutos(Set<OmProduto> omProdutos) {
		this.omProdutos = omProdutos;
	}

	@Column(name = "IS_ATIVAREXPORTACAOBC")
	public Boolean getIsArivarexportacaobc() {
		return isArivarexportacaobc;
	}

	public void setIsArivarexportacaobc(Boolean isArivarexportacaobc) {
		this.isArivarexportacaobc = isArivarexportacaobc;
	}

	
	
}
