package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

// Generated 05/01/2010 11:04:20 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.OmPrgTemplate;


/**
 * OmPrg generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_prg", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_pt", "cd_prg", "revisao" }))
public class OmPrg extends OmPrgTemplate implements java.io.Serializable {

	private long idPrg;
	private OmProduto omProduto;
	private OmPt omPt;
	private String cdPrg;
	private Long revisao;
	private String dsPrg;
	private Date dtRevisao;
	private Date dtStativo;
	private Byte stAtivo;
	private Boolean isConformeestruturaproduto;
	private Set<OmPrgpos> omPrgposes = new HashSet<OmPrgpos>(0);
	private Set<DwFolhaiac> dwFolhaiacs = new HashSet<DwFolhaiac>(0);
	private Set<OmMapa> omMapas = new HashSet<OmMapa>(0);

	public OmPrg() {
	}

	public OmPrg(long idPrg, OmPt omPt) {
		this.idPrg = idPrg;
		this.omPt = omPt;
	}

	public OmPrg(long idPrg, OmPt omPt, String cdPrg, Long revisao,
			String dsPrg, Date dtRevisao, Date dtStativo, Byte stAtivo,
			Set<OmPrgpos> omPrgposes, Set<OmMapa> omMapas) {
		this.idPrg = idPrg;
		this.omPt = omPt;
		this.cdPrg = cdPrg;
		this.revisao = revisao;
		this.dsPrg = dsPrg;
		this.dtRevisao = dtRevisao;
		this.dtStativo = dtStativo;
		this.stAtivo = stAtivo;
		this.omPrgposes = omPrgposes;
		this.omMapas = omMapas;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_PRG_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_PRG_SEQ", sequenceName = "OM_PRG_SEQ")
	@Column(name = "id_prg", unique = true, nullable = false)
	public long getIdPrg() {
		return this.idPrg;
	}

	public void setIdPrg(long idPrg) {
		this.idPrg = idPrg;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUTO")
	public OmProduto getOmProduto() {
		return this.omProduto;
	}

	public void setOmProduto(OmProduto omProduto) {
		this.omProduto = omProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pt", nullable = false)
	public OmPt getOmPt() {
		return this.omPt;
	}

	public void setOmPt(OmPt omPt) {
		this.omPt = omPt;
	}

	@Column(name = "cd_prg", length = 60)
	public String getCdPrg() {
		return this.cdPrg;
	}

	public void setCdPrg(String cdPrg) {
		this.cdPrg = cdPrg;
	}

	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_prg", length = 256)
	public String getDsPrg() {
		return this.dsPrg;
	}

	public void setDsPrg(String dsPrg) {
		this.dsPrg = dsPrg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omPrg")
	public Set<OmPrgpos> getOmPrgposes() {
		return this.omPrgposes;
	}

	public void setOmPrgposes(Set<OmPrgpos> omPrgposes) {
		this.omPrgposes = omPrgposes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omPrg")
	public Set<OmMapa> getOmMapas() {
		return this.omMapas;
	}

	public void setOmMapas(Set<OmMapa> omMapas) {
		this.omMapas = omMapas;
	}

	

	@Column(name = "IS_CONFORMEESTRUTURAPRODUTO", scale = 0)
	public Boolean getIsConformeestruturaproduto() {
		return isConformeestruturaproduto;
	}
	
	public void setIsConformeestruturaproduto(Boolean isConformeestruturaproduto) {
		this.isConformeestruturaproduto = isConformeestruturaproduto;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omPrg")
	public Set<DwFolhaiac> getDwFolhaiacs() {
		return this.dwFolhaiacs;
	}

	public void setDwFolhaiacs(Set<DwFolhaiac> dwFolhaiacs) {
		this.dwFolhaiacs = dwFolhaiacs;
	}

}
