package idw.model.pojos;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OmPtcp generated by hbm2java
 */
@Entity
@Table(name = "om_ptcp")
public class OmPtcp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idPtcp;
	private PpCp ppCp;
	private OmPt omPt;
	private Integer qtCiclos;
	private Integer qtCiclosregulagem;
	private Date dthrEntrada;
	private Date dthrSaida;

	public OmPtcp() {
	}

	public OmPtcp(Long idPtcp) {
		this.idPtcp = idPtcp;
	}

	public OmPtcp(Long idPtcp, PpCp ppCp, OmPt omPt, Integer qtCiclos) {
		this.idPtcp = idPtcp;
		this.ppCp = ppCp;
		this.omPt = omPt;
		this.qtCiclos = qtCiclos;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_PTCP_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_PTCP_SEQ", sequenceName = "OM_PTCP_SEQ")
	@Column(name = "id_ptcp", unique = true, nullable = false)
	public Long getIdPtcp() {
		return this.idPtcp;
	}

	public void setIdPtcp(Long idPtcp) {
		this.idPtcp = idPtcp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cp")
	public PpCp getPpCp() {
		return this.ppCp;
	}

	public void setPpCp(PpCp ppCp) {
		this.ppCp = ppCp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pt")
	public OmPt getOmPt() {
		return this.omPt;
	}

	public void setOmPt(OmPt omPt) {
		this.omPt = omPt;
	}

	@Column(name = "qt_ciclos")
	public Integer getQtCiclos() {
		return this.qtCiclos;
	}

	public void setQtCiclos(Integer qtCiclos) {
		this.qtCiclos = qtCiclos;
	}

	@Column(name = "qt_ciclosregulagem")
	public Integer getQtCiclosregulagem() {
		return this.qtCiclosregulagem;
	}

	public void setQtCiclosregulagem(Integer qtCiclos) {
		this.qtCiclosregulagem = qtCiclos;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_entrada", length = 23)
	public Date getDthrEntrada() {
		return this.dthrEntrada;
	}
	public void setDthrEntrada(Date valor) {
		this.dthrEntrada = valor;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_saida", length = 23)
	public Date getDthrSaida() {
		return this.dthrSaida;
	}
	public void setDthrSaida(Date valor) {
		this.dthrSaida = valor;
	}
}
