package idw.model.pojos;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OmTplicenca generated by hbm2java
 */
@Entity
@Table(name = "om_tplicenca")
public class OmTplicenca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idTplicenca;
	private OmTppt omTppt;
	private String dsLicenca;
	private String chaveVerificacao;
	private Set<OmLicenca> omLicencas = new HashSet<OmLicenca>(0);

	public OmTplicenca() {
	}

	public OmTplicenca(Long idTplicenca) {
		this.idTplicenca = idTplicenca;
	}

	public OmTplicenca(Long idTplicenca, OmTppt omTppt, String dsLicenca, String chaveVerificacao,
			Set<OmLicenca> omLicencas) {
		this.idTplicenca = idTplicenca;
		this.omTppt = omTppt;
		this.dsLicenca = dsLicenca;
		this.chaveVerificacao = chaveVerificacao;
		this.omLicencas = omLicencas;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_TP_LICENCA_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_TP_LICENCA_SEQ", sequenceName = "OM_TP_LICENCA_SEQ")
	@Column(name = "id_tplicenca", unique = true, nullable = false)
	public Long getIdTplicenca() {
		return this.idTplicenca;
	}

	public void setIdTplicenca(Long idTplicenca) {
		this.idTplicenca = idTplicenca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tppt")
	public OmTppt getOmTppt() {
		return this.omTppt;
	}

	public void setOmTppt(OmTppt omTppt) {
		this.omTppt = omTppt;
	}

	@Column(name = "ds_licenca", length = 100)
	public String getDsLicenca() {
		return this.dsLicenca;
	}

	public void setDsLicenca(String dsLicenca) {
		this.dsLicenca = dsLicenca;
	}

	@Column(name = "chave_verificacao", length = 512)
	public String getChaveVerificacao() {
		return this.chaveVerificacao;
	}

	public void setChaveVerificacao(String chaveVerificacao) {
		this.chaveVerificacao = chaveVerificacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omTplicenca")
	public Set<OmLicenca> getOmLicencas() {
		return this.omLicencas;
	}

	public void setOmLicencas(Set<OmLicenca> omLicencas) {
		this.omLicencas = omLicencas;
	}

}
