package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 05/01/2010 11:04:20 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.OmUsrgrpTemplate;


/**
 * OmUsrgrp generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_usrgrp")
public class OmUsrgrp extends OmUsrgrpTemplate implements java.io.Serializable {

	private long idUsrgrp;
	private String cdUsrgrp;
	private Long revisao;
	private String dsUsrGrp;
	private Date dtRevisao;
	private Date dtStativo;
	private Byte stAtivo;
	private Set<OmGrnts> omGrntses = new HashSet<OmGrnts>(0);
	private Set<OmUsr> omUsrs = new HashSet<OmUsr>(0);

	public OmUsrgrp() {
	}

	public OmUsrgrp(long idUsrgrp) {
		this.idUsrgrp = idUsrgrp;
	}

	public OmUsrgrp(long idUsrgrp, String cdUsrgrp, Long revisao,
			String dsUsrGrp, Date dtRevisao, Date dtStativo, Byte stAtivo,
			Set<OmGrnts> omGrntses, Set<OmUsr> omUsrs) {
		this.idUsrgrp = idUsrgrp;
		this.cdUsrgrp = cdUsrgrp;
		this.revisao = revisao;
		this.dsUsrGrp = dsUsrGrp;
		this.dtRevisao = dtRevisao;
		this.dtStativo = dtStativo;
		this.stAtivo = stAtivo;
		this.omGrntses = omGrntses;
		this.omUsrs = omUsrs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "OM_USRGRP_SEQ")
	@javax.persistence.SequenceGenerator(name = "OM_USRGRP_SEQ", sequenceName = "OM_USRGRP_SEQ")
	@Column(name = "id_usrgrp", nullable = false)
	public long getIdUsrgrp() {
		return this.idUsrgrp;
	}

	public void setIdUsrgrp(long idUsrgrp) {
		this.idUsrgrp = idUsrgrp;
	}

	@Column(name = "cd_usrgrp", length = 30)
	public String getCdUsrgrp() {
		return this.cdUsrgrp;
	}

	public void setCdUsrgrp(String cdUsrgrp) {
		this.cdUsrgrp = cdUsrgrp;
	}

	@Override
	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_usr_grp", length = 100)
	public String getDsUsrGrp() {
		return this.dsUsrGrp;
	}

	public void setDsUsrGrp(String dsUsrGrp) {
		this.dsUsrGrp = dsUsrGrp;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Override
	@Column(name = "st_ativo")
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "omUsrgrp")
	public Set<OmGrnts> getOmGrntses() {
		return this.omGrntses;
	}

	public void setOmGrntses(Set<OmGrnts> omGrntses) {
		this.omGrntses = omGrntses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omUsrgrp")
	public Set<OmUsr> getOmUsrs() {
		return this.omUsrs;
	}

	public void setOmUsrs(Set<OmUsr> omUsrs) {
		this.omUsrs = omUsrs;
	}




}
