package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 05/01/2010 11:04:20 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.OmWebcamTemplate;


/**
 * OmWebcam generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "om_webcam")
public class OmWebcam extends OmWebcamTemplate implements java.io.Serializable {

	private long idWebcam;
	private String url;
	private Date dtRevisao;
	private Date dtStativo;
	private Byte stAtivo;
	private String cdWebcam;
	private Long revisao;
	private String dsWebcam;
	private String dsCurta;
	private Set<OmObj> omObjs = new HashSet<OmObj>(0);

	public OmWebcam() {
	}

	public OmWebcam(long idWebcam, Byte stAtivo) {
		this.idWebcam = idWebcam;
		this.stAtivo = stAtivo;
	}

	public OmWebcam(long idWebcam, String url, Date dtRevisao, Date dtStativo,
			Byte stAtivo, String cdWebcam, Long revisao, String dsWebcam,
			String dsCurta, Set<OmObj> omObjs) {
		this.idWebcam = idWebcam;
		this.url = url;
		this.dtRevisao = dtRevisao;
		this.dtStativo = dtStativo;
		this.stAtivo = stAtivo;
		this.cdWebcam = cdWebcam;
		this.revisao = revisao;
		this.dsWebcam = dsWebcam;
		this.dsCurta = dsCurta;
		this.omObjs = omObjs;
	}

	@Id
	@Column(name = "id_webcam", unique = true, nullable = false)
	public long getIdWebcam() {
		return this.idWebcam;
	}

	public void setIdWebcam(long idWebcam) {
		this.idWebcam = idWebcam;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_revisao", length = 23)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_stativo", length = 23)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "st_ativo", nullable = false)
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "cd_webcam", length = 30)
	public String getCdWebcam() {
		return this.cdWebcam;
	}

	public void setCdWebcam(String cdWebcam) {
		this.cdWebcam = cdWebcam;
	}

	@Column(name = "revisao")
	public Long getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ds_webcam", length = 100)
	public String getDsWebcam() {
		return this.dsWebcam;
	}

	public void setDsWebcam(String dsWebcam) {
		this.dsWebcam = dsWebcam;
	}

	@Column(name = "ds_curta", length = 10)
	public String getDsCurta() {
		return this.dsCurta;
	}

	public void setDsCurta(String dsCurta) {
		this.dsCurta = dsCurta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "omWebcam")
	public Set<OmObj> getOmObjs() {
		return this.omObjs;
	}

	public void setOmObjs(Set<OmObj> omObjs) {
		this.omObjs = omObjs;
	}

}
