package idw.model.pojos;
// Generated 28/07/2011 10:26:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.PpClienteTemplate;

/**
 * PpCliente generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PP_CLIENTE")
public class PpCliente extends PpClienteTemplate implements java.io.Serializable {

	private Long idCliente;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdCliente;
	private Long revisao;
	private Date dtRevisao;
	private Date dtStativo;
	private Byte stAtivo;
	private String nmCliente;
	private Integer tpCliente;
	private String cnpjCpf;
	private String endereco;
	private String cidade;
	private String estado;
	private String pais;
	private String telefoneum;
	private String telefonedois;
	private String telefonetres;
	private String contato;
	private BigDecimal hrLeadtime;
	private String urlSite;
	private String depara;
	private Set<OmProduto> omProdutos = new HashSet<OmProduto>(0);
	private Set<PpCp> ppCps = new HashSet<PpCp>(0);
	private Set<OmContato> omContatos = new HashSet<OmContato>(0);
	private Set<PpNec> ppNecs = new HashSet<PpNec>(0);
	private Set<DwEstpro> dwEstpros = new HashSet<DwEstpro>(0);

	public PpCliente() {
	}

	public PpCliente(Long idCliente) {
		this.idCliente = idCliente;
	}


	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "PP_CLIENTE_SEQ")
	@javax.persistence.SequenceGenerator(name = "PP_CLIENTE_SEQ", sequenceName = "PP_CLIENTE_SEQ")
	@Column(name = "ID_CLIENTE", unique = true, nullable = false)
	public Long getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Long idCliente) {
		this.idCliente = idCliente;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRSTATIVO")
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRREVISAO")
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "CD_CLIENTE", length = 30)
	public String getCdCliente() {
		return this.cdCliente;
	}

	public void setCdCliente(String cdCliente) {
		this.cdCliente = cdCliente;
	}

	@Override
	@Column(name = "REVISAO", precision = 63, scale = 0)
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Override
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_REVISAO", length = 7)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_STATIVO", length = 7)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Override
	@Column(name = "ST_ATIVO", length = 1)
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "NM_CLIENTE", length = 256)
	public String getNmCliente() {
		return this.nmCliente;
	}

	public void setNmCliente(String nmCliente) {
		this.nmCliente = nmCliente;
	}

	@Column(name = "TP_CLIENTE")
	public Integer getTpCliente() {
		return this.tpCliente;
	}

	public void setTpCliente(Integer tpCliente) {
		this.tpCliente = tpCliente;
	}

	@Column(name = "CNPJ_CPF", length = 30)
	public String getCnpjCpf() {
		return this.cnpjCpf;
	}

	public void setCnpjCpf(String cnpjCpf) {
		this.cnpjCpf = cnpjCpf;
	}

	@Column(name = "ENDERECO", length = 256)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "CIDADE", length = 10)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "ESTADO", length = 4)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "PAIS", length = 10)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "TELEFONEUM", length = 20)
	public String getTelefoneum() {
		return this.telefoneum;
	}

	public void setTelefoneum(String telefoneum) {
		this.telefoneum = telefoneum;
	}

	@Column(name = "TELEFONEDOIS", length = 20)
	public String getTelefonedois() {
		return this.telefonedois;
	}

	public void setTelefonedois(String telefonedois) {
		this.telefonedois = telefonedois;
	}

	@Column(name = "TELEFONETRES", length = 20)
	public String getTelefonetres() {
		return this.telefonetres;
	}

	public void setTelefonetres(String telefonetres) {
		this.telefonetres = telefonetres;
	}

	@Column(name = "CONTATO", length = 100)
	public String getContato() {
		return this.contato;
	}

	public void setContato(String contato) {
		this.contato = contato;
	}

	@Column(name = "HR_LEADTIME", precision = 22, scale = 0)
	public BigDecimal getHrLeadtime() {
		return this.hrLeadtime;
	}

	public void setHrLeadtime(BigDecimal hrLeadtime) {
		this.hrLeadtime = hrLeadtime;
	}

	@Column(name = "URL_SITE")
	public String getUrlSite() {
		return this.urlSite;
	}

	public void setUrlSite(String urlSite) {
		this.urlSite = urlSite;
	}

	@Column(name = "DEPARA", length = 30)
	public String getDepara() {
		return this.depara;
	}

	public void setDepara(String depara) {
		this.depara = depara;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCliente")
	public Set<OmProduto> getOmProdutos() {
		return this.omProdutos;
	}

	public void setOmProdutos(Set<OmProduto> omProdutos) {
		this.omProdutos = omProdutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCliente")
	public Set<PpCp> getPpCps() {
		return this.ppCps;
	}

	public void setPpCps(Set<PpCp> ppCps) {
		this.ppCps = ppCps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCliente")
	public Set<OmContato> getOmContatos() {
		return this.omContatos;
	}

	public void setOmContatos(Set<OmContato> omContatos) {
		this.omContatos = omContatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCliente")
	public Set<PpNec> getPpNecs() {
		return this.ppNecs;
	}

	public void setPpNecs(Set<PpNec> ppNecs) {
		this.ppNecs = ppNecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCliente")
	public Set<DwEstpro> getDwEstpros() {
		return this.dwEstpros;
	}

	public void setDwEstpros(Set<DwEstpro> dwEstpros) {
		this.dwEstpros = dwEstpros;
	}


}
