package idw.model.pojos;
// Generated 16/12/2011 10:49:39 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PpCpHora generated by hbm2java
 */
@Entity
@Table(name = "PP_CP_HORA")
public class PpCpHora implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7601864592015753290L;
	private Long idCphora;
	private PpCpTurno ppCpTurno;
	private DwCalavu dwCalavu;
	private DwCalsem dwCalsem;
	private BigDecimal pcsProducaoprevista;

	public PpCpHora() {
	}

	public PpCpHora(Long idCphora, PpCpTurno ppCpTurno) {
		this.idCphora = idCphora;
		this.ppCpTurno = ppCpTurno;
	}

	public PpCpHora(Long idCphora, PpCpTurno ppCpTurno,
			DwCalavu dwCalavu, DwCalsem dwCalsem, BigDecimal pcsProducaoprevista) {
		this.idCphora = idCphora;
		this.ppCpTurno = ppCpTurno;
		this.dwCalavu = dwCalavu;
		this.dwCalsem = dwCalsem;
		this.pcsProducaoprevista = pcsProducaoprevista;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "PP_CP_HORA_SEQ")
	@javax.persistence.SequenceGenerator(name = "PP_CP_HORA_SEQ", sequenceName = "PP_CP_HORA_SEQ")
	@Column(name = "ID_CPHORA", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdCphora() {
		return this.idCphora;
	}

	public void setIdCphora(Long idCphora) {
		this.idCphora = idCphora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CP_TURNO", nullable = false)
	public PpCpTurno getPpCpTurno() {
		return this.ppCpTurno;
	}

	public void setPpCpTurno(PpCpTurno ppCpTurno) {
		this.ppCpTurno = ppCpTurno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CALAVU")
	public DwCalavu getDwCalavu() {
		return this.dwCalavu;
	}

	public void setDwCalavu(DwCalavu dwCalavu) {
		this.dwCalavu = dwCalavu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CALSEM")
	public DwCalsem getDwCalsem() {
		return this.dwCalsem;
	}

	public void setDwCalsem(DwCalsem dwCalsem) {
		this.dwCalsem = dwCalsem;
	}

	@Column(name = "PCS_PRODUCAOPREVISTA", precision = 63, scale = 0)
	public BigDecimal getPcsProducaoprevista() {
		return this.pcsProducaoprevista;
	}

	public void setPcsProducaoprevista(BigDecimal pcsProducaoprevista) {
		this.pcsProducaoprevista = pcsProducaoprevista;
	}

}
