package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

// Generated 28/07/2011 10:26:23 by Hibernate Tools 3.4.0.CR1

import idw.model.pojos.template.PpCpTemplate;

/**
 * PpCp generated by hbm2java
 */
@XmlRootElement
@SuppressWarnings("serial")
@Entity
@Table(name = "PP_CP")
public class PpCp extends PpCpTemplate implements java.io.Serializable {

	private Long idCp;
	private PpPlano ppPlano;
	private DwCal dwCal;
	private DwFolha dwFolha;
	private DwRota dwRota;
	private OmGt omGt;
	private PpCliente ppCliente;
	private OmUsr omUsrByIdUsrstativo;
	private OmPt omPt;
	private OmUsr omUsrByIdUsrrevisao;
	private DwEst dwEst;
	private String cdCp;
	private Long revisao;
	private Date dtRevisao;
	private Date dtStativo;
	private Byte stAtivo;
	private Integer prioridade;
	private Boolean isAntecipacao;
	private Integer stCp;
	private Date dthrInicio;
	private Date dthrFinal;
	private Date dthrInicioreal;
	private Date dthrFinalreal;
	private Integer tpCp;
	private Boolean isFinalserie;
	private Boolean isMassa;
	private Boolean isTryout;
	private Boolean isCm;
	private Boolean isBarrasete;
	private Boolean isFaltamp;
	private Boolean isApAberta;
	private Date dtCobertura;
	private PpNec ppNec;
	private Date dthrIsetup;
	private Date dthrFsetup;
	
	private String nrLoteMp;
	private String dtLoteMp;

	private Set<OmPtcp> omPtcps = new HashSet<OmPtcp>(0);
	private Set<PpCpentsai> ppCpentsais = new HashSet<PpCpentsai>(0);
	private Set<DwConsolid> dwConsolids = new HashSet<DwConsolid>(0);
	private Set<PpCpproduto> ppCpprodutos = new HashSet<PpCpproduto>(0);
	private Set<PpCpfaltamp> ppCpfaltamps = new HashSet<PpCpfaltamp>(0);
	private Set<PpCpPre> ppCpPresForIdCp = new HashSet<PpCpPre>(0);
	private Set<PpCpPre> ppCpPresForIdCppredecessora = new HashSet<PpCpPre>(0);
	private Set<PpCpneccron> ppCpneccrons = new HashSet<PpCpneccron>(0);
	private BigDecimal passo;
	private Set<DwRt> dwRts = new HashSet<DwRt>(0);
	private Set<PpCpnserie> ppCpnseries = new HashSet<PpCpnserie>(0);

	public PpCp() {
	}

	public PpCp(Long idCp, PpPlano ppPlano, DwCal dwCal, OmGt omGt, OmPt omPt) {
		this.idCp = idCp;
		this.ppPlano = ppPlano;
		this.dwCal = dwCal;
		this.omPt = omPt;
		this.omGt = omGt;
	}

	public PpCp(Long idCp, PpPlano ppPlano, DwCal dwCal, DwFolha dwFolha,
			PpCliente ppCliente, OmUsr omUsrByIdUsrstativo, OmPt omPt, OmGt omGt,
			OmUsr omUsrByIdUsrrevisao, DwEst dwEst, String cdCp, Long revisao,
			Date dtRevisao, Date dtStativo, Byte stAtivo, Integer prioridade,
			Boolean isAntecipacao, Integer stCp, Date dthrInicio,
			Date dthrFinal, Date dthrInicioreal, Date dthrFinalreal,
			Integer tpCp, Set<DwConsolid> dwConsolids,
			Set<PpCpproduto> ppCpprodutos, Set<DwRt> dwRts) {
		this.idCp = idCp;
		this.ppPlano = ppPlano;
		this.dwCal = dwCal;
		this.dwFolha = dwFolha;
		this.ppCliente = ppCliente;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omPt = omPt;
		this.omGt = omGt;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.dwEst = dwEst;
		this.cdCp = cdCp;
		this.revisao = revisao;
		this.dtRevisao = dtRevisao;
		this.dtStativo = dtStativo;
		this.stAtivo = stAtivo;
		this.prioridade = prioridade;
		this.isAntecipacao = isAntecipacao;
		this.stCp = stCp;
		this.dthrInicio = dthrInicio;
		this.dthrFinal = dthrFinal;
		this.dthrInicioreal = dthrInicioreal;
		this.dthrFinalreal = dthrFinalreal;
		this.tpCp = tpCp;
		this.dwConsolids = dwConsolids;
		this.ppCpprodutos = ppCpprodutos;
		this.dwRts = dwRts;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PP_CP_SEQ")
	@javax.persistence.SequenceGenerator(name = "PP_CP_SEQ", sequenceName = "PP_CP_SEQ")
	@Column(name = "ID_CP", unique = true, nullable = false, precision = 63, scale = 0)
	public Long getIdCp() {
		return this.idCp;
	}

	public void setIdCp(Long idCp) {
		this.idCp = idCp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PLANO")
	public PpPlano getPpPlano() {
		return this.ppPlano;
	}

	public void setPpPlano(PpPlano ppPlano) {
		this.ppPlano = ppPlano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CAL", nullable = true)
	public DwCal getDwCal() {
		return this.dwCal;
	}

	public void setDwCal(DwCal dwCal) {
		this.dwCal = dwCal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FOLHA")
	public DwFolha getDwFolha() {
		return this.dwFolha;
	}

	public void setDwFolha(DwFolha dwFolha) {
		this.dwFolha = dwFolha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENTE")
	public PpCliente getPpCliente() {
		return this.ppCliente;
	}

	public void setPpCliente(PpCliente ppCliente) {
		this.ppCliente = ppCliente;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRSTATIVO")
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	@Override
	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PT", nullable = true)
	public OmPt getOmPt() {
		return this.omPt;
	}

	public void setOmPt(OmPt omPt) {
		this.omPt = omPt;
	}

	@Override
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRREVISAO")
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	@Override
	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EST")
	public DwEst getDwEst() {
		return this.dwEst;
	}

	public void setDwEst(DwEst dwEst) {
		this.dwEst = dwEst;
	}

	@Column(name = "CD_CP", length = 60)
	public String getCdCp() {
		return this.cdCp;
	}

	public void setCdCp(String cdCp) {
		this.cdCp = cdCp;
	}

	@Override
	@Column(name = "REVISAO", precision = 63, scale = 0)
	public Long getRevisao() {
		return this.revisao;
	}

	@Override
	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Override
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_REVISAO", length = 7)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	@Override
	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Override
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_STATIVO", length = 7)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	@Override
	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Override
	@Column(name = "ST_ATIVO", length = 1)
	public Byte getStAtivo() {
		return this.stAtivo;
	}

	@Override
	public void setStAtivo(Byte stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "PRIORIDADE", precision = 22, scale = 0)
	public Integer getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(Integer prioridade) {
		this.prioridade = prioridade;
	}

	@Column(name = "IS_ANTECIPACAO", precision = 22, scale = 0)
	public Boolean getIsAntecipacao() {
		return this.isAntecipacao;
	}

	public void setIsAntecipacao(Boolean isAntecipacao) {
		this.isAntecipacao = isAntecipacao;
	}

	@Column(name = "ST_CP", precision = 22, scale = 0)
	public Integer getStCp() {
		return this.stCp;
	}

	public void setStCp(Integer stCp) {
		this.stCp = stCp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_INICIO")
	public Date getDthrInicio() {
		return this.dthrInicio;
	}

	public void setDthrInicio(Date dthrInicio) {
		this.dthrInicio = dthrInicio;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_ISETUP")
	public Date getDthrIsetup() {
		return this.dthrIsetup;
	}

	public void setDthrIsetup(Date valor) {
		this.dthrIsetup = valor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FSETUP")
	public Date getDthrFsetup() {
		return this.dthrFsetup;
	}

	public void setDthrFsetup(Date valor) {
		this.dthrFsetup = valor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FINAL")
	public Date getDthrFinal() {
		return this.dthrFinal;
	}

	public void setDthrFinal(Date dthrFinal) {
		this.dthrFinal = dthrFinal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_INICIOREAL")
	public Date getDthrInicioreal() {
		return this.dthrInicioreal;
	}

	public void setDthrInicioreal(Date dthrInicioreal) {
		this.dthrInicioreal = dthrInicioreal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FINALREAL")
	public Date getDthrFinalreal() {
		return this.dthrFinalreal;
	}

	public void setDthrFinalreal(Date dthrFinalreal) {
		this.dthrFinalreal = dthrFinalreal;
	}

	@Column(name = "TP_CP")
	public Integer getTpCp() {
		return this.tpCp;
	}

	public void setTpCp(Integer tpCp) {
		this.tpCp = tpCp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCp")
	public Set<DwRt> getDwRts() {
		return this.dwRts;
	}

	public void setDwRts(Set<DwRt> dwRts) {
		this.dwRts = dwRts;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCp")
	public Set<DwConsolid> getDwConsolids() {
		return this.dwConsolids;
	}

	public void setDwConsolids(Set<DwConsolid> dwConsolids) {
		this.dwConsolids = dwConsolids;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppCp")
	public Set<PpCpproduto> getPpCpprodutos() {
		return this.ppCpprodutos;
	}

	public void setPpCpprodutos(Set<PpCpproduto> ppCpprodutos) {
		this.ppCpprodutos = ppCpprodutos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppCp")
	public Set<PpCpfaltamp> getPpCpfaltamps() {
		return this.ppCpfaltamps;
	}

	public void setPpCpfaltamps(Set<PpCpfaltamp> ppCpfaltamp) {
		this.ppCpfaltamps = ppCpfaltamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ROTA")
	public DwRota getDwRota() {
		return this.dwRota;
	}

	public void setDwRota(DwRota dwRota) {
		this.dwRota = dwRota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GT")
	public OmGt getOmGt() {
		return this.omGt;
	}

	public void setOmGt(OmGt omGt) {
		this.omGt = omGt;
	}

	@Column(name = "IS_FINALSERIE", precision = 22, scale = 0)
	public Boolean getIsFinalserie() {
		return this.isFinalserie;
	}

	public void setIsFinalserie(Boolean isFinalserie) {
		this.isFinalserie = isFinalserie;
	}

	@Column(name = "IS_MASSA", precision = 22, scale = 0)
	public Boolean getIsMassa() {
		return this.isMassa;
	}

	public void setIsMassa(Boolean isMassa) {
		this.isMassa = isMassa;
	}

	@Column(name = "IS_TRYOUT", precision = 22, scale = 0)
	public Boolean getIsTryout() {
		return this.isTryout;
	}

	public void setIsTryout(Boolean isTryout) {
		this.isTryout = isTryout;
	}

	@Column(name = "IS_CM", precision = 22, scale = 0)
	public Boolean getIsCm() {
		return this.isCm;
	}

	public void setIsCm(Boolean isCm) {
		this.isCm = isCm;
	}

	@Column(name = "IS_BARRASETE", precision = 22, scale = 0)
	public Boolean getIsBarrasete() {
		return this.isBarrasete;
	}

	public void setIsBarrasete(Boolean isBarrasete) {
		this.isBarrasete = isBarrasete;
	}

	@Column(name = "IS_FALTAMP")
	public Boolean getIsFaltamp() {
		return this.isFaltamp;
	}

	public void setIsFaltamp(Boolean isFaltamp) {
		this.isFaltamp = isFaltamp;
	}

	@Column(name = "IS_AP_ABERTA")
	public Boolean getIsApAberta() {
		return isApAberta;
	}

	public void setIsApAberta(Boolean isApAberta) {
		this.isApAberta = isApAberta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCpByIdCp")
	public Set<PpCpPre> getPpCpPresForIdCp() {
		return this.ppCpPresForIdCp;
	}

	public void setPpCpPresForIdCp(Set<PpCpPre> ppCpPresForIdCp) {
		this.ppCpPresForIdCp = ppCpPresForIdCp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCpByIdCppredecessora")
	public Set<PpCpPre> getPpCpPresForIdCppredecessora() {
		return this.ppCpPresForIdCppredecessora;
	}

	public void setPpCpPresForIdCppredecessora(
			Set<PpCpPre> ppCpPresForIdCppredecessora) {
		this.ppCpPresForIdCppredecessora = ppCpPresForIdCppredecessora;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppCp")
	public Set<PpCpneccron> getPpCpneccrons() {
		return this.ppCpneccrons;
	}

	public void setPpCpneccrons(Set<PpCpneccron> ppCpneccrons) {
		this.ppCpneccrons = ppCpneccrons;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_COBERTURA", length = 7)
	public Date getDtCobertura() {
		return this.dtCobertura;
	}

	public void setDtCobertura(Date dtCobertura) {
		this.dtCobertura = dtCobertura;
	}

	public void setPasso(BigDecimal passo) {
		this.passo = passo;
	}

	@Column(name = "PASSO", precision = 22, scale = 0)
	public BigDecimal getPasso() {
		return this.passo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nec")
	public PpNec getPpNec() {
		return this.ppNec;
	}

	public void setPpNec(PpNec ppNec) {
		this.ppNec = ppNec;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppCp")
	public Set<PpCpnserie> getPpCpnseries() {
		return this.ppCpnseries;
	}

	public void setPpCpnseries(Set<PpCpnserie> ppCpnseries) {
		this.ppCpnseries = ppCpnseries;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCp")
	public Set<OmPtcp> getOmPtcps() {
		return this.omPtcps;
	}

	public void setOmPtcps(Set<OmPtcp> omPtcps) {
		this.omPtcps = omPtcps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppCp")
	public Set<PpCpentsai> getPpCpentsais() {
		return this.ppCpentsais;
	}

	public void setPpCpentsais(Set<PpCpentsai> ppCpentsais) {
		this.ppCpentsais = ppCpentsais;
	}

	@Column(name = "NR_LOTE_MP", length = 60)
	public String getNrLoteMp() {
		return nrLoteMp;
	}

	public void setNrLoteMp(String nrLoteMp) {
		this.nrLoteMp = nrLoteMp;
	}

	@Column(name = "DT_LOTE_MP", length = 60)
	public String getDtLoteMp() {
		return dtLoteMp;
	}

	public void setDtLoteMp(String dtLoteMp) {
		this.dtLoteMp = dtLoteMp;
	}
	
}
