package idw.model.pojos;
// Generated 16/12/2011 10:49:39 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import idw.model.pojos.template.PpCpDataTemplate;

/**
 * PpCpData generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PP_CP_DATA")
public class PpCpData extends PpCpDataTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private Long idCpData;
	private PpCpproduto ppCpproduto;
	private Date dtPlanejada;
	private BigDecimal pcsProducaoprevista;
	private Set<PpCpTurno> ppCpTurnos = new HashSet<PpCpTurno>(0);

	public PpCpData() {
	}

	public PpCpData(Long idCpData, PpCpproduto ppCpproduto) {
		this.idCpData = idCpData;
		this.ppCpproduto = ppCpproduto;
	}

	public PpCpData(Long idCpData, PpCpproduto ppCpproduto,
			Date dtPlanejada, BigDecimal pcsProducaoprevista,
			Set<PpCpTurno> ppCpTurnos) {
		this.idCpData = idCpData;
		this.ppCpproduto = ppCpproduto;
		this.dtPlanejada = dtPlanejada;
		this.pcsProducaoprevista = pcsProducaoprevista;
		this.ppCpTurnos = ppCpTurnos;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "PP_CP_DATA_SEQ")
	@javax.persistence.SequenceGenerator(name = "PP_CP_DATA_SEQ", sequenceName = "PP_CP_DATA_SEQ")
	@Column(name = "ID_CP_DATA", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdCpData() {
		return this.idCpData;
	}

	public void setIdCpData(Long idCpData) {
		this.idCpData = idCpData;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CPPRODUTO", nullable = false)
	public PpCpproduto getPpCpproduto() {
		return this.ppCpproduto;
	}

	public void setPpCpproduto(PpCpproduto ppCpproduto) {
		this.ppCpproduto = ppCpproduto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_PLANEJADA", length = 7)
	public Date getDtPlanejada() {
		return this.dtPlanejada;
	}

	public void setDtPlanejada(Date dtPlanejada) {
		this.dtPlanejada = dtPlanejada;
	}

	@Column(name = "PCS_PRODUCAOPREVISTA", precision = 63, scale = 0)
	public BigDecimal getPcsProducaoprevista() {
		return this.pcsProducaoprevista;
	}

	public void setPcsProducaoprevista(BigDecimal pcsProducaoprevista) {
		this.pcsProducaoprevista = pcsProducaoprevista;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppCpData")
	public Set<PpCpTurno> getPpCpTurnos() {
		return this.ppCpTurnos;
	}

	public void setPpCpTurnos(Set<PpCpTurno> ppCpTurnos) {
		this.ppCpTurnos = ppCpTurnos;
	}

}
