package idw.model.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 18/08/2011 14:08:40 by Hibernate Tools 3.4.0.CR1

import idw.model.pojos.template.PpIndispTemplate;

/**
 * PpIndisp generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PP_INDISP")
public class PpIndisp extends PpIndispTemplate implements java.io.Serializable {

	private Long idIndisp;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdIndisp;
	private Long revisao;
	private String dsIndisp;
	private Date dtRevisao;
	private Date dtStativo;
	private Integer stAtivo;
	private Integer stIndisp;
	private Set<PpIndispRappt> ppIndispRappts = new HashSet<PpIndispRappt>(0);

	public PpIndisp() {
	}

	public PpIndisp(Long idIndisp, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao) {
		this.idIndisp = idIndisp;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	public PpIndisp(Long idIndisp, OmUsr omUsrByIdUsrstativo,
			OmUsr omUsrByIdUsrrevisao, String cdIndisp, Long revisao,
			String dsIndisp, Date dtRevisao, Date dtStativo, Integer stAtivo,
			Integer stIndisp, Set<PpIndispRappt> ppIndispRappts) {
		this.idIndisp = idIndisp;
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
		this.cdIndisp = cdIndisp;
		this.revisao = revisao;
		this.dsIndisp = dsIndisp;
		this.dtRevisao = dtRevisao;
		this.dtStativo = dtStativo;
		this.stAtivo = stAtivo;
		this.stIndisp = stIndisp;
		this.ppIndispRappts = ppIndispRappts;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "PP_INDISP_SEQ")
	@javax.persistence.SequenceGenerator(name = "PP_INDISP_SEQ", sequenceName = "PP_INDISP_SEQ")
	@Column(name = "ID_INDISP", unique = true, nullable = false, precision = 63, scale = 0)
	public Long getIdIndisp() {
		return this.idIndisp;
	}

	public void setIdIndisp(Long idIndisp) {
		this.idIndisp = idIndisp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRSTATIVO", nullable = false)
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRREVISAO", nullable = false)
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "CD_INDISP", length = 30)
	public String getCdIndisp() {
		return this.cdIndisp;
	}

	public void setCdIndisp(String cdIndisp) {
		this.cdIndisp = cdIndisp;
	}

	@Column(name = "REVISAO", precision = 63, scale = 0)
	public Long getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Long revisao) {
		this.revisao = revisao;
	}

	@Column(name = "DS_INDISP", length = 256)
	public String getDsIndisp() {
		return this.dsIndisp;
	}

	public void setDsIndisp(String dsIndisp) {
		this.dsIndisp = dsIndisp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_REVISAO", length = 7)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_STATIVO", length = 7)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "ST_ATIVO", length = 1)
	public Integer getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Integer stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "ST_INDISP", length = 1)
	public Integer getStIndisp() {
		return this.stIndisp;
	}

	public void setStIndisp(Integer stIndisp) {
		this.stIndisp = stIndisp;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppIndisp")
	public Set<PpIndispRappt> getPpIndispRappts() {
		return this.ppIndispRappts;
	}

	public void setPpIndispRappts(Set<PpIndispRappt> ppIndispRappts) {
		this.ppIndispRappts = ppIndispRappts;
	}

}
