package idw.model.pojos;
// Generated 28/07/2011 10:26:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.PpNecimpurlTemplate;

/**
 * PpNecimpurl generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PP_NECIMPURL")
public class PpNecimpurl extends PpNecimpurlTemplate implements java.io.Serializable {

	private Long idNecimpurl;
	private PpNecimp ppNecimp;
	private String urlFonte;
	private String mascara;
	private String aba;
	private Set<PpNecimpurllog> ppNecimpurllogs = new HashSet<PpNecimpurllog>(0);

	public PpNecimpurl() {
	}

	public PpNecimpurl(Long idNecimpurl, PpNecimp ppNecimp) {
		this.idNecimpurl = idNecimpurl;
		this.ppNecimp = ppNecimp;
	}

	public PpNecimpurl(Long idNecimpurl, PpNecimp ppNecimp, String urlFonte,
			Set<PpNecimpurllog> ppNecimpurllogs) {
		this.idNecimpurl = idNecimpurl;
		this.ppNecimp = ppNecimp;
		this.urlFonte = urlFonte;
		this.ppNecimpurllogs = ppNecimpurllogs;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "PP_NECIMPURL_SEQ")
	@javax.persistence.SequenceGenerator(name = "PP_NECIMPURL_SEQ", sequenceName = "PP_NECIMPURL_SEQ")
	@Column(name = "ID_NECIMPURL", unique = true, nullable = false, precision = 63, scale = 0)
	public Long getIdNecimpurl() {
		return this.idNecimpurl;
	}

	public void setIdNecimpurl(Long idNecimpurl) {
		this.idNecimpurl = idNecimpurl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_NECIMP", nullable = false)
	public PpNecimp getPpNecimp() {
		return this.ppNecimp;
	}

	public void setPpNecimp(PpNecimp ppNecimp) {
		this.ppNecimp = ppNecimp;
	}

	@Column(name = "URL_FONTE")
	public String getUrlFonte() {
		return this.urlFonte;
	}

	public void setUrlFonte(String urlFonte) {
		this.urlFonte = urlFonte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppNecimpurl")
	public Set<PpNecimpurllog> getPpNecimpurllogs() {
		return this.ppNecimpurllogs;
	}

	public void setPpNecimpurllogs(Set<PpNecimpurllog> ppNecimpurllogs) {
		this.ppNecimpurllogs = ppNecimpurllogs;
	}
	@Column(name = "MASCARA", length = 30)
	public String getMascara() {
		return this.mascara;
	}

	public void setMascara(String mascara) {
		this.mascara = mascara;
	}

	@Column(name = "ABA", length = 30)
	public String getAba() {
		return this.aba;
	}

	public void setAba(String aba) {
		this.aba = aba;
	}
}
