package idw.model.pojos;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import idw.model.pojos.template.PpPlanoTemplate;

/**
 * PpPlano generated by hbm2java
 */
@XmlRootElement
@SuppressWarnings("serial")
@Entity
@Table(name = "PP_PLANO")
public class PpPlano extends PpPlanoTemplate implements java.io.Serializable {

	private Long idPlano;
	private DwCal dwCal;
	private PpTpplano ppTpplano;
	private OmUsr omUsrByIdUsrstativo;
	private OmUsr omUsrByIdUsrrevisao;
	private String cdPlano;
	private Integer revisao;
	private Boolean isModelo;
	private Date dtRevisao;
	private Date dtStativo;
	private Integer stAtivo;
	private Integer stPlano;
	private String dsPlano;
	private Date dthrPrevisaoinicio;
	private BigDecimal indOee;
	private Boolean isConsiderarrap;
	private Boolean isConsiderarmp;
	private Boolean isConsiderarest;
	private Boolean isConsiderarcal;
	private Boolean isConsiderarindisp;
	private Boolean isConsiderarmo;
	private Boolean isDeterminadocal;
	private Boolean isConsideraroeefinalserie;
	private Boolean isConsiderarprodutoturno;
	private Boolean isConsiderarcm;
	private Boolean isSimular;
	private Set<PpPlancol> ppPlancols = new HashSet<PpPlancol>(0);
	private Set<PpPlanptgt> ppPlanptgts = new HashSet<PpPlanptgt>(0);
	private Set<PpCp> ppCps = new HashSet<PpCp>(0);
	private Set<PpPlanec> ppPlanecs = new HashSet<PpPlanec>(0);
	private Set<PpPlaneccron> ppPlaneccrons = new HashSet<PpPlaneccron>(0);

	public PpPlano() {
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "PP_PLANO_SEQ")
	@javax.persistence.SequenceGenerator(name = "PP_PLANO_SEQ", sequenceName = "PP_PLANO_SEQ")
	@Column(name = "ID_PLANO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdPlano() {
		return this.idPlano;
	}

	public void setIdPlano(Long idPlano) {
		this.idPlano = idPlano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CAL")
	public DwCal getDwCal() {
		return this.dwCal;
	}

	public void setDwCal(DwCal dwCal) {
		this.dwCal = dwCal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TPPLANO", nullable = false)
	public PpTpplano getPpTpplano() {
		return this.ppTpplano;
	}

	public void setPpTpplano(PpTpplano ppTpplano) {
		this.ppTpplano = ppTpplano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRSTATIVO")
	public OmUsr getOmUsrByIdUsrstativo() {
		return this.omUsrByIdUsrstativo;
	}

	public void setOmUsrByIdUsrstativo(OmUsr omUsrByIdUsrstativo) {
		this.omUsrByIdUsrstativo = omUsrByIdUsrstativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRREVISAO")
	public OmUsr getOmUsrByIdUsrrevisao() {
		return this.omUsrByIdUsrrevisao;
	}

	public void setOmUsrByIdUsrrevisao(OmUsr omUsrByIdUsrrevisao) {
		this.omUsrByIdUsrrevisao = omUsrByIdUsrrevisao;
	}

	@Column(name = "CD_PLANO", length = 30)
	public String getCdPlano() {
		return this.cdPlano;
	}

	public void setCdPlano(String cdPlano) {
		this.cdPlano = cdPlano;
	}

	@Column(name = "REVISAO")
	public Integer getRevisao() {
		return this.revisao;
	}

	public void setRevisao(Integer revisao) {
		this.revisao = revisao;
	}

	@Column(name = "IS_MODELO")
	public Boolean getIsModelo() {
		return this.isModelo;
	}

	public void setIsModelo(Boolean isModelo) {
		this.isModelo = isModelo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_REVISAO", length = 7)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_STATIVO", length = 7)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "ST_ATIVO")
	public Integer getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Integer stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "ST_PLANO")
	public Integer getStPlano() {
		return this.stPlano;
	}

	public void setStPlano(Integer stPlano) {
		this.stPlano = stPlano;
	}

	@Column(name = "DS_PLANO", length = 100)
	public String getDsPlano() {
		return this.dsPlano;
	}

	public void setDsPlano(String dsPlano) {
		this.dsPlano = dsPlano;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHR_PREVISAOINICIO", length = 7)
	public Date getDthrPrevisaoinicio() {
		return this.dthrPrevisaoinicio;
	}

	public void setDthrPrevisaoinicio(Date dthrPrevisaoinicio) {
		this.dthrPrevisaoinicio = dthrPrevisaoinicio;
	}

	@Column(name = "IND_OEE", precision = 6, scale = 3)
	public BigDecimal getIndOee() {
		return this.indOee;
	}

	public void setIndOee(BigDecimal indOee) {
		this.indOee = indOee;
	}

	@Column(name = "IS_CONSIDERARRAP")
	public Boolean getIsConsiderarrap() {
		return this.isConsiderarrap;
	}

	public void setIsConsiderarrap(Boolean isConsiderarrap) {
		this.isConsiderarrap = isConsiderarrap;
	}

	@Column(name = "IS_CONSIDERARMP")
	public Boolean getIsConsiderarmp() {
		return this.isConsiderarmp;
	}

	public void setIsConsiderarmp(Boolean isConsiderarmp) {
		this.isConsiderarmp = isConsiderarmp;
	}

	@Column(name = "IS_CONSIDERAREST")
	public Boolean getIsConsiderarest() {
		return this.isConsiderarest;
	}

	public void setIsConsiderarest(Boolean isConsiderarest) {
		this.isConsiderarest = isConsiderarest;
	}

	@Column(name = "IS_CONSIDERARCAL")
	public Boolean getIsConsiderarcal() {
		return this.isConsiderarcal;
	}

	public void setIsConsiderarcal(Boolean isConsiderarcal) {
		this.isConsiderarcal = isConsiderarcal;
	}

	@Column(name = "IS_CONSIDERARINDISP")
	public Boolean getIsConsiderarindisp() {
		return this.isConsiderarindisp;
	}

	public void setIsConsiderarindisp(Boolean isConsiderarindisp) {
		this.isConsiderarindisp = isConsiderarindisp;
	}

	@Column(name = "IS_CONSIDERARMO")
	public Boolean getIsConsiderarmo() {
		return this.isConsiderarmo;
	}

	public void setIsConsiderarmo(Boolean isConsiderarmo) {
		this.isConsiderarmo = isConsiderarmo;
	}

	@Column(name = "IS_DETERMINADOCAL")
	public Boolean getIsDeterminadocal() {
		return this.isDeterminadocal;
	}

	public void setIsDeterminadocal(Boolean isDeterminadocal) {
		this.isDeterminadocal = isDeterminadocal;
	}

	@Column(name = "IS_CONSIDERAROEEFINALSERIE")
	public Boolean getIsConsideraroeefinalserie() {
		return this.isConsideraroeefinalserie;
	}

	public void setIsConsideraroeefinalserie(
			Boolean isConsideraroeefinalserie) {
		this.isConsideraroeefinalserie = isConsideraroeefinalserie;
	}

	@Column(name = "IS_CONSIDERARPRODUTOTURNO")
	public Boolean getIsConsiderarprodutoturno() {
		return this.isConsiderarprodutoturno;
	}

	public void setIsConsiderarprodutoturno(Boolean isConsiderarprodutoturno) {
		this.isConsiderarprodutoturno = isConsiderarprodutoturno;
	}

	@Column(name = "IS_CONSIDERARCM")
	public Boolean getIsConsiderarcm() {
		return this.isConsiderarcm;
	}

	public void setIsConsiderarcm(Boolean isConsiderarcm) {
		this.isConsiderarcm = isConsiderarcm;
	}
	@Column(name = "IS_SIMULAR")
	public Boolean getIsSimular() {
		return this.isSimular;
	}

	public void setIsSimular(Boolean isSimular) {
		this.isSimular = isSimular;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppPlano")
	public Set<PpPlancol> getPpPlancols() {
		return this.ppPlancols;
	}

	public void setPpPlancols(Set<PpPlancol> ppPlancols) {
		this.ppPlancols = ppPlancols;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppPlano")
	public Set<PpPlanptgt> getPpPlanptgts() {
		return this.ppPlanptgts;
	}

	public void setPpPlanptgts(Set<PpPlanptgt> ppPlanptgts) {
		this.ppPlanptgts = ppPlanptgts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppPlano")
	public Set<PpCp> getPpCps() {
		return this.ppCps;
	}

	public void setPpCps(Set<PpCp> ppCps) {
		this.ppCps = ppCps;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ppPlano")
	public Set<PpPlanec> getPpPlanecs() {
		return this.ppPlanecs;
	}

	public void setPpPlanecs(Set<PpPlanec> ppPlanecs) {
		this.ppPlanecs = ppPlanecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppPlano")
	public Set<PpPlaneccron> getPpPlaneccrons() {
		return this.ppPlaneccrons;
	}

	public void setPpPlaneccrons(Set<PpPlaneccron> ppPlaneccrons) {
		this.ppPlaneccrons = ppPlaneccrons;
	}
}
