package idw.model.pojos;
// default package
// Generated 09/09/2011 08:51:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.PpTpplanoTemplate;

/**
 * PpTpplano generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PP_TPPLANO")
public class PpTpplano extends PpTpplanoTemplate implements java.io.Serializable {

	private Long idTpplano;
	private String dsTpplano;
	private Integer tpAlgoritmo;
	private BigDecimal indOee;
	private Boolean isConsiderarrap;
	private Boolean isConsiderarmp;
	private Boolean isConsiderarest;
	private Boolean isConsiderarcal;
	private Boolean isConsiderarindisp;
	private Boolean isConsiderarmo;
	private Boolean isDeterminadocal;
	private Boolean isConsideraroeefinalserie;
	private Boolean isConsiderarprodutoturno;
	private Boolean isConsiderarcm;
	private Set<PpPlano> ppPlanos = new HashSet<PpPlano>(0);

	public PpTpplano() {
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "PP_TPPLANO_SEQ")
	@javax.persistence.SequenceGenerator(name = "PP_TPPLANO_SEQ", sequenceName = "PP_TPPLANO_SEQ")
	@Column(name = "ID_TPPLANO", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdTpplano() {
		return this.idTpplano;
	}

	public void setIdTpplano(Long idTpplano) {
		this.idTpplano = idTpplano;
	}

	@Column(name = "DS_TPPLANO", length = 100)
	public String getDsTpplano() {
		return this.dsTpplano;
	}

	public void setDsTpplano(String dsTpplano) {
		this.dsTpplano = dsTpplano;
	}

	@Column(name = "TP_ALGORITMO")
	public Integer getTpAlgoritmo() {
		return this.tpAlgoritmo;
	}

	public void setTpAlgoritmo(Integer tpAlgoritmo) {
		this.tpAlgoritmo = tpAlgoritmo;
	}

	@Column(name = "IND_OEE")
	public BigDecimal getIndOee() {
		return this.indOee;
	}

	public void setIndOee(BigDecimal indOee) {
		this.indOee = indOee;
	}

	@Column(name = "IS_CONSIDERARRAP", precision = 22, scale = 0)
	public Boolean getIsConsiderarrap() {
		return this.isConsiderarrap;
	}

	public void setIsConsiderarrap(Boolean isConsiderarrap) {
		this.isConsiderarrap = isConsiderarrap;
	}

	@Column(name = "IS_CONSIDERARMP", precision = 22, scale = 0)
	public Boolean getIsConsiderarmp() {
		return this.isConsiderarmp;
	}

	public void setIsConsiderarmp(Boolean isConsiderarmp) {
		this.isConsiderarmp = isConsiderarmp;
	}

	@Column(name = "IS_CONSIDERAREST", precision = 22, scale = 0)
	public Boolean getIsConsiderarest() {
		return this.isConsiderarest;
	}

	public void setIsConsiderarest(Boolean isConsiderarest) {
		this.isConsiderarest = isConsiderarest;
	}

	@Column(name = "IS_CONSIDERARCAL", precision = 22, scale = 0)
	public Boolean getIsConsiderarcal() {
		return this.isConsiderarcal;
	}

	public void setIsConsiderarcal(Boolean isConsiderarcal) {
		this.isConsiderarcal = isConsiderarcal;
	}

	@Column(name = "IS_CONSIDERARINDISP", precision = 22, scale = 0)
	public Boolean getIsConsiderarindisp() {
		return this.isConsiderarindisp;
	}

	public void setIsConsiderarindisp(Boolean isConsiderarindisp) {
		this.isConsiderarindisp = isConsiderarindisp;
	}

	@Column(name = "IS_CONSIDERARMO", precision = 22, scale = 0)
	public Boolean getIsConsiderarmo() {
		return this.isConsiderarmo;
	}

	public void setIsConsiderarmo(Boolean isConsiderarmo) {
		this.isConsiderarmo = isConsiderarmo;
	}

	@Column(name = "IS_DETERMINADOCAL", precision = 22, scale = 0)
	public Boolean getIsDeterminadocal() {
		return this.isDeterminadocal;
	}

	public void setIsDeterminadocal(Boolean isDeterminadocal) {
		this.isDeterminadocal = isDeterminadocal;
	}

	@Column(name = "IS_CONSIDERAROEEFINALSERIE", precision = 22, scale = 0)
	public Boolean getIsConsideraroeefinalserie() {
		return this.isConsideraroeefinalserie;
	}

	public void setIsConsideraroeefinalserie(
			Boolean isConsideraroeefinalserie) {
		this.isConsideraroeefinalserie = isConsideraroeefinalserie;
	}

	@Column(name = "IS_CONSIDERARPRODUTOTURNO", precision = 22, scale = 0)
	public Boolean getIsConsiderarprodutoturno() {
		return this.isConsiderarprodutoturno;
	}

	public void setIsConsiderarprodutoturno(Boolean isConsiderarprodutoturno) {
		this.isConsiderarprodutoturno = isConsiderarprodutoturno;
	}

	@Column(name = "IS_CONSIDERARCM", precision = 22, scale = 0)
	public Boolean getIsConsiderarcm() {
		return this.isConsiderarcm;
	}

	public void setIsConsiderarcm(Boolean isConsiderarcm) {
		this.isConsiderarcm = isConsiderarcm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppTpplano")
	public Set<PpPlano> getPpPlanos() {
		return this.ppPlanos;
	}

	public void setPpPlanos(Set<PpPlano> ppPlanos) {
		this.ppPlanos = ppPlanos;
	}

}
