package idw.model.pojos;
// Generated 15/05/2018 16:00:51 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import idw.model.pojos.template.SpCausaefeitoTemplate;

/**
 * SpCausaefeito generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SP_CAUSAEFEITO")
public class SpCausaefeito extends SpCausaefeitoTemplate implements java.io.Serializable {

	private BigDecimal idCausaefeito;
	private SpCausaefeito spCausaefeito;
	private SpProblema spProblema;
	private SpCatcausa spCatcausa;
	private SpCausa spCausa;
	private Set<SpCausaefeito> spCausaefeitos = new HashSet<SpCausaefeito>(0);

	public SpCausaefeito() {
	}

	public SpCausaefeito(BigDecimal idCausaefeito, SpProblema spProblema,
			SpCatcausa spCatcausa, SpCausa spCausa) {
		this.idCausaefeito = idCausaefeito;
		this.spProblema = spProblema;
		this.spCatcausa = spCatcausa;
		this.spCausa = spCausa;
	}

	public SpCausaefeito(BigDecimal idCausaefeito, SpCausaefeito spCausaefeito,
			SpProblema spProblema, SpCatcausa spCatcausa, SpCausa spCausa,
			Set<SpCausaefeito> spCausaefeitos) {
		this.idCausaefeito = idCausaefeito;
		this.spCausaefeito = spCausaefeito;
		this.spProblema = spProblema;
		this.spCatcausa = spCatcausa;
		this.spCausa = spCausa;
		this.spCausaefeitos = spCausaefeitos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_CAUSAEFEITO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCausaefeito() {
		return this.idCausaefeito;
	}

	public void setIdCausaefeito(BigDecimal idCausaefeito) {
		this.idCausaefeito = idCausaefeito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CAUSAEFEITOPAI")
	public SpCausaefeito getSpCausaefeito() {
		return this.spCausaefeito;
	}

	public void setSpCausaefeito(SpCausaefeito spCausaefeito) {
		this.spCausaefeito = spCausaefeito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROBLEMA", nullable = false)
	public SpProblema getSpProblema() {
		return this.spProblema;
	}

	public void setSpProblema(SpProblema spProblema) {
		this.spProblema = spProblema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CATCAUSA", nullable = false)
	public SpCatcausa getSpCatcausa() {
		return this.spCatcausa;
	}

	public void setSpCatcausa(SpCatcausa spCatcausa) {
		this.spCatcausa = spCatcausa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CAUSA", nullable = false)
	public SpCausa getSpCausa() {
		return this.spCausa;
	}

	public void setSpCausa(SpCausa spCausa) {
		this.spCausa = spCausa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spCausaefeitos")
	public Set<SpCausaefeito> getSpCausaefeitos() {
		return this.spCausaefeitos;
	}

	public void setSpCausaefeitos(Set<SpCausaefeito> spCausaefeitos) {
		this.spCausaefeitos = spCausaefeitos;
	}

}
