package idw.model.pojos;
// Generated 15/05/2018 16:00:51 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SpMain generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SP_MAIN")
public class SpMain implements java.io.Serializable {

	private BigDecimal idSp;
	private OmUsr omUsr;
	private String cdSp;
	private String dsSp;
	private String cdProduto;
	private BigDecimal stAtivo;
	private BigDecimal revisao;
	private BigDecimal idUsrativo;
	private BigDecimal idUsrrevisao;
	private Date dtIsp;
	private Date dtFsp;
	private Date dtStativo;
	private Date dtRevisao;
	private Set<SpProblema> spProblemas = new HashSet<SpProblema>(0);

	private BigDecimal cachep3CiclosbarraIdgt;
	private BigDecimal cachep3ParadaspizzaIdgt;
	private BigDecimal cachep3DefeitosbarraIdgt;
	private String cachep3ParadasbarraCdarea;
	private Date cachep7ResultDti;
	private Date cachep7ResultDtf;

	
	
	
	public SpMain() {
	}

	public SpMain(BigDecimal idSp, OmUsr omUsr, String cdProduto) {
		this.idSp = idSp;
		this.omUsr = omUsr;
		this.cdProduto = cdProduto;
	}

	public SpMain(BigDecimal idSp, OmUsr omUsr, String cdSp, String dsSp,
			String cdProduto, BigDecimal stAtivo, BigDecimal revisao,
			BigDecimal idUsrativo, BigDecimal idUsrrevisao, Date dtIsp,
			Date dtFsp, Date dtStativo, Date dtRevisao,
			Set<SpProblema> spProblemas) {
		this.idSp = idSp;
		this.omUsr = omUsr;
		this.cdSp = cdSp;
		this.dsSp = dsSp;
		this.cdProduto = cdProduto;
		this.stAtivo = stAtivo;
		this.revisao = revisao;
		this.idUsrativo = idUsrativo;
		this.idUsrrevisao = idUsrrevisao;
		this.dtIsp = dtIsp;
		this.dtFsp = dtFsp;
		this.dtStativo = dtStativo;
		this.dtRevisao = dtRevisao;
		this.spProblemas = spProblemas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_SP", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSp() {
		return this.idSp;
	}

	public void setIdSp(BigDecimal idSp) {
		this.idSp = idSp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USRDONO", nullable = false)
	public OmUsr getOmUsr() {
		return this.omUsr;
	}

	public void setOmUsr(OmUsr omUsr) {
		this.omUsr = omUsr;
	}

	@Column(name = "CD_SP", length = 120)
	public String getCdSp() {
		return this.cdSp;
	}

	public void setCdSp(String cdSp) {
		this.cdSp = cdSp;
	}

	@Column(name = "DS_SP", length = 60)
	public String getDsSp() {
		return this.dsSp;
	}

	public void setDsSp(String dsSp) {
		this.dsSp = dsSp;
	}

	@Column(name = "CD_PRODUTO", nullable = false, length = 60)
	public String getCdProduto() {
		return this.cdProduto;
	}

	public void setCdProduto(String cdProduto) {
		this.cdProduto = cdProduto;
	}

	@Column(name = "ST_ATIVO", precision = 22, scale = 0)
	public BigDecimal getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(BigDecimal stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "REVISAO", precision = 22, scale = 0)
	public BigDecimal getRevisao() {
		return this.revisao;
	}

	public void setRevisao(BigDecimal revisao) {
		this.revisao = revisao;
	}

	@Column(name = "ID_USRATIVO", precision = 22, scale = 0)
	public BigDecimal getIdUsrativo() {
		return this.idUsrativo;
	}

	public void setIdUsrativo(BigDecimal idUsrativo) {
		this.idUsrativo = idUsrativo;
	}

	@Column(name = "ID_USRREVISAO", precision = 22, scale = 0)
	public BigDecimal getIdUsrrevisao() {
		return this.idUsrrevisao;
	}

	public void setIdUsrrevisao(BigDecimal idUsrrevisao) {
		this.idUsrrevisao = idUsrrevisao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_ISP", length = 7)
	public Date getDtIsp() {
		return this.dtIsp;
	}

	public void setDtIsp(Date dtIsp) {
		this.dtIsp = dtIsp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FSP", length = 7)
	public Date getDtFsp() {
		return this.dtFsp;
	}

	public void setDtFsp(Date dtFsp) {
		this.dtFsp = dtFsp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_STATIVO", length = 7)
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_REVISAO", length = 7)
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spMain")
	public Set<SpProblema> getSpProblemas() {
		return this.spProblemas;
	}

	public void setSpProblemas(Set<SpProblema> spProblemas) {
		this.spProblemas = spProblemas;
	}

	

	@Column(name = "cachep3_ciclosbarra_idgt", precision = 22, scale = 0)
	public BigDecimal getCachep3CiclosbarraIdgt() {
		return cachep3CiclosbarraIdgt;
	}
	public void setCachep3CiclosbarraIdgt(BigDecimal cachep3CiclosbarraIdgt) {
		this.cachep3CiclosbarraIdgt = cachep3CiclosbarraIdgt;
	}

	@Column(name = "cachep3_paradaspizza_idgt", precision = 22, scale = 0)
	public BigDecimal getCachep3ParadaspizzaIdgt() {
		return cachep3ParadaspizzaIdgt;
	}
	public void setCachep3ParadaspizzaIdgt(BigDecimal cachep3ParadaspizzaIdgt) {
		this.cachep3ParadaspizzaIdgt = cachep3ParadaspizzaIdgt;
	}

	@Column(name = "cachep3_paradasbarra_cdarea", length = 60)
	public String getCachep3ParadasbarraCdarea() {
		return cachep3ParadasbarraCdarea;
	}
	public void setCachep3ParadasbarraCdarea(String cachep3ParadasbarraCdarea) {
		this.cachep3ParadasbarraCdarea = cachep3ParadasbarraCdarea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cachep7_result_dti", length = 7)
	public Date getCachep7ResultDti() {
		return cachep7ResultDti;
	}
	public void setCachep7ResultDti(Date cachep7ResultDti) {
		this.cachep7ResultDti = cachep7ResultDti;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cachep7_result_dtf", length = 7)
	public Date getCachep7ResultDtf() {
		return cachep7ResultDtf;
	}
	public void setCachep7ResultDtf(Date cachep7ResultDtf) {
		this.cachep7ResultDtf = cachep7ResultDtf;
	}

	@Column(name = "cachep3_defeitosbarra_idgt", precision = 22, scale = 0)
	public BigDecimal getCachep3DefeitosbarraIdgt() {
		return cachep3DefeitosbarraIdgt;
	}
	public void setCachep3DefeitosbarraIdgt(BigDecimal cachep3DefeitosbarraIdgt) {
		this.cachep3DefeitosbarraIdgt = cachep3DefeitosbarraIdgt;
	}
	
}
