package idw.model.pojos;
// Generated 15/05/2018 16:00:51 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import idw.model.pojos.template.SpObjTemplate;

/**
 * SpObj generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SP_OBJ")
public class SpObj extends SpObjTemplate implements java.io.Serializable {

	private BigDecimal idObj;
	private SpProblema spProblema;
	private String textoobj;
	private BigDecimal stAtivo;
	private BigDecimal revisao;
	private Date dtStativo;
	private Date dtRevisao;
	private BigDecimal idUsrativo;
	private BigDecimal idUsrrevisao;

	public SpObj() {
	}

	public SpObj(BigDecimal idObj, SpProblema spProblema) {
		this.idObj = idObj;
		this.spProblema = spProblema;
	}

	public SpObj(BigDecimal idObj, SpProblema spProblema, String textoobj,
			BigDecimal stAtivo, BigDecimal revisao, Date dtStativo,
			Date dtRevisao, BigDecimal idUsrativo,
			BigDecimal idUsrrevisao) {
		this.idObj = idObj;
		this.spProblema = spProblema;
		this.textoobj = textoobj;
		this.stAtivo = stAtivo;
		this.revisao = revisao;
		this.dtStativo = dtStativo;
		this.dtRevisao = dtRevisao;
		this.idUsrativo = idUsrativo;
		this.idUsrrevisao = idUsrrevisao;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_OBJ", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdObj() {
		return this.idObj;
	}

	public void setIdObj(BigDecimal idObj) {
		this.idObj = idObj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROBLEMA", nullable = false)
	public SpProblema getSpProblema() {
		return this.spProblema;
	}

	public void setSpProblema(SpProblema spProblema) {
		this.spProblema = spProblema;
	}

	@Column(name = "TEXTOOBJ", length = 256)
	public String getTextoobj() {
		return this.textoobj;
	}

	public void setTextoobj(String textoobj) {
		this.textoobj = textoobj;
	}

	@Column(name = "ST_ATIVO", precision = 22, scale = 0)
	public BigDecimal getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(BigDecimal stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "REVISAO", precision = 22, scale = 0)
	public BigDecimal getRevisao() {
		return this.revisao;
	}

	public void setRevisao(BigDecimal revisao) {
		this.revisao = revisao;
	}

	@Column(name = "DT_STATIVO")
	public Date getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Date dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "DT_REVISAO")
	public Date getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Date dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Column(name = "ID_USRATIVO", precision = 22, scale = 0)
	public BigDecimal getIdUsrativo() {
		return this.idUsrativo;
	}

	public void setIdUsrativo(BigDecimal idUsrativo) {
		this.idUsrativo = idUsrativo;
	}

	@Column(name = "ID_USRREVISAO", precision = 22, scale = 0)
	public BigDecimal getIdUsrrevisao() {
		return this.idUsrrevisao;
	}

	public void setIdUsrrevisao(BigDecimal idUsrrevisao) {
		this.idUsrrevisao = idUsrrevisao;
	}

}
