package idw.model.pojos;
// Generated 15/05/2018 16:00:51 by Hibernate Tools 3.2.4.GA

import idw.model.pojos.template.SpSetorTemplate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SpSetor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SP_SETOR")
public class SpSetor extends SpSetorTemplate implements java.io.Serializable {

	private BigDecimal idSetor;
	private OmGt omGt;
	private String cdSetor;
	private String dsSetor;
	private BigDecimal tpSetor;
	private BigDecimal ordem;
	private BigDecimal stAtivo;
	private BigDecimal revisao;
	private Serializable dtStativo;
	private Serializable dtRevisao;
	private BigDecimal idUsrativo;
	private BigDecimal idUsrrevisao;
	private Set<SpMfv> spMfvs = new HashSet<SpMfv>(0);

	public SpSetor() {
	}

	public SpSetor(BigDecimal idSetor) {
		this.idSetor = idSetor;
	}

	public SpSetor(BigDecimal idSetor, OmGt omGt, String cdSetor,
			String dsSetor, BigDecimal tpSetor, BigDecimal ordem,
			BigDecimal stAtivo, BigDecimal revisao, Serializable dtStativo,
			Serializable dtRevisao, BigDecimal idUsrativo,
			BigDecimal idUsrrevisao, Set<SpMfv> spMfvs) {
		this.idSetor = idSetor;
		this.omGt = omGt;
		this.cdSetor = cdSetor;
		this.dsSetor = dsSetor;
		this.tpSetor = tpSetor;
		this.ordem = ordem;
		this.stAtivo = stAtivo;
		this.revisao = revisao;
		this.dtStativo = dtStativo;
		this.dtRevisao = dtRevisao;
		this.idUsrativo = idUsrativo;
		this.idUsrrevisao = idUsrrevisao;
		this.spMfvs = spMfvs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_SETOR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSetor() {
		return this.idSetor;
	}

	public void setIdSetor(BigDecimal idSetor) {
		this.idSetor = idSetor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GT")
	public OmGt getOmGt() {
		return this.omGt;
	}

	public void setOmGt(OmGt omGt) {
		this.omGt = omGt;
	}

	@Column(name = "CD_SETOR", length = 30)
	public String getCdSetor() {
		return this.cdSetor;
	}

	public void setCdSetor(String cdSetor) {
		this.cdSetor = cdSetor;
	}

	@Column(name = "DS_SETOR", length = 60)
	public String getDsSetor() {
		return this.dsSetor;
	}

	public void setDsSetor(String dsSetor) {
		this.dsSetor = dsSetor;
	}

	@Column(name = "TP_SETOR", precision = 22, scale = 0)
	public BigDecimal getTpSetor() {
		return this.tpSetor;
	}

	public void setTpSetor(BigDecimal tpSetor) {
		this.tpSetor = tpSetor;
	}

	@Column(name = "ORDEM", precision = 22, scale = 0)
	public BigDecimal getOrdem() {
		return this.ordem;
	}

	public void setOrdem(BigDecimal ordem) {
		this.ordem = ordem;
	}

	@Column(name = "ST_ATIVO", precision = 22, scale = 0)
	public BigDecimal getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(BigDecimal stAtivo) {
		this.stAtivo = stAtivo;
	}

	@Column(name = "REVISAO", precision = 22, scale = 0)
	public BigDecimal getRevisao() {
		return this.revisao;
	}

	public void setRevisao(BigDecimal revisao) {
		this.revisao = revisao;
	}

	@Column(name = "DT_STATIVO")
	public Serializable getDtStativo() {
		return this.dtStativo;
	}

	public void setDtStativo(Serializable dtStativo) {
		this.dtStativo = dtStativo;
	}

	@Column(name = "DT_REVISAO")
	public Serializable getDtRevisao() {
		return this.dtRevisao;
	}

	public void setDtRevisao(Serializable dtRevisao) {
		this.dtRevisao = dtRevisao;
	}

	@Column(name = "ID_USRATIVO", precision = 22, scale = 0)
	public BigDecimal getIdUsrativo() {
		return this.idUsrativo;
	}

	public void setIdUsrativo(BigDecimal idUsrativo) {
		this.idUsrativo = idUsrativo;
	}

	@Column(name = "ID_USRREVISAO", precision = 22, scale = 0)
	public BigDecimal getIdUsrrevisao() {
		return this.idUsrrevisao;
	}

	public void setIdUsrrevisao(BigDecimal idUsrrevisao) {
		this.idUsrrevisao = idUsrrevisao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spSetor")
	public Set<SpMfv> getSpMfvs() {
		return this.spMfvs;
	}

	public void setSpMfvs(Set<SpMfv> spMfvs) {
		this.spMfvs = spMfvs;
	}

}
