package idw.model.pojos.tdba;
// Generated Feb 4, 2013 5:42:11 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApontPesagens generated by hbm2java
 */
@Entity
@Table(name="apont_pesagens"
)
public class ApontPesagens  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 28948821867678489L;
	private BigDecimal idRegistro;
     private String nrOp;
     private String codMaquina;
     private String ferramenta;
     private String itCodigo;
     private BigDecimal vlAferido;
     private BigDecimal tpApont;
     private BigDecimal stRegistro;
     private BigDecimal motRejeitado;
     private Date dtHrProcessamento;
     private BigDecimal movIdt;
     private Date dtHrPesagem;

    public ApontPesagens() {
    }

	
    public ApontPesagens(BigDecimal idRegistro, String nrOp, String codMaquina, String ferramenta, String itCodigo, BigDecimal vlAferido, BigDecimal tpApont, BigDecimal stRegistro) {
        this.idRegistro = idRegistro;
        this.nrOp = nrOp;
        this.codMaquina = codMaquina;
        this.ferramenta = ferramenta;
        this.itCodigo = itCodigo;
        this.vlAferido = vlAferido;
        this.tpApont = tpApont;
        this.stRegistro = stRegistro;
    }
    public ApontPesagens(BigDecimal idRegistro, String nrOp, String codMaquina, String ferramenta, String itCodigo, BigDecimal vlAferido, BigDecimal tpApont, BigDecimal stRegistro, BigDecimal motRejeitado, Date dtHrProcessamento, BigDecimal movIdt,  Date dtHrPesagem) {
       this.idRegistro = idRegistro;
       this.nrOp = nrOp;
       this.codMaquina = codMaquina;
       this.ferramenta = ferramenta;
       this.itCodigo = itCodigo;
       this.vlAferido = vlAferido;
       this.tpApont = tpApont;
       this.stRegistro = stRegistro;
       this.motRejeitado = motRejeitado;
       this.dtHrProcessamento = dtHrProcessamento;
       this.movIdt = movIdt;
       this.dtHrPesagem = dtHrPesagem;
    }
   
    @Id 
    @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "APONT_PESAGENS_SEQ")
 	@javax.persistence.SequenceGenerator(name = "APONT_PESAGENS_SEQ", sequenceName = "APONT_PESAGENS_SEQ")
 	@Column(name="IdRegistro", unique=true, nullable=false, precision=30, scale=0)
    public BigDecimal getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(BigDecimal idRegistro) {
        this.idRegistro = idRegistro;
    }

    
    @Column(name="NrOP", nullable=false, length=20)
    public String getNrOp() {
        return this.nrOp;
    }
    
    public void setNrOp(String nrOp) {
        this.nrOp = nrOp;
    }

    
    @Column(name="cod_maquina", nullable=false, length=8)
    public String getCodMaquina() {
        return this.codMaquina;
    }
    
    public void setCodMaquina(String codMaquina) {
        this.codMaquina = codMaquina;
    }

    
    @Column(name="ferramenta", nullable=false, length=18)
    public String getFerramenta() {
        return this.ferramenta;
    }
    
    public void setFerramenta(String ferramenta) {
        this.ferramenta = ferramenta;
    }

    
    @Column(name="it_codigo", nullable=false, length=20)
    public String getItCodigo() {
        return this.itCodigo;
    }
    
    public void setItCodigo(String itCodigo) {
        this.itCodigo = itCodigo;
    }

    
    @Column(name="vl_aferido", nullable=false, precision=30, scale=15)
    public BigDecimal getVlAferido() {
        return this.vlAferido;
    }
    
    public void setVlAferido(BigDecimal vlAferido) {
        this.vlAferido = vlAferido;
    }

    @Column(name="tp_apont", nullable=false, precision=30, scale=15)
    public BigDecimal getTpApont() {
        return this.tpApont;
    }
    
    public void setTpApont(BigDecimal tpApont) {
        this.tpApont = tpApont;
    }
    
    @Column(name="StRegistro", nullable=false, length=1)
    public BigDecimal getStRegistro() {
        return this.stRegistro;
    }
    
    public void setStRegistro(BigDecimal stRegistro) {
        this.stRegistro = stRegistro;
    }

    
    @Column(name="MotRejeitado", precision=38, scale=0)
    public BigDecimal getMotRejeitado() {
        return this.motRejeitado;
    }
    
    public void setMotRejeitado(BigDecimal motRejeitado) {
        this.motRejeitado = motRejeitado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_hr_processamento")
    public Date getDtHrProcessamento() {
        return this.dtHrProcessamento;
    }
    
    public void setDtHrProcessamento(Date dtHrProcessamento) {
        this.dtHrProcessamento = dtHrProcessamento;
    }

    
    @Column(name="Mov_idt", precision=38, scale=0)
    public BigDecimal getMovIdt() {
        return this.movIdt;
    }
    
    public void setMovIdt(BigDecimal movIdt) {
        this.movIdt = movIdt;
    }

    @Temporal(TemporalType.TIMESTAMP)   
    @Column(name="dt_hr_pesagem")
    public Date getDtHrPesagem() {
        return this.dtHrPesagem;
    }
    
    public void setDtHrPesagem(Date dtHrPesagem) {
        this.dtHrPesagem = dtHrPesagem;
    }




}


