package idw.model.pojos.tdba;
// Generated Feb 4, 2013 5:42:11 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SbOpsMaquinas generated by hbm2java
 */
@Entity
@Table(name="sb_OPs_Maquinas"
)
public class SbOpsMaquinas  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5275534738488376780L;
	private BigDecimal idRegistro;
     private String nrOp;
     private String codMaquina;
     private BigDecimal tipoOperacao;
     private char stRegistro;
     private BigDecimal motRejeitado;
     private Date dtHrProcessamento;

    public SbOpsMaquinas() {
    }

	
    public SbOpsMaquinas(BigDecimal idRegistro, String nrOp, String codMaquina, BigDecimal tipoOperacao, char stRegistro) {
        this.idRegistro = idRegistro;
        this.nrOp = nrOp;
        this.codMaquina = codMaquina;
        this.tipoOperacao = tipoOperacao;
        this.stRegistro = stRegistro;
    }
    public SbOpsMaquinas(BigDecimal idRegistro, String nrOp, String codMaquina, BigDecimal tipoOperacao, char stRegistro, BigDecimal motRejeitado, Date dtHrProcessamento) {
       this.idRegistro = idRegistro;
       this.nrOp = nrOp;
       this.codMaquina = codMaquina;
       this.tipoOperacao = tipoOperacao;
       this.stRegistro = stRegistro;
       this.motRejeitado = motRejeitado;
       this.dtHrProcessamento = dtHrProcessamento;
    }
   
     @Id 

    
    @Column(name="IdRegistro", unique=true, nullable=false, precision=30, scale=0)
    public BigDecimal getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(BigDecimal idRegistro) {
        this.idRegistro = idRegistro;
    }

    
    @Column(name="NrOP", nullable=false, length=20)
    public String getNrOp() {
        return this.nrOp;
    }
    
    public void setNrOp(String nrOp) {
        this.nrOp = nrOp;
    }

    
    @Column(name="cod_maquina", nullable=false, length=8)
    public String getCodMaquina() {
        return this.codMaquina;
    }
    
    public void setCodMaquina(String codMaquina) {
        this.codMaquina = codMaquina;
    }

    
    @Column(name="tipo_operacao", nullable=false, precision=38, scale=0)
    public BigDecimal getTipoOperacao() {
        return this.tipoOperacao;
    }
    
    public void setTipoOperacao(BigDecimal tipoOperacao) {
        this.tipoOperacao = tipoOperacao;
    }

    
    @Column(name="StRegistro", nullable=false, length=1)
    public char getStRegistro() {
        return this.stRegistro;
    }
    
    public void setStRegistro(char stRegistro) {
        this.stRegistro = stRegistro;
    }

    
    @Column(name="MotRejeitado", precision=38, scale=0)
    public BigDecimal getMotRejeitado() {
        return this.motRejeitado;
    }
    
    public void setMotRejeitado(BigDecimal motRejeitado) {
        this.motRejeitado = motRejeitado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_hr_processamento")
    public Date getDtHrProcessamento() {
        return this.dtHrProcessamento;
    }
    
    public void setDtHrProcessamento(Date dtHrProcessamento) {
        this.dtHrProcessamento = dtHrProcessamento;
    }




}


