package injetws.model.pojos;

// default package
// Generated 08/03/2010 15:46:01 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrColetorDriverParam generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_COLETOR_DRIVER_PARAM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDREGDRIVERCOLETOR", "ORDEMPARAMETRO" }))
public class PrColetorDriverParam implements java.io.Serializable {

	private String idregcoletordriverparam;
	private PrColetorDriver prColetorDriver;
	private BigDecimal ordemparametro;
	private String dsparametro;
	private String parametro;

	public PrColetorDriverParam() {
	}

	public PrColetorDriverParam(String idregcoletordriverparam,
			PrColetorDriver prColetorDriver, BigDecimal ordemparametro,
			String dsparametro, String parametro) {
		this.idregcoletordriverparam = idregcoletordriverparam;
		this.prColetorDriver = prColetorDriver;
		this.ordemparametro = ordemparametro;
		this.dsparametro = dsparametro;
		this.parametro = parametro;
	}

	@Id
	@Column(name = "IDREGCOLETORDRIVERPARAM", unique = true, nullable = false, length = 36)
	public String getIdregcoletordriverparam() {
		return this.idregcoletordriverparam;
	}

	public void setIdregcoletordriverparam(String idregcoletordriverparam) {
		this.idregcoletordriverparam = idregcoletordriverparam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGDRIVERCOLETOR", nullable = false)
	public PrColetorDriver getPrColetorDriver() {
		return this.prColetorDriver;
	}

	public void setPrColetorDriver(PrColetorDriver prColetorDriver) {
		this.prColetorDriver = prColetorDriver;
	}

	@Column(name = "ORDEMPARAMETRO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOrdemparametro() {
		return this.ordemparametro;
	}

	public void setOrdemparametro(BigDecimal ordemparametro) {
		this.ordemparametro = ordemparametro;
	}

	@Column(name = "DSPARAMETRO", nullable = false, length = 60)
	public String getDsparametro() {
		return this.dsparametro;
	}

	public void setDsparametro(String dsparametro) {
		this.dsparametro = dsparametro;
	}

	@Column(name = "PARAMETRO", nullable = false)
	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

}
