package injetws.model.pojos;
// default package
// Generated 16/10/2008 15:14:14 by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PrColetor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_COLETOR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDCOLETOR", "IDREGCONEXAOINJET" }))
public class PrColetor implements java.io.Serializable {

	private BigDecimal idregcoletor;
	private PrConexoesInjet prConexoesInjet;
	private String idcoletor;
	private String idcoletor2;
	private Date dthrultacessobd;
	private Double msdthrultacessobd;
	private Date dthrultacessows;
	private Double msdthrultacessows;
	private Character stmonitoraespera;
	private Set<PrSubColetor> prSubColetors = new HashSet<PrSubColetor>(0);

	public PrColetor() {
	}

	public PrColetor(BigDecimal idregcoletor, PrConexoesInjet prConexoesInjet,
			String idcoletor) {
		this.idregcoletor = idregcoletor;
		this.prConexoesInjet = prConexoesInjet;
		this.idcoletor = idcoletor;
	}

	public PrColetor(BigDecimal idregcoletor, PrConexoesInjet prConexoesInjet,
			String idcoletor, Date dthrultacessobd, Double msdthrultacessobd,
			Set<PrSubColetor> prSubColetors,Character stmonitoraespera) {
		this.idregcoletor = idregcoletor;
		this.prConexoesInjet = prConexoesInjet;
		this.idcoletor = idcoletor;
		this.dthrultacessobd = dthrultacessobd;
		this.msdthrultacessobd = msdthrultacessobd;
		this.prSubColetors = prSubColetors;
		this.stmonitoraespera = stmonitoraespera;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO, generator = "S_PR_COLETOR")
	@javax.persistence.SequenceGenerator(name = "S_PR_COLETOR", sequenceName = "S_PR_COLETOR")
	@Column(name = "IDREGCOLETOR", unique = true, nullable = false, length = 36)
	public BigDecimal getIdregcoletor() {
		return this.idregcoletor;
	}

	public void setIdregcoletor(BigDecimal idregcoletor) {
		this.idregcoletor = idregcoletor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGCONEXAOINJET", nullable = false)
	public PrConexoesInjet getPrConexoesInjet() {
		return this.prConexoesInjet;
	}

	public void setPrConexoesInjet(PrConexoesInjet prConexoesInjet) {
		this.prConexoesInjet = prConexoesInjet;
	}

	@Column(name = "IDCOLETOR", nullable = false, length = 20)
	public String getIdcoletor() {
		return this.idcoletor;
	}

	public void setIdcoletor(String idcoletor) {
		this.idcoletor = idcoletor;
	}

	@Column(name = "IDCOLETOR2", length = 20, updatable = true)
	public String getIdcoletor2() {
		return this.idcoletor2;
	}

	public void setIdcoletor2(String idcoletor) {
		this.idcoletor2 = idcoletor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRULTACESSOBD")
	public Date getDthrultacessobd() {
		return this.dthrultacessobd;
	}

	public void setDthrultacessobd(Date dthrultacessobd) {
		this.dthrultacessobd = dthrultacessobd;
	}

	@Column(name = "MSDTHRULTACESSOBD", precision = 126, scale = 0)
	public Double getMsdthrultacessobd() {
		return this.msdthrultacessobd;
	}

	public void setMsdthrultacessobd(Double msdthrultacessobd) {
		this.msdthrultacessobd = msdthrultacessobd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRULTACESSOWS")
	public Date getDthrultacessows() {
		return this.dthrultacessows;
	}

	public void setDthrultacessows(Date dthrultacessows) {
		this.dthrultacessows = dthrultacessows;
	}

	@Column(name = "MSDTHRULTACESSOWS", precision = 126, scale = 0)
	public Double getMsdthrultacessows() {
		return this.msdthrultacessows;
	}

	public void setMsdthrultacessows(Double msdthrultacessows) {
		this.msdthrultacessows = msdthrultacessows;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prColetor")
	public Set<PrSubColetor> getPrSubColetors() {
		return this.prSubColetors;
	}

	public void setPrSubColetors(Set<PrSubColetor> prSubColetors) {
		this.prSubColetors = prSubColetors;
	}
	
	@Column(name = "STMONITORAESPERA", length = 1)
	public Character getStmonitoraespera() {
		return this.stmonitoraespera;
	}

	public void setStmonitoraespera(Character stmonitoraespera) {
		this.stmonitoraespera = stmonitoraespera;
	}

}
