package injetws.model.pojos;

// default package
// Generated 15/01/2010 14:33:32 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrOperacaoColetaDiscreta generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_OPERACAO_COLETA_DISCRETA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDREGCONEXAOINJET", "CDOPERACAO" }))
public class PrOperacaoColetaDiscreta implements java.io.Serializable {

	private String idregoperacao;
	private PrConexoesInjet prConexoesInjet;
	private String cdoperacao;
	private String dsoperacao;
	private BigDecimal tpoperacao;
	private BigDecimal tpfuncoperacao;
	private String siglaum;

	public PrOperacaoColetaDiscreta() {
	}

	public PrOperacaoColetaDiscreta(String idregoperacao,
			PrConexoesInjet prConexoesInjet, String cdoperacao,
			String dsoperacao, BigDecimal tpoperacao,
			BigDecimal tpfuncoperacao, String siglaum) {
		this.idregoperacao = idregoperacao;
		this.prConexoesInjet = prConexoesInjet;
		this.cdoperacao = cdoperacao;
		this.dsoperacao = dsoperacao;
		this.tpoperacao = tpoperacao;
		this.tpfuncoperacao = tpfuncoperacao;
		this.siglaum = siglaum;
	}

	@Id
	@Column(name = "IDREGOPERACAO", unique = true, nullable = false, length = 36)
	public String getIdregoperacao() {
		return this.idregoperacao;
	}

	public void setIdregoperacao(String idregoperacao) {
		this.idregoperacao = idregoperacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGCONEXAOINJET", nullable = false)
	public PrConexoesInjet getPrConexoesInjet() {
		return this.prConexoesInjet;
	}

	public void setPrConexoesInjet(PrConexoesInjet prConexoesInjet) {
		this.prConexoesInjet = prConexoesInjet;
	}

	@Column(name = "CDOPERACAO", nullable = false, length = 6)
	public String getCdoperacao() {
		return this.cdoperacao;
	}

	public void setCdoperacao(String cdoperacao) {
		this.cdoperacao = cdoperacao;
	}

	@Column(name = "DSOPERACAO", nullable = false, length = 40)
	public String getDsoperacao() {
		return this.dsoperacao;
	}

	public void setDsoperacao(String dsoperacao) {
		this.dsoperacao = dsoperacao;
	}

	@Column(name = "TPOPERACAO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpoperacao() {
		return this.tpoperacao;
	}

	public void setTpoperacao(BigDecimal tpoperacao) {
		this.tpoperacao = tpoperacao;
	}

	@Column(name = "TPFUNCOPERACAO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpfuncoperacao() {
		return this.tpfuncoperacao;
	}

	public void setTpfuncoperacao(BigDecimal tpfuncoperacao) {
		this.tpfuncoperacao = tpfuncoperacao;
	}

	@Column(name = "SIGLAUM", nullable = false, length = 10)
	public String getSiglaum() {
		return this.siglaum;
	}

	public void setSiglaum(String siglaum) {
		this.siglaum = siglaum;
	}

}
