package injetws.model.pojos;

//import PrConexoesInjet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

// Generated 02/01/2012 14:45:53 by Hibernate Tools 3.4.0.CR1

/**
 * PrProUsu generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_PRO_USU", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDREGCONEXAOINJET", "CDUSUARIO", "CDPRODUTO" }))
public class PrProUsu implements java.io.Serializable {

	private String idregprousu;
	private PrConexoesInjet prConexoesInjet;
	private String cdproduto;
	private String cdusuario;

	public PrProUsu() {
	}

	public PrProUsu(String idregprousu, PrConexoesInjet prConexoesInjet,
			String cdproduto, String cdusuario) {
		this.idregprousu = idregprousu;
		this.prConexoesInjet = prConexoesInjet;
		this.cdproduto = cdproduto;
		this.cdusuario = cdusuario;
	}

	@Id
	@Column(name = "IDREGPROUSU", unique = true, nullable = false, length = 36)
	public String getIdregprousu() {
		return this.idregprousu;
	}

	public void setIdregprousu(String idregprousu) {
		this.idregprousu = idregprousu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGCONEXAOINJET", nullable = false)
	public PrConexoesInjet getPrConexoesInjet() {
		return this.prConexoesInjet;
	}

	public void setPrConexoesInjet(PrConexoesInjet prConexoesInjet) {
		this.prConexoesInjet = prConexoesInjet;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "CDUSUARIO", nullable = false, length = 6)
	public String getCdusuario() {
		return this.cdusuario;
	}

	public void setCdusuario(String cdusuario) {
		this.cdusuario = cdusuario;
	}

}
