package injetws.model.pojos;

// default package
// Generated 17/03/2010 09:39:07 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrUpExecinspecaoId generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_EXECINSPECAO", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "IdUP", "IdInspecao", "IdParametro",
				"OrdemLeitura", "IdCavidade", "Amostra", "SubAmostra" }) })
public class PrUpExecinspecao implements java.io.Serializable {

	private String idExecInpecao;	
	private PrUpCtrlExecinspecao prUpCtrlExecinspecao;	
	private String idInspecao;
	private int ordemLeitura;
	private String idParametro;
	private Character tpParametro;
	private String dsParametro;
	private String cdProduto;
	private String dsProduto;
	private Integer tamAmostra;
	private BigDecimal idCavidade;
	private String nmCavidade;
	private int amostra;
	private Integer subAmostra;
	private Float vlLido;
	private Character stExecucao;
	private String idParametroComp;
	private Integer tpEntradaVlr;
	private String idDriver;
	private BigDecimal lipercTolerancia;
	private BigDecimal lspercTolerancia;

	public PrUpExecinspecao() {
	}

	public PrUpExecinspecao(BigDecimal idSequence, String idInspecao,
			int ordemLeitura, String idParametro, char tpParametro,
			String dsParametro, String cdProduto, String dsProduto,
			BigDecimal idCavidade, int amostra, Float vlLido,
			char stExecucao) {
		this.idInspecao = idInspecao;
		this.ordemLeitura = ordemLeitura;
		this.idParametro = idParametro;
		this.tpParametro = tpParametro;
		this.dsParametro = dsParametro;
		this.cdProduto = cdProduto;
		this.dsProduto = dsProduto;
		this.idCavidade = idCavidade;
		this.amostra = amostra;
		this.vlLido = vlLido;
		this.stExecucao = stExecucao;
	}

	public PrUpExecinspecao(String idExecInpecao,
			String idInspecao, int ordemLeitura,
			String idParametro, char tpParametro, String dsParametro,
			String cdProduto, String dsProduto, Integer tamAmostra,
			BigDecimal idCavidade, String nmCavidade, int amostra,
			Integer subAmostra, Float vlLido, char stExecucao,
			String idParametroComp, Integer tpEntradaVlr, String idDriver,
			BigDecimal lipercTolerancia, BigDecimal lspercTolerancia) {
		this.idExecInpecao = idExecInpecao;		
		this.idInspecao = idInspecao;
		this.ordemLeitura = ordemLeitura;
		this.idParametro = idParametro;
		this.tpParametro = tpParametro;
		this.dsParametro = dsParametro;
		this.cdProduto = cdProduto;
		this.dsProduto = dsProduto;
		this.tamAmostra = tamAmostra;
		this.idCavidade = idCavidade;
		this.nmCavidade = nmCavidade;
		this.amostra = amostra;
		this.subAmostra = subAmostra;
		this.vlLido = vlLido;
		this.stExecucao = stExecucao;
		this.idParametroComp = idParametroComp;
		this.tpEntradaVlr = tpEntradaVlr;
		this.idDriver = idDriver;
		this.lipercTolerancia = lipercTolerancia;
		this.lspercTolerancia = lspercTolerancia;
	}

	@Id
	@Column(name = "IdExecInpecao", unique = true, length = 36)
	public String getIdExecInpecao() {
		return this.idExecInpecao;
	}

	public void setIdExecInpecao(String idExecInpecao) {
		this.idExecInpecao = idExecInpecao;
	}

	@Column(name = "IdInspecao", nullable = false, length = 12)
	public String getIdInspecao() {
		return this.idInspecao;
	}

	public void setIdInspecao(String idInspecao) {
		this.idInspecao = idInspecao;
	}

	@Column(name = "OrdemLeitura", nullable = false)
	public int getOrdemLeitura() {
		return this.ordemLeitura;
	}

	public void setOrdemLeitura(int ordemLeitura) {
		this.ordemLeitura = ordemLeitura;
	}

	@Column(name = "IdParametro", nullable = false, length = 20)
	public String getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(String idParametro) {
		this.idParametro = idParametro;
	}

	@Column(name = "TpParametro", nullable = false, length = 1)
	public char getTpParametro() {
		return this.tpParametro;
	}

	public void setTpParametro(char tpParametro) {
		this.tpParametro = tpParametro;
	}

	@Column(name = "DsParametro", nullable = false, length = 60)
	public String getDsParametro() {
		return this.dsParametro;
	}

	public void setDsParametro(String dsParametro) {
		this.dsParametro = dsParametro;
	}

	@Column(name = "CdProduto", nullable = false, length = 20)
	public String getCdProduto() {
		return this.cdProduto;
	}

	public void setCdProduto(String cdProduto) {
		this.cdProduto = cdProduto;
	}

	@Column(name = "DsProduto", nullable = false, length = 40)
	public String getDsProduto() {
		return this.dsProduto;
	}

	public void setDsProduto(String dsProduto) {
		this.dsProduto = dsProduto;
	}

	@Column(name = "TamAmostra")
	public Integer getTamAmostra() {
		return this.tamAmostra;
	}

	public void setTamAmostra(Integer tamAmostra) {
		this.tamAmostra = tamAmostra;
	}

	@Column(name = "IdCavidade", nullable = false, precision = 30, scale = 0)
	public BigDecimal getIdCavidade() {
		return this.idCavidade;
	}

	public void setIdCavidade(BigDecimal idCavidade) {
		this.idCavidade = idCavidade;
	}

	@Column(name = "NmCavidade", length = 20)
	public String getNmCavidade() {
		return this.nmCavidade;
	}

	public void setNmCavidade(String nmCavidade) {
		this.nmCavidade = nmCavidade;
	}

	@Column(name = "Amostra", nullable = false)
	public int getAmostra() {
		return this.amostra;
	}

	public void setAmostra(int amostra) {
		this.amostra = amostra;
	}

	@Column(name = "SubAmostra")
	public Integer getSubAmostra() {
		return this.subAmostra;
	}

	public void setSubAmostra(Integer subAmostra) {
		this.subAmostra = subAmostra;
	}

	@Column(name = "VlLido", nullable = false, precision = 30, scale = 15)
	public Float getVlLido() {
		return this.vlLido;
	}

	public void setVlLido(Float vlLido) {
		this.vlLido = vlLido;
	}

	@Column(name = "StExecucao", nullable = false, length = 1)
	public char getStExecucao() {
		return this.stExecucao;
	}

	public void setStExecucao(char stExecucao) {
		this.stExecucao = stExecucao;
	}

	@Column(name = "IdParametroComp", length = 20)
	public String getIdParametroComp() {
		return this.idParametroComp;
	}

	public void setIdParametroComp(String idParametroComp) {
		this.idParametroComp = idParametroComp;
	}

	@Column(name = "TpEntradaVlr")
	public Integer getTpEntradaVlr() {
		return this.tpEntradaVlr;
	}

	public void setTpEntradaVlr(Integer tpEntradaVlr) {
		this.tpEntradaVlr = tpEntradaVlr;
	}

	@Column(name = "IdDriver", length = 20)
	public String getIdDriver() {
		return this.idDriver;
	}

	public void setIdDriver(String idDriver) {
		this.idDriver = idDriver;
	}

	@Column(name = "LIPercTolerancia", precision = 30, scale = 15)
	public BigDecimal getLipercTolerancia() {
		return this.lipercTolerancia;
	}

	public void setLipercTolerancia(BigDecimal lipercTolerancia) {
		this.lipercTolerancia = lipercTolerancia;
	}

	@Column(name = "LSPercTolerancia", precision = 30, scale = 15)
	public BigDecimal getLspercTolerancia() {
		return this.lspercTolerancia;
	}

	public void setLspercTolerancia(BigDecimal lspercTolerancia) {
		this.lspercTolerancia = lspercTolerancia;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUP", nullable = false)
	public PrUpCtrlExecinspecao getPrUpCtrlExecinspecao() {
		return this.prUpCtrlExecinspecao;
	}

	public void setPrUpCtrlExecinspecao(PrUpCtrlExecinspecao prUp) {
		this.prUpCtrlExecinspecao = prUp;
	}
}
