package injetws.model.pojos;

// default package
// Generated 08/03/2010 15:46:01 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrUpAndonConfigArg generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_ANDON_CONFIG_ARG")
public class PrUpAndonConfigArg implements java.io.Serializable {

	private PrUpAndonConfigArgId id;
	private PrUpAndonConfig prUpAndonConfig;
	private String operadorlogico;
	private String operadorcalculo;
	private BigDecimal tpvlreferencia;
	private String vlreferenciastr;
	private Double vlreferencianum;

	public PrUpAndonConfigArg() {
	}

	public PrUpAndonConfigArg(PrUpAndonConfigArgId id,
			PrUpAndonConfig prUpAndonConfig, BigDecimal tpvlreferencia) {
		this.id = id;
		this.prUpAndonConfig = prUpAndonConfig;
		this.tpvlreferencia = tpvlreferencia;
	}

	public PrUpAndonConfigArg(PrUpAndonConfigArgId id,
			PrUpAndonConfig prUpAndonConfig, String operadorlogico,
			String operadorcalculo, BigDecimal tpvlreferencia,
			String vlreferenciastr, Double vlreferencianum) {
		this.id = id;
		this.prUpAndonConfig = prUpAndonConfig;
		this.operadorlogico = operadorlogico;
		this.operadorcalculo = operadorcalculo;
		this.tpvlreferencia = tpvlreferencia;
		this.vlreferenciastr = vlreferenciastr;
		this.vlreferencianum = vlreferencianum;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idconfigandon", column = @Column(name = "IDCONFIGANDON", nullable = false, length = 36)),
			@AttributeOverride(name = "ideventoandon", column = @Column(name = "IDEVENTOANDON", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "ordemcondicao", column = @Column(name = "ORDEMCONDICAO", nullable = false, precision = 22, scale = 0)) })
	public PrUpAndonConfigArgId getId() {
		return this.id;
	}

	public void setId(PrUpAndonConfigArgId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCONFIGANDON", nullable = false, insertable = false, updatable = false)
	public PrUpAndonConfig getPrUpAndonConfig() {
		return this.prUpAndonConfig;
	}

	public void setPrUpAndonConfig(PrUpAndonConfig prUpAndonConfig) {
		this.prUpAndonConfig = prUpAndonConfig;
	}

	@Column(name = "OPERADORLOGICO", length = 20)
	public String getOperadorlogico() {
		return this.operadorlogico;
	}

	public void setOperadorlogico(String operadorlogico) {
		this.operadorlogico = operadorlogico;
	}

	@Column(name = "OPERADORCALCULO", length = 20)
	public String getOperadorcalculo() {
		return this.operadorcalculo;
	}

	public void setOperadorcalculo(String operadorcalculo) {
		this.operadorcalculo = operadorcalculo;
	}

	@Column(name = "TPVLREFERENCIA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpvlreferencia() {
		return this.tpvlreferencia;
	}

	public void setTpvlreferencia(BigDecimal tpvlreferencia) {
		this.tpvlreferencia = tpvlreferencia;
	}

	@Column(name = "VLREFERENCIASTR", length = 20)
	public String getVlreferenciastr() {
		return this.vlreferenciastr;
	}

	public void setVlreferenciastr(String vlreferenciastr) {
		this.vlreferenciastr = vlreferenciastr;
	}

	@Column(name = "VLREFERENCIANUM", precision = 126, scale = 0)
	public Double getVlreferencianum() {
		return this.vlreferencianum;
	}

	public void setVlreferencianum(Double vlreferencianum) {
		this.vlreferencianum = vlreferencianum;
	}

}
