package injetws.model.pojos;

// Generated 23/08/2012 14:41:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrUpCtrlInicioProcesso generated by hbm2java
 */
@Entity
@Table(name = "PR_UP_CTRL_INICIO_PROCESSO")
public class PrUpCtrlInicioProcesso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -55560251411328436L;
	private String idup;
	private PrUp prUp;
	private Date dthrinicio;
	private String cdtecinicio;
	private Date dthrfinal;
	private String cdtecfinal;
	private Character iscippendente;
	private String cdmoldeantigo;

	public PrUpCtrlInicioProcesso() {
	}

	public PrUpCtrlInicioProcesso(String idup, PrUp prUp) {
		this.idup = idup;
		this.prUp = prUp;
	}

	public PrUpCtrlInicioProcesso(String idup, PrUp prUp, Date dthrinicio,
			String cdtecinicio, Date dthrfinal, String cdtecfinal,
			Character iscippendente, String cdmoldeantigo) {
		this.idup = idup;
		this.prUp = prUp;
		this.dthrinicio = dthrinicio;
		this.cdtecinicio = cdtecinicio;
		this.dthrfinal = dthrfinal;
		this.cdtecfinal = cdtecfinal;
		this.iscippendente = iscippendente;
		this.cdmoldeantigo = cdmoldeantigo;
	}

	@Id
	@Column(name = "IDUP", unique = true, nullable = false, length = 36)
	public String getIdup() {
		return this.idup;
	}

	public void setIdup(String idup) {
		this.idup = idup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUP", unique = true, nullable = false, insertable = false, updatable = false)
	public PrUp getPrUp() {
		return this.prUp;
	}

	public void setPrUp(PrUp prUp) {
		this.prUp = prUp;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRINICIO")
	public Date getDthrinicio() {
		return this.dthrinicio;
	}

	public void setDthrinicio(Date dthrinicio) {
		this.dthrinicio = dthrinicio;
	}

	@Column(name = "CDTECINICIO", length = 6)
	public String getCdtecinicio() {
		return this.cdtecinicio;
	}

	public void setCdtecinicio(String cdtecinicio) {
		this.cdtecinicio = cdtecinicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRFINAL")
	public Date getDthrfinal() {
		return this.dthrfinal;
	}

	public void setDthrfinal(Date dthrfinal) {
		this.dthrfinal = dthrfinal;
	}

	@Column(name = "CDTECFINAL", length = 6)
	public String getCdtecfinal() {
		return this.cdtecfinal;
	}

	public void setCdtecfinal(String cdtecfinal) {
		this.cdtecfinal = cdtecfinal;
	}

	@Column(name = "ISCIPPENDENTE", length = 1)
	public Character getIscippendente() {
		return this.iscippendente;
	}

	public void setIscippendente(Character iscippendente) {
		this.iscippendente = iscippendente;
	}

	@Column(name = "CDMOLDEANTIGO", length = 6)
	public String getCdmoldeantigo() {
		return this.cdmoldeantigo;
	}

	public void setCdmoldeantigo(String cdmoldeantigo) {
		this.cdmoldeantigo = cdmoldeantigo;
	}

}
