package injetws.model.pojos;

// default package
// Generated 15/01/2010 14:33:32 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * PrUpOpsEmAberto generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_OPS_EM_ABERTO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDUP", "NROP", "CDMOLDE", "CDESTRUTURA" }))
public class PrUpOpsEmAberto implements java.io.Serializable {

	private String idopemaberto;
	private PrUp prUp;
	private String nrop;
	private String nropestendido;
	private String cdmolde;
	private String cdmolestendido;
	private String cdestrutura;
	private Date dthriniplanejada;
	private String cdoperacao;
	private Set<PrUpOpsEmAbertoProd> prUpOpsEmAbertoProds = new HashSet<PrUpOpsEmAbertoProd>(
			0);
	private Set<PrUpParadasEmAberto> prUpParadasEmAbertos = new HashSet<PrUpParadasEmAberto>(
			0);

	public PrUpOpsEmAberto() {
	}

	public PrUpOpsEmAberto(String idopemaberto, PrUp prUp, String nrop,
			String nropestendido, String cdmolde, String cdmolestendido,
			String cdestrutura, Date dthriniplanejada, String cdoperacao) {
		this.idopemaberto = idopemaberto;
		this.prUp = prUp;
		this.nrop = nrop;
		this.nropestendido = nropestendido;
		this.cdmolde = cdmolde;
		this.cdmolestendido = cdmolestendido;
		this.cdestrutura = cdestrutura;
		this.dthriniplanejada = dthriniplanejada;
		this.cdoperacao = cdoperacao;
	}

	public PrUpOpsEmAberto(String idopemaberto, PrUp prUp, String nrop,
			String nropestendido, String cdmolde, String cdmolestendido,
			String cdestrutura, Date dthriniplanejada, String cdoperacao,
			Set<PrUpOpsEmAbertoProd> prUpOpsEmAbertoProds,
			Set<PrUpParadasEmAberto> prUpParadasEmAbertos) {
		this.idopemaberto = idopemaberto;
		this.prUp = prUp;
		this.nrop = nrop;
		this.nropestendido = nropestendido;
		this.cdmolde = cdmolde;
		this.cdmolestendido = cdmolestendido;
		this.cdestrutura = cdestrutura;
		this.dthriniplanejada = dthriniplanejada;
		this.cdoperacao = cdoperacao;
		this.prUpOpsEmAbertoProds = prUpOpsEmAbertoProds;
		this.prUpParadasEmAbertos = prUpParadasEmAbertos;
	}

	@Id
	@Column(name = "IDOPEMABERTO", unique = true, nullable = false, length = 36)
	public String getIdopemaberto() {
		return this.idopemaberto;
	}

	public void setIdopemaberto(String idopemaberto) {
		this.idopemaberto = idopemaberto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUP", nullable = false)
	public PrUp getPrUp() {
		return this.prUp;
	}

	public void setPrUp(PrUp prUp) {
		this.prUp = prUp;
	}

	@Column(name = "NROP", nullable = false, length = 10)
	public String getNrop() {
		return this.nrop;
	}

	public void setNrop(String nrop) {
		this.nrop = nrop;
	}

	@Column(name = "NROPESTENDIDO", nullable = false, length = 20)
	public String getNropestendido() {
		return this.nropestendido;
	}

	public void setNropestendido(String nropestendido) {
		this.nropestendido = nropestendido;
	}

	@Column(name = "CDMOLDE", nullable = false, length = 6)
	public String getCdmolde() {
		return this.cdmolde;
	}

	public void setCdmolde(String cdmolde) {
		this.cdmolde = cdmolde;
	}

	@Column(name = "CDMOLESTENDIDO", nullable = false, length = 20)
	public String getCdmolestendido() {
		return this.cdmolestendido;
	}

	public void setCdmolestendido(String cdmolestendido) {
		this.cdmolestendido = cdmolestendido;
	}

	@Column(name = "CDESTRUTURA", nullable = false, length = 4)
	public String getCdestrutura() {
		return this.cdestrutura;
	}

	public void setCdestrutura(String cdestrutura) {
		this.cdestrutura = cdestrutura;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRINIPLANEJADA", nullable = false, length = 7)
	public Date getDthriniplanejada() {
		return this.dthriniplanejada;
	}

	public void setDthriniplanejada(Date dthriniplanejada) {
		this.dthriniplanejada = dthriniplanejada;
	}

	@Column(name = "CDOPERACAO", nullable = false, length = 6)
	public String getCdoperacao() {
		return this.cdoperacao;
	}

	public void setCdoperacao(String cdoperacao) {
		this.cdoperacao = cdoperacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prUpOpsEmAberto")
	public Set<PrUpOpsEmAbertoProd> getPrUpOpsEmAbertoProds() {
		return this.prUpOpsEmAbertoProds;
	}

	public void setPrUpOpsEmAbertoProds(
			Set<PrUpOpsEmAbertoProd> prUpOpsEmAbertoProds) {
		this.prUpOpsEmAbertoProds = prUpOpsEmAbertoProds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prUpOpsEmAberto")
	public Set<PrUpParadasEmAberto> getPrUpParadasEmAbertos() {
		return this.prUpParadasEmAbertos;
	}

	public void setPrUpParadasEmAbertos(
			Set<PrUpParadasEmAberto> prUpParadasEmAbertos) {
		this.prUpParadasEmAbertos = prUpParadasEmAbertos;
	}

}
