package injetws.model.pojos;
// default package
// Generated 16/10/2008 15:14:14 by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PrUpAlertasEmAberto generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_ALERTAS_EM_ABERTO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDUP", "CDALERTA" }))
public class PrUpAlertasEmAberto implements java.io.Serializable {

	private String idalertaaberto;
	private PrUp prUp;
	private String cdalerta;
	private Date dthrinialerta;
	private double msdthrinialerta;
	private Integer tpalerta;
	
	public PrUpAlertasEmAberto() {
	}

	public PrUpAlertasEmAberto(String idalertaaberto, PrUp prUp,
			String cdalerta, Date dthrinialerta, double msdthrinialerta) {
		this.idalertaaberto = idalertaaberto;
		this.prUp = prUp;
		this.cdalerta = cdalerta;
		this.dthrinialerta = dthrinialerta;
		this.msdthrinialerta = msdthrinialerta;
	}

	@Id
	@Column(name = "IDALERTAABERTO", unique = true, nullable = false, length = 36)
	public String getIdalertaaberto() {
		return this.idalertaaberto;
	}

	public void setIdalertaaberto(String idalertaaberto) {
		this.idalertaaberto = idalertaaberto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUP", nullable = false)
	public PrUp getPrUp() {
		return this.prUp;
	}

	public void setPrUp(PrUp prUp) {
		this.prUp = prUp;
	}

	@Column(name = "CDALERTA", nullable = false, length = 6)
	public String getCdalerta() {
		return this.cdalerta;
	}

	public void setCdalerta(String cdalerta) {
		this.cdalerta = cdalerta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRINIALERTA", nullable = false)
	public Date getDthrinialerta() {
		return this.dthrinialerta;
	}

	public void setDthrinialerta(Date dthrinialerta) {
		this.dthrinialerta = dthrinialerta;
	}

	@Column(name = "MSDTHRINIALERTA", nullable = false, precision = 126, scale = 0)
	public double getMsdthrinialerta() {
		return this.msdthrinialerta;
	}

	public void setMsdthrinialerta(double msdthrinialerta) {
		this.msdthrinialerta = msdthrinialerta;
	}

	@Column(name = "TPALERTA")
	public void setTpalerta(Integer tpalerta) {
		this.tpalerta = tpalerta;
	}

	public Integer getTpalerta() {
		return tpalerta;
	}

}
