package injetws.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrUpConfiguracoes generated by hbm2java
 */
@Entity
@Table(name="PR_UP_CONFIGURACOES"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDUP", "IDEVENTOMASTERBRIDGECOLLECTODB"}) 
)
public class PrUpConfiguracoes  implements java.io.Serializable {

     /**
	 * 
	 */
	private static final long serialVersionUID = 5922410472916504188L;
	private String idconfiguracaoup;
     private PrEventosBridgeCollecDb prEventosBridgeCollecDb;
     private PrUp prUp;
     private String idregsubcoletor;
     private String cfgtpsessaoproducao;
     private Double cfgtamanhoumpacoteciclos;
     private Double cfgperctmpcicloparauto;
     private Character cfginterrupcaociclo;
     private Double cfgperctmpcicloinicializacao;
     private Double cfgperctoleranciasinalciclo;
     private Double cfgdbc;
     private Double tmpciclopadrao;
     private Double cfgtolertmpcicloparauto;
//     private Double cfgtolertmpcicloparauto2;

    public PrUpConfiguracoes() {
    }

    @Id 
    @Column(name="IDCONFIGURACAOUP", unique=true, nullable=false, length=36)
    public String getIdconfiguracaoup() {
        return this.idconfiguracaoup;
    }
    
    public void setIdconfiguracaoup(String idconfiguracaoup) {
        this.idconfiguracaoup = idconfiguracaoup;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDEVENTOMASTERBRIDGECOLLECTODB", nullable=false)
    public PrEventosBridgeCollecDb getPrEventosBridgeCollecDb() {
        return this.prEventosBridgeCollecDb;
    }
    
    public void setPrEventosBridgeCollecDb(PrEventosBridgeCollecDb prEventosBridgeCollecDb) {
        this.prEventosBridgeCollecDb = prEventosBridgeCollecDb;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUP", nullable=false)
    public PrUp getPrUp() {
        return this.prUp;
    }
    
    public void setPrUp(PrUp prUp) {
        this.prUp = prUp;
    }

    
    @Column(name="IDREGSUBCOLETOR", length=36)
    public String getIdregsubcoletor() {
        return this.idregsubcoletor;
    }
    
    public void setIdregsubcoletor(String idregsubcoletor) {
        this.idregsubcoletor = idregsubcoletor;
    }

    
    @Column(name="CFGTPSESSAOPRODUCAO")
    public String getCfgtpsessaoproducao() {
        return this.cfgtpsessaoproducao;
    }
    
    public void setCfgtpsessaoproducao(String cfgtpsessaoproducao) {
        this.cfgtpsessaoproducao = cfgtpsessaoproducao;
    }

    
    @Column(name="CFGTAMANHOUMPACOTECICLOS", precision=126, scale=0)
    public Double getCfgtamanhoumpacoteciclos() {
        return this.cfgtamanhoumpacoteciclos;
    }
    
    public void setCfgtamanhoumpacoteciclos(Double cfgtamanhoumpacoteciclos) {
        this.cfgtamanhoumpacoteciclos = cfgtamanhoumpacoteciclos;
    }

    
    @Column(name="CFGPERCTMPCICLOPARAUTO", precision=126, scale=0)
    public Double getCfgperctmpcicloparauto() {
        return this.cfgperctmpcicloparauto;
    }
    
    public void setCfgperctmpcicloparauto(Double cfgperctmpcicloparauto) {
        this.cfgperctmpcicloparauto = cfgperctmpcicloparauto;
    }

    
    @Column(name="CFGINTERRUPCAOCICLO")
    public Character getCfginterrupcaociclo() {
        return this.cfginterrupcaociclo;
    }
    
    public void setCfginterrupcaociclo(Character cfginterrupcaociclo) {
        this.cfginterrupcaociclo = cfginterrupcaociclo;
    }

    
    @Column(name="CFGPERCTMPCICLOINICIALIZACAO", precision=126, scale=0)
    public Double getCfgperctmpcicloinicializacao() {
        return this.cfgperctmpcicloinicializacao;
    }
    
    public void setCfgperctmpcicloinicializacao(Double cfgperctmpcicloinicializacao) {
        this.cfgperctmpcicloinicializacao = cfgperctmpcicloinicializacao;
    }

    
    @Column(name="CFGPERCTOLERANCIASINALCICLO", precision=126, scale=0)
    public Double getCfgperctoleranciasinalciclo() {
        return this.cfgperctoleranciasinalciclo;
    }
    
    public void setCfgperctoleranciasinalciclo(Double cfgperctoleranciasinalciclo) {
        this.cfgperctoleranciasinalciclo = cfgperctoleranciasinalciclo;
    }

    
    @Column(name="CFGDBC", precision=126, scale=0)
    public Double getCfgdbc() {
        return this.cfgdbc;
    }
    
    public void setCfgdbc(Double cfgdbc) {
        this.cfgdbc = cfgdbc;
    }

    
    @Column(name="TMPCICLOPADRAO", precision=126, scale=0)
    public Double getTmpciclopadrao() {
        return this.tmpciclopadrao;
    }
    
    public void setTmpciclopadrao(Double tmpciclopadrao) {
        this.tmpciclopadrao = tmpciclopadrao;
    }

    
    @Column(name="CFGTOLERTMPCICLOPARAUTO", precision=126, scale=0)
    public Double getCfgtolertmpcicloparauto() {
        return this.cfgtolertmpcicloparauto;
    }
    
    public void setCfgtolertmpcicloparauto(Double cfgtolertmpcicloparauto) {
        this.cfgtolertmpcicloparauto = cfgtolertmpcicloparauto;
    }

    
//    @Column(name="CFGTOLERTMPCICLOPARAUTO2", precision=126, scale=0)
//    public Double getCfgtolertmpcicloparauto2() {
//        return this.cfgtolertmpcicloparauto2;
//    }
//    
//    public void setCfgtolertmpcicloparauto2(Double cfgtolertmpcicloparauto2) {
//        this.cfgtolertmpcicloparauto2 = cfgtolertmpcicloparauto2;
//    }
//
//

}


