package injetws.model.pojos;

// default package
// Generated 15/01/2010 14:33:32 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrUpParadasEmAberto generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_PARADAS_EM_ABERTO")
public class PrUpParadasEmAberto implements java.io.Serializable {

	private PrUpParadasEmAbertoId id;
	private PrUpOpsEmAberto prUpOpsEmAberto;
	private Date dthriparada;
	private double msdthriparada;
	private String cdparada;

	public PrUpParadasEmAberto() {
	}

	public PrUpParadasEmAberto(PrUpParadasEmAbertoId id,
			PrUpOpsEmAberto prUpOpsEmAberto, Date dthriparada,
			double msdthriparada) {
		this.id = id;
		this.prUpOpsEmAberto = prUpOpsEmAberto;
		this.dthriparada = dthriparada;
		this.msdthriparada = msdthriparada;
	}

	public PrUpParadasEmAberto(PrUpParadasEmAbertoId id,
			PrUpOpsEmAberto prUpOpsEmAberto, Date dthriparada,
			double msdthriparada, String cdparada) {
		this.id = id;
		this.prUpOpsEmAberto = prUpOpsEmAberto;
		this.dthriparada = dthriparada;
		this.msdthriparada = msdthriparada;
		this.cdparada = cdparada;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idup", column = @Column(name = "IDUP", nullable = false, length = 36)),
			@AttributeOverride(name = "idopemaberto", column = @Column(name = "IDOPEMABERTO", nullable = false, length = 36)) })
	public PrUpParadasEmAbertoId getId() {
		return this.id;
	}

	public void setId(PrUpParadasEmAbertoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDOPEMABERTO", nullable = false, insertable = false, updatable = false)
	public PrUpOpsEmAberto getPrUpOpsEmAberto() {
		return this.prUpOpsEmAberto;
	}

	public void setPrUpOpsEmAberto(PrUpOpsEmAberto prUpOpsEmAberto) {
		this.prUpOpsEmAberto = prUpOpsEmAberto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHRIPARADA", nullable = false, length = 7)
	public Date getDthriparada() {
		return this.dthriparada;
	}

	public void setDthriparada(Date dthriparada) {
		this.dthriparada = dthriparada;
	}

	@Column(name = "MSDTHRIPARADA", nullable = false, precision = 126, scale = 0)
	public double getMsdthriparada() {
		return this.msdthriparada;
	}

	public void setMsdthriparada(double msdthriparada) {
		this.msdthriparada = msdthriparada;
	}

	@Column(name = "CDPARADA", length = 6)
	public String getCdparada() {
		return this.cdparada;
	}

	public void setCdparada(String cdparada) {
		this.cdparada = cdparada;
	}

}
