package injetws.model.pojos;

// default package
// Generated 15/01/2010 14:33:32 by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrUpOpsEmAbertoProd generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_OPS_EM_ABERTO_PROD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDOPEMABERTO", "CDPRODUTO" }))
public class PrUpOpsEmAbertoProd implements java.io.Serializable {

	private PrUpOpsEmAbertoProdId id;
	private PrUpOpsEmAberto prUpOpsEmAberto;

	public PrUpOpsEmAbertoProd() {
	}

	public PrUpOpsEmAbertoProd(PrUpOpsEmAbertoProdId id,
			PrUpOpsEmAberto prUpOpsEmAberto) {
		this.id = id;
		this.prUpOpsEmAberto = prUpOpsEmAberto;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idopemaberto", column = @Column(name = "IDOPEMABERTO", nullable = false, length = 36)),
			@AttributeOverride(name = "cdproduto", column = @Column(name = "CDPRODUTO", nullable = false, length = 20)),
			@AttributeOverride(name = "idreduzidaproduto", column = @Column(name = "IDREDUZIDAPRODUTO", nullable = false, length = 1)),
			@AttributeOverride(name = "qtplan", column = @Column(name = "QTPLAN", precision = 126, scale = 0)),
			@AttributeOverride(name = "qtprodliqanterior", column = @Column(name = "QTPRODLIQANTERIOR", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "siglaumprodliqanterior", column = @Column(name = "SIGLAUMPRODLIQANTERIOR", length = 10)) })
	public PrUpOpsEmAbertoProdId getId() {
		return this.id;
	}

	public void setId(PrUpOpsEmAbertoProdId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDOPEMABERTO", nullable = false, insertable = false, updatable = false)
	public PrUpOpsEmAberto getPrUpOpsEmAberto() {
		return this.prUpOpsEmAberto;
	}

	public void setPrUpOpsEmAberto(PrUpOpsEmAberto prUpOpsEmAberto) {
		this.prUpOpsEmAberto = prUpOpsEmAberto;
	}

}
