package injetws.model.pojos;

// default package
// Generated 08/03/2010 15:46:01 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrUpAndonConfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_ANDON_CONFIG", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDUP", "IDEVENTOANDON" }))
public class PrUpAndonConfig implements java.io.Serializable {

	private String idconfigandon;
	private PrEventosBridgeCollecDb prEventosBridgeCollecDb;
	private PrUp prUp;
	private double ideventoandon;
	private BigDecimal tpeventoandon;
	private BigDecimal idrele;
	private String idreleaux;
	private BigDecimal prioridade;
	private BigDecimal stintermitente;
	private BigDecimal tmpsinalalto;
	private BigDecimal tmpsinalbaixo;
	private BigDecimal stativo;
	private BigDecimal stexclusao;
	private Set<PrUpAndonConfigArg> prUpAndonConfigArgs = new HashSet<PrUpAndonConfigArg>(
			0);

	public PrUpAndonConfig() {
	}

	public PrUpAndonConfig(String idconfigandon,
			PrEventosBridgeCollecDb prEventosBridgeCollecDb, PrUp prUp,
			double ideventoandon, BigDecimal tpeventoandon, BigDecimal idrele,
			BigDecimal prioridade, BigDecimal stintermitente,
			BigDecimal stativo, BigDecimal stexclusao) {
		this.idconfigandon = idconfigandon;
		this.prEventosBridgeCollecDb = prEventosBridgeCollecDb;
		this.prUp = prUp;
		this.ideventoandon = ideventoandon;
		this.tpeventoandon = tpeventoandon;
		this.idrele = idrele;
		this.prioridade = prioridade;
		this.stintermitente = stintermitente;
		this.stativo = stativo;
		this.stexclusao = stexclusao;
	}

	public PrUpAndonConfig(String idconfigandon,
			PrEventosBridgeCollecDb prEventosBridgeCollecDb, PrUp prUp,
			double ideventoandon, BigDecimal tpeventoandon, BigDecimal idrele,
			String idreleaux, BigDecimal prioridade, BigDecimal stintermitente,
			BigDecimal tmpsinalalto, BigDecimal tmpsinalbaixo,
			BigDecimal stativo, BigDecimal stexclusao,
			Set<PrUpAndonConfigArg> prUpAndonConfigArgs) {
		this.idconfigandon = idconfigandon;
		this.prEventosBridgeCollecDb = prEventosBridgeCollecDb;
		this.prUp = prUp;
		this.ideventoandon = ideventoandon;
		this.tpeventoandon = tpeventoandon;
		this.idrele = idrele;
		this.idreleaux = idreleaux;
		this.prioridade = prioridade;
		this.stintermitente = stintermitente;
		this.tmpsinalalto = tmpsinalalto;
		this.tmpsinalbaixo = tmpsinalbaixo;
		this.stativo = stativo;
		this.stexclusao = stexclusao;
		this.prUpAndonConfigArgs = prUpAndonConfigArgs;
	}

	@Id
	@Column(name = "IDCONFIGANDON", unique = true, nullable = false, length = 36)
	public String getIdconfigandon() {
		return this.idconfigandon;
	}

	public void setIdconfigandon(String idconfigandon) {
		this.idconfigandon = idconfigandon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDEVENTOMASTERBRIDGECOLLECTODB", nullable = false)
	public PrEventosBridgeCollecDb getPrEventosBridgeCollecDb() {
		return this.prEventosBridgeCollecDb;
	}

	public void setPrEventosBridgeCollecDb(
			PrEventosBridgeCollecDb prEventosBridgeCollecDb) {
		this.prEventosBridgeCollecDb = prEventosBridgeCollecDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUP", nullable = false)
	public PrUp getPrUp() {
		return this.prUp;
	}

	public void setPrUp(PrUp prUp) {
		this.prUp = prUp;
	}

	@Column(name = "IDEVENTOANDON", nullable = false, precision = 126, scale = 0)
	public double getIdeventoandon() {
		return this.ideventoandon;
	}

	public void setIdeventoandon(double ideventoandon) {
		this.ideventoandon = ideventoandon;
	}

	@Column(name = "TPEVENTOANDON", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTpeventoandon() {
		return this.tpeventoandon;
	}

	public void setTpeventoandon(BigDecimal tpeventoandon) {
		this.tpeventoandon = tpeventoandon;
	}

	@Column(name = "IDRELE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdrele() {
		return this.idrele;
	}

	public void setIdrele(BigDecimal idrele) {
		this.idrele = idrele;
	}

	@Column(name = "IDRELEAUX", length = 20)
	public String getIdreleaux() {
		return this.idreleaux;
	}

	public void setIdreleaux(String idreleaux) {
		this.idreleaux = idreleaux;
	}

	@Column(name = "PRIORIDADE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(BigDecimal prioridade) {
		this.prioridade = prioridade;
	}

	@Column(name = "STINTERMITENTE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStintermitente() {
		return this.stintermitente;
	}

	public void setStintermitente(BigDecimal stintermitente) {
		this.stintermitente = stintermitente;
	}

	@Column(name = "TMPSINALALTO", precision = 22, scale = 0)
	public BigDecimal getTmpsinalalto() {
		return this.tmpsinalalto;
	}

	public void setTmpsinalalto(BigDecimal tmpsinalalto) {
		this.tmpsinalalto = tmpsinalalto;
	}

	@Column(name = "TMPSINALBAIXO", precision = 22, scale = 0)
	public BigDecimal getTmpsinalbaixo() {
		return this.tmpsinalbaixo;
	}

	public void setTmpsinalbaixo(BigDecimal tmpsinalbaixo) {
		this.tmpsinalbaixo = tmpsinalbaixo;
	}

	@Column(name = "STATIVO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStativo() {
		return this.stativo;
	}

	public void setStativo(BigDecimal stativo) {
		this.stativo = stativo;
	}

	@Column(name = "STEXCLUSAO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStexclusao() {
		return this.stexclusao;
	}

	public void setStexclusao(BigDecimal stexclusao) {
		this.stexclusao = stexclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prUpAndonConfig")
	public Set<PrUpAndonConfigArg> getPrUpAndonConfigArgs() {
		return this.prUpAndonConfigArgs;
	}

	public void setPrUpAndonConfigArgs(
			Set<PrUpAndonConfigArg> prUpAndonConfigArgs) {
		this.prUpAndonConfigArgs = prUpAndonConfigArgs;
	}

}
