package injetws.model.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

// default package
// Generated 28/12/2010 09:46:53 by Hibernate Tools 3.3.0.GA

/**
 * PrUpProdutoMatPrimaValid generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_PRODUTO_MAT_PRIMA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IDUP", "CDPRODUTO","CDMATERIAPRIMA" }))
public class PrUpProdutoMatPrima implements java.io.Serializable {

	private String idprodutomatprima;
	private PrUp prUp;
	private String cdproduto;
	private String dsmateriaprima;
	private String cdmateriaprima;
	private String unidade;
	private char controlalote;
	private String cdestoque;
	private String nrlote;

	public PrUpProdutoMatPrima() {
	}

	public PrUpProdutoMatPrima(String idprodutomatprima, PrUp prUp,
			String cdproduto, String cdmateriaprima, String unidade, char controlalote,
			String dsmateriaprima, String cdestoque, String nrlote) {
		this.idprodutomatprima = idprodutomatprima;
		this.prUp = prUp;
		this.cdproduto = cdproduto;
		this.cdmateriaprima = cdmateriaprima;
		this.dsmateriaprima = dsmateriaprima;
		this.unidade = unidade;
		this.controlalote = controlalote;
		this.cdestoque = cdestoque;
		this.nrlote = nrlote;
	}

	@Id
	@Column(name = "IDPRODUTOMATPRIMA", unique = true, nullable = false, length = 36)
	public String getIdprodutomatprima() {
		return this.idprodutomatprima;
	}

	public void setIdprodutomatprima(String idprodutomatprima) {
		this.idprodutomatprima = idprodutomatprima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUP", nullable = false)
	public PrUp getPrUp() {
		return this.prUp;
	}

	public void setPrUp(PrUp prUp) {
		this.prUp = prUp;
	}

	@Column(name = "CDPRODUTO", nullable = false, length = 20)
	public String getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(String cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "CDMATERIAPRIMA", nullable = false, length = 30)
	public String getCdmateriaprima() {
		return this.cdmateriaprima;
	}

	public void setCdmateriaprima(String cdmateriaprima) {
		this.cdmateriaprima = cdmateriaprima;
	}
	
	@Column(name = "DSMATERIAPRIMA", nullable = false, length = 40)
	public String getDsmateriaprima() {
		return this.dsmateriaprima;
	}

	public void setDsmateriaprima(String dsmateriaprima) {
		this.dsmateriaprima = dsmateriaprima;
	}

	@Column(name = "UNIDADE", nullable = false, length = 10)
	public String getUnidade() {
		return this.unidade;
	}

	public void setUnidade(String unidade) {
		this.unidade = unidade;
	}

	@Column(name = "CONTROLALOTE", nullable = false, length = 1)
	public char getControlalote() {
		return controlalote;
	}
	
	public void setControlalote(char controlalote) {
		this.controlalote = controlalote;
	}
	
	@Column(name = "CDESTOQUE", length = 8)
	public String getCdestoque() {
		return this.cdestoque;
	}

	public void setCdestoque(String cdestoque) {
		this.cdestoque = cdestoque;
	}

	@Column(name = "NRLOTE", length = 30)
	public String getNrlote() {
		return this.nrlote;
	}

	public void setNrlote(String nrlote) {
		this.nrlote = nrlote;
	}

}
