package injetws.model.pojos;

// default package
// Generated 17/03/2010 09:39:07 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrUpCtrlExecinspecao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PR_UP_CTRL_EXECINSPECAO")
public class PrUpCtrlExecinspecao implements java.io.Serializable {

	private String idup;
	private String idInspecao;
	private Set<PrUpExecinspecao> prUpExecinspecaos = new HashSet<PrUpExecinspecao>(
			0);

	public PrUpCtrlExecinspecao() {
	}

	public PrUpCtrlExecinspecao(String idup, String idInspecao) {
		this.idup = idup;
		this.idInspecao = idInspecao;
	}

	public PrUpCtrlExecinspecao(String idup, String idInspecao,
			Set<PrUpExecinspecao> prUpExecinspecaos) {
		this.idup = idup;
		this.idInspecao = idInspecao;
		this.prUpExecinspecaos = prUpExecinspecaos;
	}

	@Id
	@Column(name = "IDUP", unique = true, nullable = false, length = 36)
	public String getIdup() {
		return this.idup;
	}

	public void setIdup(String idup) {
		this.idup = idup;
	}

	@Column(name = "IdInspecao", nullable = false, length = 12)
	public String getIdInspecao() {
		return this.idInspecao;
	}

	public void setIdInspecao(String idInspecao) {
		this.idInspecao = idInspecao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prUpCtrlExecinspecao")
	public Set<PrUpExecinspecao> getPrUpExecinspecaos() {
		return this.prUpExecinspecaos;
	}

	public void setPrUpExecinspecaos(Set<PrUpExecinspecao> prUpExecinspecaos) {
		this.prUpExecinspecaos = prUpExecinspecaos;
	}

}
