package idw.model.pojos.cck;

// default package
// Generated Jan 13, 2014 10:43:45 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supervisao generated by hbm2java
 */
@Entity
@Table(name = "supervisao", catalog = "CCK")
public class Supervisao implements java.io.Serializable {

	private int idMedicao;
	private String versaoSoft;
	private String numeroSerie;
	private Short segIntervalo;
	private Byte posto;
	private Byte periodo;
	private Byte erroCom;
	private Date datahora;
	private Double instantanea;
	private Double ativo;
	private Double reativo;
	private Double fp;
	private Double correnteMedia;
	private Double correnteTotal;
	private Double potenciaR;
	private Double potenciaS;
	private Double potenciaT;
	private Double fpR;
	private Double fpS;
	private Double fpT;
	private Double correnteR;
	private Double correnteS;
	private Double correnteT;
	private Double tensaoR;
	private Double tensaoS;
	private Double tensaoT;

	public Supervisao() {
	}

	public Supervisao(int idMedicao) {
		this.idMedicao = idMedicao;
	}

	public Supervisao(int idMedicao, String versaoSoft, String numeroSerie,
			Short segIntervalo, Byte posto, Byte periodo, Byte erroCom,
			Date datahora, Double instantanea, Double ativo, Double reativo,
			Double fp, Double correnteMedia, Double correnteTotal,
			Double potenciaR, Double potenciaS, Double potenciaT, Double fpR,
			Double fpS, Double fpT, Double correnteR, Double correnteS,
			Double correnteT, Double tensaoR, Double tensaoS, Double tensaoT) {
		this.idMedicao = idMedicao;
		this.versaoSoft = versaoSoft;
		this.numeroSerie = numeroSerie;
		this.segIntervalo = segIntervalo;
		this.posto = posto;
		this.periodo = periodo;
		this.erroCom = erroCom;
		this.datahora = datahora;
		this.instantanea = instantanea;
		this.ativo = ativo;
		this.reativo = reativo;
		this.fp = fp;
		this.correnteMedia = correnteMedia;
		this.correnteTotal = correnteTotal;
		this.potenciaR = potenciaR;
		this.potenciaS = potenciaS;
		this.potenciaT = potenciaT;
		this.fpR = fpR;
		this.fpS = fpS;
		this.fpT = fpT;
		this.correnteR = correnteR;
		this.correnteS = correnteS;
		this.correnteT = correnteT;
		this.tensaoR = tensaoR;
		this.tensaoS = tensaoS;
		this.tensaoT = tensaoT;
	}

	@Id
	@Column(name = "id_medicao", unique = true, nullable = false)
	public int getIdMedicao() {
		return this.idMedicao;
	}

	public void setIdMedicao(int idMedicao) {
		this.idMedicao = idMedicao;
	}

	@Column(name = "versao_soft", length = 20)
	public String getVersaoSoft() {
		return this.versaoSoft;
	}

	public void setVersaoSoft(String versaoSoft) {
		this.versaoSoft = versaoSoft;
	}

	@Column(name = "numero_serie", length = 20)
	public String getNumeroSerie() {
		return this.numeroSerie;
	}

	public void setNumeroSerie(String numeroSerie) {
		this.numeroSerie = numeroSerie;
	}

	@Column(name = "seg_intervalo")
	public Short getSegIntervalo() {
		return this.segIntervalo;
	}

	public void setSegIntervalo(Short segIntervalo) {
		this.segIntervalo = segIntervalo;
	}

	@Column(name = "posto")
	public Byte getPosto() {
		return this.posto;
	}

	public void setPosto(Byte posto) {
		this.posto = posto;
	}

	@Column(name = "periodo")
	public Byte getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Byte periodo) {
		this.periodo = periodo;
	}

	@Column(name = "erro_com")
	public Byte getErroCom() {
		return this.erroCom;
	}

	public void setErroCom(Byte erroCom) {
		this.erroCom = erroCom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datahora", length = 23)
	public Date getDatahora() {
		return this.datahora;
	}

	public void setDatahora(Date datahora) {
		this.datahora = datahora;
	}

	@Column(name = "instantanea", precision = 53, scale = 0)
	public Double getInstantanea() {
		return this.instantanea;
	}

	public void setInstantanea(Double instantanea) {
		this.instantanea = instantanea;
	}

	@Column(name = "ativo", precision = 53, scale = 0)
	public Double getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Double ativo) {
		this.ativo = ativo;
	}

	@Column(name = "reativo", precision = 53, scale = 0)
	public Double getReativo() {
		return this.reativo;
	}

	public void setReativo(Double reativo) {
		this.reativo = reativo;
	}

	@Column(name = "fp", precision = 53, scale = 0)
	public Double getFp() {
		return this.fp;
	}

	public void setFp(Double fp) {
		this.fp = fp;
	}

	@Column(name = "corrente_media", precision = 53, scale = 0)
	public Double getCorrenteMedia() {
		return this.correnteMedia;
	}

	public void setCorrenteMedia(Double correnteMedia) {
		this.correnteMedia = correnteMedia;
	}

	@Column(name = "corrente_total", precision = 53, scale = 0)
	public Double getCorrenteTotal() {
		return this.correnteTotal;
	}

	public void setCorrenteTotal(Double correnteTotal) {
		this.correnteTotal = correnteTotal;
	}

	@Column(name = "potencia_r", precision = 53, scale = 0)
	public Double getPotenciaR() {
		return this.potenciaR;
	}

	public void setPotenciaR(Double potenciaR) {
		this.potenciaR = potenciaR;
	}

	@Column(name = "potencia_s", precision = 53, scale = 0)
	public Double getPotenciaS() {
		return this.potenciaS;
	}

	public void setPotenciaS(Double potenciaS) {
		this.potenciaS = potenciaS;
	}

	@Column(name = "potencia_t", precision = 53, scale = 0)
	public Double getPotenciaT() {
		return this.potenciaT;
	}

	public void setPotenciaT(Double potenciaT) {
		this.potenciaT = potenciaT;
	}

	@Column(name = "fp_r", precision = 53, scale = 0)
	public Double getFpR() {
		return this.fpR;
	}

	public void setFpR(Double fpR) {
		this.fpR = fpR;
	}

	@Column(name = "fp_s", precision = 53, scale = 0)
	public Double getFpS() {
		return this.fpS;
	}

	public void setFpS(Double fpS) {
		this.fpS = fpS;
	}

	@Column(name = "fp_t", precision = 53, scale = 0)
	public Double getFpT() {
		return this.fpT;
	}

	public void setFpT(Double fpT) {
		this.fpT = fpT;
	}

	@Column(name = "corrente_r", precision = 53, scale = 0)
	public Double getCorrenteR() {
		return this.correnteR;
	}

	public void setCorrenteR(Double correnteR) {
		this.correnteR = correnteR;
	}

	@Column(name = "corrente_s", precision = 53, scale = 0)
	public Double getCorrenteS() {
		return this.correnteS;
	}

	public void setCorrenteS(Double correnteS) {
		this.correnteS = correnteS;
	}

	@Column(name = "corrente_t", precision = 53, scale = 0)
	public Double getCorrenteT() {
		return this.correnteT;
	}

	public void setCorrenteT(Double correnteT) {
		this.correnteT = correnteT;
	}

	@Column(name = "tensao_r", precision = 53, scale = 0)
	public Double getTensaoR() {
		return this.tensaoR;
	}

	public void setTensaoR(Double tensaoR) {
		this.tensaoR = tensaoR;
	}

	@Column(name = "tensao_s", precision = 53, scale = 0)
	public Double getTensaoS() {
		return this.tensaoS;
	}

	public void setTensaoS(Double tensaoS) {
		this.tensaoS = tensaoS;
	}

	@Column(name = "tensao_t", precision = 53, scale = 0)
	public Double getTensaoT() {
		return this.tensaoT;
	}

	public void setTensaoT(Double tensaoT) {
		this.tensaoT = tensaoT;
	}

}
