package idw.model.pojos.agramkow;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Areas generated by hbm2java
 */
@Entity
@Table(name = "AREAS")
public class Areas implements java.io.Serializable  {

	private AreasId id;
	private Servers servers;
	private String name;
	private String note;
	private Byte deleted;
	private Set<ResultsHeader> resultsHeaders = new HashSet<ResultsHeader>(0);

	public Areas() {
	}

	public Areas(AreasId id, Servers servers, String name, Byte deleted) {
		this.id = id;
		this.servers = servers;
		this.name = name;
		this.deleted = deleted;
	}

	public Areas(AreasId id, Servers servers, String name,
			String note, Byte deleted, Set<ResultsHeader> resultsHeaders) {
		this.id = id;
		this.servers = servers;
		this.name = name;
		this.note = note;
		this.deleted = deleted;
		this.resultsHeaders = resultsHeaders;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "areaId", column = @Column(name = "AREA_ID", nullable = false)),
			@AttributeOverride(name = "server", column = @Column(name = "SERVER", nullable = false)) })
	public AreasId getId() {
		return this.id;
	}

	public void setId(AreasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVER", nullable = false, insertable = false, updatable = false)
	public Servers getServers() {
		return this.servers;
	}

	public void setServers(Servers servers) {
		this.servers = servers;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "DELETED", nullable = false)
	public Byte getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Byte deleted) {
		this.deleted = deleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areas")
	public Set<ResultsHeader> getResultsHeaders() {
		return this.resultsHeaders;
	}

	public void setResultsHeaders(Set<ResultsHeader> resultsHeaders) {
		this.resultsHeaders = resultsHeaders;
	}

}
