package idw.model.pojos.agramkow;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Failcodes generated by hbm2java
 */
@Entity
@Table(name = "FAILCODES")
public class Failcodes implements java.io.Serializable {

	private FailcodesId id;
	private Servers servers;
	private Devices devices;
	private String descriptor;
	private String note;
	private String barcode;
	private Integer typeId;
	private Byte faillevel;
	private String createdBy;
	private Date createdDate;
	private String changedBy;
	private Date changedDate;
	private Byte deleted;
	private Byte[] image;
	private Byte codeType;
	private Set<ResultsHeader> resultsHeaders = new HashSet<ResultsHeader>(0);
	private Set<FailcodeLanguages> failcodeLanguageses = new HashSet<FailcodeLanguages>(
			0);

	public Failcodes() {
	}

	public Failcodes(FailcodesId id, Servers servers, Devices devices,
			String descriptor, Integer typeId, Byte faillevel,
			Date createdDate, Date changedDate, Byte deleted, Byte codeType) {
		this.id = id;
		this.servers = servers;
		this.devices = devices;
		this.descriptor = descriptor;
		this.typeId = typeId;
		this.faillevel = faillevel;
		this.createdDate = createdDate;
		this.changedDate = changedDate;
		this.deleted = deleted;
		this.codeType = codeType;
	}

	public Failcodes(FailcodesId id, Servers servers, Devices devices,
			String descriptor, String note, String barcode,
			Integer typeId, Byte faillevel, String createdBy,
			Date createdDate, String changedBy, Date changedDate,
			Byte deleted, Byte[] image, Byte codeType,
			Set<ResultsHeader> resultsHeaders,
			Set<FailcodeLanguages> failcodeLanguageses) {
		this.id = id;
		this.servers = servers;
		this.devices = devices;
		this.descriptor = descriptor;
		this.note = note;
		this.barcode = barcode;
		this.typeId = typeId;
		this.faillevel = faillevel;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.changedBy = changedBy;
		this.changedDate = changedDate;
		this.deleted = deleted;
		this.image = image;
		this.codeType = codeType;
		this.resultsHeaders = resultsHeaders;
		this.failcodeLanguageses = failcodeLanguageses;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "deviceId", column = @Column(name = "DEVICE_ID", nullable = false)),
			@AttributeOverride(name = "server", column = @Column(name = "SERVER", nullable = false)) })
	public FailcodesId getId() {
		return this.id;
	}

	public void setId(FailcodesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVER", nullable = false, insertable = false, updatable = false)
	public Servers getServers() {
		return this.servers;
	}

	public void setServers(Servers servers) {
		this.servers = servers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEVICE_ID", nullable = false, insertable = false, updatable = false)
	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	@Column(name = "DESCRIPTOR", nullable = false)
	public String getDescriptor() {
		return this.descriptor;
	}

	public void setDescriptor(String descriptor) {
		this.descriptor = descriptor;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "BARCODE")
	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	@Column(name = "TYPE_ID", nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "FAILLEVEL", nullable = false)
	public Byte getFaillevel() {
		return this.faillevel;
	}

	public void setFaillevel(Byte faillevel) {
		this.faillevel = faillevel;
	}

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CHANGED_BY")
	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHANGED_DATE", nullable = false, length = 23)
	public Date getChangedDate() {
		return this.changedDate;
	}

	public void setChangedDate(Date changedDate) {
		this.changedDate = changedDate;
	}

	@Column(name = "DELETED", nullable = false)
	public Byte getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Byte deleted) {
		this.deleted = deleted;
	}

	@Column(name = "IMAGE")
	public Byte[] getImage() {
		return this.image;
	}

	public void setImage(Byte[] image) {
		this.image = image;
	}

	@Column(name = "CODE_TYPE", nullable = false)
	public Byte getCodeType() {
		return this.codeType;
	}

	public void setCodeType(Byte codeType) {
		this.codeType = codeType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "failcodes")
	public Set<ResultsHeader> getResultsHeaders() {
		return this.resultsHeaders;
	}

	public void setResultsHeaders(Set<ResultsHeader> resultsHeaders) {
		this.resultsHeaders = resultsHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "failcodes")
	public Set<FailcodeLanguages> getFailcodeLanguageses() {
		return this.failcodeLanguageses;
	}

	public void setFailcodeLanguageses(
			Set<FailcodeLanguages> failcodeLanguageses) {
		this.failcodeLanguageses = failcodeLanguageses;
	}

}
