package idw.model.pojos.agramkow;

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FailcodeLanguages generated by hbm2java
 */
@Entity
@Table(name = "FAILCODE_LANGUAGES")
public class FailcodeLanguages implements java.io.Serializable {//

	private FailcodeLanguagesId id;
	private Failcodes failcodes;
	private String descriptor;
	private String note;

	public FailcodeLanguages() {
	}

	public FailcodeLanguages(FailcodeLanguagesId id, Failcodes failcodes,
			String descriptor) {
		this.id = id;
		this.failcodes = failcodes;
		this.descriptor = descriptor;
	}

	public FailcodeLanguages(FailcodeLanguagesId id, Failcodes failcodes,
			String descriptor, String note) {
		this.id = id;
		this.failcodes = failcodes;
		this.descriptor = descriptor;
		this.note = note;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "failcodeId", column = @Column(name = "FAILCODE_ID", nullable = false)),
			@AttributeOverride(name = "deviceId", column = @Column(name = "DEVICE_ID", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "LANGUAGE_ID", nullable = false)),
			@AttributeOverride(name = "server", column = @Column(name = "SERVER", nullable = false)) })
	public FailcodeLanguagesId getId() {
		return this.id;
	}

	public void setId(FailcodeLanguagesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "FAILCODE_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "DEVICE_ID", referencedColumnName = "DEVICE_ID", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SERVER", referencedColumnName = "SERVER", nullable = false, insertable = false, updatable = false) })
	public Failcodes getFailcodes() {
		return this.failcodes;
	}

	public void setFailcodes(Failcodes failcodes) {
		this.failcodes = failcodes;
	}

	@Column(name = "DESCRIPTOR", nullable = false)
	public String getDescriptor() {
		return this.descriptor;
	}

	public void setDescriptor(String descriptor) {
		this.descriptor = descriptor;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
